OpenCAEPoro: ParamOutput Class Reference
ParamOutput Class Reference
#include <ParamOutput.hpp>
Public Member Functions
void InputSUMMARY (ifstream &ifs)
void InputType_A (ifstream &ifs, Type_A_o &obj)
void InputType_B (ifstream &ifs, Type_B_o &obj)
void InputRPTSCHED (ifstream &ifs)
Public Attributes
OutputSummary summary
See OutputSummary.
OutputDetail detailInfo
See OutputDetail.
Detailed Description
ParamOutput is an internal structure used to stores the information of outputting from input files. It is an intermediate interface and independent of the main simulator. After all file inputting finishs, the params in it will pass to corresponding modules.
Definition at line 122 of file ParamOutput.hpp.
Member Function Documentation
InputRPTSCHED()
void ParamOutput::InputRPTSCHED (ifstream & ifs)
Input the keyword RPTSCHED, which tells which detailed information will be output to the RPTfile.
Definition at line 183 of file ParamOutput.cpp.
 {
     vector<string> vbuf;
     while (ReadLine(ifs, vbuf)) {
         if (vbuf[0] == "/") break;
         USI len = vbuf.size();
         for (USI i = 0; i < len; i++) {
             string keyword = vbuf[i];
             switch (Map_Str2Int(&keyword[0], keyword.size())) {
                 case Map_Str2Int("PRES", 4):
                 case Map_Str2Int("PRESSURE", 8):
                     detailInfo.PRE = true;
                     break;
                 case Map_Str2Int("PGAS", 4):
                     detailInfo.PGAS = true;
                     break;
                 case Map_Str2Int("PWAT", 4):
                     detailInfo.PWAT = true;
                     break;
                 case Map_Str2Int("SOIL", 4):
                     detailInfo.SOIL = true;
                     break;
                 case Map_Str2Int("SGAS", 4):
                     detailInfo.SGAS = true;
                     break;
                 case Map_Str2Int("SWAT", 4):
                     detailInfo.SWAT = true;
                     break;
                 case Map_Str2Int("DENO", 4):
                     detailInfo.DENO = true;
                     break;
                 case Map_Str2Int("DENG", 4):
                     detailInfo.DENG = true;
                     break;
                 case Map_Str2Int("DENW", 4):
                     detailInfo.DENW = true;
                     break;
                 case Map_Str2Int("KRO", 3):
                     detailInfo.KRO = true;
                     break;
                 case Map_Str2Int("KRG", 3):
                     detailInfo.KRG = true;
                     break;
                 case Map_Str2Int("KRW", 3):
                     detailInfo.KRW = true;
                     break;
                 case Map_Str2Int("BOIL", 4):
                     detailInfo.BOIL = true;
                     break;
                 case Map_Str2Int("BGAS", 4):
                     detailInfo.BGAS = true;
                     break;
                 case Map_Str2Int("BWAT", 4):
                     detailInfo.BWAT = true;
                     break;
                 case Map_Str2Int("VOIL", 4):
                     detailInfo.VOIL = true;
                     break;
                 case Map_Str2Int("VGAS", 4):
                     detailInfo.VGAS = true;
                     break;
                 case Map_Str2Int("VWAT", 4):
                     detailInfo.VWAT = true;
                     break;
                 case Map_Str2Int("XMF", 3):
                     detailInfo.XMF = true;
                     break;
                 case Map_Str2Int("YMF", 3):
                     detailInfo.YMF = true;
                     break;
                 case Map_Str2Int("PCW", 3):
                     detailInfo.PCW = true;
                     break;
                 default:
                     break;
             }
         }
     }
     cout << "RPTSCHDE" << endl;
 }
References OutputDetail::BGAS, OutputDetail::BOIL, OutputDetail::BWAT, OutputDetail::DENG, OutputDetail::DENO, OutputDetail::DENW, detailInfo, OutputDetail::KRG, OutputDetail::KRO, OutputDetail::KRW, Map_Str2Int(), OutputDetail::PCW, OutputDetail::PGAS, OutputDetail::PRE, OutputDetail::PWAT, ReadLine(), OutputDetail::SGAS, OutputDetail::SOIL, OutputDetail::SWAT, OutputDetail::VGAS, OutputDetail::VOIL, OutputDetail::VWAT, OutputDetail::XMF, and OutputDetail::YMF.
InputSUMMARY()
void ParamOutput::InputSUMMARY (ifstream & ifs)
Input the keyword SUMMARY, which contains many subkeyword, indicating which results are interested by user. After the simulation, these results will be output into a summary file.
Definition at line 14 of file ParamOutput.cpp.
 {
     vector<string> vbuf;
     while (ReadLine(ifs, vbuf)) {
         if (vbuf[0] == "/") break;
         string keyword = vbuf[0];
         switch (Map_Str2Int(&keyword[0], keyword.size())) {
             case Map_Str2Int("FPR", 3):
                 summary.FPR = true;
                 break;
             // Field
             case Map_Str2Int("FOPR", 4):
                 summary.FOPR = true;
                 break;
             case Map_Str2Int("FOPT", 4):
                 summary.FOPT = true;
                 break;
             case Map_Str2Int("FGPR", 4):
                 summary.FGPR = true;
                 break;
             case Map_Str2Int("FGPT", 4):
                 summary.FGPt = true;
                 break;
             case Map_Str2Int("FWPR", 4):
                 summary.FWPR = true;
                 break;
             case Map_Str2Int("FWPT", 4):
                 summary.FWPT = true;
                 break;
             case Map_Str2Int("FGIR", 4):
                 summary.FGIR = true;
                 break;
             case Map_Str2Int("FGIT", 4):
                 summary.FGIT = true;
                 break;
             case Map_Str2Int("FWIR", 4):
                 summary.FWIR = true;
                 break;
             case Map_Str2Int("FWIT", 4):
                 summary.FWIT = true;
                 break;
             // Well
             case Map_Str2Int("WOPR", 4):
                 InputType_A(ifs, summary.WOPR);
                 break;
             case Map_Str2Int("WOPT", 4):
                 InputType_A(ifs, summary.WOPT);
                 break;
             case Map_Str2Int("WGPR", 4):
                 InputType_A(ifs, summary.WGPR);
                 break;
             case Map_Str2Int("WGPT", 4):
                 InputType_A(ifs, summary.WGPT);
                 break;
             case Map_Str2Int("WWPR", 4):
                 InputType_A(ifs, summary.WWPR);
                 break;
             case Map_Str2Int("WWPT", 4):
                 InputType_A(ifs, summary.WWPT);
                 break;
             case Map_Str2Int("WGIR", 4):
                 InputType_A(ifs, summary.WGIR);
                 break;
             case Map_Str2Int("WGIT", 4):
                 InputType_A(ifs, summary.WGIT);
                 break;
             case Map_Str2Int("WWIR", 4):
                 InputType_A(ifs, summary.WWIR);
                 break;
             case Map_Str2Int("WWIT", 4):
                 InputType_A(ifs, summary.WWIT);
                 break;
             case Map_Str2Int("WBHP", 4):
                 InputType_A(ifs, summary.WBHP);
                 break;
             case Map_Str2Int("DG", 2):
                 InputType_A(ifs, summary.DG);
                 break;
             case Map_Str2Int("BPR", 3):
                 InputType_B(ifs, summary.BPR);
                 break;
             case Map_Str2Int("SOIL", 4):
                 InputType_B(ifs, summary.SOIL);
                 break;
             case Map_Str2Int("SGAS", 4):
                 InputType_B(ifs, summary.SGAS);
                 break;
             case Map_Str2Int("SWAT", 4):
                 InputType_B(ifs, summary.SWAT);
                 break;
             default:
                 break;
         }
     }
     cout << "SUMMARY" << endl;
 }
References OutputSummary::BPR, OutputSummary::DG, OutputSummary::FGIR, OutputSummary::FGIT, OutputSummary::FGPR, OutputSummary::FGPt, OutputSummary::FOPR, OutputSummary::FOPT, OutputSummary::FPR, OutputSummary::FWIR, OutputSummary::FWIT, OutputSummary::FWPR, OutputSummary::FWPT, InputType_A(), InputType_B(), Map_Str2Int(), ReadLine(), OutputSummary::SGAS, OutputSummary::SOIL, summary, OutputSummary::SWAT, OutputSummary::WBHP, OutputSummary::WGIR, OutputSummary::WGIT, OutputSummary::WGPR, OutputSummary::WGPT, OutputSummary::WOPR, OutputSummary::WOPT, OutputSummary::WWIR, OutputSummary::WWIT, OutputSummary::WWPR, and OutputSummary::WWPT.
InputType_A()
void ParamOutput::InputType_A (ifstream & ifs, Type_A_o & obj)
Input the subkeyword in SUMMARY, the contents in these keyword is in the form of string.
Definition at line 138 of file ParamOutput.cpp.
 {
     obj.activity = true;
     vector<string> vbuf;
     ReadLine(ifs, vbuf);
     if (vbuf[0] == "/") {
         obj.obj.push_back("All");
     } else {
         OCP_INT len = vbuf.size();
         for (OCP_INT i = 0; i < len - 1; i++) {
             obj.obj.push_back(vbuf[i]);
         }
         if (vbuf.back() != "/") obj.obj.push_back(vbuf.back());
         while (ReadLine(ifs, vbuf)) {
             if (vbuf[0] == "/") break;
             OCP_INT len = vbuf.size();
             for (OCP_INT i = 0; i < len - 1; i++) {
                 obj.obj.push_back(vbuf[i]);
             }
             if (vbuf.back() != "/") obj.obj.push_back(vbuf.back());
         }
     }
     cout << "Type_A" << endl;
 }
References ReadLine().
InputType_B()
void ParamOutput::InputType_B (ifstream & ifs, Type_B_o & obj)
Input the subkeyword in SUMMARY, the contents in these keyword is in the form of coordinates.
Definition at line 165 of file ParamOutput.cpp.
 {
     vector<string> vbuf;
     while (ReadLine(ifs, vbuf)) {
         if (vbuf[0] == "/") break;
         obj.activity = true;
         DealDefault(vbuf);
         USI i = stoi(vbuf[0]);
         USI j = stoi(vbuf[1]);
         USI k = stoi(vbuf[2]);
         obj.obj.push_back(COOIJK(i, j, k));
     }
     cout << "Type_B" << endl;
 }
References DealDefault(), and ReadLine().
The documentation for this class was generated from the following files:
ParamOutput.hpp
ParamOutput.cpp