OpenCAEPoro: IsoT_IMPEC Class Reference
IsoT_IMPEC Class Reference
IsoT_IMPEC is IMPEC (implicit pressure explict saturation) method.
#include <OCPFluidMethod.hpp>
Public Member Functions
void Setup (Reservoir &rs, LinearSystem &ls, const OCPControl &ctrl)
Setup IMPEC.
void InitReservoir (Reservoir &rs) const
Init.
void Prepare (Reservoir &rs, OCPControl &ctrl)
Prepare for Assembling matrix.
void AssembleMat (LinearSystem &ls, const Reservoir &rs, const OCP_DBL &dt) const
Assemble Matrix.
void SolveLinearSystem (LinearSystem &ls, Reservoir &rs, OCPControl &ctrl)
Solve the linear system.
OCP_BOOL UpdateProperty (Reservoir &rs, OCPControl &ctrl)
Update properties of fluids.
OCP_BOOL FinishNR (const Reservoir &rs)
Determine if NR iteration finishes.
void FinishStep (Reservoir &rs, OCPControl &ctrl)
Public Member Functions inherited from IsothermalMethod
void InitRock (Bulk &bk) const
void CalRock (Bulk &bk) const
Protected Member Functions
void InitFlash (Bulk &bk) const
Perform Flash with Sj and calculate values needed for FIM.
void CalKrPc (Bulk &bk) const
Calculate relative permeability and capillary pressure needed for FIM.
void PassFlashValue (Bulk &bk, const OCP_USI &n) const
Pass value needed for FIM from flash to bulk.
Detailed Description
IsoT_IMPEC is IMPEC (implicit pressure explict saturation) method.
Definition at line 32 of file OCPFluidMethod.hpp.
Member Function Documentation
InitReservoir()
void IsoT_IMPEC::InitReservoir (Reservoir & rs) const
Init.
Initialize reservoir.
Definition at line 50 of file OCPFluidMethod.cpp.
 {
     rs.bulk.InitPTSw(50);
     InitRock(rs.bulk);
     CalRock(rs.bulk);
     InitFlash(rs.bulk);
     CalKrPc(rs.bulk);
     CalBulkFlux(rs);
     rs.allWells.InitBHP(rs.bulk);
     UpdateLastTimeStep(rs);
 }
References Reservoir::allWells, Reservoir::bulk, CalKrPc(), AllWells::InitBHP(), InitFlash(), and Bulk::InitPTSw().
The documentation for this class was generated from the following files:
OCPFluidMethod.hpp
OCPFluidMethod.cpp