OpenCAEPoro: OpenCAEPoro Class Reference
OpenCAEPoro Class Reference
Top-level data structure for the OpenCAEPoro simulator.
#include <OCP.hpp>
Public Member Functions
void PrintVersion () const
Output OpenCAEPoro version information.
void PrintUsage (string cmdname) const
Provide at least InputFileName for the input data.
void InputParam (ParamRead &param)
Read input parameters to an internal structure.
void SetupSimulator (ParamRead &param, const USI &argc, const char *options[])
Setup reservoir based on an internal structure.
void InitReservoir ()
Initialize or get initial status of reservoir.
void RunSimulation ()
Run dynamic simulation.
void OutputResults () const
Output necessary information for post-processing.
Detailed Description
Top-level data structure for the OpenCAEPoro simulator.
Definition at line 26 of file OCP.hpp.
Member Function Documentation
InitReservoir()
void OpenCAEPoro::InitReservoir ()
Initialize or get initial status of reservoir.
Initialize the reservoir class.
Definition at line 49 of file OCP.cpp.
 {
     GetWallTime timer;
     timer.Start();
     solver.InitReservoir(reservoir);
     cout << endl
          << "Initialization done. Wall time : " << fixed << setprecision(3)
          << timer.Stop() / 1000 << " Sec" << endl;
     control.RecordTotalTime(timer.Stop() / 1000);
 }
References Solver::InitReservoir(), OCPControl::RecordTotalTime(), GetWallTime::Start(), and GetWallTime::Stop().
InputParam()
void OpenCAEPoro::InputParam (ParamRead & param)
Read input parameters to an internal structure.
Read from input file and set control and output params.
Definition at line 15 of file OCP.cpp.
 {
     reservoir.InputParam(param);
     control.InputParam(param.paramControl);
     output.InputParam(param.paramOutput);
 }
References OCPControl::InputParam(), Reservoir::InputParam(), ParamRead::paramControl, and ParamRead::paramOutput.
OutputResults()
void OpenCAEPoro::OutputResults () const
Output necessary information for post-processing.
Print summary information on screen and SUMMARY.out file.
Definition at line 94 of file OCP.cpp.
 {
     cout << "=========================================" << endl;
     cout << "Final time:          " << control.current_time << " Days" << endl;
     cout << "Total time steps:    " << control.numTstep << endl;
     cout << "Total Newton steps:  " << control.iterNR_total << " (+"
          << control.wastedIterNR << " wasted steps)" << endl;
     cout << "Total linear steps:  " << control.iterLS_total << " (+"
          << control.wastedIterLS << " wasted steps)" << endl;
     cout << "Linear solve time:   " << control.totalLStime << "s"
          << " (" << 100.0 * control.totalLStime / control.totalSimTime << "%)" << endl;
     cout << "Simulation time:     " << control.totalSimTime << "s" << endl;
     output.PrintInfo();
 }
RunSimulation()
void OpenCAEPoro::RunSimulation ()
Run dynamic simulation.
Call IMPEC, FIM, etc for dynamic simulation.
Definition at line 63 of file OCP.cpp.
 {
     cout << "\n=========================================" << endl;
     switch (control.GetMethod()) {
         case IMPEC:
             cout << "Dynamic simulation with IMPEC";
             break;
         case FIM:
             cout << "Dynamic simulation with FIM";
             break;
         case FIMn:
             cout << "Dynamic simulation with FIMn";
             break;
         case AIMc:
             cout << "Dynamic simulation with AIMc";
             break;
         case AIMs:
             cout << "Dynamic simulation with AIMs";
             break;
         case AIMt:
             cout << "Dynamic simulation with AIMt";
             break;
         default:
             OCP_ABORT("Wrong method type is used!");
     }
     cout << "\n=========================================" << endl;
     solver.RunSimulation(reservoir, control, output);
 }
References AIMc, AIMs, AIMt, FIM, FIMn, OCPControl::GetMethod(), IMPEC, OCP_ABORT, and Solver::RunSimulation().
SetupSimulator()
void OpenCAEPoro::SetupSimulator (ParamRead & param, const USI & argc, const char * options[])
Setup reservoir based on an internal structure.
Call setup procedures for reservoir, output, and linear solver.
Definition at line 23 of file OCP.cpp.
 {
     GetWallTime timer;
     timer.Start();
     // Read parameters from input file
     InputParam(param);
     // Read Fast control
     control.SetupFastControl(argc, options);
     // Setup static infomation for reservoir
     reservoir.Setup();
     // Setup output for dynamic simulation
     output.Setup(reservoir, control);
     // Setup static information for solver
     solver.Setup(reservoir, control);
     cout << endl
          << "Setup simulation done. Wall time : " << fixed << setprecision(3)
          << timer.Stop() / 1000 << " Sec" << endl
          << endl;
     control.RecordTotalTime(timer.Stop() / 1000);
 }
References InputParam(), OCPControl::RecordTotalTime(), Reservoir::Setup(), Solver::Setup(), OCPControl::SetupFastControl(), GetWallTime::Start(), and GetWallTime::Stop().
The documentation for this class was generated from the following files:
OCP.hpp
OCP.cpp