OpenCAEPoro: ParamReservoir Class Reference
ParamReservoir Class Reference
#include <ParamReservoir.hpp>
Public Member Functions
vector< OCP_DBL > * FindPtr (const string &varName)
Find pointer to the specified variable.
TableSet * FindPtr_T (const string &varName)
Find pointer to the specified table.
void Init ()
Initialize the default value in reservoir, such as temperature, density, table.
void InitTable ()
Initialize the tables' name and num of colum.
template<typename T >
void setVal (vector< T > &obj, const T &val, const vector< USI > &index)
It's used in InputEQUALS, assigning values in batches.
template<typename T >
void CopyVal (vector< T > &obj, const vector< T > &src, const vector< USI > &index)
It's used in InputCOPY, copying the value of one variable to another.
void MultiplyVal (vector< OCP_DBL > &obj, const OCP_DBL &val, const vector< USI > &index)
TODO: Add Doxygen.
void InputCOMPS (ifstream &ifs)
TODO: Add Doxygen.
void InputDIMENS (ifstream &ifs)
TODO: Add Doxygen.
void DisplayDIMENS ()
Display the dimens, it's used to chech input.
void InputRTEMP (ifstream &ifs)
Input the keyword: RTEMP. RTEMP gives the temperature of reservoir.
void InputEQUALS (ifstream &ifs)
TODO: Add Doxygen.
void InputGRID (ifstream &ifs, string &keyword)
TODO: Add Doxygen.
void InputCOPY (ifstream &ifs)
Input the keyword: COPY. COPY could copy the value of one variable to another.
void InputMULTIPLY (ifstream &ifs)
TODO: Add Doxygen.
void InputTABLE (ifstream &ifs, const string &tabName)
Input PVTtable and SATtable such as SWOF, PVCO.
void InputROCK (ifstream &ifs)
Read data from the ROCK keyword.
void InputROCKT (ifstream &ifs)
input Rock information for thermal model
void InputMISCSTR (ifstream &ifs)
Input the Miscibility information.
void InputGRAVITY (ifstream &ifs)
Input the reference gravity of oil, water, and air in standard condition.
void InputDENSITY (ifstream &ifs)
Input the reference density of oil, water, and air in standard condition.
void InputTHCON (ifstream &ifs, const string &keyword)
Input the phase thermal conductivity.
void InputEQUIL (ifstream &ifs)
EQUIL contains initial information of reservoir; see ParamEQUIL.
void InputTABDIMS (ifstream &ifs)
TABDIMS contains the num of saturation region and PVT region.
void InputRegion (ifstream &ifs, const string &keyword)
Input the keyword: SATNUM and PVTNUM.
void InputCNAMES (ifstream &ifs)
void InputCOMPONENTS (ifstream &ifs, const string &keyword)
void InputLBCCOEF (ifstream &ifs)
void InputBIC (ifstream &ifs)
void InputVISCTAB (ifstream &ifs)
void InputRefPR (ifstream &ifs, const string &keyword)
void InputSSMSTA (ifstream &ifs)
void InputNRSTA (ifstream &ifs)
void InputSSMSP (ifstream &ifs)
void InputNRSP (ifstream &ifs)
void InputRR (ifstream &ifs)
void CheckParam ()
Check the reservoir param from input file.
void CheckGrid ()
Check the size of properties of grids.
void CheckRock ()
Check Rock.
void CheckEQUIL () const
Check if keyword EQUIL is given.
void CheckDenGra () const
Check if density and gravity are both input, only one of them is needed.
void CheckPhase () const
Check existence of disgas, it could only exist when both oil and gas exist.
void CheckPhaseTab () const
Check existence of PVTtable and SATtable.
void CheckRegion () const
Check if each grid is assigned to an area or all defaulted.
void CheckEqlRegion () const
(Todo) Initialization of equilibration of only one region is realized.
Public Attributes
Dimens dimens
Dimension of grid: the number of grids along x,y,z direction.
OCP_USI numGrid
Num of grids.
vector< OCP_DBL > tops
Depth of the top surface of the uppermost grids.
vector< OCP_DBL > dx
Size along the x - direction for each grid.
vector< OCP_DBL > dy
Size along the y - direction for each grid.
vector< OCP_DBL > dz
Size along the z - direction for each grid.
vector< OCP_DBL > coord
TODO: Add Doxygen.
vector< OCP_DBL > zcorn
TODO: Add Doxygen.
vector< OCP_DBL > ntg
Net to gross for each grid.
vector< OCP_DBL > poro
Porosity for each grid.
vector< OCP_DBL > permX
Permeability along the x - direction for each grid.
vector< OCP_DBL > permY
Permeability along the y-direction for each grid.
vector< OCP_DBL > permZ
Permeability along the z-direction for each grid.
vector< OCP_DBL > thconr
Rock thermal conductivity.
OCP_DBL rsTemp
Temperature for reservoir.
vector< RockParam > rockSet
a set of rock
Miscstr miscstr
reference Miscibility surface tension
vector< OCP_DBL > P
Initial pressure of components in each grid.
vector< OCP_DBL > Ni
Initial moles of components in each grid.
vector< OCP_DBL > Swat
Initial water saturation in each grid.
OCP_BOOL ScalePcow {OCP_FALSE}
whether Pcow should be scaled.
Type_A_r< OCP_DBL > density
Density of oil, water, gas in standard conditions.
Type_A_r< OCP_DBL > gravity
Gravity of oil, water, gas in standard conditions.
OCP_DBL thcono { 24 }
oil thermal conductivity
OCP_DBL thcong { 24 }
gas thermal conductivity
OCP_DBL thconw { 24 }
water thermal conductivity
OCP_BOOL blackOil {OCP_FALSE}
If ture, blackoil model will be used.
OCP_BOOL comps {OCP_FALSE}
If OCP_TRUE, compositional model will be used.
OCP_BOOL thermal {OCP_FALSE}
If OCP_TRUE, thermal model will be used.
OCP_BOOL oil {OCP_FALSE}
If OCP_TRUE, oil phase could exist.
OCP_BOOL gas {OCP_FALSE}
If OCP_TRUE, gas phase could exist.
OCP_BOOL water {OCP_FALSE}
If OCP_TRUE, water phase could exist.
OCP_BOOL disGas {OCP_FALSE}
If OCP_TRUE, dissolve gas could exist in oil phase.
ComponentParam comsParam
information for components
USI NTSFUN {1}
Num of SAT regions.
USI NTPVT {1}
Num of PVT regions.
USI NTROOC {1}
Num of Rock regions.
Type_A_r< OCP_DBL > SATNUM
Records the index of SAT region for each grid.
Type_A_r< OCP_DBL > PVTNUM
Records the index of PVT region for each grid.
Type_A_r< OCP_DBL > ACTNUM
Records the index of Active region for each grid.
Type_A_r< OCP_DBL > ROCKNUM
Records the index of ROCK region for each grid.
TableSet SWFN_T
Table set of SWFN.
TableSet SWOF_T
Table set of SWOF.
TableSet SGFN_T
Table set of SGFN.
TableSet SGOF_T
Table set of SGOF.
TableSet SOF3_T
Table set of SOF3.
TableSet PBVD_T
Table set of PBVD.
TableSet ZMFVD_T
Table set of ZMFVD.
TableSet TEMPVD_T
Table set of TEMPVD.
vector< OCP_DBL > EQUIL
See ParamEQUIL.
USI numPhase
Number of phases.
USI numCom
Number of components(hydrocarbon components), used in Compositional Model when input.
TableSet PVCO_T
Table set of PVCO.
TableSet PVDO_T
Table set of PVDO.
TableSet PVDG_T
Table set of PVDG.
TableSet PVTW_T
Table set of PVTW.
Detailed Description
ParamReservoir is an internal structure used to stores the information of reservoir(except wells) from input files. It is an intermediate interface and independent of the main simulator. After all file inputting finishs, the params in it will pass to corresponding modules.
Definition at line 175 of file ParamReservoir.hpp.
Member Function Documentation
CheckDenGra()
void ParamReservoir::CheckDenGra () const
Check if density and gravity are both input, only one of them is needed.
TODO: Add Doxygen.
Definition at line 833 of file ParamReservoir.cpp.
 {
     if (density.activity && gravity.activity) {
         OCP_ABORT("Both DENSITY and GRAVITY have been given, just one can be used!");
     }
 }
References Type_A_r< T >::activity, density, gravity, and OCP_ABORT.
CheckEqlRegion()
void ParamReservoir::CheckEqlRegion () const
(Todo) Initialization of equilibration of only one region is realized.
TODO: Add Doxygen.
Definition at line 882 of file ParamReservoir.cpp.
 {
     if (PBVD_T.data.size() > 1) {
         OCP_ABORT("Only one equilibration region is supported!");
     }
 }
References TableSet::data, OCP_ABORT, and PBVD_T.
CheckEQUIL()
void ParamReservoir::CheckEQUIL () const
Check if keyword EQUIL is given.
Check EQUIL keywords.
Definition at line 827 of file ParamReservoir.cpp.
 {
     if (EQUIL.empty()) OCP_ABORT("EQUIL is missing!");
 }
References EQUIL, and OCP_ABORT.
CheckGrid()
void ParamReservoir::CheckGrid ()
Check the size of properties of grids.
Check data dimension for potential problems.
Definition at line 794 of file ParamReservoir.cpp.
 {
     if (coord.size() == 0) {
         if (tops.size() != dimens.nx * dimens.ny) OCP_ABORT("Wrong TOPS size!");
         if (dx.size() != numGrid) OCP_ABORT("Wrong DX size!");
         if (dy.size() != numGrid) OCP_ABORT("Wrong DY size!");
         if (dz.size() != numGrid) OCP_ABORT("Wrong DZ size!");
     } else {
         if (coord.size() != (dimens.nx + 1) * (dimens.ny + 1) * 6)
             OCP_ABORT("Wrong COORD size!");
         if (zcorn.size() != numGrid * 8) OCP_ABORT("Wrong ZCORN size!");
     }
     if (poro.size() != numGrid) OCP_ABORT("Wrong PORO size!");
     if (permX.size() != numGrid) OCP_ABORT("Wrong PERMX size!");
     if (permY.size() != numGrid) OCP_ABORT("Wrong PERMY size!");
     if (permZ.size() != numGrid) OCP_ABORT("Wrong PERMZ size!");
     if (ntg.size() != numGrid) {
         ntg.resize(numGrid, 1);
         cout << "Reset Ntg size to 1!" << endl;
     }
 }
References coord, dimens, dx, dy, dz, ntg, numGrid, Dimens::nx, Dimens::ny, OCP_ABORT, permX, permY, permZ, poro, tops, and zcorn.
CheckParam()
void ParamReservoir::CheckParam ()
Check the reservoir param from input file.
Check consistency of input parameters.
Definition at line 782 of file ParamReservoir.cpp.
 {
     CheckGrid();
     CheckEQUIL();
     CheckDenGra();
     CheckPhase();
     // CheckPhaseTab();
     CheckRegion();
     CheckRock();
 }
References CheckDenGra(), CheckEQUIL(), CheckGrid(), CheckPhase(), CheckRegion(), and CheckRock().
CheckPhase()
void ParamReservoir::CheckPhase () const
Check existence of disgas, it could only exist when both oil and gas exist.
TODO: Add Doxygen.
Definition at line 841 of file ParamReservoir.cpp.
 {
     if (blackOil && disGas && (!gas && !oil)) {
         OCP_ABORT("DISGAS can only be used only if OIL and GAS are both present!");
     }
 }
References blackOil, disGas, gas, OCP_ABORT, and oil.
CheckPhaseTab()
void ParamReservoir::CheckPhaseTab () const
Check existence of PVTtable and SATtable.
Check tables: Different tables will be used under different conditions.
Definition at line 849 of file ParamReservoir.cpp.
 {
     if (!blackOil && !comps) OCP_ABORT("Unknown model: Use BLACKOIL or COMPS!");
     if (water && oil && SWOF_T.data.empty()) OCP_ABORT("SWOF is missing!");
     if (gas && oil && SGOF_T.data.empty()) OCP_ABORT("SGOF is missing!");
     if (water && PVTW_T.data.empty()) OCP_ABORT("PVTW is missing!");
     if (blackOil) {
         if (oil && disGas && PVCO_T.data.empty()) OCP_ABORT("PVCO is missing!");
         if (oil && (!disGas) && PVDO_T.data.empty()) OCP_ABORT("PVDO is missing!");
         if (gas && PVDG_T.data.empty()) OCP_ABORT("PVDG is missing!");
     }
 }
References blackOil, comps, TableSet::data, disGas, gas, OCP_ABORT, oil, PVCO_T, PVDG_T, PVDO_T, PVTW_T, SGOF_T, SWOF_T, and water.
CheckRegion()
void ParamReservoir::CheckRegion () const
Check if each grid is assigned to an area or all defaulted.
TODO: Add Doxygen.
Definition at line 865 of file ParamReservoir.cpp.
 {
     if (SATNUM.activity && SATNUM.data.size() != numGrid) {
         OCP_ABORT("Missing data in SATNUM!");
     }
     if (PVTNUM.activity && PVTNUM.data.size() != numGrid) {
         OCP_ABORT("Missing data in PVTNUM!");
     }
     if (ACTNUM.activity && ACTNUM.data.size() != numGrid) {
         OCP_ABORT("Missing data in ACTNUM!");
     }
     if (ROCKNUM.activity && ROCKNUM.data.size() != numGrid) {
         OCP_ABORT("Missing data in ROCKNUM!");
     }
 }
References Type_A_r< T >::activity, ACTNUM, Type_A_r< T >::data, numGrid, OCP_ABORT, PVTNUM, ROCKNUM, and SATNUM.
CopyVal()
template<typename T > void ParamReservoir::CopyVal (vector< T > & obj, const vector< T > & src, const vector< USI > & index)
It's used in InputCOPY, copying the value of one variable to another.
TODO: Add Doxygen.
Definition at line 243 of file ParamReservoir.cpp.
 {
     USI     Nx   = dimens.nx;
     USI     Ny   = dimens.ny;
     OCP_USI NxNy = Nx * Ny;
     OCP_USI id   = 0;
     for (USI k = index[4]; k <= index[5]; k++) {
         for (USI j = index[2]; j <= index[3]; j++) {
             for (USI i = index[0]; i <= index[1]; i++) {
                 id      = k * NxNy + j * Nx + i;
                 obj[id] = src[id];
             }
         }
     }
 }
References dimens, Dimens::nx, and Dimens::ny.
DisplayDIMENS()
void ParamReservoir::DisplayDIMENS ()
Display the dimens, it's used to chech input.
TODO: Add Doxygen.
Definition at line 309 of file ParamReservoir.cpp.
 {
     cout << "DIMENS" << endl;
     cout << dimens.nx << "  " << dimens.ny << "  " << dimens.nz << "\n\n";
     ;
 }
References dimens, Dimens::nx, Dimens::ny, and Dimens::nz.
FindPtr()
vector< OCP_DBL > * ParamReservoir::FindPtr (const string & varName)
Find pointer to the specified variable.
Find corresponding variable according to the name of variable. It is used for the basic properties of reservoir such as DX.
Definition at line 15 of file ParamReservoir.cpp.
 {
     vector<OCP_DBL>* myPtr = nullptr;
     switch (Map_Str2Int(&varName[0], varName.size())) {
         case Map_Str2Int("DX", 2):
             dx.reserve(numGrid);
             myPtr = &dx;
             break;
         case Map_Str2Int("DY", 2):
             dy.reserve(numGrid);
             myPtr = &dy;
             break;
         case Map_Str2Int("DZ", 2):
             dz.reserve(numGrid);
             myPtr = &dz;
             break;
         case Map_Str2Int("COORD", 5):
             coord.reserve((dimens.nx + 1) * (dimens.ny + 1) * 6);
             myPtr = &coord;
             break;
         case Map_Str2Int("ZCORN", 5):
             zcorn.reserve(numGrid * 8);
             myPtr = &zcorn;
             break;
         case Map_Str2Int("PORO", 4):
             poro.reserve(numGrid);
             myPtr = &poro;
             break;
         case Map_Str2Int("NTG", 3):
             ntg.reserve(numGrid);
             myPtr = &ntg;
             break;
         case Map_Str2Int("PERMX", 5):
             permX.reserve(numGrid);
             myPtr = &permX;
             break;
         case Map_Str2Int("PERMY", 5):
             permY.reserve(numGrid);
             myPtr = &permY;
             break;
         case Map_Str2Int("PERMZ", 5):
             permZ.reserve(numGrid);
             myPtr = &permZ;
             break;
         case Map_Str2Int("THCONR", 6):
             thconr.reserve(numGrid);
             myPtr = &thconr;
             break;
         case Map_Str2Int("TOPS", 4):
             tops.reserve(dimens.nx * dimens.ny);
             myPtr = &tops;
             break;
         case Map_Str2Int("PRESSURE", 8):
             P.reserve(numGrid);
             myPtr = &P;
             break;
         case Map_Str2Int("Ni", 2):
             Ni.reserve(numGrid);
             myPtr = &Ni;
             break;
         case Map_Str2Int("SWATINIT", 8):
             Swat.reserve(numGrid);
             myPtr     = &Swat;
             ScalePcow = OCP_TRUE;
             break;
         case Map_Str2Int("SATNUM", 6):
             SATNUM.activity = OCP_TRUE;
             SATNUM.data.reserve(numGrid);
             myPtr = &SATNUM.data;
             break;
         case Map_Str2Int("PVTNUM", 6):
             PVTNUM.activity = OCP_TRUE;
             PVTNUM.data.reserve(numGrid);
             myPtr = &PVTNUM.data;
             break;
         case Map_Str2Int("ROCKNUM", 7):
             ROCKNUM.activity = OCP_TRUE;
             ROCKNUM.data.reserve(numGrid);
             myPtr = &ROCKNUM.data;
             break;
     }
     return myPtr;
 }
References coord, dimens, dx, dy, dz, Map_Str2Int(), Ni, ntg, numGrid, Dimens::nx, Dimens::ny, P, permX, permY, permZ, poro, ScalePcow, Swat, thconr, tops, and zcorn.
FindPtr_T()
TableSet * ParamReservoir::FindPtr_T (const string & varName)
Find pointer to the specified table.
Find corresponding variable according to the name of variable. It is used for the scope of the table.
Definition at line 119 of file ParamReservoir.cpp.
 {
     TableSet* myPtr = nullptr;
     switch (Map_Str2Int(&varName[0], varName.size())) {
         case Map_Str2Int("SWFN", 4):
             myPtr = &SWFN_T;
             break;
         case Map_Str2Int("SWOF", 4):
             myPtr = &SWOF_T;
             break;
         case Map_Str2Int("SGFN", 4):
             myPtr = &SGFN_T;
             break;
         case Map_Str2Int("SGOF", 4):
             myPtr = &SGOF_T;
             break;
         case Map_Str2Int("SOF3", 4):
             myPtr = &SOF3_T;
             break;
         case Map_Str2Int("PBVD", 4):
             myPtr = &PBVD_T;
             break;
         case Map_Str2Int("PVCO", 4):
             myPtr = &PVCO_T;
             break;
         case Map_Str2Int("PVDO", 4):
             myPtr = &PVDO_T;
             break;
         case Map_Str2Int("PVDG", 4):
             myPtr = &PVDG_T;
             break;
         case Map_Str2Int("PVTW", 4):
             myPtr = &PVTW_T;
             break;
         case Map_Str2Int("ZMFVD", 5):
             myPtr = &ZMFVD_T;
             break;
         case Map_Str2Int("TEMPVD", 6):
             myPtr = &TEMPVD_T;
             break;
     }
     return myPtr;
 }
References Map_Str2Int(), PBVD_T, PVCO_T, PVDG_T, PVDO_T, PVTW_T, SGFN_T, SGOF_T, SOF3_T, SWFN_T, SWOF_T, TEMPVD_T, and ZMFVD_T.
Init()
void ParamReservoir::Init ()
Initialize the default value in reservoir, such as temperature, density, table.
Initialize tables and other reservoir parameters.
Definition at line 177 of file ParamReservoir.cpp.
 {
     InitTable();
     gravity.data.resize(3);
     gravity.data[0] = 45.5;   // oil
     gravity.data[1] = 1.0;    // pure water
     gravity.data[2] = 0.7773; // air
     density.data.resize(3);
     density.data[0] = 37.457;    // The density of oil at surface conditions: lb/ft3
     density.data[1] = 62.366416; // The density of water at surface conditions: lb/ft3
     density.data[2] = 0.062428;  // The density of gas at surface conditions: lb/ft3
     rsTemp    = 60.0;
 }
References Type_A_r< T >::data, density, gravity, InitTable(), and rsTemp.
InitTable()
void ParamReservoir::InitTable ()
Initialize the tables' name and num of colum.
Initialize tables.
Definition at line 195 of file ParamReservoir.cpp.
 {
     SWFN_T.name   = "SWFN";
     SWFN_T.colNum = 3;
     SWOF_T.name   = "SWOF";
     SWOF_T.colNum = 4;
     SGFN_T.name   = "SGFN";
     SGFN_T.colNum = 3;
     SGOF_T.name   = "SGOF";
     SGOF_T.colNum = 4;
     SOF3_T.name   = "SOF3";
     SOF3_T.colNum = 3;
     PBVD_T.name   = "PBVD";
     PBVD_T.colNum = 2;
     PVCO_T.name   = "PVCO";
     PVCO_T.colNum = 6;
     PVDO_T.name   = "PVDO";
     PVDO_T.colNum = 3;
     PVDG_T.name   = "PVDG";
     PVDG_T.colNum = 3;
     PVTW_T.name   = "PVTW";
     PVTW_T.colNum = 5;
     ZMFVD_T.name  = "ZMFVD"; // colnum equals numCom(hydrocarbon) + 1
     TEMPVD_T.name = "TEMPVD"; // colnum equals 2
     TEMPVD_T.colNum = 2;
 }
References TableSet::colNum, TableSet::name, PBVD_T, PVCO_T, PVDG_T, PVDO_T, PVTW_T, SGFN_T, SGOF_T, SOF3_T, SWFN_T, SWOF_T, TEMPVD_T, and ZMFVD_T.
InputCOMPS()
void ParamReservoir::InputCOMPS (ifstream & ifs)
TODO: Add Doxygen.
Input the keyword: COMPS. COMPS is used in compositional model, which gives the num of components.
Definition at line 283 of file ParamReservoir.cpp.
 {
     comps = OCP_TRUE;
     vector<string> vbuf;
     ReadLine(ifs, vbuf);
     numCom      = stoi(vbuf[0]);
     comsParam.numCom = numCom;
     comsParam.Init();
     cout << "COMPS" << endl << numCom << "\n\n";
 }
References comps.
InputCOPY()
void ParamReservoir::InputCOPY (ifstream & ifs)
Input the keyword: COPY. COPY could copy the value of one variable to another.
TODO: Add Doxygen.
Definition at line 409 of file ParamReservoir.cpp.
 {
     cout << "COPY" << endl;
     vector<string> vbuf;
     vector<USI>    index(6, 0);
     while (ReadLine(ifs, vbuf)) {
         if (vbuf[0] == "/") break;
         for (auto v : vbuf) {
             if (v != "/") cout << setw(10) << v;
         }
         cout << "\n";
         index[0] = 0, index[1] = dimens.nx - 1;
         index[2] = 0, index[3] = dimens.ny - 1;
         index[4] = 0, index[5] = dimens.nz - 1;
         string srcName = vbuf[0];
         string objName = vbuf[1];
         DealDefault(vbuf);
         for (USI n = 2; n < 8; n++) {
             if (vbuf[n] != "DEFAULT") index[n - 2] = stoi(vbuf[n]) - 1;
         }
         vector<OCP_DBL>* srcPtr = FindPtr(srcName);
         vector<OCP_DBL>* objPtr = FindPtr(objName);
         if (srcPtr != nullptr && objPtr != nullptr) {
             objPtr->resize(srcPtr->size());
             CopyVal(*objPtr, *srcPtr, index);
         } else {
             OCP_ABORT("Wrong object names: " + srcName + ", " + objName);
         }
     }
     cout << "/\n\n";
 }
References CopyVal(), DealDefault(), dimens, FindPtr(), Dimens::nx, Dimens::ny, Dimens::nz, OCP_ABORT, and ReadLine().
InputDENSITY()
void ParamReservoir::InputDENSITY (ifstream & ifs)
Input the reference density of oil, water, and air in standard condition.
Read data from the DENSITY keyword.
Definition at line 657 of file ParamReservoir.cpp.
 {
     vector<string> vbuf;
     ReadLine(ifs, vbuf);
     if (vbuf[0] == "/") return;
     DealDefault(vbuf);
     OCP_ASSERT(vbuf.size() == 4, "Wrong Keyword DENSITY!");
     for (USI i = 0; i < 3; i++) {
         if (vbuf[i] != "DEFAULT") {
             density.activity = OCP_TRUE;
             density.data[i]  = stod(vbuf[i]);
         }
     }
     cout << "---------------------" << endl
          << "DENSITY" << endl
          << "---------------------" << endl;
     cout << density.data[0] << "  " << density.data[1] << "  " << density.data[2]
          << endl;
 }
References Type_A_r< T >::activity, DealDefault(), density, OCP_ASSERT, and ReadLine().
InputDIMENS()
void ParamReservoir::InputDIMENS (ifstream & ifs)
TODO: Add Doxygen.
Input the keyword: DIMENS. DIMENS contain the dimension of grids of reservoir. It gives the num of grids along the x,y,z direction.
Definition at line 296 of file ParamReservoir.cpp.
 {
     vector<string> vbuf;
     ReadLine(ifs, vbuf);
     dimens.nx = stoi(vbuf[0]);
     dimens.ny = stoi(vbuf[1]);
     dimens.nz = stoi(vbuf[2]);
     numGrid   = dimens.nx * dimens.ny * dimens.nz;
     DisplayDIMENS();
 }
References dimens, DisplayDIMENS(), numGrid, Dimens::nx, Dimens::ny, Dimens::nz, and ReadLine().
InputEQUALS()
void ParamReservoir::InputEQUALS (ifstream & ifs)
TODO: Add Doxygen.
Input the keyword: EQUALS. EQUALS contains many keywords about grids which has special input format. These keywords contains DX, TOPS, PORO and so on. You can assign values to them in batches
Definition at line 328 of file ParamReservoir.cpp.
 {
     cout << "EQUALS" << endl;
     vector<USI>    index(6, 0);
     vector<string> vbuf;
     while (ReadLine(ifs, vbuf)) {
         if (vbuf[0] == "/") break;
         for (auto v : vbuf) {
             if (v != "/") cout << setw(10) << v;
         }
         cout << "\n";
         ;
         index[0] = 0, index[1] = dimens.nx - 1;
         index[2] = 0, index[3] = dimens.ny - 1;
         index[4] = 0, index[5] = dimens.nz - 1;
         string  objName = vbuf[0];
         OCP_DBL val     = stod(vbuf[1]);
         DealDefault(vbuf);
         for (USI n = 2; n < 8; n++) {
             if (vbuf[n] != "DEFAULT") index[n - 2] = stoi(vbuf[n]) - 1;
         }
         if (index[0] < 0 || index[2] < 0 || index[4] < 0 || index[1] > dimens.nx - 1 ||
             index[3] > dimens.ny - 1 || index[5] > dimens.nz - 1) {
             OCP_ABORT("WRONG Range in " + objName + " in EQUALS!");
         }
         vector<OCP_DBL>* objPtr = FindPtr(objName);
         if (objPtr != nullptr) {
             if (objName == "TOPS") {
                 objPtr->resize(dimens.nx * dimens.ny);
                 index[4] = index[5] = 0;
             } else {
                 objPtr->resize(numGrid);
             }
             setVal(*objPtr, val, index);
         } else {
             OCP_ABORT("Wrong object name: " + objName);
         }
     }
     cout << "/\n\n";
 }
References DealDefault(), dimens, FindPtr(), numGrid, Dimens::nx, Dimens::ny, Dimens::nz, OCP_ABORT, ReadLine(), and setVal().
InputEQUIL()
void ParamReservoir::InputEQUIL (ifstream & ifs)
EQUIL contains initial information of reservoir; see ParamEQUIL.
Read data from the EQUIL keyword.
Definition at line 702 of file ParamReservoir.cpp.
 {
     vector<string> vbuf;
     ReadLine(ifs, vbuf);
     if (vbuf[0] == "/") return;
     EQUIL.resize(6, 0);
     DealDefault(vbuf);
     for (USI i = 0; i < 6; i++) {
         if (vbuf[i] != "DEFAULT") EQUIL[i] = stod(vbuf[i]);
     }
     cout << "---------------------" << endl
          << "EQUIL" << endl
          << "---------------------" << endl;
     for (USI i = 0; i < 6; i++) cout << EQUIL[i] << "  ";
     cout << endl;
 }
References DealDefault(), EQUIL, and ReadLine().
InputGRAVITY()
void ParamReservoir::InputGRAVITY (ifstream & ifs)
Input the reference gravity of oil, water, and air in standard condition.
Read data from the GRAVITY keyword.
Definition at line 635 of file ParamReservoir.cpp.
 {
     gravity.activity = OCP_TRUE;
     vector<string> vbuf;
     ReadLine(ifs, vbuf);
     if (vbuf[0] == "/") return;
     DealDefault(vbuf);
     OCP_ASSERT(vbuf.size() == 4, "Wrong Keyword GRAVITY!");
     for (USI i = 0; i < 3; i++) {
         if (vbuf[i] != "DEFAULT") {
             gravity.data[i] = stod(vbuf[i]);
         }
     }
     cout << "---------------------" << endl
          << "GRAVITY" << endl
          << "---------------------" << endl;
     cout << gravity.data[0] << "  " << gravity.data[1] << "  " << gravity.data[2]
          << endl;
 }
References Type_A_r< T >::activity, and gravity.
InputGRID()
void ParamReservoir::InputGRID (ifstream & ifs, string & keyword)
TODO: Add Doxygen.
Input the keyword about grids, actually, it's a supplement for EQUALS. It supplies another way to input the params in EQUALS.
Definition at line 380 of file ParamReservoir.cpp.
 {
     vector<OCP_DBL>* objPtr = nullptr;
     objPtr = FindPtr(keyword);
     if (objPtr == nullptr) {
         OCP_ABORT("Unknown keyword!");
     }
     vector<string> vbuf;
     while (ReadLine(ifs, vbuf)) {
         if (vbuf[0] == "/") break;
         for (auto& str : vbuf) {
             // if m*n occurs, then push back n  m times
             auto pos = str.find('*');
             if (pos == string::npos) {
                 objPtr->push_back(stod(str));
             } else {
                 USI     len = str.size();
                 OCP_USI num = stoi(str.substr(0, pos));
                 OCP_DBL val = stod(str.substr(pos + 1, len - (pos + 1)));
                 for (USI i = 0; i < num; i++) objPtr->push_back(val);
             }
         }
     }
 }
References FindPtr(), OCP_ABORT, and ReadLine().
InputMISCSTR()
void ParamReservoir::InputMISCSTR (ifstream & ifs)
Input the Miscibility information.
Read data from the MISCSTR keyword.
Definition at line 613 of file ParamReservoir.cpp.
 {
     if (!comsParam.miscible) {
         OCP_WARNING("MISCIBLE has not been declared, this keyword will be ignored!");
     } else {
         vector<string> vbuf;
         ReadLine(ifs, vbuf);
         if (vbuf[0] == "/") return;
         if (vbuf.back() == "/") vbuf.pop_back();
         USI len = vbuf.size();
         for (USI i = 0; i < len; i++) {
             miscstr.surTenRef.push_back(stod(vbuf[i]));
         }
     }
     cout << "MISCSTR" << endl;
     for (auto& v : miscstr.surTenRef) cout << v << "   ";
     cout << endl << endl;
 }
References comsParam, ComponentParam::miscible, miscstr, OCP_WARNING, and ReadLine().
InputMULTIPLY()
void ParamReservoir::InputMULTIPLY (ifstream & ifs)
TODO: Add Doxygen.
Input the keyword: MULTIPLY. MULTIIPLY could multiply the value of a certain range of a variable by a coefficient.
Definition at line 448 of file ParamReservoir.cpp.
 {
     vector<string> vbuf;
     vector<USI>    index(6, 0);
     while (ReadLine(ifs, vbuf)) {
         if (vbuf[0] == "/") break;
         index[0] = 0, index[1] = dimens.nx - 1;
         index[2] = 0, index[3] = dimens.ny - 1;
         index[4] = 0, index[5] = dimens.nz - 1;
         string  objName = vbuf[0];
         OCP_DBL val     = stod(vbuf[1]);
         DealDefault(vbuf);
         for (USI n = 2; n < 8; n++) {
             if (vbuf[n] != "DEFAULT") index[n - 2] = stoi(vbuf[n]) - 1;
         }
         vector<OCP_DBL>* objPtr = FindPtr(objName);
         if (objPtr != nullptr) {
             if (objName == "TOPS") {
                 index[4] = index[5] = 0;
             }
             MultiplyVal(*objPtr, val, index);
         } else {
             OCP_ABORT("Wrong object name: " + objName);
         }
     }
 }
References DealDefault(), dimens, FindPtr(), MultiplyVal(), Dimens::nx, Dimens::ny, Dimens::nz, OCP_ABORT, and ReadLine().
InputRegion()
void ParamReservoir::InputRegion (ifstream & ifs, const string & keyword)
Input the keyword: SATNUM and PVTNUM.
Region information like SATNUM to decide which grid belongs to which saturation region, so corresponding saturation table will be used.
Definition at line 741 of file ParamReservoir.cpp.
 {
     Type_A_r<OCP_DBL>* ptr = &PVTNUM;
     USI                lim = NTPVT;
     if (keyword == "SATNUM") {
         ptr = &SATNUM;
         lim = NTSFUN;
     } else if (keyword == "ACTNUM") {
         ptr = &ACTNUM;
     } else if (keyword == "ROCKNUM") {
         ptr = &ROCKNUM;
     }
     ptr->activity = OCP_TRUE;
     ptr->data.reserve(numGrid);
     vector<string>  vbuf;
     vector<OCP_USI> obj;
     vector<USI>     region;
     while (ReadLine(ifs, vbuf)) {
         if (vbuf[0] == "/") break;
         for (auto& str : vbuf) {
             // if m*n occurs, then push back n  m times
             auto pos = str.find('*');
             if (pos == string::npos) {
                 ptr->data.push_back(stod(str));
             } else {
                 USI     len = str.size();
                 OCP_USI num = stoi(str.substr(0, pos));
                 OCP_DBL val = stod(str.substr(pos + 1, len - (pos + 1)));
                 for (USI i = 0; i < num; i++) ptr->data.push_back(val);
             }
         }
     }
     cout << "Number of Tables = " << lim << endl;
 }
References Type_A_r< T >::activity, ACTNUM, NTPVT, NTSFUN, PVTNUM, ROCKNUM, and SATNUM.
InputROCK()
void ParamReservoir::InputROCK (ifstream & ifs)
Read data from the ROCK keyword.
Input the keyword: ROCK. ROCK contains the compressibility factor and reference pressure at initial porosity.
Definition at line 518 of file ParamReservoir.cpp.
 {
     cout << "ROCK" << endl;
     vector<string> vbuf;
     while (true) {
         ReadLine(ifs, vbuf);
         if (vbuf[0] == "/") break;
         RockParam rock;
         rock.type = vbuf[0];
         rock.Pref = stod(vbuf[1]);
         rock.cp1 = stod(vbuf[2]);
         if (rock.type == "LINEAR02") {
             if (vbuf.size() > 3 && vbuf[3] != "/") {
                 rock.cp2 = stod(vbuf[3]);
             }
             else {
                 rock.cp2 = rock.cp1;
             }
         }
         rockSet.push_back(rock);
         cout << rock.type << "   " << rock.Pref << "   " << rock.cp1 << "   "
             << rock.cp2 << endl;
     }
     cout << "/" << endl;
 }
References RockParam::cp1, RockParam::cp2, RockParam::Pref, ReadLine(), rockSet, and RockParam::type.
InputROCKT()
void ParamReservoir::InputROCKT (ifstream & ifs)
input Rock information for thermal model
Read data from the ROCK keyword.
Definition at line 553 of file ParamReservoir.cpp.
 {
     cout << "ROCKT" << endl;
     RockParam rock;
     vector<string> vbuf;
     while (true) {
         ReadLine(ifs, vbuf);
         if (vbuf[0] == "/") break;
         USI index = 0;
         USI len = vbuf.size();
         while (index < len) {
             if (vbuf[index] == "*PORFORM") {
                 rock.type = vbuf[index + 1];
             }
             else if (vbuf[index] == "*PRPOR") {
                 rock.Pref = stod(vbuf[index + 1]);
             }
             else if (vbuf[index] == "*TRPOR") {
                 rock.Tref = stod(vbuf[index + 1]);
             }
             else if (vbuf[index] == "*CPOR") {
                 rock.cp1 = stod(vbuf[index + 1]);
             }
             else if (vbuf[index] == "*CTPOR") {
                 rock.ct = stod(vbuf[index + 1]);
             }
             else if (vbuf[index] == "*CPTPOR") {
                 rock.cpt = stod(vbuf[index + 1]);
             }
             else if (vbuf[index] == "*VOLCONST") {
                 if (vbuf[index + 1] == "BULK")
                     rock.ConstRock = OCP_FALSE;
             }
             else if (vbuf[index] == "*CP1") {
                 rock.HCP1 = stod(vbuf[index + 1]);
             }
             else if (vbuf[index] == "*CP2") {
                 rock.HCP2 = stod(vbuf[index + 1]);
             }
             index += 2;
         }
     }
     rockSet.push_back(rock);
     cout << "*PORFORM   " << rock.type << endl;
     cout << "*PRPOR     " << rock.Pref << endl;
     cout << "*TRPOR     " << rock.Tref << endl;
     cout << "*CPOR      " << rock.cp1 << endl;
     cout << "*CTPOR     " << rock.ct << endl;
     cout << "*CPTPOR    " << rock.cpt << endl;
     cout << "*VOLCONST  " << (rock.ConstRock ? "ROCK" : "BULK") << endl;
     cout << "*CP1       " << rock.HCP1 << endl;
     cout << "*CP2       " << rock.HCP2 << endl;
     cout << "/" << endl;
 }
References RockParam::ConstRock, RockParam::cp1, RockParam::cpt, RockParam::ct, RockParam::Pref, ReadLine(), RockParam::Tref, and RockParam::type.
InputRTEMP()
void ParamReservoir::InputRTEMP (ifstream & ifs)
Input the keyword: RTEMP. RTEMP gives the temperature of reservoir.
TODO: Add Doxygen.
Definition at line 317 of file ParamReservoir.cpp.
 {
     vector<string> vbuf;
     ReadLine(ifs, vbuf);
     if (vbuf[0] == "/") return;
     rsTemp = stod(vbuf[0]);
     cout << "RTEMP\n" << rsTemp << endl << endl;
 }
References ReadLine(), and rsTemp.
InputTABDIMS()
void ParamReservoir::InputTABDIMS (ifstream & ifs)
TABDIMS contains the num of saturation region and PVT region.
Read data from the TABDIMS keyword.
Definition at line 722 of file ParamReservoir.cpp.
 {
     vector<string> vbuf;
     ReadLine(ifs, vbuf);
     if (vbuf.size() < 3) {
         OCP_ABORT("Input the number of Saturation tables, PVT tables, and Rock tables in turn!");
     }
     NTSFUN = stoi(vbuf[0]);
     NTPVT  = stoi(vbuf[1]);
     NTROOC = stoi(vbuf[2]);
     cout << "TABDIMS" << endl;
     cout << NTSFUN << "   " << NTPVT << "   " << NTROOC << endl;
 }
References NTPVT, NTROOC, NTSFUN, OCP_ABORT, and ReadLine().
InputTABLE()
void ParamReservoir::InputTABLE (ifstream & ifs, const string & tabName)
Input PVTtable and SATtable such as SWOF, PVCO.
TODO: Add Doxygen.
Definition at line 481 of file ParamReservoir.cpp.
 {
     TableSet* obj;
     obj = FindPtr_T(tabName);
     if (obj == nullptr) {
         OCP_ABORT("Wrong table name :" + tabName);
     }
     USI col = obj->colNum;
     if (tabName == "ZMFVD") {
         if (!comps) OCP_ABORT("COMPS isn't set correctly!");
         obj->colNum = numCom + 1;
         col         = obj->colNum;
     }
     vector<vector<OCP_DBL>> tmpTab(col);
     vector<string> vbuf;
     while (ReadLine(ifs, vbuf)) {
         if (vbuf[0] == "/") break;
         for (USI i = 0; i < col; i++) {
             tmpTab[i].push_back(stod(vbuf[i]));
         }
         if (vbuf.back() == "/") {
             obj->data.push_back(tmpTab);
             for (USI j = 0; j < col; j++) {
                 tmpTab[j].clear();
             }
         }
     }
     if (!tmpTab[0].empty()) obj->data.push_back(tmpTab);
     obj->DisplayTable();
 }
References TableSet::colNum, comps, TableSet::data, TableSet::DisplayTable(), FindPtr_T(), numCom, OCP_ABORT, and ReadLine().
InputTHCON()
void ParamReservoir::InputTHCON (ifstream & ifs, const string & keyword)
Input the phase thermal conductivity.
Read data from the THCONO, THCONG, THCONW.
Definition at line 681 of file ParamReservoir.cpp.
 {
     vector<string> vbuf;
     ReadLine(ifs, vbuf);
     if (keyword == "THCONO") {
         thcono = stod(vbuf[0]);
     }
     else if (keyword == "THCONG") {
         thcong = stod(vbuf[0]);
     }
     else if (keyword == "THCONW") {
         thconw = stod(vbuf[0]);
     }
     cout << "THCONO\n" << thcono << endl << endl;
     cout << "THCONG\n" << thcong << endl << endl;
     cout << "THCONW\n" << thconw << endl << endl;
 }
References ReadLine(), thcong, thcono, and thconw.
MultiplyVal()
void ParamReservoir::MultiplyVal (vector< OCP_DBL > & obj, const OCP_DBL & val, const vector< USI > & index)
TODO: Add Doxygen.
It's used in InputMULTIPLY, multipling the value of a certain range of a variable by a coefficient.
Definition at line 263 of file ParamReservoir.cpp.
 {
     USI     Nx   = dimens.nx;
     USI     Ny   = dimens.ny;
     OCP_USI NxNy = Nx * Ny;
     OCP_USI id   = 0;
     for (USI k = index[4]; k <= index[5]; k++) {
         for (USI j = index[2]; j <= index[3]; j++) {
             for (USI i = index[0]; i <= index[1]; i++) {
                 id = k * NxNy + j * Nx + i;
                 obj[id] *= val;
             }
         }
     }
 }
References dimens, Dimens::nx, and Dimens::ny.
setVal()
template<typename T > void ParamReservoir::setVal (vector< T > & obj, const T & val, const vector< USI > & index)
It's used in InputEQUALS, assigning values in batches.
TODO: Add Doxygen.
Definition at line 224 of file ParamReservoir.cpp.
 {
     USI     Nx   = dimens.nx;
     USI     Ny   = dimens.ny;
     OCP_USI NxNy = Nx * Ny;
     OCP_USI id   = 0;
     for (USI k = index[4]; k <= index[5]; k++) {
         for (USI j = index[2]; j <= index[3]; j++) {
             for (USI i = index[0]; i <= index[1]; i++) {
                 id      = k * NxNy + j * Nx + i;
                 obj[id] = val;
             }
         }
     }
 }
References dimens, Dimens::nx, and Dimens::ny.
The documentation for this class was generated from the following files:
ParamReservoir.hpp
ParamReservoir.cpp