OpenCAEPoro: Solver Class Reference
Solver Class Reference
Solver class for overall solution methods.
#include <Solver.hpp>
Public Member Functions
void Setup (Reservoir &rs, const OCPControl &ctrl)
Setup Solver.
void InitReservoir (Reservoir &rs) const
Initialize the reservoir.
void RunSimulation (Reservoir &rs, OCPControl &ctrl, OCPOutput &output)
Start simulation.
Detailed Description
Solver class for overall solution methods.
Definition at line 21 of file Solver.hpp.
Member Function Documentation
InitReservoir()
void Solver::InitReservoir (Reservoir & rs) const
Initialize the reservoir.
Initialize the reservoir setting for different solution methods.
Definition at line 44 of file Solver.cpp.
 {
     switch (OCPModel)
     {
     case ISOTHERMALMODEL:
         InitReservoirIsoT(rs);
         break;
     case THERMALMODEL:
         InitReservoirT(rs);
         break;
     default:
         OCP_ABORT("WRONG MODEL!");
         break;
     }
 }
RunSimulation()
void Solver::RunSimulation (Reservoir & rs, OCPControl & ctrl, OCPOutput & output)
Start simulation.
Simulation will go through all time steps and call GoOneStep at each step.
Definition at line 74 of file Solver.cpp.
 {
     GetWallTime timer;
     timer.Start();
     output.PrintInfoSched(rs, ctrl, timer.Stop());
     USI numTSteps = ctrl.GetNumTSteps();
     for (USI d = 0; d < numTSteps - 1; d++) {
         rs.ApplyControl(d);
         ctrl.ApplyControl(d, rs);
         while (!ctrl.IsCriticalTime(d + 1)) {
             GoOneStep(rs, ctrl);
             output.SetVal(rs, ctrl);
             if (ctrl.printLevel >= PRINT_ALL) {
                 // Print Summary and critical information at every time step
                 output.PrintInfo();
             }
         }
         output.PrintInfoSched(rs, ctrl, timer.Stop());
         // rs.allWells.ShowWellStatus(rs.bulk);
     }
     if (rs.bulk.GetMixMode() == EOS_PVTW) {
         cout << "SSMSTA:     " << setw(12) << rs.bulk.GetSSMSTAiters() << setw(15)
              << rs.bulk.GetSSMSTAiters() * 1.0 / rs.bulk.GetSSMSTAcounts() << endl;
         cout << "NRSTA:      " << setw(12) << rs.bulk.GetNRSTAiters() << setw(15)
              << rs.bulk.GetNRSTAiters() * 1.0 / rs.bulk.GetNRSTAcounts() << endl;
         cout << "SSMSP:      " << setw(12) << rs.bulk.GetSSMSPiters() << setw(15)
              << rs.bulk.GetSSMSPiters() * 1.0 / rs.bulk.GetSSMSPcounts() << endl;
         cout << "NRSP:       " << setw(12) << rs.bulk.GetNRSPiters() << setw(15)
              << rs.bulk.GetNRSPiters() * 1.0 / rs.bulk.GetNRSPcounts() << endl;
         cout << "NRRR:       " << setw(12) << rs.bulk.GetRRiters() << setw(15)
              << rs.bulk.GetRRiters() * 1.0 / rs.bulk.GetRRcounts() << endl;
     }
     ctrl.RecordTotalTime(timer.Stop() / 1000);
 }
References Reservoir::ApplyControl(), OCPControl::ApplyControl(), EOS_PVTW, Bulk::GetMixMode(), OCPControl::GetNumTSteps(), OCPControl::IsCriticalTime(), OCPControl::RecordTotalTime(), GetWallTime::Start(), and GetWallTime::Stop().
The documentation for this class was generated from the following files:
Solver.hpp
Solver.cpp