OpenCAEPoro: IsothermalSolver Class Reference
IsothermalSolver Class Reference
IsothermalSolver class for fluid solution method.
#include <IsothermalSolver.hpp>
Public Member Functions
void SetupMethod (Reservoir &rs, const OCPControl &ctrl)
Setup the fluid solver.
void InitReservoir (Reservoir &rs) const
Initialize the Reservoir and prepare variables for some method.
void Prepare (Reservoir &rs, OCP_DBL &dt)
Prepare for assembling Mat.
void AssembleMat (const Reservoir &rs, const OCP_DBL &dt)
Assemble Mat.
void SolveLinearSystem (Reservoir &rs, OCPControl &ctrl)
Solve the linear system in single problem.
bool UpdateProperty (Reservoir &rs, OCPControl &ctrl)
Update properties of fluid.
bool FinishNR (Reservoir &rs, OCPControl &ctrl)
Finish the Newton-Raphson iteration.
void FinishStep (Reservoir &rs, OCPControl &ctrl)
Finish the current time step.
Detailed Description
IsothermalSolver class for fluid solution method.
Definition at line 19 of file IsothermalSolver.hpp.
Member Function Documentation
AssembleMat()
void IsothermalSolver::AssembleMat (const Reservoir & rs, const OCP_DBL & dt)
Assemble Mat.
Assemble linear systems for IMPEC and FIM.
Definition at line 96 of file IsothermalSolver.cpp.
 {
     switch (method)
     {
     case IMPEC:
     case AIMt:
         rs.AssembleMatIMPEC(LSolver, dt);
         break;
     case FIMn:
         fim_n.AssembleMat(LSolver, rs, dt);
         break;
     case FIM:
         fim.AssembleMat(LSolver, rs, dt);
         break;
     case AIMc:
         aimc.AssembleMat(LSolver, rs, dt);
         break;
     case AIMs:
         aims.AssembleMat(LSolver, rs, dt);
         break;
     default:
         OCP_ABORT("Wrong method type!");
     }
 }
References AIMc, AIMs, AIMt, OCP_AIMs::AssembleMat(), OCP_FIM::AssembleMat(), OCP_FIMn::AssembleMat(), OCP_AIMc::AssembleMat(), Reservoir::AssembleMatIMPEC(), FIM, FIMn, IMPEC, and OCP_ABORT.
FinishNR()
bool IsothermalSolver::FinishNR (Reservoir & rs, OCPControl & ctrl)
Finish the Newton-Raphson iteration.
Finish up Newton-Raphson iteration for IMPEC and FIM.
Definition at line 170 of file IsothermalSolver.cpp.
 {
     switch (method) {
         case IMPEC:
         case AIMt:
             return impec.FinishNR(rs);
             // return impec.FinishNR01(rs, ctrl);
         case AIMs:
             return aims.FinishNR(rs, ctrl);
         case FIMn:
             return fim_n.FinishNR(rs, ctrl);
         case FIM:
             return fim.FinishNR(rs, ctrl);
         case AIMc:
             return aimc.FinishNR(rs, ctrl);
         default:
             OCP_ABORT("Wrong method type!");
     }
 }
References AIMc, AIMs, AIMt, FIM, FIMn, OCP_IMPEC::FinishNR(), OCP_FIM::FinishNR(), OCP_AIMc::FinishNR(), OCP_AIMs::FinishNR(), IMPEC, and OCP_ABORT.
FinishStep()
void IsothermalSolver::FinishStep (Reservoir & rs, OCPControl & ctrl)
Finish the current time step.
Finish up time step for IMPEC and FIM.
Definition at line 191 of file IsothermalSolver.cpp.
 {
     switch (method)
     {
     case IMPEC:
     case AIMt:
         return impec.FinishStep(rs, ctrl);
     case FIMn:
         return fim_n.FinishStep(rs, ctrl);
     case FIM:
     case AIMc:
         return fim.FinishStep(rs, ctrl);
     case AIMs:
         return aims.FinishStep(rs, ctrl);
     default:
         OCP_ABORT("Wrong method type!");
     }
 }
References AIMc, AIMs, AIMt, FIM, FIMn, OCP_AIMs::FinishStep(), OCP_FIM::FinishStep(), IMPEC, and OCP_ABORT.
InitReservoir()
void IsothermalSolver::InitReservoir (Reservoir & rs) const
Initialize the Reservoir and prepare variables for some method.
Setup solution methods, including IMPEC and FIM.
Definition at line 44 of file IsothermalSolver.cpp.
 {
     switch (method)
     {
     case IMPEC:
     case AIMt:
     case AIMs:
         impec.InitReservoir(rs);
         break;
     case FIM:
         fim.InitReservoir(rs);
         break;
     case FIMn:
         fim_n.InitReservoir(rs);
         break;
     case AIMc:
         aimc.InitReservoir(rs);
         break;
     default:
         OCP_ABORT("Wrong method type!");
     }
 }
References AIMc, AIMs, AIMt, FIM, FIMn, IMPEC, OCP_IMPEC::InitReservoir(), OCP_FIM::InitReservoir(), OCP_FIMn::InitReservoir(), OCP_AIMc::InitReservoir(), and OCP_ABORT.
Prepare()
void IsothermalSolver::Prepare (Reservoir & rs, OCP_DBL & dt)
Prepare for assembling Mat.
Prepare solution methods, including IMPEC and FIM.
Definition at line 68 of file IsothermalSolver.cpp.
 {
     switch (method)
     {
     case IMPEC:
         impec.Prepare(rs, dt);
         break;
     case FIMn:
         fim_n.Prepare(rs, dt);
         break;
     case FIM:
         fim.Prepare(rs, dt);
         break;
     case AIMc:
         aimc.Prepare(rs, dt);
         break;
     case AIMs:
         aims.Prepare(rs, dt);
         break;
     case AIMt:
         aimt.Prepare(rs, dt);
         break;
     default:
         OCP_ABORT("Wrong method type!");
     }
 }
References AIMc, AIMs, AIMt, FIM, FIMn, IMPEC, OCP_ABORT, OCP_IMPEC::Prepare(), OCP_FIM::Prepare(), OCP_AIMc::Prepare(), OCP_AIMs::Prepare(), and OCP_AIMt::Prepare().
SetupMethod()
void IsothermalSolver::SetupMethod (Reservoir & rs, const OCPControl & ctrl)
Setup the fluid solver.
Setup solution methods, including IMPEC and FIM.
Definition at line 15 of file IsothermalSolver.cpp.
 {
     method = ctrl.GetMethod();
     switch (method)
     {
     case AIMt:
         aimt.Setup(rs, LSolver, auxLSolver, ctrl);
         break;
     case AIMs:
         aims.Setup(rs, LSolver, ctrl);
         break;
     case IMPEC:
         impec.Setup(rs, LSolver, ctrl);
         break;
     case AIMc:
         aimc.Setup(rs, LSolver, ctrl);
         break;
     case FIMn:
         fim_n.Setup(rs, LSolver, ctrl);
         break;
     case FIM:
     default:
         fim.Setup(rs, LSolver, ctrl);
         break;
     }
 }
References AIMc, AIMs, AIMt, FIM, FIMn, OCPControl::GetMethod(), IMPEC, OCP_IMPEC::Setup(), OCP_FIM::Setup(), OCP_AIMc::Setup(), OCP_AIMs::Setup(), and OCP_AIMt::Setup().
SolveLinearSystem()
void IsothermalSolver::SolveLinearSystem (Reservoir & rs, OCPControl & ctrl)
Solve the linear system in single problem.
Solve linear systems for IMPEC and FIM.
Definition at line 122 of file IsothermalSolver.cpp.
 {
     switch (method)
     {
     case IMPEC:
     case AIMt:
         impec.SolveLinearSystem(LSolver, rs, ctrl);
         break;
     case FIMn:
         fim_n.SolveLinearSystem(LSolver, rs, ctrl);
         break;
     case FIM:
         fim.SolveLinearSystem(LSolver, rs, ctrl);
         break;
     case AIMc:
         aimc.SolveLinearSystem(LSolver, rs, ctrl);
         break;
     case AIMs:
         aims.SolveLinearSystem(LSolver, rs, ctrl);
         break;
     default:
         OCP_ABORT("Wrong method type!");
     }
 }
References AIMc, AIMs, AIMt, FIM, FIMn, IMPEC, OCP_ABORT, OCP_IMPEC::SolveLinearSystem(), OCP_AIMc::SolveLinearSystem(), OCP_AIMs::SolveLinearSystem(), OCP_FIM::SolveLinearSystem(), and OCP_FIMn::SolveLinearSystem().
UpdateProperty()
bool IsothermalSolver::UpdateProperty (Reservoir & rs, OCPControl & ctrl)
Update properties of fluid.
Update physical properties for IMPEC and FIM.
Definition at line 148 of file IsothermalSolver.cpp.
 {
     switch (method) {
         case IMPEC:
             return impec.UpdateProperty(rs, ctrl);
             // return impec.UpdateProperty01(rs, ctrl);
         case FIMn:
             return fim_n.UpdateProperty(rs, ctrl);
         case FIM:
             return fim.UpdateProperty(rs, ctrl);
         case AIMc:
             return aimc.UpdateProperty(rs, ctrl);
         case AIMs:
             return aims.UpdateProperty(rs, ctrl);
         case AIMt:
             return aimt.UpdateProperty(rs, ctrl, auxLSolver);
         default:
             OCP_ABORT("Wrong method type!");
     }
 }
References AIMc, AIMs, AIMt, FIM, FIMn, IMPEC, OCP_ABORT, OCP_IMPEC::UpdateProperty(), OCP_FIM::UpdateProperty(), OCP_FIMn::UpdateProperty(), OCP_AIMc::UpdateProperty(), OCP_AIMs::UpdateProperty(), and OCP_AIMt::UpdateProperty().
The documentation for this class was generated from the following files:
IsothermalSolver.hpp
IsothermalSolver.cpp