OpenCAEPoro: LinearSolver Class Reference
LinearSolver Class Reference
Linear solvers for discrete systems.
#include <LinearSolver.hpp>
Public Member Functions
void AllocateRowMem (const OCP_USI &dimMax, const USI &nb)
Allocate memory for linear system with max possible number of rows.
void AllocateColMem ()
Allocate memory for each matrix row with max possible number of columns.
void AllocateFasp ()
Allocate memory for scalar-value problems in FASP.
void AllocateBFasp ()
Allocate memory for vector-value problems in FASP.
void RowCapPlus (const OCP_USI &row, const USI &n)
Enlarge row capacity. // TODO: maybe should be called EnlargeRowCap?
void SetupParam (const string &dir, const string &file)
Setup solver param for scalar-value problems from input file.
void SetupParamB (const string &dir, const string &file)
Setup solver param for vector-value problems from input file.
vector< OCP_DBL > & GetSolution ()
Return the solution.
void CheckVal () const
Check whether NAN or INF occurs in solution, used in debug mode.
void OutputLinearSystem (const string &fileA, const string &fileb) const
Output the mat and rhs to fileA and fileb. //TODO: output to some obj?
void OutputSolution (const string &filename) const
Output the solution to a disk file name.
void InitParam_Fasp ()
Initialize the solver param for FASP with default values.
void ReadParam_Fasp ()
Read the solver param for FASP from a file.
void AssembleMat_Fasp ()
Convert the internal matrix into FASP format.
int FaspSolve ()
Solve the linear system using FASP and return the status.
void ClearData ()
Clear the internal matrix data for scalar-value problems.
void InitParam_BFasp ()
Initialize the solver param for BFASP with default values.
void ReadParam_BFasp ()
Read the solver param for BFASP from a file.
void AssembleMat_BFasp ()
Convert the internal matrix into BFASP format.
void AssembleRhs_BFasp (const vector< OCP_DBL > &rhs)
Convert the internal right-hand side into BFASP format.
void Decoupling (dBSRmat *Absr, dvector *b, dBSRmat *Asc, dvector *fsc, ivector *order, double *Dmatvec, int decouple_type)
Decoupling strategies for vector-value problems.
int BFaspSolve ()
Solve the linear system using BFASP and return the status.
void ClearDataB ()
Clear the internal matrix data for vector-value problems.
Friends
class OpenCAEPoro
class BulkConn
class Well
Detailed Description
Linear solvers for discrete systems.
Definition at line 57 of file LinearSolver.hpp.
Member Function Documentation
AllocateBFasp()
void LinearSolver::AllocateBFasp ()
Allocate memory for vector-value problems in FASP.
Definition at line 45 of file LinearSolver.cpp.
{
    OCP_USI nnz = 0;
    for (OCP_USI n = 0; n < maxDim; n++) {
        nnz += rowCapacity[n];
    }
    A_BFasp = fasp_dbsr_create(maxDim, maxDim, nnz, blockDim, 0);
    Asc     = fasp_dbsr_create(maxDim, maxDim, nnz, blockDim, 0);
    fsc     = fasp_dvec_create(maxDim * blockDim);
    order   = fasp_ivec_create(maxDim);
    Dmat.resize(maxDim * blockSize);
}
AllocateColMem()
void LinearSolver::AllocateColMem ()
Allocate memory for each matrix row with max possible number of columns.
Definition at line 28 of file LinearSolver.cpp.
{
    for (OCP_USI n = 0; n < maxDim; n++) {
        colId[n].reserve(rowCapacity[n]);
        val[n].reserve(rowCapacity[n] * blockSize);
    }
}
AllocateFasp()
void LinearSolver::AllocateFasp ()
Allocate memory for scalar-value problems in FASP.
Definition at line 36 of file LinearSolver.cpp.
{
    OCP_USI nnz = 0;
    for (OCP_USI n = 0; n < maxDim; n++) {
        nnz += rowCapacity[n];
    }
    A_Fasp = fasp_dcsr_create(maxDim, maxDim, nnz);
}
AllocateRowMem()
void LinearSolver::AllocateRowMem (const OCP_USI & dimMax, const USI & nb)
Allocate memory for linear system with max possible number of rows.
Definition at line 14 of file LinearSolver.cpp.
{
    blockSize = nb * nb;
    blockDim  = nb;
    maxDim    = dimMax;
    rowCapacity.resize(maxDim);
    colId.resize(maxDim);
    val.resize(maxDim);
    diagPtr.resize(maxDim);
    diagVal.resize(maxDim * blockSize);
    b.resize(maxDim * blockDim);
    u.resize(maxDim * blockDim);
}
AssembleMat_BFasp()
void LinearSolver::AssembleMat_BFasp ()
Convert the internal matrix into BFASP format.
Definition at line 116 of file LinearSolver.cpp.
{
    OCP_USI nrow = dim * blockDim;
    // b & x
    b_BFasp.row = nrow;
    b_BFasp.val = b.data();
    x_BFasp.row = nrow;
    x_BFasp.val = u.data();
    // fsc & order
    fsc.row   = nrow;
    order.row = nrow;
    // nnz
    OCP_USI nnz = 0;
    for (OCP_USI i = 0; i < dim; i++) {
        nnz += colId[i].size();
    }
    // Asc
    Asc.ROW = dim;
    Asc.COL = dim;
    Asc.nb  = blockDim;
    Asc.NNZ = nnz;
    // A
    A_BFasp.ROW = dim;
    A_BFasp.COL = dim;
    A_BFasp.nb  = blockDim;
    A_BFasp.NNZ = nnz;
    OCP_USI count  = 0;
    OCP_USI count2 = 0;
    OCP_USI size_row;
    A_BFasp.IA[0] = 0;
    for (OCP_USI i = 1; i < dim + 1; i++) {
        USI nnb_Row   = colId[i - 1].size();
        A_BFasp.IA[i] = A_BFasp.IA[i - 1] + nnb_Row;
        for (USI j = 0; j < nnb_Row; j++) {
            A_BFasp.JA[count] = colId[i - 1][j];
            count++;
        }
        size_row = nnb_Row * blockSize;
        for (USI k = 0; k < size_row; k++) {
            A_BFasp.val[count2] = val[i - 1][k];
            count2++;
        }
    }
}
AssembleMat_Fasp()
void LinearSolver::AssembleMat_Fasp ()
Convert the internal matrix into FASP format.
Definition at line 84 of file LinearSolver.cpp.
{
    // b & x
    b_Fasp.row = dim;
    b_Fasp.val = b.data();
    x_Fasp.row = dim;
    x_Fasp.val = u.data();
    // A
    OCP_USI nnz = 0;
    for (OCP_USI i = 0; i < dim; i++) {
        nnz += colId[i].size();
    }
    A_Fasp.row = dim;
    A_Fasp.col = dim;
    A_Fasp.nnz = nnz;
    // IA
    OCP_USI count = 0;
    A_Fasp.IA[0]  = 0;
    for (OCP_USI i = 1; i < dim + 1; i++) {
        USI nnz_Row  = colId[i - 1].size();
        A_Fasp.IA[i] = A_Fasp.IA[i - 1] + nnz_Row;
        for (USI j = 0; j < nnz_Row; j++) {
            A_Fasp.JA[count]  = colId[i - 1][j];
            A_Fasp.val[count] = val[i - 1][j];
            count++;
        }
    }
}
AssembleRhs_BFasp()
void LinearSolver::AssembleRhs_BFasp (const vector< OCP_DBL > & rhs)
Convert the internal right-hand side into BFASP format.
Definition at line 166 of file LinearSolver.cpp.
{
    OCP_USI nrow = dim * blockDim;
    for (OCP_USI i = 0; i < nrow; i++) {
        b[i] = rhs[i];
    }
}
BFaspSolve()
int LinearSolver::BFaspSolve ()
Solve the linear system using BFASP and return the status.
Definition at line 471 of file LinearSolver.cpp.
{
    int status = FASP_SUCCESS;
    // Set local parameters
    const int print_level  = inParam.print_level;
    const int solver_type  = inParam.solver_type;
    const int decoup_type  = inParam.decoup_type;
    const int precond_type = inParam.precond_type;
    const int output_type  = inParam.output_type;
    if (output_type) {
        const char* outputfile = "../output/test.out";
        printf("Redirecting outputs to file: %s ...\n", outputfile);
        freopen(outputfile, "w", stdout); // open a file for stdout
    }
    fasp_dvec_set(x_BFasp.row, &x_BFasp, 0);
    // Preconditioned Krylov methods
    if (solver_type >= 1 && solver_type <= 10) {
        // Preconditioned Krylov methods in BSR format
        switch (precond_type) {
            case PC_NULL:
                status =
                    fasp_solver_dbsr_krylov(&A_BFasp, &b_BFasp, &x_BFasp, &itParam);
                break;
            case PC_DIAG:
                status = fasp_solver_dbsr_krylov_diag(&A_BFasp, &b_BFasp, &x_BFasp,
                                                      &itParam);
                break;
            case PC_BILU:
                status = fasp_solver_dbsr_krylov_ilu(&A_BFasp, &b_BFasp, &x_BFasp,
                                                     &itParam, &iluParam);
                break;
            case PC_FASP1:
                Decoupling(&A_BFasp, &b_BFasp, &Asc, &fsc, &order, Dmat.data(),
                           decoup_type);
                status = fasp_solver_dbsr_krylov_FASP1a(
                    &Asc, &fsc, &x_BFasp, &itParam, &iluParam, &amgParam, NULL, &order);
                break;
            case PC_FASP1_SHARE: // zhaoli 2021.03.24
                Decoupling(&A_BFasp, &b_BFasp, &Asc, &fsc, &order, Dmat.data(),
                           decoup_type);
                status = fasp_solver_dbsr_krylov_FASP1a_share_interface(
                    &Asc, &fsc, &x_BFasp, &itParam, &iluParam, &amgParam, NULL, &order,
                    RESET_CONST);
                break;
            case PC_FASP2:
                Decoupling(&A_BFasp, &b_BFasp, &Asc, &fsc, &order, Dmat.data(),
                           decoup_type);
                status = fasp_solver_dbsr_krylov_FASP2(
                    &Asc, &fsc, &x_BFasp, &itParam, &iluParam, &amgParam, NULL, &order);
                break;
            case PC_FASP3:
                Decoupling(&A_BFasp, &b_BFasp, &Asc, &fsc, &order, Dmat.data(),
                           decoup_type);
                status = fasp_solver_dbsr_krylov_FASP3(
                    &Asc, &fsc, &x_BFasp, &itParam, &iluParam, &amgParam, NULL, &order);
                break;
            case PC_FASP4_SHARE: // zhaoli 2021.04.24
                Decoupling(&A_BFasp, &b_BFasp, &Asc, &fsc, &order, Dmat.data(),
                           decoup_type);
                status = fasp_solver_dbsr_krylov_FASP4_share_interface(
                    &Asc, &fsc, &x_BFasp, &itParam, &iluParam, &amgParam, NULL, &order,
                    RESET_CONST);
                break;
            case PC_FASP5:
                Decoupling(&A_BFasp, &b_BFasp, &Asc, &fsc, &order, Dmat.data(),
                           decoup_type);
                status = fasp_solver_dbsr_krylov_FASP5(
                    &Asc, &fsc, &x_BFasp, &itParam, &iluParam, &amgParam, NULL, &order);
                break;
            default: // case PC_FASP4:
                Decoupling(&A_BFasp, &b_BFasp, &Asc, &fsc, &order, Dmat.data(),
                           decoup_type);
                status = fasp_solver_dbsr_krylov_FASP4(
                    &Asc, &fsc, &x_BFasp, &itParam, &iluParam, &amgParam, NULL, &order);
        }
    }
#if WITH_MUMPS // use MUMPS directly
    else if (solver_type == SOLVER_MUMPS) {
        dCSRmat Acsr = fasp_format_dbsr_dcsr(&A_BFasp);
        status       = fasp_solver_mumps(&Acsr, &b_BFasp, &x_BFasp, print_level);
        fasp_dcsr_free(&Acsr);
        if (status >= 0) status = 1; // Direct solver returns 1
    }
#endif
#if WITH_SuperLU // use SuperLU directly
    else if (solver_type == SOLVER_SUPERLU) {
        dCSRmat Acsr = fasp_format_dbsr_dcsr(&A_BFasp);
        status       = fasp_solver_superlu(&Acsr, &b_BFasp, &x_BFasp, print_level);
        fasp_dcsr_free(&Acsr);
        if (status >= 0) status = 1; // Direct solver returns 1
    }
#endif
#if WITH_UMFPACK // use UMFPACK directly
    else if (solver_type == SOLVER_UMFPACK) {
        // Need to sort the matrix A for UMFPACK to work
        dCSRmat Acsr    = fasp_format_dbsr_dcsr(&A_BFasp);
        dCSRmat A_trans = fasp_dcsr_create(Acsr.row, Acsr.col, Acsr.nnz);
        fasp_dcsr_transz(&Acsr, NULL, &A_trans);
        fasp_dcsr_sort(&A_trans);
        status = fasp_solver_umfpack(&A_trans, &b_BFasp, &x_BFasp, print_level);
        fasp_dcsr_free(&A_trans);
        fasp_dcsr_free(&Acsr);
        if (status >= 0) status = 1; // Direct solver returns 1
    }
#endif
#ifdef WITH_PARDISO // use PARDISO directly
    else if (solver_type == SOLVER_PARDISO) {
        dCSRmat Acsr = fasp_format_dbsr_dcsr(&A_BFasp);
        fasp_dcsr_sort(&Acsr);
        status = fasp_solver_pardiso(&Acsr, &b_BFasp, &x_BFasp, print_level);
        fasp_dcsr_free(&Acsr);
        if (status >= 0) status = 1; // Direct solver returns 1
    }
#endif
    else {
        printf("### ERROR: Wrong solver type %d!!!\n", solver_type);
        status = ERROR_SOLVER_TYPE;
    }
    if (print_level > PRINT_MIN) {
        if (status < 0) {
            cout << "\n### WARNING: Solver does not converge!\n" << endl;
        } else {
            cout << "\nSolver converges successfully!\n" << endl;
        }
    }
    if (output_type) fclose(stdout);
    return status;
}
References Decoupling(), PC_BILU, PC_DIAG, PC_FASP1, PC_FASP1_SHARE, PC_FASP2, PC_FASP3, PC_FASP4_SHARE, PC_FASP5, PC_NULL, and RESET_CONST.
CheckVal()
void LinearSolver::CheckVal () const
Check whether NAN or INF occurs in solution, used in debug mode.
Definition at line 613 of file LinearSolver.cpp.
{
    for (OCP_USI n = 0; n < dim; n++) {
        for (auto v : val[n]) {
            if (!isfinite(v)) {
                OCP_ABORT("NAN or INF in MAT");
            }
        }
    }
}
References OCP_ABORT.
ClearData()
void LinearSolver::ClearData ()
Clear the internal matrix data for scalar-value problems.
Definition at line 58 of file LinearSolver.cpp.
{
    for (OCP_USI i = 0; i < maxDim; i++) {
        colId[i].clear();
        val[i].clear();
    }
    // diagPtr.assign(maxDim, 0);
    diagVal.assign(maxDim * blockSize, 0);
    b.assign(maxDim * blockDim, 0);
    // In fact, for linear system the current solution is a good initial solution for
    // next step, so u will not be set to zero. u.assign(maxDim, 0);
}
ClearDataB()
void LinearSolver::ClearDataB ()
Clear the internal matrix data for vector-value problems.
Definition at line 71 of file LinearSolver.cpp.
{
    for (OCP_USI i = 0; i < maxDim; i++) {
        colId[i].clear();
        val[i].clear();
    }
    // diagPtr.assign(maxDim, 0);
    diagVal.assign(maxDim * blockSize, 0);
    Dmat.assign(Dmat.size(), 0);
    // In fact, for linear system the current solution is a good initial solution for
    // next step, so u will not be set to zero. u.assign(maxDim, 0);
}
Decoupling()
void LinearSolver::Decoupling (dBSRmat * Absr, dvector * b, dBSRmat * Asc, dvector * fsc, ivector * order, double * Dmatvec, int decouple_type)
Decoupling strategies for vector-value problems.
Applying a decoupling algorithm for linear systems of FIM.
Definition at line 468 of file Decoupling.cpp.
{
    int              nrow = Absr->ROW;
    int              nb   = Absr->nb;
    double*          Dmat = Dmatvec;
    precond_diag_bsr diagA;
    switch (decoupleType) {
        case 2:
            decouple_anl(Absr, Dmat, Asc);
            break;
        case 3:
            decouple_quasi(Absr, Dmat, Asc);
            break;
        case 4:
            decouple_trueabf(Absr, Dmat, Asc);
            break;
        case 5:
            decouple_abftrue(Absr, Dmat, Asc);
            break;
        case 6:
            decouple_abftrue(Absr, Dmat, Asc);
            break;
        case 7:
            decouple_truetrans_alg(Absr, Dmat, Asc);
            break;
        case 8:
            decouple_truetrans(Absr, Dmat, Asc);
            break;
        case 9:
            decouple_true_scale(Absr, Dmat, Asc);
            break;
        case 10:
            decouple_rotate(Absr, Dmat, Asc);
            break;
        default: // case 1:
            decouple_abf(Absr, Dmat, Asc);
    }
    diagA.diag.row = nrow * nb * nb;
    diagA.diag.val = Dmat;
    diagA.nb       = nb;
    fasp_precond_dbsr_diag(b->val, fsc->val, &diagA);
    // Natural ordering
    for (int i = 0; i < nrow; ++i) order->val[i] = i;
}
FaspSolve()
int LinearSolver::FaspSolve ()
Solve the linear system using FASP and return the status.
Definition at line 174 of file LinearSolver.cpp.
{
    int status = FASP_SUCCESS;
    const int print_level  = inParam.print_level;
    const int solver_type  = inParam.solver_type;
    const int precond_type = inParam.precond_type;
    const int output_type  = inParam.output_type;
    if (output_type) {
        const char* outputfile = "out/Solver.out";
        printf("Redirecting outputs to file: %s ...\n", outputfile);
        freopen(outputfile, "w", stdout); // open a file for stdout
    }
    // Preconditioned Krylov methods
    if (solver_type >= 1 && solver_type <= 20) {
        // Using no preconditioner for Krylov iterative methods
        if (precond_type == PREC_NULL) {
            status = fasp_solver_dcsr_krylov(&A_Fasp, &b_Fasp, &x_Fasp, &itParam);
        }
        // Using diag(A) as preconditioner for Krylov iterative methods
        else if (precond_type == PREC_DIAG) {
            status = fasp_solver_dcsr_krylov_diag(&A_Fasp, &b_Fasp, &x_Fasp, &itParam);
        }
        // Using AMG as preconditioner for Krylov iterative methods
        else if (precond_type == PREC_AMG || precond_type == PREC_FMG) {
            if (print_level > PRINT_NONE) fasp_param_amg_print(&amgParam);
            status = fasp_solver_dcsr_krylov_amg(&A_Fasp, &b_Fasp, &x_Fasp, &itParam,
                                                 &amgParam);
        }
        // Using ILU as preconditioner for Krylov iterative methods
        else if (precond_type == PREC_ILU) {
            if (print_level > PRINT_NONE) fasp_param_ilu_print(&iluParam);
            status = fasp_solver_dcsr_krylov_ilu(&A_Fasp, &b_Fasp, &x_Fasp, &itParam,
                                                 &iluParam);
        }
        // Undefined iterative methods
        else {
            printf("### ERROR: Wrong preconditioner type %d!!!\n", precond_type);
            status = ERROR_SOLVER_PRECTYPE;
        }
    }
    // AMG as the iterative solver
    else if (solver_type == SOLVER_AMG) {
        if (print_level > PRINT_NONE) fasp_param_amg_print(&amgParam);
        fasp_solver_amg(&A_Fasp, &b_Fasp, &x_Fasp, &amgParam);
    }
    // Full AMG as the iterative solver
    else if (solver_type == SOLVER_FMG) {
        if (print_level > PRINT_NONE) fasp_param_amg_print(&amgParam);
        fasp_solver_famg(&A_Fasp, &b_Fasp, &x_Fasp, &amgParam);
    }
#if WITH_MUMPS // use MUMPS directly
    else if (solver_type == SOLVER_MUMPS) {
        status = fasp_solver_mumps(&A_Fasp, &b_Fasp, &x_Fasp, print_level);
        if (status >= 0) status = 1; // Direct solver returns 1
    }
#endif
#if WITH_SuperLU // use SuperLU directly
    else if (solver_type == SOLVER_SUPERLU) {
        status = fasp_solver_superlu(&A_Fasp, &b_Fasp, &x_Fasp, print_level);
        if (status >= 0) status = 1; // Direct solver returns 1
    }
#endif
#if WITH_UMFPACK // use UMFPACK directly
    else if (solver_type == SOLVER_UMFPACK) {
        // Need to sort the matrix A for UMFPACK to work
        dCSRmat A_trans = fasp_dcsr_create(A_Fasp.row, A_Fasp.col, A_Fasp.nnz);
        fasp_dcsr_transz(&A_Fasp, NULL, &A_trans);
        fasp_dcsr_sort(&A_trans);
        status = fasp_solver_umfpack(&A_trans, &b_Fasp, &x_Fasp, print_level);
        fasp_dcsr_free(&A_trans);
        if (status >= 0) status = 1; // Direct solver returns 1
    }
#endif
#ifdef WITH_PARDISO // use PARDISO directly
    else if (solver_type == SOLVER_PARDISO) {
        fasp_dcsr_sort(&A_Fasp);
        status = fasp_solver_pardiso(&A_Fasp, &b_Fasp, &x_Fasp, print_level);
        if (status >= 0) status = 1; // Direct solver returns 1
    }
#endif
    else {
        printf("### ERROR: Wrong solver type %d!!!\n", solver_type);
        status = ERROR_SOLVER_TYPE;
    }
    if (status < 0) {
        printf("### ERROR: Solver failed! Exit status = %d.\n\n", status);
    }
    if (output_type) fclose(stdout);
    return status;
}
GetSolution()
vector< OCP_DBL > & LinearSolver::GetSolution () inline
Return the solution.
Definition at line 81 of file LinearSolver.hpp.
{ return u; }
InitParam_BFasp()
void LinearSolver::InitParam_BFasp ()
Initialize the solver param for BFASP with default values.
Definition at line 624 of file LinearSolver.cpp.
{
    // Input/output
    inParam.print_level = PRINT_MIN;
    inParam.output_type = 0;
    // Problem information
    inParam.solver_type  = SOLVER_VFGMRES;
    inParam.decoup_type  = 1;
    inParam.precond_type = 64;
    inParam.stop_type    = STOP_REL_RES;
    // Solver parameters
    inParam.itsolver_tol   = 1e-3;
    inParam.itsolver_maxit = 100;
    inParam.restart        = 30;
    // ILU method parameters
    inParam.ILU_type    = ILUk;
    inParam.ILU_lfil    = 0;
    inParam.ILU_droptol = 0.001;
    inParam.ILU_relax   = 0;
    inParam.ILU_permtol = 0.0;
    // Schwarz method parameters
    inParam.SWZ_mmsize    = 200;
    inParam.SWZ_maxlvl    = 2;
    inParam.SWZ_type      = 1;
    inParam.SWZ_blksolver = SOLVER_DEFAULT;
    // AMG method parameters
    inParam.AMG_type                = CLASSIC_AMG;
    inParam.AMG_levels              = 20;
    inParam.AMG_cycle_type          = V_CYCLE;
    inParam.AMG_smoother            = SMOOTHER_GS;
    inParam.AMG_smooth_order        = CF_ORDER;
    inParam.AMG_presmooth_iter      = 1;
    inParam.AMG_postsmooth_iter     = 1;
    inParam.AMG_relaxation          = 1.0;
    inParam.AMG_coarse_dof          = 500;
    inParam.AMG_coarse_solver       = 0;
    inParam.AMG_tol                 = 1e-6;
    inParam.AMG_maxit               = 1;
    inParam.AMG_ILU_levels          = 0;
    inParam.AMG_SWZ_levels          = 0;
    inParam.AMG_coarse_scaling      = OFF; // Require investigation --Chensong
    inParam.AMG_amli_degree         = 1;
    inParam.AMG_nl_amli_krylov_type = 2;
    // Classical AMG specific
    inParam.AMG_coarsening_type      = 1;
    inParam.AMG_interpolation_type   = 1;
    inParam.AMG_max_row_sum          = 0.9;
    inParam.AMG_strong_threshold     = 0.3;
    inParam.AMG_truncation_threshold = 0.2;
    inParam.AMG_aggressive_level     = 0;
    inParam.AMG_aggressive_path      = 1;
    // Aggregation AMG specific
    inParam.AMG_aggregation_type   = PAIRWISE;
    inParam.AMG_quality_bound      = 8.0;
    inParam.AMG_pair_number        = 2;
    inParam.AMG_strong_coupled     = 0.25;
    inParam.AMG_max_aggregation    = 9;
    inParam.AMG_tentative_smooth   = 0.67;
    inParam.AMG_smooth_filter      = ON;
    inParam.AMG_smooth_restriction = ON;
}
InitParam_Fasp()
void LinearSolver::InitParam_Fasp ()
Initialize the solver param for FASP with default values.
Definition at line 403 of file LinearSolver.cpp.
{
    // Input/output
    inParam.print_level = PRINT_MIN;
    inParam.output_type = 0;
    // Problem information
    inParam.solver_type  = SOLVER_VFGMRES;
    inParam.precond_type = PREC_AMG;
    inParam.stop_type    = STOP_REL_RES;
    // LinearSolver parameters
    inParam.itsolver_tol   = 1e-4;
    inParam.itsolver_maxit = 100;
    inParam.restart        = 30;
    // ILU method parameters
    inParam.ILU_type    = ILUk;
    inParam.ILU_lfil    = 0;
    inParam.ILU_droptol = 0.001;
    inParam.ILU_relax   = 0;
    inParam.ILU_permtol = 0.0;
    // Schwarz method parameters
    inParam.SWZ_mmsize    = 200;
    inParam.SWZ_maxlvl    = 2;
    inParam.SWZ_type      = 1;
    inParam.SWZ_blksolver = SOLVER_DEFAULT;
    // AMG method parameters
    inParam.AMG_type                = CLASSIC_AMG;
    inParam.AMG_levels              = 20;
    inParam.AMG_cycle_type          = V_CYCLE;
    inParam.AMG_smoother            = SMOOTHER_GS;
    inParam.AMG_smooth_order        = CF_ORDER;
    inParam.AMG_presmooth_iter      = 1;
    inParam.AMG_postsmooth_iter     = 1;
    inParam.AMG_relaxation          = 1.0;
    inParam.AMG_coarse_dof          = 500;
    inParam.AMG_coarse_solver       = 0;
    inParam.AMG_tol                 = 1e-6;
    inParam.AMG_maxit               = 1;
    inParam.AMG_ILU_levels          = 0;
    inParam.AMG_SWZ_levels          = 0;
    inParam.AMG_coarse_scaling      = OFF;
    inParam.AMG_amli_degree         = 1;
    inParam.AMG_nl_amli_krylov_type = 2;
    // Classical AMG specific
    inParam.AMG_coarsening_type      = 1;
    inParam.AMG_interpolation_type   = 1;
    inParam.AMG_max_row_sum          = 0.9;
    inParam.AMG_strong_threshold     = 0.3;
    inParam.AMG_truncation_threshold = 0.2;
    inParam.AMG_aggressive_level     = 0;
    inParam.AMG_aggressive_path      = 1;
    // Aggregation AMG specific
    inParam.AMG_aggregation_type   = PAIRWISE;
    inParam.AMG_quality_bound      = 8.0;
    inParam.AMG_pair_number        = 2;
    inParam.AMG_strong_coupled     = 0.25;
    inParam.AMG_max_aggregation    = 9;
    inParam.AMG_tentative_smooth   = 0.67;
    inParam.AMG_smooth_filter      = ON;
    inParam.AMG_smooth_restriction = ON;
}
OutputLinearSystem()
void LinearSolver::OutputLinearSystem (const string & fileA, const string & fileb) const
Output the mat and rhs to fileA and fileb. //TODO: output to some obj?
Definition at line 283 of file LinearSolver.cpp.
{
    string FileA = solveDir + fileA;
    string Fileb = solveDir + fileb;
    if (blockDim == 1) {
        // csr format
        ofstream outA(FileA);
        if (!outA.is_open()) cout << "Can not open " << FileA << endl;
        outA << A_Fasp.row << endl;
        OCP_USI nnz0 = A_Fasp.nnz;
        for (OCP_USI i = 0; i < A_Fasp.row + 1; i++) outA << A_Fasp.IA[i] + 1 << endl;
        for (OCP_USI i = 0; i < nnz0; i++) outA << A_Fasp.JA[i] + 1 << endl;
        for (OCP_USI i = 0; i < nnz0; i++) outA << A_Fasp.val[i] << endl;
        outA.close();
        // out rhs
        ofstream outb(Fileb);
        if (!outb.is_open()) cout << "Can not open " << Fileb << endl;
        outb << b_Fasp.row << endl;
        for (OCP_USI i = 0; i < b_Fasp.row; i++) outb << b_Fasp.val[i] << endl;
        outb.close();
    } else {
        // bsr mat
        ofstream outA(FileA);
        if (!outA.is_open()) cout << "Can not open " << FileA << endl;
        outA << A_BFasp.ROW << endl;
        outA << A_BFasp.nb << endl;
        OCP_USI nnz0 = A_BFasp.NNZ;
        OCP_USI nnz  = A_BFasp.NNZ * blockSize;
        for (OCP_USI i = 0; i < A_BFasp.ROW + 1; i++) outA << A_BFasp.IA[i] + 1 << endl;
        for (OCP_USI i = 0; i < nnz0; i++) outA << A_BFasp.JA[i] + 1 << endl;
        for (OCP_USI i = 0; i < nnz; i++) outA << A_BFasp.val[i] << endl;
        outA.close();
        // out rhs
        ofstream outb(Fileb);
        if (!outb.is_open()) cout << "Can not open " << Fileb << endl;
        outb << b_BFasp.row << endl;
        OCP_USI nrow = b_BFasp.row;
        for (OCP_USI i = 0; i < nrow; i++) outb << b_BFasp.val[i] << endl;
        outb.close();
    }
}
OutputSolution()
void LinearSolver::OutputSolution (const string & filename) const
Output the solution to a disk file name.
Definition at line 326 of file LinearSolver.cpp.
{
    string   FileU = solveDir + fileU;
    ofstream outu(FileU);
    if (!outu.is_open()) cout << "Can not open " << FileU << endl;
    outu << dim << endl;
    OCP_USI nrow = dim * blockDim;
    for (OCP_USI i = 0; i < nrow; i++) outu << u[i] << endl;
    outu.close();
}
ReadParam_BFasp()
void LinearSolver::ReadParam_BFasp ()
Read the solver param for BFASP from a file.
Definition at line 355 of file LinearSolver.cpp.
{
    string file = solveDir + solveFile;
    InitParam_BFasp(); // Set default solver parameters
    std::ifstream ifs(file);
    if (!ifs.is_open()) {
        std::cout << "The input file " << file << " is missing!" << std::endl;
        file = solveDir + "../conf/csr.dat";
        ifs.open(file);
        if (!ifs.is_open()) {
            std::cout << "The input file " << file << " is missing!" << std::endl;
            std::cout << "Using the default parameters of FASP" << std::endl;
        } else {
            ifs.close();
            std::cout << "Using the input file " << file << std::endl;
            fasp_param_input(file.data(), &inParam);
        }
    } else {
        ifs.close(); // if file has been opened, close it first
        fasp_param_input(file.data(), &inParam);
    }
    fasp_param_init(&inParam, &itParam, &amgParam, &iluParam, &swzParam);
}
References InitParam_BFasp().
ReadParam_Fasp()
void LinearSolver::ReadParam_Fasp ()
Read the solver param for FASP from a file.
Definition at line 379 of file LinearSolver.cpp.
{
    string file = solveDir + solveFile;
    InitParam_Fasp(); // Set default solver parameters
    std::ifstream ifs(file);
    if (!ifs.is_open()) {
        std::cout << "The input file " << file << " is missing!" << std::endl;
        file = solveDir + "../conf/csr.dat";
        ifs.open(file);
        if (!ifs.is_open()) {
            std::cout << "The input file " << file << " is missing!" << std::endl;
            std::cout << "Using the default parameters of FASP" << std::endl;
        } else {
            ifs.close();
            std::cout << "Using the input file " << file << std::endl;
            fasp_param_input(file.data(), &inParam);
        }
    } else {
        ifs.close(); // if file has been opened, close it first
        fasp_param_input(file.data(), &inParam);
    }
    fasp_param_init(&inParam, &itParam, &amgParam, &iluParam, &swzParam);
}
References InitParam_Fasp().
RowCapPlus()
void LinearSolver::RowCapPlus (const OCP_USI & row, const USI & n) inline
Enlarge row capacity. // TODO: maybe should be called EnlargeRowCap?
Definition at line 73 of file LinearSolver.hpp.
{ rowCapacity[row] += n; }
SetupParam()
void LinearSolver::SetupParam (const string & dir, const string & file)
Setup solver param for scalar-value problems from input file.
Definition at line 337 of file LinearSolver.cpp.
{
    solveDir  = dir;
    solveFile = file;
#ifdef __SOLVER_FASP__
    ReadParam_Fasp();
#endif //  __SOLVER_FASP__
}
References ReadParam_Fasp().
SetupParamB()
void LinearSolver::SetupParamB (const string & dir, const string & file)
Setup solver param for vector-value problems from input file.
Definition at line 346 of file LinearSolver.cpp.
{
    solveDir  = dir;
    solveFile = file;
#ifdef __SOLVER_FASP__
    ReadParam_BFasp();
#endif //  __SOLVER_FASP__
}
References ReadParam_BFasp().
Friends And Related Function Documentation
BulkConn
friend class BulkConn friend
Definition at line 60 of file LinearSolver.hpp.
OpenCAEPoro
friend class OpenCAEPoro friend
Definition at line 59 of file LinearSolver.hpp.
Well
friend class Well friend
Definition at line 61 of file LinearSolver.hpp.
The documentation for this class was generated from the following files:
LinearSolver.hpp
Decoupling.cpp
LinearSolver.cpp