OpenCAEPoro: Bulk Class Reference
Bulk Class Reference
Physical information of each active reservoir bulk.
#include <Bulk.hpp>
Public Member Functions
void InputParam (ParamReservoir &rs_param)
Input param from internal data structure ParamReservoir.
void Setup (const Grid &myGrid)
Allocate memory for bulk data of grid.
void InitSjPcBo (const USI &tabrow)
Calculate initial equilibrium for blkoil model according to EQUIL.
void InitSjPcComp (const USI &tabrow, const Grid &myGrid)
Calculate initial equilibrium for compositional model according to EQUIL.
void InitFlash (const bool &flag=false)
Perform flash calculation with saturations.
void Flash ()
Perform flash calculation with Ni.
void FlashBLKOIL ()
Perform flash calculation with Ni in Black Oil Model.
void FlashCOMP ()
Perform flash calculation with Ni in Compositional Model.
void FlashDeriv ()
Perform flash calculation with Ni and calculate derivatives.
void FlashDeriv_n ()
void FlashDerivBLKOIL ()
Perform flash calculation with Ni in Black Oil Model.
void FlashDerivBLKOIL_n ()
void FlashDerivCOMP ()
Perform flash calculation with Ni in Compositional Model.
void FlashDerivCOMP_n ()
void PassFlashValue (const OCP_USI &n)
Pass values from Flash to Bulk after Flash calculation.
void PassFlashValueAIMc (const OCP_USI &n)
void PassFlashValueDeriv (const OCP_USI &n)
Pass derivative values from Flash to Bulk after Flash calculation.
void PassFlashValueDeriv_n (const OCP_USI &n)
void ResetFlash ()
Reset variables in flash calculations.
void CalKrPc ()
Calculate relative permeability and capillary pressure with saturation.
void CalKrPcDeriv ()
Calculate relative permeability and capillary pressure and their derivatives.
void CalVpore ()
Calculate volume of pore with pressure.
OCP_DBL CalFPR () const
Calculate average pressure in reservoir.
void CalMaxChange ()
Calculate max change of some variables.
void CheckSetup () const
Check if error occurs in Setup.
void CheckInitVpore () const
Check initial pore volume.
void CheckVpore () const
Check pore volume.
bool CheckP () const
Check if negative P occurs, return false if so.
bool CheckNi ()
Check if negative Ni occurs, return false if so.
bool CheckVe (const OCP_DBL &Vlim) const
Check if relative volume error is out of range, return false if so.
void CheckSat () const
Check if the sum of saturations is one.
void CheckDiff ()
Check difference from last time step, for Debug and Test.
OCP_USI GetBulkNum () const
Return the number of bulks.
USI GetComNum () const
Return the number of components.
USI GetPhaseNum () const
Return the number of phases.
USI GetMixMode () const
Return the mixture mode.
const vector< Mixture * > & GetMixture () const
Return flash results (it has not been used by far).
OCP_DBL GetP (const OCP_USI &n) const
Return pressure of the n-th bulk.
OCP_DBL GetSOIL (const OCP_USI &n) const
Return oil saturation of the n-th bulk.
OCP_DBL GetSGAS (const OCP_USI &n) const
Return gas saturation of the n-th bulk.
OCP_DBL GetSWAT (const OCP_USI &n) const
Return water saturation of the n-th bulk.
OCP_DBL GetdPmax () const
Return dPmax.
OCP_DBL GetdNmax () const
Return dNmax.
OCP_DBL GetdSmax () const
Return dSmax.
OCP_DBL GetdVmax () const
Return dVmax.
void ResetphaseNum ()
void ResetminEigenSkip ()
void ResetflagSkip ()
void ResetziSkip ()
void ResetPSkip ()
void ResetKs ()
void ResetNt ()
Reset Nt to the ones of the last time step.
void ResetP ()
Reset P to the ones of the last time step.
void ResetPj ()
Reset Pj to the ones of the last time step.
void ResetNi ()
Reset Ni to the ones of the last time step.
void ResetKr ()
Reset Kr to the ones of the last time step.
void ResetVp ()
Reset Vp to the ones of the last time step.
void CalSomeInfo (const Grid &myGrid) const
void AllocateWellBulkId (const USI &n)
Allocate memory for WellbulkId.
void ClearWellBulkId ()
OCP_DBL CalNT ()
void AllocateAuxIMPEC ()
Allocate memory for auxiliary variables used for IMPEC.
void GetSolIMPEC (const vector< OCP_DBL > &u)
Update P and Pj after linear system is solved.
void SetCFL2Zero () const
Initialize the CFL number.
OCP_DBL CalCFL () const
Calculate the CFL number.
void UpdateLastStepIMPEC ()
Update value of last step for IMPEC.
void AllocateAuxFIM ()
Allocate memory for auxiliary variables used for FIM.
void GetSolFIM (const vector< OCP_DBL > &u, const OCP_DBL &dPmaxlim, const OCP_DBL &dSmaxlim)
Get the solution for FIM after a Newton iteration.
void GetSolFIM_n (const vector< OCP_DBL > &u, const OCP_DBL &dPmaxlim, const OCP_DBL &dSmaxlim)
void GetSol01FIM (const vector< OCP_DBL > &u)
Get the solution for FIM after a Newton iteration???
void CalRelResFIM (ResFIM &resFIM) const
Calculate relative resiual for FIM.
void ShowRes (const vector< OCP_DBL > &res) const
void ResetFIM ()
Reset FIM.
void UpdateLastStepFIM ()
Update values of last step for FIM.
OCP_DBL CalNRdSmax (OCP_USI &index)
Calculate some auxiliary variable, for example, dSmax.
OCP_DBL GetNRdPmax ()
Return NRdPmax.
OCP_DBL GetNRdSmaxP ()
Return NRdSmaxP.
OCP_DBL GetNRdNmax ()
void CorrectNi (const vector< OCP_DBL > &res)
void OutputInfo (const OCP_USI &n) const
OCP_ULL GetSSMSTAiters () const
OCP_ULL GetNRSTAiters () const
OCP_ULL GetSSMSPiters () const
OCP_ULL GetNRSPiters () const
void AllocateAuxAIM (const OCP_DBL &ratio)
Allocate memory for auxiliary variables used for AIMt.
OCP_USI GetMaxFIMBulk () const
void FlashDerivAIM (const bool &IfAIMs)
Perform flash calculation with Ni and calculate derivatives.
void PassFlashValueDerivAIM (const OCP_USI &n)
void CalKrPcDerivAIM (const bool &IfAIMs)
Calculate relative permeability and capillary pressure and their derivatives.
void CalRelResAIMt (ResFIM &resFIM) const
Calculate relative resiual for local FIM.
void GetSolAIMt (const vector< OCP_DBL > &u, const OCP_DBL &dPmaxlim, const OCP_DBL &dSmaxlim)
Get the solution for local FIM after a Newton iteration.
void CalRelResAIMs (ResFIM &resFIM) const
Calculate relative resiual for AIMs, parts related to FIM are considered.
void GetSolAIMs (const vector< OCP_DBL > &u, const OCP_DBL &dPmaxlim, const OCP_DBL &dSmaxlim)
void UpdateLastStepAIM ()
void ResetFIMBulk ()
void ShowFIMBulk (const bool &flag=false) const
bool CheckNiFIMBulk () const
Check if negative Ni occurs, return false if so.
void InFIMNi ()
Ni in FIM Bulk -> FIMNi.
void OutFIMNi ()
FIMNi -> Ni in FIM Bulk.
void AllocateAuxAIMc ()
void FlashAIMc ()
Perform flash calculation with Ni.
void FlashBLKOILAIMc ()
Perform flash calculation with Ni in Black Oil Model.
void FlashCOMPAIMc ()
Perform flash calculation with Ni in Compositional Model.
void FlashAIMc01 ()
void FlashBLKOILAIMc01 ()
void FlashCOMPAIMc01 ()
void FlashDerivAIMc ()
Perform flash calculation with Ni and calculate derivatives.
void FlashDerivBLKOILAIMc ()
Perform flash calculation with Ni in Black Oil Model.
void FlashDerivCOMPAIMc ()
Perform flash calculation with Ni in Compositional Model.
void CalKrPcAIMc ()
Calculate relative permeability and capillary pressure with saturation.
void CalKrPcDerivAIMc ()
Calculate relative permeability and capillary pressure and their derivatives.
void GetSolAIMc (const vector< OCP_DBL > &u, const OCP_DBL &dPmaxlim, const OCP_DBL &dSmaxlim)
void GetSolAIMc01 (const vector< OCP_DBL > &u, const OCP_DBL &dPmaxlim, const OCP_DBL &dSmaxlim)
void UpdatePj ()
Friends
class BulkConn
class Well
class DetailInfo
class OCP_IMPEC
class OCP_FIM
class Reservoir
class OCP_AIMt
class OCP_AIMc
Detailed Description
Physical information of each active reservoir bulk.
Definition at line 57 of file Bulk.hpp.
Member Function Documentation
AllocateAuxAIM()
void Bulk::AllocateAuxAIM (const OCP_DBL & ratio)
Allocate memory for auxiliary variables used for AIMt.
Definition at line 3407 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    maxNumFIMBulk = numBulk * ratio;
    if (maxNumFIMBulk < wellBulkId.capacity()) {
        maxNumFIMBulk = wellBulkId.capacity();
    }
    FIMBulk.reserve(maxNumFIMBulk);
    map_Bulk2FIM.resize(numBulk, -1);
    muP.resize(maxNumFIMBulk * numPhase);
    xiP.resize(maxNumFIMBulk * numPhase);
    rhoP.resize(maxNumFIMBulk * numPhase);
    mux.resize(maxNumFIMBulk * numCom * numPhase);
    xix.resize(maxNumFIMBulk * numCom * numPhase);
    rhox.resize(maxNumFIMBulk * numCom * numPhase);
    lendSdP = (numCom + 1) * (numCom + 1) * numPhase;
    dSec_dPri.resize(maxNumFIMBulk * lendSdP);
    dKr_dS.resize(maxNumFIMBulk * numPhase * numPhase);
    dPcj_dS.resize(maxNumFIMBulk * numPhase * numPhase);
    lmuP.resize(maxNumFIMBulk * numPhase);
    lxiP.resize(maxNumFIMBulk * numPhase);
    lrhoP.resize(maxNumFIMBulk * numPhase);
    lmux.resize(maxNumFIMBulk * numCom * numPhase);
    lxix.resize(maxNumFIMBulk * numCom * numPhase);
    lrhox.resize(maxNumFIMBulk * numCom * numPhase);
    ldSec_dPri.resize(maxNumFIMBulk * lendSdP);
    ldKr_dS.resize(maxNumFIMBulk * numPhase * numPhase);
    ldPcj_dS.resize(maxNumFIMBulk * numPhase * numPhase);
    FIMNi.resize(maxNumFIMBulk * numCom);
}
References OCP_FUNCNAME.
AllocateAuxAIMc()
void Bulk::AllocateAuxAIMc ()
Definition at line 3947 of file Bulk.cpp.
{
    cfl.resize(numBulk * numPhase);
    map_Bulk2FIM.resize(numBulk, -1);
}
AllocateAuxFIM()
void Bulk::AllocateAuxFIM ()
Allocate memory for auxiliary variables used for FIM.
Definition at line 2742 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    // FIM var
    nj.resize(numBulk * numPhase);
    vfi.resize(numBulk * numCom);
    vfp.resize(numBulk);
    muP.resize(numBulk * numPhase);
    xiP.resize(numBulk * numPhase);
    rhoP.resize(numBulk * numPhase);
    mux.resize(numBulk * numCom * numPhase);
    xix.resize(numBulk * numCom * numPhase);
    rhox.resize(numBulk * numCom * numPhase);
    lendSdP = (numCom + 1) * (numCom + 1) * numPhase;
    dSec_dPri.resize(numBulk * lendSdP);
    res_n.resize((numPhase + numPhase * numCom) * numBulk);
    resPc.resize(numBulk);
    dSdPindex.resize(numBulk + 1, 0);
    resIndex.resize(numBulk + 1, 0);
    pEnumCom.resize(numBulk * numPhase);
    dKr_dS.resize(numBulk * numPhase * numPhase);
    dPcj_dS.resize(numBulk * numPhase * numPhase);
    // Last Step
    lP.resize(numBulk);
    lPj.resize(numBulk * numPhase);
    lPc.resize(numBulk * numPhase);
    lphaseExist.resize(numBulk * numPhase);
    lS.resize(numBulk * numPhase);
    lnj.resize(numBulk * numPhase);
    lrho.resize(numBulk * numPhase);
    lxi.resize(numBulk * numPhase);
    lxij.resize(numBulk * numPhase * numCom);
    lNi.resize(numBulk * numCom);
    lmu.resize(numBulk * numPhase);
    lkr.resize(numBulk * numPhase);
    lvj.resize(numBulk * numPhase);
    lvf.resize(numBulk);
    lNt.resize(numBulk);
    lvfi.resize(numBulk * numCom);
    lvfp.resize(numBulk);
    lrockVp.resize(numBulk);
    lmuP.resize(numBulk * numPhase);
    lxiP.resize(numBulk * numPhase);
    lrhoP.resize(numBulk * numPhase);
    lmux.resize(numBulk * numCom * numPhase);
    lxix.resize(numBulk * numCom * numPhase);
    lrhox.resize(numBulk * numCom * numPhase);
    ldSec_dPri.resize(numBulk * lendSdP);
    lres_n.resize((numPhase + numPhase * numCom) * numBulk);
    ldSdPindex.resize(numBulk + 1, 0);
    lresIndex.resize(numBulk + 1, 0);
    lpEnumCom.resize(numBulk * numPhase);
    ldKr_dS.resize(numBulk * numPhase * numPhase);
    ldPcj_dS.resize(numBulk * numPhase * numPhase);
    dSNR.resize(numBulk * numPhase);
    dSNRP.resize(numBulk * numPhase);
    dNNR.resize(numBulk * numCom);
    dPNR.resize(numBulk);
    NRstep.resize(numBulk);
}
References OCP_FUNCNAME.
AllocateAuxIMPEC()
void Bulk::AllocateAuxIMPEC ()
Allocate memory for auxiliary variables used for IMPEC.
Definition at line 2627 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    // IMPEC var
    vfi.resize(numBulk * numCom);
    vfp.resize(numBulk);
    cfl.resize(numBulk * numPhase);
    // Last Step
    lP.resize(numBulk);
    lPj.resize(numBulk * numPhase);
    lPc.resize(numBulk * numPhase);
    lphaseExist.resize(numBulk * numPhase);
    lS.resize(numBulk * numPhase);
    lrho.resize(numBulk * numPhase);
    lxi.resize(numBulk * numPhase);
    lxij.resize(numBulk * numPhase * numCom);
    lNi.resize(numBulk * numCom);
    lmu.resize(numBulk * numPhase);
    lkr.resize(numBulk * numPhase);
    lvj.resize(numBulk * numPhase);
    lvf.resize(numBulk);
    lNt.resize(numBulk);
    lvfi.resize(numBulk * numCom);
    lvfp.resize(numBulk);
    lrockVp.resize(numBulk);
}
References OCP_FUNCNAME.
AllocateWellBulkId()
void Bulk::AllocateWellBulkId (const USI & n) inline
Allocate memory for WellbulkId.
Definition at line 204 of file Bulk.hpp.
{ wellBulkId.reserve(n); }
CalCFL()
OCP_DBL Bulk::CalCFL () const
Calculate the CFL number.
Definition at line 2672 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_DBL tmp = 0;
    OCP_USI id;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        for (USI j = 0; j < numPhase; j++)
        {
            id = n * numPhase + j;
            if (phaseExist[id])
            {
                if (vj[id] <= 0)
                    continue; // temp
                cfl[id] /= vj[id];
#ifdef DEBUG
                if (!isfinite(cfl[id]))
                {
                    OCP_ABORT("cfl is nan!");
                }
#endif // DEBUG
                if (tmp < cfl[id])
                    tmp = cfl[id];
            }
        }
    }
    return tmp;
}
References OCP_ABORT, and OCP_FUNCNAME.
CalFPR()
OCP_DBL Bulk::CalFPR () const
Calculate average pressure in reservoir.
Definition at line 2134 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_DBL ptmp = 0;
    OCP_DBL vtmp = 0;
    OCP_DBL tmp = 0;
    if (numPhase == 3)
    {
        for (OCP_USI n = 0; n < numBulk; n++)
        {
            tmp = rockVp[n] * (1 - S[n * numPhase + 2]);
            ptmp += P[n] * tmp;
            vtmp += tmp;
        }
    }
    else if (numPhase < 3)
    {
        for (OCP_USI n = 0; n < numBulk; n++)
        {
            tmp = rockVp[n] * (S[n * numPhase]);
            ptmp += P[n] * tmp;
            vtmp += tmp;
        }
    }
    else
    {
        OCP_ABORT("Number of phases is out of range!");
    }
    return ptmp / vtmp;
}
References OCP_ABORT, and OCP_FUNCNAME.
CalKrPc()
void Bulk::CalKrPc ()
Calculate relative permeability and capillary pressure with saturation.
Relative permeability and capillary pressure.
Definition at line 2051 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    if (!miscible) {
        OCP_DBL tmp = 0;
        for (OCP_USI n = 0; n < numBulk; n++)
        {
            OCP_USI bId = n * numPhase;
            flow[SATNUM[n]]->CalKrPc(&S[bId], &kr[bId], &Pc[bId], 0, tmp, tmp);
            for (USI j = 0; j < numPhase; j++)
                Pj[n * numPhase + j] = P[n] + Pc[n * numPhase + j];
        }
    }
    else {
        for (OCP_USI n = 0; n < numBulk; n++)
        {
            OCP_USI bId = n * numPhase;
            flow[SATNUM[n]]->CalKrPc(&S[bId], &kr[bId], &Pc[bId], surTen[n], Fk[n], Fp[n]);
            for (USI j = 0; j < numPhase; j++)
                Pj[n * numPhase + j] = P[n] + Pc[n * numPhase + j];
        }
    }
    if (ScalePcow) {
        // correct
        USI Wid = phase2Index[WATER];
        for (USI n = 0; n < numBulk; n++) {
            Pc[n * numPhase + Wid] *= ScaleValuePcow[n];
            Pj[n * numPhase + Wid] = P[n] + Pc[n * numPhase + Wid];
        }
    }
}
References OCP_FUNCNAME, and WATER.
CalKrPcAIMc()
void Bulk::CalKrPcAIMc ()
Calculate relative permeability and capillary pressure with saturation.
Definition at line 4158 of file Bulk.cpp.
{
    OCP_DBL tmp = 0;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        if (map_Bulk2FIM[n] > -1) {
            // FIM bulk
            continue;
        }
        OCP_USI bId = n * numPhase;
        flow[SATNUM[n]]->CalKrPc(&S[bId], &kr[bId], &Pc[bId], 0, tmp, tmp);
        for (USI j = 0; j < numPhase; j++)
            Pj[n * numPhase + j] = P[n] + Pc[n * numPhase + j];
    }
}
CalKrPcDeriv()
void Bulk::CalKrPcDeriv ()
Calculate relative permeability and capillary pressure and their derivatives.
Definition at line 2085 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    if (!miscible) {
        OCP_DBL tmp = 0;
        for (OCP_USI n = 0; n < numBulk; n++)
        {
            OCP_USI bId = n * numPhase;
            flow[SATNUM[n]]->CalKrPcDeriv(&S[bId], &kr[bId], &Pc[bId],
                &dKr_dS[bId * numPhase], &dPcj_dS[bId * numPhase], 0, tmp, tmp);
            for (USI j = 0; j < numPhase; j++)
                Pj[bId + j] = P[n] + Pc[bId + j];
        }
    }
    else {
        for (OCP_USI n = 0; n < numBulk; n++)
        {
            OCP_USI bId = n * numPhase;
            flow[SATNUM[n]]->CalKrPcDeriv(&S[bId], &kr[bId], &Pc[bId],
                &dKr_dS[bId * numPhase], &dPcj_dS[bId * numPhase],
                surTen[n], Fk[n], Fp[n]);
            for (USI j = 0; j < numPhase; j++)
                Pj[n * numPhase + j] = P[n] + Pc[n * numPhase + j];
        }
    }
    if (ScalePcow) {
        // correct
        USI Wid = phase2Index[WATER];
        for (USI n = 0; n < numBulk; n++) {
            Pc[n * numPhase + Wid] *= ScaleValuePcow[n];
            Pj[n * numPhase + Wid] = P[n] + Pc[n * numPhase + Wid];
        }
    }
}
References OCP_FUNCNAME, and WATER.
CalKrPcDerivAIM()
void Bulk::CalKrPcDerivAIM (const bool & IfAIMs)
Calculate relative permeability and capillary pressure and their derivatives.
Definition at line 3595 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    USI len;
    if (IfAIMs) {
        len = FIMBulk.size();
    }
    else {
        len = numFIMBulk;
    }
    OCP_DBL tmp;
    for (OCP_USI fn = 0; fn < len; fn++)
    {
        OCP_USI n = FIMBulk[fn];
        OCP_USI fnp = fn * numPhase;
        OCP_USI bId = n * numPhase;
        flow[SATNUM[n]]->CalKrPcDeriv(&S[bId], &kr[bId], &Pc[bId],
            &dKr_dS[fnp * numPhase],
            &dPcj_dS[fnp * numPhase], 0, tmp, tmp);
        for (USI j = 0; j < numPhase; j++)
            Pj[bId + j] = P[n] + Pc[bId + j];
    }
}
References OCP_FUNCNAME.
CalKrPcDerivAIMc()
void Bulk::CalKrPcDerivAIMc ()
Calculate relative permeability and capillary pressure and their derivatives.
Definition at line 4174 of file Bulk.cpp.
{
    OCP_DBL tmp;
    for (auto& n : FIMBulk)
    {
        OCP_USI bId = n * numPhase;
        flow[SATNUM[n]]->CalKrPcDeriv(&S[bId], &kr[bId], &Pc[bId],
            &dKr_dS[bId * numPhase],
            &dPcj_dS[bId * numPhase], 0, tmp, tmp);
        for (USI j = 0; j < numPhase; j++)
            Pj[bId + j] = P[n] + Pc[bId + j];
    }
}
CalMaxChange()
void Bulk::CalMaxChange ()
Calculate max change of some variables.
Definition at line 2167 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    dPmax = 0;
    dNmax = 0;
    dSmax = 0;
    dVmax = 0;
    OCP_DBL tmp = 0;
    OCP_USI id;
    OCP_USI ndPmax, ndNmax, ndSmax, ndVmax;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        // dP
        tmp   = fabs(P[n] - lP[n]);
        if (dPmax < tmp) {
            dPmax = tmp;
            ndPmax = n;
        }
        // dS
        for (USI j = 0; j < numPhase; j++) {
            id    = n * numPhase + j;
            tmp   = fabs(S[id] - lS[id]);
            if (dSmax < tmp) {
                dSmax = tmp;
                ndSmax = n;
            }
        }
        // dN
        for (USI i = 0; i < numCom; i++)
        {
            id = n * numCom + i;
            tmp = fabs(max(Ni[id], lNi[id]));
            if (tmp > TINY) {
                tmp   = fabs(Ni[id] - lNi[id]) / tmp;
                if (dNmax < tmp) {
                    dNmax = tmp;
                    ndNmax = n;
                }
            }
        }
        tmp   = fabs(vf[n] - rockVp[n]) / rockVp[n];
        if (dVmax < tmp) {
            dVmax = tmp;
            ndVmax = n;
        }
    }
    //cout << scientific << setprecision(6);
    //cout << setw(15) << dPmax << setw(15) << dNmax << setw(15) << dSmax << setw(15) << dVmax << endl;
    //cout << setw(15) << ndPmax << setw(15) << ndNmax << setw(15) << ndSmax << setw(15) << ndVmax << endl;
    //cout << ndSmax << endl;
    //cout << "old   " << lP[ndSmax] << endl;
    //tmp = Dnorm1(numCom_1, &lNi[ndSmax * numCom]);
    //for (USI i = 0; i < numCom_1; i++) {
    //    cout << lNi[ndSmax * numCom + i] << "   ";
    //}
    //cout << endl;
    //for (USI i = 0; i < numCom_1; i++) {
    //    cout << lNi[ndSmax * numCom + i] / tmp << "   ";
    //}
    //cout << endl;
    //for (USI j = 0; j < numPhase - 1; j++) {
    //    cout << lS[ndSmax * numPhase + j] << "   ";
    //    for (USI i = 0; i < numCom_1; i++) {
    //        cout << lxij[(ndSmax * numPhase + j) * numCom + i] << "   ";
    //    }
    //    cout << endl;
    //}
    //cout << "new   " << P[ndSmax] << endl;
    //tmp = Dnorm1(numCom_1, &Ni[ndSmax * numCom]);
    //for (USI i = 0; i < numCom_1; i++) {
    //    cout << Ni[ndSmax * numCom + i] << "   ";
    //}
    //cout << endl;
    //for (USI i = 0; i < numCom_1; i++) {
    //    cout << Ni[ndSmax * numCom + i] / tmp << "   ";
    //}
    //cout << endl;
    //for (USI j = 0; j < numPhase - 1; j++) {
    //    cout << S[ndSmax * numPhase + j] << "   ";
    //    for (USI i = 0; i < numCom_1; i++) {
    //        cout << xij[(ndSmax * numPhase + j) * numCom + i] << "   ";
    //    }
    //    cout << endl;
    //}
}
References OCP_FUNCNAME, and TINY.
CalNRdSmax()
OCP_DBL Bulk::CalNRdSmax (OCP_USI & index)
Calculate some auxiliary variable, for example, dSmax.
Definition at line 3292 of file Bulk.cpp.
{
    NRdSmax = 0;
    OCP_USI len = numBulk * numPhase;
    for (USI n = 0; n < len; n++) {
        if (fabs(NRdSmax) < fabs(dSNR[n])) {
            NRdSmax = dSNR[n];
            index = n;
        }
    }
    index /= numPhase;
    return NRdSmax;
}
CalNT()
OCP_DBL Bulk::CalNT () inline
Definition at line 206 of file Bulk.hpp.
{ NT = Dnorm1(numBulk, &Nt[0]);  return NT;   }
CalRelResAIMs()
void Bulk::CalRelResAIMs (ResFIM & resFIM) const
Calculate relative resiual for AIMs, parts related to FIM are considered.
Definition at line 3726 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    // OCP_USI tmpid01 = -1;
    // OCP_USI tmpid02 = -1;
    OCP_DBL tmp;
    const USI len = numCom + 1;
    for (OCP_USI fn = 0; fn < numFIMBulk; fn++)
    {
        OCP_USI n = FIMBulk[fn];
        for (USI i = 0; i < len; i++)
        {
            tmp = fabs(resFIM.res[n * len + i] / rockVp[n]);
            if (resFIM.maxRelRes_v < tmp)
            {
                resFIM.maxRelRes_v = tmp;
                // tmpid01            = n;
            }
        }
        for (USI i = 1; i < len; i++)
        {
            tmp = fabs(resFIM.res[n * len + i] / Nt[n]);
            if (resFIM.maxRelRes_mol < tmp)
            {
                resFIM.maxRelRes_mol = tmp;
                // tmpid02              = n;
            }
        }
    }
}
References OCP_FUNCNAME.
CalRelResAIMt()
void Bulk::CalRelResAIMt (ResFIM & resFIM) const
Calculate relative resiual for local FIM.
Definition at line 3620 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    // OCP_USI tmpid01 = -1;
    // OCP_USI tmpid02 = -1;
    OCP_DBL tmp;
    const USI len = numCom + 1;
    for (OCP_USI fn = 0; fn < numFIMBulk; fn++)
    {
        OCP_USI n = FIMBulk[fn];
        for (USI i = 0; i < len; i++)
        {
            tmp = fabs(resFIM.res[fn * len + i] / rockVp[n]);
            if (resFIM.maxRelRes_v < tmp)
            {
                resFIM.maxRelRes_v = tmp;
                // tmpid01            = n;
            }
        }
        for (USI i = 1; i < len; i++)
        {
            tmp = fabs(resFIM.res[fn * len + i] / Nt[n]);
            if (resFIM.maxRelRes_mol < tmp)
            {
                resFIM.maxRelRes_mol = tmp;
                // tmpid02              = n;
            }
        }
    }
}
References OCP_FUNCNAME.
CalRelResFIM()
void Bulk::CalRelResFIM (ResFIM & resFIM) const
Calculate relative resiual for FIM.
Definition at line 3103 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    //OCP_USI tmpid01 = -1;
    //OCP_USI tmpid02 = -1;
    OCP_DBL tmp;
    const USI len = numCom + 1;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        eV[n] = 0;
        for (USI i = 0; i < len; i++)
        {
            tmp = fabs(resFIM.res[n * len + i] / rockVp[n]);
            if (resFIM.maxRelRes_v < tmp)
            {
                resFIM.maxRelRes_v = tmp;
                resFIM.maxId_v     = n;
            }
            eV[n] += tmp * tmp;
        }
        eV[n] = sqrt(eV[n]);
        eN[n] = 0;
        for (USI i = 1; i < len; i++)
        {
            tmp = fabs(resFIM.res[n * len + i] / Nt[n]);
            if (resFIM.maxRelRes_mol < tmp)
            {
                resFIM.maxRelRes_mol = tmp;
                resFIM.maxId_mol     = n;
            }
            eN[n] += tmp * tmp;
        }
        eN[n] = sqrt(eN[n]);
    }
     //cout << scientific;
     //if (tmpid01 < numBulk) {
     //    cout << "maxRelRes_v: " << tmpid01 << "   " << S[tmpid01 * numPhase] << "   "
     //        << S[tmpid01 * numPhase + 1] << "   " << S[tmpid01 * numPhase + 2] <<
     //        "   " << resFIM.maxRelRes_v << endl;
     //}
     //if (tmpid02 < numBulk) {
     //    cout << "maxRelRes_mol: " << tmpid02 << "   " << S[tmpid02 * numPhase] << "   "
     //        << S[tmpid02 * numPhase + 1] << "   " << S[tmpid02 * numPhase + 2] <<
     //        "   " << resFIM.maxRelRes_mol << endl;
     //}
}
References OCP_FUNCNAME.
CalSomeInfo()
void Bulk::CalSomeInfo (const Grid & myGrid) const
Definition at line 2463 of file Bulk.cpp.
{
    // test
    OCP_DBL depthMax = 0;
    OCP_USI ndepa = 0;
    OCP_DBL depthMin = 1E8;
    OCP_USI ndepi = 0;
    OCP_DBL dxMax = 0;
    OCP_USI nxa = 0;
    OCP_DBL dxMin = 1E8;
    OCP_USI nxi = 0;
    OCP_DBL dyMax = 0;
    OCP_USI nya = 0;
    OCP_DBL dyMin = 1E8;
    OCP_USI nyi = 0;
    OCP_DBL dzMax = 0;
    OCP_USI nza = 0;
    OCP_DBL dzMin = 1E8;
    OCP_USI nzi = 0;
    OCP_DBL RVMax = 0;
    OCP_USI nRVa = 0;
    OCP_DBL RVMin = 1E8;
    OCP_USI nRVi = 0;
    OCP_DBL RVPMax = 0;
    OCP_USI nRVPa = 0;
    OCP_DBL RVPMin = 1E8;
    OCP_USI nRVPi = 0;
    OCP_DBL PerxMax = 0;
    OCP_USI nPerxa = 0;
    OCP_DBL PerxMin = 1E8;
    OCP_USI nPerxi = 0;
    USI I, J, K;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        // if (!activeMap_G2B[nn].IsAct())
        //     continue;
        // OCP_USI n = activeMap_G2B[nn].GetId();
        if (depthMax < depth[n])
        {
            depthMax = depth[n];
            ndepa = n;
        }
        if (depthMin > depth[n])
        {
            depthMin = depth[n];
            ndepi = n;
        }
        if (dxMax < dx[n])
        {
            dxMax = dx[n];
            nxa = n;
        }
        if (dxMin > dx[n])
        {
            dxMin = dx[n];
            nxi = n;
        }
        if (dyMax < dy[n])
        {
            dyMax = dy[n];
            nya = n;
        }
        if (dyMin > dy[n])
        {
            dyMin = dy[n];
            nyi = n;
        }
        if (dzMax < dz[n])
        {
            dzMax = dz[n];
            nza = n;
        }
        if (dzMin > dz[n])
        {
            dzMin = dz[n];
            nzi = n;
        }
        OCP_DBL tmp = myGrid.v[myGrid.activeMap_B2G[n]];
        if (RVMax < tmp)
        {
            RVMax = tmp;
            nRVa = n;
        }
        if (RVMin > tmp)
        {
            RVMin = tmp;
            nRVi = n;
        }
        tmp = rockVp[n];
        if (RVPMax < tmp)
        {
            RVPMax = tmp;
            nRVPa = n;
        }
        if (RVPMin > tmp)
        {
            RVPMin = tmp;
            nRVPi = n;
        }
        tmp = rockKx[n];
        if (PerxMax < tmp)
        {
            PerxMax = tmp;
            nPerxa = n;
        }
        if (PerxMin > tmp && fabs(tmp) > 1E-8)
        {
            PerxMin = tmp;
            nPerxi = n;
        }
    }
    cout << "---------------------" << endl
         << "BULK" << endl
         << "---------------------" << endl;
    myGrid.GetIJKGrid(I, J, K, ndepa);
    cout << "  Depthmax = " << depthMax << " feet  (" << I << ", " << J << ", " << K
         << ")" << endl;
    myGrid.GetIJKGrid(I, J, K, ndepi);
    cout << "  Depthmin = " << depthMin << " feet  (" << I << ", " << J << ", " << K
         << ")" << endl;
    myGrid.GetIJKGrid(I, J, K, nxa);
    cout << "  DXmax    = " << dxMax << " feet  (" << I << ", " << J << ", " << K << ")"
         << endl;
    myGrid.GetIJKGrid(I, J, K, nxi);
    cout << "  DXmin    = " << dxMin << " feet  (" << I << ", " << J << ", " << K << ")"
         << endl;
    myGrid.GetIJKGrid(I, J, K, nya);
    cout << "  DYmax    = " << dyMax << " feet  (" << I << ", " << J << ", " << K << ")"
         << endl;
    myGrid.GetIJKGrid(I, J, K, nyi);
    cout << "  DYmin    = " << dyMin << " feet  (" << I << ", " << J << ", " << K << ")"
         << endl;
    myGrid.GetIJKGrid(I, J, K, nza);
    cout << "  DZmax    = " << dzMax << " feet  (" << I << ", " << J << ", " << K << ")"
         << endl;
    myGrid.GetIJKGrid(I, J, K, nzi);
    cout << "  DZmin    = " << dzMin << " feet  (" << I << ", " << J << ", " << K << ")"
         << endl;
    myGrid.GetIJKGrid(I, J, K, nRVa);
    cout << "  RVmax    = " << RVMax / CONV1 << " rb   (" << I << ", " << J << ", " << K
         << ")" << endl;
    myGrid.GetIJKGrid(I, J, K, nRVi);
    cout << "  RVmin    = " << RVMin / CONV1 << " rb   (" << I << ", " << J << ", " << K
         << ")" << endl;
    myGrid.GetIJKGrid(I, J, K, nRVPa);
    cout << "  RVmax    = " << RVPMax / CONV1 << " rb   (" << I << ", " << J << ", " << K
         << ")" << endl;
    myGrid.GetIJKGrid(I, J, K, nRVPi);
    cout << "  RVmin    = " << RVPMin / CONV1 << " rb   (" << I << ", " << J << ", " << K
         << ")" << endl;
    myGrid.GetIJKGrid(I, J, K, nPerxa);
    cout << "  Perxmax  = " << PerxMax << "   (" << I << ", " << J << ", " << K << ")"
         << endl;
    myGrid.GetIJKGrid(I, J, K, nPerxi);
    cout << "  Perxmin  = " << scientific << PerxMin << "   (" << I << ", " << J << ", "
         << K << ")" << endl;
}
CalVpore()
void Bulk::CalVpore ()
Calculate volume of pore with pressure.
Definition at line 2122 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        OCP_DBL dP = rockC1 * (P[n] - rockPref);
        rockVp[n] = rockVpInit[n] * (1 + dP);
        // rockVp[n] = rockVpInit[n] * (1 + dP + dP * dP / 2);
    }
}
References OCP_FUNCNAME.
CheckDiff()
void Bulk::CheckDiff ()
Check difference from last time step, for Debug and Test.
Definition at line 2355 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_DBL tmp;
    OCP_USI id;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        for (USI j = 0; j < numPhase; j++)
        {
            id = n * numPhase + j;
            tmp = fabs(phaseExist[id] - lphaseExist[id]);
            if (tmp >= 1E-10)
            {
                cout << "Difference in phaseExist\t" << tmp << "\n";
            }
            if (lphaseExist[id] || phaseExist[id])
            {
                tmp = fabs(S[id] - lS[id]);
                if (tmp >= 1E-10)
                {
                    cout << scientific << setprecision(16);
                    cout << "Bulk[" << n << "]" << endl;
                    cout << "Saturation" << endl;
                    for (USI j = 0; j < numPhase; j++) {
                        cout << S[n * numPhase + j] << "   " << lS[n * numPhase + j] << endl;
                    }
                    cout << "Pressure" << endl;
                    cout << P[n] << "   " << lP[n] << endl;
                    cout << "Ni" << endl;
                    for (USI i = 0; i < numCom; i++) {
                        cout << Ni[n * numCom + i] << "   " << lNi[n * numCom + i] << endl;
                    }
                    cout << "PhaseNum" << endl;
                    cout << phaseNum[n] << "   " << lphaseNum[n] << endl;
                    cout << "minEigenSkip" << endl;
                    cout << minEigenSkip[n] << "   " << lminEigenSkip[n] << endl;
                    cout << "flagSkip" << endl;
                    cout << flagSkip[n] << "   " << lflagSkip[n] << endl;
                    cout << "PSkip" << endl;
                    cout << PSkip[n] << "   " << lPSkip[n] << endl;
                    cout << "ziSkip" << endl;
                    for (USI i = 0; i < numCom; i++) {
                        cout << ziSkip[n * numCom + i] << "   " << lziSkip[n * numCom + i] << endl;
                    }
                    cout << "Ks" << endl;
                    for (USI i = 0; i < numCom_1; i++) {
                        cout << Ks[n * numCom_1 + i] << "   " << lKs[n * numCom_1 + i] << endl;
                    }
                    cout << "Difference in S\t" << tmp << "  " << phaseExist[id]
                         << "\n";
                }
                tmp = fabs(xi[id] - lxi[id]);
                if (tmp >= 1E-10)
                {
                    cout << "Difference in Xi\t" << tmp << "  " << phaseExist[id]
                         << "\n";
                }
                tmp = fabs(rho[id] - lrho[id]);
                if (tmp >= 1E-10)
                {
                    cout << "Difference in rho\t" << tmp << "  " << phaseExist[id]
                         << "\n";
                }
            }
        }
    }
}
References OCP_FUNCNAME.
CheckInitVpore()
void Bulk::CheckInitVpore () const
Check initial pore volume.
Check init pore volume.
Definition at line 370 of file Bulk.cpp.
{
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        if (rockVpInit[n] < TINY)
        {
            OCP_ABORT("Bulk volume is too small: bulk[" + std::to_string(n) +
                      "] = " + std::to_string(rockVpInit[n]));
        }
    }
}
References OCP_ABORT, and TINY.
CheckNi()
bool Bulk::CheckNi ()
Check if negative Ni occurs, return false if so.
Return true if no negative Ni and false otherwise.
Definition at line 2284 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_USI len = numBulk * numCom;
    for (OCP_USI n = 0; n < len; n++)
    {
        if (Ni[n] < 0)
        {
            OCP_USI bId = n / numCom;
            if (Ni[n] > -1E-3 * Nt[bId] && false) {
                Ni[n] = 1E-8 * Nt[bId];
                // Ni[n] = 0;
            }
            else {
                USI cId = n - bId * numCom;
                std::ostringstream NiStringSci;
                NiStringSci << std::scientific << Ni[n];
                OCP_WARNING("Negative Ni: Ni[" + std::to_string(cId) + "] in Bulk[" +
                    std::to_string(bId) + "] = " + NiStringSci.str() + "   " +
                    "dNi = " + std::to_string(dNNR[n]) +
                    + "     lNi[" + std::to_string(cId) + "] in Bulk[" +
                    std::to_string(bId) + "] = " + std::to_string(lNi[n])
                    + "    Nt = " + std::to_string(Nt[bId]) + "   " + std::to_string(phaseNum[bId]) +
                    "   " + std::to_string(NRstep[bId]));
                for (USI i = 0; i < numCom; i++) {
                    cout << Ni[bId * numCom + i] << "   ";
                }
                cout << endl;
                for (USI j = 0; j < numPhase - 1; j++) {
                    cout << setprecision(9);
                    if (phaseExist[bId * numPhase + j]) {
                        cout << j << "   ";
                        for (USI i = 0; i < numCom_1; i++) {
                            cout << xij[bId * numPhase * numCom + j * numCom + i] << "   ";
                        }
                        cout << endl;
                    }
                }
                return false;
            }
        }
    }
    return true;
}
References OCP_FUNCNAME, and OCP_WARNING.
CheckNiFIMBulk()
bool Bulk::CheckNiFIMBulk () const
Check if negative Ni occurs, return false if so.
Definition at line 3900 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_USI len = numBulk * numCom;
    for (OCP_USI n = 0; n < len; n++)
    {
        if (Ni[n] < 0.0)
        {
            OCP_USI bId = n / numCom;
            USI cId = n - bId * numCom;
            std::ostringstream NiStringSci;
            NiStringSci << std::scientific << Ni[n];
            OCP_WARNING("Negative Ni: Ni[" + std::to_string(cId) + "] in Bulk[" +
                std::to_string(bId) + "] = " + NiStringSci.str());
            return false;
        }
    }
    return true;
}
References OCP_FUNCNAME, and OCP_WARNING.
CheckP()
bool Bulk::CheckP () const
Check if negative P occurs, return false if so.
Return true if no negative pressure and false otherwise.
Definition at line 2263 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        if (P[n] < 0)
        {
            std::ostringstream PStringSci;
            PStringSci << std::scientific << P[n];
            OCP_WARNING("Negative pressure: P[" + std::to_string(n) +
                        "] = " + PStringSci.str());
            cout << "P = " << P[n] << endl;
            return false;
        }
    }
    return true;
}
References OCP_FUNCNAME, and OCP_WARNING.
CheckSat()
void Bulk::CheckSat () const
Check if the sum of saturations is one.
Definition at line 2425 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_DBL tmp;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        tmp = 0.0;
        for (USI j = 0; j < numPhase; j++)
        {
            if (phaseExist[n * numPhase + j])
            {
                if (S[n * numPhase + j] < 0)
                {
                    OCP_ABORT("Negative volume!");
                }
                tmp += S[n * numPhase + j];
            }
        }
        if (fabs(tmp - 1) > TINY)
        {
            OCP_ABORT("Saturation is greater than 1!");
        }
    }
}
References OCP_ABORT, OCP_FUNCNAME, and TINY.
CheckSetup()
void Bulk::CheckSetup () const
Check if error occurs in Setup.
Definition at line 363 of file Bulk.cpp.
{
    CheckInitVpore();
    CheckVpore();
}
References CheckInitVpore(), and CheckVpore().
CheckVe()
bool Bulk::CheckVe (const OCP_DBL & Vlim) const
Check if relative volume error is out of range, return false if so.
Return true if all Ve < Vlim and false otherwise.
Definition at line 2331 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    // bool tmpflag = true;
    OCP_DBL dVe = 0.0;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        dVe = fabs(vf[n] - rockVp[n]) / rockVp[n];
        if (dVe > Vlim)
        {
            cout << "Volume error at Bulk[" << n << "] = " << setprecision(6) << dVe
                 << " is too big!" << endl;
            // OutputInfo(n);
            return false;
            // tmpflag = false;
        }
    }
    // OutputInfo(39);
    // if (!tmpflag) return false;
    return true;
}
References OCP_FUNCNAME.
CheckVpore()
void Bulk::CheckVpore () const
Check pore volume.
Definition at line 383 of file Bulk.cpp.
{
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        if (rockVp[n] < TINY)
        {
            OCP_ABORT("Bulk volume is too small: bulk[" + std::to_string(n) +
                      "] = " + std::to_string(rockVp[n]));
        }
    }
}
References OCP_ABORT, and TINY.
ClearWellBulkId()
void Bulk::ClearWellBulkId () inline
Definition at line 205 of file Bulk.hpp.
{ wellBulkId.clear(); }
CorrectNi()
void Bulk::CorrectNi (const vector< OCP_DBL > & res)
Definition at line 3323 of file Bulk.cpp.
{
    for (OCP_USI n = 0; n < numBulk; n++) {
        for (USI i = 0; i < numCom; i++) {
            Ni[n * numCom + i] += res[n * (numCom + 1) + i];
            if (Ni[n * numCom + i] < 0) {
                Ni[n * numCom + i] = 1E-8 * Nt[n];
            }
        }
    }
}
Flash()
void Bulk::Flash ()
Perform flash calculation with Ni.
Use moles of component and pressure both in blackoil and compositional model.
Definition at line 1385 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    if (comps) {
        FlashCOMP();
    }
    else {
        FlashBLKOIL();
    }
#ifdef DEBUG
    CheckSat();
#endif // DEBUG
}
References CheckSat(), FlashBLKOIL(), FlashCOMP(), and OCP_FUNCNAME.
FlashAIMc()
void Bulk::FlashAIMc ()
Perform flash calculation with Ni.
Definition at line 3953 of file Bulk.cpp.
{
    if (comps) {
        FlashCOMPAIMc();
    }
    else {
        FlashBLKOILAIMc();
    }
}
References FlashBLKOILAIMc(), and FlashCOMPAIMc().
FlashAIMc01()
void Bulk::FlashAIMc01 ()
Definition at line 4024 of file Bulk.cpp.
{
    if (comps) {
        FlashCOMPAIMc01();
    }
    else {
        FlashBLKOILAIMc01();
    }
}
FlashBLKOIL()
void Bulk::FlashBLKOIL ()
Perform flash calculation with Ni in Black Oil Model.
Definition at line 1402 of file Bulk.cpp.
{
    for (OCP_USI n = 0; n < numBulk; n++) {
        flashCal[PVTNUM[n]]->Flash(P[n], T, &Ni[n * numCom], 0, 0, 0);
        PassFlashValue(n);
    }
}
References PassFlashValue().
FlashBLKOILAIMc()
void Bulk::FlashBLKOILAIMc ()
Perform flash calculation with Ni in Black Oil Model.
Definition at line 3963 of file Bulk.cpp.
{
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        if (map_Bulk2FIM[n] > -1) {
            // FIM bulk
            continue;
        }
        flashCal[PVTNUM[n]]->Flash(P[n], T, &Ni[n * numCom], 0, 0, 0);
        PassFlashValueAIMc(n);
    }
}
FlashBLKOILAIMc01()
void Bulk::FlashBLKOILAIMc01 ()
Definition at line 4034 of file Bulk.cpp.
{
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        if (map_Bulk2FIM[n] > -1) {
            // FIM bulk
            continue;
        }
        flashCal[PVTNUM[n]]->Flash(P[n], T, &Ni[n * numCom], 0, 0, 0);
        PassFlashValue(n);
    }
}
FlashCOMP()
void Bulk::FlashCOMP ()
Perform flash calculation with Ni in Compositional Model.
Definition at line 1411 of file Bulk.cpp.
{
    USI ftype;
    OCP_USI bId;
    OCP_DBL Ntw;
    OCP_DBL minEig;
    fill(totalPhaseNum.begin(), totalPhaseNum.end(), 0);
    // cout << endl << "==================================" << endl;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        ftype = 1;
        if (flagSkip[n])
        {
            minEig = minEigenSkip[n];
            if (fabs(1 - PSkip[n] / P[n]) >= minEig / 10)
            {
                ftype = 0;
            }
            // cout << setprecision(2) << scientific << minEig / 10 << "   " << fabs(1 - lP[n] / P[n]) << "   ";
            if (ftype == 1)
            {
                bId = n * numCom;
                Ntw = Nt[n] - Ni[bId + numCom - 1];
                for (USI i = 0; i < numCom - 1; i++)
                {
                    // cout << fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) << "   ";
                    if (fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) >= minEig / 10)
                    {
                        ftype = 0;
                        break;
                    }
                }
            }
            // cout << n << endl;
        }
        else {
            ftype = 0;
        }
        flashCal[PVTNUM[n]]->Flash(P[n], T, &Ni[n * numCom], ftype, phaseNum[n], &Ks[n * numCom_1]);
        PassFlashValue(n);
    }
}
References PassFlashValue().
FlashCOMPAIMc()
void Bulk::FlashCOMPAIMc ()
Perform flash calculation with Ni in Compositional Model.
Definition at line 3977 of file Bulk.cpp.
{
    USI ftype;
    OCP_USI bId;
    OCP_DBL Ntw;
    OCP_DBL minEig;
    // cout << endl << "==================================" << endl;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        if (map_Bulk2FIM[n] > -1) {
            // FIM bulk
            continue;
        }
        ftype = 1;
        if (flagSkip[n])
        {
            minEig = minEigenSkip[n];
            if (fabs(1 - PSkip[n] / P[n]) >= minEig / 10)
            {
                ftype = 0;
            }
            // cout << setprecision(2) << scientific << minEig / 10 << "   " << fabs(1 - lP[n] / P[n]) << "   ";
            if (ftype == 1)
            {
                bId = n * numCom;
                Ntw = Nt[n] - Ni[bId + numCom - 1];
                for (USI i = 0; i < numCom - 1; i++)
                {
                    // cout << fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) << "   ";
                    if (fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) >= minEig / 10)
                    {
                        ftype = 0;
                        break;
                    }
                }
            }
            // cout << n << endl;
        }
        else {
            ftype = 0;
        }
        flashCal[PVTNUM[n]]->Flash(P[n], T, &Ni[n * numCom], ftype, phaseNum[n], &Ks[n * numCom_1]);
        PassFlashValueAIMc(n);
    }
}
FlashCOMPAIMc01()
void Bulk::FlashCOMPAIMc01 ()
Definition at line 4048 of file Bulk.cpp.
{
    USI ftype;
    OCP_USI bId;
    OCP_DBL Ntw;
    OCP_DBL minEig;
    // cout << endl << "==================================" << endl;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        if (map_Bulk2FIM[n] > -1) {
            // FIM bulk
            continue;
        }
        ftype = 1;
        if (flagSkip[n])
        {
            minEig = minEigenSkip[n];
            if (fabs(1 - PSkip[n] / P[n]) >= minEig / 10)
            {
                ftype = 0;
            }
            // cout << setprecision(2) << scientific << minEig / 10 << "   " << fabs(1 - lP[n] / P[n]) << "   ";
            if (ftype == 1)
            {
                bId = n * numCom;
                Ntw = Nt[n] - Ni[bId + numCom - 1];
                for (USI i = 0; i < numCom - 1; i++)
                {
                    // cout << fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) << "   ";
                    if (fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) >= minEig / 10)
                    {
                        ftype = 0;
                        break;
                    }
                }
            }
            // cout << n << endl;
        }
        else {
            ftype = 0;
        }
        flashCal[PVTNUM[n]]->Flash(P[n], T, &Ni[n * numCom], ftype, phaseNum[n], &Ks[n * numCom_1]);
        PassFlashValue(n);
    }
}
FlashDeriv()
void Bulk::FlashDeriv ()
Perform flash calculation with Ni and calculate derivatives.
Use moles of component and pressure both in blackoil and compositional model.
Definition at line 1456 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    if (comps) {
        FlashDerivCOMP();
    }
    else {
        FlashDerivBLKOIL();
    }
#ifdef DEBUG
    CheckSat();
#endif // DEBUG
}
References CheckSat(), FlashDerivBLKOIL(), FlashDerivCOMP(), and OCP_FUNCNAME.
FlashDeriv_n()
void Bulk::FlashDeriv_n ()
Definition at line 1472 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    if (comps) {
        FlashDerivCOMP_n();
    }
    else {
        FlashDerivBLKOIL_n();
    }
}
FlashDerivAIM()
void Bulk::FlashDerivAIM (const bool & IfAIMs)
Perform flash calculation with Ni and calculate derivatives.
Definition at line 3442 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    USI ftype;
    OCP_USI n, bIdc;
    OCP_DBL Ntw;
    OCP_DBL minEig;
    dSec_dPri.clear();
    USI len;
    if (IfAIMs) {
        len = FIMBulk.size();
    }
    else {
        len = numFIMBulk;
    }
    for (OCP_USI k = 0; k < len; k++)
    {
        n = FIMBulk[k];
        bIdc = n * numCom;
        ftype = 1;
        if (flagSkip[n])
        {
            minEig = minEigenSkip[n];
            if (fabs(1 - PSkip[n] / P[n]) >= minEig / 10) {
                ftype = 0;
            }
            if (ftype == 1) {
                Ntw = Nt[n] - Ni[bIdc + numCom_1];
                for (USI i = 0; i < numCom_1; i++)
                {
                    // cout << fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) << "   ";
                    if (fabs(Ni[bIdc + i] / Ntw - ziSkip[bIdc + i]) >= minEig / 10)
                    {
                        ftype = 0;
                        break;
                    }
                }
            }
            // cout << n << endl;
        }
        else {
            ftype = 0;
        }
        flashCal[PVTNUM[n]]->FlashDeriv(P[n], T, &Ni[n * numCom], ftype, phaseNum[n], &Ks[n * numCom_1]);
        PassFlashValueDerivAIM(k);
    }
#ifdef DEBUG
    CheckSat();
#endif // DEBUG
}
References CheckSat(), and OCP_FUNCNAME.
FlashDerivAIMc()
void Bulk::FlashDerivAIMc ()
Perform flash calculation with Ni and calculate derivatives.
Definition at line 4095 of file Bulk.cpp.
{
    if (comps) {
        FlashDerivCOMPAIMc();
    }
    else {
        FlashDerivBLKOILAIMc();
    }
}
References FlashDerivBLKOILAIMc(), and FlashDerivCOMPAIMc().
FlashDerivBLKOIL()
void Bulk::FlashDerivBLKOIL ()
Perform flash calculation with Ni in Black Oil Model.
Definition at line 1486 of file Bulk.cpp.
{
    // dSec_dPri.clear();
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        flashCal[PVTNUM[n]]->FlashDeriv(P[n], T, &Ni[n * numCom], 0, 0, 0);
        PassFlashValueDeriv(n);
    }
}
References PassFlashValueDeriv().
FlashDerivBLKOIL_n()
void Bulk::FlashDerivBLKOIL_n ()
Definition at line 1497 of file Bulk.cpp.
{
}
FlashDerivBLKOILAIMc()
void Bulk::FlashDerivBLKOILAIMc ()
Perform flash calculation with Ni in Black Oil Model.
Definition at line 4105 of file Bulk.cpp.
{
    // dSec_dPri.clear();
    for (auto& n : FIMBulk) {
        flashCal[PVTNUM[n]]->FlashDeriv(P[n], T, &Ni[n * numCom], 0, 0, 0);
        PassFlashValueDeriv(n);
    }
}
References PassFlashValueDeriv().
FlashDerivCOMP()
void Bulk::FlashDerivCOMP ()
Perform flash calculation with Ni in Compositional Model.
Definition at line 1504 of file Bulk.cpp.
{
    USI ftype;
    OCP_USI bId;
    OCP_DBL Ntw;
    OCP_DBL minEig;
    fill(totalPhaseNum.begin(), totalPhaseNum.end(), 0);
    NRdSSP = 0;
    maxNRdSSP = 0;
    index_maxNRdSSP = 0;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        ftype = 1;
        if (flagSkip[n])
        {
            minEig = minEigenSkip[n];
            if (fabs(1 - PSkip[n] / P[n]) >= minEig / 10)
            {
                ftype = 0;
            }
            // cout << setprecision(2) << scientific << minEig / 10 << "   " << fabs(1 - lP[n] / P[n]) << "   ";
            if (ftype == 1)
            {
                bId = n * numCom;
                Ntw = Nt[n] - Ni[bId + numCom_1];
                for (USI i = 0; i < numCom_1; i++)
                {
                    // cout << fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) << "   ";
                    if (fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) >= minEig / 10)
                    {
                        ftype = 0;
                        break;
                    }
                }
            }
            // cout << n << endl;
        }
        else {
            ftype = 0;
        }
        if (n == 303 && false) {
            cout << "----01----" << endl;
            cout << S[n * numPhase] << "   " << S[n * numPhase + 1] << "   "
                << S[n * numPhase + 2] << "   " << phaseNum[n] + 1 << endl;
        }
        flashCal[PVTNUM[n]]->FlashDeriv(P[n], T, &Ni[n * numCom], ftype, phaseNum[n], &Ks[n * numCom_1]);
        PassFlashValueDeriv(n);
        if (n == 303 && false) {
            cout << "----02----" << endl;
            cout << S[n * numPhase] << "   " << S[n * numPhase + 1] << "   "
                << S[n * numPhase + 2] << "   " << phaseNum[n] + 1 << endl;
        }
    }
}
References PassFlashValueDeriv().
FlashDerivCOMP_n()
void Bulk::FlashDerivCOMP_n ()
Definition at line 1565 of file Bulk.cpp.
{
    USI ftype;
    OCP_USI bId;
    OCP_DBL Ntw;
    OCP_DBL minEig;
    vector<USI> flagB(numPhase, 0);
    NRdSSP = 0;
    maxNRdSSP = 0;
    index_maxNRdSSP = 0;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        ftype = 1;
        if (flagSkip[n])
        {
            minEig = minEigenSkip[n];
            if (fabs(1 - PSkip[n] / P[n]) >= minEig / 10)
            {
                ftype = 0;
            }
            if (ftype == 1)
            {
                bId = n * numCom;
                Ntw = Nt[n] - Ni[bId + numCom_1];
                for (USI i = 0; i < numCom_1; i++)
                {
                    // cout << fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) << "   ";
                    if (fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) >= minEig / 10)
                    {
                        ftype = 0;
                        break;
                    }
                }
            }
            // cout << n << endl;
        }
        else {
            ftype = 0;
        }
        for (USI j = 0; j < numPhase; j++)
            flagB[j] = phaseExist[n * numPhase + j];
        if (n == 303 && false) {
            cout << "----01----" << endl;
            cout << S[n * numPhase] << "   " << S[n * numPhase + 1] << "   "
                << S[n * numPhase + 2] << "   " << phaseNum[n] + 1 << endl;
        }
        flashCal[PVTNUM[n]]->FlashDeriv_n(P[n], T, &Ni[n * numCom], &S[n * numPhase],
            &xij[n * numPhase * numCom], &nj[n * numPhase], ftype, &flagB[0],
            phaseNum[n], &Ks[n * numCom_1]);
        PassFlashValueDeriv_n(n);
        if (n == 303 && false) {
            cout << "----02----" << endl;
            cout << S[n * numPhase] << "   " << S[n * numPhase + 1] << "   "
                << S[n * numPhase + 2] << "   " << phaseNum[n] + 1 << endl;
        }
    }
}
FlashDerivCOMPAIMc()
void Bulk::FlashDerivCOMPAIMc ()
Perform flash calculation with Ni in Compositional Model.
Definition at line 4114 of file Bulk.cpp.
{
    USI ftype;
    OCP_USI bId;
    OCP_DBL Ntw;
    OCP_DBL minEig;
    // dSec_dPri.clear();
    for (auto& n : FIMBulk)
    {
        ftype = 1;
        if (flagSkip[n])
        {
            minEig = minEigenSkip[n];
            if (fabs(1 - PSkip[n] / P[n]) >= minEig / 10)
            {
                ftype = 0;
            }
            // cout << setprecision(2) << scientific << minEig / 10 << "   " << fabs(1 - lP[n] / P[n]) << "   ";
            if (ftype == 1)
            {
                bId = n * numCom;
                Ntw = Nt[n] - Ni[bId + numCom - 1];
                for (USI i = 0; i < numCom - 1; i++)
                {
                    // cout << fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) << "   ";
                    if (fabs(Ni[bId + i] / Ntw - ziSkip[bId + i]) >= minEig / 10)
                    {
                        ftype = 0;
                        break;
                    }
                }
            }
            // cout << n << endl;
        }
        else {
            ftype = 0;
        }
        flashCal[PVTNUM[n]]->FlashDeriv(P[n], T, &Ni[n * numCom], ftype, phaseNum[n], &Ks[n * numCom_1]);
        PassFlashValueDeriv(n);
        // lphaseNum[n];
    }
}
References PassFlashValueDeriv().
GetBulkNum()
OCP_USI Bulk::GetBulkNum () const inline
Return the number of bulks.
Definition at line 140 of file Bulk.hpp.
{ return numBulk; }
GetComNum()
USI Bulk::GetComNum () const inline
Return the number of components.
Definition at line 142 of file Bulk.hpp.
{ return numCom; }
GetdNmax()
OCP_DBL Bulk::GetdNmax () const inline
Return dNmax.
Definition at line 169 of file Bulk.hpp.
{ return dNmax; }
GetdPmax()
OCP_DBL Bulk::GetdPmax () const inline
Return dPmax.
Definition at line 167 of file Bulk.hpp.
{ return dPmax; }
GetdSmax()
OCP_DBL Bulk::GetdSmax () const inline
Return dSmax.
Definition at line 171 of file Bulk.hpp.
{ return dSmax; }
GetdVmax()
OCP_DBL Bulk::GetdVmax () const inline
Return dVmax.
Definition at line 173 of file Bulk.hpp.
{ return dVmax; }
GetMaxFIMBulk()
OCP_USI Bulk::GetMaxFIMBulk () const inline
Definition at line 492 of file Bulk.hpp.
{ return maxNumFIMBulk; }
GetMixMode()
USI Bulk::GetMixMode () const
Return the mixture mode.
Definition at line 2451 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    if (blackOil)
        return BLKOIL;
    else if (comps)
        return EOS_PVTW;
    else
        OCP_ABORT("Mixture model is not supported!");
}
References BLKOIL, EOS_PVTW, OCP_ABORT, and OCP_FUNCNAME.
GetMixture()
const vector< Mixture * > & Bulk::GetMixture () const inline
Return flash results (it has not been used by far).
Definition at line 148 of file Bulk.hpp.
{ return flashCal; }
GetNRdNmax()
OCP_DBL Bulk::GetNRdNmax ()
Definition at line 3318 of file Bulk.cpp.
{
    return NRdNmax;
}
GetNRdPmax()
OCP_DBL Bulk::GetNRdPmax ()
Return NRdPmax.
Definition at line 3307 of file Bulk.cpp.
{
    return NRdPmax;
}
GetNRdSmaxP()
OCP_DBL Bulk::GetNRdSmaxP ()
Return NRdSmaxP.
Definition at line 3313 of file Bulk.cpp.
{
    return NRdSmaxP;
}
GetNRSPiters()
OCP_ULL Bulk::GetNRSPiters () const inline
Definition at line 482 of file Bulk.hpp.
{ return flashCal[0]->GetNRSPiters(); }
GetNRSTAiters()
OCP_ULL Bulk::GetNRSTAiters () const inline
Definition at line 480 of file Bulk.hpp.
{ return flashCal[0]->GetNRSTAiters(); }
GetP()
OCP_DBL Bulk::GetP (const OCP_USI & n) const inline
Return pressure of the n-th bulk.
Definition at line 150 of file Bulk.hpp.
{ return P[n]; }
GetPhaseNum()
USI Bulk::GetPhaseNum () const inline
Return the number of phases.
Definition at line 144 of file Bulk.hpp.
{ return numPhase; }
GetSGAS()
OCP_DBL Bulk::GetSGAS (const OCP_USI & n) const inline
Return gas saturation of the n-th bulk.
Definition at line 157 of file Bulk.hpp.
    {
        return S[n * numPhase + phase2Index[GAS]];
    }
References GAS.
GetSOIL()
OCP_DBL Bulk::GetSOIL (const OCP_USI & n) const inline
Return oil saturation of the n-th bulk.
Definition at line 152 of file Bulk.hpp.
    {
        return S[n * numPhase + phase2Index[OIL]];
    }
References OIL.
GetSol01FIM()
void Bulk::GetSol01FIM (const vector< OCP_DBL > & u)
Get the solution for FIM after a Newton iteration???
Definition at line 3098 of file Bulk.cpp.
{
    GetSolAIMc(u, 1, 1);
}
GetSolAIMc()
void Bulk::GetSolAIMc (const vector< OCP_DBL > & u, const OCP_DBL & dPmaxlim, const OCP_DBL & dSmaxlim)
Definition at line 4188 of file Bulk.cpp.
{
    NRdPmax = 0;
    NRdNmax = 0;
    OCP_DBL tmp;
    USI row = numPhase * (numCom + 1);
    USI col = numCom + 1;
    OCP_DBL chopmin = 1;
    OCP_DBL choptmp = 0;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        //cout << "[" << n << "]" << endl;
        //cout << scientific << P[n] << "   " << u[n * ncol] << "   " << u[n * ncol] / P[n] << endl;
        dPNR[n] = u[n * col];
        tmp = fabs(dPNR[n] / P[n]);
        P[n] += dPNR[n];
        if (tmp > NRdPmax) {
            NRdPmax = tmp;
        }
        for (USI i = 0; i < numCom; i++)
        {
            /*cout << Ni[n * numCom + i] << "   " << u[n * ncol + 1 + i] << "   "
                << u[n * ncol + 1 + i] / Ni[n * numCom + i] << endl;*/
            if (Ni[n * numCom + i] + u[n * col + 1 + i] < 0) {
                dNNR[n * numCom + i] = -Ni[n * numCom + i];
                tmp = 1;
                Ni[n * numCom + i] = 1E-8 * Nt[n];
                // cout << Ni[n * numCom + i] << "   " << u[n * ncol + 1 + i] << endl;
            }
            else if (u[n * col + 1 + i] > Ni[n * numCom + i]) {
                dNNR[n * numCom + i] = Ni[n * numCom + i];
                tmp = 1;
                Ni[n * numCom + i] += dNNR[n * numCom + i];
            }
            else {
                dNNR[n * numCom + i] = u[n * col + 1 + i];
                tmp = fabs(dNNR[n * numCom + i]) / Ni[n * numCom + i];
                Ni[n * numCom + i] += dNNR[n * numCom + i];
            }
            if (tmp > NRdNmax) {
                NRdNmax = tmp;
            }
        }
    }
}
GetSolAIMc01()
void Bulk::GetSolAIMc01 (const vector< OCP_DBL > & u, const OCP_DBL & dPmaxlim, const OCP_DBL & dSmaxlim)
Definition at line 4240 of file Bulk.cpp.
{
    NRdSmaxP = 0;
    NRdPmax = 0;
    OCP_DBL dP;
    USI row0 = numPhase;
    USI row = numPhase * (numCom + 1);
    USI col = numCom + 1;
    USI bsize = row * col;
    vector<OCP_DBL> dtmp(row0, 0);
    OCP_DBL chopmin = 1;
    OCP_DBL choptmp = 0;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        if (map_Bulk2FIM[n] < 0) {
            // IMPEC Bulk
            // Pressure
            dP = u[n * col];
            NRdPmax = max(NRdPmax, fabs(dP));
            P[n] += dP; // seems better
            dPNR[n] = dP;
            NRstep[n] = 1;
            // Ni
            for (USI i = 0; i < numCom; i++)
            {
                dNNR[n * numCom + i] = u[n * col + 1 + i];
                Ni[n * numCom + i] += dNNR[n * numCom + i];
            }
            continue;
        }
        chopmin = 1;
        // compute the chop
        fill(dtmp.begin(), dtmp.end(), 0.0);
        DaAxpby(row0, col, 1, dSec_dPri.data() + n * bsize, u.data() + n * col, 1,
            dtmp.data());
        for (USI j = 0; j < numPhase; j++)
        {
            choptmp = 1;
            if (fabs(dtmp[j]) > dSmaxlim)
            {
                choptmp = dSmaxlim / fabs(dtmp[j]);
            }
            else if (S[n * numPhase + j] + dtmp[j] < 0.0)
            {
                choptmp = 0.9 * S[n * numPhase + j] / fabs(dtmp[j]);
            }
            chopmin = min(chopmin, choptmp);
            NRdSmaxP = max(NRdSmaxP, choptmp * fabs(dtmp[j]));
        }
        dP = u[n * col];
        choptmp = dPmaxlim / fabs(dP);
        chopmin = min(chopmin, choptmp);
        NRdPmax = max(NRdPmax, fabs(dP));
        P[n] += dP; // seems better
        dPNR[n] = dP;
        NRstep[n] = chopmin;
        for (USI i = 0; i < numCom; i++)
        {
            dNNR[n * numCom + i] = u[n * col + 1 + i] * chopmin;
            Ni[n * numCom + i] += dNNR[n * numCom + i];
        }
    }
}
GetSolAIMs()
void Bulk::GetSolAIMs (const vector< OCP_DBL > & u, const OCP_DBL & dPmaxlim, const OCP_DBL & dSmaxlim)
Definition at line 3761 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    NRdSmaxP = 0;
    NRdPmax = 0;
    OCP_DBL dP;
    USI row = numPhase * (numCom + 1);
    USI col = numCom + 1;
    USI bsize = row * col;
    vector<OCP_DBL> dtmp(row, 0);
    OCP_DBL chopmin = 1;
    OCP_DBL choptmp = 0;
    OCP_INT bIde;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        bIde = map_Bulk2FIM[n];
        if (bIde < 0 || bIde >= numFIMBulk) {
            // IMPEC Bulk
            // Method 1
            P[n] += u[n * col];
            // Method 2
            // P[n] = u[n * ncol];
            if (P[n] < 0) {
                cout << "";
            }
        }
        else {
            // FIM Bulk
            chopmin = 1;
            // compute the chop
            fill(dtmp.begin(), dtmp.end(), 0.0);
            DaAxpby(row, col, 1, dSec_dPri.data() + bIde * bsize, u.data() + bIde * col, 1,
                dtmp.data());
            for (USI j = 0; j < numPhase; j++)
            {
                choptmp = 1;
                if (fabs(dtmp[j]) > dSmaxlim)
                {
                    choptmp = dSmaxlim / fabs(dtmp[j]);
                }
                else if (S[n * numPhase + j] + dtmp[j] < 0.0)
                {
                    choptmp = 0.9 * S[n * numPhase + j] / fabs(dtmp[j]);
                }
                chopmin = min(chopmin, choptmp);
                NRdSmaxP = max(NRdSmaxP, choptmp * fabs(dtmp[j]));
            }
            dP = u[n * col];
            choptmp = dPmaxlim / fabs(dP);
            chopmin = min(chopmin, choptmp);
            dP *= chopmin;
            NRdPmax = max(NRdPmax, fabs(dP));
            P[n] += dP; // seems better
            // for (USI i = 0; i < numCom; i++) {
            //    if (Ni[n * numCom + i] + u[n * ncol + 1 + i] < 0) {
            //        chopmin = 0.9 * min(chopmin, fabs(Ni[n * numCom + i] / u[n * ncol + 1 +
            //        i]));
            //        //if (chopmin < 0 || !isfinite(chopmin)) {
            //        //    OCP_ABORT("Wrong Chop!");
            //        //}
            //    }
            //}
            for (USI i = 0; i < numCom; i++)
            {
                Ni[n * numCom + i] += u[n * col + 1 + i] * chopmin;
                // if (Ni[n * numCom + i] < 0) {
                //    cout << Ni[n * numCom + i] << "  " << u[n * ncol + 1 + i] * chopmin <<
                //    "   " << chopmin << endl;
                //}
            }
        }
    }
}
GetSolAIMt()
void Bulk::GetSolAIMt (const vector< OCP_DBL > & u, const OCP_DBL & dPmaxlim, const OCP_DBL & dSmaxlim)
Get the solution for local FIM after a Newton iteration.
Definition at line 3654 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    NRdSmaxP = 0;
    NRdPmax = 0;
    OCP_DBL dP;
    USI row = numPhase * (numCom + 1);
    USI col = numCom + 1;
    USI bsize = row * col;
    vector<OCP_DBL> dtmp(row, 0);
    OCP_DBL chopmin = 1;
    OCP_DBL choptmp = 0;
    for (OCP_USI fn = 0; fn < numFIMBulk; fn++)
    {
        OCP_USI n = FIMBulk[fn];
        chopmin = 1;
        // compute the chop
        fill(dtmp.begin(), dtmp.end(), 0.0);
        DaAxpby(row, col, 1, dSec_dPri.data() + fn * bsize, u.data() + fn * col, 1,
            dtmp.data());
        for (USI j = 0; j < numPhase; j++)
        {
            choptmp = 1;
            if (fabs(dtmp[j]) > dSmaxlim)
            {
                choptmp = dSmaxlim / fabs(dtmp[j]);
            }
            else if (S[n * numPhase + j] + dtmp[j] < 0.0)
            {
                choptmp = 0.9 * S[n * numPhase + j] / fabs(dtmp[j]);
            }
            chopmin = min(chopmin, choptmp);
            NRdSmaxP = max(NRdSmaxP, choptmp * fabs(dtmp[j]));
        }
        dP = u[fn * col];
        choptmp = dPmaxlim / fabs(dP);
        chopmin = min(chopmin, choptmp);
        dP *= chopmin;
        NRdPmax = max(NRdPmax, fabs(dP));
        P[n] += dP; // seems better
        // for (USI i = 0; i < numCom; i++) {
        //    if (Ni[n * numCom + i] + u[n * ncol + 1 + i] < 0) {
        //        chopmin = 0.9 * min(chopmin, fabs(Ni[n * numCom + i] / u[n * ncol + 1 +
        //        i]));
        //        //if (chopmin < 0 || !isfinite(chopmin)) {
        //        //    OCP_ABORT("Wrong Chop!");
        //        //}
        //    }
        //}
        for (USI i = 0; i < numCom; i++)
        {
            Ni[n * numCom + i] += u[fn * col + 1 + i] * chopmin;
            // if (Ni[n * numCom + i] < 0) {
            //    cout << Ni[n * numCom + i] << "  " << u[n * ncol + 1 + i] * chopmin <<
            //    "   " << chopmin << endl;
            //}
        }
    }
}
References DaAxpby(), and OCP_FUNCNAME.
GetSolFIM()
void Bulk::GetSolFIM (const vector< OCP_DBL > & u, const OCP_DBL & dPmaxlim, const OCP_DBL & dSmaxlim)
Get the solution for FIM after a Newton iteration.
Definition at line 2807 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    dSNR = S;
    NRphaseNum = phaseNum;
    NRdSmaxP = 0;
    NRdPmax = 0;
    NRdNmax = 0;
    OCP_DBL dP;
    USI row0 = numPhase;
    USI row = numPhase * (numCom + 1);
    USI col = numCom + 1;
    USI bsize = row * col;
    vector<OCP_DBL> dtmp(row0, 0);
    OCP_DBL chopmin = 1;
    OCP_DBL choptmp = 0;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        chopmin = 1;
        // compute the chop
        fill(dtmp.begin(), dtmp.end(), 0.0);
#ifdef OCP_NEW_FIM
        DaAxpby(phaseNum[n] + 1, col, 1, dSec_dPri.data() + dSdPindex[n], u.data() + n * col, 1,
            dtmp.data());
        const bool newFIM = true;
#else
        DaAxpby(row0, col, 1, dSec_dPri.data() + n * bsize, u.data() + n * col, 1,
                dtmp.data());
        const bool newFIM = false;
#endif // OCP_NEW_FIM
        USI js = 0;
        for (USI j = 0; j < numPhase; j++)
        {
            if (!phaseExist[n * numPhase + j] && newFIM) {
                continue;
            }
            choptmp = 1;
            if (fabs(dtmp[js]) > dSmaxlim)
            {
                choptmp = dSmaxlim / fabs(dtmp[js]);
            }
            else if (S[n * numPhase + j] + dtmp[js] < 0.0)
            {
                choptmp = 0.9 * S[n * numPhase + j] / fabs(dtmp[js]);
            }
            chopmin = min(chopmin, choptmp);
            js++;
        }
        js = 0;
        for (USI j = 0; j < numPhase; j++) {
            if (!phaseExist[n * numPhase + j] && newFIM) {
                dSNRP[n * numPhase + j] = 0;
                continue;
            }
            dSNRP[n * numPhase + j] = chopmin * dtmp[js];
            if (fabs(NRdSmaxP) < fabs(dSNRP[n * numPhase + j]))
                NRdSmaxP = dSNRP[n * numPhase + j];
            js++;
        }
        dP = u[n * col];
        //choptmp = dPmaxlim / fabs(dP);
        //chopmin = min(chopmin, choptmp);
        if (fabs(NRdPmax) < fabs(dP))  NRdPmax = dP;
        P[n] += dP; // seems better
        dPNR[n] = dP;
        NRstep[n] = chopmin;
        for (USI i = 0; i < numCom; i++)
        {
            dNNR[n * numCom + i] = u[n * col + 1 + i] * chopmin;
            if (fabs(NRdNmax) < fabs(dNNR[n * numCom + i]) / Nt[n])
                NRdNmax = dNNR[n * numCom + i] / Nt[n];
            Ni[n * numCom + i] += dNNR[n * numCom + i];
        }
        //cout << scientific << setprecision(6) << dP << "   " << n << endl;
    }
}
References DaAxpby(), and OCP_FUNCNAME.
GetSolFIM_n()
void Bulk::GetSolFIM_n (const vector< OCP_DBL > & u, const OCP_DBL & dPmaxlim, const OCP_DBL & dSmaxlim)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Definition at line 2901 of file Bulk.cpp.
{
    // For saturations changes:
    // 1. maximum changes must be less than dSmaxlim,
    // 2. if phases become mobile/immobile, then set it to crtical point,
    // 3. After saturations are determined, then scale the nij to conserve Volume equations.
    OCP_FUNCNAME;
    dSNR = S;
    NRphaseNum = phaseNum;
    fill(dSNRP.begin(), dSNRP.end(), 0.0);
    NRdSmaxP = 0;
    NRdPmax = 0;
    NRdNmax = 0;
    USI row = numPhase * (numCom + 1);
    USI ncol = numCom + 1;
    USI n_np_j;
    vector<OCP_DBL> dtmp(row, 0);
    vector<OCP_DBL> tmpNij(numPhase * numCom, 0);
    OCP_DBL dSmax;
    OCP_DBL dP;
    OCP_DBL chop = 1;
    //vector<OCP_DBL> tmpxi(numPhase, 0);
    //vector<OCP_DBL> tmpVf(numPhase, 0);
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        const vector<OCP_DBL>& scm = satcm[SATNUM[n]];
        dP = u[n * ncol];  dPNR[n] = dP;
        P[n] += dP; // seems better
        if (fabs(NRdPmax) < fabs(dP))  NRdPmax = dP;
        //rockVp[n] = rockVpInit[n] * (1 + rockC1 * (P[n] - rockPref));
        //cout << scientific << setprecision(6) << dP << "   " << n << endl;
        dSmax = 0;
        chop = 1;
        if (n == 303 && false)
        {
            const USI len = resIndex[n + 1] - resIndex[n];
            fill(dtmp.begin(), dtmp.end(), 0.0);
            DaAxpby(len, ncol, 1, dSec_dPri.data() + dSdPindex[n], u.data() + n * ncol, 1,
                dtmp.data());
        }
        const USI cNp = phaseNum[n] + 1;
        const USI len = resIndex[n + 1] - resIndex[n];
        Dcopy(cNp, &dtmp[0], &res_n[resIndex[n]]);
        DaAxpby(cNp, ncol, 1.0, dSec_dPri.data() + dSdPindex[n], u.data() + n * ncol, 1.0,
            dtmp.data());
        // Calculate dSmax
        USI js = 0;
        for (USI j = 0; j < numPhase; j++) {
            n_np_j = n * numPhase + j;
            if (phaseExist[n_np_j]) {
                dSmax = max(fabs(dtmp[js]), dSmax);
                js++;
            }
        }
        // Calculate chop
        if (dSmax > dSmaxlim) {
            chop = min(chop, dSmaxlim / dSmax);
            dSmax = dSmaxlim;
        }
        js = 0;
        for (USI j = 0; j < numPhase; j++) {
            n_np_j = n * numPhase + j;
            if (phaseExist[n_np_j]) {
                if (fabs(S[n_np_j] - scm[j]) > TINY && (S[n_np_j] - scm[j]) / (chop * dtmp[js]) < 0)
                    chop *= min(1.0, -((S[n_np_j] - scm[j]) / (chop * dtmp[js])));
                if (S[n_np_j] + chop * dtmp[js] < 0)
                    chop *= min(1.0, -S[n_np_j] / (chop * dtmp[js]));
                js++;
            }
        }
        if (n == 303 && false) {
            cout << scientific << setprecision(12);
            cout << 303 << "   chop =   " << chop << endl;
            cout << "old xij" << endl;
            js = 0;
            for (USI j = 0; j < numPhase-1; j++) {
                if (phaseExist[n * numPhase + j]) {
                    cout << j << "   " << S[n * numPhase + j] << "   "
                        << chop * dtmp[js] << endl << endl;
                    for (USI i = 0; i < numCom; i++) {
                        cout << xij[(n * numPhase + j) * numCom + i] << "   " <<
                            xij[(n * numPhase + j) * numCom + i] * nj[n * numPhase + j] << endl;
                    }
                    cout << endl;
                    js++;
                }
            }
        }
        // Calculate S, phaseExist, xij, nj
        //fill(tmpNij.begin(), tmpNij.end(), 0.0);
        //fill(Ni.begin() + n * numCom, Ni.begin() + n * numCom + numCom, 0.0);
        js = 0;  USI jx = cNp;
        for (USI j = 0; j < numPhase; j++) {
            n_np_j = n * numPhase + j;
            if (phaseExist[n_np_j]) {
                dSNRP[n_np_j] = chop * dtmp[js];
                if (fabs(NRdSmaxP) < fabs(dSNRP[n_np_j]))
                    NRdSmaxP = dSNRP[n_np_j];
                js++;
                //S[n_np_j] += chop * dtmp[js];
                //if (S[n_np_j] < TINY) {
                //    phaseExist[n_np_j] = false;
                //}
                //js++;
                //Daxpy(numCom, nj[n_np_j], &xij[n_np_j * numCom], &tmpNij[j * numCom]);
                //for (USI i = 0; i < pEnumCom[j]; i++) {
                //    tmpNij[j * numCom + i] += chop * dtmp[jx + i];
                //    // CheckNi(tmp)
                //    if (tmpNij[j * numCom + i] < 0) {
                //        cout << scientific << setprecision(6) << "n" << i << j << " = " << tmpNij[j * numCom + i] << endl;
                //        OCP_WARNING("Negative Ni");
                //    }
                //}
                //jx += pEnumCom[j];
                //nj[n_np_j] = Dnorm1(numCom, &tmpNij[j * numCom]);
                //for (USI i = 0; i < numCom; i++) {
                //    xij[n_np_j * numCom + i] = tmpNij[j * numCom + i] / nj[n_np_j];
                //    Ni[n * numCom + i] += tmpNij[j * numCom + i];
                //}
            }
        }
        // Vf correction
/*        OCP_DBL dVmin = 100 * rockVp[n];
        USI index = 0;
        for (USI j = 0; j < numPhase; j++) {
            if (phaseExist[n * numPhase + j]) {
                tmpxi[j] = flashCal[PVTNUM[n]]->XiPhase(P[n], T, &xij[(n * numPhase + j) * numCom]);
                tmpVf[j] = nj[n * numPhase + j] / (S[n * numPhase + j] * tmpxi[j]);
                if (fabs(tmpVf[j] - rockVp[n]) < dVmin) {
                    dVmin = fabs(tmpVf[j] - rockVp[n]);
                    index = j;
                }
            }
        } */
        //for (USI j = 0; j < numPhase; j++) {
        //    if (phaseExist[n * numPhase + j]) {
        //        nj[n * numPhase + j] *= (tmpVf[index] / tmpVf[j]);
        //        for (USI i = 0; i < numCom; i++) {
        //            Ni[n * numCom + i] += nj[n * numPhase + j] * xij[(n * numPhase + j) * numCom + i];
        //        }
        //    }
        //}
        NRstep[n] = chop;
        for (USI i = 0; i < numCom; i++)
        {
            dNNR[n * numCom + i] = u[n * ncol + 1 + i] * chop;
            if (fabs(NRdNmax) < fabs(dNNR[n * numCom + i]) / Nt[n])
                NRdNmax = dNNR[n * numCom + i] / Nt[n];
            Ni[n * numCom + i] += dNNR[n * numCom + i];
        }
        if (n == 303 && false) {
            cout << "new xij" << endl;
            for (USI j = 0; j < numPhase - 1; j++) {
                if (phaseExist[n * numPhase + j]) {
                    cout << j << "   " << S[n * numPhase + j] << endl << endl;
                    for (USI i = 0; i < numCom; i++) {
                        cout << xij[(n * numPhase + j) * numCom + i] << "   " <<
                            xij[(n * numPhase + j) * numCom + i] * nj[n * numPhase + j] << endl;
                    }
                    cout << endl;
                }
            }
        }
    }
}
References DaAxpby(), Dcopy(), OCP_FUNCNAME, and TINY.
GetSolIMPEC()
void Bulk::GetSolIMPEC (const vector< OCP_DBL > & u)
Update P and Pj after linear system is solved.
Definition at line 2656 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        P[n] = u[n];
        for (USI j = 0; j < numPhase; j++)
        {
            OCP_USI id = n * numPhase + j;
            if (phaseExist[id])
                Pj[id] = P[n] + Pc[id];
        }
    }
}
References OCP_FUNCNAME.
GetSSMSPiters()
OCP_ULL Bulk::GetSSMSPiters () const inline
Definition at line 481 of file Bulk.hpp.
{ return flashCal[0]->GetSSMSPiters(); }
GetSSMSTAiters()
OCP_ULL Bulk::GetSSMSTAiters () const inline
Definition at line 479 of file Bulk.hpp.
{ return flashCal[0]->GetSSMSTAiters(); }
GetSWAT()
OCP_DBL Bulk::GetSWAT (const OCP_USI & n) const inline
Return water saturation of the n-th bulk.
Definition at line 162 of file Bulk.hpp.
    {
        return S[n * numPhase + phase2Index[WATER]];
    }
References WATER.
InFIMNi()
void Bulk::InFIMNi ()
Ni in FIM Bulk -> FIMNi.
Definition at line 3922 of file Bulk.cpp.
{
    OCP_USI bIdb, bIdf;
    for (OCP_USI n = 0; n < numFIMBulk; n++) {
        bIdf = n * numCom;
        bIdb = FIMBulk[n] * numCom;
        for (USI i = 0; i < numCom; i++) {
            FIMNi[bIdf + i] = Ni[bIdb + i];
        }
    }
}
InitFlash()
void Bulk::InitFlash (const bool & flag = false)
Perform flash calculation with saturations.
Use initial saturation in blackoil model and initial Zi in compositional model. It gives initial properties and some derivatives for IMPEC It just gives Ni for FIM
Definition at line 1358 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        flashCal[PVTNUM[n]]->InitFlash(P[n], Pb[n], T, &S[n * numPhase], rockVp[n],
                                       initZi.data());
        for (USI i = 0; i < numCom; i++)
        {
            Ni[n * numCom + i] = flashCal[PVTNUM[n]]->Ni[i];
        }
        if (flag)
        {
            PassFlashValue(n);
        }
    }
#ifdef DEBUG
    if (flag)
    {
        CheckSat();
    }
#endif // DEBUG
}
References CheckSat(), OCP_FUNCNAME, and PassFlashValue().
InitSjPcBo()
void Bulk::InitSjPcBo (const USI & tabrow)
Calculate initial equilibrium for blkoil model according to EQUIL.
Here tabrow is maximum number of depth nodes in table of depth vs pressure.
Definition at line 396 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_DBL Dref = EQUIL.Dref;
    OCP_DBL Pref = EQUIL.Pref;
    OCP_DBL DOWC = EQUIL.DOWC;
    OCP_DBL PcOW = EQUIL.PcOW;
    OCP_DBL DOGC = EQUIL.DGOC;
    OCP_DBL PcGO = EQUIL.PcGO;
    OCP_DBL Zmin = 1E8;
    OCP_DBL Zmax = 0;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        OCP_DBL temp1 = depth[n] - dz[n] / 2;
        OCP_DBL temp2 = depth[n] + dz[n] / 2;
        Zmin = Zmin < temp1 ? Zmin : temp1;
        Zmax = Zmax > temp2 ? Zmax : temp2;
    }
    OCP_DBL tabdz = (Zmax - Zmin) / (tabrow - 1);
    // creater table
    OCPTable DepthP(tabrow, 4);
    vector<OCP_DBL> &Ztmp = DepthP.GetCol(0);
    vector<OCP_DBL> &Potmp = DepthP.GetCol(1);
    vector<OCP_DBL> &Pgtmp = DepthP.GetCol(2);
    vector<OCP_DBL> &Pwtmp = DepthP.GetCol(3);
    // cal Tab_Ztmp
    Ztmp[0] = Zmin;
    for (USI i = 1; i < tabrow; i++)
    {
        Ztmp[i] = Ztmp[i - 1] + tabdz;
    }
    // find the RefId
    USI beginId = 0;
    if (Dref <= Ztmp[0])
    {
        beginId = 0;
    }
    else if (Dref >= Ztmp[tabrow - 1])
    {
        beginId = tabrow - 1;
    }
    else
    {
        beginId = distance(Ztmp.begin(), find_if(Ztmp.begin(), Ztmp.end(),
                                                 [s = Dref](auto& t)
                                                 { return t > s; }));
        beginId--;
    }
    // begin calculating oil pressure
    OCP_DBL Pbb = Pref;
    OCP_DBL gammaOtmp, gammaWtmp, gammaGtmp;
    OCP_DBL Ptmp;
    USI mynum = 10;
    OCP_DBL mydz = 0;
    OCP_DBL Poref, Pgref, Pwref;
    OCP_DBL Pbegin = 0;
    if (Dref < DOGC)
    {
        // reference pressure is gas pressure
        if (!gas)
            OCP_ABORT("SGOF is missing!");
        Pgref = Pref;
        gammaGtmp = flashCal[0]->GammaPhaseG(Pgref);
        Pbegin = Pgref + gammaGtmp * (Ztmp[beginId] - Dref);
        Pgtmp[beginId] = Pbegin;
        // find the gas pressure
        for (USI id = beginId; id > 0; id--)
        {
            gammaGtmp = flashCal[0]->GammaPhaseG(Pgtmp[id]);
            Pgtmp[id - 1] = Pgtmp[id] - gammaGtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaGtmp = flashCal[0]->GammaPhaseG(Pgtmp[id]);
            Pgtmp[id + 1] = Pgtmp[id] + gammaGtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
        // find the oil pressure in Dref by Pgref
        Poref = 0;
        Ptmp = Pgref;
        mydz = (DOGC - Dref) / mynum;
        for (USI i = 0; i < mynum; i++)
        {
            gammaGtmp = flashCal[0]->GammaPhaseG(Ptmp);
            Ptmp += gammaGtmp * mydz;
        }
        Ptmp -= PcGO;
        for (USI i = 0; i < mynum; i++)
        {
            if (!EQUIL.PBVD.IsEmpty())
            {
                Pbb = EQUIL.PBVD.Eval(0, DOGC - i * mydz, 1);
            }
            gammaOtmp = flashCal[0]->GammaPhaseO(Ptmp, Pbb);
            Ptmp -= gammaOtmp * mydz;
        }
        Poref = Ptmp;
        // find the oil pressure in tab
        if (!EQUIL.PBVD.IsEmpty())
        {
            Pbb = EQUIL.PBVD.Eval(0, Dref, 1);
        }
        gammaOtmp = flashCal[0]->GammaPhaseO(Poref, Pbb);
        Pbegin = Poref + gammaOtmp * (Ztmp[beginId] - Dref);
        Potmp[beginId] = Pbegin;
        for (USI id = beginId; id > 0; id--)
        {
            if (!EQUIL.PBVD.IsEmpty())
            {
                Pbb = EQUIL.PBVD.Eval(0, Ztmp[id], 1);
            }
            gammaOtmp = flashCal[0]->GammaPhaseO(Potmp[id], Pbb);
            Potmp[id - 1] = Potmp[id] - gammaOtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            if (!EQUIL.PBVD.IsEmpty())
            {
                Pbb = EQUIL.PBVD.Eval(0, Ztmp[id], 1);
            }
            gammaOtmp = flashCal[0]->GammaPhaseO(Potmp[id], Pbb);
            Potmp[id + 1] = Potmp[id] + gammaOtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
        // find the water pressure in Dref by Poref
        Pwref = 0;
        Ptmp = Poref;
        mydz = (DOWC - Dref) / mynum;
        for (USI i = 0; i < mynum; i++)
        {
            if (!EQUIL.PBVD.IsEmpty())
            {
                Pbb = EQUIL.PBVD.Eval(0, Dref + i * mydz, 1);
            }
            gammaOtmp = flashCal[0]->GammaPhaseO(Ptmp, Pbb);
            Ptmp += gammaOtmp * mydz;
        }
        Ptmp -= PcOW;
        for (USI i = 0; i < mynum; i++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Ptmp);
            Ptmp -= gammaWtmp * mydz;
        }
        Pwref = Ptmp;
        // find the water pressure in tab
        gammaWtmp = flashCal[0]->GammaPhaseW(Pwref);
        Pbegin = Pwref + gammaWtmp * (Ztmp[beginId] - Dref);
        Pwtmp[beginId] = Pbegin;
        for (USI id = beginId; id > 0; id--)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id - 1] = Pwtmp[id] - gammaWtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id + 1] = Pwtmp[id] + gammaWtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
    }
    else if (Dref > DOWC)
    {
        // reference pressure is water pressure
        Pwref = Pref;
        gammaWtmp = flashCal[0]->GammaPhaseW(Pwref);
        Pbegin = Pwref + gammaWtmp * (Ztmp[beginId] - Dref);
        Pwtmp[beginId] = Pbegin;
        // find the water pressure
        for (USI id = beginId; id > 0; id--)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id - 1] = Pwtmp[id] - gammaWtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id + 1] = Pwtmp[id] + gammaWtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
        // find the oil pressure in Dref by Pwref
        Poref = 0;
        Ptmp = Pwref;
        mydz = (DOWC - Dref) / mynum;
        for (USI i = 0; i < mynum; i++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Ptmp);
            Ptmp += gammaWtmp * mydz;
        }
        Ptmp += PcOW;
        for (USI i = 0; i < mynum; i++)
        {
            if (!EQUIL.PBVD.IsEmpty())
            {
                Pbb = EQUIL.PBVD.Eval(0, DOWC - i * mydz, 1);
            }
            gammaOtmp = flashCal[0]->GammaPhaseO(Ptmp, Pbb);
            Ptmp -= gammaOtmp * mydz;
        }
        Poref = Ptmp;
        // find the oil pressure in tab
        if (!EQUIL.PBVD.IsEmpty())
        {
            Pbb = EQUIL.PBVD.Eval(0, Dref, 1);
        }
        gammaOtmp = flashCal[0]->GammaPhaseO(Poref, Pbb);
        Pbegin = Poref + gammaOtmp * (Ztmp[beginId] - Dref);
        Potmp[beginId] = Pbegin;
        for (USI id = beginId; id > 0; id--)
        {
            if (!EQUIL.PBVD.IsEmpty())
            {
                Pbb = EQUIL.PBVD.Eval(0, Ztmp[id], 1);
            }
            gammaOtmp = flashCal[0]->GammaPhaseO(Potmp[id], Pbb);
            Potmp[id - 1] = Potmp[id] - gammaOtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            if (!EQUIL.PBVD.IsEmpty())
            {
                Pbb = EQUIL.PBVD.Eval(0, Ztmp[id], 1);
            }
            gammaOtmp = flashCal[0]->GammaPhaseO(Potmp[id], Pbb);
            Potmp[id + 1] = Potmp[id] + gammaOtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
        if (gas)
        {
            // find the gas pressure in Dref by Poref
            Pgref = 0;
            Ptmp = Poref;
            mydz = (DOGC - Dref) / mynum;
            for (USI i = 0; i < mynum; i++)
            {
                if (!EQUIL.PBVD.IsEmpty())
                {
                    Pbb = EQUIL.PBVD.Eval(0, Dref + i * mydz, 1);
                }
                gammaOtmp = flashCal[0]->GammaPhaseO(Ptmp, Pbb);
                Ptmp += gammaOtmp * mydz;
            }
            Ptmp += PcGO;
            for (USI i = 0; i < mynum; i++)
            {
                gammaGtmp = flashCal[0]->GammaPhaseG(Ptmp);
                Ptmp -= gammaGtmp * mydz;
            }
            Pgref = Ptmp;
            // find the gas pressure in tab
            gammaGtmp = flashCal[0]->GammaPhaseG(Pgref);
            Pbegin = Pgref + gammaGtmp * (Ztmp[beginId] - Dref);
            Pgtmp[beginId] = Pbegin;
            for (USI id = beginId; id > 0; id--)
            {
                gammaGtmp = flashCal[0]->GammaPhaseG(Pgtmp[id]);
                Pgtmp[id - 1] = Pgtmp[id] - gammaGtmp * (Ztmp[id] - Ztmp[id - 1]);
            }
            for (USI id = beginId; id < tabrow - 1; id++)
            {
                gammaGtmp = flashCal[0]->GammaPhaseG(Pgtmp[id]);
                Pgtmp[id + 1] = Pgtmp[id] + gammaGtmp * (Ztmp[id + 1] - Ztmp[id]);
            }
        }
    }
    else
    {
        // reference pressure is oil pressure
        Poref = Pref;
        if (!EQUIL.PBVD.IsEmpty())
        {
            Pbb = EQUIL.PBVD.Eval(0, Dref, 1);
        }
        gammaOtmp = flashCal[0]->GammaPhaseO(Poref, Pbb);
        Pbegin = Poref + gammaOtmp * (Ztmp[beginId] - Dref);
        Potmp[beginId] = Pbegin;
        // find the oil pressure in tab
        for (USI id = beginId; id > 0; id--)
        {
            if (!EQUIL.PBVD.IsEmpty())
            {
                Pbb = EQUIL.PBVD.Eval(0, Ztmp[id], 1);
            }
            gammaOtmp = flashCal[0]->GammaPhaseO(Potmp[id], Pbb);
            Potmp[id - 1] = Potmp[id] - gammaOtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            if (!EQUIL.PBVD.IsEmpty())
            {
                Pbb = EQUIL.PBVD.Eval(0, Ztmp[id], 1);
            }
            gammaOtmp = flashCal[0]->GammaPhaseO(Potmp[id], Pbb);
            Potmp[id + 1] = Potmp[id] + gammaOtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
        if (gas)
        {
            // find the gas pressure in Dref by Poref
            Pgref = 0;
            Ptmp = Poref;
            mydz = (DOGC - Dref) / mynum;
            for (USI i = 0; i < mynum; i++)
            {
                if (!EQUIL.PBVD.IsEmpty())
                {
                    Pbb = EQUIL.PBVD.Eval(0, Dref + i * mydz, 1);
                }
                gammaOtmp = flashCal[0]->GammaPhaseO(Ptmp, Pbb);
                Ptmp += gammaOtmp * mydz;
            }
            Ptmp += PcGO;
            for (USI i = 0; i < mynum; i++)
            {
                gammaGtmp = flashCal[0]->GammaPhaseG(Ptmp);
                Ptmp -= gammaGtmp * mydz;
            }
            Pgref = Ptmp;
            // find the gas pressure in tab
            gammaGtmp = flashCal[0]->GammaPhaseG(Pgref);
            Pbegin = Pgref + gammaGtmp * (Ztmp[beginId] - Dref);
            Pgtmp[beginId] = Pbegin;
            for (USI id = beginId; id > 0; id--)
            {
                gammaGtmp = flashCal[0]->GammaPhaseG(Pgtmp[id]);
                Pgtmp[id - 1] = Pgtmp[id] - gammaGtmp * (Ztmp[id] - Ztmp[id - 1]);
            }
            for (USI id = beginId; id < tabrow - 1; id++)
            {
                gammaGtmp = flashCal[0]->GammaPhaseG(Pgtmp[id]);
                Pgtmp[id + 1] = Pgtmp[id] + gammaGtmp * (Ztmp[id + 1] - Ztmp[id]);
            }
        }
        // find the water pressure in Dref by Poref
        Pwref = 0;
        Ptmp = Poref;
        mydz = (DOWC - Dref) / mynum;
        for (USI i = 0; i < mynum; i++)
        {
            if (!EQUIL.PBVD.IsEmpty())
            {
                Pbb = EQUIL.PBVD.Eval(0, Dref + i * mydz, 1);
            }
            gammaOtmp = flashCal[0]->GammaPhaseO(Ptmp, Pbb);
            Ptmp += gammaOtmp * mydz;
        }
        Ptmp -= PcOW;
        for (USI i = 0; i < mynum; i++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Ptmp);
            Ptmp -= gammaWtmp * mydz;
        }
        Pwref = Ptmp;
        // find the water pressure in tab
        gammaWtmp = flashCal[0]->GammaPhaseW(Pwref);
        Pbegin = Pwref + gammaWtmp * (Ztmp[beginId] - Dref);
        Pwtmp[beginId] = Pbegin;
        for (USI id = beginId; id > 0; id--)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id - 1] = Pwtmp[id] - gammaWtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id + 1] = Pwtmp[id] + gammaWtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
    }
    DepthP.Display();
    // calculate Pc from DepthP to calculate Sj
    std::vector<OCP_DBL> data(4, 0), cdata(4, 0);
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        DepthP.Eval_All(0, depth[n], data, cdata);
        OCP_DBL Po = data[1];
        OCP_DBL Pg = data[2];
        OCP_DBL Pw = data[3];
        OCP_DBL Pcgo = Pg - Po;
        OCP_DBL Pcow = Po - Pw;
        OCP_DBL Sw = flow[0]->GetSwByPcow(Pcow);
        OCP_DBL Sg = 0;
        if (gas)
        {
            Sg = flow[0]->GetSgByPcgo(Pcgo);
        }
        if (Sw + Sg > 1)
        {
            // should me modified
            OCP_DBL Pcgw = Pcow + Pcgo;
            Sw = flow[0]->GetSwByPcgw(Pcgw);
            Sg = 1 - Sw;
        }
        if (1 - Sw < TINY)
        {
            // all water
            Po = Pw + flow[0]->GetPcowBySw(1.0);
        }
        else if (1 - Sg < TINY)
        {
            // all gas
            Po = Pg - flow[0]->GetPcgoBySg(1.0);
        }
        else if (1 - Sw - Sg < TINY)
        {
            // water and gas
            Po = Pg - flow[0]->GetPcgoBySg(Sg);
        }
        P[n] = Po;
        if (depth[n] < DOGC)
        {
            Pbb = Po;
        }
        else if (!EQUIL.PBVD.IsEmpty())
        {
            Pbb = EQUIL.PBVD.Eval(0, depth[n], 1);
        }
        Pb[n] = Pbb;
        // cal Sg and Sw
        Sw = 0;
        Sg = 0;
        USI ncut = 10;
        for (USI k = 0; k < ncut; k++)
        {
            OCP_DBL tmpSw = 0;
            OCP_DBL tmpSg = 0;
            OCP_DBL dep = depth[n] + dz[n] / ncut * (k - (ncut - 1) / 2.0);
            DepthP.Eval_All(0, dep, data, cdata);
            Po = data[1];
            Pg = data[2];
            Pw = data[3];
            Pcow = Po - Pw;
            Pcgo = Pg - Po;
            tmpSw = flow[0]->GetSwByPcow(Pcow);
            if (gas)
            {
                tmpSg = flow[0]->GetSgByPcgo(Pcgo);
            }
            if (tmpSw + tmpSg > 1)
            {
                // should me modified
                OCP_DBL Pcgw = Pcow + Pcgo;
                tmpSw = flow[0]->GetSwByPcgw(Pcgw);
                tmpSg = 1 - tmpSw;
            }
            Sw += tmpSw;
            Sg += tmpSg;
        }
        Sw /= ncut;
        Sg /= ncut;
        S[n * numPhase + numPhase - 1] = Sw;
        if (gas) {
            S[n * numPhase + numPhase - 2] = Sg;
        }
    }
}
References OCPTable::Display(), OCPTable::Eval(), OCPTable::Eval_All(), OCPTable::GetCol(), OCPTable::IsEmpty(), OCP_ABORT, OCP_FUNCNAME, and TINY.
InitSjPcComp()
void Bulk::InitSjPcComp (const USI & tabrow, const Grid & myGrid)
Calculate initial equilibrium for compositional model according to EQUIL.
Here tabrow is maximum number of depth nodes in table of depth vs pressure.
Definition at line 897 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_DBL Dref = EQUIL.Dref;
    OCP_DBL Pref = EQUIL.Pref;
    OCP_DBL DOWC = EQUIL.DOWC;
    OCP_DBL PcOW = EQUIL.PcOW;
    OCP_DBL DOGC = EQUIL.DGOC;
    OCP_DBL PcGO = EQUIL.PcGO;
    OCP_DBL Zmin = 1E8;
    OCP_DBL Zmax = 0;
    OCP_DBL swco = flow[0]->GetSwco();
    OCP_DBL tmp;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        OCP_DBL temp1 = depth[n] - dz[n] / 2;
        OCP_DBL temp2 = depth[n] + dz[n] / 2;
        Zmin = Zmin < temp1 ? Zmin : temp1;
        Zmax = Zmax > temp2 ? Zmax : temp2;
    }
    OCP_DBL tabdz = (Zmax - Zmin) / (tabrow - 1);
    // creater table
    OCPTable DepthP(tabrow, 4);
    vector<OCP_DBL> &Ztmp = DepthP.GetCol(0);
    vector<OCP_DBL> &Potmp = DepthP.GetCol(1);
    vector<OCP_DBL> &Pwtmp = DepthP.GetCol(2);
    vector<OCP_DBL> &Pgtmp = DepthP.GetCol(3);
    // cal Tab_Ztmp
    Ztmp[0] = Zmin;
    for (USI i = 1; i < tabrow; i++)
    {
        Ztmp[i] = Ztmp[i - 1] + tabdz;
    }
    // find the RefId
    USI beginId = 0;
    if (Dref <= Ztmp[0])
    {
        beginId = 0;
    }
    else if (Dref >= Ztmp[tabrow - 1])
    {
        beginId = tabrow - 1;
    }
    else
    {
        beginId = distance(Ztmp.begin(), find_if(Ztmp.begin(), Ztmp.end(),
                                                 [s = Dref](auto& t)
                                                 { return t > s; }));
        beginId--;
    }
    // begin calculating oil pressure:
    OCP_DBL mytemp = T;
    OCP_DBL gammaOtmp, gammaWtmp, gammaGtmp;
    OCP_DBL Ptmp;
    USI mynum = 10;
    OCP_DBL mydz = 0;
    OCP_DBL Poref, Pgref, Pwref;
    OCP_DBL Pbegin = 0;
    if (Dref < DOGC)
    {
        // reference pressure is gas pressure
        Pgref = Pref;
        gammaGtmp = flashCal[0]->GammaPhaseOG(Pgref, mytemp, &initZi[0]);
        Pbegin = Pgref + gammaGtmp * (Ztmp[beginId] - Dref);
        Pgtmp[beginId] = Pbegin;
        // find the gas pressure
        for (USI id = beginId; id > 0; id--)
        {
            gammaGtmp = flashCal[0]->GammaPhaseOG(Pgtmp[id], mytemp, &initZi[0]);
            Pgtmp[id - 1] = Pgtmp[id] - gammaGtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaGtmp = flashCal[0]->GammaPhaseOG(Pgtmp[id], mytemp, &initZi[0]);
            Pgtmp[id + 1] = Pgtmp[id] + gammaGtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
        // find the oil pressure in Dref by Pgref
        Poref = 0;
        Ptmp = Pgref;
        mydz = (DOGC - Dref) / mynum;
        for (USI i = 0; i < mynum; i++)
        {
            gammaGtmp = flashCal[0]->GammaPhaseOG(Ptmp, mytemp, &initZi[0]);
            Ptmp += gammaGtmp * mydz;
        }
        Ptmp -= PcGO;
        for (USI i = 0; i < mynum; i++)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Ptmp, mytemp, &initZi[0]);
            Ptmp -= gammaOtmp * mydz;
        }
        Poref = Ptmp;
        // find the oil pressure in tab
        gammaOtmp = flashCal[0]->GammaPhaseOG(Poref, mytemp, &initZi[0]);
        Pbegin = Poref + gammaOtmp * (Ztmp[beginId] - Dref);
        Potmp[beginId] = Pbegin;
        for (USI id = beginId; id > 0; id--)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Potmp[id], mytemp, &initZi[0]);
            Potmp[id - 1] = Potmp[id] - gammaOtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Potmp[id], mytemp, &initZi[0]);
            Potmp[id + 1] = Potmp[id] + gammaOtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
        // find the water pressure in Dref by Poref
        Pwref = 0;
        Ptmp = Poref;
        mydz = (DOWC - Dref) / mynum;
        for (USI i = 0; i < mynum; i++)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Ptmp, mytemp, &initZi[0]);
            Ptmp += gammaOtmp * mydz;
        }
        Ptmp -= PcOW;
        for (USI i = 0; i < mynum; i++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Ptmp);
            Ptmp -= gammaWtmp * mydz;
        }
        Pwref = Ptmp;
        // find the water pressure in tab
        gammaWtmp = flashCal[0]->GammaPhaseW(Pwref);
        Pbegin = Pwref + gammaWtmp * (Ztmp[beginId] - Dref);
        Pwtmp[beginId] = Pbegin;
        for (USI id = beginId; id > 0; id--)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id - 1] = Pwtmp[id] - gammaWtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id + 1] = Pwtmp[id] + gammaWtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
    }
    else if (Dref > DOWC)
    {
        // reference pressure is water pressure
        Pwref = Pref;
        gammaWtmp = flashCal[0]->GammaPhaseW(Pwref);
        Pbegin = Pwref + gammaWtmp * (Ztmp[beginId] - Dref);
        Pwtmp[beginId] = Pbegin;
        // find the water pressure
        for (USI id = beginId; id > 0; id--)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id - 1] = Pwtmp[id] - gammaWtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id + 1] = Pwtmp[id] + gammaWtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
        // find the oil pressure in Dref by Pwref
        Poref = 0;
        Ptmp = Pwref;
        mydz = (DOWC - Dref) / mynum;
        for (USI i = 0; i < mynum; i++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Ptmp);
            Ptmp += gammaWtmp * mydz;
        }
        Ptmp += PcOW;
        for (USI i = 0; i < mynum; i++)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Ptmp, mytemp, &initZi[0]);
            Ptmp -= gammaOtmp * mydz;
        }
        Poref = Ptmp;
        // find the oil pressure in tab
        gammaOtmp = flashCal[0]->GammaPhaseOG(Poref, mytemp, &initZi[0]);
        Pbegin = Poref + gammaOtmp * (Ztmp[beginId] - Dref);
        Potmp[beginId] = Pbegin;
        for (USI id = beginId; id > 0; id--)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Potmp[id], mytemp, &initZi[0]);
            Potmp[id - 1] = Potmp[id] - gammaOtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Potmp[id], mytemp, &initZi[0]);
            Potmp[id + 1] = Potmp[id] + gammaOtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
        // find the gas pressure in Dref by Poref
        Pgref = 0;
        Ptmp = Poref;
        mydz = (DOGC - Dref) / mynum;
        for (USI i = 0; i < mynum; i++)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Ptmp, mytemp, &initZi[0]);
            Ptmp += gammaOtmp * mydz;
        }
        Ptmp += PcGO;
        for (USI i = 0; i < mynum; i++)
        {
            gammaGtmp = flashCal[0]->GammaPhaseOG(Ptmp, mytemp, &initZi[0]);
            Ptmp -= gammaGtmp * mydz;
        }
        Pgref = Ptmp;
        // find the gas pressure in tab
        gammaGtmp = flashCal[0]->GammaPhaseOG(Pgref, mytemp, &initZi[0]);
        Pbegin = Pgref + gammaGtmp * (Ztmp[beginId] - Dref);
        Pgtmp[beginId] = Pbegin;
        for (USI id = beginId; id > 0; id--)
        {
            gammaGtmp = flashCal[0]->GammaPhaseOG(Pgtmp[id], mytemp, &initZi[0]);
            Pgtmp[id - 1] = Pgtmp[id] - gammaGtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaGtmp = flashCal[0]->GammaPhaseOG(Pgtmp[id], mytemp, &initZi[0]);
            Pgtmp[id + 1] = Pgtmp[id] + gammaGtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
    }
    else
    {
        // reference pressure is oil pressure
        Poref = Pref;
        gammaOtmp = flashCal[0]->GammaPhaseOG(Poref, mytemp, &initZi[0]);
        Pbegin = Poref + gammaOtmp * (Ztmp[beginId] - Dref);
        Potmp[beginId] = Pbegin;
        // find the oil pressure
        for (USI id = beginId; id > 0; id--)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Potmp[id], mytemp, &initZi[0]);
            Potmp[id - 1] = Potmp[id] - gammaOtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Potmp[id], mytemp, &initZi[0]);
            Potmp[id + 1] = Potmp[id] + gammaOtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
        // find the gas pressure in Dref by Poref
        Pgref = 0;
        Ptmp = Poref;
        mydz = (DOGC - Dref) / mynum;
        for (USI i = 0; i < mynum; i++)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Ptmp, mytemp, &initZi[0]);
            Ptmp += gammaOtmp * mydz;
        }
        Ptmp += PcGO;
        for (USI i = 0; i < mynum; i++)
        {
            gammaGtmp = flashCal[0]->GammaPhaseOG(Ptmp, mytemp, &initZi[0]);
            Ptmp -= gammaGtmp * mydz;
        }
        Pgref = Ptmp;
        // find the gas pressure in tab
        gammaGtmp = flashCal[0]->GammaPhaseOG(Pgref, mytemp, &initZi[0]);
        Pbegin = Pgref + gammaGtmp * (Ztmp[beginId] - Dref);
        Pgtmp[beginId] = Pbegin;
        for (USI id = beginId; id > 0; id--)
        {
            gammaGtmp = flashCal[0]->GammaPhaseOG(Pgtmp[id], mytemp, &initZi[0]);
            Pgtmp[id - 1] = Pgtmp[id] - gammaGtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaGtmp = flashCal[0]->GammaPhaseOG(Pgtmp[id], mytemp, &initZi[0]);
            Pgtmp[id + 1] = Pgtmp[id] + gammaGtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
        // find the water pressure in Dref by Poref
        Pwref = 0;
        Ptmp = Poref;
        mydz = (DOWC - Dref) / mynum;
        for (USI i = 0; i < mynum; i++)
        {
            gammaOtmp = flashCal[0]->GammaPhaseOG(Ptmp, mytemp, &initZi[0]);
            Ptmp += gammaOtmp * mydz;
        }
        Ptmp -= PcOW;
        for (USI i = 0; i < mynum; i++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Ptmp);
            Ptmp -= gammaWtmp * mydz;
        }
        Pwref = Ptmp;
        // find the water pressure in tab
        gammaWtmp = flashCal[0]->GammaPhaseW(Pwref);
        Pbegin = Pwref + gammaWtmp * (Ztmp[beginId] - Dref);
        Pwtmp[beginId] = Pbegin;
        for (USI id = beginId; id > 0; id--)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id - 1] = Pwtmp[id] - gammaWtmp * (Ztmp[id] - Ztmp[id - 1]);
        }
        for (USI id = beginId; id < tabrow - 1; id++)
        {
            gammaWtmp = flashCal[0]->GammaPhaseW(Pwtmp[id]);
            Pwtmp[id + 1] = Pwtmp[id] + gammaWtmp * (Ztmp[id + 1] - Ztmp[id]);
        }
    }
    cout << "Depth    "
         << "Poil    "
         << "Pwat    "
         << "Pgas" << endl;
    DepthP.Display();
    // calculate Pc from DepthP to calculate Sj
    std::vector<OCP_DBL> data(4, 0), cdata(4, 0);
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        DepthP.Eval_All(0, depth[n], data, cdata);
        OCP_DBL Po = data[1];
        OCP_DBL Pw = data[2];
        OCP_DBL Pg = data[3];
        OCP_DBL Pcgo = Pg - Po;
        OCP_DBL Pcow = Po - Pw;
        OCP_DBL Sw = flow[0]->GetSwByPcow(Pcow);
        OCP_DBL Sg = 0;
        if (gas)
        {
            Sg = flow[0]->GetSgByPcgo(Pcgo);
        }
        if (Sw + Sg > 1)
        {
            // should me modified
            OCP_DBL Pcgw = Pcow + Pcgo;
            Sw = flow[0]->GetSwByPcgw(Pcgw);
            Sg = 1 - Sw;
        }
        if (1 - Sw < TINY)
        {
            // all water
            Po = Pw + flow[0]->GetPcowBySw(1.0);
        }
        else if (1 - Sg < TINY)
        {
            // all gas
            Po = Pg - flow[0]->GetPcgoBySg(1.0);
        }
        else if (1 - Sw - Sg < TINY)
        {
            // water and gas
            Po = Pg - flow[0]->GetPcgoBySg(Sg);
        }
        P[n] = Po;
        // cal Sg and Sw
        Sw = 0;
        Sg = 0;
        USI ncut = 10;
        OCP_DBL avePcow = 0;
        for (USI k = 0; k < ncut; k++)
        {
            OCP_DBL tmpSw = 0;
            OCP_DBL tmpSg = 0;
            OCP_DBL dep = depth[n] + dz[n] / ncut * (k - (ncut - 1) / 2.0);
            DepthP.Eval_All(0, dep, data, cdata);
            Po = data[1];
            Pw = data[2];
            Pg = data[3];
            Pcow = Po - Pw;
            Pcgo = Pg - Po;
            avePcow += Pcow;
            tmpSw = flow[0]->GetSwByPcow(Pcow);
            if (gas)
            {
                tmpSg = flow[0]->GetSgByPcgo(Pcgo);
            }
            if (tmpSw + tmpSg > 1)
            {
                // should me modified
                OCP_DBL Pcgw = Pcow + Pcgo;
                tmpSw = flow[0]->GetSwByPcgw(Pcgw);
                tmpSg = 1 - tmpSw;
            }
            Sw += tmpSw;
            Sg += tmpSg;
        }
        Sw /= ncut;
        Sg /= ncut;
        avePcow /= ncut;
        if (SwatInitExist) {
            if (ScalePcow) {
                ScaleValuePcow[n] = 1.0;
            }
            if (SwatInit[n] <= swco) {
                Sw = swco;
            }
            else {
                Sw = SwatInit[n];
                if (ScalePcow) {
                    if (avePcow > 0) {
                        tmp = flow[0]->GetPcowBySw(Sw);
                        if (tmp > 0) {
                            ScaleValuePcow[n] = avePcow / tmp;
                            /*USI I, J, K;
                            myGrid.GetIJKGrid(I, J, K, myGrid.activeMap_B2G[n]);
                            cout << I << "   " << J << "   " << K << "   "
                                << fixed << setprecision(3) << "   " << ScaleValuePcow[n] * flow[0]->GetPcowBySw(0) << endl;*/
                        }
                    }
                }
            }
        }
        S[n * numPhase + numPhase - 1] = Sw;
        if (gas)
        {
            S[n * numPhase + numPhase - 2] = Sg;
        }
    }
}
References OCPTable::Display(), OCPTable::Eval_All(), OCPTable::GetCol(), OCP_FUNCNAME, and TINY.
InputParam()
void Bulk::InputParam (ParamReservoir & rs_param)
Input param from internal data structure ParamReservoir.
Read parameters from rs_param data strucutre.
Definition at line 23 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    rockPref = rs_param.rock.Pref;
    rockC1 = rs_param.rock.Cr;
    rockC2 = rockC1;
    T = rs_param.rsTemp + 460;
    ScalePcow = rs_param.ScalePcow;
    blackOil = rs_param.blackOil;
    comps = rs_param.comps;
    oil = rs_param.oil;
    gas = rs_param.gas;
    water = rs_param.water;
    disGas = rs_param.disGas;
    miscible = rs_param.EoSp.miscible;
    EQUIL.Dref = rs_param.EQUIL[0];
    EQUIL.Pref = rs_param.EQUIL[1];
    if (rs_param.PBVD_T.data.size() > 0)
        EQUIL.PBVD.Setup(rs_param.PBVD_T.data[0]);
    if (blackOil)
    {
        if (water && !oil && !gas)
        {
            // water
            numPhase = 1;
            numCom = 1;
            SATmode = PHASE_W;
            PVTmode = PHASE_W;
        }
        else if (water && oil && !gas)
        {
            // water, dead oil
            numPhase = 2;
            numCom = 2;
            EQUIL.DOWC = rs_param.EQUIL[2];
            EQUIL.PcOW = rs_param.EQUIL[3];
            SATmode = PHASE_OW;
            PVTmode = PHASE_OW;
        }
        else if (water && oil && gas && !disGas)
        {
            // water, dead oil, dry gas
            numPhase = 3;
            numCom = 3;
            EQUIL.DOWC = rs_param.EQUIL[2];
            EQUIL.PcOW = rs_param.EQUIL[3];
            EQUIL.DGOC = rs_param.EQUIL[4];
            EQUIL.PcGO = rs_param.EQUIL[5];
            SATmode = PHASE_DOGW;
            PVTmode = PHASE_DOGW; // maybe it should be added later
        }
        else if (water && oil && gas && disGas)
        {
            // water, live oil, dry gas
            numPhase = 3;
            numCom = 3;
            EQUIL.DOWC = rs_param.EQUIL[2];
            EQUIL.PcOW = rs_param.EQUIL[3];
            EQUIL.DGOC = rs_param.EQUIL[4];
            EQUIL.PcGO = rs_param.EQUIL[5];
            PVTmode = PHASE_ODGW;
            if (rs_param.SOF3_T.data.size() > 0)
            {
                SATmode = PHASE_ODGW02;
            }
            else
            {
                SATmode = PHASE_ODGW01;
            }
        }
        numCom_1 = numCom - 1;
        rs_param.numPhase = numPhase;
        rs_param.numCom = numCom;
        switch (PVTmode)
        {
        case PHASE_W:
            OCP_ABORT("Wrong Type!");
            break;
        case PHASE_OW:
            for (USI i = 0; i < rs_param.NTPVT; i++)
                flashCal.push_back(new BOMixture_OW(rs_param, i));
            break;
        case PHASE_DOGW:
            OCP_ABORT("Wrong Type!");
            break;
        case PHASE_ODGW:
            for (USI i = 0; i < rs_param.NTPVT; i++)
                flashCal.push_back(new BOMixture_ODGW(rs_param, i));
            break;
        default:
            OCP_ABORT("Wrong Type!");
            break;
        }
        cout << "Bulk::InputParam --- BLACKOIL" << endl;
    }
    else if (comps)
    {
        // Water exists and is excluded in EoS model NOW!
        oil = true;
        gas = true;
        water = true;
        initZi = rs_param.EoSp.zi; // Easy initialization!
        initZi.push_back(0.0); // include water
        numPhase = rs_param.EoSp.numPhase + 1;
        numCom = rs_param.EoSp.numComp + 1;
        numCom_1 = numCom - 1;
        EQUIL.DOWC = rs_param.EQUIL[2];
        EQUIL.PcOW = rs_param.EQUIL[3];
        EQUIL.DGOC = rs_param.EQUIL[4];
        EQUIL.PcGO = rs_param.EQUIL[5];
        if (rs_param.SOF3_T.data.size() > 0)
        {
            SATmode = PHASE_ODGW02;
        }
        else
        {
            SATmode = PHASE_ODGW01;
        }
        for (USI i = 0; i < rs_param.NTPVT; i++)
            flashCal.push_back(new MixtureComp(rs_param, i));
        cout << "Bulk::InputParam --- COMPOSITIONAL" << endl;
    }
    if (SATmode == PHASE_ODGW01 && miscible) {
        SATmode = PHASE_ODGW01_MISCIBLE;
    }
    satcm.resize(rs_param.NTSFUN);
    switch (SATmode)
    {
    case PHASE_W:
        for (USI i = 0; i < rs_param.NTSFUN; i++)
            flow.push_back(new FlowUnit_W(rs_param, i));
        break;
    case PHASE_OW:
        for (USI i = 0; i < rs_param.NTSFUN; i++)
            flow.push_back(new FlowUnit_OW(rs_param, i));
        break;
    case PHASE_ODGW01:
        for (USI i = 0; i < rs_param.NTSFUN; i++) {
            flow.push_back(new FlowUnit_ODGW01(rs_param, i));
            satcm[i] = flow[i]->GetScm();
        }
        break;
    case PHASE_ODGW01_MISCIBLE:
        for (USI i = 0; i < rs_param.NTSFUN; i++) {
            flow.push_back(new FlowUnit_ODGW01_Miscible(rs_param, i));
            satcm[i] = flow[i]->GetScm();
        }
        break;
    case PHASE_ODGW02:
        for (USI i = 0; i < rs_param.NTSFUN; i++)
            flow.push_back(new FlowUnit_ODGW02(rs_param, i));
        break;
    default:
        OCP_ABORT("Wrong Type!");
        break;
    }
}
References ParamReservoir::blackOil, ParamReservoir::comps, Rock::Cr, TableSet::data, ParamReservoir::disGas, ParamReservoir::EoSp, ParamReservoir::EQUIL, ParamReservoir::gas, EoSparam::miscible, ParamReservoir::NTPVT, ParamReservoir::NTSFUN, ParamReservoir::numCom, EoSparam::numComp, EoSparam::numPhase, ParamReservoir::numPhase, OCP_ABORT, OCP_FUNCNAME, ParamReservoir::oil, ParamReservoir::PBVD_T, PHASE_DOGW, PHASE_ODGW, PHASE_ODGW01, PHASE_ODGW01_MISCIBLE, PHASE_ODGW02, PHASE_OW, PHASE_W, Rock::Pref, ParamReservoir::rock, ParamReservoir::rsTemp, ParamReservoir::ScalePcow, OCPTable::Setup(), ParamReservoir::SOF3_T, ParamReservoir::water, and EoSparam::zi.
OutFIMNi()
void Bulk::OutFIMNi ()
FIMNi -> Ni in FIM Bulk.
Definition at line 3935 of file Bulk.cpp.
{
    OCP_USI bIdb, bIdf;
    for (OCP_USI n = 0; n < numFIMBulk; n++) {
        bIdf = n * numCom;
        bIdb = FIMBulk[n] * numCom;
        for (USI i = 0; i < numCom; i++) {
            Ni[bIdb + i] = FIMNi[bIdf + i];
        }
    }
}
OutputInfo()
void Bulk::OutputInfo (const OCP_USI & n) const
Definition at line 3336 of file Bulk.cpp.
{
    OCP_USI bIdC = n * numCom;
    OCP_USI bIdP = n * numPhase;
    OCP_USI bIdPC = bIdP * numCom;
    cout << "------------------------------" << endl;
    cout << "Bulk[" << n << "]" << endl;
    cout << fixed << setprecision(3);
    for (USI i = 0; i < numCom; i++)
    {
        cout << Ni[bIdC + i] << "   ";
    }
    cout << endl
         << P[n] << "   " << T;
    cout << endl;
    cout << fixed << setprecision(8);
    if (phaseExist[bIdP + 0])
    {
        for (USI i = 0; i < numCom; i++)
        {
            cout << xij[bIdPC + i] << "   ";
        }
    }
    else
    {
        for (USI i = 0; i < numCom; i++)
        {
            cout << 0.000000 << "   ";
        }
    }
    cout << phaseExist[bIdP + 0] << "   ";
    cout << xi[bIdP + 0] << "   ";
    cout << S[bIdP + 0] << "   ";
    cout << endl;
    if (phaseExist[bIdP + 1])
    {
        for (USI i = 0; i < numCom; i++)
        {
            cout << xij[bIdPC + numCom + i] << "   ";
        }
    }
    else
    {
        for (USI i = 0; i < numCom; i++)
        {
            cout << 0.000000 << "   ";
        }
    }
    cout << phaseExist[bIdP + 1] << "   ";
    cout << xi[bIdP + 1] << "   ";
    cout << S[bIdP + 1] << "   ";
    cout << endl;
    cout << fixed << setprecision(3);
    cout << vf[n] << "   " << rockVp[n] << "   ";
    cout << fixed << setprecision(12);
    cout << fabs(vf[n] - rockVp[n]) / rockVp[n] << endl;
    cout << fixed << setprecision(3);
    cout << vj[bIdP] << "   " << vj[bIdP + 1] << "   " << vj[bIdP + 2] << endl;
    cout << "------------------------------" << endl;
}
PassFlashValue()
void Bulk::PassFlashValue (const OCP_USI & n)
Pass values from Flash to Bulk after Flash calculation.
Definition at line 1631 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_USI bIdp = n * numPhase;
    USI pvtnum = PVTNUM[n];
    USI nptmp = 0;
    for (USI j = 0; j < numPhase; j++)
    {
        phaseExist[bIdp + j] = flashCal[pvtnum]->phaseExist[j];
        // Important! Saturation must be passed no matter if the phase exists. This is
        // because it will be used to calculate relative permeability and capillary
        // pressure at each time step. Make sure that all saturations are updated at
        // each step!
        S[bIdp + j] = flashCal[pvtnum]->S[j];
        if (phaseExist[bIdp + j])
        { // j -> bId + j   fix bugs.
            totalPhaseNum[j]++;
            nptmp++;
            rho[bIdp + j] = flashCal[pvtnum]->rho[j];
            xi[bIdp + j] = flashCal[pvtnum]->xi[j];
            for (USI i = 0; i < numCom; i++)
            {
                xij[bIdp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->xij[j * numCom + i];
            }
            mu[bIdp + j] = flashCal[pvtnum]->mu[j];
            vj[bIdp + j] = flashCal[pvtnum]->v[j];
        }
    }
    Nt[n] = flashCal[pvtnum]->Nt;
    vf[n] = flashCal[pvtnum]->vf;
    vfp[n] = flashCal[pvtnum]->vfp;
    OCP_USI bIdc = n * numCom;
    for (USI i = 0; i < numCom; i++)
    {
        vfi[bIdc + i] = flashCal[pvtnum]->vfi[i];
    }
    phaseNum[n] = nptmp - 1; // water is excluded
    if (comps)
    {
        if (nptmp == 3)
        {
            // num of hydrocarbon phase equals 2
            // Calculate Ks
            OCP_USI bIdc1 = n * numCom_1;
            for (USI i = 0; i < numCom_1; i++)
            {
                Ks[bIdc1 + i] = flashCal[pvtnum]->xij[i] / flashCal[pvtnum]->xij[numCom + i];
            }
        }
        if (flashCal[pvtnum]->GetFtype() == 0)
        {
            flagSkip[n] = flashCal[pvtnum]->GetFlagSkip();
            if (flagSkip[n])
            {
                minEigenSkip[n] = flashCal[pvtnum]->GetMinEigenSkip();
                for (USI j = 0; j < numPhase - 1; j++)
                {
                    if (phaseExist[bIdp + j])
                    {
                        for (USI i = 0; i < numCom - 1; i++)
{
                            ziSkip[bIdc + i] = flashCal[pvtnum]->xij[j * numCom + i];
                        }
                        break;
                    }
                }
                PSkip[n] = P[n];
            }
        }
        if (miscible) {
            surTen[n] = flashCal[pvtnum]->GetSurTen();
        }
    }
}
References OCP_FUNCNAME.
PassFlashValueAIMc()
void Bulk::PassFlashValueAIMc (const OCP_USI & n)
Definition at line 1711 of file Bulk.cpp.
{
    // only var about volume needs, some flash var also
    OCP_FUNCNAME;
    OCP_USI bIdp = n * numPhase;
    USI pvtnum = PVTNUM[n];
    Nt[n] = flashCal[pvtnum]->Nt;
    vf[n] = flashCal[pvtnum]->vf;
    vfp[n] = flashCal[pvtnum]->vfp;
    OCP_USI bIdc = n * numCom;
    for (USI i = 0; i < numCom; i++)
    {
        vfi[bIdc + i] = flashCal[pvtnum]->vfi[i];
    }
    USI nptmp = 0;
    for (USI j = 0; j < numPhase; j++) {
        if (flashCal[pvtnum]->phaseExist[j]) {
            nptmp++;
        }
    }
    phaseNum[n] = nptmp - 1; // water is excluded
    if (comps)
    {
        if (nptmp == 3)
        {
            // num of hydrocarbon phase equals 2
            // Calculate Ks
            OCP_USI bIdc1 = n * numCom_1;
            for (USI i = 0; i < numCom_1; i++)
            {
                Ks[bIdc1 + i] = flashCal[pvtnum]->xij[i] / flashCal[pvtnum]->xij[numCom + i];
            }
        }
        if (flashCal[pvtnum]->GetFtype() == 0)
        {
            flagSkip[n] = flashCal[pvtnum]->GetFlagSkip();
            if (flagSkip[n])
            {
                minEigenSkip[n] = flashCal[pvtnum]->GetMinEigenSkip();
                for (USI j = 0; j < numPhase - 1; j++)
                {
                    if (phaseExist[bIdp + j])
                    {
                        for (USI i = 0; i < numCom - 1; i++)
{
                            ziSkip[bIdc + i] = flashCal[pvtnum]->xij[j * numCom + i];
                        }
                        break;
                    }
                }
                PSkip[n] = P[n];
            }
        }
        if (miscible) {
            surTen[n] = flashCal[pvtnum]->GetSurTen();
        }
    }
}
PassFlashValueDeriv()
void Bulk::PassFlashValueDeriv (const OCP_USI & n)
Pass derivative values from Flash to Bulk after Flash calculation.
Definition at line 1778 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_USI bIdp = n * numPhase;
    USI pvtnum = PVTNUM[n];
    USI nptmp = 0;
    USI len = 0;
    for (USI j = 0; j < numPhase; j++)
    {
        // Important! Saturation must be passed no matter if the phase exists. This is
        // because it will be used to calculate relative permeability and capillary
        // pressure at each time step. Make sure that all saturations are updated at
        // each step!
        S[bIdp + j] = flashCal[pvtnum]->S[j];
        dSNR[bIdp + j] = S[bIdp + j] - dSNR[bIdp + j];
        if (phaseExist[bIdp + j]) {
            NRdSSP += (dSNR[bIdp + j] - dSNRP[bIdp + j]) * (dSNR[bIdp + j] - dSNRP[bIdp + j]);
            if (fabs(maxNRdSSP) < fabs(dSNR[bIdp + j] - dSNRP[bIdp + j])) {
                maxNRdSSP = dSNR[bIdp + j] - dSNRP[bIdp + j];
                index_maxNRdSSP = n;
            }
            // cout << n << "   " << scientific << setprecision(6) << dSNR[bIdp + j] << "   " << dSNRP[bIdp + j] << endl;
        }
        phaseExist[bIdp + j] = flashCal[pvtnum]->phaseExist[j];
        pEnumCom[bIdp + j] = flashCal[pvtnum]->pEnumCom[j];
        len += pEnumCom[bIdp + j];
        if (phaseExist[bIdp + j])
        { // j -> bId + j fix bugs.
            totalPhaseNum[j]++;
            nptmp++;
            nj[bIdp + j] = flashCal[pvtnum]->nj[j];
            rho[bIdp + j] = flashCal[pvtnum]->rho[j];
            xi[bIdp + j] = flashCal[pvtnum]->xi[j];
            mu[bIdp + j] = flashCal[pvtnum]->mu[j];
            vj[bIdp + j] = flashCal[pvtnum]->v[j];
            // Derivatives
            muP[bIdp + j] = flashCal[pvtnum]->muP[j];
            xiP[bIdp + j] = flashCal[pvtnum]->xiP[j];
            rhoP[bIdp + j] = flashCal[pvtnum]->rhoP[j];
            for (USI i = 0; i < numCom; i++)
            {
                xij[bIdp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->xij[j * numCom + i];
                mux[bIdp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->mux[j * numCom + i];
                xix[bIdp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->xix[j * numCom + i];
                rhox[bIdp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->rhox[j * numCom + i];
            }
        }
    }
    Nt[n] = flashCal[pvtnum]->Nt;
    vf[n] = flashCal[pvtnum]->vf;
    vfp[n] = flashCal[pvtnum]->vfp;
    OCP_USI bIdc = n * numCom;
    for (USI i = 0; i < numCom; i++)
    {
        vfi[bIdc + i] = flashCal[pvtnum]->vfi[i];
    }
    len += nptmp;
#ifdef OCP_NEW_FIM_n
    resIndex[n + 1] = resIndex[n] + len;
    Dcopy(len, &res_n[0] + resIndex[n], &flashCal[pvtnum]->res[0]);
    len *= (numCom + 1);
    dSdPindex[n + 1] = dSdPindex[n] + len;
    Dcopy(len, &dSec_dPri[0] + dSdPindex[n], &flashCal[pvtnum]->dXsdXp[0]);
#else
#ifdef OCP_NEW_FIM
    len *= (numCom + 1);
    dSdPindex[n + 1] = dSdPindex[n] + len;
    Dcopy(len, &dSec_dPri[0] + dSdPindex[n], &flashCal[pvtnum]->dXsdXp[0]);
#else
    Dcopy(lendSdP, &dSec_dPri[0] + n * lendSdP, &flashCal[pvtnum]->dXsdXp[0]);
#endif // OCP_NEW_FIM
#endif // OCP_NEW_FIM_n
    // test
    phaseNum[n] = nptmp - 1; // So water must exist!!!
    if (comps)
    {
        ePEC[n] = flashCal[pvtnum]->GetErrorPEC();
        if (nptmp == 3)
        {
            // num of hydrocarbon phase equals 2
            // Calculate Ks
            // IMPORTANT!!!
            // Ks will change as long as nums of hydroncarbon phase equals 2, and it will has an effect
            // on phase spliting calculation as a intial value. So you should not expect to obtain
            // the exact same result with identical P, T, Ni if the final mixture contains 2 hydroncarbon phase.
            OCP_USI bIdc1 = n * numCom_1;
            for (USI i = 0; i < numCom_1; i++) {
                Ks[bIdc1 + i] = flashCal[pvtnum]->xij[i] / flashCal[pvtnum]->xij[numCom + i];
            }
        }
        if (flashCal[pvtnum]->GetFtype() == 0)
        {
            flagSkip[n] = flashCal[pvtnum]->GetFlagSkip();
            if (flagSkip[n])
            {
                minEigenSkip[n] = flashCal[pvtnum]->GetMinEigenSkip();
                for (USI j = 0; j < numPhase - 1; j++)
                {
                    if (phaseExist[bIdp + j])
                    {
                        for (USI i = 0; i < numCom - 1; i++)
{
                            ziSkip[bIdc + i] = flashCal[pvtnum]->xij[j * numCom + i];
                        }
                        break;
                    }
                }
                PSkip[n] = P[n];
            }
        }
        if (miscible) {
            surTen[n] = flashCal[pvtnum]->GetSurTen();
        }
    }
}
References Dcopy(), and OCP_FUNCNAME.
PassFlashValueDeriv_n()
void Bulk::PassFlashValueDeriv_n (const OCP_USI & n)
Definition at line 1912 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_USI bIdp = n * numPhase;
    USI pvtnum = PVTNUM[n];
    USI nptmp = 0;
    USI len = 0;
    for (USI j = 0; j < numPhase; j++)
    {
        // Important! Saturation must be passed no matter if the phase exists. This is
        // because it will be used to calculate relative permeability and capillary
        // pressure at each time step. Make sure that all saturations are updated at
        // each step!
        S[bIdp + j] = flashCal[pvtnum]->S[j];
        dSNR[bIdp + j] = S[bIdp + j] - dSNR[bIdp + j];
        if (phaseExist[bIdp + j]) {
            NRdSSP += (dSNR[bIdp + j] - dSNRP[bIdp + j]) * (dSNR[bIdp + j] - dSNRP[bIdp + j]);
            if (fabs(maxNRdSSP) < fabs(dSNR[bIdp + j] - dSNRP[bIdp + j])) {
                maxNRdSSP = dSNR[bIdp + j] - dSNRP[bIdp + j];
                index_maxNRdSSP = n;
            }
        }
        phaseExist[bIdp + j] = flashCal[pvtnum]->phaseExist[j];
        pEnumCom[bIdp + j] = flashCal[pvtnum]->pEnumCom[j];
        len += pEnumCom[bIdp + j];
        if (phaseExist[bIdp + j])
        { // j -> bId + j fix bugs.
            totalPhaseNum[j]++;
            nptmp++;
            nj[bIdp + j] = flashCal[pvtnum]->nj[j];
            rho[bIdp + j] = flashCal[pvtnum]->rho[j];
            xi[bIdp + j] = flashCal[pvtnum]->xi[j];
            mu[bIdp + j] = flashCal[pvtnum]->mu[j];
            vj[bIdp + j] = flashCal[pvtnum]->v[j];
            // Derivatives
            muP[bIdp + j] = flashCal[pvtnum]->muP[j];
            xiP[bIdp + j] = flashCal[pvtnum]->xiP[j];
            rhoP[bIdp + j] = flashCal[pvtnum]->rhoP[j];
            for (USI i = 0; i < numCom; i++)
            {
                xij[bIdp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->xij[j * numCom + i];
                mux[bIdp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->mux[j * numCom + i];
                xix[bIdp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->xix[j * numCom + i];
                rhox[bIdp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->rhox[j * numCom + i];
            }
        }
    }
    Nt[n] = flashCal[pvtnum]->Nt;
    vf[n] = flashCal[pvtnum]->vf;
    vfp[n] = flashCal[pvtnum]->vfp;
    OCP_USI bIdc = n * numCom;
    for (USI i = 0; i < numCom; i++)
    {
        vfi[bIdc + i] = flashCal[pvtnum]->vfi[i];
    }
    len += nptmp;
    resIndex[n + 1] = resIndex[n] + len;
    Dcopy(len, &res_n[0] + resIndex[n], &flashCal[pvtnum]->res[0]);
    len *= (numCom + 1);
    dSdPindex[n + 1] = dSdPindex[n] + len;
    Dcopy(len, &dSec_dPri[0] + dSdPindex[n], &flashCal[pvtnum]->dXsdXp[0]);
    resPc[n] = flashCal[pvtnum]->resPc;
    // test
    phaseNum[n] = nptmp - 1; // So water must exist!!!
    if (comps)
    {
        ePEC[n] = flashCal[pvtnum]->GetErrorPEC();
        if (nptmp == 3)
        {
            // num of hydrocarbon phase equals 2
            // Calculate Ks
            // IMPORTANT!!!
            // Ks will change as long as nums of hydroncarbon phase equals 2, and it will has an effect
            // on phase spliting calculation as a intial value. So you should not expect to obtain
            // the exact same result with identical P, T, Ni if the final mixture contains 2 hydroncarbon phase.
            OCP_USI bIdc1 = n * numCom_1;
            for (USI i = 0; i < numCom_1; i++) {
                Ks[bIdc1 + i] = flashCal[pvtnum]->xij[i] / flashCal[pvtnum]->xij[numCom + i];
            }
        }
        if (flashCal[pvtnum]->GetFtype() == 0)
        {
            flagSkip[n] = flashCal[pvtnum]->GetFlagSkip();
            if (flagSkip[n])
            {
                minEigenSkip[n] = flashCal[pvtnum]->GetMinEigenSkip();
                for (USI j = 0; j < numPhase - 1; j++)
                {
                    if (phaseExist[bIdp + j])
                    {
                        for (USI i = 0; i < numCom - 1; i++)
{
                            ziSkip[bIdc + i] = flashCal[pvtnum]->xij[j * numCom + i];
                        }
                        break;
                    }
                }
                PSkip[n] = P[n];
            }
        }
        if (miscible) {
            surTen[n] = flashCal[pvtnum]->GetSurTen();
        }
    }
}
PassFlashValueDerivAIM()
void Bulk::PassFlashValueDerivAIM (const OCP_USI & n)
Definition at line 3499 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    OCP_USI n = FIMBulk[fn];
    OCP_USI bIdp = n * numPhase;
    OCP_USI fnp = fn * numPhase;
    USI pvtnum = PVTNUM[n];
    USI nptmp = 0;
    for (USI j = 0; j < numPhase; j++)
    {
        phaseExist[bIdp + j] = flashCal[pvtnum]->phaseExist[j];
        // Important! Saturation must be passed no matter if the phase exists. This is
        // because it will be used to calculate relative permeability and capillary
        // pressure at each time step. Make sure that all saturations are updated at
        // each step!
        S[bIdp + j] = flashCal[pvtnum]->S[j];
        if (phaseExist[bIdp + j])
        { // j -> bId + j fix bugs.
            nptmp++;
            rho[bIdp + j] = flashCal[pvtnum]->rho[j];
            xi[bIdp + j] = flashCal[pvtnum]->xi[j];
            mu[bIdp + j] = flashCal[pvtnum]->mu[j];
            vj[bIdp + j] = flashCal[pvtnum]->v[j];
            // Derivatives
            muP[fnp + j] = flashCal[pvtnum]->muP[j];
            xiP[fnp + j] = flashCal[pvtnum]->xiP[j];
            rhoP[fnp + j] = flashCal[pvtnum]->rhoP[j];
            for (USI i = 0; i < numCom; i++)
            {
                xij[bIdp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->xij[j * numCom + i];
                mux[fnp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->mux[j * numCom + i];
                xix[fnp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->xix[j * numCom + i];
                rhox[fnp * numCom + j * numCom + i] =
                    flashCal[pvtnum]->rhox[j * numCom + i];
            }
        }
    }
    Nt[n] = flashCal[pvtnum]->Nt;
    vf[n] = flashCal[pvtnum]->vf;
    vfp[n] = flashCal[pvtnum]->vfp;
    OCP_USI bIdc = n * numCom;
    for (USI i = 0; i < numCom; i++)
    {
        vfi[bIdc + i] = flashCal[pvtnum]->vfi[i];
    }
    dSec_dPri.insert(dSec_dPri.end(), flashCal[pvtnum]->dXsdXp.begin(),
        flashCal[pvtnum]->dXsdXp.end());
    phaseNum[n] = nptmp - 1; // water is excluded
    if (comps)
    {
        if (nptmp == 3)
        {
            // num of hydrocarbon phase equals 2
            // Calculate Ks
            OCP_USI bIdc1 = n * numCom_1;
            for (USI i = 0; i < numCom_1; i++)
            {
                Ks[bIdc1 + i] = flashCal[pvtnum]->xij[i] / flashCal[pvtnum]->xij[numCom + i];
            }
        }
        if (flashCal[pvtnum]->GetFtype() == 0)
        {
            flagSkip[n] = flashCal[pvtnum]->GetFlagSkip();
            if (flagSkip[n])
            {
                minEigenSkip[n] = flashCal[pvtnum]->GetMinEigenSkip();
                for (USI j = 0; j < numPhase - 1; j++)
                {
                    if (phaseExist[bIdp + j])
                    {
                        for (USI i = 0; i < numCom - 1; i++)
{
                            ziSkip[bIdc + i] = flashCal[pvtnum]->xij[j * numCom + i];
                        }
                        break;
                    }
                }
                PSkip[n] = P[n];
            }
        }
        if (miscible) {
            surTen[n] = flashCal[pvtnum]->GetSurTen();
        }
    }
}
ResetFIM()
void Bulk::ResetFIM ()
Reset FIM.
Definition at line 3193 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    phaseNum = lphaseNum;
    minEigenSkip = lminEigenSkip;
    flagSkip = lflagSkip;
    ziSkip = lziSkip;
    PSkip = lPSkip;
    Ks = lKs;
    P = lP;
    Pj = lPj;
    Pc = lPc;
    phaseExist = lphaseExist;
    S = lS;
    nj = lnj;
    rho = lrho;
    xi = lxi;
    xij = lxij;
    Ni = lNi;
    mu = lmu;
    kr = lkr;
    vj = lvj;
    vf = lvf;
    Nt = lNt;
    vfi = lvfi;
    vfp = lvfp;
    rockVp = lrockVp;
    muP = lmuP;
    xiP = lxiP;
    rhoP = lrhoP;
    mux = lmux;
    xix = lxix;
    rhox = lrhox;
    dSec_dPri = ldSec_dPri;
    res_n = lres_n;
    resPc = lresPc;
    dSdPindex = ldSdPindex;
    resIndex = lresIndex;
    pEnumCom = lpEnumCom;
    dKr_dS = ldKr_dS;
    dPcj_dS = ldPcj_dS;
    if (miscible) {
        surTen = lsurTen;
    }
}
References OCP_FUNCNAME.
ResetFIMBulk()
void Bulk::ResetFIMBulk ()
Definition at line 3861 of file Bulk.cpp.
{
    muP = lmuP;
    xiP = lxiP;
    rhoP = lrhoP;
    mux = lmux;
    xix = lxix;
    rhox = lrhox;
    dPcj_dS = ldPcj_dS;
    dKr_dS = ldKr_dS;
    dSec_dPri = ldSec_dPri;
}
ResetflagSkip()
void Bulk::ResetflagSkip () inline
Definition at line 180 of file Bulk.hpp.
{ flagSkip = lflagSkip; }
ResetFlash()
void Bulk::ResetFlash ()
Reset variables in flash calculations.
Definition at line 2034 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    phaseExist = lphaseExist;
    S = lS;
    rho = lrho;
    xi = lxi;
    xij = lxij;
    mu = lmu;
    vj = lvj;
    vf = lvf;
    vfp = lvfp;
    vfi = lvfi;
}
References OCP_FUNCNAME.
ResetKr()
void Bulk::ResetKr () inline
Reset Kr to the ones of the last time step.
Definition at line 198 of file Bulk.hpp.
{ kr = lkr; }
ResetKs()
void Bulk::ResetKs () inline
Definition at line 186 of file Bulk.hpp.
{ Ks = lKs; }
ResetminEigenSkip()
void Bulk::ResetminEigenSkip () inline
Definition at line 178 of file Bulk.hpp.
{ minEigenSkip = lminEigenSkip; }
ResetNi()
void Bulk::ResetNi () inline
Reset Ni to the ones of the last time step.
Definition at line 196 of file Bulk.hpp.
{ Ni = lNi; }
ResetNt()
void Bulk::ResetNt () inline
Reset Nt to the ones of the last time step.
Definition at line 189 of file Bulk.hpp.
{ Nt = lNt; }
ResetP()
void Bulk::ResetP () inline
Reset P to the ones of the last time step.
Definition at line 192 of file Bulk.hpp.
{ P = lP; }
ResetphaseNum()
void Bulk::ResetphaseNum () inline
Definition at line 176 of file Bulk.hpp.
{ phaseNum = lphaseNum; }
ResetPj()
void Bulk::ResetPj () inline
Reset Pj to the ones of the last time step.
Definition at line 194 of file Bulk.hpp.
{ Pj = lPj; }
ResetPSkip()
void Bulk::ResetPSkip () inline
Definition at line 184 of file Bulk.hpp.
{ PSkip = lPSkip; }
ResetVp()
void Bulk::ResetVp () inline
Reset Vp to the ones of the last time step.
Definition at line 200 of file Bulk.hpp.
{ rockVp = lrockVp; }
ResetziSkip()
void Bulk::ResetziSkip () inline
Definition at line 182 of file Bulk.hpp.
{ ziSkip = lziSkip; }
SetCFL2Zero()
void Bulk::SetCFL2Zero () const inline
Initialize the CFL number.
Definition at line 381 of file Bulk.hpp.
{ fill(cfl.begin(), cfl.end(), 0); }
Setup()
void Bulk::Setup (const Grid & myGrid)
Allocate memory for bulk data of grid.
Setup bulk information.
Definition at line 199 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    // Rock/Grid properties
    numBulk = myGrid.activeGridNum;
    dx.resize(numBulk, 0);
    dy.resize(numBulk, 0);
    dz.resize(numBulk, 0);
    depth.resize(numBulk, 0);
    ntg.resize(numBulk, 0);
    rockVpInit.resize(numBulk, 0);
    rockVp.resize(numBulk, 0);
    rockKxInit.resize(numBulk, 0);
    rockKyInit.resize(numBulk, 0);
    rockKzInit.resize(numBulk, 0);
    SATNUM.resize(numBulk, 0);
    PVTNUM.resize(numBulk, 0);
    if (myGrid.SwatInit.size() > 0) {
        SwatInitExist = true;
        SwatInit.resize(numBulk);
    }
    if (ScalePcow) {
        ScaleValuePcow.resize(numBulk, 0);
    }
    for (OCP_USI bIdb = 0; bIdb < numBulk; bIdb++)
    {
        OCP_USI bIdg = myGrid.activeMap_B2G[bIdb];
        dx[bIdb] = myGrid.dx[bIdg];
        dy[bIdb] = myGrid.dy[bIdg];
        dz[bIdb] = myGrid.dz[bIdg];
        depth[bIdb] = myGrid.depth[bIdg];
        ntg[bIdb] = myGrid.ntg[bIdg];
        rockVpInit[bIdb] = myGrid.v[bIdg] * myGrid.ntg[bIdg] * myGrid.poro[bIdg];
        rockKxInit[bIdb] = myGrid.kx[bIdg];
        rockKyInit[bIdb] = myGrid.ky[bIdg];
        rockKzInit[bIdb] = myGrid.kz[bIdg];
        SATNUM[bIdb] = myGrid.SATNUM[bIdg];
        PVTNUM[bIdb] = myGrid.PVTNUM[bIdg];
        if (SwatInitExist) {
            SwatInit[bIdb] = myGrid.SwatInit[bIdg];
        }
    }
    rockVp = rockVpInit;
    rockKx = rockKxInit;
    rockKy = rockKyInit;
    rockKz = rockKzInit;
    // physical variables
    P.resize(numBulk);
    Pb.resize(numBulk);
    Pj.resize(numBulk * numPhase);
    Pc.resize(numBulk * numPhase);
    phaseExist.resize(numBulk * numPhase);
    S.resize(numBulk * numPhase);
    rho.resize(numBulk * numPhase);
    xi.resize(numBulk * numPhase);
    xij.resize(numBulk * numPhase * numCom);
    Ni.resize(numBulk * numCom);
    mu.resize(numBulk * numPhase);
    kr.resize(numBulk * numPhase);
    vj.resize(numBulk * numPhase);
    vf.resize(numBulk);
    Nt.resize(numBulk);
    // Phase num
    totalPhaseNum.resize(numPhase);
    phaseNum.resize(numBulk);
    lphaseNum.resize(numBulk);
    NRphaseNum.resize(numBulk);
    phase2Index.resize(3);
    if (blackOil)
    {
        switch (PVTmode)
        {
        case PHASE_W:
            index2Phase.resize(1);
            index2Phase[0] = WATER;
            phase2Index[WATER] = 0;
            break;
        case PHASE_OW:
            index2Phase.resize(2);
            index2Phase[0] = OIL;
            index2Phase[1] = WATER;
            phase2Index[OIL] = 0;
            phase2Index[WATER] = 1;
            break;
        case PHASE_OG:
            index2Phase.resize(2);
            index2Phase[0] = OIL;
            index2Phase[1] = GAS;
            phase2Index[OIL] = 0;
            phase2Index[GAS] = 1;
            break;
        case PHASE_GW:
            index2Phase.resize(2);
            index2Phase[0] = GAS;
            index2Phase[1] = WATER;
            phase2Index[GAS] = 0;
            phase2Index[WATER] = 1;
            break;
        case PHASE_ODGW:
        case PHASE_DOGW:
            index2Phase.resize(3);
            index2Phase[0] = OIL;
            index2Phase[1] = GAS;
            index2Phase[2] = WATER;
            phase2Index[OIL] = 0;
            phase2Index[GAS] = 1;
            phase2Index[WATER] = 2;
            break;
        default:
            OCP_ABORT("Unknown PVT model!");
        }
    }
    else if (comps)
    {
        phase2Index[OIL] = 0;
        phase2Index[GAS] = 1;
        phase2Index[WATER] = 2;
        minEigenSkip.resize(numBulk);
        flagSkip.resize(numBulk);
        ziSkip.resize(numBulk* numCom);
        PSkip.resize(numBulk);
        lminEigenSkip.resize(numBulk);
        lflagSkip.resize(numBulk);
        lziSkip.resize(numBulk* numCom);
        lPSkip.resize(numBulk);
        Ks.resize(numBulk* (numCom - 1));
        lKs.resize(numBulk* (numCom - 1));
        if (miscible) {
            surTen.resize(numBulk);
            Fk.resize(numBulk);
            Fp.resize(numBulk);
            lsurTen.resize(numBulk);
        }
    }
    // error
    ePEC.resize(numBulk);
    eN.resize(numBulk);
    eV.resize(numBulk);
    CalSomeInfo(myGrid);
#if DEBUG
    CheckSetup();
#endif
}
References CheckSetup(), GAS, OCP_ABORT, OCP_FUNCNAME, OIL, PHASE_DOGW, PHASE_GW, PHASE_ODGW, PHASE_OG, PHASE_OW, PHASE_W, and WATER.
ShowFIMBulk()
void Bulk::ShowFIMBulk (const bool & flag = false) const
Definition at line 3875 of file Bulk.cpp.
{
    cout << numFIMBulk << "   " << fixed << setprecision(3)
        << numFIMBulk * 100.0 / numBulk << "%" << endl;
    if (flag) {
        for (USI n = 0; n < numFIMBulk; n++) {
            cout << setw(6) << FIMBulk[n] << "   ";
            if ((n + 1) % 10 == 0) {
                cout << endl;
            }
        }
        cout << endl;
    }
    if (false) {
        for (USI n = 0; n < numBulk; n++) {
            cout << setw(6) << map_Bulk2FIM[n] << "   ";
            if ((n + 1) % 10 == 0) {
                cout << endl;
            }
        }
        cout << endl;
    }
}
ShowRes()
void Bulk::ShowRes (const vector< OCP_DBL > & res) const
Definition at line 3154 of file Bulk.cpp.
{
    OCP_USI bId;
    const USI len = numCom + 1;
    for (OCP_USI n = 0; n < numBulk; n++)
    {
        bId = n * len;
        cout << endl;
        cout << "Bulk[" << setw(3) << n << "]   ";
        cout << "Vp  " << rockVp[n] << "   ";
        cout << "Nt  " << Nt[n] << "   ";
        cout << "NRstep  " << NRstep[n] << "   ";
        cout << "P   " << P[n] << "   ";
        cout << dPNR[n] << "   " << dPNR[n] / P[n] << "   ";
        cout << (P[n] - lP[n]) / P[n] << "   ";
        cout << "PhaseNum   " << phaseNum[n] << "   ";
        cout << endl;
        for (USI i = 0; i < len; i++) {
            cout << "[" << setw(2) << i << "]" << "   ";
            cout << -res[bId + i] << "   ";
            cout << fabs(res[bId + i] / rockVp[n]) << "   ";
            if (i > 0) {
                cout << fabs(res[bId + i] / Nt[n]) << "   ";
                cout << Ni[n * numCom + i - 1] << "   " << lNi[n * numCom + i - 1] << "   ";
                cout << dNNR[n * numCom + i - 1] << "   " << dNNR[n * numCom + i - 1] / (Ni[n * numCom + i - 1]- dNNR[n * numCom + i - 1]) << "   ";
                cout << (Ni[n * numCom + i - 1] - lNi[n * numCom + i - 1]) / lNi[n * numCom + i - 1] << "   ";
                // cout << vfi[n * numCom + i] << "   ";
            }
            else {
                cout << rockVp[n] - vf[n] << "   ";
            }
            cout << endl;
        }
    }
}
UpdateLastStepAIM()
void Bulk::UpdateLastStepAIM ()
Definition at line 3847 of file Bulk.cpp.
{
    lmuP = muP;
    lxiP = xiP;
    lrhoP = rhoP;
    lmux = mux;
    lxix = xix;
    lrhox = rhox;
    ldPcj_dS = dPcj_dS;
    ldKr_dS = dKr_dS;
    ldSec_dPri = dSec_dPri;
}
UpdateLastStepFIM()
void Bulk::UpdateLastStepFIM ()
Update values of last step for FIM.
Definition at line 3243 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    lphaseNum = phaseNum;
    lminEigenSkip = minEigenSkip;
    lflagSkip = flagSkip;
    lziSkip = ziSkip;
    lPSkip = PSkip;
    lKs = Ks;
    lP = P;
    lPj = Pj;
    lPc = Pc;
    lphaseExist = phaseExist;
    lS = S;
    lnj = nj;
    lrho = rho;
    lxi = xi;
    lxij = xij;
    lNi = Ni;
    lmu = mu;
    lkr = kr;
    lvj = vj;
    lvf = vf;
    lNt = Nt;
    lvfi = vfi;
    lvfp = vfp;
    lrockVp = rockVp;
    lmuP = muP;
    lxiP = xiP;
    lrhoP = rhoP;
    lmux = mux;
    lxix = xix;
    lrhox = rhox;
    ldSec_dPri = dSec_dPri;
    lres_n = res_n;
    lresPc = resPc;
    ldSdPindex = dSdPindex;
    lresIndex = resIndex;
    lpEnumCom = pEnumCom;
    ldKr_dS = dKr_dS;
    ldPcj_dS = dPcj_dS;
    if (miscible) {
        lsurTen = surTen;
    }
}
References OCP_FUNCNAME.
UpdateLastStepIMPEC()
void Bulk::UpdateLastStepIMPEC ()
Update value of last step for IMPEC.
Definition at line 2704 of file Bulk.cpp.
{
    OCP_FUNCNAME;
    lphaseNum = phaseNum;
    lminEigenSkip = minEigenSkip;
    lflagSkip = flagSkip;
    lziSkip = ziSkip;
    lPSkip = PSkip;
    lKs = Ks;
    lP = P;
    lPj = Pj;
    lPc = Pc;
    lphaseExist = phaseExist;
    lS = S;
    lrho = rho;
    lxi = xi;
    lxij = xij;
    lNi = Ni;
    lmu = mu;
    lkr = kr;
    lvj = vj;
    lvf = vf;
    lvfi = vfi;
    lvfp = vfp;
    lrockVp = rockVp;
    lNt = Nt;
    if (miscible) {
        lsurTen = surTen;
    }
}
References OCP_FUNCNAME.
UpdatePj()
void Bulk::UpdatePj ()
Definition at line 4312 of file Bulk.cpp.
{
    for (OCP_USI n = 0; n < numBulk; n++) {
        for (USI j = 0; j < numPhase; j++) {
            Pj[n * numPhase + j] = P[n] + Pc[n * numPhase + j];
        }
    }
}
Friends And Related Function Documentation
BulkConn
friend class BulkConn friend
Definition at line 59 of file Bulk.hpp.
DetailInfo
friend class DetailInfo friend
Definition at line 61 of file Bulk.hpp.
OCP_AIMc
friend class OCP_AIMc friend
Definition at line 68 of file Bulk.hpp.
OCP_AIMt
friend class OCP_AIMt friend
Definition at line 67 of file Bulk.hpp.
OCP_FIM
friend class OCP_FIM friend
Definition at line 65 of file Bulk.hpp.
OCP_IMPEC
friend class OCP_IMPEC friend
Definition at line 64 of file Bulk.hpp.
Reservoir
friend class Reservoir friend
Definition at line 66 of file Bulk.hpp.
Well
friend class Well friend
Definition at line 60 of file Bulk.hpp.
The documentation for this class was generated from the following files:
Bulk.hpp
Bulk.cpp