OpenCAEPoro: OCP_FIM Class Reference
OCP_FIM Class Reference
OCP_FIM is FIM (Fully Implicit Method).
#include <OCPFluidMethod.hpp>
Public Member Functions
void Setup (Reservoir &rs, LinearSystem &myLS, const OCPControl &ctrl)
Setup FIM.
void InitReservoir (Reservoir &rs) const
Init.
void Prepare (Reservoir &rs, OCP_DBL &dt)
Prepare for Assembling matrix.
void AssembleMat (LinearSystem &myLS, const Reservoir &rs, const OCP_DBL &dt) const
Assemble Matrix.
void SolveLinearSystem (LinearSystem &myLS, Reservoir &rs, OCPControl &ctrl) const
Solve the linear system.
bool UpdateProperty (Reservoir &rs, OCPControl &ctrl)
Update properties of fluids.
bool FinishNR (Reservoir &rs, OCPControl &ctrl)
Finish a Newton-Raphson iteration.
void FinishStep (Reservoir &rs, OCPControl &ctrl) const
Finish a time step.
Protected Attributes
ResFIM resFIM
Resiual for FIM.
Detailed Description
OCP_FIM is FIM (Fully Implicit Method).
Definition at line 50 of file OCPFluidMethod.hpp.
Member Function Documentation
AssembleMat()
void OCP_FIM::AssembleMat (LinearSystem & myLS, const Reservoir & rs, const OCP_DBL & dt) const
Assemble Matrix.
Definition at line 246 of file OCPFluidMethod.cpp.
{
    rs.AssembleMatFIM(myLS, dt);
    myLS.AssembleRhs(resFIM.res);
}
References Reservoir::AssembleMatFIM(), LinearSystem::AssembleRhs(), and resFIM.
FinishNR()
bool OCP_FIM::FinishNR (Reservoir & rs, OCPControl & ctrl)
Finish a Newton-Raphson iteration.
Definition at line 324 of file OCPFluidMethod.cpp.
{
    OCP_USI dSn;
    const OCP_DBL NRdSmax = rs.GetNRdSmax(dSn);
    OCP_DBL NRdPmax = rs.GetNRdPmax();
    const OCP_DBL NRdNmax = rs.GetNRdNmax();
    OCP_DBL NRdSmaxP = rs.GetNRdSmaxP();
    //for (USI j = 0; j < rs.bulk.numPhase; j++)
    //    cout << rs.bulk.totalPhaseNum[j] << "   ";
    //cout << endl;
//#ifdef _DEBUG
    cout << "### Res:    " << setprecision(2) << scientific << resFIM.maxRelRes0_v << setw(12)
        << resFIM.maxRelRes_v << setw(12) << resFIM.maxRelRes_mol << setw(11) << NRdPmax << setw(11) << NRdNmax << setw(11) << NRdSmax
        << setw(80) << sqrt(rs.bulk.NRdSSP) / rs.bulk.numBulk << setw(12) << rs.bulk.maxNRdSSP << "  "
        << rs.bulk.phaseNum[rs.bulk.index_maxNRdSSP] << "  " << rs.bulk.NRphaseNum[rs.bulk.index_maxNRdSSP] << "  "
        << setw(6) << rs.bulk.index_maxNRdSSP << "   " << rs.bulk.ePEC[rs.bulk.index_maxNRdSSP] << endl << endl;
    cout << "S:" << setw(6) << dSn << setw(12) << rs.bulk.eV[dSn] << setw(12) << rs.bulk.eN[dSn]
        << setw(12) << rs.bulk.ePEC[dSn] << setw(5) << rs.bulk.phaseNum[dSn] << setw(5) << rs.bulk.NRphaseNum[dSn] << setw(12) << rs.bulk.dPNR[dSn]
        << setw(8) << "  |" << setw(12) <<  rs.bulk.S[dSn * 3] << setw(12) << rs.bulk.dSNR[dSn * 3] << setw(12) << rs.bulk.dSNRP[dSn * 3]
        << setw(12) << rs.bulk.S[dSn * 3 + 1] << setw(12) << rs.bulk.dSNR[dSn * 3 + 1] << setw(12) << rs.bulk.dSNRP[dSn * 3 + 1] << endl;
    cout << "V:" << setw(6) << resFIM.maxId_v << setw(12) << rs.bulk.eV[resFIM.maxId_v] << setw(12) << rs.bulk.eN[resFIM.maxId_v]
        << setw(12) << rs.bulk.ePEC[resFIM.maxId_v] << setw(5) << rs.bulk.phaseNum[resFIM.maxId_v] << setw(5) << rs.bulk.NRphaseNum[resFIM.maxId_v] << setw(12) << rs.bulk.dPNR[resFIM.maxId_v]
        << setw(8) << "  |" << setw(12) << rs.bulk.S[resFIM.maxId_v * 3] << setw(12) << rs.bulk.dSNR[resFIM.maxId_v * 3] << setw(12) << rs.bulk.dSNRP[resFIM.maxId_v * 3]
        << setw(12) << rs.bulk.S[resFIM.maxId_v * 3 + 1] << setw(12) << rs.bulk.dSNR[resFIM.maxId_v * 3 + 1] << setw(12) << rs.bulk.dSNRP[resFIM.maxId_v * 3 + 1] << endl;
    cout << "N:" << setw(6) << resFIM.maxId_mol << setw(12) << rs.bulk.eV[resFIM.maxId_mol] << setw(12) << rs.bulk.eN[resFIM.maxId_mol]
        << setw(12) << rs.bulk.ePEC[resFIM.maxId_mol] << setw(5) << rs.bulk.phaseNum[resFIM.maxId_mol] << setw(5) << rs.bulk.NRphaseNum[resFIM.maxId_mol] << setw(12) << rs.bulk.dPNR[resFIM.maxId_mol]
        << setw(8) << "  |" << setw(12) << rs.bulk.S[resFIM.maxId_mol * 3] << setw(12) << rs.bulk.dSNR[resFIM.maxId_mol * 3] << setw(12) << rs.bulk.dSNRP[resFIM.maxId_mol * 3]
        << setw(12) << rs.bulk.S[resFIM.maxId_mol * 3 + 1] << setw(12) << rs.bulk.dSNR[resFIM.maxId_mol * 3 + 1] << setw(12) << rs.bulk.dSNRP[resFIM.maxId_mol * 3 + 1] << endl;
    // cout << "Res2   " << Dnorm2(resFIM.res.size(), &resFIM.res[0]) / resFIM.res.size() << "   ";
    // cout << "SdP " << Dnorm1(rs.bulk.dPNR.size(), &rs.bulk.dPNR[0]) / rs.bulk.dPNR.size() << "   ";
    // cout << "SdNi " << Dnorm1(rs.bulk.dNNR.size(), &rs.bulk.dNNR[0]) / rs.bulk.dNNR.size() << "   ";
    cout << endl;
    // rs.ShowRes(resFIM.res);
//#endif
    if (ctrl.iterNR > ctrl.ctrlNR.maxNRiter) {
        ctrl.current_dt *= ctrl.ctrlTime.cutFacNR;
        rs.ResetFIM(false);
        rs.CalResFIM(resFIM, ctrl.current_dt);
        resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
        ctrl.ResetIterNRLS();
        cout << "### WARNING: NR not fully converged! Cut time stepsize and repeat!\n";
        return false;
    }
    if ((resFIM.maxRelRes_v <= resFIM.maxRelRes0_v * ctrl.ctrlNR.NRtol ||
        resFIM.maxRelRes_v <= ctrl.ctrlNR.NRtol ||
        resFIM.maxRelRes_mol <= ctrl.ctrlNR.NRtol) &&
        (fabs(NRdPmax) <= ctrl.ctrlNR.NRdPmin && fabs(NRdSmax) <= ctrl.ctrlNR.NRdSmin)) {
        OCP_INT flagCheck = rs.CheckP(false, true);
#if DEBUG
        if (flagCheck > 0) {
            cout << ">> Switch well constraint: Case " << flagCheck << endl;
        }
#endif
        switch (flagCheck) {
            case 1:
                ctrl.current_dt *= ctrl.ctrlTime.cutFacNR;
                rs.ResetFIM(true);
                rs.CalResFIM(resFIM, ctrl.current_dt);
                resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
                ctrl.ResetIterNRLS();
                cout << "-----" << endl;
                return false;
            case 2:
                ctrl.current_dt /= 1;
                rs.ResetFIM(true);
                rs.CalResFIM(resFIM, ctrl.current_dt);
                resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
                ctrl.ResetIterNRLS();
                cout << "-----" << endl;
                return false;
            default:
                return true;
                break;
        }
    } else {
        return false;
    }
}
References Reservoir::CalResFIM(), Reservoir::CheckP(), ControlTime::cutFacNR, Reservoir::GetNRdNmax(), Reservoir::GetNRdPmax(), Reservoir::GetNRdSmax(), Reservoir::GetNRdSmaxP(), ControlNR::maxNRiter, ControlNR::NRdPmin, ControlNR::NRdSmin, ControlNR::NRtol, Reservoir::ResetFIM(), OCPControl::ResetIterNRLS(), and resFIM.
FinishStep()
void OCP_FIM::FinishStep (Reservoir & rs, OCPControl & ctrl) const
Finish a time step.
Definition at line 416 of file OCPFluidMethod.cpp.
{
    rs.CalIPRT(ctrl.GetCurDt());
    rs.CalMaxChange();
    rs.UpdateLastStepFIM();
    ctrl.CalNextTstepFIM(rs);
    ctrl.UpdateIters();
}
References Reservoir::CalIPRT(), Reservoir::CalMaxChange(), OCPControl::GetCurDt(), OCPControl::UpdateIters(), and Reservoir::UpdateLastStepFIM().
InitReservoir()
void OCP_FIM::InitReservoir (Reservoir & rs) const
Init.
Definition at line 233 of file OCPFluidMethod.cpp.
{
    rs.InitFIM();
}
References Reservoir::InitFIM().
Prepare()
void OCP_FIM::Prepare (Reservoir & rs, OCP_DBL & dt)
Prepare for Assembling matrix.
Definition at line 238 of file OCPFluidMethod.cpp.
{
    rs.PrepareWell();
    rs.CalWellFlux();
    rs.CalResFIM(resFIM, dt);
    resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
}
References Reservoir::CalResFIM(), Reservoir::CalWellFlux(), Reservoir::PrepareWell(), and resFIM.
Setup()
void OCP_FIM::Setup (Reservoir & rs, LinearSystem & myLS, const OCPControl & ctrl)
Setup FIM.
Definition at line 220 of file OCPFluidMethod.cpp.
{
    // Allocate Bulk and BulkConn Memory
    rs.AllocateAuxFIM();
    // Allocate memory for internal matrix structure
    rs.AllocateMatFIM(myLS);
    // Allocate memory for resiual of FIM
    OCP_USI num = (rs.GetBulkNum() + rs.GetWellNum()) * (rs.GetComNum() + 1);
    resFIM.res.resize(num);
    myLS.SetupLinearSolver(VECTORFASP, ctrl.GetWorkDir(), ctrl.GetLsFile());
}
References Reservoir::AllocateAuxFIM(), Reservoir::AllocateMatFIM(), Reservoir::GetBulkNum(), Reservoir::GetComNum(), OCPControl::GetLsFile(), Reservoir::GetWellNum(), OCPControl::GetWorkDir(), resFIM, LinearSystem::SetupLinearSolver(), and VECTORFASP.
SolveLinearSystem()
void OCP_FIM::SolveLinearSystem (LinearSystem & myLS, Reservoir & rs, OCPControl & ctrl) const
Solve the linear system.
Definition at line 253 of file OCPFluidMethod.cpp.
{
#ifdef _DEBUG
    myLS.CheckEquation();
#endif // DEBUG
    myLS.AssembleMatLinearSolver();
    GetWallTime Timer;
    Timer.Start();
    int status = myLS.Solve();
    if (status < 0) {
        status = myLS.GetNumIters();
    }
    // cout << "LS step = " << status << endl;
#ifdef DEBUG
    myLS.OutputLinearSystem("testA_FIM.out", "testb_FIM.out");
    myLS.OutputSolution("testx_FIM.out");
    myLS.CheckSolution();
#endif // DEBUG
    ctrl.UpdateTimeLS(Timer.Stop() / 1000);
    ctrl.UpdateIterLS(status);
    ctrl.UpdateIterNR();
    rs.GetSolutionFIM(myLS.GetSolution(), ctrl.ctrlNR.NRdPmax, ctrl.ctrlNR.NRdSmax);
    // rs.GetSolution01FIM(myLS.GetSolution());
    // rs.PrintSolFIM(ctrl.workDir + "testPNi.out");
    myLS.ClearData();
}
References LinearSystem::AssembleMatLinearSolver(), LinearSystem::CheckEquation(), LinearSystem::CheckSolution(), LinearSystem::ClearData(), LinearSystem::GetNumIters(), LinearSystem::GetSolution(), Reservoir::GetSolutionFIM(), ControlNR::NRdPmax, ControlNR::NRdSmax, LinearSystem::OutputLinearSystem(), LinearSystem::OutputSolution(), LinearSystem::Solve(), GetWallTime::Start(), GetWallTime::Stop(), OCPControl::UpdateIterLS(), OCPControl::UpdateIterNR(), and OCPControl::UpdateTimeLS().
UpdateProperty()
bool OCP_FIM::UpdateProperty (Reservoir & rs, OCPControl & ctrl)
Update properties of fluids.
Definition at line 285 of file OCPFluidMethod.cpp.
{
    OCP_DBL& dt = ctrl.current_dt;
    // Second check: Ni check and bulk Pressure check
    if (!rs.CheckNi() || rs.CheckP(true, false) != 0) {
        dt *= ctrl.ctrlTime.cutFacNR;
        rs.ResetFIM(false);
        rs.CalResFIM(resFIM, dt);
        resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
        cout << "Cut time stepsize and repeat!\n";
        return false;
    }
    // Update reservoir properties
    rs.CalFlashDerivFIM();
    rs.CalKrPcDerivFIM();
    rs.CalVpore();
    rs.CalWellTrans();
    rs.CalWellFlux();
    rs.CalResFIM(resFIM, dt);
    //if (rs.bulk.NRdPmax < 1E-4) {
    //    // correct
    //    cout << "correct" << endl;
    //    rs.bulk.CorrectNi(resFIM.res);
    //    // Update reservoir properties
    //    rs.CalFlashDerivFIM();
    //    rs.CalKrPcDerivFIM();
    //    rs.CalVpore();
    //    rs.CalWellTrans();
    //    rs.CalWellFlux();
    //    rs.CalResFIM(resFIM, dt);
    //}
    return true;
}
References Reservoir::CalFlashDerivFIM(), Reservoir::CalKrPcDerivFIM(), Reservoir::CalResFIM(), Reservoir::CalVpore(), Reservoir::CalWellFlux(), Reservoir::CalWellTrans(), Reservoir::CheckNi(), Reservoir::CheckP(), ControlTime::cutFacNR, Reservoir::ResetFIM(), and resFIM.
Member Data Documentation
resFIM
ResFIM OCP_FIM::resFIM protected
Resiual for FIM.
Definition at line 80 of file OCPFluidMethod.hpp.
The documentation for this class was generated from the following files:
OCPFluidMethod.hpp
OCPFluidMethod.cpp