OpenCAEPoro: ParamRead Class Reference
ParamRead Class Reference
Pre-processing unit for OpenCAEPoro for reading params from input files.
#include <ParamRead.hpp>
Public Member Functions
void GetDirAndName ()
Get current work dir and input file name from the full file path.
void Init ()
Initialize the param reading process.
void ReadInputFile (const string &file)
General interface for reading input data.
void ReadFile (const string &file)
Read the input file.
void ReadINCLUDE (ifstream &ifs)
Handle the INCLUDE keyword, which contains other input files.
void CheckParam ()
Check whether the params contain error.
Public Attributes
string inputFile
Input file with its path (absolute or relative).
string workDir
Current work directory.
string fileName
File name of input file.
ParamReservoir paramRs
Read the reservoir params.
ParamWell paramWell
Read the well params.
ParamControl paramControl
Read the control params.
ParamOutput paramOutput
Read the output params.
Detailed Description
Pre-processing unit for OpenCAEPoro for reading params from input files.
Definition at line 32 of file ParamRead.hpp.
Member Function Documentation
CheckParam()
void ParamRead::CheckParam ()
Check whether the params contain error.
Check parameters in paramRs and paramWell.
Definition at line 298 of file ParamRead.cpp.
{
    cout << "=========================================" << endl
         << "Check reading parameters from input data!" << endl
         << "=========================================" << endl;
    paramRs.CheckParam();
    paramWell.CheckParam(paramRs.blackOil);
}
References ParamReservoir::blackOil, ParamReservoir::CheckParam(), ParamWell::CheckParam(), paramRs, and paramWell.
GetDirAndName()
void ParamRead::GetDirAndName ()
Get current work dir and input file name from the full file path.
Get workDir and fileName from inputFile.
Definition at line 23 of file ParamRead.cpp.
{
#if defined(_CONSOLE) || defined(_WIN32) || defined(_WIN64)
    // for Window file system
    OCP_INT pos = inputFile.find_last_of('\\') + 1;
    workDir     = inputFile.substr(0, pos);
    fileName    = inputFile.substr(pos, inputFile.size() - pos);
#else
    // for Linux and Mac OSX file system
    OCP_INT pos = inputFile.find_last_of('/') + 1;
    workDir     = inputFile.substr(0, pos);
    fileName    = inputFile.substr(pos, inputFile.size() - pos);
#endif
}
References fileName, inputFile, and workDir.
Init()
void ParamRead::Init ()
Initialize the param reading process.
Initialize paramRs, paramWell, and paramControl.
Definition at line 15 of file ParamRead.cpp.
{
    paramRs.Init();
    paramWell.Init();
    paramControl.Init(workDir);
}
References ParamReservoir::Init(), ParamWell::Init(), ParamControl::Init(), paramControl, paramRs, paramWell, and workDir.
ReadFile()
void ParamRead::ReadFile (const string & file)
Read the input file.
Read parameters from a file, which is called in ReadInputFile.
Definition at line 49 of file ParamRead.cpp.
{
    ifstream ifs(filename, ios::in);
    if (!ifs) {
        OCP_MESSAGE("Trying to open file: " << (filename));
        OCP_ABORT("Failed to open the input file!");
    }
    while (!ifs.eof()) {
        vector<string> vbuf;
        if (!ReadLine(ifs, vbuf)) break;
        string keyword = vbuf[0];
        switch (Map_Str2Int(&keyword[0], keyword.size())) {
            case Map_Str2Int("BLACKOIL", 8):
                paramRs.blackOil = true;
                break;
            case Map_Str2Int("COMPS", 5):
                paramRs.InputCOMPS(ifs);
                break;
            case Map_Str2Int("OIL", 3):
                paramRs.oil = true;
                break;
            case Map_Str2Int("GAS", 3):
                paramRs.gas = true;
                break;
            case Map_Str2Int("WATER", 5):
                paramRs.water = true;
                break;
            case Map_Str2Int("DISGAS", 6):
                paramRs.disGas = true;
                break;
            case Map_Str2Int("DIMENS", 6):
                paramRs.InputDIMENS(ifs);
                paramRs.DisplayDIMENS();
                break;
            case Map_Str2Int("RTEMP", 5):
                paramRs.InputRTEMP(ifs);
                break;
            case Map_Str2Int("EQUALS", 6):
                paramRs.InputEQUALS(ifs);
                break;
            case Map_Str2Int("DX", 2):
            case Map_Str2Int("DY", 2):
            case Map_Str2Int("DZ", 2):
            case Map_Str2Int("COORD", 5):
            case Map_Str2Int("ZCORN", 5):
            case Map_Str2Int("NTG", 3):
            case Map_Str2Int("PORO", 4):
            case Map_Str2Int("TOPS", 4):
            case Map_Str2Int("PERMX", 5):
            case Map_Str2Int("PERMY", 5):
            case Map_Str2Int("PERMZ", 5):
            case Map_Str2Int("PRESSURE", 8):
            case Map_Str2Int("Ni", 2):
            case Map_Str2Int("SWATINIT", 8):
                paramRs.InputGRID(ifs, keyword);
                break;
            case Map_Str2Int("COPY", 4):
                paramRs.InputCOPY(ifs);
                break;
            case Map_Str2Int("MULTIPLY", 8):
                paramRs.InputMULTIPLY(ifs);
                break;
            case Map_Str2Int("SWFN", 4):
            case Map_Str2Int("SWOF", 4):
            case Map_Str2Int("SGFN", 4):
            case Map_Str2Int("SGOF", 4):
            case Map_Str2Int("SOF3", 4):
            case Map_Str2Int("PVCO", 4):
            case Map_Str2Int("PVDO", 4):
            case Map_Str2Int("PVDG", 4):
            case Map_Str2Int("PVTW", 4):
            case Map_Str2Int("PBVD", 4):
                paramRs.InputTABLE(ifs, keyword);
                break;
            case Map_Str2Int("ROCK", 4):
                paramRs.InputROCK(ifs);
                break;
            case Map_Str2Int("MISCIBLE", 8):
                paramRs.EoSp.miscible = true;
                break;
            case Map_Str2Int("MISCSTR", 7):
                paramRs.InputMISCSTR(ifs);
                break;
            case Map_Str2Int("GRAVITY", 7):
                paramRs.InputGRAVITY(ifs);
                break;
            case Map_Str2Int("DENSITY", 7):
                paramRs.InputDENSITY(ifs);
                break;
            case Map_Str2Int("EQUIL", 5):
                paramRs.InputEQUIL(ifs);
                break;
            case Map_Str2Int("TABDIMS", 7):
                paramRs.InputTABDIMS(ifs);
                break;
            case Map_Str2Int("SATNUM", 6):
            case Map_Str2Int("PVTNUM", 6):
            case Map_Str2Int("ACTNUM", 6):
                paramRs.InputRegion(ifs, keyword);
                break;
            case Map_Str2Int("INCLUDE", 7):
                ReadINCLUDE(ifs);
                break;
            case Map_Str2Int("METHOD", 6):
                paramControl.InputMETHOD(ifs);
                break;
            case Map_Str2Int("TUNING", 6):
                paramControl.InputTUNING(ifs);
                break;
            case Map_Str2Int("WELSPECS", 8):
                paramWell.InputWELSPECS(ifs);
                break;
            case Map_Str2Int("COMPDAT", 7):
                paramWell.InputCOMPDAT(ifs);
                break;
            case Map_Str2Int("WCONINJE", 8):
                paramWell.InputWCONINJE(ifs);
                break;
            case Map_Str2Int("WCONPROD", 8):
                paramWell.InputWCONPROD(ifs);
                break;
            case Map_Str2Int("TSTEP", 5):
                paramWell.InputTSTEP(ifs);
                paramControl.criticalTime = paramWell.criticalTime;
                break;
            case Map_Str2Int("WELTARG", 7):
            case Map_Str2Int("WELLTARG", 8):
                paramWell.InputWELTARG(ifs);
                break;
            case Map_Str2Int("WELLSTRE", 8):
                paramWell.InputWELLSTRE(ifs);
                break;
            case Map_Str2Int("SUMMARY", 7):
                paramOutput.InputSUMMARY(ifs);
                break;
            case Map_Str2Int("RPTSCHED", 8):
                paramOutput.InputRPTSCHED(ifs);
                break;
            case Map_Str2Int("NCNP", 4):
                paramRs.InputNCNP(ifs);
                break;
            case Map_Str2Int("CNAMES", 6):
                paramRs.InputCNAMES(ifs);
                break;
            case Map_Str2Int("ZI", 2):
                paramRs.InputZI(ifs);
                break;
            case Map_Str2Int("COM", 3):
                paramRs.InputCOM(ifs);
                break;
            case Map_Str2Int("TCRIT", 5):
            case Map_Str2Int("PCRIT", 5):
            case Map_Str2Int("VCRIT", 5):
            case Map_Str2Int("ZCRIT", 5):
            case Map_Str2Int("MW", 2):
            case Map_Str2Int("ACF", 3):
            case Map_Str2Int("OMEGAA", 6):
            case Map_Str2Int("OMEGAB", 6):
            case Map_Str2Int("SSHIFT", 6):
            case Map_Str2Int("PARACHOR", 8):
            case Map_Str2Int("VCRITVIS", 8):
                paramRs.InputCOMPONENTS(ifs, keyword);
                break;
            case Map_Str2Int("LBCCOEF", 7):
                paramRs.InputLBCCOEF(ifs);
                break;
            case Map_Str2Int("BIC", 3):
                paramRs.InputBIC(ifs);
                break;
            case Map_Str2Int("SSMSTA", 6):
                paramRs.InputSSMSTA(ifs);
                break;
            case Map_Str2Int("SSMSP", 5):
                paramRs.InputSSMSP(ifs);
                break;
            case Map_Str2Int("NRSTA", 5):
                paramRs.InputNRSTA(ifs);
                break;
            case Map_Str2Int("NRSP", 4):
                paramRs.InputNRSP(ifs);
                break;
            case Map_Str2Int("RR", 2):
                paramRs.InputRR(ifs);
                break;
            default: // skip non-keywords
                break;
        }
    }
    ifs.close();
}
References ParamReservoir::blackOil, ParamControl::criticalTime, ParamWell::criticalTime, ParamReservoir::disGas, ParamReservoir::DisplayDIMENS(), ParamReservoir::EoSp, ParamReservoir::gas, ParamWell::InputCOMPDAT(), ParamReservoir::InputCOMPS(), ParamReservoir::InputCOPY(), ParamReservoir::InputDENSITY(), ParamReservoir::InputDIMENS(), ParamReservoir::InputEQUALS(), ParamReservoir::InputEQUIL(), ParamReservoir::InputGRAVITY(), ParamReservoir::InputGRID(), ParamControl::InputMETHOD(), ParamReservoir::InputMISCSTR(), ParamReservoir::InputMULTIPLY(), ParamReservoir::InputRegion(), ParamReservoir::InputROCK(), ParamOutput::InputRPTSCHED(), ParamReservoir::InputRTEMP(), ParamOutput::InputSUMMARY(), ParamReservoir::InputTABDIMS(), ParamReservoir::InputTABLE(), ParamWell::InputTSTEP(), ParamControl::InputTUNING(), ParamWell::InputWCONINJE(), ParamWell::InputWCONPROD(), ParamWell::InputWELLSTRE(), ParamWell::InputWELSPECS(), ParamWell::InputWELTARG(), Map_Str2Int(), EoSparam::miscible, OCP_ABORT, OCP_MESSAGE, ParamReservoir::oil, paramControl, paramOutput, paramRs, paramWell, ReadINCLUDE(), ReadLine(), and ParamReservoir::water.
ReadINCLUDE()
void ParamRead::ReadINCLUDE (ifstream & ifs)
Handle the INCLUDE keyword, which contains other input files.
Read INCLUDE files; these files should have identical format.
Definition at line 289 of file ParamRead.cpp.
{
    vector<string> vbuf;
    ReadLine(ifs, vbuf);
    DealDefault(vbuf);
    ReadFile(workDir + vbuf[0]);
}
References DealDefault(), ReadFile(), ReadLine(), and workDir.
ReadInputFile()
void ParamRead::ReadInputFile (const string & file)
General interface for reading input data.
This is the general interface for reading input files.
Definition at line 39 of file ParamRead.cpp.
{
    inputFile = filename;
    GetDirAndName();
    Init();
    ReadFile(inputFile);
    CheckParam();
}
References CheckParam(), GetDirAndName(), Init(), inputFile, and ReadFile().
Member Data Documentation
fileName
string ParamRead::fileName
File name of input file.
Definition at line 37 of file ParamRead.hpp.
inputFile
string ParamRead::inputFile
Input file with its path (absolute or relative).
Definition at line 35 of file ParamRead.hpp.
paramControl
ParamControl ParamRead::paramControl
Read the control params.
Definition at line 44 of file ParamRead.hpp.
paramOutput
ParamOutput ParamRead::paramOutput
Read the output params.
Definition at line 45 of file ParamRead.hpp.
paramRs
ParamReservoir ParamRead::paramRs
Read the reservoir params.
Definition at line 42 of file ParamRead.hpp.
paramWell
ParamWell ParamRead::paramWell
Read the well params.
Definition at line 43 of file ParamRead.hpp.
workDir
string ParamRead::workDir
Current work directory.
Definition at line 36 of file ParamRead.hpp.
The documentation for this class was generated from the following files:
ParamRead.hpp
ParamRead.cpp