OpenCAEPoro: FlowUnit_ODGW02 Class Reference
FlowUnit_ODGW02 Class Reference
Public Member Functions
FlowUnit_ODGW02 (const ParamReservoir &rs_param, const USI &i)
void CalKrPc (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp) override
calculate relative permeability and capillary pressure.
void CalKrPcDeriv (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, OCP_DBL *dkrdS, OCP_DBL *dPcjdS, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp) override
OCP_DBL CalKro_Stone2Der (OCP_DBL krow, OCP_DBL krog, OCP_DBL krw, OCP_DBL krg, OCP_DBL dkrwdSw, OCP_DBL dkrowdSo, OCP_DBL dkrgdSg, OCP_DBL dkrogdSo, OCP_DBL &out_dkrodSo) const
OCP_DBL CalKro_DefaultDer (const OCP_DBL &Sg, const OCP_DBL &Sw, const OCP_DBL &krog, const OCP_DBL &krow, const OCP_DBL &dkrogSo, const OCP_DBL &dkrowSo, OCP_DBL &dkroSo) const
OCP_DBL GetPcowBySw (const OCP_DBL &sw) override
Pcow = Po - Pw.
OCP_DBL GetSwByPcow (const OCP_DBL &pcow) override
OCP_DBL GetPcgoBySg (const OCP_DBL &sg) override
Pcgo = Pg - Po.
OCP_DBL GetSgByPcgo (const OCP_DBL &pcgo) override
OCP_DBL GetSwByPcgw (const OCP_DBL &pcgw) override
Pcgw = Pg - Pw.
void Generate_SWPCWG ()
Public Member Functions inherited from FlowUnit_ODGW
OCP_DBL CalKro_Stone2 (const OCP_DBL &krow, const OCP_DBL &krog, const OCP_DBL &krw, const OCP_DBL &krg) const
OCP_DBL CalKro_Default (const OCP_DBL &Sg, const OCP_DBL &Sw, const OCP_DBL &krog, const OCP_DBL &krow) const
OCP_DBL GetSwco () const override
const vector< OCP_DBL > & GetScm () const override
Public Member Functions inherited from FlowUnit
FlowUnit ()=default
Default constructor.
virtual OCP_DBL GetPcowBySw (const OCP_DBL &sw)=0
Pcow = Po - Pw.
virtual OCP_DBL GetSwByPcow (const OCP_DBL &pcow)=0
virtual OCP_DBL GetPcgoBySg (const OCP_DBL &sg)=0
Pcgo = Pg - Po.
virtual OCP_DBL GetSgByPcgo (const OCP_DBL &pcgo)=0
virtual OCP_DBL GetSwByPcgw (const OCP_DBL &pcgw)=0
Pcgw = Pg - Pw.
virtual OCP_DBL GetSwco () const =0
virtual const vector< OCP_DBL > & GetScm () const =0
virtual void CalKrPc (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp)=0
calculate relative permeability and capillary pressure.
virtual void CalKrPcDeriv (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, OCP_DBL *dkrdS, OCP_DBL *dPcjdS, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp)=0
Additional Inherited Members
Protected Attributes inherited from FlowUnit_ODGW
OCP_DBL kroMax
oil relative permeability in the presence of connate water only, used in stone2
OCP_DBL Swco
Saturation of connate water.
vector< OCP_DBL > Scm
critical saturation when phase becomes mobile / immobile
Detailed Description
Definition at line 290 of file FlowUnit.hpp.
Constructor & Destructor Documentation
FlowUnit_ODGW02()
FlowUnit_ODGW02::FlowUnit_ODGW02 (const ParamReservoir & rs_param, const USI & i)
Definition at line 477 of file FlowUnit.cpp.
{
    SWFN.Setup(rs_param.SWFN_T.data[i]);
    SGFN.Setup(rs_param.SGFN_T.data[i]);
    SOF3.Setup(rs_param.SOF3_T.data[i]);
    kroMax = SOF3.GetCol(1).back();
    Swco = SWFN.GetCol(0)[0];
    data.resize(3, 0);
    cdata.resize(3, 0);
    Generate_SWPCWG();
}
Member Function Documentation
CalKro_DefaultDer()
OCP_DBL FlowUnit_ODGW02::CalKro_DefaultDer (const OCP_DBL & Sg, const OCP_DBL & Sw, const OCP_DBL & krog, const OCP_DBL & krow, const OCP_DBL & dkrogSo, const OCP_DBL & dkrowSo, OCP_DBL & dkroSo) const
Definition at line 598 of file FlowUnit.cpp.
{
    OCP_DBL tmp = Sg + Sw - Swco;
    OCP_DBL kro = (Sg * krog + (Sw - Swco) * krow) / tmp;
    out_dkrodSo = (Sg * dkrogdSo + (Sw - Swco) * dkrowdSo) / tmp;
    if (tmp <= TINY) {
        kro = kroMax;
        out_dkrodSo = 0;
    }
    return kro;
}
CalKro_Stone2Der()
OCP_DBL FlowUnit_ODGW02::CalKro_Stone2Der (OCP_DBL krow, OCP_DBL krog, OCP_DBL krw, OCP_DBL krg, OCP_DBL dkrwdSw, OCP_DBL dkrowdSo, OCP_DBL dkrgdSg, OCP_DBL dkrogdSo, OCP_DBL & out_dkrodSo) const
Definition at line 581 of file FlowUnit.cpp.
{
    OCP_DBL kro, dKrodSo;
    kro = kroMax * ((krow / kroMax + krw) * (krog / kroMax + krg) - (krw + krg));
    dKrodSo = dkrowdSo * (krog / kroMax + krg) + dkrogdSo * (krow / kroMax + krw);
    if (kro < 0) {
        kro = 0;
        dKrodSo = 0;
    }
    out_dkrodSo = dKrodSo;
    return kro;
}
CalKrPc()
void FlowUnit_ODGW02::CalKrPc (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out, const OCP_DBL & MySurTen, OCP_DBL & MyFk, OCP_DBL & MyFp) override virtual
calculate relative permeability and capillary pressure.
Implements FlowUnit.
Definition at line 493 of file FlowUnit.cpp.
{
    OCP_DBL So = S_in[0];
    OCP_DBL Sg = S_in[1];
    OCP_DBL Sw = S_in[2];
    SWFN.Eval_All(0, Sw, data, cdata);
    OCP_DBL krw = data[1];
    OCP_DBL Pcwo = -data[2];
    SGFN.Eval_All(0, Sg, data, cdata);
    OCP_DBL krg = data[1];
    OCP_DBL Pcgo = data[2];
    SOF3.Eval_All(0, So, data, cdata);
    OCP_DBL krow = data[1];
    OCP_DBL krog = data[2];
    // OCP_DBL kro = CalKro_Stone2(krow, krog, krw, krg);
    OCP_DBL kro = CalKro_Default(Sg, Sw, krog, krow);
    kr_out[0] = kro;
    kr_out[1] = krg;
    kr_out[2] = krw;
    pc_out[0] = 0;
    pc_out[1] = Pcgo;
    pc_out[2] = Pcwo;
}
References OCPTable::Eval_All().
CalKrPcDeriv()
void FlowUnit_ODGW02::CalKrPcDeriv (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out, OCP_DBL * dkrdS, OCP_DBL * dPcjdS, const OCP_DBL & MySurTen, OCP_DBL & MyFk, OCP_DBL & MyFp) override virtual
Implements FlowUnit.
Definition at line 524 of file FlowUnit.cpp.
{
    OCP_DBL So = S_in[0];
    OCP_DBL Sg = S_in[1];
    OCP_DBL Sw = S_in[2];
    SWFN.Eval_All(0, Sw, data, cdata);
    OCP_DBL krw        = data[1];
    OCP_DBL dKrwdSw    = cdata[1];
    OCP_DBL Pcwo       = -data[2];
    OCP_DBL dPcwodSw   = -cdata[2];
    SGFN.Eval_All(0, Sg, data, cdata);
    OCP_DBL krg        = data[1];
    OCP_DBL dKrgdSg    = cdata[1];
    OCP_DBL Pcgo       = data[2];
    OCP_DBL dPcgodSg   = cdata[2];
    SOF3.Eval_All(0, So, data, cdata);
    OCP_DBL krow       = data[1];
    OCP_DBL dKrowdSo   = cdata[1];
    OCP_DBL krog       = data[2];
    OCP_DBL dKrogdSo   = cdata[2];
    OCP_DBL dKroSo = 0;
    OCP_DBL kro = CalKro_Stone2Der(krow, krog, krw, krg, dKrwdSw, dKrowdSo, dKrgdSg, dKrogdSo, dKroSo);
    // OCP_DBL kro = CalKro_DefaultDer(Sg, Sw, krog, krow, dKrogdSo, dKrowdSo, dKroSo);
    kr_out[0] = kro;
    kr_out[1] = krg;
    kr_out[2] = krw;
    pc_out[0] = 0;
    pc_out[1] = Pcgo;
    pc_out[2] = Pcwo;
    dkrdS[0] = dKroSo;
    dkrdS[1] = 0;
    dkrdS[2] = 0;
    dkrdS[3] = 0;
    dkrdS[4] = dKrgdSg;
    dkrdS[5] = 0;
    dkrdS[6] = 0;
    dkrdS[7] = 0;
    dkrdS[8] = dKrwdSw;
    dPcjdS[0] = 0;
    dPcjdS[1] = 0;
    dPcjdS[2] = 0;
    dPcjdS[3] = 0;
    dPcjdS[4] = dPcgodSg;
    dPcjdS[5] = 0;
    dPcjdS[6] = 0;
    dPcjdS[7] = 0;
    dPcjdS[8] = dPcwodSw;
}
Generate_SWPCWG()
void FlowUnit_ODGW02::Generate_SWPCWG ()
Definition at line 614 of file FlowUnit.cpp.
{
    if (SWFN.IsEmpty()) OCP_ABORT("SWFN is missing!");
    if (SGFN.IsEmpty()) OCP_ABORT("SGFN is missing!");
    std::vector<OCP_DBL> Sw(SWFN.GetCol(0));
    std::vector<OCP_DBL> Pcow(SWFN.GetCol(2));
    USI                  n = Sw.size();
    for (USI i = 0; i < n; i++) {
        OCP_DBL Pcgo = SGFN.Eval(0, 1 - Sw[i], 2);
        Pcow[i] += Pcgo; // pcgw
    }
    SWPCGW.PushCol(Sw);
    SWPCGW.PushCol(Pcow);
    SWPCGW.SetRowCol();
}
GetPcgoBySg()
OCP_DBL FlowUnit_ODGW02::GetPcgoBySg (const OCP_DBL & sg) inline override virtual
Pcgo = Pg - Po.
Implements FlowUnit.
Definition at line 315 of file FlowUnit.hpp.
{
        return SGFN.Eval(0, sg, 2);
    }
References OCPTable::Eval().
GetPcowBySw()
OCP_DBL FlowUnit_ODGW02::GetPcowBySw (const OCP_DBL & sw) inline override virtual
Pcow = Po - Pw.
Implements FlowUnit.
Definition at line 309 of file FlowUnit.hpp.
{
        return SWFN.Eval(0, sw, 2);
    }
References OCPTable::Eval().
GetSgByPcgo()
OCP_DBL FlowUnit_ODGW02::GetSgByPcgo (const OCP_DBL & pcgo) inline override virtual
Implements FlowUnit.
Definition at line 318 of file FlowUnit.hpp.
{
        return SGFN.Eval(2, pcgo, 0);
    }
GetSwByPcgw()
OCP_DBL FlowUnit_ODGW02::GetSwByPcgw (const OCP_DBL & pcgw) inline override virtual
Pcgw = Pg - Pw.
Implements FlowUnit.
Definition at line 321 of file FlowUnit.hpp.
{
        return SWPCGW.Eval_Inv(1, pcgw, 0);
    }
References OCPTable::Eval_Inv().
GetSwByPcow()
OCP_DBL FlowUnit_ODGW02::GetSwByPcow (const OCP_DBL & pcow) inline override virtual
Implements FlowUnit.
Definition at line 312 of file FlowUnit.hpp.
{
        return SWFN.Eval_Inv(2, pcow, 0);
    }
The documentation for this class was generated from the following files:
FlowUnit.hpp
FlowUnit.cpp