OpenCAEPoro: FlowUnit_ODGW01_Miscible Class Reference
FlowUnit_ODGW01_Miscible Class Reference
Public Member Functions
FlowUnit_ODGW01_Miscible (const ParamReservoir &rs_param, const USI &i)
void CalKrPc (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp) override
calculate relative permeability and capillary pressure.
void CalKrPcDeriv (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, OCP_DBL *dkrdS, OCP_DBL *dPcjdS, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp) override
Public Member Functions inherited from FlowUnit_ODGW01
FlowUnit_ODGW01 (const ParamReservoir &rs_param, const USI &i)
virtual void CalKrPc (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp) override
calculate relative permeability and capillary pressure.
virtual void CalKrPcDeriv (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, OCP_DBL *dkrdS, OCP_DBL *dPcjdS, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp) override
OCP_DBL CalKro_Stone2Der (OCP_DBL krow, OCP_DBL krog, OCP_DBL krw, OCP_DBL krg, OCP_DBL dkrwdSw, OCP_DBL dkrowdSw, OCP_DBL dkrgdSg, OCP_DBL dkrogdSg, OCP_DBL &out_dkrodSw, OCP_DBL &out_dkrodSg) const
OCP_DBL CalKro_DefaultDer (const OCP_DBL &Sg, const OCP_DBL &Sw, const OCP_DBL &krog, const OCP_DBL &krow, const OCP_DBL &dkrogSg, const OCP_DBL &dkrowSw, OCP_DBL &dkroSg, OCP_DBL &dkroSw) const
OCP_DBL GetPcowBySw (const OCP_DBL &sw) override
Pcow = Po - Pw.
OCP_DBL GetSwByPcow (const OCP_DBL &pcow) override
OCP_DBL GetPcgoBySg (const OCP_DBL &sg) override
Pcgo = Pg - Po.
OCP_DBL GetSgByPcgo (const OCP_DBL &pcgo) override
OCP_DBL GetSwByPcgw (const OCP_DBL &pcgw) override
Pcgw = Pg - Pw.
void Generate_SWPCWG ()
Public Member Functions inherited from FlowUnit_ODGW
OCP_DBL CalKro_Stone2 (const OCP_DBL &krow, const OCP_DBL &krog, const OCP_DBL &krw, const OCP_DBL &krg) const
OCP_DBL CalKro_Default (const OCP_DBL &Sg, const OCP_DBL &Sw, const OCP_DBL &krog, const OCP_DBL &krow) const
OCP_DBL GetSwco () const override
const vector< OCP_DBL > & GetScm () const override
Public Member Functions inherited from FlowUnit
FlowUnit ()=default
Default constructor.
virtual OCP_DBL GetPcowBySw (const OCP_DBL &sw)=0
Pcow = Po - Pw.
virtual OCP_DBL GetSwByPcow (const OCP_DBL &pcow)=0
virtual OCP_DBL GetPcgoBySg (const OCP_DBL &sg)=0
Pcgo = Pg - Po.
virtual OCP_DBL GetSgByPcgo (const OCP_DBL &pcgo)=0
virtual OCP_DBL GetSwByPcgw (const OCP_DBL &pcgw)=0
Pcgw = Pg - Pw.
virtual OCP_DBL GetSwco () const =0
virtual const vector< OCP_DBL > & GetScm () const =0
virtual void CalKrPc (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp)=0
calculate relative permeability and capillary pressure.
virtual void CalKrPcDeriv (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, OCP_DBL *dkrdS, OCP_DBL *dPcjdS, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp)=0
Additional Inherited Members
Protected Attributes inherited from FlowUnit_ODGW01
OCPTable SGOF
saturation table about gas and oil.
OCPTable SWOF
saturation table about water and oil.
vector< OCP_DBL > data
container used to store the results of values of interpolation.
vector< OCP_DBL > cdata
container used to store the results of slopes of interpolation.
OCPTable SWPCGW
Protected Attributes inherited from FlowUnit_ODGW
OCP_DBL kroMax
oil relative permeability in the presence of connate water only, used in stone2
OCP_DBL Swco
Saturation of connate water.
vector< OCP_DBL > Scm
critical saturation when phase becomes mobile / immobile
Detailed Description
Definition at line 241 of file FlowUnit.hpp.
Constructor & Destructor Documentation
FlowUnit_ODGW01_Miscible()
FlowUnit_ODGW01_Miscible::FlowUnit_ODGW01_Miscible (const ParamReservoir & rs_param, const USI & i) inline
Definition at line 244 of file FlowUnit.hpp.
                                                                           :
        FlowUnit_ODGW01(rs_param, i){
        // gas is mobilable all the time
        Scm[1] = 0;
        USI len = rs_param.miscstr.surTenRef.size();
        if (len > 0) {
            surTenRef = rs_param.miscstr.surTenRef[0];
            surTenPc = 1;
            if (len > 2) {
                surTenPc = rs_param.miscstr.surTenRef[2] / surTenRef;
            }
        }
        else {
            OCP_ABORT("No data in MISCSTR!");
        }
    }
Member Function Documentation
CalKrPc()
void FlowUnit_ODGW01_Miscible::CalKrPc (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out, const OCP_DBL & MySurTen, OCP_DBL & MyFk, OCP_DBL & MyFp) override virtual
calculate relative permeability and capillary pressure.
Reimplemented from FlowUnit_ODGW01.
Definition at line 342 of file FlowUnit.cpp.
{
    surTen = MySurTen;
    if (surTen >= surTenRef || surTen < TINY) {
        MyFk = 1; MyFp = 1;
        FlowUnit_ODGW01::CalKrPc(S_in, kr_out, pc_out, surTen, surTen, surTen);
    }
    else {
        OCP_DBL So = S_in[0];
        OCP_DBL Sg = S_in[1];
        OCP_DBL Sw = S_in[2];
        Fk = min(1.0, pow(surTen / surTenRef, Fkexp));
        Fp = min(surTenPc, surTen / surTenRef);
        SWOF.Eval_All(0, Sw, data, cdata);
        const OCP_DBL krw = data[1];
        OCP_DBL krow = data[2];
        const OCP_DBL Pcwo = -data[3];
        SGOF.Eval_All(0, Sg, data, cdata);
        OCP_DBL krg = data[1];
        OCP_DBL krog = data[2];
        const OCP_DBL Pcgo = data[3] * Fp;
        OCP_DBL kro = CalKro_Stone2(krow, krog, krw, krg);
        // OCP_DBL kro = CalKro_Default(Sg, Sw, krog, krow);
        OCP_DBL krgt = SGOF.Eval(0, (1 - Sw), 1);
        OCP_DBL krh = 0.5 * (krow + krgt);
        // from CMG, see *SIGMA
        kro = Fk * kro + (1 - Fk) * krh * So / (1 - Sw);
        krg = Fk * krg + (1 - Fk) * krh * Sg / (1 - Sw);
        kr_out[0] = kro;
        kr_out[1] = krg;
        kr_out[2] = krw;
        pc_out[0] = 0;
        pc_out[1] = Pcgo;
        pc_out[2] = Pcwo;
        MyFk = Fk;
        MyFp = Fp;
        // cout << Fk << endl;
    }
}
References FlowUnit_ODGW01::CalKrPc(), FlowUnit_ODGW01::cdata, FlowUnit_ODGW01::data, OCPTable::Eval(), OCPTable::Eval_All(), FlowUnit_ODGW01::SGOF, FlowUnit_ODGW01::SWOF, and TINY.
CalKrPcDeriv()
void FlowUnit_ODGW01_Miscible::CalKrPcDeriv (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out, OCP_DBL * dkrdS, OCP_DBL * dPcjdS, const OCP_DBL & MySurTen, OCP_DBL & MyFk, OCP_DBL & MyFp) override virtual
Reimplemented from FlowUnit_ODGW01.
Definition at line 392 of file FlowUnit.cpp.
{
    surTen = MySurTen;
    if (surTen >= surTenRef || surTen < TINY) {
        MyFk = 1; MyFp = 1;
        FlowUnit_ODGW01::CalKrPcDeriv(S_in, kr_out, pc_out, dkrdS, dPcjdS, surTen, surTen, surTen);
    }
    else {
        const OCP_DBL So = S_in[0];
        const OCP_DBL Sg = S_in[1];
        const OCP_DBL Sw = S_in[2];
        Fk = min(1.0, pow(surTen / surTenRef, Fkexp));
        Fp = min(surTenPc, surTen / surTenRef);
        SWOF.Eval_All(0, Sw, data, cdata);
        const OCP_DBL krw = data[1];
        const OCP_DBL dKrwdSw = cdata[1];
        const OCP_DBL krow = data[2];
        const OCP_DBL dKrowdSw = cdata[2];
        const OCP_DBL Pcwo = -data[3];
        const OCP_DBL dPcwdSw = -cdata[3];
        SGOF.Eval_All(0, Sg, data, cdata);
        OCP_DBL krg = data[1];
        const OCP_DBL dKrgdSg = cdata[1];
        const OCP_DBL krog = data[2];
        const OCP_DBL dKrogdSg = cdata[2];
        const OCP_DBL Pcgo = data[3] * Fp;
        const OCP_DBL dPcgdSg = cdata[3] * Fp;
        OCP_DBL dKrodSg{ 0 }, dKrodSw{ 0 }, kro{ 0 };
        kro = CalKro_Stone2Der(krow, krog, krw, krg, dKrwdSw, dKrowdSw, dKrgdSg, dKrogdSg,
            dKrodSw, dKrodSg);
        OCP_DBL dkrgd1_Sw = 0;
        const OCP_DBL krgt = SGOF.Eval(0, (1 - Sw), 1, dkrgd1_Sw);
        const OCP_DBL krh = 0.5 * (krow + krgt);
        // from CMG, see *SIGMA
        kro = Fk * kro + (1 - Fk) * krh * So / (1 - Sw);
        krg = Fk * krg + (1 - Fk) * krh * Sg / (1 - Sw);
        kr_out[0] = kro;
        kr_out[1] = krg;
        kr_out[2] = krw;
        pc_out[0] = 0;
        pc_out[1] = Pcgo;
        pc_out[2] = Pcwo;
        OCP_DBL dkrhdSw = 0.5 * (dKrowdSw - dkrgd1_Sw);
        OCP_DBL temp = (1 - Fk) / (1 - Sw) * (krh / (1 - Sw) + dkrhdSw);
        dkrdS[0] = (1 - Fk) * krh / (1 - Sw);
        dkrdS[1] = Fk * dKrodSg;
        dkrdS[2] = Fk * dKrodSw + temp * So;
        dkrdS[3] = 0;
        dkrdS[4] = Fk * dKrgdSg + (1 - Fk) * krh / (1 - Sw);
        dkrdS[5] = temp * Sg;
        dkrdS[6] = 0;
        dkrdS[7] = 0;
        dkrdS[8] = dKrwdSw;
        dPcjdS[0] = 0;
        dPcjdS[1] = 0;
        dPcjdS[2] = 0;
        dPcjdS[3] = 0;
        dPcjdS[4] = dPcgdSg;
        dPcjdS[5] = 0;
        dPcjdS[6] = 0;
        dPcjdS[7] = 0;
        dPcjdS[8] = dPcwdSw;
        MyFk = Fk;
        MyFp = Fp;
        // cout << Fk << endl;
    }
}
The documentation for this class was generated from the following files:
FlowUnit.hpp
FlowUnit.cpp