OpenCAEPoro: OCP_AIMs Class Reference
OCP_AIMs Class Reference
perform AIM in space, that is, some grids will be implicit, others will be explicit at the same time step
#include <OCPFluidMethod.hpp>
Public Member Functions
void Setup (Reservoir &rs, LinearSystem &myLS, const OCPControl &ctrl)
Setup AIMs.
void Prepare (Reservoir &rs, OCP_DBL &dt)
Prepare for Assembling matrix.
void AssembleMat (LinearSystem &myLS, const Reservoir &rs, const OCP_DBL &dt)
Assemble Matrix.
void SolveLinearSystem (LinearSystem &myLS, Reservoir &rs, OCPControl &ctrl)
Solve the linear system.
bool UpdateProperty (Reservoir &rs, OCPControl &ctrl)
Update properties of fluids.
bool FinishNR (Reservoir &rs, OCPControl &ctrl)
Finish a Newton-Raphson iteration.
void FinishStep (Reservoir &rs, OCPControl &ctrl)
Finish a time step.
Detailed Description
perform AIM in space, that is, some grids will be implicit, others will be explicit at the same time step
Definition at line 124 of file OCPFluidMethod.hpp.
Member Function Documentation
AssembleMat()
void OCP_AIMs::AssembleMat (LinearSystem & myLS, const Reservoir & rs, const OCP_DBL & dt)
Assemble Matrix.
Definition at line 730 of file OCPFluidMethod.cpp.
{
    rs.AssembleMatAIMs(myLS, resFIM.res, dt);
    myLS.AssembleRhs(resFIM.res);
}
References Reservoir::AssembleMatAIMs(), and LinearSystem::AssembleRhs().
FinishNR()
bool OCP_AIMs::FinishNR (Reservoir & rs, OCPControl & ctrl)
Finish a Newton-Raphson iteration.
Definition at line 797 of file OCPFluidMethod.cpp.
{
    OCP_DBL NRdPmax = rs.GetNRdPmax();
    OCP_DBL NRdSmax = rs.GetNRdSmaxP();
#ifdef _DEBUG
     cout << "### DEBUG: Residuals = " << setprecision(3) << scientific << resFIM.maxRelRes0_v << "  "
        << resFIM.maxRelRes_v << "  " << resFIM.maxRelRes_mol << "  " << NRdSmax
        << "  " << NRdPmax << endl;
#endif
    if (ctrl.iterNR > ctrl.ctrlNR.maxNRiter) {
        ctrl.current_dt *= ctrl.ctrlTime.cutFacNR;
        rs.ResetValAIM();
        rs.CalResAIMs(resFIM, ctrl.current_dt);
        resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
        ctrl.ResetIterNRLS();
        cout << "### WARNING: NR not fully converged! Cut time stepsize and repeat!\n";
        return false;
    }
    if (resFIM.maxRelRes_v <= resFIM.maxRelRes0_v * ctrl.ctrlNR.NRtol ||
        resFIM.maxRelRes_v <= ctrl.ctrlNR.NRtol ||
        resFIM.maxRelRes_mol <= ctrl.ctrlNR.NRtol ||
        (NRdPmax <= ctrl.ctrlNR.NRdPmin && NRdSmax <= ctrl.ctrlNR.NRdSmin)) {
        OCP_INT flagCheck = rs.CheckP(false, true);
#if DEBUG
        if (flagCheck > 0) {
            cout << ">> Switch well constraint: Case " << flagCheck << endl;
        }
#endif
        switch (flagCheck) {
        case 1:
            ctrl.current_dt *= ctrl.ctrlTime.cutFacNR;
            rs.ResetValAIM();
            rs.CalResAIMs(resFIM, ctrl.current_dt);
            resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
            ctrl.ResetIterNRLS();
            return false;
        case 2:
            ctrl.current_dt /= 1;
            rs.ResetValAIM();
            rs.CalResAIMs(resFIM, ctrl.current_dt);
            resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
            ctrl.ResetIterNRLS();
            return false;
        default:
            break;
        }
        // Mass Conserve
        rs.bulk.InFIMNi();
        rs.conn.MassConserveIMPEC(rs.bulk, ctrl.current_dt);
        rs.bulk.OutFIMNi();
        if (!rs.CheckNi()) {
            ctrl.current_dt *= ctrl.ctrlTime.cutFacNR;
            rs.ResetValAIM();
            rs.CalResAIMs(resFIM, ctrl.current_dt);
            resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
            cout << "Cut time stepsize and repeat!\n";
            return false;
        }
        if (!rs.CheckVe(0.01)) {
            // cout << ctrl.GetCurTime() << "Days" << "=======" << endl;
            rs.AddFIMBulk();
            rs.SetupFIMBulkBoundAIMs();
            rs.bulk.ShowFIMBulk();
            // Calculate Resiual
            rs.CalResAIMs(resFIM, ctrl.current_dt);
            resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
            // Calculat property of FIM Bulk
            rs.CalFlashDerivAIM(true);
            rs.CalKrPcDerivAIM(true);
            // Store particular property of FIM Bulk
            rs.bulk.UpdateLastStepAIM();
            // ctrl.current_dt /= 2;
            rs.ResetValAIM();
            ctrl.ResetIterNRLS();
            cout << "Cut time stepsize and repeat!  --  02\n";
            return false;
        }
        OCP_DBL cfl = rs.CalCFLAIM(ctrl.current_dt);
        if (cfl > 1) {
            cout << "CFL is too big" << endl;
            ctrl.current_dt /= 2;
            rs.ResetValAIM();
            ctrl.ResetIterNRLS();
            return false;
        }
        return true;
    }
    else {
        return false;
    }
}
References Reservoir::CalFlashDerivAIM(), Reservoir::CalKrPcDerivAIM(), Reservoir::CalResAIMs(), Reservoir::CheckNi(), Reservoir::CheckP(), Reservoir::CheckVe(), ControlTime::cutFacNR, Reservoir::GetNRdPmax(), Reservoir::GetNRdSmaxP(), Bulk::InFIMNi(), BulkConn::MassConserveIMPEC(), ControlNR::maxNRiter, ControlNR::NRdPmin, ControlNR::NRdSmin, ControlNR::NRtol, Bulk::OutFIMNi(), and OCPControl::ResetIterNRLS().
FinishStep()
void OCP_AIMs::FinishStep (Reservoir & rs, OCPControl & ctrl)
Finish a time step.
Definition at line 903 of file OCPFluidMethod.cpp.
{
    // rs.GetNTQT(ctrl.current_dt);
    rs.CalIPRT(ctrl.GetCurDt());
    rs.CalMaxChange();
    rs.UpdateLastStepAIM();
    ctrl.CalNextTstepIMPEC(rs);
    ctrl.UpdateIters();
}
References Reservoir::CalIPRT(), Reservoir::CalMaxChange(), OCPControl::CalNextTstepIMPEC(), OCPControl::GetCurDt(), OCPControl::UpdateIters(), and Reservoir::UpdateLastStepAIM().
Prepare()
void OCP_AIMs::Prepare (Reservoir & rs, OCP_DBL & dt)
Prepare for Assembling matrix.
Definition at line 705 of file OCPFluidMethod.cpp.
{
    // for Well
    rs.PrepareWell();
    rs.CalWellFlux();
    // Set FIM Bulk
    rs.SetupWellBulk();
    rs.SetupFIMBulk();
    rs.SetupFIMBulkBoundAIMs();
    rs.bulk.ShowFIMBulk();
    // Calculate Resiual
    rs.CalResAIMs(resFIM, dt);
    resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
    // Calculat property of FIM Bulk
    rs.CalFlashDerivAIM(true);
    rs.CalKrPcDerivAIM(true);
    // Store particular property of FIM Bulk
    rs.bulk.UpdateLastStepAIM();
}
References Reservoir::CalFlashDerivAIM(), Reservoir::CalKrPcDerivAIM(), Reservoir::CalResAIMs(), Reservoir::CalWellFlux(), Reservoir::PrepareWell(), and Reservoir::SetupFIMBulk().
Setup()
void OCP_AIMs::Setup (Reservoir & rs, LinearSystem & myLS, const OCPControl & ctrl)
Setup AIMs.
Definition at line 692 of file OCPFluidMethod.cpp.
{
    // Allocate Memory of auxiliary variables for AIMt
    rs.AllocateAuxAIMs();
    // Allocate Memory of Matrix for FIM
    rs.AllocateMatFIM(myLS);
    // Allocate memory for resiual of FIM
    OCP_USI num = (rs.GetBulkNum() + rs.GetWellNum()) * (rs.GetComNum() + 1);
    resFIM.res.resize(num);
    myLS.SetupLinearSolver(VECTORFASP, ctrl.GetWorkDir(), ctrl.GetLsFile());
}
References Reservoir::AllocateAuxAIMs(), Reservoir::AllocateMatFIM(), Reservoir::GetBulkNum(), Reservoir::GetComNum(), OCPControl::GetLsFile(), Reservoir::GetWellNum(), OCPControl::GetWorkDir(), LinearSystem::SetupLinearSolver(), and VECTORFASP.
SolveLinearSystem()
void OCP_AIMs::SolveLinearSystem (LinearSystem & myLS, Reservoir & rs, OCPControl & ctrl)
Solve the linear system.
Definition at line 736 of file OCPFluidMethod.cpp.
{
#ifdef _DEBUG
    myLS.CheckEquation();
#endif // DEBUG
    myLS.AssembleMatLinearSolver();
    GetWallTime Timer;
    Timer.Start();
    int status = myLS.Solve();
    if (status < 0) {
        status = myLS.GetNumIters();
    }
    // cout << "LS step = " << status << endl;
#ifdef DEBUG
    myLS.OutputLinearSystem("testA.out", "testb.out");
    myLS.OutputSolution("testx.out");
    myLS.CheckSolution();
#endif // DEBUG
    ctrl.UpdateTimeLS(Timer.Stop() / 1000);
    ctrl.UpdateIterLS(status);
    ctrl.UpdateIterNR();
    rs.GetSolutionAIMs(myLS.GetSolution(), ctrl.ctrlNR.NRdPmax, ctrl.ctrlNR.NRdSmax);
    // rs.GetSolution01FIM(myLS.GetSolution());
    // rs.PrintSolFIM(ctrl.workDir + "testPNi.out");
    myLS.ClearData();
}
References LinearSystem::AssembleMatLinearSolver(), LinearSystem::CheckEquation(), LinearSystem::CheckSolution(), LinearSystem::ClearData(), LinearSystem::GetNumIters(), LinearSystem::GetSolution(), ControlNR::NRdPmax, ControlNR::NRdSmax, LinearSystem::OutputLinearSystem(), LinearSystem::OutputSolution(), LinearSystem::Solve(), GetWallTime::Start(), GetWallTime::Stop(), OCPControl::UpdateIterLS(), OCPControl::UpdateIterNR(), and OCPControl::UpdateTimeLS().
UpdateProperty()
bool OCP_AIMs::UpdateProperty (Reservoir & rs, OCPControl & ctrl)
Update properties of fluids.
Definition at line 768 of file OCPFluidMethod.cpp.
{
    OCP_DBL& dt = ctrl.current_dt;
    // Second check: Ni check and bulk Pressure check
    if (!rs.CheckNi() || rs.CheckP(true, false) != 0) {
        dt *= ctrl.ctrlTime.cutFacNR;
        rs.ResetValAIM();
        rs.CalResAIMs(resFIM, dt);
        resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
        cout << "Cut time stepsize and repeat!  --  01\n";
        return false;
    }
    // Update reservoir properties
    rs.CalFlashIMPEC();
    rs.CalKrPc();
    rs.CalFlashDerivAIM(true);
    rs.CalKrPcDerivAIM(true);
    rs.CalVpore();
    rs.CalFLuxIMPEC();
    rs.CalWellTrans();
    rs.CalWellFlux();
    rs.CalConnFluxIMPEC();
    rs.CalResAIMs(resFIM, dt);
    return true;
}
References Reservoir::CalConnFluxIMPEC(), Reservoir::CalFlashDerivAIM(), Reservoir::CalFlashIMPEC(), Reservoir::CalFLuxIMPEC(), Reservoir::CalKrPc(), Reservoir::CalKrPcDerivAIM(), Reservoir::CalResAIMs(), Reservoir::CalVpore(), Reservoir::CalWellFlux(), Reservoir::CalWellTrans(), Reservoir::CheckNi(), Reservoir::CheckP(), and ControlTime::cutFacNR.
The documentation for this class was generated from the following files:
OCPFluidMethod.hpp
OCPFluidMethod.cpp