OpenCAEPoro: EoSparam Class Reference
EoSparam Class Reference
EoSParam contains the params for Compositional Model and functions to read them.
#include <ParamReservoir.hpp>
Public Member Functions
void InitEoSparam ()
Init Params.
void InputNCNP (ifstream &ifs)
Input the num of hydrocarbon components and hydrocarbon phases.
void InputZI (ifstream &ifs)
Input the initial moles fraction of hydrocarbon components.
void InputCOM (ifstream &ifs)
Input the information of components.
void InputCOMPONENTS (ifstream &ifs, const string &keyword)
Input the information of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > * FindPtr (const string &varName)
void InputCNAMES (ifstream &ifs)
Input the names of hydrocarbon components.
void InputLBCCOEF (ifstream &ifs)
Input LBC coefficients for viscosity calculation.
void InputBIC (ifstream &ifs)
Input the Binary interaction of components.
void InputSSMSTA (ifstream &ifs)
TODO: Add Doxygen.
void InputNRSTA (ifstream &ifs)
TODO: Add Doxygen.
void InputSSMSP (ifstream &ifs)
TODO: Add Doxygen.
void InputNRSP (ifstream &ifs)
TODO: Add Doxygen.
void InputRR (ifstream &ifs)
TODO: Add Doxygen.
Public Attributes
USI NTPVT {0}
num of EoS region
USI numComp {0}
num of components, water is excluded.
USI numPhase {0}
num of phase, water is excluded.
vector< OCP_DBL > zi
molar fraction of components in initial reservoir, water is excluded.
vector< vector< string > > COM
Components information.
vector< string > Cname
Name of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > Tc
Critical temperature of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > Pc
Critical pressure of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > Vc
Critical volume of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > Zc
Critical Z-factor of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > MW
Molecular Weight of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > Acf
Acentric factor of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > OmegaA
OMEGA_A of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > OmegaB
OMEGA_B of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > Vshift
Volume shift of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > Parachor
PARACHOR of hydrocarbon components.
Type_A_r< vector< OCP_DBL > > Vcvis
Critical volume used for viscosity calculations only.
Type_A_r< vector< OCP_DBL > > Zcvis
Critical Z-factor used for viscosity calculations only.
vector< OCP_DBL > LBCcoef
LBC coefficients for viscosity calculation.
vector< vector< OCP_DBL > > BIC
Binary interaction.
vector< string > SSMparamSTA
Params for Solving Phase Spliting with SSM.
vector< string > NRparamSTA
Params for Solving Phase Spliting with NR.
vector< string > SSMparamSP
Params for Solving Phase Spliting with SSM.
vector< string > NRparamSP
Params for Solving Phase Spliting with NR.
vector< string > RRparam
Params for Solving Rachford-Rice equations.
Detailed Description
EoSParam contains the params for Compositional Model and functions to read them.
Definition at line 65 of file ParamReservoir.hpp.
Member Function Documentation
FindPtr()
Type_A_r< vector< OCP_DBL > > * EoSparam::FindPtr (const string & varName)
Find corresponding variable according to the name of variable. It is used for the basic properties of hydrocarbon components such as TCRIT
Definition at line 798 of file ParamReservoir.cpp.
{
    Type_A_r<vector<OCP_DBL>>* myPtr = nullptr;
    switch (Map_Str2Int(&varName[0], varName.size()))
    {
    case Map_Str2Int("TCRIT", 5):
        myPtr = &Tc;
        break;
    case Map_Str2Int("PCRIT", 5):
        myPtr = &Pc;
        break;
    case Map_Str2Int("VCRIT", 5):
        myPtr = &Vc;
        break;
    case Map_Str2Int("ZCRIT", 5):
        myPtr = &Zc;
        break;
    case Map_Str2Int("MW", 2):
        myPtr = &MW;
        break;
    case Map_Str2Int("ACF", 3):
        myPtr = &Acf;
        break;
    case Map_Str2Int("OMEGAA", 6):
        myPtr = &OmegaA;
        break;
    case Map_Str2Int("OMEGAB", 6):
        myPtr = &OmegaB;
        break;
    case Map_Str2Int("SSHIFT", 6):
        myPtr = &Vshift;
        break;
    case Map_Str2Int("PARACHOR", 6):
        myPtr = &Parachor;
        break;
    case Map_Str2Int("VCRITVIS", 8):
        myPtr = &Vcvis;
        break;
    case Map_Str2Int("ZCRITVIS", 8):
        myPtr = &Zcvis;
        break;
    }
    return myPtr;
}
References Acf, Map_Str2Int(), MW, OmegaA, OmegaB, Parachor, Pc, Tc, Vc, Vcvis, Vshift, Zc, and Zcvis.
InitEoSparam()
void EoSparam::InitEoSparam ()
Init Params.
Definition at line 719 of file ParamReservoir.cpp.
{
    // Init LBC coefficient
    LBCcoef.resize(5);
    LBCcoef[0] = 0.1023;
    LBCcoef[1] = 0.023364;
    LBCcoef[2] = 0.058533;
    LBCcoef[3] = -0.040758;
    LBCcoef[4] = 0.0093324;
}
References LBCcoef.
InputBIC()
void EoSparam::InputBIC (ifstream & ifs)
Input the Binary interaction of components.
Input Binary Interaction Coefficients Matrix.
Definition at line 945 of file ParamReservoir.cpp.
{
    OCP_ASSERT((numComp > 0) && (NTPVT > 0), "NCNP hasn't been input!");
    BIC.resize(NTPVT);
    vector<string> vbuf;
    USI nReg = 0;
    while (true) {
        ReadLine(ifs, vbuf);
        if (vbuf[0] == "/") {
            nReg++;
            if (nReg >= NTPVT)
                break;
            continue;
        }
        for (auto& v : vbuf) {
            if (v != "/") {
                BIC[nReg].push_back(stod(v));
                cout << setw(10) << BIC[nReg].back();
            }
        }
        cout << endl;
        if (vbuf.back() == "/") {
            nReg++;
            if (nReg >= NTPVT)
                break;
        }
    }
}
References BIC, NTPVT, numComp, OCP_ASSERT, and ReadLine().
InputCNAMES()
void EoSparam::InputCNAMES (ifstream & ifs)
Input the names of hydrocarbon components.
Definition at line 899 of file ParamReservoir.cpp.
{
    OCP_ASSERT(numComp > 0, "NCNP hasn't be input!");
    vector<string> vbuf;
    while (true) {
        ReadLine(ifs, vbuf);
        if (vbuf[0] == "/") {
            break;
        }
        for (auto& v : vbuf) {
            if (v != "/")
                Cname.push_back(v);
        }
        if (vbuf.back() == "/")
            break;
    }
    OCP_FUNCNAME;
    cout << "CNAMES" << endl;
    for (USI i = 0; i < numComp; i++) {
        cout << Cname[i] << "   ";
    }
    cout << endl << endl;
}
References Cname, numComp, OCP_ASSERT, OCP_FUNCNAME, and ReadLine().
InputCOM()
void EoSparam::InputCOM (ifstream & ifs)
Input the information of components.
TODO: Add Doxygen.
Definition at line 764 of file ParamReservoir.cpp.
{
    OCP_ASSERT(numComp > 0, "Wrong NC!");
    COM.resize(numComp);
    USI len = 9;
    vector<string> vbuf;
    for (USI c = 0; c < numComp; c++) {
        COM[c].resize(len);
        ReadLine(ifs, vbuf);
        for (USI i = 0; i < len; i++) {
            COM[c][i] = vbuf[i];
        }
    }
    OCP_FUNCNAME;
    cout << "Name    "
         << "Pc                "
         << "Tc           "
         << "Acentric    "
         << "MW               "
         << "Vc            "
         << "OmegaA          "
         << "OmegaB       "
         << "Shift" << endl;
    for (auto& c : COM) {
        for (auto& item : c) {
            cout << item << "\t";
        }
        cout << endl;
    }
    cout << endl;
}
References COM, numComp, OCP_ASSERT, OCP_FUNCNAME, and ReadLine().
InputCOMPONENTS()
void EoSparam::InputCOMPONENTS (ifstream & ifs, const string & keyword)
Input the information of hydrocarbon components.
Definition at line 858 of file ParamReservoir.cpp.
{
    OCP_ASSERT((numComp > 0) && (NTPVT > 0), "NPNC hasn't be input!");
    Type_A_r<vector<OCP_DBL>>* objPtr = nullptr;
    objPtr = FindPtr(keyword);
    if (objPtr == nullptr) {
        OCP_ABORT("Unknown keyword!");
    }
    objPtr->activity = true;
    vector<string> vbuf;
    vector<OCP_DBL> tmp;
    USI nReg = 0;
    while (true) {
        ReadLine(ifs, vbuf);
        if (vbuf[0] == "/") {
            nReg++;
            objPtr->data.push_back(tmp);
            if (nReg >= NTPVT)
                break;
            tmp.clear();
            continue;
        }
        for (auto& v : vbuf) {
            if (v != "/") {
                tmp.push_back(stod(v));
            }
        }
        if (vbuf.back() == "/") {
            nReg++;
            objPtr->data.push_back(tmp);
            tmp.clear();
            if (nReg >= NTPVT)
                break;
        }
    }
}
References Type_A_r< T >::activity, Type_A_r< T >::data, FindPtr(), NTPVT, numComp, OCP_ABORT, OCP_ASSERT, and ReadLine().
InputLBCCOEF()
void EoSparam::InputLBCCOEF (ifstream & ifs)
Input LBC coefficients for viscosity calculation.
Definition at line 926 of file ParamReservoir.cpp.
{
    vector<string> vbuf;
    ReadLine(ifs, vbuf);
    DealDefault(vbuf);
    for (USI i = 0; i < 5; i++) {
        if (vbuf[i] != "DEFAULT")
        LBCcoef[i] = stod(vbuf[i]);
    }
    OCP_FUNCNAME;
    cout << "LBCCOEF" << endl;
    for (USI i = 0; i < 5; i++) {
        cout << LBCcoef[i] << "   ";
    }
    cout << endl << endl;
}
References DealDefault(), LBCcoef, OCP_FUNCNAME, and ReadLine().
InputNCNP()
void EoSparam::InputNCNP (ifstream & ifs)
Input the num of hydrocarbon components and hydrocarbon phases.
TODO: Add Doxygen.
Definition at line 732 of file ParamReservoir.cpp.
{
    vector<string> vbuf;
    ReadLine(ifs, vbuf);
    numComp  = stoi(vbuf[0]);
    numPhase = stoi(vbuf[1]);
    OCP_FUNCNAME;
    cout << "NC = " << numComp << "   NPmax = " << numPhase << endl << endl;
    InitEoSparam();
}
References InitEoSparam(), numComp, numPhase, OCP_FUNCNAME, and ReadLine().
InputNRSP()
void EoSparam::InputNRSP (ifstream & ifs)
TODO: Add Doxygen.
Definition at line 1023 of file ParamReservoir.cpp.
{
    vector<string> vbuf;
    ReadLine(ifs, vbuf);
    for (USI i = 0; i < 2; i++) {
        NRparamSP.push_back(vbuf[i]);
    }
    OCP_FUNCNAME;
    for (USI i = 0; i < 2; i++) {
        cout << NRparamSP[i] << "   ";
    }
    cout << endl << endl;
}
References OCP_FUNCNAME, and ReadLine().
InputNRSTA()
void EoSparam::InputNRSTA (ifstream & ifs)
TODO: Add Doxygen.
Definition at line 993 of file ParamReservoir.cpp.
{
    vector<string> vbuf;
    ReadLine(ifs, vbuf);
    for (USI i = 0; i < 2; i++) {
        NRparamSTA.push_back(vbuf[i]);
    }
    OCP_FUNCNAME;
    for (USI i = 0; i < 2; i++) {
        cout << NRparamSTA[i] << "   ";
    }
    cout << endl << endl;
}
References OCP_FUNCNAME, and ReadLine().
InputRR()
void EoSparam::InputRR (ifstream & ifs)
TODO: Add Doxygen.
Definition at line 1038 of file ParamReservoir.cpp.
{
    vector<string> vbuf;
    ReadLine(ifs, vbuf);
    for (USI i = 0; i < 2; i++) {
        RRparam.push_back(vbuf[i]);
    }
    OCP_FUNCNAME;
    for (USI i = 0; i < 2; i++) {
        cout << RRparam[i] << "   ";
    }
    cout << endl << endl;
}
References OCP_FUNCNAME, and ReadLine().
InputSSMSP()
void EoSparam::InputSSMSP (ifstream & ifs)
TODO: Add Doxygen.
Definition at line 1008 of file ParamReservoir.cpp.
{
    vector<string> vbuf;
    ReadLine(ifs, vbuf);
    for (USI i = 0; i < 2; i++) {
        SSMparamSP.push_back(vbuf[i]);
    }
    OCP_FUNCNAME;
    for (USI i = 0; i < 2; i++) {
        cout << SSMparamSP[i] << "   ";
    }
    cout << endl << endl;
}
References OCP_FUNCNAME, and ReadLine().
InputSSMSTA()
void EoSparam::InputSSMSTA (ifstream & ifs)
TODO: Add Doxygen.
Definition at line 977 of file ParamReservoir.cpp.
{
    vector<string> vbuf;
    ReadLine(ifs, vbuf);
    int len = vbuf.size();
    for (USI i = 0; i < len; i++) {
        SSMparamSTA.push_back(vbuf[i]);
    }
    OCP_FUNCNAME;
    for (USI i = 0; i < len; i++) {
        cout << SSMparamSTA[i] << "   ";
    }
    cout << endl << endl;
}
References OCP_FUNCNAME, and ReadLine().
InputZI()
void EoSparam::InputZI (ifstream & ifs)
Input the initial moles fraction of hydrocarbon components.
TODO: Add Doxygen.
Definition at line 745 of file ParamReservoir.cpp.
{
    OCP_ASSERT(numComp > 0, "Wrong NC!");
    vector<string> vbuf;
    ReadLine(ifs, vbuf);
    zi.resize(numComp);
    for (USI i = 0; i < numComp; i++) {
        zi[i] = stod(vbuf[i]);
    }
    OCP_FUNCNAME;
    cout << "Init Zi" << endl;
    for (USI i = 0; i < numComp; i++) {
        cout << zi[i] << "   ";
    }
    cout << endl << endl;
}
References numComp, OCP_ASSERT, OCP_FUNCNAME, ReadLine(), and zi.
Member Data Documentation
Acf
Type_A_r<vector<OCP_DBL> > EoSparam::Acf
Acentric factor of hydrocarbon components.
Definition at line 109 of file ParamReservoir.hpp.
BIC
vector<vector<OCP_DBL> > EoSparam::BIC
Binary interaction.
Definition at line 119 of file ParamReservoir.hpp.
Cname
vector<string> EoSparam::Cname
Name of hydrocarbon components.
Definition at line 103 of file ParamReservoir.hpp.
COM
vector<vector<string> > EoSparam::COM
Components information.
Definition at line 102 of file ParamReservoir.hpp.
LBCcoef
vector<OCP_DBL> EoSparam::LBCcoef
LBC coefficients for viscosity calculation.
Definition at line 117 of file ParamReservoir.hpp.
MW
Type_A_r<vector<OCP_DBL> > EoSparam::MW
Molecular Weight of hydrocarbon components.
Definition at line 108 of file ParamReservoir.hpp.
NRparamSP
vector<string> EoSparam::NRparamSP
Params for Solving Phase Spliting with NR.
Definition at line 124 of file ParamReservoir.hpp.
NRparamSTA
vector<string> EoSparam::NRparamSTA
Params for Solving Phase Spliting with NR.
Definition at line 122 of file ParamReservoir.hpp.
NTPVT
USI EoSparam::NTPVT {0}
num of EoS region
Definition at line 97 of file ParamReservoir.hpp.
numComp
USI EoSparam::numComp {0}
num of components, water is excluded.
Definition at line 98 of file ParamReservoir.hpp.
numPhase
USI EoSparam::numPhase {0}
num of phase, water is excluded.
Definition at line 99 of file ParamReservoir.hpp.
OmegaA
Type_A_r<vector<OCP_DBL> > EoSparam::OmegaA
OMEGA_A of hydrocarbon components.
Definition at line 110 of file ParamReservoir.hpp.
OmegaB
Type_A_r<vector<OCP_DBL> > EoSparam::OmegaB
OMEGA_B of hydrocarbon components.
Definition at line 111 of file ParamReservoir.hpp.
Parachor
Type_A_r<vector<OCP_DBL> > EoSparam::Parachor
PARACHOR of hydrocarbon components.
Definition at line 113 of file ParamReservoir.hpp.
Pc
Type_A_r<vector<OCP_DBL> > EoSparam::Pc
Critical pressure of hydrocarbon components.
Definition at line 105 of file ParamReservoir.hpp.
RRparam
vector<string> EoSparam::RRparam
Params for Solving Rachford-Rice equations.
Definition at line 125 of file ParamReservoir.hpp.
SSMparamSP
vector<string> EoSparam::SSMparamSP
Params for Solving Phase Spliting with SSM.
Definition at line 123 of file ParamReservoir.hpp.
SSMparamSTA
vector<string> EoSparam::SSMparamSTA
Params for Solving Phase Spliting with SSM.
Definition at line 121 of file ParamReservoir.hpp.
Tc
Type_A_r<vector<OCP_DBL> > EoSparam::Tc
Critical temperature of hydrocarbon components.
Definition at line 104 of file ParamReservoir.hpp.
Vc
Type_A_r<vector<OCP_DBL> > EoSparam::Vc
Critical volume of hydrocarbon components.
Definition at line 106 of file ParamReservoir.hpp.
Vcvis
Type_A_r<vector<OCP_DBL> > EoSparam::Vcvis
Critical volume used for viscosity calculations only.
Definition at line 115 of file ParamReservoir.hpp.
Vshift
Type_A_r<vector<OCP_DBL> > EoSparam::Vshift
Volume shift of hydrocarbon components.
Definition at line 112 of file ParamReservoir.hpp.
Zc
Type_A_r<vector<OCP_DBL> > EoSparam::Zc
Critical Z-factor of hydrocarbon components.
Definition at line 107 of file ParamReservoir.hpp.
Zcvis
Type_A_r<vector<OCP_DBL> > EoSparam::Zcvis
Critical Z-factor used for viscosity calculations only.
Definition at line 116 of file ParamReservoir.hpp.
zi
vector<OCP_DBL> EoSparam::zi
molar fraction of components in initial reservoir, water is excluded.
Definition at line 101 of file ParamReservoir.hpp.
The documentation for this class was generated from the following files:
ParamReservoir.hpp
ParamReservoir.cpp