OpenCAEPoro: MixtureComp Class Reference
MixtureComp Class Reference
Public Member Functions
OCP_DBL GetErrorPEC () override
OCP_ULL GetSSMSTAiters () override
OCP_ULL GetNRSTAiters () override
OCP_ULL GetSSMSPiters () override
OCP_ULL GetNRSPiters () override
MixtureComp (const ParamReservoir &rs_param, const USI &i)
MixtureComp (const EoSparam &param, const USI &i)
void InitFlash (const OCP_DBL &Pin, const OCP_DBL &Pbbin, const OCP_DBL &Tin, const OCP_DBL *Sjin, const OCP_DBL &Vpore, const OCP_DBL *Ziin) override
flash calculation with saturation of phases.
void Flash (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin, const USI &ftype, const USI &lastNP, const OCP_DBL *lastKs) override
Flash calculation with moles of components.
void CalFlash (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin)
void FlashDeriv (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin, const USI &ftype, const USI &lastNP, const OCP_DBL *lastKs) override
Flash calculation with moles of components and Calculate the derivative.
void FlashDeriv_n (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin, const OCP_DBL *Sjin, const OCP_DBL *xijin, const OCP_DBL *njin, const USI &ftype, const USI *phaseExistin, const USI &lastNP, const OCP_DBL *lastKs) override
OCP_DBL XiPhase (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Ziin) override
OCP_DBL RhoPhase (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Ziin) override
return mass density of phase.
OCP_DBL GammaPhaseO (const OCP_DBL &Pin, const OCP_DBL &Pbbin) override
return gamma of oil phase, gamma equals to mass density times gravity factor.
OCP_DBL GammaPhaseG (const OCP_DBL &Pin) override
return gamma of gas phase, gamma equals to mass density times gravity factor.
OCP_DBL GammaPhaseW (const OCP_DBL &Pin) override
return gamma of water phase, gamma equals to mass density times gravity factor.
OCP_DBL GammaPhaseOG (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Ziin) override
void setPT (const OCP_DBL &p, const OCP_DBL &t)
void setZi (const OCP_DBL *Ziin)
void setZi ()
void setNi (const OCP_DBL *Niin)
void CallId ()
USI GetFtype () override
void CalSurfaceTension ()
OCP_DBL GetSurTen () override
void AllocateEoS ()
void SolEoS (OCP_DBL &ZjT, const OCP_DBL &AjT, const OCP_DBL &BjT) const
void CalAiBi ()
void CalAjBj (OCP_DBL &AjT, OCP_DBL &BjT, const vector< OCP_DBL > &xj) const
void CalAjBj (OCP_DBL &AjT, OCP_DBL &BjT, const OCP_DBL *xj) const
USI CubicRoot (const OCP_DBL &a, const OCP_DBL &b, const OCP_DBL &c, const bool &NTflag=false) const
Result is stored in Ztmp.
void PrintZtmp ()
test
void AllocatePhase ()
void CalFugPhi (vector< OCP_DBL > &phiT, vector< OCP_DBL > &fugT, const vector< OCP_DBL > &xj)
void CalFugPhi (OCP_DBL *phiT, OCP_DBL *fugT, const OCP_DBL *xj)
void CalFugPhi (OCP_DBL *fugT, const OCP_DBL *xj)
void CalFugPhiAll ()
void CalMW ()
void CalVfXiRho ()
void CalSaturation ()
USI FindMWmax ()
void x2n ()
x[j][i] -> n[j][i]
void PrintX ()
void AllocateMethod ()
void PhaseEquilibrium ()
void CalKwilson ()
bool PhaseStable ()
bool StableSSM (const USI &Id)
strict SSM
bool StableSSM01 (const USI &Id)
relaxable SSM
bool StableNR (const USI &Id)
void CalFugXSTA ()
Calculate d ln(Fug) / dx for Y.
void AssembleJmatSTA ()
bool CheckSplit ()
void PhaseSplit ()
void SplitSSM (const bool &flag)
void SplitSSM2 (const bool &flag)
void SplitSSM3 (const bool &flag)
void RachfordRice2 ()
Used when NP = 2.
void RachfordRice3 ()
Used when NP > 2.
void UpdateXRR ()
Update X according to RR.
void SplitNR ()
void CalResSP ()
void CalFugNAll (const bool &Znflag=true)
void PrintFugN ()
void AssembleJmatSP ()
void CalPhiNSTA ()
Calculate d ln phi[i][j] / d n[k][j].
void AssembleSkipMatSTA ()
OCP_DBL CalStepNRsp ()
OCP_SIN GetMinEigenSkip () override
bool GetFlagSkip () override
void AllocateOthers ()
void IdentifyPhase ()
void CopyPhase ()
Copy the basic properties from MixtureComp to Mixture.
void CalViscosity ()
void CalViscoLBC ()
void CalViscoHZYT ()
void CalFugXAll ()
void CalFugPAll (const bool &Zpflag=true)
void CalVjpVfpVfx_partial ()
void CalXiPNX_partial ()
void CalRhoPX_partial ()
void CalMuPX_partial ()
void CalMuPXLBC_partial ()
void CalXiRhoMuPN_pfullx ()
void CaldXsdXpAPI04 ()
void CaldXsdXp04 ()
void CalRhoPNX_full ()
void CalXiPNX_full01 ()
void CalRhoPNX_full01 ()
void CalMuPX_full01 ()
void CalMuPXLBC_full01 ()
void CalVfiVfp_full01 ()
void AssembleMatVfiVfp_full01 ()
void AssembleRhsVfiVfp_full01 ()
void CaldXsdXp01 ()
void CaldXsdXpAPI01 ()
void CalXiPNX_full02 ()
void CalVfiVfp_full02 ()
void AssembleMatVfiVfp_full02 ()
void AssembleRhsVfiVfp_full02 ()
void CaldXsdXpAPI02 ()
void CaldXsdXpAPI02p ()
void CalVjpVfpVfn_partial ()
void CalXiPn_partial ()
void CalRhoPn_partial ()
void CalMuPn_partial ()
void CalMuPnLBC_partial ()
void CalXiRhoMuPN_pfullxn (const bool &xflag=true)
void CaldXsdXpAPI03 ()
void CaldXsdXp03 ()
void CalVfiVfp_full03 ()
void CalKeyDerx ()
void CalKeyDern ()
Public Member Functions inherited from Mixture
void Allocate ()
Allocate memory for common variables for basic class.
virtual void SetPVTW ()
USI GetType () const
return type of mixture.
virtual bool IsEmpty_PVDG () const
Check whether Table PVDG is empty, it will only be used in black oil model.
virtual void InitFlash (const OCP_DBL &Pin, const OCP_DBL &Pbbin, const OCP_DBL &Tin, const OCP_DBL *Sjin, const OCP_DBL &Vpore, const OCP_DBL *Ziin)=0
flash calculation with saturation of phases.
virtual void Flash (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin, const USI &ftype, const USI &lastNP, const OCP_DBL *lastKs)=0
Flash calculation with moles of components.
virtual void FlashDeriv (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin, const USI &ftype, const USI &lastNP, const OCP_DBL *lastKs)=0
Flash calculation with moles of components and Calculate the derivative.
virtual void FlashDeriv_n (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin, const OCP_DBL *Sjin, const OCP_DBL *xijin, const OCP_DBL *njin, const USI &ftype, const USI *phaseExistin, const USI &lastNP, const OCP_DBL *lastKs)=0
virtual OCP_DBL XiPhase (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Ziin)=0
virtual OCP_DBL RhoPhase (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Ziin)=0
return mass density of phase.
virtual OCP_DBL GammaPhaseO (const OCP_DBL &Pin, const OCP_DBL &Pbbin)=0
return gamma of oil phase, gamma equals to mass density times gravity factor.
virtual OCP_DBL GammaPhaseW (const OCP_DBL &Pin)=0
return gamma of water phase, gamma equals to mass density times gravity factor.
virtual OCP_DBL GammaPhaseG (const OCP_DBL &Pin)=0
return gamma of gas phase, gamma equals to mass density times gravity factor.
virtual OCP_DBL GammaPhaseOG (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Ziin)=0
void CheckNi (const OCP_DBL *Ni)
virtual USI GetFtype ()=0
virtual OCP_SIN GetMinEigenSkip ()=0
virtual bool GetFlagSkip ()=0
virtual OCP_DBL GetSurTen ()=0
virtual OCP_DBL GetErrorPEC ()=0
virtual OCP_ULL GetSSMSTAiters ()=0
virtual OCP_ULL GetNRSTAiters ()=0
virtual OCP_ULL GetSSMSPiters ()=0
virtual OCP_ULL GetNRSPiters ()=0
Additional Inherited Members
Protected Attributes inherited from Mixture
USI mixtureType
USI numPhase
num of phases.
USI numCom
num of components.
OCP_DBL P
pressure when flash calculation.
OCP_DBL T
temperature when flash calculation.
vector< OCP_DBL > Ni
moles of component: numCom
vector< bool > phaseExist
existence of phase: numPhase
vector< OCP_DBL > S
saturation of phase: numPhase
vector< OCP_DBL > rho
mass density of phase: numPhase
vector< OCP_DBL > xi
molar density of phase: numPhase
vector< OCP_DBL > xij
vector< OCP_DBL > nj
mole number of phase j
vector< OCP_DBL > mu
viscosity of phase: numPhase
vector< OCP_DBL > v
volume of phase: numPhase;
OCP_DBL vf
volume of total fluids.
OCP_DBL Nt
Total moles of Components.
vector< vector< OCP_DBL > > vji
dvj / dNi, used in 2 hydrocarbon phase in EOS; or dvj / dnij
vector< OCP_DBL > vjp
dvj / dp, used in 2 hydrocarbon phase in EOS
OCP_DBL vfp
vector< OCP_DBL > vfi
vector< OCP_DBL > muP
d mu / dP: numPhase
vector< OCP_DBL > xiP
d xi / dP: numphase
vector< OCP_DBL > rhoP
d rho / dP: numphase
vector< OCP_DBL > muN
d mu[j] / d N[i]: numphase * numCom
vector< OCP_DBL > xiN
d xi[j] / d N[i]: numphase * numCom
vector< OCP_DBL > rhoN
d rho[j] / d N[i]: numphase * numCom
vector< OCP_DBL > mux
d mu[j] / d x[i][j]: numphase * numCom
vector< OCP_DBL > xix
d xi[j] / d x[i][j]: numphase * numCom
vector< OCP_DBL > rhox
d rho[j] / d x[i][j]: numphase * numCom
vector< OCP_DBL > dXsdXp
the derivates of second variables wrt. primary variables
vector< USI > pEnumCom
see pEnumCom in bulk
vector< OCP_DBL > res
residual of a set of equations
OCP_DBL resPc
a precalculated value
vector< OCP_DBL > keyDer
d (xij*xi/mu) / dP or dNk
Detailed Description
Definition at line 127 of file MixtureComp.hpp.
Constructor & Destructor Documentation
MixtureComp() [1/2]
MixtureComp::MixtureComp (const ParamReservoir & rs_param, const USI & i) inline
Definition at line 151 of file MixtureComp.hpp.
                                                              :MixtureComp(rs_param.EoSp, i) {
        mixtureType = EOS_PVTW;
        if (rs_param.PVTW_T.data.size() != 0) {
            PVTW.Setup(rs_param.PVTW_T.data[i]);
            if (rs_param.gravity.activity)
                std_RhoW = RHOW_STD * rs_param.gravity.data[1];
            if (rs_param.density.activity)
                std_RhoW = RHOW_STD;
            std_GammaW = GRAVITY_FACTOR * std_RhoW;
            data.resize(5);
            cdata.resize(5);
        }
    };
MixtureComp() [2/2]
MixtureComp::MixtureComp (const EoSparam & param, const USI & i)
Definition at line 28 of file MixtureComp.cpp.
{
    // if Water don't exist?
    // for Mixture class
    numPhase = param.numPhase + 1;
    numCom   = param.numComp + 1;
    Allocate();
    // for MixtureComp class
    NC    = param.numComp;
    NPmax = param.numPhase;
    zi.resize(NC);
    // comp.resize(NC);
    // for (USI i = 0; i < NC; i++) {
    //  comp[i] = COMP(param.COM[i]);
    //}
    Cname = param.Cname;
    if (param.Tc.activity)
        Tc = param.Tc.data[tar];
    else
        OCP_ABORT("TCRIT hasn't been input!");
    if (param.Pc.activity)
        Pc = param.Pc.data[tar];
    else
        OCP_ABORT("PCRIT hasn't been input!");
    if (param.Vc.activity)
        Vc = param.Vc.data[tar];
    else if (param.Zc.activity) {
        Zc = param.Zc.data[tar];
        Vc.resize(NC);
        for (USI i = 0; i < NC; i++) {
            Vc[i] = 10.73159 * Zc[i] * Tc[i] / Pc[i];
        }
    } else
        OCP_ABORT("VCRIT or ZCRIT hasn't been input!");
    if (param.MW.activity)
        MWC = param.MW.data[tar];
    else
        OCP_ABORT("MW hasn't been input!");
    if (param.Acf.activity)
        Acf = param.Acf.data[tar];
    else
        OCP_ABORT("ACF hasn't been input!");
    if (param.OmegaA.activity)
        OmegaA = param.OmegaA.data[tar];
    else
        OmegaA.resize(NC, 0.457235529);
    if (param.OmegaB.activity)
        OmegaB = param.OmegaB.data[tar];
    else
        OmegaB.resize(NC, 0.077796074);
    if (param.Vshift.activity) {
        Vshift = param.Vshift.data[tar];
        for (USI i = 0; i < NC; i++)
            Vshift[i] *= (GAS_CONSTANT * OmegaB[i] *  Tc[i] / Pc[i]);
    }
    else
        Vshift.resize(NC, 0);
    ParachorAct = true;
    if (param.Parachor.activity)
        Parachor = param.Parachor.data[tar];
    else
        ParachorAct = false;
    if (param.Vcvis.activity)
        Vcvis = param.Vcvis.data[tar];
    else if (param.Zcvis.activity) {
        Zcvis = param.Zcvis.data[tar];
        Vcvis.resize(NC);
        for (USI i = 0; i < NC; i++) {
            Vcvis[i] = GAS_CONSTANT * Zcvis[i] * Tc[i] / Pc[i];
        }
    } else
        Vcvis = Vc;
    LBCcoef = param.LBCcoef;
    for (auto& lbc : LBCcoef) {
        lbc *= 10;
    }
    miscible = param.miscible;
    if (miscible && !ParachorAct) {
        OCP_ABORT("PARACHOR has not been Input!");
    }
    CallId();
    USI len   = NC * NC;
    USI count = 0;
    BIC.resize(len, 0);
    if (param.BIC[tar].size() != len) {
        USI iter = 0;
        for (USI i = 1; i < NC; i++) {
            for (USI j = 0; j < i; j++) {
                BIC[i * NC + j] = param.BIC[tar][iter];
                BIC[j * NC + i] = BIC[i * NC + j];
                iter++;
            }
        }
    } else {
        BIC = param.BIC[tar];
    }
    for (USI i = 0; i < NC; i++) {
        for (USI j = 0; j < NC; j++) {
            cout << setw(10) << BIC[i * NC + j] << "   ";
        }
        cout << endl;
    }
    EoSctrl.SSMsta.maxIt = stoi(param.SSMparamSTA[0]);
    EoSctrl.SSMsta.tol   = stod(param.SSMparamSTA[1]);
    EoSctrl.SSMsta.eYt   = stod(param.SSMparamSTA[2]);
    EoSctrl.SSMsta.tol2  = EoSctrl.SSMsta.tol * EoSctrl.SSMsta.tol;
    EoSctrl.NRsta.maxIt = stoi(param.NRparamSTA[0]);
    EoSctrl.NRsta.tol   = stod(param.NRparamSTA[1]);
    EoSctrl.NRsta.tol2  = EoSctrl.NRsta.tol * EoSctrl.NRsta.tol;
    EoSctrl.SSMsp.maxIt = stoi(param.SSMparamSP[0]);
    EoSctrl.SSMsp.tol   = stod(param.SSMparamSP[1]);
    EoSctrl.SSMsp.tol2  = EoSctrl.SSMsp.tol * EoSctrl.SSMsp.tol;
    EoSctrl.NRsp.maxIt = stoi(param.NRparamSP[0]);
    EoSctrl.NRsp.tol   = stod(param.NRparamSP[1]);
    EoSctrl.NRsp.tol2  = EoSctrl.NRsp.tol * EoSctrl.NRsp.tol;
    EoSctrl.RR.maxIt = stoi(param.RRparam[0]);
    EoSctrl.RR.tol   = stod(param.RRparam[1]);
    EoSctrl.RR.tol2  = EoSctrl.RR.tol * EoSctrl.RR.tol;
    AllocateEoS();
    AllocatePhase();
    AllocateMethod();
    AllocateOthers();
}
Member Function Documentation
AllocateEoS()
void MixtureComp::AllocateEoS ()
Definition at line 582 of file MixtureComp.cpp.
{
    // Allocate Memoery for EoS variables
    Ai.resize(NC);
    Bi.resize(NC);
    Aj.resize(NPmax);
    Bj.resize(NPmax);
    Zj.resize(NPmax);
    Ztmp.resize(3);
    delta1P2 = delta1 + delta2;
    delta1M2 = delta1 - delta2;
    delta1T2 = delta1 * delta2;
}
AllocateMethod()
void MixtureComp::AllocateMethod ()
Definition at line 930 of file MixtureComp.cpp.
{
    Kw.resize(4);
    for (USI i = 0; i < 4; i++) {
        Kw[i].resize(NC);
    }
    Ks.resize(NPmax - 1);
    for (USI i = 0; i < NPmax - 1; i++) {
        Ks[i].resize(NC);
    }
    phiSta.resize(NC);
    fugSta.resize(NC);
    Y.resize(NC);
    di.resize(NC);
    resSTA.resize(NC);
    JmatSTA.resize(NC * NC);
    Ax.resize(NC);
    Bx.resize(NC);
    Zx.resize(NC);
    phiN.resize(NC * NC);
    skipMatSTA.resize(NC * NC);
    eigenSkip.resize(NC);
    leigenWork = 2 * NC + 1;
    eigenWork.resize(leigenWork);
    lKs.resize(NC);
    tmpRR.resize(NC);
    resRR.resize(NPmax - 1);
    resSP.resize(NC * NPmax);
    JmatSP.resize(NC * NC * NPmax * NPmax);
    fugX.resize(NPmax);
    fugN.resize(NPmax);
    Zn.resize(NPmax);
    for (USI j = 0; j < NPmax; j++) {
        fugX[j].resize(NC * NC);
        fugN[j].resize(NC * NC);
        Zn[j].resize(NC);
    }
    An.resize(NC);
    Bn.resize(NC);
    pivot.resize((NC + 1) * NPmax, 1);
    lJmatWork = NC * (NPmax - 1);
    JmatWork.resize(lJmatWork);
    pivot.resize(NPmax * NC + numPhase, 1);
}
AllocateOthers()
void MixtureComp::AllocateOthers ()
Definition at line 2090 of file MixtureComp.cpp.
{
    sqrtMWi.resize(NC);
    for (USI i = 0; i < NC; i++) sqrtMWi[i] = sqrt(MWC[i]);
    muC.resize(NPmax);
    muAux.resize(NPmax);
    for (USI i = 0; i < NPmax; i++) {
        muAux[i].resize(5);
    }
    muAux1I.resize(NC);
    for (USI i = 0; i < NC; i++) {
        muAux1I[i] = 5.4402 * pow(Tc[i], 1.0 / 6) / pow(Pc[i], 2.0 / 3);
    }
    fugP.resize(NPmax);
    for (USI j = 0; j < NPmax; j++) {
        fugP[j].resize(NC);
    }
    Zp.resize(NPmax);
    JmatDer.resize(NPmax * NPmax * (NC + 1) * (NC + 1));
    JmatTmp = JmatDer;
    rhsDer.resize(NPmax * (NC + 1) * (NC + 1));
    xixC.resize(NPmax * NC);
    xiPC.resize(NPmax);
    xiNC.resize(NPmax * NC);
    // new
    JmatDer.resize((numPhase + NPmax * NC) * (numPhase + NPmax * NC));
    JmatTmp = JmatDer;
    rhsDer.resize((numPhase + NPmax * NC) * (numCom + 1 + 1));
}
AllocatePhase()
void MixtureComp::AllocatePhase ()
Definition at line 678 of file MixtureComp.cpp.
{
    // Allocate Memoery for Phase variables
    vC.resize(NPmax);
    nu.resize(NPmax);
    xiC.resize(NPmax);
    rhoC.resize(NPmax);
    MW.resize(NPmax);
    phaseLabel.resize(NPmax);
    x.resize(NPmax);
    phi.resize(NPmax);
    fug.resize(NPmax);
    n.resize(NPmax);
    for (USI j = 0; j < NPmax; j++) {
        x[j].resize(NC);
        phi[j].resize(NC);
        fug[j].resize(NC);
        n[j].resize(NC);
    }
    ln = n;
}
AssembleJmatSP()
void MixtureComp::AssembleJmatSP ()
Definition at line 1938 of file MixtureComp.cpp.
{
    // Dim: (NP-1)*NC
    // Attention that fugNj is sysmetric
    fill(JmatSP.begin(), JmatSP.end(), 0);
    OCP_DBL*       Jtmp = &JmatSP[0];
    const OCP_DBL* fugNp;
    const OCP_DBL* fugNj;
    for (USI j = 0; j < NP - 1; j++) {
        fugNp = &fugN[NP - 1][0];
        fugNj = &fugN[j][0];
        for (USI i = 0; i < NC; i++) {
            // ith components
            for (USI k = 0; k < NC; k++) {
                // kth fugacity
                Jtmp[k] = fugNj[k] + fugNp[k];
            }
            Jtmp += NC * (NP - 1);
            fugNp += NC;
            fugNj += NC;
        }
        Jtmp += NC;
    }
    //cout << endl << "Jmat" << endl;
    //for (USI i = 0; i < NC; i++) {
    //    for (USI j = 0; j < NC; j++) {
    //        cout << scientific << setprecision(6) << JmatSP[i * NC + j] << "   ";
    //    }
    //    cout << endl;
    //}
}
AssembleJmatSTA()
void MixtureComp::AssembleJmatSTA ()
Definition at line 1480 of file MixtureComp.cpp.
{
    vector<OCP_DBL>& fugx = fugX[0];
    fill(JmatSTA.begin(), JmatSTA.end(), 0.0);
    OCP_DBL tmp;
    for (USI i = 0; i < NC; i++) {
        tmp = 0;
        for (USI k = 0; k < NC; k++) {
            tmp += Y[k] * fugx[i * NC + k];
        }
        for (USI j = 0; j < NC; j++) {
            // Symmetric
            // JmatSTA[i * NC + j] = (fugx[i * NC + j] - tmp + delta(i, j) / Y[i]) / Yt;
            JmatSTA[i * NC + j] = (fugx[i * NC + j] - tmp + 1) / Yt;
        }
    }
    // cout << "JmatSTA" << endl;
    // for (USI i = 0; i < NC; i++) {
    //  for (USI k = 0; k < NC; k++) {
    //      cout << JmatSTA[k * NC + i] << "      ";
    //  }
    //  cout << endl;
    //}
}
AssembleMatVfiVfp_full01()
void MixtureComp::AssembleMatVfiVfp_full01 ()
Definition at line 3688 of file MixtureComp.cpp.
{
    fill(JmatDer.begin(), JmatDer.end(), 0.0);
    // Attention 1: JmatDer should be sorted by column
    // Attention 2: d ln fij / d nkj is symetric for each j;
    OCP_DBL* bId = &JmatDer[0];
    for (USI j = 0; j < NP - 1; j++) {
        // for jth phase
        OCP_DBL* fugNj = &fugN[j][0];
        for (USI i = 0; i < NC; i++) {
            // for ith components
            Dcopy(NC, bId, fugNj);
            bId += (NP - 1 - j) * NC;
            bId[i] = 1.0;
            bId += (1 + j) * NC;
            fugNj += NC;
        }
        bId += NC;
    }
    // NP - 1 phase
    bId            = &JmatDer[(NP - 1) * (NP * NC * NC)];
    OCP_DBL* fugNj = &fugN[NP - 1][0];
    for (USI i = 0; i < NC; i++) {
        for (USI j = 0; j < NP - 1; j++) {
            Dcopy(NC, bId, fugNj);
            bId += NC;
        }
        Dscalar((NP - 1) * NC, -1.0, bId - (NP - 1) * NC);
        fugNj += NC;
        bId[i] = 1.0;
        bId += NC;
    }
}
AssembleMatVfiVfp_full02()
void MixtureComp::AssembleMatVfiVfp_full02 ()
Definition at line 3829 of file MixtureComp.cpp.
{
    // NP = 2
    fill(JmatDer.begin(), JmatDer.end(), 0.0);
    // Attention 1: JmatDer should be sorted by column
    // Attention 2: d ln fij / d nkj is symetric for each j;
    OCP_DBL* tmpMat = &JmatDer[0];
    for (USI i = 0; i < NC; i++) {
        for (USI m = 0; m < NC; m++) {
            tmpMat[m] = fugN[0][i * NC + m] + fugN[1][i * NC + m];
        }
        tmpMat += NC;
    }
}
AssembleRhsVfiVfp_full01()
void MixtureComp::AssembleRhsVfiVfp_full01 ()
Definition at line 3722 of file MixtureComp.cpp.
{
    fill(rhsDer.begin(), rhsDer.end(), 0.0);
    OCP_DBL* rhstmp = &rhsDer[0];
    for (USI k = 0; k < NC; k++) {
        // d Nk
        rhstmp[NC * (NP - 1) + k] = 1;
        rhstmp += NP * NC;
    }
    // d P
    for (USI j = 0; j < NP; j++) {
        for (USI i = 0; i < NC; i++) {
            rhstmp[j * NC + i] = fugP[NP - 1][i] - fugP[j][i];
        }
    }
#ifdef OCP_NANCHECK
    if (!CheckNan(rhsDer.size(), &rhsDer[0])) {
        OCP_ABORT("INF or NAN in rhsDer !");
    }
#endif // NANCHECK
}
AssembleRhsVfiVfp_full02()
void MixtureComp::AssembleRhsVfiVfp_full02 ()
Definition at line 3844 of file MixtureComp.cpp.
{
    // NP = 2
    fill(rhsDer.begin(), rhsDer.end(), 0.0);
    OCP_DBL* rhstmp = &rhsDer[0];
    // dP
    for (USI i = 0; i < NC; i++) {
        rhstmp[i] = fugP[1][i] - fugP[0][i];
    }
    rhstmp += NC;
    // dNk
    for (USI k = 0; k < NC; k++) {
        for (USI i = 0; i < NC; i++) {
            rhstmp[i] = fugN[1][k * NC + i]; // d lnfij / d nkj = d lnfkj / d nij
        }
        rhstmp += NC;
    }
}
AssembleSkipMatSTA()
void MixtureComp::AssembleSkipMatSTA ()
Definition at line 2047 of file MixtureComp.cpp.
{
    // Sysmetric Matrix
    // stored by colum
    vector<OCP_DBL>& xj = x[0];
    for (USI i = 0; i < NC; i++) {
        for (USI j = 0; j <= i; j++) {
            skipMatSTA[i * NC + j] = delta(i, j) + sqrt(xj[i] * xj[j]) * phiN[i * NC + j];
            skipMatSTA[j * NC + i] = skipMatSTA[i * NC + j];
        }
    }
/*    cout << endl << "skipMatSTA" << endl;
    for (USI i = 0; i < NC; i++) {
        for (USI j = 0; j < NC; j++) {
            cout << skipMatSTA[i * NC + j] << "   ";
        }
        cout << endl;
    } */
}
CalAiBi()
void MixtureComp::CalAiBi ()
Definition at line 623 of file MixtureComp.cpp.
{
    // Calculate Ai, Bi
    OCP_DBL acf, mwi;
    OCP_DBL Pri, Tri;
    for (USI i = 0; i < NC; i++) {
        acf = Acf[i];
        // PR
        if (acf <= 0.49) {
            mwi = 0.37464 + 1.54226 * acf - 0.26992 * pow(acf, 2);
        } else {
            mwi = 0.379642 + 1.48503 * acf - 0.164423 * pow(acf, 2) +
                  0.016667 * pow(acf, 3);
        }
        Pri   = P / Pc[i];
        Tri   = T / Tc[i];
        Ai[i] = OmegaA[i] * Pri / pow(Tri, 2) * pow((1 + mwi * (1 - sqrt(Tri))), 2);
        Bi[i] = OmegaB[i] * Pri / Tri;
    }
}
CalAjBj() [1/2]
void MixtureComp::CalAjBj (OCP_DBL & AjT, OCP_DBL & BjT, const OCP_DBL * xj) const
Definition at line 662 of file MixtureComp.cpp.
{
    AjT = 0;
    BjT = 0;
    for (USI i1 = 0; i1 < NC; i1++) {
        BjT += Bi[i1] * xj[i1];
        AjT += xj[i1] * xj[i1] * Ai[i1] * (1 - BIC[i1 * NC + i1]);
        for (USI i2 = 0; i2 < i1; i2++) {
            AjT +=
                2 * xj[i1] * xj[i2] * sqrt(Ai[i1] * Ai[i2]) * (1 - BIC[i1 * NC + i2]);
        }
    }
}
CalAjBj() [2/2]
void MixtureComp::CalAjBj (OCP_DBL & AjT, OCP_DBL & BjT, const vector< OCP_DBL > & xj) const
Definition at line 646 of file MixtureComp.cpp.
{
    AjT = 0;
    BjT = 0;
    for (USI i1 = 0; i1 < NC; i1++) {
        BjT += Bi[i1] * xj[i1];
        AjT += xj[i1] * xj[i1] * Ai[i1] * (1 - BIC[i1 * NC + i1]);
        for (USI i2 = 0; i2 < i1; i2++) {
            AjT +=
                2 * xj[i1] * xj[i2] * sqrt(Ai[i1] * Ai[i2]) * (1 - BIC[i1 * NC + i2]);
        }
    }
}
CaldXsdXp01()
void MixtureComp::CaldXsdXp01 ()
Definition at line 3865 of file MixtureComp.cpp.
{
    // NP > 1 in this function
    // only hydrocarbon was considered
    // if water exists, vf, vfp, and S should be updated
    // CalVfiVfp_full01() and CalXiPNX_full01() should be called before
    fill(JmatTmp.begin(), JmatTmp.end(), 0.0);
    OCP_DBL* MTmp = &JmatTmp[0];
    // dF / dXs
    // dFn / dXs
    for (USI i = 0; i < NC; i++) {
        // dFn / dSm
        for (USI m = 0; m < NP; m++) {
            MTmp[m] = vf * xiC[m] * x[m][i];
        }
        MTmp += NP;
        // dFn / dxnm
        for (USI m = 0; m < NP; m++) {
            for (USI n = 0; n < NC; n++) {
                MTmp[n] =
                    vf * S[m] * (xixC[m * NC + n] * x[m][i] + delta(i, n) * xiC[m]);
            }
            MTmp += NC;
        }
    }
    // dFx / dXs
    for (USI j = 0; j < NP; j++) {
        // dFx / dSm
        MTmp += NP;
        // dFx / dxnm, m = j
        MTmp += j * NC;
        for (USI n = 0; n < NC; n++) {
            MTmp[n] = 1.0;
        }
        MTmp += (NP - j) * NC;
    }
    // dFf / dXs
    for (USI j = 0; j < NP - 1; j++) {
        const OCP_DBL* fugXJ  = &fugX[j][0];
        const OCP_DBL* fugXNP = &fugX[NP - 1][0];
        for (USI i = 0; i < NC; i++) {
            // dFf / dSm
            MTmp += NP;
            // dFf / dxnm, m = j or m = np-1
            // m = j
            MTmp += j * NC;
            for (USI n = 0; n < NC; n++) {
                MTmp[n] = fugXJ[n];
            }
            fugXJ += NC;
            // m = np-1
            MTmp += (NP - 1 - j) * NC;
            for (USI n = 0; n < NC; n++) {
                MTmp[n] = -fugXNP[n];
            }
            fugXNP += NC;
            MTmp += NC;
        }
    }
    USI row01 = NP * (NC + 1);
    // USI col01 = row01;
    // cout << "FsXs" << endl;
    // for (USI i = 0; i < row01; i++) {
    //  for (USI j = 0; j < col01; j++) {
    //      cout << JmatTmp[i * row01 + j] << "   ";
    //  }
    //  cout << endl;
    //}
    // Transpose JmatTmp
    USI dim = NP * (NC + 1);
    for (USI i = 0; i < dim; i++) {
        for (USI j = 0; j < dim; j++) {
            JmatDer[i * dim + j] = JmatTmp[j * dim + i];
        }
    }
    // dF / dXp
    // d fij / dP have been calculated in CalVfiVfp_full01() before
    fill(JmatTmp.begin(), JmatTmp.end(), 0.0);
    MTmp = &JmatTmp[0];
    OCP_DBL tmp01;
    OCP_DBL tmp02;
    // dFn / dXp
    for (USI i = 0; i < NC; i++) {
        // dFn / dP
        tmp01 = 0;
        tmp02 = 0;
        for (USI j = 0; j < NP; j++) {
            tmp01 += S[j] * x[j][i] * xiPC[j];
            tmp02 += S[j] * x[j][i] * xiC[j];
        }
        MTmp[0] = -(vf * tmp01 + vfp * tmp02); // in OCP
        // MTmp[0] = -(vf * tmp01); // in PennSim
        MTmp += 1;
        // dFn / dNk
        // in OCP
        for (USI k = 0; k < NC; k++) {
            tmp01 = 0;
            for (USI j = 0; j < NP; j++) {
                tmp01 += S[j] * x[j][i] * xiNC[j * NC + k];
            }
            MTmp[k] = -(vf * tmp01 + vfi[k] * tmp02 - delta(i, k));
        }
        // in PennSim
        // MTmp[i] = 1.0;
        MTmp += NC;
    }
    // dFx / dXp
    MTmp += NP * (NC + 1);
    // dFf / dXp
    const vector<OCP_DBL>& fugPNP = fugP[NP - 1];
    for (USI j = 0; j < NP - 1; j++) {
        const vector<OCP_DBL>& fugPj = fugP[j];
        for (USI i = 0; i < NC; i++) {
            // dFf / dP
            MTmp[0] = -(fugPj[i] - fugPNP[i]);
            MTmp += (NC + 1);
        }
    }
    USI row02 = NP * (NC + 1);
    USI col02 = NC + 1;
    // cout << "FsXp" << endl;
    // for (USI i = 0; i < row02; i++) {
    //  for (USI j = 0; j < col02; j++) {
    //      cout << JmatTmp[i * col02 + j] << "   ";
    //  }
    //  cout << endl;
    //}
    // Transpose JmatTmp
    USI nrhs = NC + 1;
    USI nrow = (NC + 1) * NP;
    for (USI i = 0; i < nrhs; i++) {
        for (USI j = 0; j < nrow; j++) {
            rhsDer[i * nrow + j] = JmatTmp[j * nrhs + i];
        }
    }
    LUSolve(NC + 1, (NC + 1) * NP, &JmatDer[0], &rhsDer[0], &pivot[0]);
    // now in rhsDer: dXs / dP, dXs / dNk
    // print solution
    // cout << "Solution" << endl;
    // for (USI i = 0; i < nrhs; i++) {
    //  for (USI j = 0; j < nrow; j++) {
    //      cout << rhsDer[i * nrow + j] << "    ";
    //  }
    //  cout << endl;
    //}
}
CaldXsdXp03()
void MixtureComp::CaldXsdXp03 ()
Definition at line 4480 of file MixtureComp.cpp.
{
    // p : P, Ni
    // s : S, nij
    fill(JmatTmp.begin(), JmatTmp.end(), 0.0);
    OCP_DBL* MTmp = &JmatTmp[0];
    const USI dim = NP + 1 + NP * NC;
    const OCP_DBL vf2 = vf * vf;
    // -dF / ds
    // -dFf / ds
    for (USI j = 0; j < NP - 1; j++) {
        const OCP_DBL* fugNJ = &fugN[j][0];
        const OCP_DBL* fugNNP = &fugN[NP - 1][0];
        for (USI i = 0; i < NC; i++) {
            // -dFf / dS = 0
            MTmp += (NP + 1);
            // -dFf / dnij
            MTmp += j * NC;
            for (USI k = 0; k < NC; k++) {
                MTmp[k] = -fugNJ[k];
            }
            fugNJ += NC;
            // np-1 phase
            MTmp += (NP - 1 - j) * NC;
            for (USI k = 0; k < NC; k++) {
                MTmp[k] = fugNNP[k];
            }
            fugNNP += NC;
            MTmp += NC;
        }
    }
    // -dFn / ds
    for (USI i = 0; i < NC; i++) {
        // -dFn / dS = 0
        MTmp += (NP + 1);
        // -dFn / dnij
        for (USI j = 0; j < NP; j++) {
            MTmp[i] = 1;
            MTmp += NC;
        }
    }
    // -dFs / ds  ---- Hydroncarbon
    for (USI j = 0; j < NP; j++) {
        const USI j1 = phaseLabel[j];
        // -dFs / dS
        MTmp[j] = -1;
        MTmp += (NP + 1);
        // -dFs / dnkm
        for (USI m = 0; m < NP; m++) {
            const USI m1 = phaseLabel[m];
            if (m1 == j1) {
                for (USI k = 0; k < NC; k++) {
                    MTmp[k] = vji[j1][k] * (vf - v[j1]) / vf2;
                }
            }
            else{
                for (USI k = 0; k < NC; k++) {
                    MTmp[k] = -vji[m1][k] * v[j1] / vf2;
                }
            }
            MTmp += NC;
        }
    }
    // -dFsw / ds
    // -dFsw / dSw
    MTmp[NP] = -1;
    MTmp += (NP + 1);
    // -dFsw / dnkm
    for (USI m = 0; m < NP; m++) {
        const USI m1 = phaseLabel[m];
        for (USI k = 0; k < NC; k++) {
            MTmp[k] = -vji[m1][k] * v[numPhase-1] / vf2;
        }
        MTmp += NC;
    }
    //cout << "dFdS" << endl;
    //cout << scientific << setprecision(1);
    //for (USI i = 0; i < dim; i++) {
    //    for (USI j = 0; j < dim; j++)
    //        cout << JmatTmp[i * dim + j] << " ";
    //    cout << endl;
    //    if (i == dim - 4)
    //        cout << endl;
    //}
    //cout << phaseLabel[0] << "   " << phaseLabel[1] << endl;
    // Transpose JmatTmp
    for (USI i = 0; i < dim; i++) {
        for (USI j = 0; j < dim; j++) {
            JmatDer[i * dim + j] = JmatTmp[j * dim + i];
        }
    }
    fill(JmatTmp.begin(), JmatTmp.end(), 0.0);
    MTmp = &JmatTmp[0];
    // dF / dp
    const USI ncol2 = numCom + 1;
    // dFf / dp
    for (USI j = 0; j < NP - 1; j++) {
        for (USI i = 0; i < NC; i++) {
            MTmp[0] = fugP[j][i] - fugP[NP - 1][i];
            MTmp += ncol2;
        }
    }
    // dFn / dp
    for (USI i = 0; i < NC; i++) {
        MTmp++;
        MTmp[i] = 1;
        MTmp += numCom;
    }
    // dFs / dp   ---- Hydroncarbon
    for (USI j = 0; j < NP; j++) {
        const USI j1 = phaseLabel[j];
        // dFs / dP
        MTmp[0] = (vfp * v[j1] - vjp[j1] * vf) / vf2;
        // dFs / dNh
        MTmp += numCom;
        // dFs / dNw
        MTmp[0] = vfi[numCom - 1] * v[j1] / vf2;
        MTmp++;
    }
    // dFsw / dp
    // dFsw / dP
    MTmp[0] = (vfp * v[numPhase - 1] - vjp[numPhase - 1] * vf) / vf2;
    // dFsw / dNh
    MTmp += numCom;
    // dFsw / dNw
    MTmp[0] = vfi[numCom - 1] * (v[numPhase - 1] - vf) / vf2;
    MTmp++;
    //cout << "dFdp" << endl;
    //cout << scientific << setprecision(3);
    //for (USI i = 0; i < dim; i++) {
    //    for (USI j = 0; j < numCom+1; j++)
    //        cout << JmatTmp[i * (numCom + 1) + j] << "   ";
    //    cout << endl;
    //}
    // Transpose JmatTmp
    const USI nrhs = numCom + 1;
    const USI nrow = NP * NC + NP + 1;
    for (USI i = 0; i < nrhs; i++) {
        for (USI j = 0; j < nrow; j++) {
            rhsDer[i * nrow + j] = JmatTmp[j * nrhs + i];
        }
    }
    // Calculate res
    // resF
    OCP_DBL* myRes = &rhsDer[nrhs * nrow];
    for (USI j = 0; j < NP - 1; j++) {
        const OCP_DBL* fugJ = &fug[j][0];
        const OCP_DBL* fugNP = &fug[NP - 1][0];
        for (USI i = 0; i < NC; i++) {
            myRes[i] = fugJ[i] - fugNP[i];
        }
        myRes += NC;
    }
    // resN
    for (USI i = 0; i < NC; i++) {
        myRes[i] = Ni[i];
        for (USI j = 0; j < NP; j++) {
            myRes[i] -= x[j][i] * nu[j];
        }
    }
    myRes += NC;
    // resS
    for (USI j = 0; j < NP; j++) {
        myRes[j] = S[phaseLabel[j]] - v[phaseLabel[j]] / vf;
    }
    myRes[NP] = S[numPhase - 1] - v[numPhase - 1] / vf;
    //cout << scientific << setprecision(4);
    //cout << "res0" << endl;
    //for (USI i = 0; i < nrow; i++) {
    //    for (USI j = nrhs; j < nrhs + 1; j++) {
    //        cout << setw(12) << rhsDer[j * nrow + i] << "   ";
    //    }
    //    cout << endl;
    //}
    //cout << endl;
    LUSolve(numCom + 1 + 1, nrow, &JmatDer[0], &rhsDer[0], &pivot[0]);
}
CaldXsdXp04()
void MixtureComp::CaldXsdXp04 ()
Definition at line 2673 of file MixtureComp.cpp.
{
    // Wrong Now !
    fill(JmatTmp.begin(), JmatTmp.end(), 0.0);
    OCP_DBL* MTmp = &JmatTmp[0];
    // -dF / dXs
    // -dFn / dXs
    const USI dim = NP + 1 + NP * NC;
    for (USI i = 0; i < NC; i++) {
        // -dFn / dSh
        for (USI m = 0; m < NP; m++) {
            MTmp[m] = vf * xi[phaseLabel[m]] * x[m][i];
        }
        MTmp += NP;
        // -dFn / dSw
        MTmp++;
        // -dFn / dxnm
        for (USI m = 0; m < NP; m++) {
            const USI m1 = phaseLabel[m];
            for (USI n = 0; n < NC; n++) {
                MTmp[n] =
                    vf * S[m1] * (xix[m1 * numCom + n] * x[m][i] + delta(i, n) * xi[m1]);
                for (USI j = 0; j < NP; j++) {
                    MTmp[n] += vji[m1][n] * x[m][i] * S[phaseLabel[j]] * xi[phaseLabel[j]];
                }
            }
            MTmp += NC;
        }
    }
    // -dFnw / dFs
    // -dFnw / dSw
    MTmp[numPhase - 1] = vf * xi[numPhase - 1];
    MTmp += (NP + 1);
    // -dFnw / dxnm
    for (USI m = 0; m < NP; m++) {
        for (USI n = 0; n < NC; n++) {
            MTmp[n] = vji[phaseLabel[m]][n] * xi[numPhase - 1] * S[numPhase - 1];
        }
        MTmp += NC;
    }
    // -dFx / dXs
    for (USI j = 0; j < NP; j++) {
        // -dFx / dSm
        MTmp += (NP + 1);
        // -dFx / dxnm, m = j
        MTmp += j * NC;
        for (USI n = 0; n < NC; n++) {
            MTmp[n] = -1.0;
        }
        MTmp += (NP - j) * NC;
    }
    // -dFf / dXs
    for (USI j = 0; j < NP - 1; j++) {
        const OCP_DBL* fugXJ = &fugX[j][0];
        const OCP_DBL* fugXNP = &fugX[NP - 1][0];
        for (USI i = 0; i < NC; i++) {
            // -dFf / dSm
            MTmp += (NP + 1);
            // -dFf / dxnm, m = j or m = np-1
            // m = j
            MTmp += j * NC;
            for (USI n = 0; n < NC; n++) {
                MTmp[n] = -fugXJ[n];
            }
            fugXJ += NC;
            // m = np-1
            MTmp += (NP - 1 - j) * NC;
            for (USI n = 0; n < NC; n++) {
                MTmp[n] = fugXNP[n];
            }
            fugXNP += NC;
            MTmp += NC;
        }
    }
    cout << endl << "dFdS" << endl;
    cout << scientific << setprecision(1);
    for (USI i = 0; i < dim; i++) {
        for (USI j = 0; j < dim; j++)
            cout << setw(8) << JmatTmp[i * dim + j] << " ";
        cout << endl;
    }
    // Transpose JmatTmp
    for (USI i = 0; i < dim; i++) {
        for (USI j = 0; j < dim; j++) {
            JmatDer[i * dim + j] = JmatTmp[j * dim + i];
        }
    }
    // dF / dXp
    // d fij / dP have been calculated in CalVfiVfp_full01() before
    fill(JmatTmp.begin(), JmatTmp.end(), 0.0);
    MTmp = &JmatTmp[0];
    OCP_DBL tmp01;
    OCP_DBL tmp02;
    USI j1;
    const USI nrhs = numCom + 1;
    const USI nrow = dim;
    // dFn / dXp
    for (USI i = 0; i < NC; i++) {
        // dFn / dP
        tmp01 = 0;
        tmp02 = 0;
        for (USI j = 0; j < NP; j++) {
            j1 = phaseLabel[j];
            tmp01 += S[j1] * x[j][i] * xiP[j1];
            tmp02 += S[j1] * x[j][i] * xi[j1];
        }
        MTmp[0] = -(vf * tmp01 + vfp * tmp02);
        MTmp += 1;
        // dFn / dNk
        MTmp[i] = 1;
        MTmp += NC;
        // dFn / dNw
        MTmp[0] = -vfi[numCom - 1] * tmp02;
        MTmp++;
    }
    // dFnw / dXp
    // dFnw / dP
    MTmp[0] = -S[numPhase - 1] * (vfp * xi[numPhase - 1] + vf * xiP[numPhase - 1]);
    // dFnw / dNw
    MTmp[numCom] = 1 - vfi[numCom - 1] * S[numPhase - 1] * xi[numPhase - 1];
    MTmp += nrhs;
    // dFx / dXp
    MTmp += NP * nrhs;
    // dFf / dXp
    const vector<OCP_DBL>& fugPNP = fugP[NP - 1];
    for (USI j = 0; j < NP - 1; j++) {
        const vector<OCP_DBL>& fugPj = fugP[j];
        for (USI i = 0; i < NC; i++) {
            // dFf / dP
            MTmp[0] = fugPj[i] - fugPNP[i];
            MTmp += nrhs;
        }
    }
    cout << endl << "dFdp" << endl;
    cout << scientific << setprecision(3);
    for (USI i = 0; i < dim; i++) {
        for (USI j = 0; j < numCom+1; j++)
            cout << setw(10) << JmatTmp[i * (numCom + 1) + j] << "   ";
        cout << endl;
    }
    // Transpose JmatTmp
    for (USI i = 0; i < nrhs; i++) {
        for (USI j = 0; j < nrow; j++) {
            rhsDer[i * nrow + j] = JmatTmp[j * nrhs + i];
        }
    }
    LUSolve(nrhs, dim, &JmatDer[0], &rhsDer[0], &pivot[0]);
    cout << setprecision(6);
    cout << endl << "dXsdXp" << endl;
    for (USI i = 0; i < nrow; i++) {
        for (USI j = 0; j < nrhs; j++) {
            cout << setw(13) << rhsDer[j * nrow + i] << "   ";
        }
        cout << endl;
    }
    cout << endl;
}
CaldXsdXpAPI01()
void MixtureComp::CaldXsdXpAPI01 ()
Definition at line 4023 of file MixtureComp.cpp.
{
    // Calculate derivates for hydrocarbon phase and components
    // if water exists, vf, vfp, and S should be updated
    fill(dXsdXp.begin(), dXsdXp.end(), 0.0);
    OCP_DBL vw = v[numPhase - 1];
    OCP_DBL vwp = vjp[numPhase - 1];
    if (NP == 1) {
        USI     bId = (numCom + 1) * phaseLabel[0];
        OCP_DBL tmp = vf * vf;
        // only dSj / dP, dSj / dNk ---- hydrocarbon phase
        dXsdXp[bId] = (vfp * vw - vf * vwp) / tmp;
        for (USI k = 0; k < NC; k++) {
            dXsdXp[bId + k + 1] = (vfi[k] * vw) / tmp;
        }
        // dxij / dNk --- new
        bId = (numCom + 1) * (numPhase + numCom * phaseLabel[0]) + 1;
        for (USI i = 0; i < NC; i++) {
            for (USI k = 0; k < NC; k++) {
                dXsdXp[bId + k] = (delta(i, k) * Nh - Ni[i]) / (Nh * Nh);
            }
            bId += (numCom + 1);
        }
    } else {
        // NP > 1
        // Calculate Saturation
        for (USI j = 0; j < NP; j++) {
            S[j] = vC[j] / vf;
        }
        CalFugXAll();
        CaldXsdXp01();
        // copy from rhsDer to dXsdXp
        OCP_DBL*       DTmp;
        const OCP_DBL* STmp;
        USI            nrow  = NP * (NC + 1); // row num of rhsDer
        USI            ncol  = NC + 1;        // col num of rhsDer
        USI            ncol2 = numCom + 1;    // col num of dXsdXp
        // Saturation
        for (USI j = 0; j < NP; j++) {
            STmp = &rhsDer[j];
            DTmp = &dXsdXp[phaseLabel[j] * ncol2];
            // dS / dP
            DTmp[0] = STmp[0];
            // dS / dNk
            DTmp++;
            for (USI k = 0; k < NC; k++) {
                STmp += nrow;
                DTmp[k] = STmp[0];
            }
            // water is excluded
        }
        // xij ---- mole fraction of component i in phase j
        OCP_DBL* DbId = &dXsdXp[numPhase * ncol2];
        for (USI j = 0; j < NP; j++) {
            DTmp = DbId + phaseLabel[j] * numCom * ncol2;
            for (USI i = 0; i < NC; i++) {
                STmp = &rhsDer[NP + j * NC + i];
                // dxij / dP
                DTmp[0] = STmp[0];
                // dxij / dNk
                DTmp++;
                for (USI k = 0; k < NC; k++) {
                    STmp += nrow;
                    DTmp[k] = STmp[0];
                }
                DTmp += numCom;
                // water is excluded
            }
        }
    }
    // Correct Sj
    CalSaturation();
    USI Wpid = numPhase - 1;
    USI Wcid = numCom - 1;
    // Calculate water derivatives
    // only dSj / dNw, dSw / dP , dSw / dNk needs to be considered
    USI ncol = 1 + numCom;
    // dSj / dNw
    for (USI j = 0; j < NP; j++) {
        dXsdXp[(phaseLabel[j] + 1) * ncol - 1] = -S[phaseLabel[j]] * vfi[Wcid] / vf;
    }
    OCP_DBL* Dtmp = &dXsdXp[Wpid * ncol];
    // dSw / dP
    OCP_DBL vf2 = vf * vf;
    Dtmp[0] = (vwp * vf - vw * vfp) / vf2;
    Dtmp++;
    // dSw / d Nk
    for (USI k = 0; k < NC; k++) {
        Dtmp[k] = -vw * vfi[k] / vf2;
    }
    // dSw / d Nw
    Dtmp[NC] = (vfi[Wcid] * vf - vw * vfi[Wcid]) / vf2;
}
CaldXsdXpAPI02()
void MixtureComp::CaldXsdXpAPI02 ()
Definition at line 4121 of file MixtureComp.cpp.
{
    // Attention!
    // NP = 1 or NP = 2
    // dS / dP
    // S = Sj, xij
    // P = P, Ni
    // water is included
    fill(dXsdXp.begin(), dXsdXp.end(), 0);
    USI ncol = numCom + 1;
    OCP_DBL vf2 = vf * vf;
    OCP_DBL vwp = vjp[numPhase - 1];
    OCP_DBL vw = v[numPhase - 1];
    if (NP == 1) {
        // when NP = 1, vfi = vhi, vfp = vhp + vwp, h = hydrocarbon
        USI j0 = phaseLabel[0];
        OCP_DBL* bId = &dXsdXp[j0 * ncol];
        // dS / dP
        bId[0] = ((vfp - vwp) * vf - vfp * v[j0]) / vf2;
        bId++;
        // dSh / dNm
        for (USI m = 0; m < NC; m++) {
            bId[m] = vfi[m] * vw / vf2;
        }
        bId += NC;
        // dSh / dNw
        bId[0] = -vfi[numCom - 1] * v[j0] / vf2;
        // dSw / dP, dNm
        bId = &dXsdXp[(numPhase - 1) * ncol];
        for (USI m = 0; m < ncol; m++) {
            bId[m] = -dXsdXp[j0 * ncol + m];
        }
        // dxij / dNm
        bId = &dXsdXp[(numPhase + j0 * numCom) * ncol + 1];
        for (USI i = 0; i < NC; i++) {
            for (USI m = 0; m < NC; m++) {
                bId[m] = (delta(i, m) * Nh - Ni[i]) / (Nh * Nh);
            }
            bId += ncol;
        }
    }
    else {
        // NP = 2
        // dSj / dP, dSj / dNm
        OCP_DBL* bId;
        for (USI j = 0; j < 2; j++) {
            const USI j1 = phaseLabel[j];
            bId = &dXsdXp[j1 * ncol];
            // dSj / dP
            bId[0] = (vjp[j1] * vf - vfp * v[j1]) / vf2;
            bId++;
            // dSj / dNm
            for (USI m = 0; m < numCom; m++) {
                bId[m] = (vji[j1][m] * vf - vfi[m] * v[j1]) / vf2;
            }
        }
        // dSw / dP, dSw / dNm
        bId = &dXsdXp[(numPhase - 1) * ncol];
        // dSw / dP
        bId[0] = (vwp * vf - vfp * vw) / vf2;
        bId++;
        // dSw / dNm
        for (USI m = 0; m < numCom; m++) {
            bId[m] = (vji[(numPhase - 1)][m] * vf - vfi[m] * vw) / vf2;
        }
        bId += numCom;
        // dxij / dP, dxij / dNm
        const USI j0 = phaseLabel[0];
        const USI j1 = phaseLabel[1];
        const OCP_DBL* dnkjdNP = &rhsDer[0];
        OCP_DBL* bId1 = bId + j0 * numCom * ncol;
        OCP_DBL* bId2 = bId + j1 * numCom * ncol;
        OCP_DBL njDerSum = 0;
        // dxij / dP
        for (USI i = 0; i < NC; i++)
            njDerSum += dnkjdNP[i];
        for (USI i = 0; i < NC; i++) {
            bId1[0] = (dnkjdNP[i] * nu[0] - njDerSum * Nh * n[0][i]) / (nu[0] * nu[0]);
            bId2[0] = (-dnkjdNP[i] * nu[1] + njDerSum * Nh * n[1][i]) / (nu[1] * nu[1]);
            bId1 += ncol;
            bId2 += ncol;
        }
        dnkjdNP += NC;
        // dxij / dNm
        for (USI m = 0; m < NC; m++) {
            njDerSum = 0;
            for (USI i = 0; i < NC; i++)
                njDerSum += dnkjdNP[i];
            bId1 = bId + j0 * numCom * ncol + m + 1;
            bId2 = bId + j1 * numCom * ncol + m + 1;
            for (USI i = 0; i < NC; i++) {
                bId1[0] = (dnkjdNP[i] * nu[0] - njDerSum * Nh * n[0][i]) / (nu[0] * nu[0]);
                bId2[0] = ((delta(i, m) - dnkjdNP[i]) * nu[1] - (1 - njDerSum) * Nh * n[1][i]) / (nu[1] * nu[1]);
                bId1 += ncol;
                bId2 += ncol;
            }
            dnkjdNP += NC;
        }
    }
}
CaldXsdXpAPI02p()
void MixtureComp::CaldXsdXpAPI02p ()
Definition at line 4227 of file MixtureComp.cpp.
{
    // Attention!
    // NP = 1 or NP = 2
    // water not in oil or gas; hydroncarbon not in water
    // inexist phase will bot be stored
    // only hydrocarbon phases, hydrocarbon components, water phase will be stored
    // dS / dP
    // S = Sj, xij
    // P = P, Ni
    // water is included
    fill(dXsdXp.begin(), dXsdXp.end(), 0);
    USI ncol = numCom + 1;
    OCP_DBL vf2 = vf * vf;
    OCP_DBL vwp = vjp[numPhase - 1];
    OCP_DBL vw = v[numPhase - 1];
    if (NP == 1) {
        // when NP = 1, vfi = vhi, vfp = vhp + vwp, h = hydrocarbon
        const USI j1 = phaseLabel[0];
        OCP_DBL* bId = &dXsdXp[0];
        // dS / dP
        bId[0] = ((vfp - vwp) * vf - vfp * v[j1]) / vf2;
        bId++;
        // dSh / dNm
        for (USI m = 0; m < NC; m++) {
            bId[m] = vfi[m] * vw / vf2;
        }
        bId += NC;
        // dSh / dNw
        bId[0] = -vfi[numCom - 1] * v[j1] / vf2;
        bId++;
        // dSw / dP, dNm
        for (USI m = 0; m < ncol; m++) {
            bId[m] = -dXsdXp[m];
        }
        bId += ncol + 1;
        // dxij / dNm
        for (USI i = 0; i < NC; i++) {
            for (USI m = 0; m < NC; m++) {
                bId[m] = (delta(i, m) * Nh - Ni[i]) / (Nh * Nh);
            }
            bId += ncol;
        }
    }
    else {
        // NP = 2
        // dSj / dP, dSj / dNm
        OCP_DBL* bId;
        for (USI j = 0; j < 2; j++) {
            const USI j1 = phaseLabel[j];
            bId = &dXsdXp[j1 * ncol];
            // dSj / dP
            bId[0] = (vjp[j1] * vf - vfp * v[j1]) / vf2;
            bId++;
            // dSj / dNm
            for (USI m = 0; m < numCom; m++) {
                bId[m] = (vji[j1][m] * vf - vfi[m] * v[j1]) / vf2;
            }
        }
        // dSw / dP, dSw / dNm
        bId = &dXsdXp[(numPhase - 1) * ncol];
        // dSw / dP
        bId[0] = (vwp * vf - vfp * vw) / vf2;
        bId++;
        // dSw / dNm
        for (USI m = 0; m < numCom; m++) {
            bId[m] = (vji[(numPhase - 1)][m] * vf - vfi[m] * vw) / vf2;
        }
        bId += numCom;
        // dxij / dP, dxij / dNm
        const USI j0 = phaseLabel[0];
        const USI j1 = phaseLabel[1];
        const OCP_DBL* dnkjdNP = &rhsDer[0];
        OCP_DBL* bId1 = bId + j0 * NC * ncol;
        OCP_DBL* bId2 = bId + j1 * NC * ncol;
        OCP_DBL njDerSum = 0;
        // dxij / dP
        for (USI i = 0; i < NC; i++)
            njDerSum += dnkjdNP[i];
        for (USI i = 0; i < NC; i++) {
            bId1[0] = (dnkjdNP[i] * nu[0] - njDerSum * Nh * n[0][i]) / (nu[0] * nu[0]);
            bId2[0] = (-dnkjdNP[i] * nu[1] + njDerSum * Nh * n[1][i]) / (nu[1] * nu[1]);
            bId1 += ncol;
            bId2 += ncol;
        }
        dnkjdNP += NC;
        // dxij / dNm
        for (USI m = 0; m < NC; m++) {
            njDerSum = 0;
            for (USI i = 0; i < NC; i++)
                njDerSum += dnkjdNP[i];
            bId1 = bId + j0 * NC * ncol + m + 1;
            bId2 = bId + j1 * NC * ncol + m + 1;
            for (USI i = 0; i < NC; i++) {
                bId1[0] = (dnkjdNP[i] * nu[0] - njDerSum * Nh * n[0][i]) / (nu[0] * nu[0]);
                bId2[0] = ((delta(i, m) - dnkjdNP[i]) * nu[1] - (1 - njDerSum) * Nh * n[1][i]) / (nu[1] * nu[1]);
                bId1 += ncol;
                bId2 += ncol;
            }
            dnkjdNP += NC;
        }
    }
}
CaldXsdXpAPI03()
void MixtureComp::CaldXsdXpAPI03 ()
Definition at line 4337 of file MixtureComp.cpp.
{
    // p : P, Ni
    // s : S, nij
    // water not in oil or gas; hydroncarbon not in water
    // inexist phase will bot be stored
    // only hydrocarbon phases, hydrocarbon components, water phase will be stored
    // water is included
    fill(dXsdXp.begin(), dXsdXp.end(), 0.0);
    fill(res.begin(), res.end(), 0.0);
    resPc = 0;
    const USI ncol = numCom + 1;
    const OCP_DBL vf2 = vf * vf;
    const OCP_DBL vwp = vjp[numPhase - 1];
    const OCP_DBL vw = v[numPhase - 1];
    if (NP == 1) {
        // when NP = 1, vfi = vhi, vfp = vhp + vwp, h = hydrocarbon
        // and vfi = vji
        const USI j0 = phaseLabel[0];
        OCP_DBL* bId = &dXsdXp[0];
        // dS / dP
        bId[0] = ((vfp - vwp) * vf - vfp * v[j0]) / vf2;
        bId++;
        // dSh / dNm
        for (USI m = 0; m < NC; m++) {
            bId[m] = vji[j0][m] * vw / vf2;
        }
        bId += NC;
        // dSh / dNw
        bId[0] = -vfi[numCom - 1] * v[j0] / vf2;
        bId++;
        // dSw / dP, dNm
        for (USI m = 0; m < ncol; m++) {
            bId[m] = -dXsdXp[m];
        }
        // dnij / dNm
        bId = &dXsdXp[2 * ncol + 1];
        for (USI i = 0; i < NC; i++) {
            bId[i] = 1;
            bId += ncol;
        }
        // res = 0
    }
    else {
        CalFugNAll(false);
        CalFugPAll(false);
        CaldXsdXp03();
        // Assemble dXsdXp
        // // inexist phase will bot be stored
        // no d xiw / dP, d xiw / dNk
        // no d xwj / dP, d xwj / dNk
        vector<USI> sIndex(numPhase, 0); // store index
        for (USI j = 0; j < numPhase - 1; j++) {
            if (phaseExist[j]) {
                for (USI j1 = j + 1; j1 < numPhase; j1++) {
                    sIndex[j1]++;
                }
            }
        }
        const OCP_DBL* STmp = &rhsDer[0];
        const USI nrhs = numCom + 1;
        const USI wNP = NP + 1;
        const USI nrow = wNP + NP * NC;
        USI bId;
        for (USI i = 0; i < nrhs; i++) {
            // Sh
            for (USI j = 0; j < NP; j++) {
                dXsdXp[sIndex[phaseLabel[j]] * nrhs + i] = STmp[j];
            }
            STmp += NP;
            // Sw
            dXsdXp[NP * nrhs + i] = STmp[0];
            STmp++;
            // nij
            for (USI j = 0; j < NP; j++) {
                bId = wNP + sIndex[phaseLabel[j]] * NC;
                for (USI k = 0; k < NC; k++) {
                    dXsdXp[(bId + k) * nrhs + i] = STmp[k];
                }
                STmp += NC;
            }
        }
        // res
        // Sh
        for (USI j = 0; j < NP; j++) {
            res[sIndex[phaseLabel[j]]] = STmp[j];
        }
        STmp += NP;
        // Sw
        res[NP] = STmp[0];
        STmp++;
        // nij
        for (USI j = 0; j < NP; j++) {
            bId = wNP + sIndex[phaseLabel[j]] * NC;
            for (USI k = 0; k < NC; k++) {
                res[bId + k] = STmp[k];
            }
            STmp += NC;
        }
        OCP_DBL* myres = &res[NP + 1];
        // precalculate a value
        for (USI j = 0; j < NP; j++) {
            const USI j1 = phaseLabel[j];
            for (USI i = 0; i < NC; i++) {
                resPc += vji[j1][i] * myres[i];
            }
            myres += NC;
        }
        //resPc = 0;
        //fill(res.begin(), res.end(), 0.0);
        //cout << "res1" << endl;
        //for (USI i = 0; i < nrow; i++) {
        //    for (USI j = nrhs; j < nrhs + 1; j++) {
        //        cout << setw(12) << rhsDer[j * nrow + i] << "   ";
        //    }
        //    cout << endl;
        //}
        //cout << endl;
        //cout << "resPc = " << resPc << endl;
    }
#ifdef OCP_NANCHECK
    if (!CheckNan(dXsdXp.size(), &dXsdXp[0]))
    {
        OCP_ABORT("INF or INF in bmat !");
    }
#endif
}
CaldXsdXpAPI04()
void MixtureComp::CaldXsdXpAPI04 ()
Definition at line 2615 of file MixtureComp.cpp.
{
    // Wrong Now !
    // water not in oil or gas; hydroncarbon not in water
    // inexist phase will bot be stored
    // only hydrocarbon phases, hydrocarbon components, water phase will be stored
    // dS / dP
    // S = Sj, xij
    // P = P, Ni
    // water is included
    fill(dXsdXp.begin(), dXsdXp.end(), 0.0);
    fill(res.begin(), res.end(), 0.0);
    resPc = 0;
    const USI ncol = numCom + 1;
    const OCP_DBL vf2 = vf * vf;
    const OCP_DBL vwp = vjp[numPhase - 1];
    const OCP_DBL vw = v[numPhase - 1];
    if (NP == 1) {
        // when NP = 1, vfi = vhi, vfp = vhp + vwp, h = hydrocarbon
        const USI j1 = phaseLabel[0];
        OCP_DBL* bId = &dXsdXp[0];
        // dS / dP
        bId[0] = ((vfp - vwp) * vf - vfp * v[j1]) / vf2;
        bId++;
        // dSh / dNm
        for (USI m = 0; m < NC; m++) {
            bId[m] = vfi[m] * vw / vf2;
        }
        bId += NC;
        // dSh / dNw
        bId[0] = -vfi[numCom - 1] * v[j1] / vf2;
        bId++;
        // dSw / dP, dNm
        for (USI m = 0; m < ncol; m++) {
            bId[m] = -dXsdXp[m];
        }
        bId += ncol + 1;
        // dxij / dNm
        for (USI i = 0; i < NC; i++) {
            for (USI m = 0; m < NC; m++) {
                bId[m] = (delta(i, m) * Nh - Ni[i]) / (Nh * Nh);
            }
            bId += ncol;
        }
        // res = 0
    }
    else {
        CalFugXAll();
        CalFugPAll(false);
        CaldXsdXp04();
    }
}
CalFlash()
void MixtureComp::CalFlash (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Niin)
Definition at line 466 of file MixtureComp.cpp.
{
    setPT(Pin, Tin);
    setNi(Niin);
    nu[0] = 1;
    nu[1] = 0;
    // Water is excluded
    Nh = Dnorm1(NC, &Ni[0]);
    setZi();
    PhaseEquilibrium();
    // Next, nu represents moles of phase instead of molar fraction of phase
    Dscalar(NP, Nh, &nu[0]);
    CalMW();
    CalVfXiRho();
    CalViscosity();
    CalSurfaceTension();
    IdentifyPhase();
    CopyPhase();
}
CalFugNAll()
void MixtureComp::CalFugNAll (const bool & Znflag = true)
Definition at line 1842 of file MixtureComp.cpp.
{
    OCP_DBL C, D, E, G;
    OCP_DBL Cnk, Dnk, Enk, Gnk;
    OCP_DBL tmp, aik;
    for (USI j = 0; j < NP; j++) {
        // j th phase
        vector<OCP_DBL>&       fugn = fugN[j];
        const OCP_DBL&         aj   = Aj[j];
        const OCP_DBL&         bj   = Bj[j];
        const OCP_DBL&         zj   = Zj[j];
        const vector<OCP_DBL>& xj   = x[j];
        vector<OCP_DBL>&       Znj  = Zn[j];
        for (USI i = 0; i < NC; i++) {
            tmp = 0;
            for (USI m = 0; m < NC; m++) {
                tmp += (1 - BIC[i * NC + m]) * sqrt(Ai[i] * Ai[m]) * xj[m];
            }
            An[i] = 2 / nu[j] * (tmp - aj);
            Bn[i] = 1 / nu[j] * (Bi[i] - bj);
            if (Znflag) {
                Znj[i] =
                    ((bj - zj) * An[i] +
                        ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                            ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                            (delta1 + delta2 - 1) * zj * zj) *
                        Bn[i]) /
                    (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                        (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
            }
        }
        G = (zj + delta1 * bj) / (zj + delta2 * bj);
        for (USI i = 0; i < NC; i++) {
            // i th fugacity
            C = xj[i] * P / (zj - bj);
            // D = Bi[i] / bj * (zj - 1);
            tmp = 0;
            for (USI k = 0; k < NC; k++) {
                tmp += (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]) * xj[k];
            }
            E = -aj / ((delta1 - delta2) * bj) * (2 * tmp / aj - Bi[i] / bj);
            for (USI k = 0; k <= i; k++) {
                // k th components
                aik = (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]);
                Cnk = P / (zj - bj) / (zj - bj) *
                      ((zj - bj) / nu[j] * (delta(i, k) - xj[i]) -
                       xj[i] * (Znj[k] - Bn[k]));
                Dnk = Bi[i] / bj * (Znj[k] - (Bi[k] - bj) * (zj - 1) / (nu[j] * bj));
                Gnk = (delta1 - delta2) / ((zj + delta2 * bj) * (zj + delta2 * bj)) *
                      (Bn[k] * zj - Znj[k] * bj);
                /*Enk = 1 / ((delta1 - delta2) * bj * bj) * (An[k] * bj - Bn[k] * aj) *
                   (Bi[i] / bj - 2 * tmp / aj)
                    + aj / ((delta1 - delta2) * bj) * (-Bi[i] / (bj * bj) * Bn[k] - 2 /
                   (aj * aj) * (aj * (aik - tmp) / nu[j] - An[k] * tmp));*/
                Enk = -1 / (delta1 - delta2) / (bj * bj) *
                      (2 * (bj * aik / nu[j] + Bn[k] * (Bi[i] * aj / bj - tmp)) -
                       An[k] * Bi[i] - aj * Bi[i] / nu[j]);
                Enk -= E / nu[j];
                fugn[i * NC + k] = 1 / C * Cnk + Dnk + Enk * log(G) + E / G * Gnk;
                fugn[k * NC + i] = fugn[i * NC + k];
                /*cout << "fnn[" << j << "][" << i << "][" << k << "] = " << fugn[i * NC
                + k]; cout << endl;*/
            }
        }
    }
    // PrintFugN();
#ifdef OCP_NANCHECK
    for (USI j = 0; j < NP; j++) {
        if (!CheckNan(fugN[j].size(), &fugN[j][0]))
        {
            OCP_ABORT("INF or NAN in fugN !");
        }
    }
#endif // NANCHECK
}
CalFugPAll()
void MixtureComp::CalFugPAll (const bool & Zpflag = true)
Definition at line 2308 of file MixtureComp.cpp.
{
    OCP_DBL C, D, E, G;
    OCP_DBL Cp, Dp, Ep, Gp;
    OCP_DBL tmp;
    for (USI j = 0; j < NP; j++) {
        vector<OCP_DBL>& fugp = fugP[j];
        vector<OCP_DBL>& xj   = x[j];
        OCP_DBL&         aj   = Aj[j];
        OCP_DBL&         bj   = Bj[j];
        OCP_DBL&         zj   = Zj[j];
        OCP_DBL Ap = aj / P;
        OCP_DBL Bp = bj / P;
        if (Zpflag) {
            Zp[j] = ((bj - zj) * Ap +
                ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                    ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                    (delta1 + delta2 - 1) * zj * zj) *
                Bp) /
                (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                    (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
        }
        G  = (zj + delta1 * bj) / (zj + delta2 * bj);
        Gp = (delta1 - delta2) / ((zj + delta2 * bj) * (zj + delta2 * bj)) *
             (Bp * zj - Zp[j] * bj);
        for (USI i = 0; i < NC; i++) {
            C = P / (zj - bj);
            // D = Bi[i] / bj * (zj - 1);
            tmp = 0;
            for (USI m = 0; m < NC; m++) {
                tmp += (1 - BIC[i * NC + m]) * sqrt(Ai[i] * Ai[m]) * xj[m];
            }
            E = -aj / ((delta1 - delta2) * bj) * (2 * tmp / aj - Bi[i] / bj);
            Cp = ((zj - bj) - P * (Zp[j] - Bp)) / ((zj - bj) * (zj - bj));
            Dp = Bi[i] / bj * Zp[j];
            // Ep = 0;
            // Attention that if xj[i] = 0, then fugp[i] = nan
            // but Cp also contains xj[i], so eliminate it first
            fugp[i] = Cp / C  + Dp + E / G * Gp;
        }
    }
#ifdef OCP_NANCHECK
    for (USI j = 0; j < NP; j++) {
        if (!CheckNan(fugP[j].size(), &fugP[j][0]))
        {
            OCP_ABORT("INF or NAN in fugP !");
        }
    }
#endif // NANCHECK
}
CalFugPhi() [1/3]
void MixtureComp::CalFugPhi (OCP_DBL * fugT, const OCP_DBL * xj)
Definition at line 779 of file MixtureComp.cpp.
{
    OCP_DBL aj, bj, zj;
    CalAjBj(aj, bj, xj);
    SolEoS(zj, aj, bj);
    const OCP_DBL m1    = delta1;
    const OCP_DBL m2    = delta2;
    const OCP_DBL m1Mm2 = delta1M2;
    // OCP_DBL tmp01 = log(zj - bj);
    // OCP_DBL tmp02 = aj / (m1Mm2) / bj * log((zj + m1 * bj) / (zj + m2 * bj));
    OCP_DBL tmp;
    for (USI i = 0; i < NC; i++) {
        tmp = 0;
        for (int k = 0; k < NC; k++) {
            tmp += 2 * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]) * xj[k];
        }
        tmp     = exp(Bi[i] / bj * (zj - 1) - log(zj - bj) -
                  aj / (m1Mm2) / bj * (tmp / aj - Bi[i] / bj) *
                      log((zj + m1 * bj) / (zj + m2 * bj)));
        fugT[i] = tmp * xj[i] * P;
    }
    Asta = aj;
    Bsta = bj;
    Zsta = zj;
}
CalFugPhi() [2/3]
void MixtureComp::CalFugPhi (OCP_DBL * phiT, OCP_DBL * fugT, const OCP_DBL * xj)
Definition at line 741 of file MixtureComp.cpp.
{
    OCP_DBL aj, bj, zj;
    CalAjBj(aj, bj, xj);
    SolEoS(zj, aj, bj);
    const OCP_DBL m1    = delta1;
    const OCP_DBL m2    = delta2;
    const OCP_DBL m1Mm2 = delta1M2;
    // OCP_DBL tmp01 = log(zj - bj);
    // OCP_DBL tmp02 = aj / (m1Mm2) / bj * log((zj + m1 * bj) / (zj + m2 * bj));
    OCP_DBL tmp;
    for (USI i = 0; i < NC; i++) {
        tmp = 0;
        for (int k = 0; k < NC; k++) {
            tmp += 2 * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]) * xj[k];
        }
        phiT[i] = exp(Bi[i] / bj * (zj - 1) - log(zj - bj) -
                      aj / (m1Mm2) / bj * (tmp / aj - Bi[i] / bj) *
                          log((zj + m1 * bj) / (zj + m2 * bj)));
        fugT[i] = phiT[i] * xj[i] * P;
    }
    // for (USI i = 0; i < NC; i++) {
    //    tmp = 0;
    //    for (int k = 0; k < NC; k++) {
    //        tmp += 2 * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]) * xj[k];
    //    }
    //    phiT[i] = exp(Bi[i] / bj * (zj - 1) - tmp01 - tmp02 * (tmp / aj - Bi[i] /
    //    bj)); fugT[i] = phiT[i] * xj[i] * P;
    //}
    Asta = aj;
    Bsta = bj;
    Zsta = zj;
}
CalFugPhi() [3/3]
void MixtureComp::CalFugPhi (vector< OCP_DBL > & phiT, vector< OCP_DBL > & fugT, const vector< OCP_DBL > & xj)
Definition at line 700 of file MixtureComp.cpp.
{
    OCP_DBL aj, bj, zj;
    CalAjBj(aj, bj, xj);
    SolEoS(zj, aj, bj);
    const OCP_DBL m1 = delta1;
    const OCP_DBL m2 = delta2;
    // const OCP_DBL m1Mm2 = delta1M2;
    OCP_DBL tmp;
    for (USI i = 0; i < NC; i++) {
        tmp = 0;
        for (int k = 0; k < NC; k++) {
            tmp += 2 * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]) * xj[k];
        }
        phiT[i] = exp(Bi[i] / bj * (zj - 1) - log(zj - bj) -
                      aj / (m1 - m2) / bj * (tmp / aj - Bi[i] / bj) *
                          log((zj + m1 * bj) / (zj + m2 * bj)));
        fugT[i] = phiT[i] * xj[i] * P;
    }
    //   OCP_DBL       tmp01 = log(zj - bj);
    //   OCP_DBL       tmp02 = aj / (m1Mm2) / bj * log((zj + m1 * bj) / (zj + m2 * bj));
    // for (USI i = 0; i < NC; i++) {
    //  tmp = 0;
    //  for (int k = 0; k < NC; k++) {
    //      tmp += 2 * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]) * xj[k];
    //  }
    //       phiT[i] = exp(Bi[i] / bj * (zj - 1) - tmp01 - tmp02 * (tmp / aj - Bi[i] /
    //       bj));
    //  fugT[i] = phiT[i] * xj[i] * P;
    //}
    Asta = aj;
    Bsta = bj;
    Zsta = zj;
}
CalFugPhiAll()
void MixtureComp::CalFugPhiAll ()
Definition at line 809 of file MixtureComp.cpp.
{
    OCP_DBL       tmp;// , tmp01, tmp02;
    const OCP_DBL m1    = delta1;
    const OCP_DBL m2    = delta2;
    const OCP_DBL m1Mm2 = delta1M2;
    for (USI j = 0; j < NP; j++) {
        const vector<OCP_DBL>& xj   = x[j];
        vector<OCP_DBL>&       phiT = phi[j];
        vector<OCP_DBL>&       fugT = fug[j];
        OCP_DBL&               aj   = Aj[j];
        OCP_DBL&               bj   = Bj[j];
        OCP_DBL&               zj   = Zj[j];
        CalAjBj(aj, bj, xj);
        SolEoS(zj, aj, bj);
        for (USI i = 0; i < NC; i++) {
            tmp = 0;
            for (int k = 0; k < NC; k++) {
                tmp += 2 * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]) * xj[k];
            }
            phiT[i] = exp(Bi[i] / bj * (zj - 1) - log(zj - bj) -
                          aj / (m1Mm2) / bj * (tmp / aj - Bi[i] / bj) *
                              log((zj + m1 * bj) / (zj + m2 * bj)));
            fugT[i] = phiT[i] * xj[i] * P;
        }
        // tmp01 = log(zj - bj);
        // tmp02 = aj / (m1Mm2) / bj * log((zj + m1 * bj) / (zj + m2 * bj));
        // for (USI i = 0; i < NC; i++) {
        //  tmp = 0;
        //  for (int k = 0; k < NC; k++) {
        //      tmp += 2 * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]) * xj[k];
        //  }
        //          phiT[i] =
        //              exp(Bi[i] / bj * (zj - 1) - tmp01 - tmp02 * (tmp / aj - Bi[i] /
        //              bj));
        //  fugT[i] = phiT[i] * xj[i] * P;
        //}
    }
}
CalFugXAll()
void MixtureComp::CalFugXAll ()
Definition at line 2237 of file MixtureComp.cpp.
{
    for (USI j = 0; j < NP; j++) {
        vector<OCP_DBL>& fugx = fugX[j];
        vector<OCP_DBL>& xj   = x[j];
        OCP_DBL          aj   = Aj[j];
        OCP_DBL          bj   = Bj[j];
        OCP_DBL          zj   = Zj[j];
        OCP_DBL          tmp  = 0;
        Bx = Bi;
        for (USI i = 0; i < NC; i++) {
            tmp = 0;
            for (USI k = 0; k < NC; k++) {
                tmp += xj[k] * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]);
            }
            Ax[i] = 2 * tmp;
            Zx[i] =
                ((bj - zj) * Ax[i] +
                 ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                  ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                  (delta1 + delta2 - 1) * zj * zj) *
                     Bx[i]) /
                (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                 (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
        }
        OCP_DBL  C, D, E, G;
        OCP_DBL  Cxk, Dxk, Exk, Gxk;
        OCP_DBL  aik;
        G = (zj + delta1 * bj) / (zj + delta2 * bj);
        for (USI i = 0; i < NC; i++) {
            // ith fugacity
            C = xj[i] * P / (zj - bj);
            // C = 1 / (zj - bj);
            // D = Bx[i] * (zj - 1) / bj;
            E = -aj / ((delta1 - delta2) * bj) * (Ax[i] / aj - Bx[i] / bj);
            for (USI k = 0; k < NC; k++) {
                aik = (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]);
                // kth components
                Cxk = ((zj - bj) * delta(i, k) - xj[i] * (Zx[k] - Bx[k])) * P /
                      ((zj - bj) * (zj - bj));
                Dxk = Bx[i] / bj * (Zx[k] - Bx[k] * (zj - 1) / bj);
                /*Exk = (Ax[k] * bj - aj * Bx[k]) / (bj * bj) * (Ax[i] / aj - Bx[i] /
                   bj) + aj / bj * (2 * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]) / aj
                   - Ax[k] * Ax[i] / (aj * aj) + Bx[i] * Bx[k] / (bj * bj));*/
                Exk = (2 * (aj / bj * Bx[k] * Bx[i] + bj * aik) - Ax[i] * Bx[k] -
                       Ax[k] * Bi[i]) /
                      (bj * bj);
                Exk /= -(delta1 - delta2);
                Gxk = (delta1 - delta2) / (zj + delta2 * bj) / (zj + delta2 * bj) *
                      (zj * Bx[k] - Zx[k] * bj);
                fugx[i * NC + k] = 1 / C * Cxk + Dxk + Exk * log(G) + E / G * Gxk;
            }
        }
    }
#ifdef OCP_NANCHECK
    for (USI j = 0; j < NP; j++) {
        if (!CheckNan(fugX[j].size(), &fugX[j][0]))
        {
            OCP_ABORT("INF or NAN in fugX !");
        }
    }
#endif // NANCHECK
}
CalFugXSTA()
void MixtureComp::CalFugXSTA ()
Calculate d ln(Fug) / dx for Y.
Definition at line 1401 of file MixtureComp.cpp.
{
    // Y sums to be 1 now, it's actually the mole fraction of spliting phase
    // for stability analysis
    vector<OCP_DBL>& fugx = fugX[0];
    OCP_DBL          aj   = Asta;
    OCP_DBL          bj   = Bsta;
    OCP_DBL          zj   = Zsta;
    OCP_DBL          tmp  = 0;
    const OCP_DBL m1    = delta1;
    const OCP_DBL m2    = delta2;
    const OCP_DBL m1Pm2 = delta1P2;
    const OCP_DBL m1Mm2 = delta1M2;
    const OCP_DBL m1Tm2 = delta1T2;
    Bx = Bi;
    for (USI i = 0; i < NC; i++) {
        tmp = 0;
        for (USI k = 0; k < NC; k++) {
            tmp += Y[k] * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]);
        }
        Ax[i] = 2 * tmp;
        Zx[i] = ((bj - zj) * Ax[i] + ((aj + m1Tm2 * (3 * bj * bj + 2 * bj)) +
                                      ((m1Pm2) * (2 * bj + 1) - 2 * m1Tm2 * bj) * zj -
                                      (m1Pm2 - 1) * zj * zj) *
                                         Bx[i]) /
                (3 * zj * zj + 2 * ((m1Pm2 - 1) * bj - 1) * zj +
                 (aj + m1Tm2 * bj * bj - (m1Pm2)*bj * (bj + 1)));
    }
    OCP_DBL  C, D, E, G;
    OCP_DBL  Cxk, Dxk, Exk, Gxk;
    OCP_DBL  aik;
    G = (zj + m1 * bj) / (zj + m2 * bj);
    for (USI i = 0; i < NC; i++) {
        C = Y[i] * P / (zj - bj);
        // C = 1 / (zj - bj);
        // D = Bx[i] * (zj - 1) / bj;
        E = -aj / ((m1Mm2)*bj) * (Ax[i] / aj - Bx[i] / bj);
        for (USI k = 0; k < NC; k++) {
            aik = (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]);
            // Cxk = -Y[i] * (Zx[k] - Bx[k]) / ((zj - bj) * (zj - bj));
            Cxk = ((zj - bj) * delta(i, k) - Y[i] * (Zx[k] - Bx[k])) * P /
                  ((zj - bj) * (zj - bj));
            Dxk = Bx[i] / bj * (Zx[k] - Bx[k] * (zj - 1) / bj);
            /*Exk = (Ax[k] * bj - aj * Bx[k]) / (bj * bj) * (Ax[i] / aj - Bx[i] / bj) +
               aj / bj * (2 * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]) / aj -
                Ax[k] * Ax[i] / (aj * aj) + Bx[i] * Bx[k] / (bj * bj));*/
            Exk = (2 * (aj / bj * Bx[k] * Bx[i] + bj * aik) - Ax[i] * Bx[k] -
                   Ax[k] * Bi[i]) /
                  (bj * bj);
            Exk /= -(m1Mm2);
            Gxk = (m1Mm2) / (zj + m2 * bj) / (zj + m2 * bj) * (zj * Bx[k] - Zx[k] * bj);
            fugx[i * NC + k] = 1 / C * Cxk + Dxk + Exk * log(G) + E / G * Gxk;
        }
    }
    // cout << "PhiX" << endl;
    // for (USI i = 0; i < NC; i++) {
    //  for (USI k = 0; k < NC; k++) {
    //      cout << fugx[i * NC + k] << "      ";
    //  }
    //  cout << endl;
    //}
#ifdef OCP_NANCHECK
    for (USI j = 0; j < NP; j++) {
        if (!CheckNan(fugX[j].size(), &fugX[j][0]))
        {
            OCP_ABORT("INF or NAN in fugX !");
        }
    }
#endif // NANCHECK
}
References CheckNan(), and OCP_ABORT.
CalKeyDern()
void MixtureComp::CalKeyDern ()
Definition at line 4758 of file MixtureComp.cpp.
{
    // Call CaldXsdXpAPI03 before
    // Calculate d (xij*xi/mu) / dP or dNk
    // no water component
    // use dXsdXp
    // s = S, nij, p = P, Nk
    // xij = nij / nj
    vector<OCP_DBL> njPN(NC + 1, 0);
    fill(keyDer.begin(), keyDer.end(), 0.0);
    const USI ncol = numCom + 1;
    const OCP_DBL* sTmp = &dXsdXp[(NP + 1) * ncol];
    const OCP_DBL* xiNtmp = &xiN[0];
    const OCP_DBL* muNtmp = &muN[0];
    const OCP_DBL* xijtmp = &xij[0];
    OCP_DBL* dTmp = &keyDer[0];
    OCP_DBL tmp01, tmp02;
    if (NP == 1) {
        const USI j = phaseLabel[0];
        xiNtmp += j * numCom;
        muNtmp += j * numCom;
        xijtmp += j * numCom;
        const OCP_DBL tmp = xi[j] / (mu[j] * mu[j]);
        for (USI i = 0; i < NC; i++) {
            // dP
            dTmp[0] = (xijtmp[i] * xiP[j]) / mu[j] - xijtmp[i] * muP[j] * tmp;
            dTmp++;
            // dNk
            for (USI k = 0; k < NC; k++) {
                dTmp[k] = ((delta(i, k) - xijtmp[i]) * xi[j] / nj[j] + xijtmp[i] * xiNtmp[k]) / mu[j] - xijtmp[i] * muNtmp[k] * tmp;
            }
            dTmp += numCom;
        }
    }
    else {
        // hydrocarbon phase
        for (USI j = 0; j < numPhase - 1; j++) {
            if (!phaseExist[j]) {
                xiNtmp += numCom;
                muNtmp += numCom;
                xijtmp += numCom;
                continue;
            }
            fill(njPN.begin(), njPN.end(), 0.0);
            for (USI i = 0; i < NC; i++) {
                for (USI k = 0; k < NC + 1; k++) {
                    njPN[k] += sTmp[k];
                }
                sTmp += ncol;
            }
            sTmp -= NC * ncol;
            tmp01 = xi[j] / (mu[j] * mu[j]);
            for (USI i = 0; i < NC; i++) {
                tmp02 = (sTmp[0] - njPN[0] * xijtmp[i]) / nj[j];
                // dP
                dTmp[0] = (tmp02 * xi[j] + xijtmp[i] * xiP[j]) / mu[j] - xijtmp[i] * muP[j] * tmp01;
                dTmp++;
                sTmp++;
                // dNk
                for (USI k = 0; k < NC; k++) {
                    tmp02 = (sTmp[k] - njPN[k + 1] * xijtmp[i]) / nj[j];
                    dTmp[k] = (tmp02 * xi[j] + xijtmp[i] * xiNtmp[k]) / mu[j] - xijtmp[i] * muNtmp[k] * tmp01;
                }
                dTmp += numCom;
                sTmp += numCom;
            }
            xiNtmp += numCom;
            muNtmp += numCom;
            xijtmp += numCom;
        }
    }
    // water phase
    // dP
    const USI wpid = numPhase - 1;
    keyDer[NP * NC * ncol] = (xiP[wpid] * mu[wpid] - muP[wpid] * xi[wpid]) / (mu[wpid] * mu[wpid]);
}
CalKeyDerx()
void MixtureComp::CalKeyDerx ()
Definition at line 4704 of file MixtureComp.cpp.
{
    // Call CaldXsdXpAPI01 or CaldXsdXpAPI02 before
    // Calculate d (xij*xi/mu) / dP or dNk
    // no water component
    // use dXsdXp
    // s = S, xij, p = P, Nk
    fill(keyDer.begin(), keyDer.end(), 0.0);
    const USI ncol = numCom + 1;
    OCP_DBL tmp;
    const OCP_DBL* sTmp = &dXsdXp[numPhase * ncol];
    const OCP_DBL* xiNtmp = &xiN[0];
    const OCP_DBL* muNtmp = &muN[0];
    const OCP_DBL* xijtmp = &xij[0];
    OCP_DBL* dTmp = &keyDer[0];
    // hydrocarbon phase
    for (USI j = 0; j < numPhase - 1; j++) {
        if (!phaseExist[j]) {
            sTmp += numCom * ncol;
            xiNtmp += numCom;
            muNtmp += numCom;
            xijtmp += numCom;
            continue;
        }
        tmp = xi[j] / (mu[j] * mu[j]);
        for (USI i = 0; i < NC; i++) {
            // dP
            dTmp[0] = (sTmp[0] * xi[j] + xijtmp[i] * xiP[j]) / mu[j] - xijtmp[i] * muP[j] * tmp;
            dTmp++;
            sTmp++;
            // dNk
            for (USI k = 0; k < NC; k++) {
                dTmp[k] = (sTmp[k] * xi[j] + xijtmp[i] * xiNtmp[k]) / mu[j] - xijtmp[i] * muNtmp[k] * tmp;
            }
            dTmp += numCom;
            sTmp += numCom;
        }
        xiNtmp += numCom;
        muNtmp += numCom;
        xijtmp += numCom;
        // skip water components
        sTmp += ncol;
    }
    // water phase
    // dP
    const USI wpid = numPhase - 1;
    keyDer[NP * NC * ncol] = (xiP[wpid] * mu[wpid] - muP[wpid] * xi[wpid]) / (mu[wpid] * mu[wpid]);
}
CalKwilson()
void MixtureComp::CalKwilson ()
Definition at line 979 of file MixtureComp.cpp.
{
    for (USI i = 0; i < NC; i++) {
        Kw[0][i] = (Pc[i] / P) * exp(5.373 * (1 + Acf[i]) * (1 - Tc[i] / T));
        Kw[1][i] = 1 / Kw[0][i];
        Kw[2][i] = pow(Kw[0][i], 1.0 / 3);
        Kw[3][i] = pow(Kw[1][i], 1.0 / 3);
    }
}
CallId()
void MixtureComp::CallId ()
Definition at line 555 of file MixtureComp.cpp.
{
    lId = 0;
    for (USI i = 1; i < NC; i++) {
        if (MWC[i] < MWC[lId]) lId = i;
    }
}
CalMuPn_partial()
void MixtureComp::CalMuPn_partial ()
Definition at line 2463 of file MixtureComp.cpp.
{
    CalMuPnLBC_partial();
}
CalMuPnLBC_partial()
void MixtureComp::CalMuPnLBC_partial ()
Definition at line 2469 of file MixtureComp.cpp.
{
    // muN = 0
    // muP
    // mun in mux
    fill(muN.begin(), muN.end() - numCom, 0.0);
    OCP_DBL val1IJ, val2IJ;
    OCP_DBL der1IJ, der2IJ, der3J, der4J, der6J, der7J, der8J;
    OCP_DBL Tri, tmp;
    OCP_DBL xTj, xPj, xVj;
    OCP_DBL derxTj, derxPj, derMWj, derxVj;
    // dxij / dP = 0, d MJ / dP = 0
    // Calculate dmuj / dP
    // der2IJ = der3J = der4J = der6J = 0;
    for (USI j = 0; j < NP; j++) {
        const USI j1 = phaseLabel[j];
        const vector<OCP_DBL>& xj = x[j];
        const vector<OCP_DBL>& muAuxj = muAux[j];
        xTj = xPj = xVj = 0;
        for (USI i = 0; i < NC; i++) {
            xTj += xj[i] * Tc[i];
            xPj += xj[i] * Pc[i];
            xVj += xj[i] * Vcvis[i];
        }
        der7J = xVj * xiP[j1];
        if (muAuxj[3] <= 0.18 && false) {
            muP[j1] = (2.05 * 1E-4) * der7J / muAuxj[2];
        }
        else {
            der8J = der7J * (LBCcoef[1] +
                muAuxj[3] * (2 * LBCcoef[2] +
                    muAuxj[3] * (3 * LBCcoef[3] +
                        muAuxj[3] * 4 * LBCcoef[4])));
            muP[j1] = (4 * 1E-4) * pow(muAuxj[4], 3) * der8J / muAuxj[2];
        }
        // Calculate dmuj / nkj
        const USI bId = numCom * j1;
        for (USI k = 0; k < NC; k++) {
            derxTj = (Tc[k] - xTj) / nu[j];
            derxPj = (Pc[k] - xPj) / nu[j];
            derMWj = (MWC[k] - MW[j]) / nu[j];
            der3J = 0;
            der4J = sqrtMWi[k];
            for (USI i = 0; i < NC; i++) {
                val1IJ = muAux1I[i] / sqrt(MW[j]);
                der1IJ = -(1 / 2) * muAux1I[i] * pow(MW[j], -1.5) * derMWj;
                Tri = T / Tc[i];
                if (Tri <= 1.5) {
                    tmp = 34 * 1E-5 * pow(Tri, 0.94);
                }
                else {
                    tmp = 17.78 * 1E-5 * pow(4.58 * Tri - 1.67, 0.625);
                }
                val2IJ = tmp / val1IJ;
                der2IJ = -tmp * der1IJ / (val1IJ * val1IJ);
                der3J += sqrtMWi[i] * (xj[i] * der2IJ + (delta(i, k) - xj[i]) * val2IJ / nu[j]);
                der4J -= xj[i] * sqrtMWi[i];
            }
            der4J /= nu[j];
            der6J =
                5.4402 *
                (1.0 / 6 * pow(xTj, -5.0 / 6) * derxTj -
                    pow(xTj, 1.0 / 6) * (0.5 / MW[j] * derMWj + 2.0 / 3 / xPj * derxPj)) /
                (sqrt(MW[j]) * pow(xPj, 2.0 / 3));
            der7J = xix[j1 * numCom + k] * xVj + (Vcvis[k] - xVj) * xi[j1] / nu[j];
            if (muAuxj[3] <= 0.18 && false) {
                mux[bId + k] =
                    (der3J * muAuxj[1] - muAuxj[0] * der4J) / (muAuxj[1] * muAuxj[1]) +
                    2.05 * 1E-4 * (der7J * muAuxj[2] - muAuxj[3] * der6J) /
                    (muAuxj[2] * muAuxj[2]);
            }
            else {
                der8J =
                    der7J * (LBCcoef[1] +
                        muAuxj[3] * (2 * LBCcoef[2] +
                            muAuxj[3] * (3 * LBCcoef[3] +
                                muAuxj[3] * 4 * LBCcoef[4])));
                mux[bId + k] =
                    (der3J * muAuxj[1] - muAuxj[0] * der4J) / (muAuxj[1] * muAuxj[1]) +
                    1E-4 *
                    (4 * pow(muAuxj[4], 3) * der8J * muAuxj[2] -
                        (pow(muAuxj[4], 4) - 1) * der6J) /
                    (muAuxj[2] * muAuxj[2]);
            }
        }
    }
}
CalMuPX_full01()
void MixtureComp::CalMuPX_full01 ()
Definition at line 3337 of file MixtureComp.cpp.
{
    fill(muP.begin(), muP.end() - 1, 0.0);
    fill(muN.begin(), muN.end() - numCom, 0.0);
    fill(mux.begin(), mux.end() - numCom, 0.0);
    CalMuPXLBC_full01();
}
CalMuPX_partial()
void MixtureComp::CalMuPX_partial ()
Definition at line 2932 of file MixtureComp.cpp.
{
    //fill(muP.begin(), muP.end() - 1, 0.0);
    fill(muN.begin(), muN.end() - numCom, 0.0);
    //fill(mux.begin(), mux.end() - numCom, 0.0);
    CalMuPXLBC_partial();
}
CalMuPXLBC_full01()
void MixtureComp::CalMuPXLBC_full01 ()
Definition at line 3346 of file MixtureComp.cpp.
{
    // CaldXsdXp01() before
    // use rhsDer
    OCP_DBL val1IJ, val2IJ;
    OCP_DBL der1IJ, der2IJ, der3J, der4J, der6J, der7J, der8J;
    OCP_DBL Tri, tmp;
    OCP_DBL xTj, xPj, xVj;
    OCP_DBL derxTj, derxPj, derMWj, derxVj;
    // Calculate dmuj / dxkj
    for (USI j = 0; j < NP; j++) {
        const vector<OCP_DBL>& xj = x[j];
        const vector<OCP_DBL>& muAuxj = muAux[j];
        const USI j1 = phaseLabel[j];
        const USI              bId = numCom * j1;
        xTj = xPj = xVj = 0;
        for (USI i = 0; i < NC; i++) {
            xTj += xj[i] * Tc[i];
            xPj += xj[i] * Pc[i];
            xVj += xj[i] * Vcvis[i];
        }
        for (USI k = 0; k < NC; k++) {
            derxTj = Tc[k];
            derxPj = Pc[k];
            derMWj = MWC[k];
            derxVj = Vcvis[k];
            der3J = 0;
            for (USI i = 0; i < NC; i++) {
                val1IJ = muAux1I[i] / sqrt(MW[j]);
                der1IJ = -(1 / 2) * muAux1I[i] * pow(MW[j], -1.5) * derMWj;
                Tri = T / Tc[i];
                if (Tri <= 1.5) {
                    tmp = 34 * 1E-5 * pow(Tri, 0.94);
                }
                else {
                    tmp = 17.78 * 1E-5 * pow(4.58 * Tri - 1.67, 0.625);
                }
                val2IJ = tmp / val1IJ;
                der2IJ = -tmp * der1IJ / (val1IJ * val1IJ);
                der3J += sqrtMWi[i] * (delta(i, k) * val2IJ + xj[i] * der2IJ);
            }
            der4J = sqrtMWi[k];
            der6J = 5.4402 *
                (1.0 / 6 * pow(xTj, -5.0 / 6) * derxTj -
                    pow(xTj, 1.0 / 6) *
                    (0.5 / MW[j] * derMWj + 2.0 / 3 / xPj * derxPj)) /
                (sqrt(MW[j]) * pow(xPj, 2.0 / 3));
            der7J = xix[bId + k] * xVj + xi[j1] * derxVj;
            if (muAuxj[3] <= 0.18 && false) {
                mux[bId + k] = (der3J * muAuxj[1] - muAuxj[0] * der4J) /
                    (muAuxj[1] * muAuxj[1]) +
                    2.05 * 1E-4 *
                    (der7J * muAuxj[2] - muAuxj[3] * der6J) /
                    (muAuxj[2] * muAuxj[2]);
            }
            else {
                der8J = der7J *
                    (LBCcoef[1] +
                        muAuxj[3] * (2 * LBCcoef[2] +
                            muAuxj[3] * (3 * LBCcoef[3] +
                                muAuxj[3] * 4 * LBCcoef[4])));
                mux[bId + k] = (der3J * muAuxj[1] - muAuxj[0] * der4J) /
                    (muAuxj[1] * muAuxj[1]) +
                    1E-4 *
                    (4 * pow(muAuxj[4], 3) * der8J * muAuxj[2] -
                        (pow(muAuxj[4], 4) - 1) * der6J) /
                    (muAuxj[2] * muAuxj[2]);
            }
        }
    }
    if (NP == 1) {
        // NP = 1, then dxij / dP = 0, d MJ / dP = 0
        // Calculate dmuj / dP
        // der2IJ = der3J = der4J = der6J = 0;
        const vector<OCP_DBL>& xj     = x[0];
        const vector<OCP_DBL>& muAuxj = muAux[0];
        xTj = xPj = xVj = 0;
        for (USI i = 0; i < NC; i++) {
            xTj += xj[i] * Tc[i];
            xPj += xj[i] * Pc[i];
            xVj += xj[i] * Vcvis[i];
        }
        der7J = xVj * xiPC[0];
        if (muAuxj[3] <= 0.18 && false) {
            muP[phaseLabel[0]] = (2.05 * 1E-4) * der7J / muAuxj[2];
        } else {
            der8J              = der7J * (LBCcoef[1] +
                             muAuxj[3] * (2 * LBCcoef[2] +
                                          muAuxj[3] * (3 * LBCcoef[3] +
                                                       muAuxj[3] * 4 * LBCcoef[4])));
            muP[phaseLabel[0]] = (4 * 1E-4) * pow(muAuxj[4], 3) * der8J / muAuxj[2];
        }
    } else {
        // NP > 1
        // Calculate dmuj / dP
        // use rhsDer (after CaldXsdXpAPI01)
        for (USI j = 0; j < NP; j++) {
            const OCP_DBL*         xijP   = &rhsDer[NP + j * NC];
            const vector<OCP_DBL>& xj     = x[j];
            const vector<OCP_DBL>& muAuxj = muAux[j];
            const USI              j1    = phaseLabel[j];
            xTj = xPj = xVj = 0;
            derxTj = derxPj = derMWj = 0;
            for (USI i = 0; i < NC; i++) {
                xTj += xj[i] * Tc[i];
                xPj += xj[i] * Pc[i];
                xVj += xj[i] * Vcvis[i];
                derxTj += xijP[i] * Tc[i];
                derxPj += xijP[i] * Pc[i];
                derMWj += xijP[i] * MWC[i];
            }
            der3J = der4J = der7J = 0;
            for (USI i = 0; i < NC; i++) {
                val1IJ = muAux1I[i] / sqrt(MW[j]);
                der1IJ = -(1 / 2) * muAux1I[i] * pow(MW[j], -1.5) * derMWj;
                Tri    = T / Tc[i];
                if (Tri <= 1.5) {
                    tmp = 34 * 1E-5 * pow(Tri, 0.94);
                } else {
                    tmp = 17.78 * 1E-5 * pow(4.58 * Tri - 1.67, 0.625);
                }
                val2IJ = tmp / val1IJ;
                der2IJ = -tmp * der1IJ / (val1IJ * val1IJ);
                der3J += sqrtMWi[i] * (xijP[i] * val2IJ + xj[i] * der2IJ);
                der4J += sqrtMWi[i] * xijP[i];
                der7J += xijP[i] * Vcvis[i];
            }
            der7J *= xi[j1];
            der7J += xiP[j1] * xVj;
            der6J =
                5.4402 *
                (1.0 / 6 * pow(xTj, -5.0 / 6) * derxTj -
                 pow(xTj, 1.0 / 6) * (0.5 / MW[j] * derMWj + 2.0 / 3 / xPj * derxPj)) /
                (sqrt(MW[j]) * pow(xPj, 2.0 / 3));
            if (muAuxj[3] <= 0.18 && false) {
                muP[j1] =
                    (der3J * muAuxj[1] - muAuxj[0] * der4J) / (muAuxj[1] * muAuxj[1]) +
                    2.05 * 1E-4 * (der7J * muAuxj[2] - muAuxj[3] * der6J) /
                        (muAuxj[2] * muAuxj[2]);
            } else {
                der8J =
                    der7J * (LBCcoef[1] +
                             muAuxj[3] * (2 * LBCcoef[2] +
                                          muAuxj[3] * (3 * LBCcoef[3] +
                                                       muAuxj[3] * 4 * LBCcoef[4])));
                muP[j1] =
                    (der3J * muAuxj[1] - muAuxj[0] * der4J) / (muAuxj[1] * muAuxj[1]) +
                    1E-4 *
                        (4 * pow(muAuxj[4], 3) * der8J * muAuxj[2] -
                         (pow(muAuxj[4], 4) - 1) * der6J) /
                        (muAuxj[2] * muAuxj[2]);
            }
        }
    }
}
CalMuPXLBC_partial()
void MixtureComp::CalMuPXLBC_partial ()
Definition at line 2941 of file MixtureComp.cpp.
{
    // Here!
    // dmu/dP = dmu/dP
    // dmu/dNk = dmu/dNk = 0
    // // dxij / dP = dxij / dNk = 0
    // See MixtureComp::CalMuPXLBC_full01()
    OCP_DBL val1IJ, val2IJ;
    OCP_DBL der1IJ, der2IJ, der3J, der4J, der6J, der7J, der8J;
    OCP_DBL Tri, tmp;
    OCP_DBL xTj, xPj, xVj;
    OCP_DBL derxTj, derxPj, derMWj, derxVj;
    // dxij / dP = 0, d MJ / dP = 0
    // Calculate dmuj / dP
    // der2IJ = der3J = der4J = der6J = 0;
    for (USI j = 0; j < NP; j++) {
        const USI j1 = phaseLabel[j];
        const vector<OCP_DBL>& xj = x[j];
        const vector<OCP_DBL>& muAuxj = muAux[j];
        xTj = xPj = xVj = 0;
        for (USI i = 0; i < NC; i++) {
            xTj += xj[i] * Tc[i];
            xPj += xj[i] * Pc[i];
            xVj += xj[i] * Vcvis[i];
        }
        der7J = xVj * xiP[j1];
        if (muAuxj[3] <= 0.18 && false) {
            muP[j1] = (2.05 * 1E-4) * der7J / muAuxj[2];
        }
        else {
            der8J = der7J * (LBCcoef[1] +
                muAuxj[3] * (2 * LBCcoef[2] +
                    muAuxj[3] * (3 * LBCcoef[3] +
                        muAuxj[3] * 4 * LBCcoef[4])));
            muP[j1] = (4 * 1E-4) * pow(muAuxj[4], 3) * der8J / muAuxj[2];
        }
        // Calculate dmuj / xkj
        const USI bId = numCom * j1;
        for (USI k = 0; k < NC; k++) {
            derxTj = Tc[k];
            derxPj = Pc[k];
            derMWj = MWC[k];
            der3J = 0;
            for (USI i = 0; i < NC; i++) {
                val1IJ = muAux1I[i] / sqrt(MW[j]);
                der1IJ = -(1 / 2) * muAux1I[i] * pow(MW[j], -1.5) * derMWj;
                Tri = T / Tc[i];
                if (Tri <= 1.5) {
                    tmp = 34 * 1E-5 * pow(Tri, 0.94);
                }
                else {
                    tmp = 17.78 * 1E-5 * pow(4.58 * Tri - 1.67, 0.625);
                }
                val2IJ = tmp / val1IJ;
                der2IJ = -tmp * der1IJ / (val1IJ * val1IJ);
                der3J +=
                    xj[i] * sqrtMWi[i] * der2IJ + delta(i, k) * sqrtMWi[k] * val2IJ;
            }
            der4J = sqrtMWi[k];
            der6J =
                5.4402 *
                (1.0 / 6 * pow(xTj, -5.0 / 6) * derxTj -
                    pow(xTj, 1.0 / 6) * (0.5 / MW[j] * derMWj + 2.0 / 3 / xPj * derxPj)) /
                (sqrt(MW[j]) * pow(xPj, 2.0 / 3));
            der7J = xix[j1 * numCom + k] * xVj + xi[j1] * Vcvis[k];
            if (muAuxj[3] <= 0.18 && false) {
                mux[bId + k] =
                    (der3J * muAuxj[1] - muAuxj[0] * der4J) / (muAuxj[1] * muAuxj[1]) +
                    2.05 * 1E-4 * (der7J * muAuxj[2] - muAuxj[3] * der6J) /
                    (muAuxj[2] * muAuxj[2]);
            }
            else {
                der8J =
                    der7J * (LBCcoef[1] +
                        muAuxj[3] * (2 * LBCcoef[2] +
                            muAuxj[3] * (3 * LBCcoef[3] +
                                muAuxj[3] * 4 * LBCcoef[4])));
                mux[bId + k] =
                    (der3J * muAuxj[1] - muAuxj[0] * der4J) / (muAuxj[1] * muAuxj[1]) +
                    1E-4 *
                    (4 * pow(muAuxj[4], 3) * der8J * muAuxj[2] -
                        (pow(muAuxj[4], 4) - 1) * der6J) /
                    (muAuxj[2] * muAuxj[2]);
            }
        }
    }
}
CalMW()
void MixtureComp::CalMW ()
Definition at line 853 of file MixtureComp.cpp.
{
    // Calculate Molecular Weight of phase
    for (USI j = 0; j < NP; j++) {
        MW[j] = 0;
        for (USI i = 0; i < NC; i++) {
            MW[j] += x[j][i] * MWC[i];
        }
    }
}
CalPhiNSTA()
void MixtureComp::CalPhiNSTA ()
Calculate d ln phi[i][j] / d n[k][j].
Definition at line 1974 of file MixtureComp.cpp.
{
    OCP_DBL C, D, E, G;
    OCP_DBL Cnk, Dnk, Enk, Gnk;
    OCP_DBL tmp, aik;
    // 0 th phase
    const OCP_DBL& aj = Aj[0];
    const OCP_DBL& bj = Bj[0];
    const OCP_DBL& zj = Zj[0];
    const vector<OCP_DBL>& xj = x[0];
    vector<OCP_DBL>& Znj = Zn[0];
    for (USI i = 0; i < NC; i++) {
        tmp = 0;
        for (USI m = 0; m < NC; m++) {
            tmp += (1 - BIC[i * NC + m]) * sqrt(Ai[i] * Ai[m]) * xj[m];
        }
        An[i] = 2 / nu[0] * (tmp - aj);
        Bn[i] = 1 / nu[0] * (Bi[i] - bj);
        Znj[i] =
            ((bj - zj) * An[i] +
                ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                    ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                    (delta1 + delta2 - 1) * zj * zj) *
                Bn[i]) /
            (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
    }
    G = (zj + delta1 * bj) / (zj + delta2 * bj);
    for (USI i = 0; i < NC; i++) {
        // i th fugacity
        C = 1 / (zj - bj);
        // D = Bi[i] / bj * (zj - 1);
        tmp = 0;
        for (USI k = 0; k < NC; k++) {
            tmp += (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]) * xj[k];
        }
        E = -aj / ((delta1 - delta2) * bj) * (2 * tmp / aj - Bi[i] / bj);
        for (USI k = 0; k <= i; k++) {
            // k th components
            aik = (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]);
            Cnk = (Bn[k] - Znj[k]) / ((zj - bj) * (zj - bj));
            Dnk = Bi[i] / bj * (Znj[k] - (Bi[k] - bj) * (zj - 1) / (nu[0] * bj));
            Gnk = (delta1 - delta2) / ((zj + delta2 * bj) * (zj + delta2 * bj)) *
                (Bn[k] * zj - Znj[k] * bj);
            /*Enk = 1 / ((delta1 - delta2) * bj * bj) * (An[k] * bj - Bn[k] * aj) *
               (Bi[i] / bj - 2 * tmp / aj)
                + aj / ((delta1 - delta2) * bj) * (-Bi[i] / (bj * bj) * Bn[k] - 2 /
               (aj * aj) * (aj * (aik - tmp) / nu[j] - An[k] * tmp));*/
            Enk = -1 / (delta1 - delta2) / (bj * bj) *
                (2 * (bj * aik / nu[0] + Bn[k] * (Bi[i] * aj / bj - tmp)) -
                    An[k] * Bi[i] - aj * Bi[i] / nu[0]);
            Enk -= E / nu[0];
            phiN[i * NC + k] = 1 / C * Cnk + Dnk + Enk * log(G) + E / G * Gnk;
            phiN[k * NC + i] = phiN[i * NC + k];
        }
    }
    //cout << endl << "phiN" << endl;
    //for (USI i = 0; i < NC; i++) {
    //    for (USI j = 0; j < NC; j++) {
    //        cout << phiN[i * NC + j] << "   ";
    //    }
    //    cout << endl;
    //}
}
CalResSP()
void MixtureComp::CalResSP ()
Definition at line 1831 of file MixtureComp.cpp.
{
    // So it equals -res
    for (USI j = 0; j < NP - 1; j++) {
        for (USI i = 0; i < NC; i++) {
            // if zi is too small, resSP[j][i] = 0?
            resSP[j * NC + i] = log(fug[NP - 1][i] / fug[j][i]);
        }
    }
}
CalRhoPn_partial()
void MixtureComp::CalRhoPn_partial ()
Definition at line 2445 of file MixtureComp.cpp.
{
    // rhoN = 0
    // rhoP
    // rhon(drhoj / d nij) in rhox
    fill(rhoN.begin(), rhoN.end() - numCom, 0.0);
    USI j1;
    for (USI j = 0; j < NP; j++) {
        j1 = phaseLabel[j];
        rhoP[j1] = xiP[j1] * MW[j];
        for (USI m = 0; m < NC; m++) {
            rhox[j1 * numCom + m] = xix[j1 * numCom + m] * MW[j]
                + xi[j1] / nu[j] * (MWC[m] - MW[j]);
        }
    }
}
CalRhoPNX_full()
void MixtureComp::CalRhoPNX_full ()
Definition at line 3282 of file MixtureComp.cpp.
{
    // CaldXsdXpAPI01() or CaldXsdXpAPI02() shoule be called before
    // Using dXsdXp
    // Cal rhoP, rhoX
    // Water has been calculated
    // fill(rhox.begin(), rhox.end() - numCom, 0.0);
    // fill(rhoP.begin(), rhoP.end() - 1, 0.0);
    USI j1, bId;
    OCP_DBL tmp = 0;
    if (NP == 1) {
        j1 = phaseLabel[0];
        bId = j1 * numCom;
        rhoP[j1] = xiP[j1] * MW[0];
        for (USI m = 0; m < NC; m++) {
            rhox[bId + m] = xix[bId + m] * MW[0] + xi[j1] * MWC[m];
            rhoN[bId + m] = xiN[bId + m] * MW[0];
            tmp = MWC[m] * Nh;
            for (USI i = 0; i < NC; i++) {
                tmp -= MWC[i] * Ni[i];
            }
            rhoN[bId + m] += tmp * xi[j1] / (Nh * Nh);
        }
    }
    else {
        // Using dXsdXp
        fill(rhoP.begin(), rhoP.end() - 1, 0.0);
        fill(rhoN.begin(), rhoN.end() - numCom, 0.0);
        OCP_DBL ncol = numCom + 1;
        for (USI j = 0; j < NP; j++) {
            j1 = phaseLabel[j];
            bId = j1 * numCom;
            const OCP_DBL* xijPN = &dXsdXp[(numPhase + bId) * ncol];
            for (USI i = 0; i < NC; i++) {
                rhoP[j1] += MWC[i] * xijPN[0];
                xijPN++;
                for (USI m = 0; m < NC; m++) {
                    rhoN[bId + m] += MWC[i] * xijPN[m];
                }
                xijPN += numCom;
            }
            rhoP[j1] *= xi[j1];
            rhoP[j1] += xiP[j1] * MW[j];
            for (USI m = 0; m < NC; m++) {
                rhoN[bId + m] *= xi[j1];
                rhoN[bId + m] += xiN[bId + m] * MW[j];
                rhox[bId + m] = xix[bId + m] * MW[j] + xi[j1] * MWC[m];
            }
        }
    }
}
CalRhoPNX_full01()
void MixtureComp::CalRhoPNX_full01 ()
Definition at line 3218 of file MixtureComp.cpp.
{
    // CaldXsdXp01() shoule be called before
    // Using rhsDer
    // Cal rhoP, rhoX
    // Water has been calculated
    //fill(rhox.begin(), rhox.end() - numCom, 0.0);
    //fill(rhoP.begin(), rhoP.end() - 1, 0.0);
    USI j1, bId;
    for (USI j = 0; j < NP; j++) {
        j1 = phaseLabel[j];
        bId = j1 * numCom;
        rhoP[j1] = xiP[j1] * MW[j];
        for (USI m = 0; m < NC; m++) {
            rhox[bId + m] = xix[bId + m] * MW[j] + xi[j1] * MWC[m];
        }
    }
    if (NP == 1) {
        OCP_DBL tmp;
        j1 = phaseLabel[0];
        bId = j1 * numCom;
        for (USI m = 0; m < NC; m++) {
            rhoN[bId + m] = xiN[bId + m] * MW[0];
            tmp = MWC[m] * Nh;
            for (USI i = 0; i < NC; i++) {
                tmp -= MWC[i] * Ni[i];
            }
            rhoN[bId + m] += tmp * xi[j1] / (Nh * Nh);
        }
    }
    if (NP > 1) {
        // correct rhoP
        // use rhsDer, see CaldXsdXp01(), attention that it only contains hydrocarbon
        OCP_DBL        tmp;
        const OCP_DBL* xijP = &rhsDer[NP];
        for (USI j = 0; j < NP; j++) {
            j1 = phaseLabel[j];
            tmp = 0;
            for (USI i = 0; i < NC; i++) {
                tmp += MWC[i] * xijP[i];
            }
            rhoP[j1] += xi[j1] * tmp;
            xijP += NC;
        }
        // Calculate rhoN
        const OCP_DBL* xijN = xijP;
        for (USI m = 0; m < NC; m++) {
            xijN += NP;
            for (USI j = 0; j < NP; j++) {
                j1 = phaseLabel[j];
                bId = j1 * numCom;
                rhoN[bId + m] = xiN[bId + m] * MW[j];
                tmp = 0;
                for (USI i = 0; i < NC; i++) {
                    tmp += MWC[i] * xijN[i];
                }
                rhoN[bId + m] += tmp * xi[j1];
                xijN += NC;
            }
        }
    }
}
CalRhoPX_partial()
void MixtureComp::CalRhoPX_partial ()
Definition at line 2909 of file MixtureComp.cpp.
{
    // Here!
    // drho/dP = drho/dP
    // drho/dNk = drho/dNk = 0
    // dxij / dP = dxij / dNk = 0
    // See MixtureComp::CalRhoPNX_full()
    //fill(rhox.begin(), rhox.end() - numCom, 0.0);
    fill(rhoN.begin(), rhoN.end() - numCom, 0.0);
    //fill(rhoP.begin(), rhoP.end() - 1, 0.0);
    USI j1;
    for (USI j = 0; j < NP; j++) {
        j1 = phaseLabel[j];
        rhoP[j1] = xiP[j1] * MW[j];
        for (USI i = 0; i < NC; i++) {
            rhox[j1 * numCom + i] = xix[j1 * numCom + i] * MW[j] + xi[j1] * MWC[i];
        }
    }
}
CalSaturation()
void MixtureComp::CalSaturation ()
Definition at line 883 of file MixtureComp.cpp.
{
    for (USI j = 0; j < numPhase; j++) {
        S[j] = 0;
        if (phaseExist[j]) {
            S[j] = v[j] / vf;
        }
    }
}
CalStepNRsp()
OCP_DBL MixtureComp::CalStepNRsp ()
Definition at line 2069 of file MixtureComp.cpp.
{
    OCP_DBL alpha = 1;
    OCP_DBL tmp;
    for (USI j = 0; j < NP - 1; j++) {
        const OCP_DBL* nj = &n[j][0];
        const OCP_DBL* r  = &resSP[j * NC];
        for (USI i = 0; i < NC; i++) {
            tmp = nj[i] + alpha * r[i];
            if (tmp < 0) {
                alpha *= 0.9 * fabs(nj[i] / r[i]);
            }
        }
    }
    return alpha;
}
CalSurfaceTension()
void MixtureComp::CalSurfaceTension ()
Definition at line 563 of file MixtureComp.cpp.
{
    // be careful!
    // phase molar densities should be converted into gm-M/cc here
    if (miscible) {
        if (NP == 1)  surTen = 100;
        else {
            const OCP_DBL unitF = CONV3 / (CONV4 * 1E3); // lbm/ft3 -> gm-M/cc
            const OCP_DBL b0 = xiC[0] * unitF;
            const OCP_DBL b1 = xiC[1] * unitF;
            surTen = 0;
            for (USI i = 0; i < NC; i++)
                surTen += Parachor[i] * (b0 * x[0][i] - b1 * x[1][i]);
            surTen = pow(surTen, 4.0);
            // cout << surTen << endl;
        }
    }
}
CalVfiVfp_full01()
void MixtureComp::CalVfiVfp_full01 ()
Definition at line 3608 of file MixtureComp.cpp.
{
    OCP_DBL CgTP = GAS_CONSTANT * T / P;
    if (NP == 1) {
        // NP = 1
        const OCP_DBL&         aj   = Aj[0];
        const OCP_DBL&         bj   = Bj[0];
        const OCP_DBL&         zj   = Zj[0];
        const vector<OCP_DBL>& xj   = x[0];
        vector<OCP_DBL>&       Znij = Zn[0];
        OCP_DBL                tmp;
        for (USI i = 0; i < NC; i++) {
            tmp = 0;
            for (USI m = 0; m < NC; m++) {
                tmp += (1 - BIC[i * NC + m]) * sqrt(Ai[i] * Ai[m]) * xj[m];
            }
            An[i] = 2 / nu[0] * (tmp - aj);
            Bn[i] = 1 / nu[0] * (Bi[i] - bj);
            Znij[i] =
                ((bj - zj) * An[i] +
                 ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                  ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                  (delta1 + delta2 - 1) * zj * zj) *
                     Bn[i]) /
                (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                 (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
            vfi[i] = CgTP * (zj + nu[0] * Znij[i]);
        }
        Zp[0] = ((bj - zj) * aj +
                 ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                  ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                  (delta1 + delta2 - 1) * zj * zj) *
                     bj) /
                P /
                (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                 (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
        vfp = CgTP * nu[0] * (Zp[0] - zj / P);
    } else {
        // NP > 1
        CalFugNAll();
        CalFugPAll();
        AssembleMatVfiVfp_full01();
        AssembleRhsVfiVfp_full01();
        LUSolve(NC + 1, NC * NP, &JmatDer[0], &rhsDer[0], &pivot[0]);
        // Calculate Vfi
        OCP_DBL* dnkjdNP = &rhsDer[0];
        for (USI i = 0; i < NC; i++) {
            vfi[i] = 0;
            for (USI j = 0; j < NP; j++) {
                for (USI k = 0; k < NC; k++) {
                    vfi[i] += dnkjdNP[j * NC + k] * (Zj[j] + nu[j] * Zn[j][k]);
                }
            }
            vfi[i] *= CgTP;
            dnkjdNP += NP * NC;
        }
        // Calculate Vfp
        vfp = 0;
        for (USI j = 0; j < NP; j++) {
            vfp += nu[j] / P * (Zp[j] * P - Zj[j]);
            for (USI k = 0; k < NC; k++) {
                vfp += dnkjdNP[j * NC + k] * (Zj[j] + nu[j] * Zn[j][k]);
            }
        }
        vfp *= CgTP;
    }
#ifdef OCP_NANCHECK
    if (!CheckNan(vfi.size(), &vfi[0])) {
        OCP_ABORT("INF or NAN in vfi !");
    }
    if (!CheckNan(1, &vfp)) {
        OCP_ABORT("INF or NAN in vfp !");
    }
#endif // NANCHECK
}
CalVfiVfp_full02()
void MixtureComp::CalVfiVfp_full02 ()
Definition at line 3746 of file MixtureComp.cpp.
{
    // Attention!
    // NP = 1 or NP = 2
    OCP_DBL CgTP = GAS_CONSTANT * T / P;
    if (NP == 1) {
        // NP = 1
        const OCP_DBL& aj = Aj[0];
        const OCP_DBL& bj = Bj[0];
        const OCP_DBL& zj = Zj[0];
        const vector<OCP_DBL>& xj = x[0];
        vector<OCP_DBL>& Znij = Zn[0];
        OCP_DBL                tmp;
        for (USI i = 0; i < NC; i++) {
            tmp = 0;
            for (USI m = 0; m < NC; m++) {
                tmp += (1 - BIC[i * NC + m]) * sqrt(Ai[i] * Ai[m]) * xj[m];
            }
            An[i] = 2 / nu[0] * (tmp - aj);
            Bn[i] = 1 / nu[0] * (Bi[i] - bj);
            Znij[i] =
                ((bj - zj) * An[i] +
                    ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                        ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                        (delta1 + delta2 - 1) * zj * zj) *
                    Bn[i]) /
                (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                    (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
            vfi[i] = CgTP * (zj + nu[0] * Znij[i]);
        }
        Zp[0] = ((bj - zj) * aj +
            ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                (delta1 + delta2 - 1) * zj * zj) *
            bj) /
            P /
            (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
        vfp = CgTP * nu[0] * (Zp[0] - zj / P);
    }
    else {
        // NP = 2,  IF NP > 2  ->  WRONG!
        CalFugNAll();
        CalFugPAll();
        AssembleMatVfiVfp_full02();
        AssembleRhsVfiVfp_full02();
        LUSolve(NC + 1, NC, &JmatDer[0], &rhsDer[0], &pivot[0]);
        // now d nm0 / dP(dNk) has been available
        const OCP_DBL* dnkjdNP = &rhsDer[0];
        // Calculate Vfp
        const USI j0 = phaseLabel[0];
        const USI j1 = phaseLabel[1];
        vjp[j0] = nu[0] * (Zp[0] - Zj[0] / P);
        vjp[j1] = nu[1] * (Zp[1] - Zj[1] / P);
        for (USI k = 0; k < NC; k++) {
            vjp[j0] += (Zj[0] + nu[0] * Zn[0][k]) * dnkjdNP[k];
            vjp[j1] -= (Zj[1] + nu[1] * Zn[1][k]) * dnkjdNP[k];
        }
        vjp[j0] *= CgTP;
        vjp[j1] *= CgTP;
        vfp = vjp[j0] + vjp[j1];
        dnkjdNP += NC;
        // Calculate Vfi
        for (USI i = 0; i < NC; i++) {
            vfi[i] = 0;
            vji[j0][i] = 0;
            vji[j1][i] = 0;
            for (USI k = 0; k < NC; k++) {
                vji[j0][i] += (Zj[0] + nu[0] * Zn[0][k]) * dnkjdNP[k];
                vji[j1][i] += (Zj[1] + nu[1] * Zn[1][k]) * (delta(i, k) - dnkjdNP[k]);
            }
            vji[j0][i] *= CgTP;
            vji[j1][i] *= CgTP;
            vfi[i] = vji[j0][i] + vji[j1][i];
            dnkjdNP += NC;
        }
    }
}
CalVfiVfp_full03()
void MixtureComp::CalVfiVfp_full03 ()
Definition at line 4670 of file MixtureComp.cpp.
{
    // Call CaldXsdXpAPI03() before
    // use dXsdXp: s = Sj,nij; p = P,Ni
    USI j1;
    if (NP == 1) {
        // vfp = vfp; vfi = vji
        j1 = phaseLabel[0];
        for (USI i = 0; i < NC; i++) {
            vfi[i] = vji[j1][i];
        }
    }
    else {
        const USI ncol = numCom + 1;
        const OCP_DBL* nijPN = &dXsdXp[(NP + 1) * ncol];
        for (USI j = 0; j < numPhase-1; j++) {
            if (!phaseExist[j])  // skip
                continue;
            for (USI i = 0; i < NC; i++) {
                vfp += vji[j][i] * nijPN[0];
                nijPN++;
                for (USI m = 0; m < NC; m++) {
                    vfi[m] += vji[j][i] * nijPN[m];
                }
                nijPN += numCom;
            }
            // don't skip water, no water in dXsdXp here.
        }
    }
}
CalVfXiRho()
void MixtureComp::CalVfXiRho ()
Definition at line 864 of file MixtureComp.cpp.
{
    // Attention that nu is moles of phase instead of molar fraction of phase now
    vf = 0;
    OCP_DBL tmp;
    for (USI j = 0; j < NP; j++) {
        vector<OCP_DBL>& xj = x[j];
        tmp                 = Zj[j] * GAS_CONSTANT * T / P;
        for (USI i = 0; i < NC; i++) {
            tmp -= xj[i] * Vshift[i];
        }
        vC[j] = tmp * nu[j];
        vf += vC[j];
        xiC[j]  = 1 / tmp;
        rhoC[j] = MW[j] * xiC[j];
    }
}
CalViscoHZYT()
void MixtureComp::CalViscoHZYT ()
Definition at line 2235 of file MixtureComp.cpp.
{}
CalViscoLBC()
void MixtureComp::CalViscoLBC ()
Definition at line 2171 of file MixtureComp.cpp.
{
    OCP_DBL tmp;
    OCP_DBL Tri;
    OCP_DBL xijT;
    OCP_DBL xijP;
    OCP_DBL xijV;
    // test
    //T = 750;
    //P = 4867.594;
    //x[0][0] = 0.657538;
    //x[0][1] = 0.014955;
    //x[0][2] = 0.003126;
    //x[0][3] = 0.008749;
    //x[0][4] = 0.008200;
    //x[0][5] = 0.017913;
    //x[0][6] = 0.035430;
    //x[0][7] = 0.254089;
    //CalAiBi();
    //CalAjBj(Aj[0], Bj[0], x[0]);
    //SolEoS(Zj[0], Aj[0], Bj[0]);
    //CalMW();
    //CalVfXiRho();
    //test
    for (USI j = 0; j < NP; j++) {
        const vector<OCP_DBL>& xj  = x[j];
        vector<OCP_DBL>&       muA = muAux[j];
        fill(muA.begin(), muA.end(), 0.0);
        xijT = 0;
        xijP = 0;
        xijV = 0;
        for (USI i = 0; i < NC; i++) {
            tmp = 5.4402 * pow(Tc[i], 1.0 / 6) / sqrt(MW[j]) / pow(Pc[i], 2.0 / 3);
            // tmp = muAux1I[i] / sqrt(MW[j]);
            Tri = T / Tc[i];
            if (Tri <= 1.5) {
                tmp = 34 * 1E-5 * pow(Tri, 0.94) / tmp;
            } else {
                tmp = 17.78 * 1E-5 * pow((4.58 * Tri - 1.67), 0.625) / tmp;
            }
            muA[0] += xj[i] * sqrt(MWC[i]) * tmp;
            muA[1] += xj[i] * sqrt(MWC[i]);
            xijT += xj[i] * Tc[i];
            xijP += xj[i] * Pc[i];
            xijV += xj[i] * Vcvis[i];
        }
        muA[2] = 5.4402 * pow(xijT, 1.0 / 6) / sqrt(MW[j]) / pow(xijP, 2.0 / 3);
        muA[3] = xiC[j] * xijV;
        if (muA[3] <= 0.18 && false) {
            muC[j] = muA[0] / muA[1] + 2.05 * 1E-4 * muA[3] / muA[2];
        } else {
            muA[4] = muA[3] * (muA[3] * (muA[3] * (LBCcoef[4] * muA[3] + LBCcoef[3]) +
                                         LBCcoef[2]) +
                               LBCcoef[1]) +
                     LBCcoef[0];
            muC[j] = muA[0] / muA[1] + 1E-4 * (pow(muA[4], 4) - 1) / muA[2];
        }
    }
}
CalViscosity()
void MixtureComp::CalViscosity ()
Definition at line 2169 of file MixtureComp.cpp.
{ CalViscoLBC(); }
CalVjpVfpVfn_partial()
void MixtureComp::CalVjpVfpVfn_partial ()
Definition at line 2372 of file MixtureComp.cpp.
{
    // Vfi = 0
    // Vjp, Vfp
    // Vjn(dVj / dnij) in Vji
    OCP_DBL CgTP = GAS_CONSTANT * T / P;
    fill(vfi.begin(), vfi.end(), 0.0);
    vfp = 0;
    for (USI j = 0; j < NP; j++) {
        const OCP_DBL& aj = Aj[j];
        const OCP_DBL& bj = Bj[j];
        const OCP_DBL& zj = Zj[j];
        const vector<OCP_DBL>& xj = x[j];
        vector<OCP_DBL>& Znj = Zn[j];
        OCP_DBL                tmp;
        const USI j1 = phaseLabel[j];
        for (USI i = 0; i < NC; i++) {
            tmp = 0;
            for (USI m = 0; m < NC; m++) {
                tmp += (1 - BIC[i * NC + m]) * sqrt(Ai[i] * Ai[m]) * xj[m];
            }
            An[i] = 2 / nu[j] * (tmp - aj);
            Bn[i] = 1 / nu[j] * (Bi[i] - bj);
            Znj[i] =
                ((bj - zj) * An[i] +
                    ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                        ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                        (delta1 + delta2 - 1) * zj * zj) *
                    Bn[i]) /
                (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                    (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
            vji[j1][i] = CgTP * (zj + nu[j] * Znj[i]);
        }
        Zp[j] = ((bj - zj) * aj +
            ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                (delta1 + delta2 - 1) * zj * zj) *
            bj) /
            P /
            (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
        vjp[j1] = CgTP * nu[j] * (Zp[j] - zj / P);
        vfp += vjp[j1];
    }
}
CalVjpVfpVfx_partial()
void MixtureComp::CalVjpVfpVfx_partial ()
Definition at line 2564 of file MixtureComp.cpp.
{
    // Wrong Now !
    // Vfi = 0
    // Vjp, Vfp
    // Vjn(dVj / dxij) in Vji
    OCP_DBL CgTP = GAS_CONSTANT * T / P;
    fill(vfi.begin(), vfi.end(), 0.0);
    vfp = 0;
    for (USI j = 0; j < NP; j++) {
        const USI j1 = phaseLabel[j];
        const vector<OCP_DBL>& xj = x[j];
        const OCP_DBL    aj = Aj[j];
        const OCP_DBL    bj = Bj[j];
        const OCP_DBL    zj = Zj[j];
        OCP_DBL    tmp = 0;
        Bx = Bi;
        for (USI i = 0; i < NC; i++) {
            tmp = 0;
            for (USI k = 0; k < NC; k++) {
                tmp += xj[k] * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]);
            }
            Ax[i] = 2 * tmp;
            Zx[i] =
                ((bj - zj) * Ax[i] +
                    ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                        ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                        (delta1 + delta2 - 1) * zj * zj) *
                    Bx[i]) /
                (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                    (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
            vji[j1][i] = CgTP * nu[j] * Zx[i];
        }
        Zp[j] = ((bj - zj) * aj +
            ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                (delta1 + delta2 - 1) * zj * zj) *
            bj) /
            P /
            (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
        vjp[j1] = CgTP * nu[j] * (Zp[j] - zj / P);
        vfp += vjp[j1];
    }
}
CalXiPn_partial()
void MixtureComp::CalXiPn_partial ()
Definition at line 2420 of file MixtureComp.cpp.
{
    // xiN = 0
    // xiP
    // xin(dxi_j / d nij) in xix
    OCP_DBL CgTP = GAS_CONSTANT * T / P;
    OCP_DBL tmp;
    fill(xiN.begin(), xiN.end() - numCom, 0.0);
    for (USI j = 0; j < NP; j++) {
        const vector<OCP_DBL>& xj = x[j];
        OCP_DBL                aj = Aj[j];
        OCP_DBL                bj = Bj[j];
        OCP_DBL                zj = Zj[j];
        const USI j1 = phaseLabel[j];
        tmp = -xi[j1] * xi[j1] * CgTP;
        for (USI i = 0; i < NC; i++) {
            xix[j1 * numCom + i] = tmp * Zn[j][i];
        }
        xiP[j1] = tmp * (Zp[j] - Zj[j] / P);
    }
}
CalXiPNX_full01()
void MixtureComp::CalXiPNX_full01 ()
Definition at line 3035 of file MixtureComp.cpp.
{
    // call CalVfiVfp_full01() before, use rhsDer
    // Calculate xiPC, xiNC, xixC
    // Calculate xixC first
    OCP_DBL CgTP = GAS_CONSTANT * T / P;
    OCP_DBL tmp;
    for (USI j = 0; j < NP; j++) {
        const vector<OCP_DBL>& xj = x[j];
        OCP_DBL                aj = Aj[j];
        OCP_DBL                bj = Bj[j];
        OCP_DBL                zj = Zj[j];
        Bx = Bi;
        for (USI i = 0; i < NC; i++) {
            tmp = 0;
            for (USI k = 0; k < NC; k++) {
                tmp += xj[k] * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]);
            }
            Ax[i] = 2 * tmp;
            Zx[i] =
                ((bj - zj) * Ax[i] +
                 ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                  ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                  (delta1 + delta2 - 1) * zj * zj) *
                     Bx[i]) /
                (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                 (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
        }
        tmp           = -xiC[j] * xiC[j] * CgTP;
        for (USI i = 0; i < NC; i++) {
            xixC[j * NC + i] = tmp * Zx[i];
        }
    }
    // Calculate xiPC and xiNC
    if (NP == 1) {
        // NP = 1
        tmp     = -xiC[0] * xiC[0] * CgTP;
        xiPC[0] = tmp * (Zp[0] - Zj[0] / P);
        for (USI i = 0; i < NC; i++) {
            xiNC[i] = tmp * Zn[0][i];
        }
    } else {
        // NP > 1
        const OCP_DBL* dnkjdNP = &rhsDer[0];
        OCP_DBL        dertmp;
        // Calculate xiNC
        // Now dnkjdNP reach to dnkj / dNi after CalVfiVfp_full01
        for (USI i = 0; i < NC; i++) {
            for (USI j = 0; j < NP; j++) {
                dertmp                     = 0;
                tmp                        = -xiC[j] * xiC[j] * CgTP;
                const vector<OCP_DBL>& Znj = Zn[j];
                for (USI k = 0; k < NC; k++) {
                    dertmp += Znj[k] * dnkjdNP[k];
                }
                xiNC[j * NC + i] = tmp * dertmp;
                dnkjdNP += NC;
            }
        }
        // Calculate xiPC
        // Now dnkjdNP reach to dnkj / dP
        for (USI j = 0; j < NP; j++) {
            tmp                        = -xiC[j] * xiC[j] * CgTP;
            xiPC[j]                    = Zp[j] - Zj[j] / P;
            const vector<OCP_DBL>& Znj = Zn[j];
            // in OCP
            for (USI k = 0; k < NC; k++) {
                xiPC[j] += Znj[k] * dnkjdNP[k];
            }
            dnkjdNP += NC;
            xiPC[j] *= tmp;
        }
    }
    // Copoy to xiP, xix, xiN
    //fill(xiP.begin(), xiP.end(), 0.0);
    //fill(xix.begin(), xix.end(), 0.0);
    USI j1;
    for (USI j = 0; j < NP; j++) {
        j1      = phaseLabel[j];
        xiP[j1] = xiPC[j];
        Dcopy(NC, &xiN[j1 * numCom], &xiNC[j * NC]);
        Dcopy(NC, &xix[j1 * numCom], &xixC[j * NC]);
    }
}
CalXiPNX_full02()
void MixtureComp::CalXiPNX_full02 ()
Definition at line 3128 of file MixtureComp.cpp.
{
    // Attention!
    // NP = 1 or NP = 2
    // Call CalVfiVfp_full02() before, use rhsder
    // Calculate xiPC, xiNC, xixC
    // Calculate xixC first
    OCP_DBL CgTP = GAS_CONSTANT * T / P;
    OCP_DBL tmp;
    for (USI j = 0; j < NP; j++) {
        const vector<OCP_DBL>& xj = x[j];
        OCP_DBL                aj = Aj[j];
        OCP_DBL                bj = Bj[j];
        OCP_DBL                zj = Zj[j];
        Bx = Bi;
        for (USI i = 0; i < NC; i++) {
            tmp = 0;
            for (USI k = 0; k < NC; k++) {
                tmp += xj[k] * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]);
            }
            Ax[i] = 2 * tmp;
            Zx[i] =
                ((bj - zj) * Ax[i] +
                    ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                        ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                        (delta1 + delta2 - 1) * zj * zj) *
                    Bx[i]) /
                (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                    (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
        }
        tmp = -xiC[j] * xiC[j] * CgTP;
        for (USI i = 0; i < NC; i++) {
            xixC[j * NC + i] = tmp * Zx[i];
        }
    }
    // Calculate xiPC and xiNC
    if (NP == 1) {
        // NP = 1
        tmp = -xiC[0] * xiC[0] * CgTP;
        xiPC[0] = tmp * (Zp[0] - Zj[0] / P);
        for (USI i = 0; i < NC; i++) {
            xiNC[i] = tmp * Zn[0][i];
        }
    }
    else {
        // NP = 2
        OCP_DBL* nijPN = &rhsDer[0];
        // Calculate xiPC
        xiPC[0] = (Zp[0] - Zj[0] / P);
        xiPC[1] = (Zp[1] - Zj[1] / P);
        for (USI i = 0; i < NC; i++) {
            xiPC[0] += Zn[0][i] * nijPN[i];
            xiPC[1] -= Zn[1][i] * nijPN[i];
        }
        nijPN += NC;
        xiPC[0] *= -xiC[0] * xiC[0] * CgTP;
        xiPC[1] *= -xiC[1] * xiC[1] * CgTP;
        // Calculate xiNC
        OCP_DBL tmp0 = -xiC[0] * xiC[0] * CgTP;
        OCP_DBL tmp1 = -xiC[1] * xiC[1] * CgTP;
        for (USI i = 0; i < NC; i++) {
            xiNC[i] = 0;
            xiNC[NC + i] = 0;
            for (USI k = 0; k < NC; k++) {
                xiNC[i] += Zn[0][k] * nijPN[k];
                xiNC[NC + i] -= Zn[1][k] * nijPN[k];
            }
            xiNC[NC + i] += Zn[1][i];
            nijPN += NC;
            xiNC[i] *= tmp0;
            xiNC[NC + i] *= tmp1;
        }
    }
    // Copoy to xiP, xix, xiN
    //fill(xiP.begin(), xiP.end(), 0.0);
    //fill(xix.begin(), xix.end(), 0.0);
    USI j1;
    for (USI j = 0; j < NP; j++) {
        j1 = phaseLabel[j];
        xiP[j1] = xiPC[j];
        Dcopy(NC, &xiN[j1 * numCom], &xiNC[j * NC]);
        Dcopy(NC, &xix[j1 * numCom], &xixC[j * NC]);
    }
}
CalXiPNX_partial()
void MixtureComp::CalXiPNX_partial ()
Definition at line 2851 of file MixtureComp.cpp.
{
    // Here!
    // dxi/dP = dxi/dP
    // dxi/dNk = dxi/dNk = 0
    // dxij / dP = dxij / dNk = 0
    // See MixtureComp::CalXiPNX_full01()
    // Calculate xix and xiP
    OCP_DBL CgTP = GAS_CONSTANT * T / P;
    OCP_DBL tmp;
    for (USI j = 0; j < NP; j++) {
        const vector<OCP_DBL>& xj = x[j];
        OCP_DBL                aj = Aj[j];
        OCP_DBL                bj = Bj[j];
        OCP_DBL                zj = Zj[j];
        Bx = Bi;
        for (USI i = 0; i < NC; i++) {
            tmp = 0;
            for (USI k = 0; k < NC; k++) {
                tmp += xj[k] * (1 - BIC[i * NC + k]) * sqrt(Ai[i] * Ai[k]);
            }
            Ax[i] = 2 * tmp;
            Zx[i] =
                ((bj - zj) * Ax[i] +
                    ((aj + delta1 * delta2 * (3 * bj * bj + 2 * bj)) +
                        ((delta1 + delta2) * (2 * bj + 1) - 2 * delta1 * delta2 * bj) * zj -
                        (delta1 + delta2 - 1) * zj * zj) *
                    Bx[i]) /
                (3 * zj * zj + 2 * ((delta1 + delta2 - 1) * bj - 1) * zj +
                    (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1)));
        }
        tmp = -xiC[j] * xiC[j] * CgTP;
        for (USI i = 0; i < NC; i++) {
            xixC[j * NC + i] = tmp * Zx[i];
        }
        xiPC[j] = tmp * (Zp[j] - Zj[j] / P);
    }
    // xiNC
    fill(xiNC.begin(), xiNC.end(), 0.0);
    // Copoy to xiP, xix
    //fill(xiP.begin(), xiP.end(), 0.0);
    //fill(xix.begin(), xix.end(), 0.0);
    fill(xiN.begin(), xiN.end(), 0.0);
    USI j1;
    for (USI j = 0; j < NP; j++) {
        j1 = phaseLabel[j];
        xiP[j1] = xiPC[j];
        Dcopy(NC, &xix[j1 * numCom], &xixC[j * NC]);
    }
}
CalXiRhoMuPN_pfullx()
void MixtureComp::CalXiRhoMuPN_pfullx ()
Definition at line 3505 of file MixtureComp.cpp.
{
    // Using dXsdXp
    // CalXiPNX_partial(),CalRhoPX_partial(),CalMuPX_partial() have been called
    // s: S,x; p: P,N  Call CaldXsdXpAPI01 or CaldXsdXpAPI02 before
    const USI ncol = numCom + 1;
    const OCP_DBL* xijPN = &dXsdXp[numPhase * ncol];
    if (NP == 1) {
        const USI j1 = phaseLabel[0];
        const USI bId = j1 * numCom;
        xijPN += bId * ncol;
        for (USI i = 0; i < NC; i++) {
            xijPN++;
            // dN
            for (USI m = 0; m < NC; m++) {
                xiN[bId + m] += xix[bId + i] * xijPN[m];
                rhoN[bId + m] += rhox[bId + i] * xijPN[m];
                muN[bId + m] += mux[bId + i] * xijPN[m];
            }
            xijPN += numCom;
        }
    }
    else {
        for (USI j = 0; j < numPhase - 1; j++) {
            if (!phaseExist[j]) {  // skip
                xijPN += numCom * ncol;
                continue;
            }
            const USI bId = j * numCom;
            for (USI i = 0; i < NC; i++) {
                // dP
                xiP[j] += xix[bId + i] * xijPN[0];
                rhoP[j] += rhox[bId + i] * xijPN[0];
                muP[j] += mux[bId + i] * xijPN[0];
                xijPN++;
                // xiN
                for (USI m = 0; m < NC; m++) {
                    xiN[bId + m] += xix[bId + i] * xijPN[m];
                    rhoN[bId + m] += rhox[bId + i] * xijPN[m];
                    muN[bId + m] += mux[bId + i] * xijPN[m];
                }
                xijPN += numCom;
            }
            // skip water component
            xijPN += ncol;
        }
    }
}
CalXiRhoMuPN_pfullxn()
void MixtureComp::CalXiRhoMuPN_pfullxn (const bool & xflag = true)
Definition at line 3560 of file MixtureComp.cpp.
{
    // Using dXsdXp
    // s: S,n; p: P,N  Call CaldXsdXpAPI03, CaldXsdXpAPI02p before
    // CalXiPn_partial(); CalRhoPn_partial(); CalMuPn_partial() have been called
    if (NP == 1 && !xflag) {
        const USI j1 = phaseLabel[0];
        const USI bId = j1 * numCom;
        // dN
        for (USI i = 0; i < NC; i++) {
            xiN[bId + i] = xix[bId + i];
            rhoN[bId + i] = rhox[bId + i];
            muN[bId + i] = mux[bId + i];
        }
    }
    else {
        const USI ncol = numCom + 1;
        const OCP_DBL* xijPN = &dXsdXp[(NP + 1) * ncol];
        for (USI j = 0; j < numPhase - 1; j++) {
            if (!phaseExist[j]) // skip
                continue;
            const USI bId = j * numCom;
            for (USI i = 0; i < NC; i++) {
                // dP
                xiP[j] += xix[bId + i] * xijPN[0];
                rhoP[j] += rhox[bId + i] * xijPN[0];
                muP[j] += mux[bId + i] * xijPN[0];
                xijPN++;
                // xiN
                for (USI m = 0; m < NC; m++) {
                    xiN[bId + m] += xix[bId + i] * xijPN[m];
                    rhoN[bId + m] += rhox[bId + i] * xijPN[m];
                    muN[bId + m] += mux[bId + i] * xijPN[m];
                }
                xijPN += numCom;
            }
            // don't skip water component
        }
    }
}
CheckSplit()
bool MixtureComp::CheckSplit ()
Definition at line 1541 of file MixtureComp.cpp.
{
    if (NP == 2) {
        OCP_DBL tmp   = 0;
        OCP_DBL nuMax = max(nu[0], nu[1]);
        for (USI i = 0; i < NC; i++) {
            tmp += (x[0][i] - x[1][i]) * (x[0][i] - x[1][i]);
        }
        if (nuMax < 1 && EoSctrl.NRsp.conflag && isfinite(tmp)) {
            // accept this result
        } else {
            if (!isfinite(tmp) || (1 - nuMax) < 1E-3) {
                // single phase
                // cout << "-------------------------------------------" << endl;
                // cout << fixed << scientific << setprecision(12);
                // cout << Yt << "   " << nu[0] << "   " << nu[1] << "   ";
                // cout << sqrt(EoSctrl.SSMsp.realTol) << "   " << EoSctrl.SSMsp.conflag
                // << "   "; cout << sqrt(EoSctrl.NRsp.realTol) << "   " <<
                // EoSctrl.NRsp.conflag << endl; for (USI i = 0; i < NC; i++)   cout <<
                //zi[i] << "   "; cout << endl; for (USI j = 0; j < NP; j++) {  for (USI
                //i = 0; i < NC; i++) {         cout << x[j][i] << "   ";
                //  }
                //  cout << endl;
                //}
                NP    = 1;
                x[0]  = zi;
                nu[0] = 1;
                CalAjBj(Aj[0], Bj[0], x[0]);
                SolEoS(Zj[0], Aj[0], Bj[0]);
                EoSctrl.SSMsta.conflag = false;
                EoSctrl.NRsta.conflag = false;
                return false;
            }
        }
    }
    return true;
}
CopyPhase()
void MixtureComp::CopyPhase ()
Copy the basic properties from MixtureComp to Mixture.
Definition at line 2155 of file MixtureComp.cpp.
{
    // copy v, x, mu, xi, rho
    for (USI j = 0; j < NP; j++) {
        const USI j1 = phaseLabel[j];
        v[j1]  = vC[j];
        Dcopy(NC, &xij[j1 * numCom], &x[j][0]);
        mu[j1]  = muC[j];
        xi[j1]  = xiC[j];
        rho[j1] = rhoC[j];
        nj[j1] = nu[j];
    }
}
References Dcopy(), Mixture::mu, Mixture::nj, Mixture::numCom, Mixture::rho, Mixture::v, Mixture::xi, and Mixture::xij.
CubicRoot()
USI MixtureComp::CubicRoot (const OCP_DBL & a, const OCP_DBL & b, const OCP_DBL & c, const bool & NTflag = false) const
Result is stored in Ztmp.
Definition at line 4844 of file MixtureComp.cpp.
{
    OCP_DBL Q = (a * a - 3 * b) / 9;
    OCP_DBL R = (2 * a * a * a - 9 * a * b + 27 * c) / 54;
    OCP_DBL Q3 = Q * Q * Q;
    OCP_DBL M  = R * R - Q3;
    if (M <= 0) {
        // 3 real roots
        OCP_DBL theta = acos(R / sqrt(Q3));
        Ztmp[0]       = -2 * sqrt(Q) * cos(theta / 3) - a / 3;
        Ztmp[1]       = -2 * sqrt(Q) * cos((theta + 2 * PI) / 3) - a / 3;
        Ztmp[2]       = -2 * sqrt(Q) * cos((theta - 2 * PI) / 3) - a / 3;
        if (NTflag) {
            NTcubicroot(Ztmp[0], a, b, c);
            NTcubicroot(Ztmp[1], a, b, c);
            NTcubicroot(Ztmp[2], a, b, c);
        }
        sort(Ztmp.begin(), Ztmp.end());
        // vector<OCP_DBL> e(3, 0);
        // for (USI i = 0; i < 3; i++) {
        //  e[i] = Ztmp[i] * (Ztmp[i] * (Ztmp[i] + a) + b) + c;
        //}
        // for (USI i = 0; i < 3; i++) {
        //  cout << scientific << e[i] << "\t";
        //}
        return 3;
    } else {
        OCP_DBL tmp1 = -R + sqrt(M);
        OCP_DBL tmp2 = R + sqrt(M);
        OCP_DBL S    = signD(tmp1) * pow(fabs(tmp1), 1.0 / 3);
        OCP_DBL T    = -signD(tmp2) * pow(fabs(tmp2), 1.0 / 3);
        Ztmp[0]      = S + T - a / 3;
        if (NTflag) {
            NTcubicroot(Ztmp[0], a, b, c);
        }
        // vector<OCP_DBL> e(1, 0);
        // for (USI i = 0; i < 1; i++) {
        //  e[i] = Ztmp[i] * (Ztmp[i] * (Ztmp[i] + a) + b) + c;
        //}
        // for (USI i = 0; i < 1; i++) {
        //  cout << scientific << e[i] << "\t";
        //}
        return 1;
    }
}
References PI, Mixture::S, and signD().
FindMWmax()
USI MixtureComp::FindMWmax ()
Definition at line 893 of file MixtureComp.cpp.
{
    // find the phase id with the highest Molecular Weight
    USI     tmpId = 0;
    OCP_DBL tmpMW = MW[0];
    for (USI j = 1; j < NP; j++) {
        if (tmpMW < MW[j]) {
            tmpMW = MW[j];
            tmpId = j;
        }
    }
    return tmpId;
}
Flash()
void MixtureComp::Flash (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Niin, const USI & ftype, const USI & lastNP, const OCP_DBL * lastKs) override virtual
Flash calculation with moles of components.
Implements Mixture.
Definition at line 237 of file MixtureComp.cpp.
{
    ftype = Myftype;
    lNP   = lastNP;
    if (lNP == 2) {
        Dcopy(NC, &lKs[0], lastKs);
    }
    CalFlash(Pin, Tin, Niin);
    // Calculate derivates for hydrocarbon phase and components
    // d vf / d Ni, d vf / d P
    // CalVfiVfp_full01();
    CalVfiVfp_full02();
    // Water Properties
    USI Wpid                  = numPhase - 1;
    USI Wcid                  = numCom - 1;
    phaseExist[Wpid]          = true;
    xij[Wpid * numCom + Wcid] = 1.0;
    Nt = Nh + Ni[Wcid];
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw  = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[Wpid]    = data[3];
    xi[Wpid]    = 1 / (CONV1 * bw);
    rho[Wpid]   = std_RhoW / bw;
    v[Wpid]     = CONV1 * Ni[Wcid] * bw;
    vf += v[Wpid];
    vfi[Wcid] = CONV1 * bw;
    vfp += CONV1 * Ni[Wcid] * bwp;
    // Calculate Sj
    CalSaturation();
}
References CONV1, Dcopy(), OCPTable::Eval_All(), Mixture::mu, Mixture::Ni, Mixture::Nt, Mixture::numCom, Mixture::numPhase, Mixture::phaseExist, Mixture::rho, Mixture::v, Mixture::vf, Mixture::vfi, Mixture::vfp, Mixture::xi, and Mixture::xij.
FlashDeriv()
void MixtureComp::FlashDeriv (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Niin, const USI & ftype, const USI & lastNP, const OCP_DBL * lastKs) override virtual
Flash calculation with moles of components and Calculate the derivative.
Implements Mixture.
Definition at line 278 of file MixtureComp.cpp.
{
    ftype = Myftype;
    lNP   = lastNP;
    if (lNP == 2) {
        Dcopy(NC, &lKs[0], lastKs);
    }
    CalFlash(Pin, Tin, Niin);
    // Calculate derivates for hydrocarbon phase and components
    // d vf / d Ni, d vf / d P
#ifdef OCP_NEW_FIM_n
    CalVjpVfpVfn_partial();
#else
    CalVfiVfp_full02();
#endif // OCP_NEW_FIM_n
    // Water Properties
    USI Wpid                  = numPhase - 1;
    USI Wcid                  = numCom - 1;
    phaseExist[Wpid]          = true;
    xij[Wpid * numCom + Wcid] = 1.0;
    nj[Wpid] = Ni[Wcid];
    Nt = Nh + Ni[Wcid];
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw  = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[Wpid]    = data[3];
    xi[Wpid]    = 1 / (CONV1 * bw);
    rho[Wpid]   = std_RhoW / bw;
    muP[Wpid]   = cdata[3];
    xiP[Wpid]   = -bwp / (bw * bw * CONV1);
    rhoP[Wpid]  = CONV1 * xiP[Wpid] * std_RhoW;
    v[Wpid]     = CONV1 * Ni[Wcid] * bw;
    vfi[Wcid]   = CONV1 * bw;
    const OCP_DBL vwp = CONV1 * Ni[Wcid] * bwp;
    vf += v[Wpid];
    vfp += vwp;
    vji[numPhase - 1][numCom - 1] = vfi[Wcid];
    vjp[numPhase - 1] = vwp;
    CalSaturation();
#ifdef OCP_NEW_FIM_n
    CaldXsdXpAPI03();
    CalXiPn_partial();
    CalRhoPn_partial();
    CalMuPn_partial();
    CalVfiVfp_full03();
#else
#ifdef OCP_NEW_FIM
    CaldXsdXpAPI02p();
    CalXiPNX_partial();
    CalRhoPX_partial();
    CalMuPX_partial();
#else
    CaldXsdXpAPI02();
    CalXiPNX_partial();
    CalRhoPX_partial();
    CalMuPX_partial();
#endif // OCP_NEW_FIM
#endif // OCP_NEW_FIM_n
    // Calculate pEnumCom
    fill(pEnumCom.begin(), pEnumCom.end(), 0.0);
    if (phaseExist[0]) pEnumCom[0] = NC;
    if (phaseExist[1]) pEnumCom[1] = NC;
}
References CONV1, Dcopy(), OCPTable::Eval_All(), Mixture::mu, Mixture::muP, Mixture::Ni, Mixture::nj, Mixture::Nt, Mixture::numCom, Mixture::numPhase, Mixture::pEnumCom, Mixture::phaseExist, Mixture::rho, Mixture::rhoP, Mixture::v, Mixture::vf, Mixture::vfi, Mixture::vfp, Mixture::vji, Mixture::vjp, Mixture::xi, Mixture::xij, and Mixture::xiP.
FlashDeriv_n()
void MixtureComp::FlashDeriv_n (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Niin, const OCP_DBL * Sjin, const OCP_DBL * xijin, const OCP_DBL * njin, const USI & ftype, const USI * phaseExistin, const USI & lastNP, const OCP_DBL * lastKs) override virtual
Becareful if NP > 2 (temp)
Implements Mixture.
Definition at line 357 of file MixtureComp.cpp.
{
    inputNP = 0;
    for (USI j = 0; j < numPhase; j++) {
        if (phaseExistin[j] == 1)
            inputNP++;
    }
    inputNP--;
    if (inputNP == 1 || true) {
        ftype = myftype;
        lNP = lastNP;
        if (lNP == 2) {
            Dcopy(NC, &lKs[0], lastKs);
        }
        CalFlash(Pin, Tin, Niin);
    }
    else {
        NP = inputNP;
        P = Pin; T = Tin;
        setNi(Niin);
        CalAiBi();
        Nh = Dnorm1(NC, &Ni[0]);
        for (USI j = 0; j < NP; j++) {
            phaseExist[j] = phaseExistin[j];
            S[j] = Sjin[j];
            nu[j] = njin[j];
            nj[j] = njin[j];
            Dcopy(NC, &x[j][0], &xijin[j * numCom]);
            Dcopy(NC, &xij[j * numCom], &xijin[j * numCom]);
        }
        CalFugPhiAll();
        S[numPhase - 1] = Sjin[numPhase - 1];
        phaseLabel[0] = OIL;   phaseLabel[1] = GAS;
        CalMW();
        CalVfXiRho();
        CalViscosity();
        CopyPhase();
        CalSurfaceTension();
    }
    CalVjpVfpVfn_partial();
    // Water Properties
    USI Wpid = numPhase - 1;
    USI Wcid = numCom - 1;
    phaseExist[Wpid] = true;
    xij[Wpid * numCom + Wcid] = 1.0;
    nj[Wpid] = Ni[Wcid];
    Nt = Nh + Ni[Wcid];
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[Wpid] = data[3];
    xi[Wpid] = 1 / (CONV1 * bw);
    rho[Wpid] = std_RhoW / bw;
    muP[Wpid] = cdata[3];
    xiP[Wpid] = -bwp / (bw * bw * CONV1);
    rhoP[Wpid] = CONV1 * xiP[Wpid] * std_RhoW;
    v[Wpid] = CONV1 * Ni[Wcid] * bw;
    vfi[Wcid] = CONV1 * bw;
    const OCP_DBL vwp = CONV1 * Ni[Wcid] * bwp;
    vf += v[Wpid];
    vfp += vwp;
    vji[numPhase - 1][numCom - 1] = vfi[Wcid];
    vjp[numPhase - 1] = vwp;
    CalSaturation();
    // calculate diff
    if (inputNP == NP && NP == 2 && false) {
        cout << scientific << setprecision(3);
        cout << "--------- " << NP << " --------- " << inputNP << endl;
        for (USI j = 0; j < NP; j++) {
            USI j1 = phaseLabel[j];
            cout << setw(10) << S[j1] - Sjin[j1] << "   "
                << setw(10) << (nj[j1] - njin[j1]) / njin[j1] << "   ";
            for (USI i = 0; i < NC; i++) {
                cout << setw(10) << xij[j1 * numCom + i] - xijin[j1 * numCom + i] << "   ";
            }
            cout << endl;
        }
        cout << S[2] - Sjin[2] << endl;
    }
    CaldXsdXpAPI03();
    CalXiPn_partial();
    CalRhoPn_partial();
    CalMuPn_partial();
    CalVfiVfp_full03();
    // Calculate pEnumCom
    fill(pEnumCom.begin(), pEnumCom.end(), 0.0);
    if (phaseExist[0]) pEnumCom[0] = NC;
    if (phaseExist[1]) pEnumCom[1] = NC;
}
References CONV1, CopyPhase(), Dcopy(), Dnorm1(), OCPTable::Eval_All(), GAS, Mixture::mu, Mixture::muP, Mixture::Ni, Mixture::nj, Mixture::Nt, Mixture::numCom, Mixture::numPhase, OIL, Mixture::pEnumCom, Mixture::phaseExist, Mixture::rho, Mixture::rhoP, Mixture::S, Mixture::v, Mixture::vf, Mixture::vfi, Mixture::vfp, Mixture::vji, Mixture::vjp, Mixture::xi, Mixture::xij, and Mixture::xiP.
GammaPhaseG()
OCP_DBL MixtureComp::GammaPhaseG (const OCP_DBL & Pin) inline override virtual
return gamma of gas phase, gamma equals to mass density times gravity factor.
Implements Mixture.
Definition at line 185 of file MixtureComp.hpp.
{ OCP_ABORT("Should not be used in Compositional mode!"); };
References OCP_ABORT.
GammaPhaseO()
OCP_DBL MixtureComp::GammaPhaseO (const OCP_DBL & Pin, const OCP_DBL & Pbbin) inline override virtual
return gamma of oil phase, gamma equals to mass density times gravity factor.
Implements Mixture.
Definition at line 184 of file MixtureComp.hpp.
{ OCP_ABORT("Should not be used in Compositional mode!"); };
References OCP_ABORT.
GammaPhaseOG()
OCP_DBL MixtureComp::GammaPhaseOG (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Ziin) override virtual
return gamma of hydrocarbon mixture, gamma equals to mass density times gravity factor.
Implements Mixture.
Definition at line 547 of file MixtureComp.cpp.
{
    // assume that only single phase exists here, no matter it's oil or gas
    OCP_DBL rhotmp = RhoPhase(Pin, Tin, Ziin);
    return rhotmp * GRAVITY_FACTOR;
}
References GRAVITY_FACTOR, and RhoPhase().
GammaPhaseW()
OCP_DBL MixtureComp::GammaPhaseW (const OCP_DBL & Pin) override virtual
return gamma of water phase, gamma equals to mass density times gravity factor.
Implements Mixture.
Definition at line 536 of file MixtureComp.cpp.
{
    PVTW.Eval_All(0, Pin, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw  = (bw0 * (1 - cbw * (Pin - Pw0)));
    return std_GammaW / bw;
}
References OCPTable::Eval_All().
GetErrorPEC()
OCP_DBL MixtureComp::GetErrorPEC () inline override virtual
Implements Mixture.
Definition at line 131 of file MixtureComp.hpp.
{ return ePEC; }
GetFlagSkip()
bool MixtureComp::GetFlagSkip () inline override virtual
Implements Mixture.
Definition at line 350 of file MixtureComp.hpp.
{ return flagSkip; }
GetFtype()
USI MixtureComp::GetFtype () inline override virtual
Implements Mixture.
Definition at line 194 of file MixtureComp.hpp.
{ return ftype; }
GetMinEigenSkip()
OCP_SIN MixtureComp::GetMinEigenSkip () inline override virtual
Implements Mixture.
Definition at line 349 of file MixtureComp.hpp.
{ return eigenSkip[0]; }
GetNRSPiters()
OCP_ULL MixtureComp::GetNRSPiters () inline override virtual
Implements Mixture.
Definition at line 135 of file MixtureComp.hpp.
{ return NRSPiters; }
GetNRSTAiters()
OCP_ULL MixtureComp::GetNRSTAiters () inline override virtual
Implements Mixture.
Definition at line 133 of file MixtureComp.hpp.
{ return NRSTAiters; }
GetSSMSPiters()
OCP_ULL MixtureComp::GetSSMSPiters () inline override virtual
Implements Mixture.
Definition at line 134 of file MixtureComp.hpp.
{ return SSMSPiters; }
GetSSMSTAiters()
OCP_ULL MixtureComp::GetSSMSTAiters () inline override virtual
Implements Mixture.
Definition at line 132 of file MixtureComp.hpp.
{ return SSMSTAiters; }
GetSurTen()
OCP_DBL MixtureComp::GetSurTen () inline override virtual
Implements Mixture.
Definition at line 196 of file MixtureComp.hpp.
{ return surTen; }
IdentifyPhase()
void MixtureComp::IdentifyPhase ()
Definition at line 2121 of file MixtureComp.cpp.
{
    phaseExist[0] = false;
    phaseExist[1] = false;
    if (NP == 1) {
        // Critical Temperature Method
        OCP_DBL A = 0;
        OCP_DBL B = 0;
        for (USI i = 0; i < NC; i++) {
            A += x[0][i] * Vc[i] * Tc[i];
            B += x[0][i] * Vc[i];
        }
        OCP_DBL Tc = A / B;
        if (T > Tc) {
            phaseLabel[0] = GAS;
            phaseExist[1] = true;
        } else {
            phaseLabel[0] = OIL;
            phaseExist[0] = true;
        }
    } else {
        // Compare MW
        if (MW[0] > MW[1]) {
            phaseLabel[0] = OIL;
            phaseLabel[1] = GAS;
        } else {
            phaseLabel[0] = GAS;
            phaseLabel[1] = OIL;
        }
        phaseExist[0] = true;
        phaseExist[1] = true;
    }
}
InitFlash()
void MixtureComp::InitFlash (const OCP_DBL & Pin, const OCP_DBL & Pbbin, const OCP_DBL & Tin, const OCP_DBL * Sjin, const OCP_DBL & Vpore, const OCP_DBL * Ziin) override virtual
flash calculation with saturation of phases.
Implements Mixture.
Definition at line 174 of file MixtureComp.cpp.
{
    // Attention: zi[numCom - 1] = 0 here, that's Zw = 0;
    ftype = 0;
    lNP   = 0;
    Nh    = 1;
    nu[0] = 1;
    setPT(Pin, Tin);
    setZi(Ziin);
    PhaseEquilibrium();
    // Attention Nt = 1 now
    CalMW();
    CalVfXiRho();
    CalViscosity();
    CalSurfaceTension();
    IdentifyPhase();
    CopyPhase();
    // Calulate Nt, water is exclued
    OCP_DBL Sw = Sjin[numPhase - 1];
    Nh         = Vpore * (1 - Sw) / vf;
    // Next, nu represents moles of phase instead of molar fraction of phase
    Dscalar(NP, Nh, &nu[0]);
    // correct vj, vf with new Nt
    Dscalar(NPmax, Nh, &v[0]);
    vf *= Nh;
    //CalVfiVfp_full01();
    CalVfiVfp_full02();
    // Calculate Ni
    for (USI i = 0; i < NC; i++) {
        Ni[i] = zi[i] * Nh;
    }
    // Water Properties
    USI Wpid                  = numPhase - 1;
    USI Wcid                  = numCom - 1;
    phaseExist[Wpid]          = true;
    xij[Wpid * numCom + Wcid] = 1.0;
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw  = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[Wpid]    = data[3];
    xi[Wpid]    = 1 / (CONV1 * bw);
    rho[Wpid]   = std_RhoW / bw;
    Ni[Wcid]    = Vpore * Sw * xi[Wpid];
    Nt = Nh + Ni[Wcid];
    v[Wpid] = CONV1 * Ni[Wcid] * bw;
    vf += v[Wpid];
    vfi[Wcid] = CONV1 * bw;
    vfp += CONV1 * Ni[Wcid] * bwp;
    // Calculate Sj
    CalSaturation();
}
References CONV1, CopyPhase(), Dscalar(), OCPTable::Eval_All(), Mixture::mu, Mixture::Ni, Mixture::Nt, Mixture::numCom, Mixture::numPhase, Mixture::phaseExist, Mixture::rho, Mixture::v, Mixture::vf, Mixture::vfi, Mixture::vfp, Mixture::xi, and Mixture::xij.
PhaseEquilibrium()
void MixtureComp::PhaseEquilibrium ()
Definition at line 989 of file MixtureComp.cpp.
{
    NP   = 1;
    x[0] = zi;
    CalAiBi();
    CalAjBj(Aj[0], Bj[0], x[0]);
    SolEoS(Zj[0], Aj[0], Bj[0]);
    flagSkip = true;
    // tmpFtype = ftype;
    // ftype = 0;
    switch (ftype) {
        case 0:
            // flash from single phase
            CalKwilson();
            while (!PhaseStable()) {
                NP++;
                PhaseSplit();
                if (NP == NPmax || NP == 1) break;
            }
            // record error
            if (NP == 1) {
                if (EoSctrl.NRsta.conflag)
                    ePEC = EoSctrl.NRsta.realTol;
                else if (EoSctrl.SSMsta.conflag)
                    ePEC = EoSctrl.SSMsta.realTol;
                else
                    ePEC = 1E8;
            }
            else {
                if (EoSctrl.NRsp.conflag)
                    ePEC = EoSctrl.NRsp.realTol;
                else if (EoSctrl.SSMsp.conflag)
                    ePEC = EoSctrl.SSMsp.realTol;
                else
                    ePEC = 1E8;
            }
            break;
        case 1:
            // Skip Phase Stability analysis, only single phase exists
            NP = 1;
            // record error
            ePEC = 0.0;
            break;
        case 2: // not used now
            // Skip Phase Stability analysis, two phases exist
            CalKwilson();
            NP                    = 2;
            EoSctrl.SSMsp.conflag = false;
            EoSctrl.NRsp.conflag  = false;
            Ks[NP - 2]            = Kw[0];
            SplitSSM(true);
            SplitNR();
            while (!EoSctrl.NRsp.conflag) {
                SplitSSM(true);
                SplitNR();
                if (!CheckSplit()) break;
                if (EoSctrl.SSMsp.conflag) break;
            }
            CheckSplit();
            break;
        default:
            OCP_ABORT("Wrong flash type!");
            break;
    }
    if (NP > 1)  flagSkip = false;
    if (NP == 1 && ftype == 0 && flagSkip) {
        CalPhiNSTA();
        AssembleSkipMatSTA();
#ifdef _DEBUG
        if (!CheckNan(skipMatSTA.size(), &skipMatSTA[0])) {
            OCP_WARNING("Nan in skipMatSTA!");
        }
#endif // _DEBUG
        MinEigenSY(NC, &skipMatSTA[0], &eigenSkip[0], &eigenWork[0], leigenWork);
        // PrintDX(NC, &eigenSkip[0]);
        // cout << "done!" << endl;
    }
}
PhaseSplit()
void MixtureComp::PhaseSplit ()
Definition at line 1507 of file MixtureComp.cpp.
{
    EoSctrl.SSMsp.conflag = false;
    EoSctrl.SSMsp.curIt = 0;
    EoSctrl.NRsp.conflag = false;
    EoSctrl.NRsp.curIt = 0;
    SplitSSM(false);
    SplitNR();
    while (!EoSctrl.NRsp.conflag) {
        SplitSSM(true);
        SplitNR();
        if (!CheckSplit()) break;
        if (EoSctrl.SSMsp.conflag) break;
    }
    CheckSplit();
    SSMSPiters += EoSctrl.SSMsp.curIt;
    NRSPiters += EoSctrl.NRsp.curIt;
    //cout << scientific << setprecision(8);
    //for (USI i = 0; i < NC; i++) {
    //    cout << x[0][i] / x[1][i] << "   ";
    //}
    //cout << endl;
    //cout << "Yt = " << scientific << setprecision(12) << Yt << "   "
    //    << setw(3) << "SSMtol = " << setprecision(6) << sqrt(EoSctrl.SSMsp.realTol) << "   "
    //    << setw(3) << EoSctrl.SSMsp.curIt << "   "
    //    << setw(3) << "NRtol = " << setprecision(6) << EoSctrl.NRsp.realTol << "   "
    //    << setw(3) << EoSctrl.NRsp.curIt << "   "
    //    << setw(2) << lNP << "   " << setw(2) << NP << "   "
    //    << (lNP == NP ? "N" : "Y") << "   ";
}
PhaseStable()
bool MixtureComp::PhaseStable ()
Definition at line 1076 of file MixtureComp.cpp.
{
    if (NP == 1) {
        testPId = 0;
    } else {
        CalMW();
        testPId = FindMWmax();
    }
    EoSctrl.SSMsta.conflag = false;
    EoSctrl.SSMsta.curIt = 0;
    EoSctrl.NRsta.conflag = false;
    EoSctrl.NRsta.curIt  = 0;
    // Test if a phase is stable, if stable return true, else return false
    bool flag;
    USI  tmpNP = NP;
    if (lNP == 0) {
        // strict stability ananlysis
        flag = StableSSM(testPId);
    }
    else {
        flag = StableSSM01(testPId);
        if (!flag) tmpNP++;
        if (tmpNP != lNP) {
            flag = StableSSM(testPId);
            flagSkip = false;
        }
    }
    SSMSTAiters += EoSctrl.SSMsta.curIt;
    NRSTAiters += EoSctrl.NRsta.curIt;
    //cout << "Yt = " << setprecision(8) << scientific << Yt << "  " << setw(2)
    //    << EoSctrl.SSMsta.curIt << "  " << setw(2) << EoSctrl.NRsta.curIt << "  "
    //    << lNP << "  " << tmpNP << "  " << tmpFtype << "   "
    //    << (lNP == tmpNP ? "N" : "Y") << "  ";
    //if (lNP == 1 && tmpNP == 2 && tmpFtype == 1) {
    //    cout << "AAA" << "  ";
    //}
    return flag;
}
PrintFugN()
void MixtureComp::PrintFugN ()
Definition at line 1925 of file MixtureComp.cpp.
{
    for (USI j = 0; j < NP; j++) {
        for (USI i = 0; i < NC; i++) {
            for (USI k = 0; k < NC; k++) {
                cout << fugN[j][i * NC + k] << "   ";
            }
            cout << endl;
        }
        cout << "---------------" << endl;
    }
}
PrintX()
void MixtureComp::PrintX ()
Definition at line 919 of file MixtureComp.cpp.
{
    for (USI j = 0; j < NP; j++) {
        for (USI i = 0; i < NC; i++) {
            cout << x[j][i] << "   ";
        }
        cout << endl;
    }
    cout << "----------------------" << endl;
}
PrintZtmp()
void MixtureComp::PrintZtmp () inline
test
Definition at line 263 of file MixtureComp.hpp.
    {
        for (auto z : Ztmp) cout << z << "\t";
    }
RachfordRice2()
void MixtureComp::RachfordRice2 ()
Used when NP = 2.
Definition at line 1665 of file MixtureComp.cpp.
{
    const vector<OCP_DBL>& Ktmp = Ks[0];
    OCP_DBL                Kmin = Ktmp[0];
    OCP_DBL                Kmax = Ktmp[0];
    for (USI i = 1; i < NC; i++) {
        if (Ktmp[i] < Kmin) Kmin = Ktmp[i];
        if (Ktmp[i] > Kmax) Kmax = Ktmp[i];
    }
    OCP_DBL numin = 1 / (1 - Kmax);
    OCP_DBL numax = 1 / (1 - Kmin);
    nu[0] = 0.5 * (numin + numax);
    // Solve RR with NR
    fill(tmpRR.begin(), tmpRR.end(), 0);
    OCP_DBL rj, J, dnuj, tmp;
    USI     iter  = 0;
    OCP_DBL RRtol = EoSctrl.RR.tol;
    while (true) {
        rj = 0;
        J  = 0;
        for (USI i = 0; i < NC; i++) {
            tmpRR[i] = 1 + nu[0] * (Ktmp[i] - 1);
            rj += zi[i] * (Ktmp[i] - 1) / tmpRR[i];
            J -= zi[i] * (Ktmp[i] - 1) * (Ktmp[i] - 1) / (tmpRR[i] * tmpRR[i]);
        }
        if (fabs(rj) < RRtol || iter > EoSctrl.RR.maxIt) break;
        dnuj = -rj / J;
        tmp  = nu[0] + dnuj;
        if (tmp < numax && tmp > numin) {
            nu[0] = tmp;
        } else {
            if (dnuj > 0) {
                nu[0] = (nu[0] + numax) / 2;
            } else {
                nu[0] = (nu[0] + numin) / 2;
            }
        }
        iter++;
    }
    // if (iter > EoSctrl.RR.maxIt) {
    //  OCP_WARNING("RR2 not converged!");
    //}
    nu[1] = 1 - nu[0];
#ifdef DEBUG
    cout << nu[0] << endl;
#endif // DEBUG
}
References RRparam::maxIt, and RRparam::tol.
RachfordRice3()
void MixtureComp::RachfordRice3 ()
Used when NP > 2.
Definition at line 1725 of file MixtureComp.cpp.
{
}
RhoPhase()
OCP_DBL MixtureComp::RhoPhase (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Ziin) override virtual
return mass density of phase.
Implements Mixture.
Definition at line 517 of file MixtureComp.cpp.
{
    OCP_DBL xitmp = XiPhase(Pin, Tin, Ziin);
    OCP_DBL rhotmp;
    // assume that only single phase exists here
    if (Ziin[numCom - 1] > 1 - 1e-6) {
        // water phase
        rhotmp = std_RhoW * (CONV1 * xitmp);
        return rhotmp;
    } else {
        // hydrocarbon phase
        x[0] = zi;
        CalMW();
        rhotmp = MW[0] * xitmp;
        return rhotmp;
    }
}
References CONV1, Mixture::numCom, and XiPhase().
setNi()
void MixtureComp::setNi (const OCP_DBL * Niin) inline
Definition at line 192 of file MixtureComp.hpp.
{ Dcopy(numCom, &Ni[0], Niin); }
setPT()
void MixtureComp::setPT (const OCP_DBL & p, const OCP_DBL & t) inline
Definition at line 189 of file MixtureComp.hpp.
{ P = p; T = t; }
setZi() [1/2]
void MixtureComp::setZi () inline
Definition at line 191 of file MixtureComp.hpp.
{ for (USI i = 0; i < NC; i++) zi[i] = Ni[i] / Nh; }
setZi() [2/2]
void MixtureComp::setZi (const OCP_DBL * Ziin) inline
Definition at line 190 of file MixtureComp.hpp.
{ Dcopy(NC, &zi[0], Ziin); }
SolEoS()
void MixtureComp::SolEoS (OCP_DBL & ZjT, const OCP_DBL & AjT, const OCP_DBL & BjT) const
Definition at line 596 of file MixtureComp.cpp.
{
    const OCP_DBL aj = AjT;
    const OCP_DBL bj = BjT;
    const OCP_DBL a = (delta1 + delta2 - 1) * bj - 1;
    const OCP_DBL b =
        (aj + delta1 * delta2 * bj * bj - (delta1 + delta2) * bj * (bj + 1));
    const OCP_DBL c = -(aj * bj + delta1 * delta2 * bj * bj * (bj + 1));
    USI flag = CubicRoot(a, b, c, true); // True with NT
    if (flag == 1) {
        ZjT = Ztmp[0];
    } else {
        OCP_DBL zj1 = Ztmp[0];
        OCP_DBL zj2 = Ztmp[2];
        OCP_DBL dG  = (zj2 - zj1) + log((zj1 - bj) / (zj2 - bj)) -
                     aj / (bj * (delta2 - delta1)) *
                         log((zj1 + delta1 * bj) * (zj2 + delta2 * bj) /
                             ((zj1 + delta2 * bj) * (zj2 + delta1 * bj)));
        if (dG > 0)
            ZjT = zj1;
        else
            ZjT = zj2;
    }
}
SplitNR()
void MixtureComp::SplitNR ()
Definition at line 1744 of file MixtureComp.cpp.
{
    EoSctrl.NRsp.conflag = false;
    for (USI j = 0; j < NP; j++) {
        nu[j] = fabs(nu[j]);
    }
    USI len = NC * (NP - 1);
    x2n();
    CalResSP();
    OCP_DBL eNR0;
    OCP_DBL eNR   = Dnorm2(len, &resSP[0]);
    OCP_DBL NRtol = EoSctrl.NRsp.tol;
    OCP_DBL alpha;
#ifdef DEBUG
    cout << "NRSP Begins!\n";
#endif
    OCP_DBL en;
    USI     iter = 0;
    eNR0         = eNR;
    while (eNR > NRtol) {
        // eNR0 = eNR;
        ln = n;
        CalFugNAll();
        AssembleJmatSP();
        // LUSolve(1, len, &JmatSP[0], &resSP[0], &pivot[0]);
        // PrintDX(NC, &resSP[0]);
        SYSSolve(1, &uplo, len, &JmatSP[0], &resSP[0], &pivot[0], &JmatWork[0], lJmatWork);
        // PrintDX(NC, &resSP[0]);
        alpha = CalStepNRsp();
        n[NP - 1] = zi;
        for (USI j = 0; j < NP - 1; j++) {
            Daxpy(NC, alpha, &resSP[j * NC], &n[j][0]);
            Daxpy(NC, -1, &n[j][0], &n[NP - 1][0]);
            nu[j] = Dnorm1(NC, &n[j][0]);
            for (USI i = 0; i < NC; i++) {
                x[j][i] = n[j][i] / nu[j];
            }
#ifdef DEBUG
            PrintDX(NC, &x[j][0]);
#endif
        }
        for (USI i = 0; i < NC; i++) {
            n[NP - 1][i] = fabs(n[NP - 1][i]);
        }
        nu[NP - 1] = Dnorm1(NC, &n[NP - 1][0]);
        for (USI i = 0; i < NC; i++) {
            x[NP - 1][i] = n[NP - 1][i] / nu[NP - 1];
        }
#ifdef DEBUG
        PrintDX(NC, &x[NP - 1][0]);
        cout << "---------------------" << endl;
#endif
        CalFugPhiAll();
        CalResSP();
        eNR = Dnorm2(len, &resSP[0]);
        iter++;
        if (eNR > eNR0 || iter > EoSctrl.NRsp.maxIt) {
            break;
        }
        // Maybe it should be execute before "eNR > eNR0 || iter > EoSctrl.NRsp.maxIt"
        en = 0;
        for (USI j = 0; j < NP; j++) {
            Daxpy(NC, -1, &n[j][0], &ln[j][0]);
            en += Dnorm2(NC, &ln[j][0]);
        }
        if (en / (NP * NC) < 1E-8) {
            EoSctrl.NRsp.conflag = true;
            break;
        }
    }
    EoSctrl.NRsp.realTol = eNR;
    if (eNR < NRtol) EoSctrl.NRsp.conflag = true;
    EoSctrl.NRsp.curIt += iter;
}
SplitSSM()
void MixtureComp::SplitSSM (const bool & flag)
Definition at line 1583 of file MixtureComp.cpp.
{
#ifdef DEBUG
    cout << "SSMSP Begins!" << endl;
#endif
    if (NP == 2) {
        SplitSSM2(flag);
    } else {
        SplitSSM3(flag);
    }
}
SplitSSM2()
void MixtureComp::SplitSSM2 (const bool & flag)
Definition at line 1596 of file MixtureComp.cpp.
{
    // NP = 2 in this case
    // Ks is very IMPORTANT!
    // flag = true : Restart SSM
    // flag = false : New SSM
    EoSctrl.SSMsp.conflag = true;
    OCP_DBL Se            = 1;
    OCP_DBL Stol          = EoSctrl.SSMsp.tol2;
    USI     maxIt         = EoSctrl.SSMsp.maxIt;
    if (!flag) {
        if (lNP == 2) {
            Ks[NP - 2] = lKs;
        }
        else {
            if (Yt < 1.1 || true) {
                Ks[NP - 2] = Kw[0];
            }
            else {
                for (USI i = 0; i < NC; i++) {
                    // Ks[NP - 2][i] = phi[testPId][i] / phiSta[i];
                    Ks[NP - 2][i] = Y[i] / x[testPId][i];
                }
            }
        }
    } else {
        Stol *= 1E-1;
        maxIt *= 2;
    }
    if (Yt < 1.1) {
        Stol *= 1E-1;
        maxIt *= 2;
    }
#ifdef DEBUG
    PrintX();
#endif // DEBUG
    USI iter = 0;
    while (Se > Stol) {
        RachfordRice2();
        UpdateXRR();
        CalFugPhiAll();
        Se = 0;
        for (USI i = 0; i < NC; i++) {
            Se += pow(fug[1][i] / fug[0][i] - 1, 2);
            Ks[0][i] = phi[1][i] / phi[0][i];
        }
#ifdef DEBUG
        PrintX();
#endif // DEBUG
        iter++;
        if (iter > maxIt) {
            // OCP_WARNING("SSM not converged in Phase Spliting!");
            EoSctrl.SSMsp.conflag = false;
            break;
        }
    }
    EoSctrl.SSMsp.realTol = sqrt(Se);
    EoSctrl.SSMsp.curIt += iter;
}
SplitSSM3()
void MixtureComp::SplitSSM3 (const bool & flag)
Definition at line 1663 of file MixtureComp.cpp.
{}
StableNR()
bool MixtureComp::StableNR (const USI & Id)
Definition at line 1317 of file MixtureComp.cpp.
{
#ifdef DEBUG
    cout << endl << "Stable NR Begins !" << endl << endl;
#endif // DEBUG
    for (USI i = 0; i < NC; i++) {
        resSTA[i] = log(fug[Id][i] / (fugSta[i] * Yt));
    }
#ifdef DEBUG
    // PrintDX(NC, &resSTA[0]);
#endif // DEBUG
    USI     maxIt = EoSctrl.NRsta.maxIt;
    OCP_DBL Stol  = EoSctrl.NRsta.tol;
    OCP_DBL Se    = Dnorm2(NC, &resSTA[0]);
    OCP_DBL alpha = 1;
    USI     iter  = 0;
    // OCP_DBL Se0   = Se;
    while (Se > Stol) {
        CalFugXSTA();
        AssembleJmatSTA();
        // LUSolve(1, NC, &JmatSTA[0], &resSTA[0], &pivot[0]);
        SYSSolve(1, &uplo, NC, &JmatSTA[0], &resSTA[0], &pivot[0], &JmatWork[0], lJmatWork);
        Dscalar(NC, Yt, &Y[0]);
        Daxpy(NC, alpha, &resSTA[0], &Y[0]);
        Yt = 0;
        for (USI i = 0; i < NC; i++) {
            Yt += Y[i];
        }
        Dscalar(NC, 1 / Yt, &Y[0]);
        CalFugPhi(&fugSta[0], &Y[0]);
        for (USI i = 0; i < NC; i++) {
            resSTA[i] = log(fug[Id][i] / (fugSta[i] * Yt));
        }
        Se = Dnorm2(NC, &resSTA[0]);
        iter++;
        if (iter > maxIt) {
            // cout << "---------------" << endl;
            // cout << setprecision(6) << scientific << Se0 << endl;
            // cout << setprecision(6) << scientific << Se << endl;
            // cout << setprecision(6) << scientific << Yt << endl;
            // PrintDX(NC, &x[Id][0]);
            // PrintDX(NC, &Y[0]);
            // cout << "---------------" << endl;
            EoSctrl.NRsta.curIt += iter;
            EoSctrl.NRsta.conflag = false;
            EoSctrl.NRsta.realTol = Se;
            return false;
        }
#ifdef DEBUG
        // PrintDX(NC, &resSTA[0]);
#endif // DEBUG
    }
    // if (iter > 0 && !isfinite(Se)) {
    //  cout << "---------------" << endl;
    //  cout << setprecision(6) << scientific << Se0 << endl;
    //  cout << setprecision(6) << scientific << Se << endl;
    //  cout << setprecision(6) << scientific << Yt << endl;
    //  PrintDX(NC, &x[Id][0]);
    //  PrintDX(NC, &Y[0]);
    //  cout << "done!" << endl;
    //  cout << "---------------" << endl;
    //}
    // if (Yt > 1 + 1E-8 && iter > 0) {
    //  cout << setprecision(6) << scientific << Se0 << endl;
    //  cout << setprecision(6) << scientific << Se << endl;
    //  PrintDX(NC, &x[Id][0]);
    //  PrintDX(NC, &Y[0]);
    //  cout << endl;
    //}
    EoSctrl.NRsta.curIt += iter;
    EoSctrl.NRsta.conflag = true;
    EoSctrl.NRsta.realTol = Se;
    return true;
}
StableSSM()
bool MixtureComp::StableSSM (const USI & Id)
strict SSM
Definition at line 1218 of file MixtureComp.cpp.
{
    // if unsatble, return false
    // if stable, return true
    const vector<OCP_DBL>& xj = x[Id];
    CalFugPhi(phi[Id], fug[Id], xj);
    const vector<OCP_DBL>& fugId = fug[Id];
    for (USI i = 0; i < NC; i++) {
        di[i] = phi[Id][i] * xj[i];
    }
    OCP_DBL Stol  = EoSctrl.SSMsta.tol2;
    USI     maxIt = EoSctrl.SSMsta.maxIt;
    OCP_DBL eYt   = EoSctrl.SSMsta.eYt;
    OCP_DBL Se;
    bool    flag;
    USI     iter;
    USI     k;
    // cout << "SSMBEGINS" << endl;
    for (k = 0; k < 4; k++) {
        Yt = 0;
        for (USI i = 0; i < NC; i++) {
            Y[i] = xj[i] / Kw[k][i];
            Yt += Y[i];
        }
        Dscalar(NC, 1 / Yt, &Y[0]);
        // CalFugPhi(phiSta, fugSta, Y);
        CalFugPhi(&phiSta[0], &fugSta[0], &Y[0]);
        Se = 0;
        for (USI i = 0; i < NC; i++) {
            Se += pow(log(fugSta[i] / fugId[i] * Yt), 2);
        }
        flag = true;
        iter = 0;
        // cout << "ssmbegins" << endl;
        while (Se > Stol) {
            // cout << setprecision(6) << scientific << Se;
            // cout << "         ";
            // cout << setprecision(12) << scientific << Yt;
            // cout << "         " << iter << endl;
            // PrintDX(NC, &xj[0]);
            // PrintDX(NC, &Y[0]);
            Yt = 0;
            for (USI i = 0; i < NC; i++) {
                Y[i] = di[i] / phiSta[i];
                Yt += Y[i];
            }
            Dscalar(NC, 1 / Yt, &Y[0]);
            // CalFugPhi(phiSta, fugSta, Y);
            CalFugPhi(&phiSta[0], &fugSta[0], &Y[0]);
            Se = 0;
            for (USI i = 0; i < NC; i++) {
                Se += pow(log(fugSta[i] / fugId[i] * Yt), 2);
            }
            iter++;
            if (iter > maxIt) {
                flag = false;
                break;
            }
        }
        EoSctrl.SSMsta.curIt += iter;
        flag = StableNR(Id);
        // here, a relaxation is needed, on the one hand it can prevent the influence
        // of rounding error, on the other hand, if Yt is too close to 1, phase
        // splitting calculation may get into trouble and single phase is indentified
        // finally
        if (flag && Yt > 1 + eYt) {
            // cout << "Yt = " << setprecision(12) << scientific << Yt << "    " <<
            // setw(3)
            //     << EoSctrl.SSMsta.curIt << "    " << setw(3) << EoSctrl.NRsta.curIt
            //     << "   " << flag << "   " << k << "   " << 2 << "   ";
            EoSctrl.SSMsta.conflag = true;
            EoSctrl.SSMsta.realTol = sqrt(Se);
            return false;
        }
    }
    // cout << "Yt = " << setprecision(12) << scientific << Yt << "    " << setw(3)
    //     << EoSctrl.SSMsta.curIt << "    " << setw(3) << EoSctrl.NRsta.curIt << "   "
    //     << flag << "   " << k << "   " << 1 << "   ";
    /*if (!flag) {
        OCP_WARNING("SSM not converged in Stability Analysis");
    }*/
    EoSctrl.SSMsta.realTol = sqrt(Se);
    return true;
}
References SSMparamSTA::conflag, SSMparamSTA::curIt, Dscalar(), SSMparamSTA::eYt, SSMparamSTA::maxIt, SSMparamSTA::realTol, and SSMparamSTA::tol2.
StableSSM01()
bool MixtureComp::StableSSM01 (const USI & Id)
relaxable SSM
Definition at line 1119 of file MixtureComp.cpp.
{
    // if unsatble, return false
    // if stable, return true
    OCP_DBL Stol  = EoSctrl.SSMsta.tol2;
    USI     maxIt = EoSctrl.SSMsta.maxIt;
    OCP_DBL eYt   = EoSctrl.SSMsta.eYt;
    OCP_DBL Ktol  = EoSctrl.SSMsta.Ktol;
    OCP_DBL dYtol = EoSctrl.SSMsta.dYtol;
    // OCP_DBL& Sk = EoSctrl.SSMsta.curSk;
    OCP_DBL Se, Sk, dY;
    bool    flag, Tsol; // Tsol, trivial solution
    USI     iter, k;
    const vector<OCP_DBL>& xj = x[Id];
    CalFugPhi(phi[Id], fug[Id], xj);
    const vector<OCP_DBL>& fugId = fug[Id];
    vector<OCP_DBL>&       ks    = Ks[0];
    for (k = 0; k < 2; k++) {
        ks   = Kw[k];
        iter = 0;
        flag = false;
        Tsol = false;
        while (true) {
            Yt = 0;
            for (USI i = 0; i < NC; i++) {
                Y[i] = xj[i] * ks[i];
                Yt += Y[i];
            }
            Dscalar(NC, 1 / Yt, &Y[0]);
            if (iter > 0) {
                dY = 0;
                for (USI i = 0; i < NC; i++) {
                    dY += pow((Y[i] - di[i]), 2);
                }
                if (dY < dYtol) {
                    // converges
                    flag = true;
                    break;
                }
            }
            CalFugPhi(&fugSta[0], &Y[0]);
            Se = 0;
            Sk = 0;
            for (USI i = 0; i < NC; i++) {
                di[i] = fugId[i] / (fugSta[i] * Yt);
                ks[i] *= di[i];
                Se += pow(di[i] - 1, 2);
                // Sk += pow(ks[i] - 1, 2);
                Sk += pow(log(ks[i]), 2);
            }
            iter++;
            if (Se < Stol) {
                flag = true;
                break;
            }
            if (Sk < Ktol) {
                // Sk < Ktol -> trivial solution
                flag = true;
                Tsol = true;
                break;
            }
            if (iter > maxIt) {
                break;
            }
            // Record last Y with di
            di = Y;
        }
        // if (!Tsol) {
        // flag = StableNR(Id);
        //}
        //cout << "Yt = " << setprecision(8) << scientific << Yt << "   " << setw(2)
        //    << "Sk = " << setprecision(3) << scientific << Sk << "   " << setw(2)
        //    << iter << "  ";
        EoSctrl.SSMsta.curIt += iter;
        if (flag && Yt > 1 - 0.1 && Sk > 1) {
            // close to phase boundary, or more than 1 phase, So don't skip at next step
            flagSkip = false;
        }
        if (flag && Yt > 1 + eYt) {
            EoSctrl.SSMsta.conflag = true;
            EoSctrl.SSMsta.realTol = sqrt(Se);
            return false;
        }
    }
    EoSctrl.SSMsta.realTol = sqrt(Se);
    return true;
}
References SSMparamSTA::conflag, SSMparamSTA::curIt, Dscalar(), SSMparamSTA::eYt, SSMparamSTA::Ktol, SSMparamSTA::maxIt, SSMparamSTA::realTol, and SSMparamSTA::tol2.
UpdateXRR()
void MixtureComp::UpdateXRR ()
Update X according to RR.
Definition at line 1729 of file MixtureComp.cpp.
{
    OCP_DBL tmp = 0;
    for (USI i = 0; i < NC; i++) {
        tmp = 1;
        for (USI j = 0; j < NP - 1; j++) {
            tmp += nu[j] * (Ks[j][i] - 1);
        }
        x[NP - 1][i] = zi[i] / tmp;
        for (USI j = 0; j < NP - 1; j++) {
            x[j][i] = Ks[j][i] * x[NP - 1][i];
        }
    }
}
x2n()
void MixtureComp::x2n ()
x[j][i] -> n[j][i]
Definition at line 907 of file MixtureComp.cpp.
{
    // Total moles are supposed to be 1
    for (USI j = 0; j < NP; j++) {
        // nu[j] = fabs(nu[j]);
        for (USI i = 0; i < NC; i++) {
            n[j][i] = nu[j] * x[j][i];
        }
    }
}
XiPhase()
OCP_DBL MixtureComp::XiPhase (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Ziin) override virtual
Return molar density of phase, it's used to calculate the molar density of injection fluids in injection wells.
Implements Mixture.
Definition at line 487 of file MixtureComp.cpp.
{
    // assume that only single phase exists here
    if (Ziin[numCom - 1] > 1 - 1e-6) {
        // water phase
        PVTW.Eval_All(0, Pin, data, cdata);
        OCP_DBL Pw0   = data[0];
        OCP_DBL bw0   = data[1];
        OCP_DBL cbw   = data[2];
        OCP_DBL bw    = bw0 * (1 - cbw * (P - Pw0));
        OCP_DBL xitmp = 1 / (CONV1 * bw);
        return xitmp;
    } else {
        // hydrocarbon phase
        setPT(Pin, Tin);
        setZi(Ziin);
        NP = 1;
        CalAiBi();
        CalAjBj(Aj[0], Bj[0], zi);
        SolEoS(Zj[0], Aj[0], Bj[0]);
        OCP_DBL vtmp = Zj[0] * GAS_CONSTANT * T / P;
        for (USI i = 0; i < NC; i++) {
            vtmp -= zi[i] * Vshift[i];
        }
        OCP_DBL xitmp = 1 / vtmp;
        return xitmp;
    }
}
References CONV1, OCPTable::Eval_All(), GAS_CONSTANT, and Mixture::numCom.
The documentation for this class was generated from the following files:
MixtureComp.hpp
MixtureComp.cpp