OpenCAEPoro: WellGroup Class Reference
WellGroup Class Reference
#include <WellGroup.hpp>
Public Member Functions
void InputParam (const ParamWell &paramWell)
Input param from ParamWell.
void Setup (const Grid &myGrid, const Bulk &myBulk)
Setup well in wellgroup.
void SetupWell (const Grid &myGrid, const Bulk &myBulk)
complete the information of well according to Grid and Bulk.
void SetupMixture (const Bulk &myBulk)
get the mixture from bulk -— usless now
void ApplyControl (const USI &i)
Apply the operation mode at the ith critical time.
void InitBHP (const Bulk &myBulk)
Set the initial well pressure.
void PrepareWell (const Bulk &myBulk)
Calculate well properties at the beginning of each time step.
void CalTrans (const Bulk &myBulk)
Calculate Transmissibility of Wells.
void CalFlux (const Bulk &myBulk)
Calculate volume flow rate and moles flow rate of each perforation.
void CaldG (const Bulk &myBulk)
Calculate dG.
void CalIPRT (const Bulk &myBulk, OCP_DBL dt)
Calculate Injection rate, total Injection, Production rate, total Production.
void AllocateMat (LinearSystem &myLS, const USI &bulknum) const
Calculate memory for Matrix.
void UpdateLastBHP ()
void ResetBHP ()
void UpdateLastDg ()
Reset dG to ldG for each well.
void ResetDg ()
OCP_INT CheckP (const Bulk &myBulk)
Check if unreasonable well pressure or perforation pressure occurs.
USI GetWellNum () const
Return the num of wells.
string GetWellName (const USI &i) const
Return the name of specified well.
USI GetIndex (const string &name) const
Return the index of specified well.
USI GetWellPerfNum (const USI &i) const
Return the num of perforations of well i.
USI GetMaxWellPerNum () const
Calculate mamimum num of perforations of all Wells.
void CalMaxBHPChange ()
OCP_DBL GetdBHPmax () const
OCP_DBL GetFOPR () const
Return oil production rate in field.
OCP_DBL GetFOPT () const
Return total oil production in field.
OCP_DBL GetFGPR () const
Return gas production rate in field.
OCP_DBL GetFGPT () const
Return total gas production in field.
OCP_DBL GetFWPR () const
Return water production rate in field.
OCP_DBL GetFWPT () const
Return total water production in field.
OCP_DBL GetFGIR () const
Return gas injection rate in field.
OCP_DBL GetFGIT () const
Return gas water injection in field.
OCP_DBL GetFWIR () const
Return water injection rate in field.
OCP_DBL GetFWIT () const
Return total water injection in field.
OCP_DBL GetWOPR (const USI &w) const
Return oil production rate of the wth well.
OCP_DBL GetWOPT (const USI &w) const
Return total oil production of the wth well.
OCP_DBL GetWGPR (const USI &w) const
Return gas production rate of the wth well.
OCP_DBL GetWGPT (const USI &w) const
Return total gas production of the wth well.
OCP_DBL GetWWPR (const USI &w) const
Return water production rate of the wth well.
OCP_DBL GetWWPT (const USI &w) const
Return total water production of the wth well.
OCP_DBL GetWGIR (const USI &w) const
Return gas injection rate of the wth well.
OCP_DBL GetWGIT (const USI &w) const
Return total gas injection of the wth well.
OCP_DBL GetWWIR (const USI &w) const
Return water injection rate of the wth well.
OCP_DBL GetWWIT (const USI &w) const
Return total water injection of the wth well.
OCP_DBL GetWBHP (const USI &w) const
Return the BHP of wth well.
OCP_DBL GetWellDg (const USI &w, const USI &p) const
Return the pth dG of wth well.
OCP_DBL CalCFLIMPEC (const Bulk &myBulk, const OCP_DBL &dt) const
Calculate the CFL number for each perforation and return the maximum one.
void CalCFL01IMPEC (const Bulk &myBulk, const OCP_DBL &dt) const
Calculate the CFL number for each perforation and return the maximum one.
void MassConserveIMPEC (Bulk &myBulk, OCP_DBL dt)
Update moles of components in Bulks which connects to well.
void AssemblaMatIMPEC (LinearSystem &myLS, const Bulk &myBulk, const OCP_DBL &dt) const
Assemble matrix, parts related to well are included for IMPEC.
void GetSolIMPEC (const vector< OCP_DBL > &u, const OCP_USI &bId)
Get solution from solver class after linear system is solved for IMPEC.
void AssemblaMatFIM (LinearSystem &myLS, const Bulk &myBulk, const OCP_DBL &dt) const
Assemble matrix, parts related to well are included for FIM.
void GetSolFIM (const vector< OCP_DBL > &u, const OCP_USI &bId, const USI &len)
Get solution from solver class after linear system is solved for IMPEC for FIM.
void GetSol01FIM (const vector< OCP_DBL > &u, const OCP_USI &bId, const USI &len, const OCP_DBL &alpha)
void CalResFIM (ResFIM &resFIM, const Bulk &myBulk, const OCP_DBL &dt) const
Calculate Resiual and relative Resiual for FIM.
Friends
class Reservoir
Detailed Description
WellGroups contains all wells now, it's used to manages all wells uniformly in reservoirs. actually, you can regard it as an interface between wells and other modules.
Definition at line 24 of file WellGroup.hpp.
Member Function Documentation
AllocateMat()
void WellGroup::AllocateMat (LinearSystem & myLS, const USI & bulknum) const
Calculate memory for Matrix.
Definition at line 185 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    USI maxNum = GetMaxWellPerNum() + 1;
    for (USI w = 0; w < numWell; w++) {
        wellGroup[w].AllocateMat(myLS);
        myLS.EnlargeRowCap(bulknum + w, maxNum);
    }
}
References LinearSystem::EnlargeRowCap(), GetMaxWellPerNum(), and OCP_FUNCNAME.
ApplyControl()
void WellGroup::ApplyControl (const USI & i)
Apply the operation mode at the ith critical time.
Definition at line 81 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        wellGroup[w].opt = wellGroup[w].optSet[i];
    }
}
References OCP_FUNCNAME.
AssemblaMatFIM()
void WellGroup::AssemblaMatFIM (LinearSystem & myLS, const Bulk & myBulk, const OCP_DBL & dt) const
Assemble matrix, parts related to well are included for FIM.
Definition at line 359 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            switch (wellGroup[w].WellType()) {
                case INJ:
                    wellGroup[w].AssembleMatINJ_FIM(myBulk, myLS, dt);
                    break;
                case PROD:
                    wellGroup[w].AssembleMatPROD_BO_FIM(myBulk, myLS, dt);
                    break;
                default:
                    OCP_ABORT("Wrong well type");
            }
        }
    }
}
References OCP_FUNCNAME.
AssemblaMatIMPEC()
void WellGroup::AssemblaMatIMPEC (LinearSystem & myLS, const Bulk & myBulk, const OCP_DBL & dt) const
Assemble matrix, parts related to well are included for IMPEC.
Definition at line 319 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            switch (wellGroup[w].WellType()) {
                case INJ:
                    wellGroup[w].AssembleMatINJ_IMPEC(myBulk, myLS, dt);
                    break;
                case PROD:
                    wellGroup[w].AssembleMatPROD_BO_IMPEC(myBulk, myLS, dt);
                    break;
                default:
                    OCP_ABORT("Wrong well type");
            }
        }
    }
}
References OCP_FUNCNAME.
CalCFL01IMPEC()
void WellGroup::CalCFL01IMPEC (const Bulk & myBulk, const OCP_DBL & dt) const
Calculate the CFL number for each perforation and return the maximum one.
Definition at line 297 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            wellGroup[w].CalCFL01IMPEC(myBulk, dt);
        }
    }
}
References OCP_FUNCNAME.
CalCFLIMPEC()
OCP_DBL WellGroup::CalCFLIMPEC (const Bulk & myBulk, const OCP_DBL & dt) const
Calculate the CFL number for each perforation and return the maximum one.
Definition at line 282 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    OCP_DBL cflw = 0;
    OCP_DBL tmp  = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            tmp = wellGroup[w].CalCFLIMPEC(myBulk, dt);
            if (cflw < tmp) cflw = tmp;
        }
    }
    return cflw;
}
References OCP_FUNCNAME.
CaldG()
void WellGroup::CaldG (const Bulk & myBulk)
Calculate dG.
Definition at line 138 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            wellGroup[w].CaldG(myBulk);
        }
    }
}
References OCP_FUNCNAME.
CalFlux()
void WellGroup::CalFlux (const Bulk & myBulk)
Calculate volume flow rate and moles flow rate of each perforation.
Definition at line 127 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            wellGroup[w].CalFlux(myBulk);
        }
    }
}
References OCP_FUNCNAME.
CalIPRT()
void WellGroup::CalIPRT (const Bulk & myBulk, OCP_DBL dt)
Calculate Injection rate, total Injection, Production rate, total Production.
Definition at line 149 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    FGIR = 0;
    FWIR = 0;
    FOPR = 0;
    FGPR = 0;
    FWPR = 0;
    for (USI w = 0; w < numWell; w++) {
        wellGroup[w].WGIR = 0;
        wellGroup[w].WWIR = 0;
        wellGroup[w].WOPR = 0;
        wellGroup[w].WGPR = 0;
        wellGroup[w].WWPR = 0;
        if (wellGroup[w].WellState()) {
            if (wellGroup[w].WellType() == PROD) {
                wellGroup[w].CalProdQiBO(myBulk, dt);
            } else {
                wellGroup[w].CalInjQiBO(myBulk, dt);
            }
        }
        FGIR += wellGroup[w].WGIR;
        FWIR += wellGroup[w].WWIR;
        FOPR += wellGroup[w].WOPR;
        FGPR += wellGroup[w].WGPR;
        FWPR += wellGroup[w].WWPR;
    }
    FGIT += FGIR * dt;
    FWIT += FWIR * dt;
    FOPT += FOPR * dt;
    FGPt += FGPR * dt;
    FWPT += FWPR * dt;
}
References OCP_FUNCNAME.
CalMaxBHPChange()
void WellGroup::CalMaxBHPChange ()
Definition at line 268 of file WellGroup.cpp.
{
    dPmax = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            dPmax = max(dPmax, fabs(wellGroup[w].BHP - wellGroup[w].lBHP));
        }
    }
}
CalResFIM()
void WellGroup::CalResFIM (ResFIM & resFIM, const Bulk & myBulk, const OCP_DBL & dt) const
Calculate Resiual and relative Resiual for FIM.
Definition at line 408 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            wellGroup[w].CalResFIM(resFIM, myBulk, dt, wId);
            wId++;
        }
    }
    // cout << "Well  " << resFIM.maxRelRes_v;
}
References OCP_FUNCNAME.
CalTrans()
void WellGroup::CalTrans (const Bulk & myBulk)
Calculate Transmissibility of Wells.
Definition at line 116 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            wellGroup[w].CalTrans(myBulk);
        }
    }
}
References OCP_FUNCNAME.
CheckP()
OCP_INT WellGroup::CheckP (const Bulk & myBulk)
Check if unreasonable well pressure or perforation pressure occurs.
Definition at line 206 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    // 0 : All correct
    // 1   : negative P, cut the timestep and resolve
    // 2.1 : change well mode to BHP, resolve
    // 2.2 : crossflow happens, then close corresponding perf, resolve
    bool flag2 = false;
    bool flag3 = false;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            OCP_INT flag = wellGroup[w].CheckP(myBulk);
#ifdef _DEBUG
            // wellGroup[w].ShowPerfStatus();
#endif // _DEBUG
            switch (flag) {
                case 1:
                    return 1;
                case 2:
                    flag2 = true;
                    break;
                case 3:
                    flag3 = true;
                    break;
                default:
                    break;
            }
        }
    }
    if (flag2 || flag3) return 2;
    return 0;
}
References OCP_FUNCNAME.
GetdBHPmax()
OCP_DBL WellGroup::GetdBHPmax () const inline
Definition at line 89 of file WellGroup.hpp.
{ return dPmax; }
GetFGIR()
OCP_DBL WellGroup::GetFGIR () const inline
Return gas injection rate in field.
Definition at line 103 of file WellGroup.hpp.
{ return FGIR; }
GetFGIT()
OCP_DBL WellGroup::GetFGIT () const inline
Return gas water injection in field.
Definition at line 105 of file WellGroup.hpp.
{ return FGIT; }
GetFGPR()
OCP_DBL WellGroup::GetFGPR () const inline
Return gas production rate in field.
Definition at line 95 of file WellGroup.hpp.
{ return FGPR; }
GetFGPT()
OCP_DBL WellGroup::GetFGPT () const inline
Return total gas production in field.
Definition at line 97 of file WellGroup.hpp.
{ return FGPt; }
GetFOPR()
OCP_DBL WellGroup::GetFOPR () const inline
Return oil production rate in field.
Definition at line 91 of file WellGroup.hpp.
{ return FOPR; }
GetFOPT()
OCP_DBL WellGroup::GetFOPT () const inline
Return total oil production in field.
Definition at line 93 of file WellGroup.hpp.
{ return FOPT; }
GetFWIR()
OCP_DBL WellGroup::GetFWIR () const inline
Return water injection rate in field.
Definition at line 107 of file WellGroup.hpp.
{ return FWIR; }
GetFWIT()
OCP_DBL WellGroup::GetFWIT () const inline
Return total water injection in field.
Definition at line 109 of file WellGroup.hpp.
{ return FWIT; }
GetFWPR()
OCP_DBL WellGroup::GetFWPR () const inline
Return water production rate in field.
Definition at line 99 of file WellGroup.hpp.
{ return FWPR; }
GetFWPT()
OCP_DBL WellGroup::GetFWPT () const inline
Return total water production in field.
Definition at line 101 of file WellGroup.hpp.
{ return FWPT; }
GetIndex()
USI WellGroup::GetIndex (const string & name) const
Return the index of specified well.
Definition at line 245 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].name == name) {
            return w;
        }
    }
    OCP_ABORT("Well name not found!");
}
References OCP_ABORT, and OCP_FUNCNAME.
GetMaxWellPerNum()
USI WellGroup::GetMaxWellPerNum () const
Calculate mamimum num of perforations of all Wells.
Definition at line 257 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    USI m = 0;
    for (USI w = 0; w < numWell; w++) {
        m = max(m, wellGroup[w].numPerf);
    }
    return m;
}
References OCP_FUNCNAME.
GetSol01FIM()
void WellGroup::GetSol01FIM (const vector< OCP_DBL > & u, const OCP_USI & bId, const USI & len, const OCP_DBL & alpha)
Definition at line 395 of file WellGroup.cpp.
{
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            wellGroup[w].BHP += u[(bId + wId) * len] * alpha;
            wellGroup[w].UpdatePerfP();
            wId++;
        }
    }
}
GetSolFIM()
void WellGroup::GetSolFIM (const vector< OCP_DBL > & u, const OCP_USI & bId, const USI & len)
Get solution from solver class after linear system is solved for IMPEC for FIM.
Definition at line 381 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            wellGroup[w].BHP += u[(bId + wId) * len];
            wellGroup[w].UpdatePerfP();
            wId++;
        }
    }
}
References OCP_FUNCNAME.
GetSolIMPEC()
void WellGroup::GetSolIMPEC (const vector< OCP_DBL > & u, const OCP_USI & bId)
Get solution from solver class after linear system is solved for IMPEC.
Definition at line 341 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            wellGroup[w].BHP = u[bId + wId];
            wellGroup[w].UpdatePerfP();
            wId++;
        }
    }
}
References OCP_FUNCNAME.
GetWBHP()
OCP_DBL WellGroup::GetWBHP (const USI & w) const inline
Return the BHP of wth well.
Definition at line 131 of file WellGroup.hpp.
{ return wellGroup[w].BHP; }
GetWellDg()
OCP_DBL WellGroup::GetWellDg (const USI & w, const USI & p) const inline
Return the pth dG of wth well.
Definition at line 133 of file WellGroup.hpp.
{ return wellGroup[w].dG[p]; }
GetWellName()
string WellGroup::GetWellName (const USI & i) const inline
Return the name of specified well.
Definition at line 81 of file WellGroup.hpp.
{ return wellGroup[i].name; }
GetWellNum()
USI WellGroup::GetWellNum () const inline
Return the num of wells.
Definition at line 79 of file WellGroup.hpp.
{ return numWell; }
GetWellPerfNum()
USI WellGroup::GetWellPerfNum (const USI & i) const inline
Return the num of perforations of well i.
Definition at line 85 of file WellGroup.hpp.
{ return wellGroup[i].numPerf; }
GetWGIR()
OCP_DBL WellGroup::GetWGIR (const USI & w) const inline
Return gas injection rate of the wth well.
Definition at line 123 of file WellGroup.hpp.
{ return wellGroup[w].WGIR; }
GetWGIT()
OCP_DBL WellGroup::GetWGIT (const USI & w) const inline
Return total gas injection of the wth well.
Definition at line 125 of file WellGroup.hpp.
{ return wellGroup[w].WGIT; }
GetWGPR()
OCP_DBL WellGroup::GetWGPR (const USI & w) const inline
Return gas production rate of the wth well.
Definition at line 115 of file WellGroup.hpp.
{ return wellGroup[w].WGPR; }
GetWGPT()
OCP_DBL WellGroup::GetWGPT (const USI & w) const inline
Return total gas production of the wth well.
Definition at line 117 of file WellGroup.hpp.
{ return wellGroup[w].WGPT; }
GetWOPR()
OCP_DBL WellGroup::GetWOPR (const USI & w) const inline
Return oil production rate of the wth well.
Definition at line 111 of file WellGroup.hpp.
{ return wellGroup[w].WOPR; }
GetWOPT()
OCP_DBL WellGroup::GetWOPT (const USI & w) const inline
Return total oil production of the wth well.
Definition at line 113 of file WellGroup.hpp.
{ return wellGroup[w].WOPT; }
GetWWIR()
OCP_DBL WellGroup::GetWWIR (const USI & w) const inline
Return water injection rate of the wth well.
Definition at line 127 of file WellGroup.hpp.
{ return wellGroup[w].WWIR; }
GetWWIT()
OCP_DBL WellGroup::GetWWIT (const USI & w) const inline
Return total water injection of the wth well.
Definition at line 129 of file WellGroup.hpp.
{ return wellGroup[w].WWIT; }
GetWWPR()
OCP_DBL WellGroup::GetWWPR (const USI & w) const inline
Return water production rate of the wth well.
Definition at line 119 of file WellGroup.hpp.
{ return wellGroup[w].WWPR; }
GetWWPT()
OCP_DBL WellGroup::GetWWPT (const USI & w) const inline
Return total water production of the wth well.
Definition at line 121 of file WellGroup.hpp.
{ return wellGroup[w].WWPT; }
InitBHP()
void WellGroup::InitBHP (const Bulk & myBulk)
Set the initial well pressure.
Definition at line 90 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        wellGroup[w].InitBHP(myBulk);
    }
}
References OCP_FUNCNAME.
InputParam()
void WellGroup::InputParam (const ParamWell & paramWell)
Input param from ParamWell.
Definition at line 18 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    USI len = paramWell.solSet.size();
    solvents.resize(len);
    for (USI i = 0; i < len; i++) {
        solvents[i] = paramWell.solSet[i];
    }
    numWell = paramWell.well.size();
    wellGroup.resize(numWell);
    USI         t = paramWell.criticalTime.size();
    vector<USI> wellCriticalTime;
    for (USI w = 0; w < numWell; w++) {
        wellGroup[w].name  = paramWell.well[w].name;
        wellGroup[w].depth = paramWell.well[w].depth;
        wellGroup[w].I     = paramWell.well[w].I - 1;
        wellGroup[w].J     = paramWell.well[w].J - 1;
        wellGroup[w].InputPerfo(paramWell.well[w]);
        // opt
        wellGroup[w].optSet.resize(t);
        USI n = paramWell.well[w].optParam.size();
        wellCriticalTime.clear();
        wellCriticalTime.resize(n + 1);
        for (USI i = 0; i < n; i++) {
            wellCriticalTime[i] = paramWell.well[w].optParam[i].d;
        }
        wellCriticalTime.back() = t;
        for (USI i = 0; i < n; i++) {
            for (USI d = wellCriticalTime[i]; d < wellCriticalTime[i + 1]; d++) {
                wellGroup[w].optSet[d] = WellOpt(paramWell.well[w].optParam[i].opt);
            }
        }
    }
}
References ParamWell::criticalTime, OCP_FUNCNAME, ParamWell::solSet, and ParamWell::well.
MassConserveIMPEC()
void WellGroup::MassConserveIMPEC (Bulk & myBulk, OCP_DBL dt)
Update moles of components in Bulks which connects to well.
Definition at line 308 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            wellGroup[w].MassConserveIMPEC(myBulk, dt);
        }
    }
}
References OCP_FUNCNAME.
PrepareWell()
void WellGroup::PrepareWell (const Bulk & myBulk)
Calculate well properties at the beginning of each time step.
Definition at line 99 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wellGroup[w].WellState()) {
            wellGroup[w].CalTrans(myBulk);
            wellGroup[w].CalFlux(myBulk, true);
            wellGroup[w].CaldG(myBulk);
            // test
            // wellGroup[w].SmoothdG();
            wellGroup[w].CheckOptMode(myBulk);
        }
    }
}
References OCP_FUNCNAME.
ResetBHP()
void WellGroup::ResetBHP ()
Definition at line 196 of file WellGroup.cpp.
{
    for (auto& w : wellGroup) {
        if (w.WellState()) {
            w.BHP = w.lBHP;
            w.SetBHP();
        }
    }
}
ResetDg()
void WellGroup::ResetDg () inline
Definition at line 72 of file WellGroup.hpp.
    {
        for (auto& w : wellGroup) w.dG = w.ldG;
    }
Setup()
void WellGroup::Setup (const Grid & myGrid, const Bulk & myBulk)
Setup well in wellgroup.
Definition at line 57 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    SetupWell(myGrid, myBulk);
    SetupMixture(myBulk);
}
References OCP_FUNCNAME, SetupMixture(), and SetupWell().
SetupMixture()
void WellGroup::SetupMixture (const Bulk & myBulk)
get the mixture from bulk -— usless now
Definition at line 74 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    flashCal = myBulk.GetMixture();
}
References Bulk::GetMixture(), and OCP_FUNCNAME.
SetupWell()
void WellGroup::SetupWell (const Grid & myGrid, const Bulk & myBulk)
complete the information of well according to Grid and Bulk.
Definition at line 65 of file WellGroup.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        wellGroup[w].Setup(myGrid, myBulk, solvents);
    }
}
References OCP_FUNCNAME.
UpdateLastBHP()
void WellGroup::UpdateLastBHP () inline
Definition at line 62 of file WellGroup.hpp.
    {
        for (auto& w : wellGroup) w.lBHP = w.BHP;
    }
UpdateLastDg()
void WellGroup::UpdateLastDg () inline
Reset dG to ldG for each well.
Definition at line 68 of file WellGroup.hpp.
    {
        for (auto& w : wellGroup) w.ldG = w.dG;
    }
Friends And Related Function Documentation
Reservoir
friend class Reservoir friend
Definition at line 28 of file WellGroup.hpp.
The documentation for this class was generated from the following files:
WellGroup.hpp
WellGroup.cpp