OpenCAEPoro: Summary Class Reference
Summary Class Reference
The Summary class manages the output in the summary file.
#include <OCPOutput.hpp>
Public Member Functions
void InputParam (const OutputSummary &summary_param)
TODO: Add Doxygen.
void Setup (const Reservoir &reservoir, const OCP_DBL &totalTime)
TODO: Add Doxygen.
void SetVal (const Reservoir &reservoir, const OCPControl &ctrl)
TODO: Add Doxygen.
void PrintInfo (const string &dir) const
Write output information to a file.
Detailed Description
The Summary class manages the output in the summary file.
Definition at line 90 of file OCPOutput.hpp.
Member Function Documentation
InputParam()
void Summary::InputParam (const OutputSummary & summary_param)
TODO: Add Doxygen.
Definition at line 14 of file OCPOutput.cpp.
{
    FPR = summary_param.FPR;
    FOPR = summary_param.FOPR;
    FOPT = summary_param.FOPT;
    FGPR = summary_param.FGPR;
    FGPt = summary_param.FGPt;
    FWPR = summary_param.FWPR;
    FWPT = summary_param.FWPT;
    FGIR = summary_param.FGIR;
    FGIT = summary_param.FGIT;
    FWIR = summary_param.FWIR;
    FWIT = summary_param.FWIT;
    WOPR = summary_param.WOPR;
    WOPT = summary_param.WOPT;
    WGPR = summary_param.WGPR;
    WGPT = summary_param.WGPT;
    WWPR = summary_param.WWPR;
    WWPT = summary_param.WWPT;
    WGIR = summary_param.WGIR;
    WGIT = summary_param.WGIT;
    WWIR = summary_param.WWIR;
    WWIT = summary_param.WWIT;
    WBHP = summary_param.WBHP;
    DG = summary_param.DG;
    BPR = summary_param.BPR;
    SOIL = summary_param.SOIL;
    SGAS = summary_param.SGAS;
    SWAT = summary_param.SWAT;
    // cout << "Summary::InputParam" << endl;
}
References OutputSummary::BPR, OutputSummary::DG, OutputSummary::FGIR, OutputSummary::FGIT, OutputSummary::FGPR, OutputSummary::FGPt, OutputSummary::FOPR, OutputSummary::FOPT, OutputSummary::FPR, OutputSummary::FWIR, OutputSummary::FWIT, OutputSummary::FWPR, OutputSummary::FWPT, OutputSummary::SGAS, OutputSummary::SOIL, OutputSummary::SWAT, OutputSummary::WBHP, OutputSummary::WGIR, OutputSummary::WGIT, OutputSummary::WGPR, OutputSummary::WGPT, OutputSummary::WOPR, OutputSummary::WOPT, OutputSummary::WWIR, OutputSummary::WWIT, OutputSummary::WWPR, and OutputSummary::WWPT.
PrintInfo()
void Summary::PrintInfo (const string & dir) const
Write output information to a file.
Write output information in the dir/SUMMARY.out file.
Definition at line 579 of file OCPOutput.cpp.
{
    string FileOut = dir + "SUMMARY.out";
    ofstream outF(FileOut);
    if (!outF.is_open())
    {
        OCP_ABORT("Can not open " + FileOut);
    }
    USI ns = 12;
    USI col = 10;
    USI row = 0;
    USI num = Sumdata.size();
    USI len = Sumdata[0].val.size();
    USI id = 0;
    USI ID = 1;
    while (id != num)
    {
        outF << "Row " << ++row << endl;
        // Item
        // Time
        outF << "\t" << setw(ns) << Sumdata[0].Item;
        id = ID;
        for (USI i = 1; i < col; i++)
        {
            outF << "\t" << setw(ns) << Sumdata[id++].Item;
            if (id == num)
                break;
        }
        outF << endl;
        // Unit
        // Time
        outF << "\t" << setw(ns) << Sumdata[0].Unit;
        id = ID;
        for (USI i = 1; i < col; i++)
        {
            outF << "\t" << setw(ns) << Sumdata[id++].Unit;
            if (id == num)
                break;
        }
        outF << endl;
        // Obj
        // Time
        outF << "\t" << setw(ns) << Sumdata[0].Obj;
        id = ID;
        for (USI i = 1; i < col; i++)
        {
            outF << "\t" << setw(ns) << Sumdata[id++].Obj;
            if (id == num)
                break;
        }
        outF << endl;
        // Data
        for (USI l = 0; l < len; l++)
        {
            // Time
            outF << "\t" << setw(ns) << Sumdata[0].val[l];
            id = ID;
            for (USI i = 1; i < col; i++)
            {
                outF << "\t" << setw(ns) << Sumdata[id++].val[l];
                if (id == num)
                    break;
            }
            outF << endl;
        }
        ID += (col - 1);
        outF << endl;
    }
    outF.close();
}
References OCP_ABORT.
Setup()
void Summary::Setup (const Reservoir & reservoir, const OCP_DBL & totalTime)
TODO: Add Doxygen.
Definition at line 50 of file OCPOutput.cpp.
{
    Sumdata.push_back(SumPair("TIME", "  ", "DAY"));
    Sumdata.push_back(SumPair("NRiter", "  ", "  "));
    Sumdata.push_back(SumPair("LSiter", "  ", "  "));
    if (FPR)
        Sumdata.push_back(SumPair("FPR", "  ", "PSIA"));
    if (FOPR)
        Sumdata.push_back(SumPair("FOPR", "  ", "STB/DAY"));
    if (FOPT)
        Sumdata.push_back(SumPair("FOPT", "  ", "STB"));
    if (FGPR)
        Sumdata.push_back(SumPair("FGPR", "  ", "MSCF/DAY"));
    if (FGPt)
        Sumdata.push_back(SumPair("FGPT", "  ", "MSCF"));
    if (FWPR)
        Sumdata.push_back(SumPair("FWPR", "  ", "STB/DAY"));
    if (FWPT)
        Sumdata.push_back(SumPair("FWPT", "  ", "STB"));
    if (FGIR)
        Sumdata.push_back(SumPair("FGIR", "  ", "MSCF/DAY"));
    if (FGIT)
        Sumdata.push_back(SumPair("FGIT", "  ", "MSCF"));
    if (FWIR)
        Sumdata.push_back(SumPair("FWIR", "  ", "STB/DAY"));
    if (FWIT)
        Sumdata.push_back(SumPair("FWIT", "  ", "STB"));
    USI num;
    USI wellnum = reservoir.allWells.GetWellNum();
    string wellname;
    if (WOPR.activity)
    {
        if (WOPR.obj[0] == "All")
        {
            WOPR.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                wellname = reservoir.allWells.GetWellName(w);
                WOPR.obj.push_back(wellname);
                Sumdata.push_back(SumPair("WOPR", wellname, "STB/DAY"));
                WOPR.index.push_back(w);
            }
        }
        else
        {
            num = WOPR.obj.size();
            for (USI w = 0; w < num; w++)
            {
                Sumdata.push_back(SumPair("WOPR", WOPR.obj[w], "STB/DAY"));
                WOPR.index.push_back(reservoir.allWells.GetIndex(WOPR.obj[w]));
            }
        }
    }
    if (WOPT.activity)
    {
        if (WOPT.obj[0] == "All")
        {
            WOPT.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                wellname = reservoir.allWells.GetWellName(w);
                WOPT.obj.push_back(wellname);
                Sumdata.push_back(SumPair("WOPT", wellname, "STB"));
                WOPT.index.push_back(w);
            }
        }
        else
        {
            num = WOPT.obj.size();
            for (USI w = 0; w < num; w++)
            {
                Sumdata.push_back(SumPair("WOPT", WOPT.obj[w], "STB"));
                WOPT.index.push_back(reservoir.allWells.GetIndex(WOPT.obj[w]));
            }
        }
    }
    if (WGPR.activity)
    {
        if (WGPR.obj[0] == "All")
        {
            WGPR.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                wellname = reservoir.allWells.GetWellName(w);
                WGPR.obj.push_back(wellname);
                Sumdata.push_back(SumPair("WGPR", wellname, "MSCF/DAY"));
                WGPR.index.push_back(w);
            }
        }
        else
        {
            num = WGPR.obj.size();
            for (USI w = 0; w < num; w++)
            {
                Sumdata.push_back(SumPair("WGPR", WGPR.obj[w], "MSCF/DAY"));
                WGPR.index.push_back(reservoir.allWells.GetIndex(WGPR.obj[w]));
            }
        }
    }
    if (WGPT.activity)
    {
        if (WGPT.obj[0] == "All")
        {
            WGPT.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                wellname = reservoir.allWells.GetWellName(w);
                WGPT.obj.push_back(wellname);
                Sumdata.push_back(SumPair("WGPT", wellname, "MSCF"));
                WGPT.index.push_back(w);
            }
        }
        else
        {
            num = WGPT.obj.size();
            for (USI w = 0; w < num; w++)
            {
                Sumdata.push_back(SumPair("WGPT", WGPT.obj[w], "MSCF"));
                WGPT.index.push_back(reservoir.allWells.GetIndex(WGPT.obj[w]));
            }
        }
    }
    if (WWPR.activity)
    {
        if (WWPR.obj[0] == "All")
        {
            WWPR.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                wellname = reservoir.allWells.GetWellName(w);
                WWPR.obj.push_back(wellname);
                Sumdata.push_back(SumPair("WWPR", wellname, "STB/DAY"));
                WWPR.index.push_back(w);
            }
        }
        else
        {
            num = WWPR.obj.size();
            for (USI w = 0; w < num; w++)
            {
                Sumdata.push_back(SumPair("WWPR", WWPR.obj[w], "STB/DAY"));
                WWPR.index.push_back(reservoir.allWells.GetIndex(WWPR.obj[w]));
            }
        }
    }
    if (WWPT.activity)
    {
        if (WWPT.obj[0] == "All")
        {
            WWPT.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                wellname = reservoir.allWells.GetWellName(w);
                WWPT.obj.push_back(wellname);
                Sumdata.push_back(SumPair("WWPT", wellname, "STB"));
                WWPT.index.push_back(w);
            }
        }
        else
        {
            num = WWPT.obj.size();
            for (USI w = 0; w < num; w++)
            {
                Sumdata.push_back(SumPair("WWPT", WWPT.obj[w], "STB"));
                WWPT.index.push_back(reservoir.allWells.GetIndex(WWPT.obj[w]));
            }
        }
    }
    if (WGIR.activity)
    {
        if (WGIR.obj[0] == "All")
        {
            WGIR.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                wellname = reservoir.allWells.GetWellName(w);
                WGIR.obj.push_back(wellname);
                Sumdata.push_back(SumPair("WGIR", wellname, "MSCF/DAY"));
                WGIR.index.push_back(w);
            }
        }
        else
        {
            num = WGIR.obj.size();
            for (USI w = 0; w < num; w++)
            {
                Sumdata.push_back(SumPair("WGIR", WGIR.obj[w], "MSCF/DAY"));
                WGIR.index.push_back(reservoir.allWells.GetIndex(WGIR.obj[w]));
            }
        }
    }
    if (WGIT.activity)
    {
        if (WGIT.obj[0] == "All")
        {
            WGIT.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                wellname = reservoir.allWells.GetWellName(w);
                WGIT.obj.push_back(wellname);
                Sumdata.push_back(SumPair("WGIT", wellname, "MSCF"));
                WGIT.index.push_back(w);
            }
        }
        else
        {
            num = WGIT.obj.size();
            for (USI w = 0; w < num; w++)
            {
                Sumdata.push_back(SumPair("WGIT", WGIT.obj[w], "MSCF"));
                WGIT.index.push_back(reservoir.allWells.GetIndex(WGIT.obj[w]));
            }
        }
    }
    if (WWIR.activity)
    {
        if (WWIR.obj[0] == "All")
        {
            WWIR.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                wellname = reservoir.allWells.GetWellName(w);
                WWIR.obj.push_back(wellname);
                Sumdata.push_back(SumPair("WWIR", wellname, "STB/DAY"));
                WWIR.index.push_back(w);
            }
        }
        else
        {
            num = WWIR.obj.size();
            for (USI w = 0; w < num; w++)
            {
                Sumdata.push_back(SumPair("WWIR", WWIR.obj[w], "STB/DAY"));
                WWIR.index.push_back(reservoir.allWells.GetIndex(WWIR.obj[w]));
            }
        }
    }
    if (WWIT.activity)
    {
        if (WWIT.obj[0] == "All")
        {
            WWIT.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                wellname = reservoir.allWells.GetWellName(w);
                WWIT.obj.push_back(wellname);
                Sumdata.push_back(SumPair("WWIT", wellname, "STB"));
                WWIT.index.push_back(w);
            }
        }
        else
        {
            num = WWIT.obj.size();
            for (USI w = 0; w < num; w++)
            {
                Sumdata.push_back(SumPair("WWIT", WWIT.obj[w], "STB"));
                WWIT.index.push_back(reservoir.allWells.GetIndex(WWIT.obj[w]));
            }
        }
    }
    if (WBHP.activity)
    {
        if (WBHP.obj[0] == "All")
        {
            WBHP.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                wellname = reservoir.allWells.GetWellName(w);
                WBHP.obj.push_back(wellname);
                Sumdata.push_back(SumPair("WBHP", wellname, "PSIA"));
                WBHP.index.push_back(w);
            }
        }
        else
        {
            num = WBHP.obj.size();
            for (USI w = 0; w < num; w++)
            {
                Sumdata.push_back(SumPair("WBHP", WBHP.obj[w], "PSIA"));
                WBHP.index.push_back(reservoir.allWells.GetIndex(WBHP.obj[w]));
            }
        }
    }
    if (DG.activity)
    {
        if (DG.obj[0] == "All")
        {
            DG.obj.clear();
            for (USI w = 0; w < wellnum; w++)
            {
                string wellname = reservoir.allWells.GetWellName(w);
                DG.obj.push_back(wellname);
                USI perfnum = reservoir.allWells.GetWellPerfNum(w);
                for (USI p = 0; p < perfnum; p++)
                {
                    Sumdata.push_back(
                        SumPair("DG", wellname + " Perf" + to_string(p), "PSIA"));
                    DG.index.push_back(w);
                }
            }
        }
        else
        {
            num = DG.obj.size();
            for (USI w = 0; w < num; w++)
            {
                USI wId = reservoir.allWells.GetIndex(DG.obj[w]);
                USI perfnum = reservoir.allWells.GetWellPerfNum(wId);
                for (USI p = 0; p < perfnum; p++)
                {
                    Sumdata.push_back(
                        SumPair("DG", DG.obj[w] + " P" + to_string(p), "PSIA"));
                    DG.index.push_back(wId);
                }
            }
        }
    }
    if (BPR.activity)
    {
        num = BPR.obj.size();
        for (USI i = 0; i < num; i++)
        {
            string temp = "(" + to_string(BPR.obj[i].I) + "," +
                          to_string(BPR.obj[i].J) + "," + to_string(BPR.obj[i].K) + ")";
            Sumdata.push_back(SumPair("BPR", temp, "PSIA"));
            USI I = BPR.obj[i].I - 1;
            USI J = BPR.obj[i].J - 1;
            USI K = BPR.obj[i].K - 1;
            BPR.index.push_back(reservoir.grid.GetActIndex(I, J, K));
        }
    }
    if (SOIL.activity)
    {
        num = SOIL.obj.size();
        for (USI i = 0; i < num; i++)
        {
            string temp = "(" + to_string(SOIL.obj[i].I) + "," +
                          to_string(SOIL.obj[i].J) + "," + to_string(SOIL.obj[i].K) +
                          ")";
            Sumdata.push_back(SumPair("SOIL", temp, "   "));
            USI I = SOIL.obj[i].I - 1;
            USI J = SOIL.obj[i].J - 1;
            USI K = SOIL.obj[i].K - 1;
            SOIL.index.push_back(reservoir.grid.GetActIndex(I, J, K));
        }
    }
    if (SGAS.activity)
    {
        num = SGAS.obj.size();
        for (USI i = 0; i < num; i++)
        {
            string temp = "(" + to_string(SGAS.obj[i].I) + "," +
                          to_string(SGAS.obj[i].J) + "," + to_string(SGAS.obj[i].K) +
                          ")";
            Sumdata.push_back(SumPair("SGAS", temp, "   "));
            USI I = SGAS.obj[i].I - 1;
            USI J = SGAS.obj[i].J - 1;
            USI K = SGAS.obj[i].K - 1;
            SGAS.index.push_back(reservoir.grid.GetActIndex(I, J, K));
        }
    }
    if (SWAT.activity)
    {
        num = SWAT.obj.size();
        for (USI i = 0; i < num; i++)
        {
            string temp = "(" + to_string(SWAT.obj[i].I) + "," +
                          to_string(SWAT.obj[i].J) + "," + to_string(SWAT.obj[i].K) +
                          ")";
            Sumdata.push_back(SumPair("SWAT", temp, "   "));
            USI I = SWAT.obj[i].I - 1;
            USI J = SWAT.obj[i].J - 1;
            USI K = SWAT.obj[i].K - 1;
            SWAT.index.push_back(reservoir.grid.GetActIndex(I, J, K));
        }
    }
    // Allocate memory
    USI rs = totalTime / 0.1;
    USI cs = Sumdata.size();
    for (USI i = 0; i < cs; i++)
    {
        Sumdata[i].val.reserve(rs);
    }
    // cout << "Summary::Setup" << endl;
}
References Grid::GetActIndex(), AllWells::GetIndex(), AllWells::GetWellName(), AllWells::GetWellNum(), AllWells::GetWellPerfNum(), and OCPType_Sum< T >::index.
SetVal()
void Summary::SetVal (const Reservoir & reservoir, const OCPControl & ctrl)
TODO: Add Doxygen.
Definition at line 455 of file OCPOutput.cpp.
{
    USI n = 0;
    // TIME
    Sumdata[n++].val.push_back(ctrl.GetCurTime());
    // NRiter
    Sumdata[n++].val.push_back(ctrl.GetNRiterT());
    // LSiter
    Sumdata[n++].val.push_back(ctrl.GetLSiterT());
    // FPR
    if (FPR)
        Sumdata[n++].val.push_back(rs.bulk.CalFPR());
    if (FOPR)
        Sumdata[n++].val.push_back(rs.allWells.GetFOPR());
    if (FOPT)
        Sumdata[n++].val.push_back(rs.allWells.GetFOPT());
    if (FGPR)
        Sumdata[n++].val.push_back(rs.allWells.GetFGPR());
    if (FGPt)
        Sumdata[n++].val.push_back(rs.allWells.GetFGPT());
    if (FWPR)
        Sumdata[n++].val.push_back(rs.allWells.GetFWPR());
    if (FWPT)
        Sumdata[n++].val.push_back(rs.allWells.GetFWPT());
    if (FGIR)
        Sumdata[n++].val.push_back(rs.allWells.GetFGIR());
    if (FGIT)
        Sumdata[n++].val.push_back(rs.allWells.GetFGIT());
    if (FWIR)
        Sumdata[n++].val.push_back(rs.allWells.GetFWIR());
    if (FWIT)
        Sumdata[n++].val.push_back(rs.allWells.GetFWIT());
    USI len = 0;
    // WOPR
    len = WOPR.index.size();
    for (USI w = 0; w < len; w++)
        Sumdata[n++].val.push_back(rs.allWells.GetWOPR(WOPR.index[w]));
    // WOPT
    len = WOPT.index.size();
    for (USI w = 0; w < len; w++)
        Sumdata[n++].val.push_back(rs.allWells.GetWOPT(WOPT.index[w]));
    // WGPR
    len = WGPR.index.size();
    for (USI w = 0; w < len; w++)
        Sumdata[n++].val.push_back(rs.allWells.GetWGPR(WGPR.index[w]));
    // WGPT
    len = WGPT.index.size();
    for (USI w = 0; w < len; w++)
        Sumdata[n++].val.push_back(rs.allWells.GetWGPT(WGPT.index[w]));
    // WWPR
    len = WWPR.index.size();
    for (USI w = 0; w < len; w++)
        Sumdata[n++].val.push_back(rs.allWells.GetWWPR(WWPR.index[w]));
    // WWPT
    len = WWPT.index.size();
    for (USI w = 0; w < len; w++)
        Sumdata[n++].val.push_back(rs.allWells.GetWWPT(WWPT.index[w]));
    // WGIR
    len = WGIR.index.size();
    for (USI w = 0; w < len; w++)
        Sumdata[n++].val.push_back(rs.allWells.GetWGIR(WGIR.index[w]));
    // WGIT
    len = WGIT.index.size();
    for (USI w = 0; w < len; w++)
        Sumdata[n++].val.push_back(rs.allWells.GetWGIT(WGIT.index[w]));
    // WWIR
    len = WWIR.index.size();
    for (USI w = 0; w < len; w++)
        Sumdata[n++].val.push_back(rs.allWells.GetWWIR(WWIR.index[w]));
    // WWIT
    len = WWIT.index.size();
    for (USI w = 0; w < len; w++)
        Sumdata[n++].val.push_back(rs.allWells.GetWWIT(WWIT.index[w]));
    // WBHP
    len = WBHP.index.size();
    for (USI w = 0; w < len; w++)
        Sumdata[n++].val.push_back(rs.allWells.GetWBHP(WBHP.index[w]));
    // DG
    len = DG.obj.size();
    for (USI w = 0; w < len; w++)
    {
        USI numperf = rs.allWells.GetWellPerfNum(DG.index[w]);
        for (USI p = 0; p < numperf; p++)
        {
            Sumdata[n++].val.push_back(rs.allWells.GetWellDg(DG.index[w], p));
        }
    }
    // BPR
    len = BPR.index.size();
    for (USI i = 0; i < len; i++)
        Sumdata[n++].val.push_back(rs.bulk.GetP(BPR.index[i]));
    // SOIL
    len = SOIL.index.size();
    for (USI i = 0; i < len; i++)
        Sumdata[n++].val.push_back(rs.bulk.GetSOIL(SOIL.index[i]));
    // SGAS
    len = SGAS.index.size();
    for (USI i = 0; i < len; i++)
        Sumdata[n++].val.push_back(rs.bulk.GetSGAS(SGAS.index[i]));
    // SWAT
    len = SWAT.index.size();
    for (USI i = 0; i < len; i++)
        Sumdata[n++].val.push_back(rs.bulk.GetSWAT(SWAT.index[i]));
}
References Bulk::CalFPR(), OCPControl::GetCurTime(), AllWells::GetFGIR(), AllWells::GetFGIT(), AllWells::GetFGPR(), AllWells::GetFGPT(), AllWells::GetFOPR(), AllWells::GetFOPT(), AllWells::GetFWIR(), AllWells::GetFWIT(), AllWells::GetFWPR(), AllWells::GetFWPT(), OCPControl::GetLSiterT(), OCPControl::GetNRiterT(), Bulk::GetP(), Bulk::GetSGAS(), Bulk::GetSOIL(), Bulk::GetSWAT(), AllWells::GetWBHP(), AllWells::GetWellDg(), AllWells::GetWellPerfNum(), AllWells::GetWGIR(), AllWells::GetWGIT(), AllWells::GetWGPR(), AllWells::GetWGPT(), AllWells::GetWOPR(), AllWells::GetWOPT(), AllWells::GetWWIR(), AllWells::GetWWIT(), AllWells::GetWWPR(), AllWells::GetWWPT(), and OCPType_Sum< T >::index.
The documentation for this class was generated from the following files:
OCPOutput.hpp
OCPOutput.cpp