OpenCAEPoro: OCP_IMPES Class Reference
OCP_IMPES Class Reference
OCP_IMPES is IMPES (implict pressure explict saturation) method.
#include <OCPMethod.hpp>
Public Member Functions
void SetupParam (const string &dir, const string &file)
Setup parameters needed for IMPES.
void AllocateMat (const Reservoir &rs)
Allocate maximal possible memory needed by linear solver.
void Run (Reservoir &rs, OCP_Control &ctrl, OCP_Output &output)
Start dynamic simulation. // TODO: ???
void GoOneStep (Reservoir &rs, OCP_Control &ctrl)
One time step of simulation.
void SolveP (Reservoir &rs, OCP_Control &ctrl, const OCP_DBL &dt)
Assemble linear system and solve. // TODO: Only difference as an interface?
Detailed Description
OCP_IMPES is IMPES (implict pressure explict saturation) method.
Definition at line 23 of file OCPMethod.hpp.
Member Function Documentation
AllocateMat()
void OCP_IMPES::AllocateMat (const Reservoir & rs)
Allocate maximal possible memory needed by linear solver.
Definition at line 19 of file OCPMethod.cpp.
{
    solver.AllocateMem(rs.bulk.GetBulkNum() + rs.wellgroup.GetWellNum());
    rs.conn.AllocateMat(solver);
    rs.wellgroup.AllocateMat(solver);
    solver.AllocateColValMem();
}
References Connection_BB::AllocateMat(), WellGroup::AllocateMat(), Bulk::GetBulkNum(), and WellGroup::GetWellNum().
GoOneStep()
void OCP_IMPES::GoOneStep (Reservoir & rs, OCP_Control & ctrl)
One time step of simulation.
Definition at line 47 of file OCPMethod.cpp.
{
    OCP_DBL ve        = 0.01;
    double& dt        = ctrl.current_dt;
    int     flagCheck = 0;
    // Init CFL number and dt
    OCP_DBL cfl = rs.CalCFL(dt);
    if (cfl > 1) dt /= (cfl + 1);
    // Init wells
    rs.wellgroup.PrepareWell(rs.bulk);
    while (true) {
        if (dt < MIN_TIME_STEP) OCP_ABORT("Time stepsize is too small!");
        SolveP(rs, ctrl, dt); // TODO: Why Solver needs dt?
        // first check : Pressure check
        flagCheck = rs.CheckP();
        if (flagCheck == 1) {
            dt /= 2;
            continue;
        } else if (flagCheck == 2) {
            continue;
        }
        rs.conn.CalFlux(rs.bulk);
        rs.wellgroup.CalFlux(rs.bulk);
        // second check : CFL check
        cfl = rs.CalCFL(dt);
        if (cfl > 1) {
            dt /= 2;
            rs.ResetVal01();
            continue;
        }
        rs.conn.MassConserve(rs.bulk, dt);
        rs.wellgroup.MassConserve(rs.bulk, dt);
        // third check: Ni check
        if (!rs.CheckNi()) {
            dt /= 2;
            rs.ResetVal01();
            continue;
        }
        rs.bulk.FlashNi();
        rs.bulk.CalVporo();
        // fouth check: Volume error check
        if (!rs.CheckVe(ve)) {
            dt /= 2;
            rs.ResetVal02();
            continue;
        }
        rs.bulk.CalKrPc();
        rs.conn.CalFlux(rs.bulk);
        break;
    }
    rs.wellgroup.CalIPRT(rs.bulk, dt);
    ctrl.tstep += 1;
    ctrl.iterNR = 1;
    ctrl.iterNR_total += 1;
    rs.bulk.CalMaxChange();
    ctrl.SetNextTstep(rs);
    rs.bulk.SetLastStep();
    rs.wellgroup.SetLastStep();
}
References Reservoir::CalCFL(), Connection_BB::CalFlux(), WellGroup::CalFlux(), WellGroup::CalIPRT(), Bulk::CalKrPc(), Bulk::CalMaxChange(), Bulk::CalVporo(), Reservoir::CheckNi(), Reservoir::CheckP(), Reservoir::CheckVe(), Bulk::FlashNi(), Connection_BB::MassConserve(), WellGroup::MassConserve(), MIN_TIME_STEP, OCP_ABORT, WellGroup::PrepareWell(), Reservoir::ResetVal01(), Reservoir::ResetVal02(), Bulk::SetLastStep(), WellGroup::SetLastStep(), OCP_Control::SetNextTstep(), and SolveP().
Run()
void OCP_IMPES::Run (Reservoir & rs, OCP_Control & ctrl, OCP_Output & output)
Start dynamic simulation. // TODO: ???
Definition at line 27 of file OCPMethod.cpp.
{
    GetWallTime timer;
    timer.Start();
    USI numdates = ctrl.GetNumDates();
    output.PrintInfoSched(rs, ctrl, timer.Stop());
    for (USI d = 0; d < numdates - 1; d++) {
        rs.wellgroup.ApplyControl(d);
        ctrl.ApplyControl(d);
        ctrl.InitTime(d);
        while (ctrl.criticalTime[d + 1] - ctrl.current_time > TINY) {
            GoOneStep(rs, ctrl);
            output.SetVal(rs, ctrl);
        }
        output.PrintInfoSched(rs, ctrl, timer.Stop());
    }
}
References WellGroup::ApplyControl(), OCP_Control::GetNumDates(), GoOneStep(), GetWallTime::Start(), GetWallTime::Stop(), and TINY.
SetupParam()
void OCP_IMPES::SetupParam (const string & dir, const string & file)
Setup parameters needed for IMPES.
Definition at line 14 of file OCPMethod.cpp.
{
    solver.SetupParam(dir, file);
}
SolveP()
void OCP_IMPES::SolveP (Reservoir & rs, OCP_Control & ctrl, const OCP_DBL & dt)
Assemble linear system and solve. // TODO: Only difference as an interface?
First assemble linear, then solve and return solution.
Definition at line 123 of file OCPMethod.cpp.
{
    rs.AssembleMat(solver, dt);
#ifdef DEBUG
    solver.CheckVal();
#endif // DEBUG
#ifdef __SOLVER_FASP__
    solver.AssembleMat_Fasp();
    GetWallTime Timer;
    Timer.Start();
    int status = solver.FaspSolve();
    ctrl.timeLS += Timer.Stop() / 1000;
#ifdef DEBUG
    solver.PrintfMatCSR("testA.out", "testb.out");
    solver.PrintfSolution("testx.out");
#endif // DEBUG
    solver.Free_Fasp();
    ctrl.iterLS = status;
    ctrl.iterLS_total += status;
#endif // __SOLVER_FASP__
    rs.GetSolution_IMPES(solver.GetSolution());
    solver.ClearData();
}
References Reservoir::AssembleMat(), Reservoir::GetSolution_IMPES(), GetWallTime::Start(), and GetWallTime::Stop().
The documentation for this class was generated from the following files:
OCPMethod.hpp
OCPMethod.cpp