OpenCAEPoro: OCP_AIMt Class Reference
OCP_AIMt Class Reference
perform AIM in time, that is, local FIM will be performed after global IMPEC performs
#include <OCPFluidMethod.hpp>
Public Member Functions
void Setup (Reservoir &rs, LinearSystem &myLS, LinearSystem &myAuxLS, const OCPControl &ctrl)
Setup AIMt.
void Prepare (Reservoir &rs, OCP_DBL &dt)
Prepare for Assembling matrix.
bool UpdateProperty (Reservoir &rs, OCPControl &ctrl, LinearSystem &myAuxLS)
Update properties of fluids.
Detailed Description
perform AIM in time, that is, local FIM will be performed after global IMPEC performs
Definition at line 149 of file OCPFluidMethod.hpp.
Member Function Documentation
Prepare()
void OCP_AIMt::Prepare (Reservoir & rs, OCP_DBL & dt)
Prepare for Assembling matrix.
Definition at line 936 of file OCPFluidMethod.cpp.
{
    rs.PrepareWell();
    OCP_DBL cfl = rs.CalCFL(dt);
    if (cfl > 1) dt /= (cfl + 1);
    // setup WellbulkId
    rs.SetupWellBulk();
}
References Reservoir::CalCFL(), and Reservoir::PrepareWell().
Setup()
void OCP_AIMt::Setup (Reservoir & rs, LinearSystem & myLS, LinearSystem & myAuxLS, const OCPControl & ctrl)
Setup AIMt.
Definition at line 920 of file OCPFluidMethod.cpp.
{
    // Allocate Memory of auxiliary variables for AIMt
    rs.AllocateAuxAIMt();
    // Allocate Memory of Matrix for IMPEC
    rs.AllocateMatIMPEC(myLS);
    // Allocate memory for internal matrix structure for local FIM
    rs.AllocateMatAIMt(myAuxLS);
    // Allocate memory for resiual of FIM
    OCP_USI num = (rs.GetMaxFIMBulk() + rs.GetWellNum()) * (rs.GetComNum() + 1);
    resFIM.res.resize(num);
    myLS.SetupLinearSolver(SCALARFASP, ctrl.GetWorkDir(), ctrl.GetLsFile());
    myAuxLS.SetupLinearSolver(VECTORFASP, ctrl.GetWorkDir(), "./bsr.fasp");
}
References Reservoir::AllocateAuxAIMt(), Reservoir::AllocateMatAIMt(), Reservoir::AllocateMatIMPEC(), Reservoir::GetComNum(), OCPControl::GetLsFile(), Reservoir::GetMaxFIMBulk(), Reservoir::GetWellNum(), OCPControl::GetWorkDir(), SCALARFASP, LinearSystem::SetupLinearSolver(), and VECTORFASP.
UpdateProperty()
bool OCP_AIMt::UpdateProperty (Reservoir & rs, OCPControl & ctrl, LinearSystem & myAuxLS)
Update properties of fluids.
Definition at line 947 of file OCPFluidMethod.cpp.
{
    OCP_DBL& dt = ctrl.current_dt;
    rs.CalFLuxIMPEC();
    rs.CalCFL(dt);
    rs.MassConseveIMPEC(dt);
    // third check: Ni check
    if (!rs.CheckNi()) {
        dt /= 2;
        rs.ResetVal03IMPEC();
        cout << "Negative Ni occurs\n";
        return false;
    }
    rs.CalVpore();
    rs.CalFlashIMPEC();
    // Perform FIM in local grid
    // Init
    rs.SetupFIMBulk();
    // cout << "FIM Bulk : " << rs.bulk.numFIMBulk << endl;
    //for (USI i = 0; i < rs.bulk.numFIMBulk; i++) {
    //    cout << rs.bulk.P[rs.bulk.FIMBulk[i]] << "   ";
    //}
    //cout << endl << endl;
    rs.bulk.FlashDerivAIM(false);
    rs.CalKrPcDerivAIM(false);
    rs.CalResAIMt(resFIM, dt);
    resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
    //for (USI i = 0; i < rs.bulk.numFIMBulk; i++) {
    //    cout << rs.bulk.P[rs.bulk.FIMBulk[i]] << "   ";
    //}
    //cout << endl << endl;
    ctrl.iterNR = 0;
    // cout << ctrl.iterNR << "   " << resFIM.maxRelRes0_v << endl;
    while (true) {
        rs.AssembleMatAIMt(myAuxLS, dt);
        myAuxLS.AssembleRhs(resFIM.res);
        myAuxLS.AssembleMatLinearSolver();
        int status = myAuxLS.Solve();
        rs.GetSolutionAIMt(myAuxLS.GetSolution(), ctrl.ctrlNR.NRdPmax, ctrl.ctrlNR.NRdSmax);
        myAuxLS.ClearData();
        // third check: Ni check
        if (!rs.CheckNi()) {
            dt /= 2;
            rs.ResetVal03IMPEC();
            cout << "Negative Ni occurs\n";
            return false;
        }
        rs.bulk.FlashDerivAIM(false);
        rs.CalKrPcDerivAIM(false);
        rs.CalVpore();
        rs.CalWellTrans();
        rs.CalWellFlux();
        rs.CalResAIMt(resFIM, dt);
        //for (USI i = 0; i < rs.bulk.numFIMBulk; i++) {
        //    cout << fixed << rs.bulk.P[rs.bulk.FIMBulk[i]] << "   ";
        //}
        //cout << scientific << resFIM.maxRelRes_v;
        //cout << endl << endl;
        OCP_DBL NRdPmax = rs.GetNRdPmax();
        OCP_DBL NRdSmax = rs.GetNRdSmaxP();
        ctrl.iterNR++;
        //cout << ctrl.iterNR << "   " << resFIM.maxRelRes_v << "   "
        //    << resFIM.maxRelRes_mol << "   " << NRdPmax << "   "
        //    << NRdSmaxP << "   " << endl;
        if (resFIM.maxRelRes_v <= resFIM.maxRelRes0_v * ctrl.ctrlNR.NRtol ||
            resFIM.maxRelRes_v <= ctrl.ctrlNR.NRtol ||
            resFIM.maxRelRes_mol <= ctrl.ctrlNR.NRtol ||
            (NRdPmax <= ctrl.ctrlNR.NRdPmin && NRdSmax <= ctrl.ctrlNR.NRdSmin)) {
            break;
        }
        if (ctrl.iterNR > ctrl.ctrlNR.maxNRiter) {
            ctrl.current_dt *= ctrl.ctrlTime.cutFacNR;
            rs.ResetVal03IMPEC();
            cout << "Local FIM Failed!" << endl;
            return false;
        }
    }
    // Pressure check
    OCP_INT flagCheck = rs.CheckP(true, true);
    switch (flagCheck) {
    case 1:
        // Negative Bulk P, well P, or Perforation P
        dt /= 2;
        return false;
    case 2:
        // Switch Well opt Mode, or close the crossflow perforation
        dt /= 1;
        return false;
    default:
        // All right
        break;
    }
    // fouth check: Volume error check
    if (!rs.CheckVe(0.01)) {
        // cout << ctrl.GetCurTime() << "Days" << "=======" << endl;
        dt /= 2;
        rs.ResetVal03IMPEC();
        return false;
    }
    rs.CalKrPc();
    rs.CalConnFluxIMPEC();
    return true;
}
References Reservoir::AssembleMatAIMt(), LinearSystem::AssembleMatLinearSolver(), LinearSystem::AssembleRhs(), Reservoir::CalCFL(), Reservoir::CalConnFluxIMPEC(), Reservoir::CalFlashIMPEC(), Reservoir::CalFLuxIMPEC(), Reservoir::CalKrPc(), Reservoir::CalKrPcDerivAIM(), Reservoir::CalResAIMt(), Reservoir::CalVpore(), Reservoir::CalWellFlux(), Reservoir::CalWellTrans(), Reservoir::CheckNi(), Reservoir::CheckP(), Reservoir::CheckVe(), LinearSystem::ClearData(), ControlTime::cutFacNR, Bulk::FlashDerivAIM(), Reservoir::GetNRdPmax(), Reservoir::GetNRdSmaxP(), LinearSystem::GetSolution(), Reservoir::GetSolutionAIMt(), Reservoir::MassConseveIMPEC(), ControlNR::maxNRiter, ControlNR::NRdPmax, ControlNR::NRdPmin, ControlNR::NRdSmax, ControlNR::NRdSmin, ControlNR::NRtol, Reservoir::ResetVal03IMPEC(), Reservoir::SetupFIMBulk(), and LinearSystem::Solve().
The documentation for this class was generated from the following files:
OCPFluidMethod.hpp
OCPFluidMethod.cpp