OpenCAEPoro: FlowUnit Class Reference
FlowUnit Class Reference
#include <FlowUnit.hpp>
Public Member Functions
FlowUnit ()=default
Default constructor.
FlowUnit (const ParamReservoir &rs_param, const USI &inmode, const USI &i)
TODO: Add Doxygen.
bool IsEmpty_SGOF ()
Check whether SGOF is empty.
bool IsEmpty_SWOF ()
Check whether SWOF is empty.
void Generate_SWPCWG ()
Generate the table of water saturation vs. capillary between water and gas.
OCP_DBL Eval_SWOF (const USI &j, const OCP_DBL &val, const USI &destj)
OCP_DBL EvalInv_SWOF (const USI &j, const OCP_DBL &val, const USI &destj)
OCP_DBL Eval_SGOF (const USI &j, const OCP_DBL &val, const USI &destj)
OCP_DBL EvalInv_SGOF (const USI &j, const OCP_DBL &val, const USI &destj)
OCP_DBL Eval_SWPCWG (const USI &j, const OCP_DBL &val, const USI &destj)
OCP_DBL EvalInv_SWPCWG (const USI &j, const OCP_DBL &val, const USI &destj)
void CalKrPc (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out)
calculate relative permeability and capillary pressure.
void CalKrPc_W (OCP_DBL *kr_out, OCP_DBL *pc_out)
TODO: Add Doxygen.
void CalKrPc_OW (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out)
TODO: Add Doxygen.
void CalKrPc_OG (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out)
TODO: Add Doxygen.
void CalKrPc_ODGW (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out)
TODO: Add Doxygen.
void CalKrPcDeriv (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, OCP_DBL *dkrdS, OCP_DBL *dPcjdS)
void CalKrPcDeriv_OW (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, OCP_DBL *dkrdS, OCP_DBL *dPcjdS)
void CalKrPcDeriv_ODGW (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, OCP_DBL *dkrdS, OCP_DBL *dPcjdS)
OCP_DBL CalKro_Stone2 (const OCP_DBL &krow, const OCP_DBL &krog, const OCP_DBL &krw, const OCP_DBL &krg) const
calculate relative permeability of oil phase with stone2 method.
OCP_DBL CalKro_Stone2Der (OCP_DBL krow, OCP_DBL krog, OCP_DBL krw, OCP_DBL krg, OCP_DBL dkrwSw, OCP_DBL dkrowSw, OCP_DBL dkrgSg, OCP_DBL dkrogSg, OCP_DBL &out_dkrodSw, OCP_DBL &dkrodSg)
OCP_DBL CalKro_Default (const OCP_DBL &Sg, const OCP_DBL &Sw, const OCP_DBL &krog, const OCP_DBL &krow)
OCP_DBL CalKro_DefaultDer (const OCP_DBL &Sg, const OCP_DBL &Sw, const OCP_DBL &krog, const OCP_DBL &krow, const OCP_DBL &dkrogSg, const OCP_DBL &dkrowSw, OCP_DBL &dkroSg, OCP_DBL &dkroSw)
Detailed Description
designed to deal with matters related to saturation table. relative permeability, capillary pressure woulbe be calculated here.
Definition at line 22 of file FlowUnit.hpp.
Constructor & Destructor Documentation
FlowUnit()
FlowUnit::FlowUnit (const ParamReservoir & rs_param, const USI & inmode, const USI & i)
TODO: Add Doxygen.
Definition at line 295 of file FlowUnit.cpp.
{
    mode = inmode;
    if (rs_param.water) {
        SWOF.Setup(rs_param.SWOF_T.data[i]);
        len = max(len, SWOF.GetColNum());
    }
    if (rs_param.gas) {
        SGOF.Setup(rs_param.SGOF_T.data[i]);
        len = max(len, SWOF.GetColNum());
    }
    data.resize(len, 0);
    cdata.resize(len, 0);
    kroMax = 0;
    if (rs_param.water) {
        kroMax = SWOF.GetCol(2)[0];
    } else if (rs_param.gas) {
        kroMax = SGOF.GetCol(2)[0];
    }
    Swco = 0;
    if (rs_param.water) {
        Swco = SWOF.GetCol(0)[0];
    }
}
References TableSet::data, ParamReservoir::gas, OCPTable::GetCol(), OCPTable::GetColNum(), OCPTable::Setup(), ParamReservoir::SGOF_T, ParamReservoir::SWOF_T, and ParamReservoir::water.
Member Function Documentation
CalKro_Default()
OCP_DBL FlowUnit::CalKro_Default (const OCP_DBL & Sg, const OCP_DBL & Sw, const OCP_DBL & krog, const OCP_DBL & krow)
Definition at line 266 of file FlowUnit.cpp.
{
    OCP_DBL tmp = Sg + Sw - Swco;
    if (tmp <= TINY) {
        return kroMax;
    }
    OCP_DBL kro = (Sg * krog + (Sw - Swco) * krow) / tmp;
    return kro;
}
CalKro_DefaultDer()
OCP_DBL FlowUnit::CalKro_DefaultDer (const OCP_DBL & Sg, const OCP_DBL & Sw, const OCP_DBL & krog, const OCP_DBL & krow, const OCP_DBL & dkrogSg, const OCP_DBL & dkrowSw, OCP_DBL & dkroSg, OCP_DBL & dkroSw)
Definition at line 277 of file FlowUnit.cpp.
{
    OCP_DBL tmp = Sg + Sw - Swco;
    if (tmp <= TINY) {
        dkroSg = 0;
        dkroSw = 0;
        return kroMax;
    }
    OCP_DBL kro = (Sg * krog + (Sw - Swco) * krow) / tmp;
    dkroSg      = (krog + Sg * dkrogSg - kro) / tmp;
    dkroSw      = (krow + (Sw - Swco) * dkrowSw - kro) / tmp;
    return kro;
}
CalKro_Stone2()
OCP_DBL FlowUnit::CalKro_Stone2 (const OCP_DBL & krow, const OCP_DBL & krog, const OCP_DBL & krw, const OCP_DBL & krg) const
calculate relative permeability of oil phase with stone2 method.
TODO: Add Doxygen.
Definition at line 230 of file FlowUnit.cpp.
{
    // krog : oil relative permeability for a system with oil, gas and connate water
    // krow : oil relative permeability for a system with oil and water only
    OCP_DBL kro =
        kroMax * ((krow / kroMax + krw) * (krog / kroMax + krg) - (krw + krg));
    if (kro < 0) kro = 0;
    return kro;
}
CalKro_Stone2Der()
OCP_DBL FlowUnit::CalKro_Stone2Der (OCP_DBL krow, OCP_DBL krog, OCP_DBL krw, OCP_DBL krg, OCP_DBL dkrwSw, OCP_DBL dkrowSw, OCP_DBL dkrgSg, OCP_DBL dkrogSg, OCP_DBL & out_dkrodSw, OCP_DBL & dkrodSg)
Definition at line 243 of file FlowUnit.cpp.
{
    OCP_DBL kro, dkrodSw, dkrodSg;
    kro = kroMax * ((krow / kroMax + krw) * (krog / kroMax + krg) - (krw + krg));
    dkrodSw =
        kroMax * ((dkrowdSw / kroMax + dkrwdSw) * (krog / kroMax + krg) - (dkrwdSw));
    dkrodSg =
        kroMax * ((krow / kroMax + krw) * (dkrogdSg / kroMax + dkrgdSg) - (dkrgdSg));
    if (kro < 0) {
        kro     = 0;
        dkrodSg = 0;
        dkrodSw = 0;
    }
    out_dkrodSw = dkrodSw;
    out_dkrodSg = dkrodSg;
    return kro;
}
CalKrPc()
void FlowUnit::CalKrPc (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out)
calculate relative permeability and capillary pressure.
TODO: Add Doxygen.
Definition at line 35 of file FlowUnit.cpp.
{
    switch (mode) {
        case PHASE_W:
            CalKrPc_W(kr_out, pc_out);
            break;
        case PHASE_OW:
            CalKrPc_OW(S_in, kr_out, pc_out);
            break;
        case PHASE_OG:
            CalKrPc_OG(S_in, kr_out, pc_out);
            break;
        case PHASE_ODGW: // should SWOF be used here?
            CalKrPc_ODGW(S_in, kr_out, pc_out);
            break;
        default:
            OCP_ABORT("Wrong mode specified!");
    }
}
References CalKrPc_ODGW(), CalKrPc_OG(), CalKrPc_OW(), CalKrPc_W(), OCP_ABORT, PHASE_ODGW, PHASE_OG, PHASE_OW, and PHASE_W.
CalKrPc_ODGW()
void FlowUnit::CalKrPc_ODGW (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out)
TODO: Add Doxygen.
calculate relative permeability and capillary pressure for oil, gas and water. it will be used if oil, gas and water exist or could be exist.
Definition at line 97 of file FlowUnit.cpp.
{
    OCP_DBL Sg = S_in[1];
    OCP_DBL Sw = S_in[2];
    // three phase black oil model using stone 2
    SWOF.Eval_All(0, Sw, data, cdata);
    OCP_DBL krw  = data[1];
    OCP_DBL krow = data[2];
    OCP_DBL Pcw  = -data[3];
    SGOF.Eval_All(0, Sg, data, cdata);
    OCP_DBL krg  = data[1];
    OCP_DBL krog = data[2];
    OCP_DBL Pcg  = data[3];
    OCP_DBL kro = CalKro_Stone2(krow, krog, krw, krg);
    // OCP_DBL kro = CalKro_Default(Sg, Sw, krog, krow);
    kr_out[0] = kro;
    kr_out[1] = krg;
    kr_out[2] = krw;
    pc_out[0] = 0;
    pc_out[1] = Pcg;
    pc_out[2] = Pcw;
}
References CalKro_Stone2(), and OCPTable::Eval_All().
CalKrPc_OG()
void FlowUnit::CalKrPc_OG (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out)
TODO: Add Doxygen.
calculate relative permeability and capillary pressure for oil and gas. it will be used if oil and gas exist or could be exist.
Definition at line 80 of file FlowUnit.cpp.
{
    OCP_DBL Sg = S_in[1];
    // three phase black oil model using stone 2
    SGOF.Eval_All(0, Sg, data, cdata);
    OCP_DBL krg = data[1];
    OCP_DBL kro = data[2];
    OCP_DBL Pcg = data[3];
    kr_out[0] = kro;
    kr_out[1] = krg;
    pc_out[0] = 0;
    pc_out[1] = Pcg;
}
References OCPTable::Eval_All().
CalKrPc_OW()
void FlowUnit::CalKrPc_OW (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out)
TODO: Add Doxygen.
calculate relative permeability and capillary pressure for oil and water. it will be used if oil and water exist or could be exist.
Definition at line 63 of file FlowUnit.cpp.
{
    OCP_DBL Sw = S_in[1];
    // three phase black oil model using stone 2
    SWOF.Eval_All(0, Sw, data, cdata);
    OCP_DBL krw = data[1];
    OCP_DBL kro = data[2];
    OCP_DBL Pcw = -data[3];
    kr_out[0] = kro;
    kr_out[1] = krw;
    pc_out[0] = 0;
    pc_out[1] = Pcw;
}
References OCPTable::Eval_All().
CalKrPc_W()
void FlowUnit::CalKrPc_W (OCP_DBL * kr_out, OCP_DBL * pc_out)
TODO: Add Doxygen.
calculate relative permeability and capillary pressure for water. it will be used if water exists or could be exist.
Definition at line 56 of file FlowUnit.cpp.
{
    kr_out[0] = 1;
    pc_out[0] = 0;
}
CalKrPcDeriv()
void FlowUnit::CalKrPcDeriv (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out, OCP_DBL * dkrdS, OCP_DBL * dPcjdS)
Definition at line 124 of file FlowUnit.cpp.
{
    switch (mode) {
        case PHASE_OW:
            CalKrPcDeriv_OW(S_in, kr_out, pc_out, dkrdS, dPcjdS);
            break;
        case PHASE_ODGW:
            CalKrPcDeriv_ODGW(S_in, kr_out, pc_out, dkrdS, dPcjdS);
            break;
        default:
            break;
    }
}
CalKrPcDeriv_ODGW()
void FlowUnit::CalKrPcDeriv_ODGW (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out, OCP_DBL * dkrdS, OCP_DBL * dPcjdS)
Definition at line 167 of file FlowUnit.cpp.
{
    OCP_DBL Sg = S_in[1];
    OCP_DBL Sw = S_in[2];
    // three phase black oil model using stone 2
    SWOF.Eval_All(0, Sw, data, cdata);
    OCP_DBL krw      = data[1];
    OCP_DBL dKrwdSw  = cdata[1];
    OCP_DBL krow     = data[2];
    OCP_DBL dKrowdSw = cdata[2];
    OCP_DBL Pcw      = -data[3];
    OCP_DBL dPcwdSw  = -cdata[3];
    SGOF.Eval_All(0, Sg, data, cdata);
    OCP_DBL krg      = data[1];
    OCP_DBL dKrgdSg  = cdata[1];
    OCP_DBL krog     = data[2];
    OCP_DBL dKrogdSg = cdata[2];
    OCP_DBL Pcg      = data[3];
    OCP_DBL dPcgdSg  = cdata[3];
    OCP_DBL dKrodSg{0}, dKrodSw{0}, kro{0};
    kro = CalKro_Stone2Der(krow, krog, krw, krg, dKrwdSw, dKrowdSw, dKrgdSg, dKrogdSg,
                           dKrodSw, dKrodSg);
    // if (kro < 0) {
    //    cout << S_in[0] << "   " << S_in[1] << "   " << S_in[2] << endl;
    //    kro = 0;
    //}
    // kro = CalKro_DefaultDer(Sg, Sw, krog, krow, dKrogdSg, dKrowdSw, dKrodSg,
    // dKrodSw);
    kr_out[0] = kro;
    kr_out[1] = krg;
    kr_out[2] = krw;
    pc_out[0] = 0;
    pc_out[1] = Pcg;
    pc_out[2] = Pcw;
    dkrdS[0] = 0;
    dkrdS[1] = dKrodSg;
    dkrdS[2] = dKrodSw;
    dkrdS[3] = 0;
    dkrdS[4] = dKrgdSg;
    dkrdS[5] = 0;
    dkrdS[6] = 0;
    dkrdS[7] = 0;
    dkrdS[8] = dKrwdSw;
    dPcjdS[0] = 0;
    dPcjdS[1] = 0;
    dPcjdS[2] = 0;
    dPcjdS[3] = 0;
    dPcjdS[4] = dPcgdSg;
    dPcjdS[5] = 0;
    dPcjdS[6] = 0;
    dPcjdS[7] = 0;
    dPcjdS[8] = dPcwdSw;
}
CalKrPcDeriv_OW()
void FlowUnit::CalKrPcDeriv_OW (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out, OCP_DBL * dkrdS, OCP_DBL * dPcjdS)
Definition at line 139 of file FlowUnit.cpp.
{
    OCP_DBL Sw = S_in[1];
    SWOF.Eval_All(0, Sw, data, cdata);
    OCP_DBL krw      = data[1];
    OCP_DBL dKrwdSw  = cdata[1];
    OCP_DBL krow     = data[2];
    OCP_DBL dKrowdSw = cdata[2];
    OCP_DBL Pcw      = -data[3];
    OCP_DBL dPcwdSw  = -cdata[3];
    kr_out[0] = krow;
    kr_out[1] = krw;
    pc_out[0] = 0;
    pc_out[1] = Pcw;
    dkrdS[0] = 0;
    dkrdS[1] = dKrowdSw;
    dkrdS[2] = 0;
    dkrdS[3] = dKrwdSw;
    dPcjdS[0] = 0;
    dPcjdS[1] = 0;
    dPcjdS[2] = 0;
    dPcjdS[3] = dPcwdSw;
}
Eval_SGOF()
OCP_DBL FlowUnit::Eval_SGOF (const USI & j, const OCP_DBL & val, const USI & destj) inline
interpolate the specified monotonically increasing column in SGOF to evaluate the target column.
Definition at line 56 of file FlowUnit.hpp.
    {
        return SGOF.Eval(j, val, destj);
    }
References OCPTable::Eval().
Eval_SWOF()
OCP_DBL FlowUnit::Eval_SWOF (const USI & j, const OCP_DBL & val, const USI & destj) inline
interpolate the specified monotonically increasing column in SWOF to evaluate the target column.
Definition at line 42 of file FlowUnit.hpp.
    {
        return SWOF.Eval(j, val, destj);
    }
References OCPTable::Eval().
Eval_SWPCWG()
OCP_DBL FlowUnit::Eval_SWPCWG (const USI & j, const OCP_DBL & val, const USI & destj) inline
interpolate the specified monotonically increasing column in SWPCWG to evaluate the target column.
Definition at line 70 of file FlowUnit.hpp.
    {
        return SWPCWG.Eval(j, val, destj);
    }
References OCPTable::Eval().
EvalInv_SGOF()
OCP_DBL FlowUnit::EvalInv_SGOF (const USI & j, const OCP_DBL & val, const USI & destj) inline
interpolate the specified monotonically decreasing column in SGOF to evaluate the target column.
Definition at line 63 of file FlowUnit.hpp.
    {
        return SGOF.Eval_Inv(j, val, destj);
    }
References OCPTable::Eval_Inv().
EvalInv_SWOF()
OCP_DBL FlowUnit::EvalInv_SWOF (const USI & j, const OCP_DBL & val, const USI & destj) inline
interpolate the specified monotonically decreasing column in SWOF to evaluate the target column.
Definition at line 49 of file FlowUnit.hpp.
    {
        return SWOF.Eval_Inv(j, val, destj);
    }
References OCPTable::Eval_Inv().
EvalInv_SWPCWG()
OCP_DBL FlowUnit::EvalInv_SWPCWG (const USI & j, const OCP_DBL & val, const USI & destj) inline
interpolate the specified monotonically decreasing column in SWPCWG to evaluate the target column.
Definition at line 77 of file FlowUnit.hpp.
    {
        return SWPCWG.Eval_Inv(j, val, destj);
    }
References OCPTable::Eval_Inv().
Generate_SWPCWG()
void FlowUnit::Generate_SWPCWG ()
Generate the table of water saturation vs. capillary between water and gas.
Generate the table of Sw vs. Pcwg using SGOF and SWOF.
Definition at line 16 of file FlowUnit.cpp.
{
    if (SGOF.IsEmpty()) OCP_ABORT("SGOF is missing!");
    if (SWOF.IsEmpty()) OCP_ABORT("SWOF is missing!");
    std::vector<OCP_DBL> Sw(SWOF.GetCol(0));
    std::vector<OCP_DBL> Pcw(SWOF.GetCol(3));
    USI                  n = Sw.size();
    for (USI i = 0; i < n; i++) {
        OCP_DBL Pcg = SGOF.Eval(0, 1 - Sw[i], 3);
        Pcw[i] += Pcg;
    }
    SWPCWG.PushCol(Sw);
    SWPCWG.PushCol(Pcw);
    SWPCWG.SetRowCol();
}
References OCPTable::Eval(), OCPTable::GetCol(), OCPTable::IsEmpty(), OCP_ABORT, OCPTable::PushCol(), and OCPTable::SetRowCol().
IsEmpty_SGOF()
bool FlowUnit::IsEmpty_SGOF () inline
Check whether SGOF is empty.
Definition at line 32 of file FlowUnit.hpp.
{ return SGOF.IsEmpty(); }
References OCPTable::IsEmpty().
IsEmpty_SWOF()
bool FlowUnit::IsEmpty_SWOF () inline
Check whether SWOF is empty.
Definition at line 35 of file FlowUnit.hpp.
{ return SWOF.IsEmpty(); }
References OCPTable::IsEmpty().
The documentation for this class was generated from the following files:
FlowUnit.hpp
FlowUnit.cpp