OpenCAEPoro: AllWells Class Reference
AllWells Class Reference
#include <AllWells.hpp>
Public Member Functions
void InputParam (const ParamWell &paramWell)
Input param from ParamWell.
void Setup (const Grid &myGrid, const Bulk &myBulk)
Setup well in allWells.
void SetupWell (const Grid &myGrid, const Bulk &myBulk)
complete the information of well according to Grid and Bulk.
void SetupWellGroup (const Bulk &myBulk)
Setup information of wellGroup.
void SetupMixture (const Bulk &myBulk)
get the mixture from bulk -— usless now
void SetupWellBulk (Bulk &myBulk) const
Setup bulks which are penetrated by wells.
void ApplyControl (const USI &i)
Apply the operation mode at the ith critical time.
void InitBHP (const Bulk &myBulk)
Set the initial well pressure.
void PrepareWell (const Bulk &myBulk)
Calculate well properties at the beginning of each time step.
void CalTrans (const Bulk &myBulk)
Calculate Transmissibility of Wells.
void CalFlux (const Bulk &myBulk)
Calculate volume flow rate and moles flow rate of each perforation.
void CalProdWeight (const Bulk &myBulk)
Calculate Prodweight.
void CaldG (const Bulk &myBulk)
Calculate dG.
void CalIPRT (const Bulk &myBulk, OCP_DBL dt)
Calculate Injection rate, total Injection, Production rate, total Production.
void CalReInjFluid (const Bulk &myBulk)
Calculate Reinjection fluid.
void AllocateMat (LinearSystem &myLS, const USI &bulknum) const
Calculate memory for Matrix.
void UpdateLastBHP ()
void ResetBHP ()
void UpdateLastDg ()
Reset dG to ldG for each well.
void ResetDg ()
OCP_INT CheckP (const Bulk &myBulk)
Check if unreasonable well pressure or perforation pressure occurs.
USI GetWellNum () const
Return the num of wells.
string GetWellName (const USI &i) const
Return the name of specified well.
USI GetIndex (const string &name) const
Return the index of specified well.
USI GetWellPerfNum (const USI &i) const
Return the num of perforations of well i.
USI GetWellPerfNum () const
Return the num of perforations of all wells.
USI GetMaxWellPerNum () const
Calculate mamimum num of perforations of all Wells.
void CalMaxBHPChange ()
OCP_DBL GetdBHPmax () const
OCP_DBL GetFOPR () const
Return oil production rate in field.
OCP_DBL GetFOPT () const
Return total oil production in field.
OCP_DBL GetFGPR () const
Return gas production rate in field.
OCP_DBL GetFGPT () const
Return total gas production in field.
OCP_DBL GetFWPR () const
Return water production rate in field.
OCP_DBL GetFWPT () const
Return total water production in field.
OCP_DBL GetFGIR () const
Return gas injection rate in field.
OCP_DBL GetFGIT () const
Return gas water injection in field.
OCP_DBL GetFWIR () const
Return water injection rate in field.
OCP_DBL GetFWIT () const
Return total water injection in field.
OCP_DBL GetWOPR (const USI &w) const
Return oil production rate of the wth well.
OCP_DBL GetWOPT (const USI &w) const
Return total oil production of the wth well.
OCP_DBL GetWGPR (const USI &w) const
Return gas production rate of the wth well.
OCP_DBL GetWGPT (const USI &w) const
Return total gas production of the wth well.
OCP_DBL GetWWPR (const USI &w) const
Return water production rate of the wth well.
OCP_DBL GetWWPT (const USI &w) const
Return total water production of the wth well.
OCP_DBL GetWGIR (const USI &w) const
Return gas injection rate of the wth well.
OCP_DBL GetWGIT (const USI &w) const
Return total gas injection of the wth well.
OCP_DBL GetWWIR (const USI &w) const
Return water injection rate of the wth well.
OCP_DBL GetWWIT (const USI &w) const
Return total water injection of the wth well.
OCP_DBL GetWBHP (const USI &w) const
Return the BHP of wth well.
OCP_DBL GetWellDg (const USI &w, const USI &p) const
Return the pth dG of wth well.
OCP_DBL CalWellQT ()
void ShowWellStatus (const Bulk &myBulk)
void CalCFL (const Bulk &myBulk, const OCP_DBL &dt) const
Calculate the CFL number for each perforation and return the maximum one.
void MassConserveIMPEC (Bulk &myBulk, OCP_DBL dt)
Update moles of components in Bulks which connects to well.
void AssemblaMatIMPEC (LinearSystem &myLS, const Bulk &myBulk, const OCP_DBL &dt) const
Assemble matrix, parts related to well are included for IMPEC.
void GetSolIMPEC (const vector< OCP_DBL > &u, const OCP_USI &bId)
Update Well P and Perforation P after linear system is solved for IMPEC.
void AssemblaMatFIM (LinearSystem &myLS, const Bulk &myBulk, const OCP_DBL &dt) const
Assemble matrix, parts related to well are included for FIM.
void GetSolFIM (const vector< OCP_DBL > &u, const OCP_USI &bId, const USI &len)
Get solution from solver class after linear system is solved for FIM.
void GetSol01FIM (const vector< OCP_DBL > &u, const OCP_USI &bId, const USI &len, const OCP_DBL &alpha)
void CalResFIM (ResFIM &resFIM, const Bulk &myBulk, const OCP_DBL &dt) const
Calculate Resiual and relative Resiual for FIM.
void ShowRes (const vector< OCP_DBL > &res, const Bulk &myBulk) const
Show Res.
void AssemblaMatFIM_new (LinearSystem &myLS, const Bulk &myBulk, const OCP_DBL &dt) const
Assemble matrix, parts related to well are included for FIM.
void AssemblaMatFIM_new_n (LinearSystem &myLS, const Bulk &myBulk, const OCP_DBL &dt) const
void AssemblaMatAIMt (LinearSystem &myLS, const Bulk &myBulk, const OCP_DBL &dt) const
Assemble matrix, parts related to well are included for AIMt.
void CalResAIMt (ResFIM &resFIM, const Bulk &myBulk, const OCP_DBL &dt) const
Calculate Resiual and relative Resiual for local FIM.
void GetSolAIMt (const vector< OCP_DBL > &u, const OCP_USI &bId, const USI &len)
Get solution from solver class after linear system is solved for local FIM.
void AssemblaMatAIMs (LinearSystem &myLS, const Bulk &myBulk, const OCP_DBL &dt) const
Assemble matrix, parts related to well are included for AIMt.
Friends
class Reservoir
class DetailInfo
Detailed Description
AllWells contains all wells now, it's used to manages all wells uniformly in reservoirs. actually, you can regard it as an interface between wells and other modules.
Definition at line 68 of file AllWells.hpp.
Member Function Documentation
AllocateMat()
void AllWells::AllocateMat (LinearSystem & myLS, const USI & bulknum) const
Calculate memory for Matrix.
Definition at line 315 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    USI maxNum = (GetMaxWellPerNum() + 1) * numWell;
    for (USI w = 0; w < numWell; w++) {
        wells[w].AllocateMat(myLS);
        myLS.EnlargeRowCap(bulknum + w, maxNum);
    }
}
References LinearSystem::EnlargeRowCap(), GetMaxWellPerNum(), and OCP_FUNCNAME.
ApplyControl()
void AllWells::ApplyControl (const USI & i)
Apply the operation mode at the ith critical time.
Definition at line 149 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        wells[w].opt = wells[w].optSet[i];
        if (wells[w].WellState()) {
            wells[w].wEId = wId;
            wId++;
        }
    }
}
References OCP_FUNCNAME.
AssemblaMatAIMs()
void AllWells::AssemblaMatAIMs (LinearSystem & myLS, const Bulk & myBulk, const OCP_DBL & dt) const
Assemble matrix, parts related to well are included for AIMt.
Definition at line 703 of file AllWells.cpp.
{
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            switch (wells[w].WellType()) {
            case INJ:
                wells[w].AssembleMatINJ_AIMs(myBulk, myLS, dt);
                break;
            case PROD:
                wells[w].AssembleMatPROD_AIMs(myBulk, myLS, dt);
                break;
            default:
                OCP_ABORT("Wrong well type");
            }
        }
    }
}
References INJ, OCP_ABORT, and PROD.
AssemblaMatAIMt()
void AllWells::AssemblaMatAIMt (LinearSystem & myLS, const Bulk & myBulk, const OCP_DBL & dt) const
Assemble matrix, parts related to well are included for AIMt.
Definition at line 654 of file AllWells.cpp.
{
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            switch (wells[w].WellType()) {
            case INJ:
                wells[w].AssembleMatINJ_AIMt(myBulk, myLS, dt);
                break;
            case PROD:
                wells[w].AssembleMatPROD_AIMt(myBulk, myLS, dt);
                break;
            default:
                OCP_ABORT("Wrong well type");
            }
        }
    }
}
References INJ, OCP_ABORT, and PROD.
AssemblaMatFIM()
void AllWells::AssemblaMatFIM (LinearSystem & myLS, const Bulk & myBulk, const OCP_DBL & dt) const
Assemble matrix, parts related to well are included for FIM.
Definition at line 509 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            switch (wells[w].WellType()) {
                case INJ:
                    wells[w].AssembleMatINJ_FIM(myBulk, myLS, dt);
                    break;
                case PROD:
                    wells[w].AssembleMatPROD_FIM(myBulk, myLS, dt);
                    break;
                default:
                    OCP_ABORT("Wrong well type");
            }
        }
    }
    // for Reinjection
    for (auto& wG : wellGroup) {
        if (wG.reInj) {
            for (auto& prod : wellGroup[wG.prodGroup].wIdPROD) {
                if (wells[prod].WellState()) {
                    wells[prod].AssembleMatReinjection_FIM(myBulk, myLS, dt, wells, wG.wIdINJ);
                }
            }
        }
    }
}
References INJ, OCP_ABORT, OCP_FUNCNAME, and PROD.
AssemblaMatFIM_new()
void AllWells::AssemblaMatFIM_new (LinearSystem & myLS, const Bulk & myBulk, const OCP_DBL & dt) const
Assemble matrix, parts related to well are included for FIM.
Definition at line 603 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            switch (wells[w].WellType()) {
            case INJ:
                wells[w].AssembleMatINJ_FIM_new(myBulk, myLS, dt);
                break;
            case PROD:
                wells[w].AssembleMatPROD_FIM_new(myBulk, myLS, dt);
                break;
            default:
                OCP_ABORT("Wrong well type");
            }
        }
    }
}
References INJ, OCP_ABORT, OCP_FUNCNAME, and PROD.
AssemblaMatFIM_new_n()
void AllWells::AssemblaMatFIM_new_n (LinearSystem & myLS, const Bulk & myBulk, const OCP_DBL & dt) const
Definition at line 626 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            switch (wells[w].WellType()) {
            case INJ:
                wells[w].AssembleMatINJ_FIM_new_n(myBulk, myLS, dt);
                break;
            case PROD:
                wells[w].AssembleMatPROD_FIM_new_n(myBulk, myLS, dt);
                break;
            default:
                OCP_ABORT("Wrong well type");
            }
        }
    }
}
AssemblaMatIMPEC()
void AllWells::AssemblaMatIMPEC (LinearSystem & myLS, const Bulk & myBulk, const OCP_DBL & dt) const
Assemble matrix, parts related to well are included for IMPEC.
Definition at line 458 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            switch (wells[w].WellType()) {
                case INJ:
                    wells[w].AssembleMatINJ_IMPEC(myBulk, myLS, dt);
                    break;
                case PROD:
                    wells[w].AssembleMatPROD_IMPEC(myBulk, myLS, dt);
                    break;
                default:
                    OCP_ABORT("Wrong well type");
            }
        }
    }
    // for Reinjection
    for (auto& wG : wellGroup) {
        if (wG.reInj) {
            for (auto& prod : wellGroup[wG.prodGroup].wIdPROD) {
                if (wells[prod].WellState()) {
                    wells[prod].AssembleMatReinjection_IMPEC(myBulk, myLS, dt, wells, wG.wIdINJ);
                }
            }
        }
    }
}
References INJ, OCP_ABORT, OCP_FUNCNAME, and PROD.
CalCFL()
void AllWells::CalCFL (const Bulk & myBulk, const OCP_DBL & dt) const
Calculate the CFL number for each perforation and return the maximum one.
Definition at line 436 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].CalCFL(myBulk, dt);
        }
    }
}
References OCP_FUNCNAME.
CaldG()
void AllWells::CaldG (const Bulk & myBulk)
Calculate dG.
Definition at line 222 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].CaldG(myBulk);
        }
    }
}
References OCP_FUNCNAME.
CalFlux()
void AllWells::CalFlux (const Bulk & myBulk)
Calculate volume flow rate and moles flow rate of each perforation.
Definition at line 200 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].CalFlux(myBulk, false);
        }
    }
}
References OCP_FUNCNAME.
CalIPRT()
void AllWells::CalIPRT (const Bulk & myBulk, OCP_DBL dt)
Calculate Injection rate, total Injection, Production rate, total Production.
Definition at line 233 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    FGIR = 0;
    FWIR = 0;
    FOPR = 0;
    FGPR = 0;
    FWPR = 0;
    for (USI w = 0; w < numWell; w++) {
        wells[w].WGIR = 0;
        wells[w].WWIR = 0;
        wells[w].WOPR = 0;
        wells[w].WGPR = 0;
        wells[w].WWPR = 0;
        if (wells[w].WellState()) {
            if (wells[w].WellType() == PROD) {
                wells[w].CalProdQj(myBulk, dt);
            } else {
                wells[w].CalInjQi(myBulk, dt);
            }
        }
        FGIR += wells[w].WGIR;
        FWIR += wells[w].WWIR;
        FOPR += wells[w].WOPR;
        FGPR += wells[w].WGPR;
        FWPR += wells[w].WWPR;
    }
    FGIT += FGIR * dt;
    FWIT += FWIR * dt;
    FOPT += FOPR * dt;
    FGPt += FGPR * dt;
    FWPT += FWPR * dt;
}
References OCP_FUNCNAME, and PROD.
CalMaxBHPChange()
void AllWells::CalMaxBHPChange ()
Definition at line 408 of file AllWells.cpp.
{
    dPmax = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            dPmax = max(dPmax, fabs(wells[w].BHP - wells[w].lBHP));
        }
    }
}
CalProdWeight()
void AllWells::CalProdWeight (const Bulk & myBulk)
Calculate Prodweight.
Definition at line 211 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].CalProdWeight(myBulk);
        }
    }
}
References OCP_FUNCNAME.
CalReInjFluid()
void AllWells::CalReInjFluid (const Bulk & myBulk)
Calculate Reinjection fluid.
Definition at line 270 of file AllWells.cpp.
{
    for (auto& wG : wellGroup) {
        if (wG.reInj) {
            const USI nc = myBulk.GetComNum();
            // const USI np = myBulk.GetPhaseNum();
            fill(wG.zi.begin(), wG.zi.end(), 0.0);
            for (auto& prod : wellGroup[wG.prodGroup].wIdPROD) {
                Daxpy(nc, 1.0, &wells[prod].qi_lbmol[0], &wG.zi[0]);
            }
            OCP_DBL qt = Dnorm1(nc, &wG.zi[0]);
            if (fabs(qt) < 1E-8) {
                // Recalculate zi
                fill(wG.zi.begin(), wG.zi.end(), 0.0);
                for (auto& prod : wellGroup[wG.prodGroup].wIdPROD) {
                    wells[prod].CalReInjFluid(myBulk, wG.zi);
                }
                qt = Dnorm1(nc, &wG.zi[0]);
            }
            flashCal[0]->Flash(PRESSURE_STD, TEMPERATURE_STD, &wG.zi[0], 0, 0, 0);
            Dcopy(nc, &wG.zi[0], &flashCal[0]->xij[wG.injPhase * nc]);
            wG.xi = flashCal[0]->xi[wG.injPhase];
            wG.factor = wG.xi * flashCal[0]->v[wG.injPhase] / qt;
            // assign to every open injection well in wG
            for (auto& w : wG.wIdINJ) {
                if (wells[w].WellState()) {
                    wells[w].opt.reInj = true;
                    wells[w].opt.connWell = wG.wIdPROD;
                    wells[w].opt.injPhase = wG.injPhase;
                    wells[w].opt.zi = wG.zi;
                    wells[w].opt.xiINJ = wG.xi;
                    wells[w].opt.factor = wG.factor;
                    wells[w].opt.maxRate = -wG.saleRate * wG.xi * 1000; // Mscf -> ft3 -> lbmol
                }
            }
            //for (USI i = 0; i < nc; i++) {
            //    cout << scientific << wG.zi[i] << "   ";
            //}
            //cout << "xi:  " << wG.xi << "    Factor:   " << wG.factor;
            //cout << endl;
        }
    }
}
References Daxpy(), Dcopy(), Dnorm1(), Bulk::GetComNum(), PRESSURE_STD, and TEMPERATURE_STD.
CalResAIMt()
void AllWells::CalResAIMt (ResFIM & resFIM, const Bulk & myBulk, const OCP_DBL & dt) const
Calculate Resiual and relative Resiual for local FIM.
Definition at line 674 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].CalResAIMt(resFIM, myBulk, dt, wId, wells);
            wId++;
        }
    }
    // cout << "Well  " << resFIM.maxRelRes_v;
}
References OCP_FUNCNAME.
CalResFIM()
void AllWells::CalResFIM (ResFIM & resFIM, const Bulk & myBulk, const OCP_DBL & dt) const
Calculate Resiual and relative Resiual for FIM.
Definition at line 569 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].CalResFIM(resFIM, myBulk, dt, wId, wells);
            wId++;
        }
    }
    // cout << "Well  " << resFIM.maxRelRes_v;
}
References OCP_FUNCNAME.
CalTrans()
void AllWells::CalTrans (const Bulk & myBulk)
Calculate Transmissibility of Wells.
Definition at line 189 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].CalTrans(myBulk);
        }
    }
}
References OCP_FUNCNAME.
CalWellQT()
OCP_DBL AllWells::CalWellQT ()
Definition at line 418 of file AllWells.cpp.
{
    QT = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            for (auto& q : wells[w].qi_lbmol) {
                QT += q;
            }
        }
    }
    return QT;
}
CheckP()
OCP_INT AllWells::CheckP (const Bulk & myBulk)
Check if unreasonable well pressure or perforation pressure occurs.
Definition at line 337 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    // 0 : All correct
    // 1   : negative P, cut the timestep and resolve
    // 2.1 : change well mode to BHP, resolve
    // 2.2 : crossflow happens, then close corresponding perf, resolve
    bool flag2 = false;
    bool flag3 = false;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            OCP_INT flag = wells[w].CheckP(myBulk);
//#ifdef _DEBUG
            // wells[w].ShowPerfStatus();
//#endif // _DEBUG
            switch (flag) {
                case 1:
                    return 1;
                case 2:
                    flag2 = true;
                    break;
                case 3:
                    flag3 = true;
                    break;
                default:
                    break;
            }
        }
    }
    if (flag2 || flag3) return 2;
    return 0;
}
References OCP_FUNCNAME.
GetdBHPmax()
OCP_DBL AllWells::GetdBHPmax () const inline
Definition at line 141 of file AllWells.hpp.
{ return dPmax; }
GetFGIR()
OCP_DBL AllWells::GetFGIR () const inline
Return gas injection rate in field.
Definition at line 155 of file AllWells.hpp.
{ return FGIR; }
GetFGIT()
OCP_DBL AllWells::GetFGIT () const inline
Return gas water injection in field.
Definition at line 157 of file AllWells.hpp.
{ return FGIT; }
GetFGPR()
OCP_DBL AllWells::GetFGPR () const inline
Return gas production rate in field.
Definition at line 147 of file AllWells.hpp.
{ return FGPR; }
GetFGPT()
OCP_DBL AllWells::GetFGPT () const inline
Return total gas production in field.
Definition at line 149 of file AllWells.hpp.
{ return FGPt; }
GetFOPR()
OCP_DBL AllWells::GetFOPR () const inline
Return oil production rate in field.
Definition at line 143 of file AllWells.hpp.
{ return FOPR; }
GetFOPT()
OCP_DBL AllWells::GetFOPT () const inline
Return total oil production in field.
Definition at line 145 of file AllWells.hpp.
{ return FOPT; }
GetFWIR()
OCP_DBL AllWells::GetFWIR () const inline
Return water injection rate in field.
Definition at line 159 of file AllWells.hpp.
{ return FWIR; }
GetFWIT()
OCP_DBL AllWells::GetFWIT () const inline
Return total water injection in field.
Definition at line 161 of file AllWells.hpp.
{ return FWIT; }
GetFWPR()
OCP_DBL AllWells::GetFWPR () const inline
Return water production rate in field.
Definition at line 151 of file AllWells.hpp.
{ return FWPR; }
GetFWPT()
OCP_DBL AllWells::GetFWPT () const inline
Return total water production in field.
Definition at line 153 of file AllWells.hpp.
{ return FWPT; }
GetIndex()
USI AllWells::GetIndex (const string & name) const
Return the index of specified well.
Definition at line 376 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].name == name) {
            return w;
        }
    }
    OCP_ABORT("Well name not found!");
}
References OCP_ABORT, and OCP_FUNCNAME.
GetMaxWellPerNum()
USI AllWells::GetMaxWellPerNum () const
Calculate mamimum num of perforations of all Wells.
Definition at line 397 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    USI m = 0;
    for (USI w = 0; w < numWell; w++) {
        m = max(m, wells[w].numPerf);
    }
    return m;
}
References OCP_FUNCNAME.
GetSol01FIM()
void AllWells::GetSol01FIM (const vector< OCP_DBL > & u, const OCP_USI & bId, const USI & len, const OCP_DBL & alpha)
Definition at line 556 of file AllWells.cpp.
{
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].BHP += u[(bId + wId) * len] * alpha;
            wells[w].UpdatePerfP();
            wId++;
        }
    }
}
GetSolAIMt()
void AllWells::GetSolAIMt (const vector< OCP_DBL > & u, const OCP_USI & bId, const USI & len)
Get solution from solver class after linear system is solved for local FIM.
Definition at line 689 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].BHP += u[(bId + wId) * len];
            wells[w].UpdatePerfP();
            wId++;
        }
    }
}
References OCP_FUNCNAME.
GetSolFIM()
void AllWells::GetSolFIM (const vector< OCP_DBL > & u, const OCP_USI & bId, const USI & len)
Get solution from solver class after linear system is solved for FIM.
Definition at line 542 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].BHP += u[(bId + wId) * len];
            wells[w].UpdatePerfP();
            wId++;
        }
    }
}
References OCP_FUNCNAME.
GetSolIMPEC()
void AllWells::GetSolIMPEC (const vector< OCP_DBL > & u, const OCP_USI & bId)
Update Well P and Perforation P after linear system is solved for IMPEC.
Definition at line 491 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].BHP = u[bId + wId];
            wells[w].UpdatePerfP();
            wId++;
        }
    }
}
References OCP_FUNCNAME.
GetWBHP()
OCP_DBL AllWells::GetWBHP (const USI & w) const inline
Return the BHP of wth well.
Definition at line 183 of file AllWells.hpp.
{
        if (wells[w].WellState())
            return wells[w].BHP;
        else
            return 0;
    }
GetWellDg()
OCP_DBL AllWells::GetWellDg (const USI & w, const USI & p) const inline
Return the pth dG of wth well.
Definition at line 190 of file AllWells.hpp.
{ return wells[w].dG[p]; }
GetWellName()
string AllWells::GetWellName (const USI & i) const inline
Return the name of specified well.
Definition at line 131 of file AllWells.hpp.
{ return wells[i].name; }
GetWellNum()
USI AllWells::GetWellNum () const inline
Return the num of wells.
Definition at line 129 of file AllWells.hpp.
{ return numWell; }
GetWellPerfNum() [1/2]
USI AllWells::GetWellPerfNum () const
Return the num of perforations of all wells.
Definition at line 388 of file AllWells.cpp.
{
    USI numPerf = 0;
    for (USI w = 0; w < numWell; w++) {
        numPerf += wells[w].numPerf;
    }
    return numPerf;
}
GetWellPerfNum() [2/2]
USI AllWells::GetWellPerfNum (const USI & i) const inline
Return the num of perforations of well i.
Definition at line 135 of file AllWells.hpp.
{ return wells[i].numPerf; }
GetWGIR()
OCP_DBL AllWells::GetWGIR (const USI & w) const inline
Return gas injection rate of the wth well.
Definition at line 175 of file AllWells.hpp.
{ return wells[w].WGIR; }
GetWGIT()
OCP_DBL AllWells::GetWGIT (const USI & w) const inline
Return total gas injection of the wth well.
Definition at line 177 of file AllWells.hpp.
{ return wells[w].WGIT; }
GetWGPR()
OCP_DBL AllWells::GetWGPR (const USI & w) const inline
Return gas production rate of the wth well.
Definition at line 167 of file AllWells.hpp.
{ return wells[w].WGPR; }
GetWGPT()
OCP_DBL AllWells::GetWGPT (const USI & w) const inline
Return total gas production of the wth well.
Definition at line 169 of file AllWells.hpp.
{ return wells[w].WGPT; }
GetWOPR()
OCP_DBL AllWells::GetWOPR (const USI & w) const inline
Return oil production rate of the wth well.
Definition at line 163 of file AllWells.hpp.
{ return wells[w].WOPR; }
GetWOPT()
OCP_DBL AllWells::GetWOPT (const USI & w) const inline
Return total oil production of the wth well.
Definition at line 165 of file AllWells.hpp.
{ return wells[w].WOPT; }
GetWWIR()
OCP_DBL AllWells::GetWWIR (const USI & w) const inline
Return water injection rate of the wth well.
Definition at line 179 of file AllWells.hpp.
{ return wells[w].WWIR; }
GetWWIT()
OCP_DBL AllWells::GetWWIT (const USI & w) const inline
Return total water injection of the wth well.
Definition at line 181 of file AllWells.hpp.
{ return wells[w].WWIT; }
GetWWPR()
OCP_DBL AllWells::GetWWPR (const USI & w) const inline
Return water production rate of the wth well.
Definition at line 171 of file AllWells.hpp.
{ return wells[w].WWPR; }
GetWWPT()
OCP_DBL AllWells::GetWWPT (const USI & w) const inline
Return total water production of the wth well.
Definition at line 173 of file AllWells.hpp.
{ return wells[w].WWPT; }
InitBHP()
void AllWells::InitBHP (const Bulk & myBulk)
Set the initial well pressure.
Definition at line 162 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        wells[w].InitBHP(myBulk);
    }
}
References OCP_FUNCNAME.
InputParam()
void AllWells::InputParam (const ParamWell & paramWell)
Input param from ParamWell.
Definition at line 19 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    USI len = paramWell.solSet.size();
    solvents.resize(len);
    for (USI i = 0; i < len; i++) {
        solvents[i] = paramWell.solSet[i];
    }
    numWell = paramWell.well.size();
    wells.resize(numWell);
    USI         t = paramWell.criticalTime.size();
    vector<USI> wellCriticalTime;
    for (USI w = 0; w < numWell; w++) {
        wells[w].name  = paramWell.well[w].name;
        wells[w].group = paramWell.well[w].group;
        wells[w].depth = paramWell.well[w].depth;
        wells[w].I     = paramWell.well[w].I - 1;
        wells[w].J     = paramWell.well[w].J - 1;
        wells[w].InputPerfo(paramWell.well[w]);
        // opt
        wells[w].optSet.resize(t);
        USI n = paramWell.well[w].optParam.size();
        wellCriticalTime.clear();
        wellCriticalTime.resize(n + 1);
        for (USI i = 0; i < n; i++) {
            wellCriticalTime[i] = paramWell.well[w].optParam[i].d;
        }
        wellCriticalTime.back() = t;
        for (USI i = 0; i < n; i++) {
            for (USI d = wellCriticalTime[i]; d < wellCriticalTime[i + 1]; d++) {
                wells[w].optSet[d] = WellOpt(paramWell.well[w].optParam[i].opt);
            }
        }
    }
}
References ParamWell::criticalTime, OCP_FUNCNAME, ParamWell::solSet, and ParamWell::well.
MassConserveIMPEC()
void AllWells::MassConserveIMPEC (Bulk & myBulk, OCP_DBL dt)
Update moles of components in Bulks which connects to well.
Definition at line 447 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].MassConserveIMPEC(myBulk, dt);
        }
    }
}
References OCP_FUNCNAME.
PrepareWell()
void AllWells::PrepareWell (const Bulk & myBulk)
Calculate well properties at the beginning of each time step.
Definition at line 171 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].CalTrans(myBulk);
            wells[w].CalFlux(myBulk, true);
            wells[w].CalProdWeight(myBulk);
            wells[w].CaldG(myBulk);
            // test
            // wells[w].SmoothdG();
            wells[w].CheckOptMode(myBulk);
        }
    }
}
References OCP_FUNCNAME.
ResetBHP()
void AllWells::ResetBHP ()
Definition at line 326 of file AllWells.cpp.
{
    for (auto& w : wells) {
        if (w.WellState()) {
            w.BHP = w.lBHP;
            w.SetBHP();
            // w.dG = w.ldG;
        }
    }
}
ResetDg()
void AllWells::ResetDg () inline
Definition at line 122 of file AllWells.hpp.
    {
        for (auto& w : wells) w.dG = w.ldG;
    }
Setup()
void AllWells::Setup (const Grid & myGrid, const Bulk & myBulk)
Setup well in allWells.
Definition at line 58 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    SetupWell(myGrid, myBulk);
    SetupMixture(myBulk);
}
References OCP_FUNCNAME, SetupMixture(), and SetupWell().
SetupMixture()
void AllWells::SetupMixture (const Bulk & myBulk)
get the mixture from bulk -— usless now
Definition at line 132 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    flashCal = myBulk.GetMixture();
}
References Bulk::GetMixture(), and OCP_FUNCNAME.
SetupWell()
void AllWells::SetupWell (const Grid & myGrid, const Bulk & myBulk)
complete the information of well according to Grid and Bulk.
Definition at line 66 of file AllWells.cpp.
{
    OCP_FUNCNAME;
    for (USI w = 0; w < numWell; w++) {
        wells[w].Setup(myGrid, myBulk, solvents);
    }
}
References OCP_FUNCNAME.
SetupWellBulk()
void AllWells::SetupWellBulk (Bulk & myBulk) const
Setup bulks which are penetrated by wells.
Definition at line 139 of file AllWells.cpp.
{
    myBulk.ClearWellBulkId();
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            wells[w].SetupWellBulk(myBulk);
        }
    }
}
SetupWellGroup()
void AllWells::SetupWellGroup (const Bulk & myBulk)
Setup information of wellGroup.
Definition at line 76 of file AllWells.cpp.
{
    wellGroup.clear();
    // Field Group, contain all wells
    wellGroup.push_back(WellGroup("Field"));
    for (USI w = 0; w < numWell; w++) {
        wellGroup[0].wId.push_back(w);
        if (wells[w].WellType() == INJ)
            wellGroup[0].wIdINJ.push_back(w);
        else
            wellGroup[0].wIdPROD.push_back(w);
    }
    // other subgroups
    USI glen = 1;
    USI g = 1;
    for (USI w = 0; w < numWell; w++) {
        for (g = 1; g < glen; g++) {
            if (wells[w].group == wellGroup[g].name) {
                // existing group
                wellGroup[g].wId.push_back(w);
                if (wells[w].WellType() == INJ)
                    wellGroup[g].wIdINJ.push_back(w);
                else
                    wellGroup[g].wIdPROD.push_back(w);
                break;
            }
        }
        if (g == glen && wells[w].group != "Field") {
            // new group
            wellGroup.push_back(WellGroup(wells[w].group));
            wellGroup[glen].wId.push_back(w);
            if (wells[w].WellType() == INJ)  wellGroup[glen].wIdINJ.push_back(w);
            else wellGroup[glen].wIdPROD.push_back(w);
            glen++;
        }
    }
    numGroup = wellGroup.size();
    // relation between wellGroup should be completed if "node groups" exist
    // control of group should be update according to input file
    // for test
    if (false) {
        wellGroup[0].reInj = true;
        wellGroup[0].saleRate = 1500;
        wellGroup[0].injPhase = GAS;
        wellGroup[0].prodGroup = 0;
    }
    wellGroup[0].zi.resize(myBulk.GetComNum());
    CalReInjFluid(myBulk);
}
References CalReInjFluid(), GAS, Bulk::GetComNum(), and INJ.
ShowRes()
void AllWells::ShowRes (const vector< OCP_DBL > & res, const Bulk & myBulk) const
Show Res.
Definition at line 584 of file AllWells.cpp.
{
    USI wId = 0;
    for (USI w = 0; w < numWell; w++) {
        if (wells[w].WellState()) {
            cout << endl;
            wells[w].ShowRes(wId, res, myBulk);
            wId++;
        }
    }
    cout << endl;
}
ShowWellStatus()
void AllWells::ShowWellStatus (const Bulk & myBulk) inline
Definition at line 192 of file AllWells.hpp.
{ for (USI w = 0; w < numWell; w++) wells[w].ShowPerfStatus(myBulk); }
UpdateLastBHP()
void AllWells::UpdateLastBHP () inline
Definition at line 115 of file AllWells.hpp.
{ for (auto& w : wells) w.lBHP = w.BHP; }
UpdateLastDg()
void AllWells::UpdateLastDg () inline
Reset dG to ldG for each well.
Definition at line 118 of file AllWells.hpp.
    {
        for (auto& w : wells) w.ldG = w.dG;
    }
Friends And Related Function Documentation
DetailInfo
friend class DetailInfo friend
Definition at line 73 of file AllWells.hpp.
Reservoir
friend class Reservoir friend
Definition at line 72 of file AllWells.hpp.
The documentation for this class was generated from the following files:
AllWells.hpp
AllWells.cpp