OpenCAEPoro: BOMixture_OW Class Reference
BOMixture_OW Class Reference
Public Member Functions
BOMixture_OW (const ParamReservoir &rs_param, const USI &i)
void InitFlash (const OCP_DBL &Pin, const OCP_DBL &Pbbin, const OCP_DBL &Tin, const OCP_DBL *Sjin, const OCP_DBL &Vpore, const OCP_DBL *Ziin) override
flash calculation with saturation of phases.
void Flash (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin, const USI &ftype, const USI &lastNP, const OCP_DBL *lastKs) override
Flash calculation with moles of components.
void FlashDeriv (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin, const USI &ftype, const USI &lastNP, const OCP_DBL *lastKs) override
Flash calculation with moles of components and Calculate the derivative.
void FlashDeriv_n (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin, const OCP_DBL *Sjin, const OCP_DBL *xijin, const OCP_DBL *njin, const USI &ftype, const USI *phaseExistin, const USI &lastNP, const OCP_DBL *lastKs) override
OCP_DBL XiPhase (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Ziin) override
OCP_DBL RhoPhase (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Ziin) override
return mass density of phase.
OCP_DBL GammaPhaseO (const OCP_DBL &Pin, const OCP_DBL &Pbbin) override
return gamma of oil phase, gamma equals to mass density times gravity factor.
OCP_DBL GammaPhaseW (const OCP_DBL &Pin) override
return gamma of water phase, gamma equals to mass density times gravity factor.
Public Member Functions inherited from BOMixture
void BOMixtureInit (const ParamReservoir &rs_param)
virtual OCP_DBL GammaPhaseG (const OCP_DBL &Pin) override
return gamma of gas phase, gamma equals to mass density times gravity factor.
OCP_DBL GammaPhaseOG (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Ziin) override
USI GetFtype () override
OCP_SIN GetMinEigenSkip () override
bool GetFlagSkip () override
OCP_DBL GetSurTen () override
OCP_DBL GetErrorPEC () override
OCP_ULL GetSSMSTAiters () override
OCP_ULL GetNRSTAiters () override
OCP_ULL GetSSMSPiters () override
OCP_ULL GetNRSPiters () override
Public Member Functions inherited from Mixture
void Allocate ()
Allocate memory for common variables for basic class.
virtual void SetPVTW ()
USI GetType () const
return type of mixture.
virtual bool IsEmpty_PVDG () const
Check whether Table PVDG is empty, it will only be used in black oil model.
void CheckNi (const OCP_DBL *Ni)
Additional Inherited Members
Protected Attributes inherited from BOMixture
OCP_DBL std_RhoO
< others.
OCP_DBL std_GammaO
std_RhoO * gravity factor.
OCP_DBL std_RhoG
mass density of gas phase in standard condition.
OCP_DBL std_GammaG
std_RhoG * gravity factor.
OCP_DBL std_RhoW
mass density of water phase in standard condition.
OCP_DBL std_GammaW
std_RhoW * gravity factor.
Protected Attributes inherited from Mixture
USI mixtureType
USI numPhase
num of phases.
USI numCom
num of components.
OCP_DBL P
pressure when flash calculation.
OCP_DBL T
temperature when flash calculation.
vector< OCP_DBL > Ni
moles of component: numCom
vector< bool > phaseExist
existence of phase: numPhase
vector< OCP_DBL > S
saturation of phase: numPhase
vector< OCP_DBL > rho
mass density of phase: numPhase
vector< OCP_DBL > xi
molar density of phase: numPhase
vector< OCP_DBL > xij
vector< OCP_DBL > nj
mole number of phase j
vector< OCP_DBL > mu
viscosity of phase: numPhase
vector< OCP_DBL > v
volume of phase: numPhase;
OCP_DBL vf
volume of total fluids.
OCP_DBL Nt
Total moles of Components.
vector< vector< OCP_DBL > > vji
dvj / dNi, used in 2 hydrocarbon phase in EOS; or dvj / dnij
vector< OCP_DBL > vjp
dvj / dp, used in 2 hydrocarbon phase in EOS
OCP_DBL vfp
vector< OCP_DBL > vfi
vector< OCP_DBL > muP
d mu / dP: numPhase
vector< OCP_DBL > xiP
d xi / dP: numphase
vector< OCP_DBL > rhoP
d rho / dP: numphase
vector< OCP_DBL > muN
d mu[j] / d N[i]: numphase * numCom
vector< OCP_DBL > xiN
d xi[j] / d N[i]: numphase * numCom
vector< OCP_DBL > rhoN
d rho[j] / d N[i]: numphase * numCom
vector< OCP_DBL > mux
d mu[j] / d x[i][j]: numphase * numCom
vector< OCP_DBL > xix
d xi[j] / d x[i][j]: numphase * numCom
vector< OCP_DBL > rhox
d rho[j] / d x[i][j]: numphase * numCom
vector< OCP_DBL > dXsdXp
the derivates of second variables wrt. primary variables
vector< USI > pEnumCom
see pEnumCom in bulk
vector< OCP_DBL > res
residual of a set of equations
OCP_DBL resPc
a precalculated value
vector< OCP_DBL > keyDer
d (xij*xi/mu) / dP or dNk
Detailed Description
Definition at line 109 of file MixtureBO.hpp.
Constructor & Destructor Documentation
BOMixture_OW()
BOMixture_OW::BOMixture_OW (const ParamReservoir & rs_param, const USI & i)
Definition at line 18 of file MixtureBO2_OW.cpp.
{
    BOMixtureInit(rs_param);
    PVTW.Setup(rs_param.PVTW_T.data[i]);
    PVDO.Setup(rs_param.PVDO_T.data[i]);
    data.resize(5, 0);
    cdata.resize(5, 0);
}
Member Function Documentation
Flash()
void BOMixture_OW::Flash (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Niin, const USI & ftype, const USI & lastNP, const OCP_DBL * lastKs) override virtual
Flash calculation with moles of components.
Implements Mixture.
Definition at line 77 of file MixtureBO2_OW.cpp.
{
    phaseExist[0] = true;
    phaseExist[1] = true;
    P     = Pin;
    Ni[0] = Niin[0];
    Ni[1] = Niin[1];
    // Water Properties
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw  = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[1]  = data[3];
    xi[1]  = 1 / (bw * CONV1);
    rho[1] = std_RhoW / bw;
    // Oil Properties
    PVDO.Eval_All(0, P, data, cdata);
    OCP_DBL bo  = data[1];
    OCP_DBL bop = cdata[1];
    mu[0]  = data[2];
    xi[0]  = 1 / (CONV1 * bo);
    rho[0] = std_RhoO / bo;
    xij[0 * 2 + 0] = 1;
    xij[0 * 2 + 1] = 0;
    xij[1 * 2 + 0] = 0;
    xij[1 * 2 + 1] = 1;
    v[0]   = CONV1 * Ni[0] * bo;
    v[1]   = CONV1 * Ni[1] * bw;
    vf     = v[0] + v[1];
    S[0]   = v[0] / vf;
    S[1]   = v[1] / vf;
    vfi[0] = CONV1 * bo;
    vfi[1] = CONV1 * bw;
    vfp    = CONV1 * Ni[0] * bop + CONV1 * Ni[1] * bwp;
}
References CONV1, OCPTable::Eval_All(), Mixture::mu, Mixture::Ni, Mixture::P, Mixture::phaseExist, Mixture::rho, Mixture::S, BOMixture::std_RhoO, BOMixture::std_RhoW, Mixture::v, Mixture::vf, Mixture::vfi, Mixture::vfp, Mixture::xi, and Mixture::xij.
FlashDeriv()
void BOMixture_OW::FlashDeriv (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Niin, const USI & ftype, const USI & lastNP, const OCP_DBL * lastKs) override virtual
Flash calculation with moles of components and Calculate the derivative.
Implements Mixture.
Definition at line 123 of file MixtureBO2_OW.cpp.
{
    phaseExist[0] = true;
    phaseExist[1] = true;
    fill(dXsdXp.begin(), dXsdXp.end(), 0.0);
    fill(pEnumCom.begin(), pEnumCom.end(), 0);
    P     = Pin;
    Ni[0] = Niin[0];
    Ni[1] = Niin[1];
    Nt    = Ni[0] + Ni[1];
    // Water Properties
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw  = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[1]  = data[3];
    xi[1]  = 1 / (bw * CONV1);
    rho[1] = std_RhoW / bw;
    muP[1]  = cdata[3];
    xiP[1]  = -bwp / (bw * bw * CONV1);
    rhoP[1] = CONV1 * xiP[1] * std_RhoW;
    // Oil Properties
    PVDO.Eval_All(0, P, data, cdata);
    OCP_DBL bo  = data[1];
    OCP_DBL bop = cdata[1];
    mu[0]  = data[2];
    xi[0]  = 1 / (CONV1 * bo);
    rho[0] = std_RhoO / bo;
    muP[0]  = cdata[2];
    xiP[0]  = -xi[0] * bop / bo;
    rhoP[0] = -rho[0] * bop / bo;
    xij[0 * 2 + 0] = 1;
    xij[0 * 2 + 1] = 0;
    xij[1 * 2 + 0] = 0;
    xij[1 * 2 + 1] = 1;
    v[0]   = CONV1 * Ni[0] * bo;
    v[1]   = CONV1 * Ni[1] * bw;
    vf     = v[0] + v[1];
    S[0]   = v[0] / vf;
    S[1]   = v[1] / vf;
    vfi[0] = CONV1 * bo;
    vfi[1] = CONV1 * bw;
    vfp    = CONV1 * Ni[0] * bop + CONV1 * Ni[1] * bwp;
    dXsdXp[0] = (CONV1 * Ni[0] * bop - S[0] * vfp) / vf; // dSo / dP
    dXsdXp[1] = (CONV1 * bo - S[0] * vfi[0]) / vf;       // dSo / dNo
    dXsdXp[2] = -S[0] * vfi[1] / vf;                     // dSo / dNw
    dXsdXp[3] = (CONV1 * Ni[1] * bwp - S[1] * vfp) / vf; // dSw / dP
    dXsdXp[4] = -S[1] * vfi[0] / vf;                     // dSw / dNo
    dXsdXp[5] = (CONV1 * bw - S[1] * vfi[1]) / vf;       // dSw / dNw
}
References CONV1, Mixture::dXsdXp, OCPTable::Eval_All(), Mixture::mu, Mixture::muP, Mixture::Ni, Mixture::Nt, Mixture::P, Mixture::pEnumCom, Mixture::phaseExist, Mixture::rho, Mixture::rhoP, Mixture::S, BOMixture::std_RhoO, BOMixture::std_RhoW, Mixture::v, Mixture::vf, Mixture::vfi, Mixture::vfp, Mixture::xi, Mixture::xij, and Mixture::xiP.
FlashDeriv_n()
void BOMixture_OW::FlashDeriv_n (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Niin, const OCP_DBL * Sjin, const OCP_DBL * xijin, const OCP_DBL * njin, const USI & ftype, const USI * phaseExistin, const USI & lastNP, const OCP_DBL * lastKs) inline override virtual
Implements Mixture.
Definition at line 123 of file MixtureBO.hpp.
{
        OCP_ABORT("Not Completed!");
    }
GammaPhaseO()
OCP_DBL BOMixture_OW::GammaPhaseO (const OCP_DBL & Pin, const OCP_DBL & Pbbin) override virtual
return gamma of oil phase, gamma equals to mass density times gravity factor.
Reimplemented from BOMixture.
Definition at line 224 of file MixtureBO2_OW.cpp.
{
    OCP_DBL bo     = PVDO.Eval(0, Pin, 1);
    OCP_DBL gammaO = std_GammaO / bo;
    return gammaO;
}
References OCPTable::Eval(), and BOMixture::std_GammaO.
GammaPhaseW()
OCP_DBL BOMixture_OW::GammaPhaseW (const OCP_DBL & Pin) override virtual
return gamma of water phase, gamma equals to mass density times gravity factor.
Reimplemented from BOMixture.
Definition at line 232 of file MixtureBO2_OW.cpp.
{
    PVTW.Eval_All(0, Pin, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw = (bw0 * (1 - cbw * (Pin - Pw0)));
    return std_GammaW / bw;
}
References OCPTable::Eval_All(), and BOMixture::std_GammaW.
InitFlash()
void BOMixture_OW::InitFlash (const OCP_DBL & Pin, const OCP_DBL & Pbbin, const OCP_DBL & Tin, const OCP_DBL * Sjin, const OCP_DBL & Vpore, const OCP_DBL * Ziin) override virtual
flash calculation with saturation of phases.
Implements Mixture.
Definition at line 29 of file MixtureBO2_OW.cpp.
{
    phaseExist[0] = true;
    phaseExist[1] = true;
    P    = Pin;
    S[1] = Sjin[1];
    // Water Properties
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw  = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[1]  = data[3];
    xi[1]  = 1 / (bw * CONV1);
    rho[1] = std_RhoW / bw;
    Ni[1] = Vpore * S[1] * xi[1];
    // Oil Properties
    PVDO.Eval_All(0, P, data, cdata);
    OCP_DBL bo  = data[1];
    OCP_DBL bop = cdata[1];
    mu[0]  = data[2];
    xi[0]  = 1 / (CONV1 * bo);
    rho[0] = std_RhoO / bo;
    Ni[0]  = Vpore * (1 - S[1]) * xi[0];
    xij[0 * 2 + 0] = 1;
    xij[0 * 2 + 1] = 0;
    xij[1 * 2 + 0] = 0;
    xij[1 * 2 + 1] = 1;
    v[0]   = CONV1 * Ni[0] * bo;
    v[1]   = CONV1 * Ni[1] * bw;
    vf     = v[0] + v[1];
    S[0]   = v[0] / vf;
    S[1]   = v[1] / vf;
    vfi[0] = CONV1 * bo;
    vfi[1] = CONV1 * bw;
    vfp    = CONV1 * Ni[0] * bop + CONV1 * Ni[1] * bwp;
}
References CONV1, OCPTable::Eval_All(), Mixture::mu, Mixture::Ni, Mixture::P, Mixture::phaseExist, Mixture::rho, Mixture::S, BOMixture::std_RhoO, BOMixture::std_RhoW, Mixture::v, Mixture::vf, Mixture::vfi, Mixture::vfp, Mixture::xi, and Mixture::xij.
RhoPhase()
OCP_DBL BOMixture_OW::RhoPhase (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Ziin) override virtual
return mass density of phase.
Implements Mixture.
Definition at line 207 of file MixtureBO2_OW.cpp.
{
    if (Ziin[1] > 1 - TINY) {
        // inj fluid is water
        PVTW.Eval_All(0, Pin, data, cdata);
        OCP_DBL Pw0  = data[0];
        OCP_DBL bw0  = data[1];
        OCP_DBL cbw  = data[2];
        OCP_DBL bw   = bw0 * (1 - cbw * (P - Pw0));
        OCP_DBL rhow = std_RhoW / bw;
        return rhow;
    } else {
        OCP_ABORT("Wrong Zi!");
    }
}
References OCPTable::Eval_All(), OCP_ABORT, Mixture::P, BOMixture::std_RhoW, and TINY.
XiPhase()
OCP_DBL BOMixture_OW::XiPhase (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Ziin) override virtual
Return molar density of phase, it's used to calculate the molar density of injection fluids in injection wells.
Implements Mixture.
Definition at line 191 of file MixtureBO2_OW.cpp.
{
    if (Ziin[1] > 1 - TINY) {
        // inj fluid is water
        PVTW.Eval_All(0, Pin, data, cdata);
        OCP_DBL Pw0 = data[0];
        OCP_DBL bw0 = data[1];
        OCP_DBL cbw = data[2];
        OCP_DBL bw  = bw0 * (1 - cbw * (P - Pw0));
        OCP_DBL xiw = 1 / (CONV1 * bw);
        return xiw;
    } else {
        OCP_ABORT("Wrong Zi!");
    }
}
References CONV1, OCPTable::Eval_All(), OCP_ABORT, Mixture::P, and TINY.
The documentation for this class was generated from the following files:
MixtureBO.hpp
MixtureBO2_OW.cpp