OpenCAEPoro: FlowUnit_ODGW01 Class Reference
FlowUnit_ODGW01 Class Reference
Public Member Functions
FlowUnit_ODGW01 (const ParamReservoir &rs_param, const USI &i)
virtual void CalKrPc (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp) override
calculate relative permeability and capillary pressure.
virtual void CalKrPcDeriv (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, OCP_DBL *dkrdS, OCP_DBL *dPcjdS, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp) override
OCP_DBL CalKro_Stone2Der (OCP_DBL krow, OCP_DBL krog, OCP_DBL krw, OCP_DBL krg, OCP_DBL dkrwdSw, OCP_DBL dkrowdSw, OCP_DBL dkrgdSg, OCP_DBL dkrogdSg, OCP_DBL &out_dkrodSw, OCP_DBL &out_dkrodSg) const
OCP_DBL CalKro_DefaultDer (const OCP_DBL &Sg, const OCP_DBL &Sw, const OCP_DBL &krog, const OCP_DBL &krow, const OCP_DBL &dkrogSg, const OCP_DBL &dkrowSw, OCP_DBL &dkroSg, OCP_DBL &dkroSw) const
OCP_DBL GetPcowBySw (const OCP_DBL &sw) override
Pcow = Po - Pw.
OCP_DBL GetSwByPcow (const OCP_DBL &pcow) override
OCP_DBL GetPcgoBySg (const OCP_DBL &sg) override
Pcgo = Pg - Po.
OCP_DBL GetSgByPcgo (const OCP_DBL &pcgo) override
OCP_DBL GetSwByPcgw (const OCP_DBL &pcgw) override
Pcgw = Pg - Pw.
void Generate_SWPCWG ()
Public Member Functions inherited from FlowUnit_ODGW
OCP_DBL CalKro_Stone2 (const OCP_DBL &krow, const OCP_DBL &krog, const OCP_DBL &krw, const OCP_DBL &krg) const
OCP_DBL CalKro_Default (const OCP_DBL &Sg, const OCP_DBL &Sw, const OCP_DBL &krog, const OCP_DBL &krow) const
OCP_DBL GetSwco () const override
const vector< OCP_DBL > & GetScm () const override
Public Member Functions inherited from FlowUnit
FlowUnit ()=default
Default constructor.
virtual OCP_DBL GetPcowBySw (const OCP_DBL &sw)=0
Pcow = Po - Pw.
virtual OCP_DBL GetSwByPcow (const OCP_DBL &pcow)=0
virtual OCP_DBL GetPcgoBySg (const OCP_DBL &sg)=0
Pcgo = Pg - Po.
virtual OCP_DBL GetSgByPcgo (const OCP_DBL &pcgo)=0
virtual OCP_DBL GetSwByPcgw (const OCP_DBL &pcgw)=0
Pcgw = Pg - Pw.
virtual OCP_DBL GetSwco () const =0
virtual const vector< OCP_DBL > & GetScm () const =0
virtual void CalKrPc (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp)=0
calculate relative permeability and capillary pressure.
virtual void CalKrPcDeriv (const OCP_DBL *S_in, OCP_DBL *kr_out, OCP_DBL *pc_out, OCP_DBL *dkrdS, OCP_DBL *dPcjdS, const OCP_DBL &MySurTen, OCP_DBL &MyFk, OCP_DBL &MyFp)=0
Protected Attributes
OCPTable SGOF
saturation table about gas and oil.
OCPTable SWOF
saturation table about water and oil.
vector< OCP_DBL > data
container used to store the results of values of interpolation.
vector< OCP_DBL > cdata
container used to store the results of slopes of interpolation.
OCPTable SWPCGW
Protected Attributes inherited from FlowUnit_ODGW
OCP_DBL kroMax
oil relative permeability in the presence of connate water only, used in stone2
OCP_DBL Swco
Saturation of connate water.
vector< OCP_DBL > Scm
critical saturation when phase becomes mobile / immobile
Detailed Description
Definition at line 186 of file FlowUnit.hpp.
Constructor & Destructor Documentation
FlowUnit_ODGW01()
FlowUnit_ODGW01::FlowUnit_ODGW01 (const ParamReservoir & rs_param, const USI & i)
Definition at line 167 of file FlowUnit.cpp.
{
    SWOF.Setup(rs_param.SWOF_T.data[i]);
    SGOF.Setup(rs_param.SGOF_T.data[i]);
    kroMax = SWOF.GetCol(2)[0];
    Swco = SWOF.GetCol(0)[0];
    data.resize(4, 0);
    cdata.resize(4, 0);
    Generate_SWPCWG();
    Scm.resize(3, 0);
    // oil, set to zero now
    OCP_INT tmprow;
    tmprow = SGOF.GetRowZero(1);
    if (tmprow >= 0)  Scm[1] = SGOF.GetCol(0)[tmprow];
    tmprow = SWOF.GetRowZero(1);
    if (tmprow >= 0)  Scm[2] = SWOF.GetCol(0)[tmprow];
}
Member Function Documentation
CalKro_DefaultDer()
OCP_DBL FlowUnit_ODGW01::CalKro_DefaultDer (const OCP_DBL & Sg, const OCP_DBL & Sw, const OCP_DBL & krog, const OCP_DBL & krow, const OCP_DBL & dkrogSg, const OCP_DBL & dkrowSw, OCP_DBL & dkroSg, OCP_DBL & dkroSw) const
Definition at line 303 of file FlowUnit.cpp.
{
    OCP_DBL tmp = Sg + Sw - Swco;
    if (tmp <= TINY) {
        dkroSg = 0;
        dkroSw = 0;
        return kroMax;
    }
    OCP_DBL kro = (Sg * krog + (Sw - Swco) * krow) / tmp;
    dkroSg = (krog + Sg * dkrogSg - kro) / tmp;
    dkroSw = (krow + (Sw - Swco) * dkrowSw - kro) / tmp;
    return kro;
}
CalKro_Stone2Der()
OCP_DBL FlowUnit_ODGW01::CalKro_Stone2Der (OCP_DBL krow, OCP_DBL krog, OCP_DBL krw, OCP_DBL krg, OCP_DBL dkrwdSw, OCP_DBL dkrowdSw, OCP_DBL dkrgdSg, OCP_DBL dkrogdSg, OCP_DBL & out_dkrodSw, OCP_DBL & out_dkrodSg) const
Definition at line 280 of file FlowUnit.cpp.
{
    OCP_DBL kro, dkrodSw, dkrodSg;
    kro = kroMax * ((krow / kroMax + krw) * (krog / kroMax + krg) - (krw + krg));
    dkrodSw =
        kroMax * ((dkrowdSw / kroMax + dkrwdSw) * (krog / kroMax + krg) - (dkrwdSw));
    dkrodSg =
        kroMax * ((krow / kroMax + krw) * (dkrogdSg / kroMax + dkrgdSg) - (dkrgdSg));
    if (kro < 0) {
        kro = 0;
        dkrodSg = 0;
        dkrodSw = 0;
    }
    out_dkrodSw = dkrodSw;
    out_dkrodSg = dkrodSg;
    return kro;
}
CalKrPc()
void FlowUnit_ODGW01::CalKrPc (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out, const OCP_DBL & MySurTen, OCP_DBL & MyFk, OCP_DBL & MyFp) override virtual
calculate relative permeability and capillary pressure.
Implements FlowUnit.
Reimplemented in FlowUnit_ODGW01_Miscible.
Definition at line 190 of file FlowUnit.cpp.
{
    const OCP_DBL Sg = S_in[1];
    const OCP_DBL Sw = S_in[2];
    // three phase black oil model using stone 2
    SWOF.Eval_All(0, Sw, data, cdata);
    const OCP_DBL krw = data[1];
    const OCP_DBL krow = data[2];
    const OCP_DBL Pcwo = -data[3];
    SGOF.Eval_All(0, Sg, data, cdata);
    const OCP_DBL krg = data[1];
    const OCP_DBL krog = data[2];
    const OCP_DBL Pcgo = data[3];
    const OCP_DBL kro = CalKro_Stone2(krow, krog, krw, krg);
    // OCP_DBL kro = CalKro_Default(Sg, Sw, krog, krow);
    kr_out[0] = kro;
    kr_out[1] = krg;
    kr_out[2] = krw;
    pc_out[0] = 0;
    pc_out[1] = Pcgo;
    pc_out[2] = Pcwo;
}
References cdata, data, OCPTable::Eval_All(), SGOF, and SWOF.
CalKrPcDeriv()
void FlowUnit_ODGW01::CalKrPcDeriv (const OCP_DBL * S_in, OCP_DBL * kr_out, OCP_DBL * pc_out, OCP_DBL * dkrdS, OCP_DBL * dPcjdS, const OCP_DBL & MySurTen, OCP_DBL & MyFk, OCP_DBL & MyFp) override virtual
Implements FlowUnit.
Definition at line 218 of file FlowUnit.cpp.
{
    OCP_DBL Sg = S_in[1];
    OCP_DBL Sw = S_in[2];
    // three phase black oil model using stone 2
    SWOF.Eval_All(0, Sw, data, cdata);
    OCP_DBL krw = data[1];
    OCP_DBL dKrwdSw = cdata[1];
    OCP_DBL krow = data[2];
    OCP_DBL dKrowdSw = cdata[2];
    OCP_DBL Pcwo = -data[3];
    OCP_DBL dPcwdSw = -cdata[3];
    SGOF.Eval_All(0, Sg, data, cdata);
    OCP_DBL krg = data[1];
    OCP_DBL dKrgdSg = cdata[1];
    OCP_DBL krog = data[2];
    OCP_DBL dKrogdSg = cdata[2];
    OCP_DBL Pcgo = data[3];
    OCP_DBL dPcgdSg = cdata[3];
    OCP_DBL dKrodSg{ 0 }, dKrodSw{ 0 }, kro{ 0 };
    kro = CalKro_Stone2Der(krow, krog, krw, krg, dKrwdSw, dKrowdSw, dKrgdSg, dKrogdSg,
        dKrodSw, dKrodSg);
    // if (kro < 0) {
    //    cout << S_in[0] << "   " << S_in[1] << "   " << S_in[2] << endl;
    //    kro = 0;
    //}
    // kro = CalKro_DefaultDer(Sg, Sw, krog, krow, dKrogdSg, dKrowdSw, dKrodSg,
    // dKrodSw);
    kr_out[0] = kro;
    kr_out[1] = krg;
    kr_out[2] = krw;
    pc_out[0] = 0;
    pc_out[1] = Pcgo;
    pc_out[2] = Pcwo;
    dkrdS[0] = 0;
    dkrdS[1] = dKrodSg;
    dkrdS[2] = dKrodSw;
    dkrdS[3] = 0;
    dkrdS[4] = dKrgdSg;
    dkrdS[5] = 0;
    dkrdS[6] = 0;
    dkrdS[7] = 0;
    dkrdS[8] = dKrwdSw;
    dPcjdS[0] = 0;
    dPcjdS[1] = 0;
    dPcjdS[2] = 0;
    dPcjdS[3] = 0;
    dPcjdS[4] = dPcgdSg;
    dPcjdS[5] = 0;
    dPcjdS[6] = 0;
    dPcjdS[7] = 0;
    dPcjdS[8] = dPcwdSw;
}
Generate_SWPCWG()
void FlowUnit_ODGW01::Generate_SWPCWG ()
Definition at line 320 of file FlowUnit.cpp.
{
    if (SGOF.IsEmpty()) OCP_ABORT("SGOF is missing!");
    if (SWOF.IsEmpty()) OCP_ABORT("SWOF is missing!");
    std::vector<OCP_DBL> Sw(SWOF.GetCol(0));
    std::vector<OCP_DBL> Pcow(SWOF.GetCol(3));
    USI                  n = Sw.size();
    for (USI i = 0; i < n; i++) {
        OCP_DBL Pcgo = SGOF.Eval(0, 1 - Sw[i], 3);
        Pcow[i] += Pcgo; // Pcgw
    }
    SWPCGW.PushCol(Sw);
    SWPCGW.PushCol(Pcow);
    SWPCGW.SetRowCol();
}
GetPcgoBySg()
OCP_DBL FlowUnit_ODGW01::GetPcgoBySg (const OCP_DBL & sg) inline override virtual
Pcgo = Pg - Po.
Implements FlowUnit.
Definition at line 212 of file FlowUnit.hpp.
{
        return SGOF.Eval(0, sg, 3);
    }
References OCPTable::Eval(), and SGOF.
GetPcowBySw()
OCP_DBL FlowUnit_ODGW01::GetPcowBySw (const OCP_DBL & sw) inline override virtual
Pcow = Po - Pw.
Implements FlowUnit.
Definition at line 206 of file FlowUnit.hpp.
{
        return SWOF.Eval(0, sw, 3);
    }
References OCPTable::Eval(), and SWOF.
GetSgByPcgo()
OCP_DBL FlowUnit_ODGW01::GetSgByPcgo (const OCP_DBL & pcgo) inline override virtual
Implements FlowUnit.
Definition at line 215 of file FlowUnit.hpp.
{
        return SGOF.Eval(3, pcgo, 0);
    }
GetSwByPcgw()
OCP_DBL FlowUnit_ODGW01::GetSwByPcgw (const OCP_DBL & pcgw) inline override virtual
Pcgw = Pg - Pw.
Implements FlowUnit.
Definition at line 218 of file FlowUnit.hpp.
{
        return SWPCGW.Eval_Inv(1, pcgw, 0);
    }
References OCPTable::Eval_Inv(), and SWPCGW.
GetSwByPcow()
OCP_DBL FlowUnit_ODGW01::GetSwByPcow (const OCP_DBL & pcow) inline override virtual
Implements FlowUnit.
Definition at line 209 of file FlowUnit.hpp.
{
        return SWOF.Eval_Inv(3, pcow, 0);
    }
Member Data Documentation
cdata
vector<OCP_DBL> FlowUnit_ODGW01::cdata protected
container used to store the results of slopes of interpolation.
Definition at line 230 of file FlowUnit.hpp.
data
vector<OCP_DBL> FlowUnit_ODGW01::data protected
container used to store the results of values of interpolation.
Definition at line 228 of file FlowUnit.hpp.
SGOF
OCPTable FlowUnit_ODGW01::SGOF protected
saturation table about gas and oil.
Definition at line 225 of file FlowUnit.hpp.
SWOF
OCPTable FlowUnit_ODGW01::SWOF protected
saturation table about water and oil.
Definition at line 226 of file FlowUnit.hpp.
SWPCGW
OCPTable FlowUnit_ODGW01::SWPCGW protected
auxiliary table: saturation of water vs. capillary pressure between water and gas.
Definition at line 231 of file FlowUnit.hpp.
The documentation for this class was generated from the following files:
FlowUnit.hpp
FlowUnit.cpp