OpenCAEPoro: OCP_AIMc Class Reference
OCP_AIMc Class Reference
Public Member Functions
void Setup (Reservoir &rs, LinearSystem &myLS, const OCPControl &ctrl)
Setup AIMc.
void InitReservoir (Reservoir &rs) const
Init.
void Prepare (Reservoir &rs, OCP_DBL &dt)
Prepare for Assembling matrix.
void AssembleMat (LinearSystem &myLS, const Reservoir &rs, const OCP_DBL &dt) const
Assemble Matrix.
void SolveLinearSystem (LinearSystem &myLS, Reservoir &rs, OCPControl &ctrl)
Solve the linear system.
bool UpdateProperty (Reservoir &rs, OCPControl &ctrl)
Update properties of fluids.
bool FinishNR (Reservoir &rs, OCPControl &ctrl)
Finish a Newton-Raphson iteration.
Public Member Functions inherited from OCP_FIM
void Setup (Reservoir &rs, LinearSystem &myLS, const OCPControl &ctrl)
Setup FIM.
void InitReservoir (Reservoir &rs) const
Init.
void Prepare (Reservoir &rs, OCP_DBL &dt)
Prepare for Assembling matrix.
void AssembleMat (LinearSystem &myLS, const Reservoir &rs, const OCP_DBL &dt) const
Assemble Matrix.
void SolveLinearSystem (LinearSystem &myLS, Reservoir &rs, OCPControl &ctrl) const
Solve the linear system.
bool UpdateProperty (Reservoir &rs, OCPControl &ctrl)
Update properties of fluids.
bool FinishNR (Reservoir &rs, OCPControl &ctrl)
Finish a Newton-Raphson iteration.
void FinishStep (Reservoir &rs, OCPControl &ctrl) const
Finish a time step.
Additional Inherited Members
Protected Attributes inherited from OCP_FIM
ResFIM resFIM
Resiual for FIM.
Detailed Description
Definition at line 98 of file OCPFluidMethod.hpp.
Member Function Documentation
AssembleMat()
void OCP_AIMc::AssembleMat (LinearSystem & myLS, const Reservoir & rs, const OCP_DBL & dt) const
Assemble Matrix.
Definition at line 548 of file OCPFluidMethod.cpp.
{
    rs.AssembleMatAIMc(myLS, dt);
    myLS.AssembleRhs(resFIM.res);
}
References Reservoir::AssembleMatAIMc(), LinearSystem::AssembleRhs(), and OCP_FIM::resFIM.
FinishNR()
bool OCP_AIMc::FinishNR (Reservoir & rs, OCPControl & ctrl)
Finish a Newton-Raphson iteration.
Definition at line 613 of file OCPFluidMethod.cpp.
{
    const OCP_DBL NRdPmax = rs.GetNRdPmax();
    const OCP_DBL NRdNmax = rs.GetNRdNmax();
    const OCP_DBL NRdSmax = rs.GetNRdSmaxP();
//#ifdef _DEBUG
    cout << "### DEBUG: Residuals = " << setprecision(3) << scientific << resFIM.maxRelRes0_v << "  "
       << resFIM.maxRelRes_v << "  " << resFIM.maxRelRes_mol << "  " << NRdPmax
       << "  " << NRdSmax << endl;
    //for (OCP_USI n = 0; n < resFIM.res.size(); n++) {
    //    cout << resFIM.res[n] << endl;
    //}
//#endif
    if (ctrl.iterNR > ctrl.ctrlNR.maxNRiter) {
        ctrl.current_dt *= ctrl.ctrlTime.cutFacNR;
        rs.ResetFIM(false);
        rs.CalResAIMc(resFIM, ctrl.current_dt);
        resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
        ctrl.ResetIterNRLS();
        cout << "### WARNING: NR not fully converged! Cut time stepsize and repeat!\n";
        return false;
    }
    if (resFIM.maxRelRes_v <= resFIM.maxRelRes0_v * ctrl.ctrlNR.NRtol ||
        resFIM.maxRelRes_v <= ctrl.ctrlNR.NRtol ||
        resFIM.maxRelRes_mol <= ctrl.ctrlNR.NRtol ||
        (NRdPmax <= ctrl.ctrlNR.NRdPmin && NRdSmax <= ctrl.ctrlNR.NRdSmin)) {
        OCP_INT flagCheck = rs.CheckP(false, true);
#if DEBUG
        if (flagCheck > 0) {
            cout << ">> Switch well constraint: Case " << flagCheck << endl;
        }
#endif
        switch (flagCheck) {
        case 1:
            ctrl.current_dt *= ctrl.ctrlTime.cutFacNR;
            rs.ResetFIM(true);
            rs.CalResAIMc(resFIM, ctrl.current_dt);
            resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
            ctrl.ResetIterNRLS();
            return false;
        case 2:
            // ctrl.current_dt /= 1;
            rs.ResetFIM(true);
            rs.CalResAIMc(resFIM, ctrl.current_dt);
            resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
            ctrl.ResetIterNRLS();
            return false;
        default:
            // Update IMPEC Bulk Properties
            rs.CalFlashAIMc01();
            rs.CalKrPcAIMc();
            return true;
            break;
        }
    }
    else {
        //rs.CalCFL(ctrl.current_dt);
        //rs.SetupWellBulk();
        //rs.SetupFIMBulk(true);
        //rs.CalFlashDerivAIMc();
        //rs.CalKrPcDerivAIMc();
        //rs.bulk.ShowFIMBulk(false);
        return false;
    }
}
References Reservoir::CalResAIMc(), Reservoir::CheckP(), ControlTime::cutFacNR, Reservoir::GetNRdNmax(), Reservoir::GetNRdPmax(), Reservoir::GetNRdSmaxP(), ControlNR::maxNRiter, ControlNR::NRdPmin, ControlNR::NRdSmin, ControlNR::NRtol, Reservoir::ResetFIM(), OCPControl::ResetIterNRLS(), and OCP_FIM::resFIM.
InitReservoir()
void OCP_AIMc::InitReservoir (Reservoir & rs) const
Init.
Definition at line 517 of file OCPFluidMethod.cpp.
{
    rs.InitAIMc();
}
Prepare()
void OCP_AIMc::Prepare (Reservoir & rs, OCP_DBL & dt)
Prepare for Assembling matrix.
Definition at line 522 of file OCPFluidMethod.cpp.
{
    rs.PrepareWell();
    rs.CalWellFlux();
    rs.CalResAIMc(resFIM, dt);
    resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
    // Set FIM Bulk
    rs.CalCFL(dt);
    rs.SetupWellBulk();
    rs.SetupFIMBulk();
    //rs.bulk.FIMBulk.resize(rs.bulk.numBulk, 0);
    //for (OCP_USI n = 0; n < rs.bulk.numBulk; n++) {
    //    rs.bulk.FIMBulk[n] = n;
    //    rs.bulk.map_Bulk2FIM[n] = n;
    //}
    //rs.bulk.numFIMBulk = rs.bulk.numBulk;
    // Calculate FIM Bulk properties
    rs.CalFlashDerivAIMc();
    rs.CalKrPcDerivAIMc();
    // rs.bulk.CheckDiff();
    rs.UpdateLastStepFIM();
    rs.bulk.ShowFIMBulk(false);
}
References Reservoir::CalCFL(), Reservoir::CalFlashDerivAIMc(), Reservoir::CalKrPcDerivAIMc(), Reservoir::CalResAIMc(), Reservoir::CalWellFlux(), Reservoir::PrepareWell(), OCP_FIM::resFIM, Reservoir::SetupFIMBulk(), and Reservoir::UpdateLastStepFIM().
Setup()
void OCP_AIMc::Setup (Reservoir & rs, LinearSystem & myLS, const OCPControl & ctrl)
Setup AIMc.
Definition at line 503 of file OCPFluidMethod.cpp.
{
    // Allocate Bulk and BulkConn Memory
    rs.AllocateAuxAIMc();
    // Allocate memory for internal matrix structure
    rs.AllocateMatFIM(myLS);
    // Allocate memory for resiual of FIM
    OCP_USI num = (rs.GetBulkNum() + rs.GetWellNum()) * (rs.GetComNum() + 1);
    resFIM.res.resize(num);
    myLS.SetupLinearSolver(VECTORFASP, ctrl.GetWorkDir(), ctrl.GetLsFile());
}
References Reservoir::AllocateAuxAIMc(), Reservoir::AllocateMatFIM(), Reservoir::GetBulkNum(), Reservoir::GetComNum(), OCPControl::GetLsFile(), Reservoir::GetWellNum(), OCPControl::GetWorkDir(), OCP_FIM::resFIM, LinearSystem::SetupLinearSolver(), and VECTORFASP.
SolveLinearSystem()
void OCP_AIMc::SolveLinearSystem (LinearSystem & myLS, Reservoir & rs, OCPControl & ctrl)
Solve the linear system.
Definition at line 554 of file OCPFluidMethod.cpp.
{
#ifdef _DEBUG
    myLS.CheckEquation();
#endif // DEBUG
    myLS.AssembleMatLinearSolver();
    GetWallTime Timer;
    Timer.Start();
    int status = myLS.Solve();
    if (status < 0) {
        status = myLS.GetNumIters();
    }
    // cout << "LS step = " << status << endl;
#ifdef DEBUG
    myLS.OutputLinearSystem("testA.out", "testb.out");
    myLS.OutputSolution("testx.out");
    myLS.CheckSolution();
#endif // DEBUG
    ctrl.UpdateTimeLS(Timer.Stop() / 1000);
    ctrl.UpdateIterLS(status);
    ctrl.UpdateIterNR();
    rs.GetSolutionAIMc(myLS.GetSolution(), ctrl.ctrlNR.NRdPmax, ctrl.ctrlNR.NRdSmax);
    // rs.GetSolution01FIM(myLS.GetSolution());
    // rs.PrintSolFIM(ctrl.workDir + "testPNi.out");
    myLS.ClearData();
}
References LinearSystem::AssembleMatLinearSolver(), LinearSystem::CheckEquation(), LinearSystem::CheckSolution(), LinearSystem::ClearData(), LinearSystem::GetNumIters(), LinearSystem::GetSolution(), ControlNR::NRdPmax, ControlNR::NRdSmax, LinearSystem::OutputLinearSystem(), LinearSystem::OutputSolution(), LinearSystem::Solve(), GetWallTime::Start(), GetWallTime::Stop(), OCPControl::UpdateIterLS(), OCPControl::UpdateIterNR(), and OCPControl::UpdateTimeLS().
UpdateProperty()
bool OCP_AIMc::UpdateProperty (Reservoir & rs, OCPControl & ctrl)
Update properties of fluids.
Definition at line 586 of file OCPFluidMethod.cpp.
{
    OCP_DBL& dt = ctrl.current_dt;
    // Second check: Ni check and bulk Pressure check
    if (!rs.CheckNi() || rs.CheckP(true, false) != 0) {
        dt *= ctrl.ctrlTime.cutFacNR;
        rs.ResetFIM(false);
        rs.CalResAIMc(resFIM, dt);
        resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
        cout << "Cut time stepsize and repeat!\n";
        return false;
    }
    rs.CalFlashDerivAIMc();
    rs.CalKrPcDerivAIMc();
    rs.CalFlashAIMc();
    // Important, Pj must be updated with current and last Pc for IMPEC Bulk
    rs.UpdatePj();
    rs.CalVpore();
    rs.CalWellTrans();
    rs.CalWellFlux();
    rs.CalResAIMc(resFIM, dt);
    return true;
}
References Reservoir::CalFlashDerivAIMc(), Reservoir::CalKrPcDerivAIMc(), Reservoir::CalResAIMc(), Reservoir::CalVpore(), Reservoir::CalWellFlux(), Reservoir::CalWellTrans(), Reservoir::CheckNi(), Reservoir::CheckP(), ControlTime::cutFacNR, Reservoir::ResetFIM(), and OCP_FIM::resFIM.
The documentation for this class was generated from the following files:
OCPFluidMethod.hpp
OCPFluidMethod.cpp