OpenCAEPoro: OCP_FIMn Class Reference
OCP_FIMn Class Reference
Public Member Functions
void AssembleMat (LinearSystem &myLS, const Reservoir &rs, const OCP_DBL &dt) const
Assemble Matrix.
void SolveLinearSystem (LinearSystem &myLS, Reservoir &rs, OCPControl &ctrl) const
Solve the linear system.
bool UpdateProperty (Reservoir &rs, OCPControl &ctrl)
Update properties of fluids.
Public Member Functions inherited from OCP_FIM
void Setup (Reservoir &rs, LinearSystem &myLS, const OCPControl &ctrl)
Setup FIM.
void InitReservoir (Reservoir &rs) const
Init.
void Prepare (Reservoir &rs, OCP_DBL &dt)
Prepare for Assembling matrix.
void AssembleMat (LinearSystem &myLS, const Reservoir &rs, const OCP_DBL &dt) const
Assemble Matrix.
void SolveLinearSystem (LinearSystem &myLS, Reservoir &rs, OCPControl &ctrl) const
Solve the linear system.
bool UpdateProperty (Reservoir &rs, OCPControl &ctrl)
Update properties of fluids.
bool FinishNR (Reservoir &rs, OCPControl &ctrl)
Finish a Newton-Raphson iteration.
void FinishStep (Reservoir &rs, OCPControl &ctrl) const
Finish a time step.
Additional Inherited Members
Protected Attributes inherited from OCP_FIM
ResFIM resFIM
Resiual for FIM.
Detailed Description
Definition at line 84 of file OCPFluidMethod.hpp.
Member Function Documentation
AssembleMat()
void OCP_FIMn::AssembleMat (LinearSystem & myLS, const Reservoir & rs, const OCP_DBL & dt) const
Assemble Matrix.
Definition at line 432 of file OCPFluidMethod.cpp.
{
    rs.AssembleMatFIM_n(myLS, dt);
    myLS.AssembleRhs(resFIM.res);
}
References LinearSystem::AssembleRhs(), and OCP_FIM::resFIM.
SolveLinearSystem()
void OCP_FIMn::SolveLinearSystem (LinearSystem & myLS, Reservoir & rs, OCPControl & ctrl) const
Solve the linear system.
Definition at line 439 of file OCPFluidMethod.cpp.
{
#ifdef _DEBUG
    myLS.CheckEquation();
#endif // DEBUG
    myLS.AssembleMatLinearSolver();
    GetWallTime Timer;
    Timer.Start();
    int status = myLS.Solve();
    if (status < 0) {
        status = myLS.GetNumIters();
    }
    // cout << "LS step = " << status << endl;
#ifdef DEBUG
    myLS.OutputLinearSystem("testA.out", "testb.out");
    myLS.OutputSolution("testx.out");
    myLS.CheckSolution();
#endif // DEBUG
    ctrl.UpdateTimeLS(Timer.Stop() / 1000);
    ctrl.UpdateIterLS(status);
    ctrl.UpdateIterNR();
    rs.GetSolutionFIM_n(myLS.GetSolution(), ctrl.ctrlNR.NRdPmax, ctrl.ctrlNR.NRdSmax);
    // rs.GetSolution01FIM(myLS.GetSolution());
    // rs.PrintSolFIM(ctrl.workDir + "testPNi.out");
    myLS.ClearData();
}
References LinearSystem::AssembleMatLinearSolver(), LinearSystem::CheckEquation(), LinearSystem::CheckSolution(), LinearSystem::ClearData(), LinearSystem::GetNumIters(), LinearSystem::GetSolution(), ControlNR::NRdPmax, ControlNR::NRdSmax, LinearSystem::OutputLinearSystem(), LinearSystem::OutputSolution(), LinearSystem::Solve(), GetWallTime::Start(), GetWallTime::Stop(), OCPControl::UpdateIterLS(), OCPControl::UpdateIterNR(), and OCPControl::UpdateTimeLS().
UpdateProperty()
bool OCP_FIMn::UpdateProperty (Reservoir & rs, OCPControl & ctrl)
Update properties of fluids.
Definition at line 472 of file OCPFluidMethod.cpp.
{
    OCP_DBL& dt = ctrl.current_dt;
    // Second check: Ni check and bulk Pressure check
    if (!rs.CheckNi() || rs.CheckP(true, false) != 0) {
        dt *= ctrl.ctrlTime.cutFacNR;
        rs.ResetFIM(false);
        rs.CalResFIM(resFIM, dt);
        resFIM.maxRelRes0_v = resFIM.maxRelRes_v;
        cout << "Cut time stepsize and repeat!\n";
        return false;
    }
    // Update reservoir properties
    rs.CalFlashDerivFIM_n();
    rs.CalKrPcDerivFIM();
    rs.CalVpore();
    rs.CalWellTrans();
    rs.CalWellFlux();
    rs.CalResFIM(resFIM, dt);
    return true;
}
References Reservoir::CalKrPcDerivFIM(), Reservoir::CalResFIM(), Reservoir::CalVpore(), Reservoir::CalWellFlux(), Reservoir::CalWellTrans(), Reservoir::CheckNi(), Reservoir::CheckP(), ControlTime::cutFacNR, Reservoir::ResetFIM(), and OCP_FIM::resFIM.
The documentation for this class was generated from the following files:
OCPFluidMethod.hpp
OCPFluidMethod.cpp