OpenCAEPoro: OCP_IMPEC Class Reference
OCP_IMPEC Class Reference
OCP_IMPEC is IMPEC (implict pressure explict saturation) method.
#include <OCPFluidMethod.hpp>
Public Member Functions
void Setup (Reservoir &rs, LinearSystem &myLS, const OCPControl &ctrl)
Setup IMPEC.
void InitReservoir (Reservoir &rs) const
Init.
void Prepare (Reservoir &rs, OCP_DBL &dt)
Prepare for Assembling matrix.
void SolveLinearSystem (LinearSystem &myLS, Reservoir &rs, OCPControl &ctrl)
Solve the linear system.
bool UpdateProperty (Reservoir &rs, OCPControl &ctrl)
Update properties of fluids.
bool UpdateProperty01 (Reservoir &rs, OCPControl &ctrl)
bool FinishNR (const Reservoir &rs)
Determine if NR iteration finishes.
bool FinishNR01 (Reservoir &rs, OCPControl &ctrl)
void FinishStep (Reservoir &rs, OCPControl &ctrl)
Detailed Description
OCP_IMPEC is IMPEC (implict pressure explict saturation) method.
Definition at line 22 of file OCPFluidMethod.hpp.
Member Function Documentation
FinishNR()
bool OCP_IMPEC::FinishNR (const Reservoir & rs)
Determine if NR iteration finishes.
Definition at line 133 of file OCPFluidMethod.cpp.
{
    //for (USI j = 0; j < rs.bulk.numPhase; j++)
    //    cout << rs.bulk.totalPhaseNum[j] << "   ";
    //cout << endl;
    return true;
}
FinishNR01()
bool OCP_IMPEC::FinishNR01 (Reservoir & rs, OCPControl & ctrl)
Definition at line 191 of file OCPFluidMethod.cpp.
{
    OCP_DBL& dt = ctrl.current_dt;
    // fouth check: Volume error check
    if (!rs.CheckVe(0.01)) {
        // continue NR
        rs.bulk.ResetNi();
        rs.allWells.CalTrans(rs.bulk);
        rs.allWells.CalFlux(rs.bulk);
        rs.allWells.CalProdWeight(rs.bulk);
        rs.allWells.CaldG(rs.bulk);
        return false;
    }
    return true;
}
FinishStep()
void OCP_IMPEC::FinishStep (Reservoir & rs, OCPControl & ctrl)
Definition at line 207 of file OCPFluidMethod.cpp.
{
    rs.CalIPRT(ctrl.GetCurDt());
    rs.CalMaxChange();
    rs.UpdateLastStepIMPEC();
    ctrl.CalNextTstepIMPEC(rs);
    ctrl.UpdateIters();
}
InitReservoir()
void OCP_IMPEC::InitReservoir (Reservoir & rs) const
Init.
Definition at line 29 of file OCPFluidMethod.cpp.
{
    rs.InitIMPEC();
}
References Reservoir::InitIMPEC().
Prepare()
void OCP_IMPEC::Prepare (Reservoir & rs, OCP_DBL & dt)
Prepare for Assembling matrix.
Definition at line 34 of file OCPFluidMethod.cpp.
{
    rs.PrepareWell();
    OCP_DBL cfl = rs.CalCFL(dt);
    if (cfl > 1) dt /= (cfl + 1);
}
References Reservoir::CalCFL(), and Reservoir::PrepareWell().
Setup()
void OCP_IMPEC::Setup (Reservoir & rs, LinearSystem & myLS, const OCPControl & ctrl)
Setup IMPEC.
Definition at line 18 of file OCPFluidMethod.cpp.
{
    // Allocate Memory of auxiliary variables for IMPEC
    rs.AllocateAuxIMPEC();
    // Allocate Memory of Matrix for IMPEC
    rs.AllocateMatIMPEC(myLS);
    myLS.SetupLinearSolver(SCALARFASP, ctrl.GetWorkDir(), ctrl.GetLsFile());
}
References Reservoir::AllocateAuxIMPEC(), Reservoir::AllocateMatIMPEC(), OCPControl::GetLsFile(), OCPControl::GetWorkDir(), SCALARFASP, and LinearSystem::SetupLinearSolver().
SolveLinearSystem()
void OCP_IMPEC::SolveLinearSystem (LinearSystem & myLS, Reservoir & rs, OCPControl & ctrl)
Solve the linear system.
Definition at line 41 of file OCPFluidMethod.cpp.
{
#ifdef _DEBUG
    myLS.CheckEquation();
#endif // DEBUG
    myLS.AssembleMatLinearSolver();
#ifdef _DEBUG
    myLS.OutputLinearSystem("testA.out", "testb.out");
#endif // _DEBUG
    GetWallTime Timer;
    Timer.Start();
    int status = myLS.Solve();
    if (status < 0) {
        status = myLS.GetNumIters();
    }
    ctrl.UpdateTimeLS(Timer.Stop() / 1000);
    ctrl.UpdateIterLS(status);
    ctrl.UpdateIterNR();
#ifdef DEBUG
    myLS.OutputSolution("testx.out");
#endif // DEBUG
    rs.GetSolutionIMPEC(myLS.GetSolution());
    myLS.ClearData();
}
References LinearSystem::AssembleMatLinearSolver(), LinearSystem::CheckEquation(), LinearSystem::ClearData(), LinearSystem::GetNumIters(), LinearSystem::GetSolution(), Reservoir::GetSolutionIMPEC(), LinearSystem::OutputLinearSystem(), LinearSystem::OutputSolution(), LinearSystem::Solve(), GetWallTime::Start(), GetWallTime::Stop(), OCPControl::UpdateIterLS(), OCPControl::UpdateIterNR(), and OCPControl::UpdateTimeLS().
UpdateProperty()
bool OCP_IMPEC::UpdateProperty (Reservoir & rs, OCPControl & ctrl)
Update properties of fluids.
Definition at line 72 of file OCPFluidMethod.cpp.
{
    OCP_DBL& dt = ctrl.current_dt;
    // first check : Pressure check
    OCP_INT flagCheck = rs.CheckP(true, true);
    switch (flagCheck) {
        case 1:
            // Negative Bulk P, well P, or Perforation P
            dt /= 2;
            return false;
        case 2:
            // Switch Well opt Mode, or close the crossflow perforation
            dt /= 1;
            return false;
        default:
            // All right
            break;
    }
    // Calculate Flux between bulks and between bulks and wells
    rs.CalFLuxIMPEC();
    // second check : CFL check
    OCP_DBL cfl = rs.CalCFL(dt);
    if (cfl > 1) {
        dt /= 2;
        rs.ResetVal01IMPEC();
        cout << "CFL is too big" << endl;
        return false;
    }
    rs.MassConseveIMPEC(dt);
    // third check: Ni check
    if (!rs.CheckNi()) {
        dt /= 2;
        rs.ResetVal02IMPEC();
        cout << "Negative Ni occurs\n";
        return false;
    }
    rs.CalVpore();
    rs.CalFlashIMPEC();
    // fouth check: Volume error check
    if (!rs.CheckVe(0.01)) {
        // cout << ctrl.GetCurTime() << "Days" << "=======" << endl;
        dt /= 2;
        rs.ResetVal03IMPEC();
        return false;
    }
    rs.CalKrPc();
    rs.CalConnFluxIMPEC();
    // rs.allWells.ShowWellStatus(rs.bulk);
    return true;
}
References Reservoir::CalCFL(), Reservoir::CalConnFluxIMPEC(), Reservoir::CalFlashIMPEC(), Reservoir::CalFLuxIMPEC(), Reservoir::CalKrPc(), Reservoir::CalVpore(), Reservoir::CheckNi(), Reservoir::CheckP(), Reservoir::CheckVe(), Reservoir::MassConseveIMPEC(), Reservoir::ResetVal01IMPEC(), Reservoir::ResetVal02IMPEC(), and Reservoir::ResetVal03IMPEC().
UpdateProperty01()
bool OCP_IMPEC::UpdateProperty01 (Reservoir & rs, OCPControl & ctrl)
Definition at line 142 of file OCPFluidMethod.cpp.
{
    OCP_DBL& dt = ctrl.current_dt;
    // first check : Pressure check
    OCP_INT flagCheck = rs.CheckP();
    switch (flagCheck) {
    case 1:
        // Negative Bulk P, well P, or Perforation P
        dt /= 2;
        return false;
    case 2:
        // Switch Well opt Mode, or close the crossflow perforation
        dt /= 1;
        return false;
    default:
        // All right
        break;
    }
    rs.CalFLuxIMPEC();
    // second check : CFL check
    OCP_DBL cfl = rs.CalCFL(dt);
    if (cfl > 1) {
        dt /= 2;
        rs.ResetVal01IMPEC();
        cout << "CFL is too big" << endl;
        return false;
    }
    rs.MassConseveIMPEC(dt);
    // third check: Ni check
    if (!rs.CheckNi()) {
        dt /= 2;
        rs.ResetVal02IMPEC();
        cout << "Negative Ni occurs\n";
        return false;
    }
    rs.CalVpore();
    rs.CalFlashIMPEC();
    rs.CalKrPc();
    rs.CalConnFluxIMPEC();
    return true;
}
The documentation for this class was generated from the following files:
OCPFluidMethod.hpp
OCPFluidMethod.cpp