OpenCAEPoro: BOMixture Class Reference
BOMixture Class Reference
BOMixture is inherited class of Mixture, it's used for black oil model.
#include <MixtureBO.hpp>
Public Member Functions
BOMixture (const ParamReservoir &rs_param, const USI &PVTmode, const USI &i)
bool IsEmpty_PVDG () const override
judge if table PVDG is empty.
void Flash_Sj (const OCP_DBL &Pin, const OCP_DBL &Pbbin, const OCP_DBL &Tin, const OCP_DBL *Sjin, const OCP_DBL &Vpore, const OCP_DBL *Ziin) override
void BOFlash_Sj_W (const OCP_DBL &Pin, const OCP_DBL *Sjin, const OCP_DBL &Vpore)
void BOFlash_Sj_OW (const OCP_DBL &Pin, const OCP_DBL *Sjin, const OCP_DBL &Vpore)
void BOFlash_Sj_ODGW (const OCP_DBL &Pin, const OCP_DBL &Pbbin, const OCP_DBL *Sjin, const OCP_DBL &Vpore)
void Flash_Ni (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin) override
void BOFlash_Ni_W (const OCP_DBL &Pin, const OCP_DBL *Niin)
void BOFlash_Ni_OW (const OCP_DBL &Pin, const OCP_DBL *Niin)
void BOFlash_Ni_ODGW (const OCP_DBL &Pin, const OCP_DBL *Niin)
void Flash_Ni_Deriv (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Niin) override
Flash calculation with moles of components and Calculate the derivative.
void BOFlash_Ni_W_Deriv (const OCP_DBL &Pin, const OCP_DBL *Niin)
void BOFlash_Ni_OW_Deriv (const OCP_DBL &Pin, const OCP_DBL *Niin)
void BOFlash_Ni_ODGW_Deriv (const OCP_DBL &Pin, const OCP_DBL *Niin)
OCP_DBL XiPhase (const OCP_DBL &Pin, const OCP_DBL &T, const OCP_DBL *Ziin) override
OCP_DBL XiPhase_OW (const OCP_DBL &Pin, const OCP_DBL *Ziin)
OCP_DBL XiPhase_ODGW (const OCP_DBL &Pin, const OCP_DBL *Ziin)
OCP_DBL RhoPhase (const OCP_DBL &Pin, const OCP_DBL &T, const OCP_DBL *Ziin) override
return mass density of phase.
OCP_DBL RhoPhase_OW (const OCP_DBL &Pin, const OCP_DBL *Ziin)
OCP_DBL RhoPhase_ODGW (const OCP_DBL &Pin, const OCP_DBL *Ziin)
OCP_DBL GammaPhaseO (const OCP_DBL &Pin, const OCP_DBL &Pbbin) override
return gamma of oil phase, gamma equals to mass density times gravity factor.
OCP_DBL GammaPhaseG (const OCP_DBL &Pin) override
return gamma of gas phase, gamma equals to mass density times gravity factor.
OCP_DBL GammaPhaseW (const OCP_DBL &Pin) override
return gamma of water phase, gamma equals to mass density times gravity factor.
OCP_DBL GammaPhaseO_OW (const OCP_DBL &Pin)
OCP_DBL GammaPhaseO_ODGW (const OCP_DBL &Pin, const OCP_DBL &Pbbin)
OCP_DBL GammaPhaseOG (const OCP_DBL &Pin, const OCP_DBL &Tin, const OCP_DBL *Ziin) override
Public Member Functions inherited from Mixture
USI GetType () const
return type of mixture.
void CheckNi (const OCP_DBL *Ni)
Additional Inherited Members
Protected Attributes inherited from Mixture
USI mixtureType
USI numPhase
num of phases.
USI numCom
num of components.
OCP_DBL P
pressure when flash calculation.
OCP_DBL T
temperature when flash calculation.
vector< OCP_DBL > Ni
moles of component: numCom
vector< bool > phaseExist
existence of phase: numPhase
vector< OCP_DBL > S
saturation of phase: numPhase
vector< OCP_DBL > rho
mass density of phase: numPhase
vector< OCP_DBL > xi
molar density of phase: numPhase
vector< OCP_DBL > cij
vector< OCP_DBL > mu
viscosity of phase: numPhase
vector< OCP_DBL > v
volume of phase: numPhase;
OCP_DBL vf
volume of total fluids.
OCP_DBL Nt
Total moles of Components.
OCP_DBL vfp
Derivatives.
vector< OCP_DBL > vfi
vector< OCP_DBL > muP
vector< OCP_DBL > xiP
vector< OCP_DBL > rhoP
vector< OCP_DBL > muC
vector< OCP_DBL > xiC
vector< OCP_DBL > rhoC
vector< OCP_DBL > dSec_dPri
Detailed Description
BOMixture is inherited class of Mixture, it's used for black oil model.
Definition at line 23 of file MixtureBO.hpp.
Constructor & Destructor Documentation
BOMixture()
BOMixture::BOMixture (const ParamReservoir & rs_param, const USI & PVTmode, const USI & i)
Definition at line 14 of file MixtureBO.cpp.
{
    mixtureType = BLKOIL;
    mode        = PVTmode;
    numPhase    = rs_param.numPhase;
    numCom      = rs_param.numCom;
    Ni.resize(numCom);
    phaseExist.resize(numPhase);
    v.resize(numPhase);
    S.resize(numPhase);
    xi.resize(numPhase);
    cij.resize(numPhase * numCom);
    rho.resize(numPhase);
    mu.resize(numPhase);
    vfi.resize(numCom);
    // Derivatives for FIM
    rhoP.resize(numPhase);
    xiP.resize(numPhase);
    muP.resize(numPhase);
    rhoC.resize(numPhase * numCom);
    xiC.resize(numPhase * numCom);
    muC.resize(numPhase * numCom);
    dSec_dPri.resize((numCom + 1) * (numPhase + numPhase * numCom));
    if (rs_param.density.activity) {
        std_RhoO = rs_param.density.data[0];
        std_RhoW = rs_param.density.data[1];
        std_RhoG = rs_param.density.data[2];
    } else {
        std_RhoO = (141.5 * RHOW_STD) / (rs_param.gravity.data[0] + 131.5);
        std_RhoW = RHOW_STD * rs_param.gravity.data[1];
        std_RhoG = RHOAIR_STD * rs_param.gravity.data[2];
    }
    std_GammaO = GRAVITY_FACTOR * std_RhoO;
    std_GammaG = GRAVITY_FACTOR * std_RhoG;
    std_GammaW = GRAVITY_FACTOR * std_RhoW;
    if (rs_param.PVTW_T.data.size() != 0) {
        PVTW.Setup(rs_param.PVTW_T.data[i]);
        len = max(len, PVTW.GetCol());
    }
    if (rs_param.PVCO_T.data.size() != 0) {
        PVCO.Setup(rs_param.PVCO_T.data[i]);
        len = max(len, PVCO.GetCol());
    }
    if (rs_param.PVDO_T.data.size() != 0) {
        PVDO.Setup(rs_param.PVDO_T.data[i]);
        len = max(len, PVDO.GetCol());
    }
    if (rs_param.PVDG_T.data.size() != 0) {
        PVDG.Setup(rs_param.PVDG_T.data[i]);
        len = max(len, PVDG.GetCol());
    }
    data.resize(len, 0);
    cdata.resize(len, 0);
}
Member Function Documentation
BOFlash_Ni_ODGW()
void BOMixture::BOFlash_Ni_ODGW (const OCP_DBL & Pin, const OCP_DBL * Niin)
flash calculation with moles of components while PVTmode is PHASE_OGW, where water phase, oil phase and gas phase could exist. (to do)in fact, the phasecase where if dissolved gas exists should be distinguished.
Definition at line 211 of file MixtureBO3_ODGW.cpp.
{
    phaseExist.assign(numPhase, false);
    cij.assign(numPhase * numCom, 0); //
    P          = Pin;
    Nt = 0;
    for (USI i = 0; i < numCom; i++) {
        Ni[i] = Niin[i];
        Nt += Ni[i];
    }
    // Water property
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw  = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[2]  = data[3];
    xi[2]  = 1 / (CONV1 * bw);
    rho[2] = std_RhoW / bw;
    USI     phasecase;
    OCP_DBL Rs_sat = PVCO.Eval(0, P, 1);
    if (Ni[0] < Nt * TINY) {
        if (Ni[1] <= Ni[0] * Rs_sat)
            phasecase = PHASE_W; // water, no oil, no gas
        else
            phasecase = PHASE_GW; // water, gas, no oil
    } else if (Ni[1] <= Ni[0] * Rs_sat)
        phasecase = PHASE_OW; // water, oil, no gas
    else
        phasecase = PHASE_ODGW; // water, oil ,gas
    switch (phasecase) {
        case PHASE_W: {
            // water
            phaseExist[2] = true;
            S[0]          = 0;
            S[1]          = 0;
            S[2]          = 1;
            cij[2 * 3 + 2] = 1;
            // hypothetical Oil property
            PVCO.Eval_All(0, P, data, cdata);
            OCP_DBL rs = data[1];
            OCP_DBL bo = data[2];
            // hypothetical Gas property
            PVDG.Eval_All(0, P, data, cdata);
            OCP_DBL bg = data[1] * (CONV1 / 1000);
            // total
            v[0]   = 0;
            v[1]   = 0;
            v[2]   = CONV1 * Ni[2] * bw;
            vf     = v[2];
            vfp    = CONV1 * Ni[2] * bwp;
            vfi[0] = CONV1 * bo - 1000 * rs * bg;
            vfi[1] = 1000 * bg;
            vfi[2] = CONV1 * bw;
            break;
        }
        case PHASE_GW: {
            // water, gas
            phaseExist[1] = true;
            phaseExist[2] = true;
            cij[1 * 3 + 1] = 1;
            cij[2 * 3 + 2] = 1;
            // hypothetical Oil property
            PVCO.Eval_All(0, P, data, cdata);
            OCP_DBL rs = data[1];
            OCP_DBL bo = data[2];
            // gas property
            PVDG.Eval_All(0, P, data, cdata);
            OCP_DBL bg  = data[1] * (CONV1 / 1000);
            OCP_DBL cbg = cdata[1] * (CONV1 / 1000);
            mu[1]  = data[2];
            xi[1]  = 1 / bg / 1000;
            rho[1] = std_RhoG / bg;
            // total
            v[0] = 0;
            v[1] = 1000 * (Ni[1] - rs * Ni[0]) * bg;
            v[2] = CONV1 * Ni[2] * bw;
#ifdef _DEBUG
            if (v[1] <= 0) {
                OCP_ABORT("gas volume <= 0");
            }
#endif // _DEBUG
            vf     = v[1] + v[2];
            S[0]   = 0;
            S[1]   = v[1] / vf;
            S[2]   = v[2] / vf;
            vfp    = 1000 * Ni[1] * cbg + CONV1 * Ni[2] * bwp;
            vfi[0] = CONV1 * bo - 1000 * rs * bg;
            vfi[1] = 1000 * bg;
            vfi[2] = CONV1 * bw;
            break;
        }
        case PHASE_OW: {
            // water, oil
            phaseExist[0] = true;
            phaseExist[2] = true;
            cij[0 * 3 + 0]        = Ni[0] / (Ni[0] + Ni[1]);
            cij[0 * 3 + 1]        = 1 - cij[0 * 3 + 0];
            cij[1 * 3 + 1]        = 1;
            cij[2 * 3 + 2]        = 1;
            // oil property
            OCP_DBL rs = Ni[1] / Ni[0];
            PVCO.Eval_All(1, rs, data, cdata);
            OCP_DBL pbb     = data[0];
            OCP_DBL bosat   = data[2];
            OCP_DBL muosat  = data[3];
            OCP_DBL cbosat  = data[4];
            OCP_DBL cmuosat = data[5];
            OCP_DBL bo      = bosat * (1 - cbosat * (P - pbb));
            OCP_DBL bop     = -bosat * cbosat;
            OCP_DBL dBo_drs = bo / bosat * cdata[2] +
                              bosat * (cdata[4] * (pbb - P) + cbosat * cdata[0]);
            mu[0]  = muosat * (1 + cmuosat * (P - pbb));
            xi[0]  = (1 + rs) / (CONV1 * bo);
            rho[0] = (std_RhoO + (1000 / CONV1) * rs * std_RhoG) / bo;
            // total
            v[0]   = CONV1 * Ni[0] * bo;
            v[2]   = CONV1 * Ni[2] * bw;
            vf     = v[0] + v[2];
            S[0]   = v[0] / vf;
            S[1]   = 0;
            S[2]   = v[2] / vf;
            vfp    = CONV1 * (Ni[0] * bop + Ni[2] * bwp);
            vfi[0] = CONV1 * (bo - dBo_drs * (Ni[1] / Ni[0]));
            vfi[1] = CONV1 * dBo_drs;
            vfi[2] = CONV1 * bw;
            break;
        }
        case PHASE_ODGW: {
            phaseExist.assign(3, true);
            // oil property
            PVCO.Eval_All(0, P, data, cdata);
            OCP_DBL rs     = data[1];
            OCP_DBL bo     = data[2];
            OCP_DBL crs    = cdata[1];
            OCP_DBL cbosat = cdata[2];
            mu[0]  = data[3];
            xi[0]  = (1 + rs) / bo / CONV1;
            rho[0] = (std_RhoO + (1000 / CONV1) * rs * std_RhoG) / bo;
            // gas property
            PVDG.Eval_All(0, P, data, cdata);
            OCP_DBL bg  = data[1] * (CONV1 / 1000);
            OCP_DBL cbg = cdata[1] * (CONV1 / 1000);
            mu[1]  = data[2];
            xi[1]  = 1 / data[1] / CONV1;
            rho[1] = std_RhoG / bg;
            // total
            cij[0 * 3 + 0] = 1 / (1 + rs);
            cij[0 * 3 + 1] = 1 - cij[0 * 3 + 0];
            cij[1 * 3 + 1] = 1;
            cij[2 * 3 + 2] = 1;
            v[0] = CONV1 * Ni[0] * bo;
            v[1] = 1000 * (Ni[1] - rs * Ni[0]) * bg;
            v[2] = CONV1 * Ni[2] * bw;
            vf   = v[0] + v[1] + v[2];
            S[0] = v[0] / vf;
            S[1] = v[1] / vf;
            S[2] = v[2] / vf;
            vfp  = CONV1 * Ni[0] * cbosat +
                  1000 * (-crs * Ni[0] * bg + (Ni[1] - rs * Ni[0]) * cbg) +
                  CONV1 * Ni[2] * bwp;
            vfi[0] = CONV1 * bo - 1000 * rs * bg;
            vfi[1] = 1000 * bg;
            vfi[2] = CONV1 * bw;
            break;
        }
    }
}
References Mixture::cij, CONV1, OCPTable::Eval(), OCPTable::Eval_All(), Mixture::mu, Mixture::Ni, Mixture::Nt, Mixture::numCom, Mixture::numPhase, Mixture::P, Mixture::phaseExist, Mixture::rho, TINY, and Mixture::xi.
BOFlash_Ni_ODGW_Deriv()
void BOMixture::BOFlash_Ni_ODGW_Deriv (const OCP_DBL & Pin, const OCP_DBL * Niin)
Definition at line 411 of file MixtureBO3_ODGW.cpp.
{
    phaseExist.assign(numPhase, false);
    cij.assign(numPhase * numCom, 0);
    rhoP.assign(numPhase, 0);
    xiP.assign(numPhase, 0);
    muP.assign(numPhase, 0);
    rhoC.assign(numPhase * numCom, 0);
    xiC.assign(numPhase * numCom, 0);
    muC.assign(numPhase * numCom, 0);
    dSec_dPri.assign(dSec_dPri.size(), 0);
    P = Pin;
    Nt = 0;
    for (USI i = 0; i < numCom; i++) {
        Ni[i] = Niin[i];
        Nt += Ni[i];
    }
    // Water property
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[2] = data[3];
    xi[2] = 1 / (CONV1 * bw);
    rho[2] = std_RhoW / bw;
    muP[2] = cdata[3];
    xiP[2] = -bwp / (bw * bw * CONV1);
    rhoP[2] = CONV1 * xiP[2] * std_RhoW;
    USI     phasecase;
    OCP_DBL Rs_sat = PVCO.Eval(0, P, 1);
    if (Ni[0] < Nt * TINY) {
        if (Ni[1] <= Ni[0] * Rs_sat)
            phasecase = PHASE_W; // water, no oil, no gas
        else
            phasecase = PHASE_GW; // water, gas, no oil
    }
    else if (Ni[1] <= Ni[0] * Rs_sat)
        phasecase = PHASE_OW; // water, oil, no gas
    else
        phasecase = PHASE_ODGW; // water, oil ,gas
    switch (phasecase) {
    case PHASE_W: {
        // water
        phaseExist[2] = true;
        S[0] = 0;
        S[1] = 0;
        S[2] = 1;
        cij[2 * 3 + 2] = 1;
        // hypothetical Oil property
        PVCO.Eval_All(0, P, data, cdata);
        OCP_DBL rs = data[1];
        OCP_DBL bo = data[2];
        // hypothetical Gas property
        PVDG.Eval_All(0, P, data, cdata);
        OCP_DBL bg = data[1] * (CONV1 / 1000);
        // total
        v[0] = 0;
        v[1] = 0;
        v[2] = CONV1 * Ni[2] * bw;
        vf = v[2];
        vfp = CONV1 * Ni[2] * bwp;
        vfi[0] = CONV1 * bo - 1000 * rs * bg;
        vfi[1] = 1000 * bg;
        vfi[2] = CONV1 * bw;
        // dSec_dPri[0] = 0; // dSo / dP
        dSec_dPri[1] = CONV1 * bo / vf;  // dSo / dNo
        // dSec_dPri[2] = 0;   // dSo / dNg;
        // dSec_dPri[3] = 0;   // dSo / dNw;
        // dSec_dPri[1 * 4 + 0] = 0;   // dSg / dP
        // dSec_dPri[1 * 4 + 1] = 0;   // dSg / dNo
        dSec_dPri[1 * 4 + 2] = 1000 * bg / vf;  // dSg / dNg
        // dSec_dPri[1 * 4 + 3] = 0;   // dSg / dNw
        dSec_dPri[2 * 4 + 0] = Ni[2] / vf * bwp * CONV1 - S[2] / vf * vfp; // dSw / dP
        dSec_dPri[2 * 4 + 1] = -S[2] / vf * vfi[0]; // dSw / dNo
        dSec_dPri[2 * 4 + 2] = -S[2] / vf * vfi[1]; // dSw / dNg
        dSec_dPri[2 * 4 + 3] = CONV1 * bw / vf - S[2] / vf * vfi[2]; // dSw / dNw
        break;
    }
    case PHASE_GW: {
        // water, gas
        phaseExist[1] = true;
        phaseExist[2] = true;
        cij[1 * 3 + 1] = 1;
        cij[2 * 3 + 2] = 1;
        // hypothetical Oil property
        PVCO.Eval_All(0, P, data, cdata);
        OCP_DBL rs = data[1];
        OCP_DBL bo = data[2];
        // gas property
        PVDG.Eval_All(0, P, data, cdata);
        OCP_DBL bg = data[1] * (CONV1 / 1000);
        OCP_DBL cbg = cdata[1] * (CONV1 / 1000);
        mu[1] = data[2];
        xi[1] = 1 / bg / 1000;
        rho[1] = std_RhoG / bg;
        muP[1] = cdata[2];
        xiP[1] = -cdata[1] / (CONV1 * data[1] * data[1]);
        rhoP[1] = 1000 * std_RhoG * xiP[1];
        // total
        v[0] = 0;
        v[1] = 1000 * (Ni[1] - rs * Ni[0]) * bg;
        v[2] = CONV1 * Ni[2] * bw;
#ifdef _DEBUG
        if (v[1] <= 0) {
            OCP_ABORT("gas volume <= 0");
        }
#endif // _DEBUG
        vf = v[1] + v[2];
        S[0] = 0;
        S[1] = v[1] / vf;
        S[2] = v[2] / vf;
        vfp = 1000 * Ni[1] * cbg + CONV1 * Ni[2] * bwp;
        vfi[0] = CONV1 * bo - 1000 * rs * bg;
        vfi[1] = 1000 * bg;
        vfi[2] = CONV1 * bw;
        // dSec_dPri[0] = 0; // dSo / dP
        dSec_dPri[1] = CONV1 * bo / vf; // dSo / dNo
        // dSec_dPri[2] = 0;   // dSo / dNg
        // dSec_dPri[3] = 0;   // dSo / dNw
        dSec_dPri[1 * 4 + 0] = 1000 * Ni[1] / vf * cbg - S[1] / vf * vfp;   // dSg / dP
        dSec_dPri[1 * 4 + 1] = -1000 * rs / vf * bg - S[1] / vf * vfi[0]; // dSg / dNo
        dSec_dPri[1 * 4 + 2] = 1000 * bg / vf - S[1] / vf * vfi[1]; // dSg / dNg
        dSec_dPri[1 * 4 + 3] = -S[1] / vf * vfi[2]; // dSg / dNw
        dSec_dPri[2 * 4 + 0] = Ni[2] / vf * bwp * CONV1 - S[2] / vf * vfp; // dSw / dP
        dSec_dPri[2 * 4 + 1] = -S[2] / vf * vfi[0]; // dSw / dNo
        dSec_dPri[2 * 4 + 2] = -S[2] / vf * vfi[1]; // dSw / dNg
        dSec_dPri[2 * 4 + 3] = CONV1 * bw / vf - S[2] / vf * vfi[2]; // dSw / dNw
        break;
    }
    case PHASE_OW: {
        // water, oil
        phaseExist[0] = true;
        phaseExist[2] = true;
        cij[0 * 3 + 0] = Ni[0] / (Ni[0] + Ni[1]);
        cij[0 * 3 + 1] = 1 - cij[0 * 3 + 0];
        cij[1 * 3 + 1] = 1;
        cij[2 * 3 + 2] = 1;
        // oil property
        OCP_DBL rs = Ni[1] / Ni[0];
        PVCO.Eval_All(1, rs, data, cdata);
        OCP_DBL pbb = data[0];
        OCP_DBL bosat = data[2];
        OCP_DBL muosat = data[3];
        OCP_DBL cbosat = data[4];
        OCP_DBL cmuosat = data[5];
        OCP_DBL bo = bosat * (1 - cbosat * (P - pbb));
        OCP_DBL bop = -bosat * cbosat;
        OCP_DBL dBo_drs = bo / bosat * cdata[2] +
            bosat * (cdata[4] * (pbb - P) + cbosat * cdata[0]);
        mu[0] = muosat * (1 + cmuosat * (P - pbb));
        xi[0] = (1 + rs) / (CONV1 * bo);
        rho[0] = (std_RhoO + (1000 / CONV1) * rs * std_RhoG) / bo;
        muP[0] = muosat * cmuosat;
        xiP[0] = -(1 + rs) * bop / (CONV1 * bo * bo);
        rhoP[0] = -(std_RhoO + (1000/CONV1) * rs * std_RhoG) / (bo * bo) * bop;
        OCP_DBL muo_rs = mu[0] / muosat * cdata[3] + muosat * (cdata[5] * (P - pbb) - cmuosat * cdata[0]);
        OCP_DBL xio_rs = 1 / (CONV1 * bo) - (1 + rs) * dBo_drs / (CONV1 * bo * bo);
        OCP_DBL rhoo_rs = (1000 / CONV1) * std_RhoG / bo - (std_RhoO + (1000 / CONV1) * rs * std_RhoG) * dBo_drs / (bo * bo);
        // total
        v[0] = CONV1 * Ni[0] * bo;
        v[2] = CONV1 * Ni[2] * bw;
        vf = v[0] + v[2];
        S[0] = v[0] / vf;
        S[1] = 0;
        S[2] = v[2] / vf;
        vfp = CONV1 * (Ni[0] * bop + Ni[2] * bwp);
        vfi[0] = CONV1 * (bo - dBo_drs * (Ni[1] / Ni[0]));
        vfi[1] = CONV1 * dBo_drs;
        vfi[2] = CONV1 * bw;
        dSec_dPri[0] = -CONV1 * Ni[0] / vf * cbosat * bosat - S[0] / vf * vfp;  // dSo / dP
        dSec_dPri[1] = CONV1 * bo / vf - CONV1 / vf * dBo_drs * (Ni[1] / Ni[0]) - S[0] / vf * vfi[0]; // dSg / dNo
        dSec_dPri[2] = CONV1 * Ni[0] / vf * dBo_drs / Ni[0] - S[0] / vf * vfi[1]; // dSg / dNg
        dSec_dPri[3] = -S[0] / vf * vfi[2]; // dSg / dNw
        dSec_dPri[2 * 4 + 0] = Ni[2] / vf * bwp * CONV1 - S[2] / vf * vfp; // dSw / dP
        dSec_dPri[2 * 4 + 1] = -S[2] / vf * vfi[0]; // dSw / dNo
        dSec_dPri[2 * 4 + 2] = -S[2] / vf * vfi[1]; // dSw / dNg
        dSec_dPri[2 * 4 + 3] = CONV1 * bw / vf - S[2] / vf * vfi[2]; // dSw / dNw
        dSec_dPri[3 * 4 + 1] = Ni[1] / pow((Ni[0] + Ni[1]), 2); // d Coo / d No
        dSec_dPri[3 * 4 + 2] = -Ni[0] / pow((Ni[0] + Ni[1]), 2); // d Coo / d Ng
        dSec_dPri[4 * 4 + 1] = -dSec_dPri[3 * 4 + 1]; // d Cgo / d No
        dSec_dPri[4 * 4 + 2] = -dSec_dPri[3 * 4 + 2]; // d Cgo / d Ng
        OCP_DBL tmp = cij[0] * cij[0];
        muC[0] = -muo_rs * cij[1] / tmp;    // dMuo / dCoo
        muC[1] = muo_rs / cij[0];           // dMuo / dCgo
        xiC[0] = -xio_rs * cij[1] / tmp;    // dXio / dCoo
        xiC[1] = xio_rs / cij[0];           // dXio / dCgo
        rhoC[0] = -rhoo_rs * cij[1] / tmp;  // dRhoo / dCoo
        rhoC[1] = rhoo_rs / cij[0];         // dRhoo / dCgo
        break;
    }
    case PHASE_ODGW: {
        phaseExist.assign(3, true);
        // oil property
        PVCO.Eval_All(0, P, data, cdata);
        OCP_DBL rs = data[1];
        OCP_DBL bo = data[2];
        OCP_DBL crs = cdata[1];
        OCP_DBL cbosat = cdata[2];
        mu[0] = data[3];
        xi[0] = (1 + rs) / bo / CONV1;
        rho[0] = (std_RhoO + (1000 / CONV1) * rs * std_RhoG) / bo;
        muP[0] = cdata[3];
        xiP[0] = crs / (CONV1 * bo) + -(1 + rs) * cbosat / (CONV1 * bo * bo);
        rhoP[0] = (1000 / CONV1) * std_RhoG * crs / bo  - (std_RhoO + (1000/CONV1) * rs * std_RhoG) * cbosat / (bo * bo);
        // gas property
        PVDG.Eval_All(0, P, data, cdata);
        OCP_DBL bg = data[1] * (CONV1 / 1000);
        OCP_DBL cbg = cdata[1] * (CONV1 / 1000);
        mu[1] = data[2];
        xi[1] = 1 / data[1] / CONV1;
        rho[1] = std_RhoG / bg;
        muP[1] = cdata[2];
        xiP[1] = -cdata[1] / (CONV1 * data[1] * data[1]);
        rhoP[1] = 1000 * std_RhoG * xiP[1];
        // total
        cij[0 * 3 + 0] = 1 / (1 + rs);
        cij[0 * 3 + 1] = 1 - cij[0 * 3 + 0];
        cij[1 * 3 + 1] = 1;
        cij[2 * 3 + 2] = 1;
        v[0] = CONV1 * Ni[0] * bo;
        v[1] = 1000 * (Ni[1] - rs * Ni[0]) * bg;
        v[2] = CONV1 * Ni[2] * bw;
        vf = v[0] + v[1] + v[2];
        S[0] = v[0] / vf;
        S[1] = v[1] / vf;
        S[2] = v[2] / vf;
        vfp = CONV1 * Ni[0] * cbosat +
            1000 * (-crs * Ni[0] * bg + (Ni[1] - rs * Ni[0]) * cbg) +
            CONV1 * Ni[2] * bwp;
        vfi[0] = CONV1 * bo - 1000 * rs * bg;
        vfi[1] = 1000 * bg;
        vfi[2] = CONV1 * bw;
        dSec_dPri[0] = (CONV1 * Ni[0] * cbosat - S[0] * vfp)/ vf; // dSo / dP
        dSec_dPri[1] = (CONV1 * bo - S[0] * vfi[0]) / vf; // dSo / dNo
        dSec_dPri[2] = -S[0] * vfi[1] / vf; // dSo / dNg
        dSec_dPri[3] = -S[0] * vfi[2] / vf; // dSo / dNw
        dSec_dPri[1 * 4 + 0] = (1000 * (Ni[1] - rs * Ni[0]) * cbg - 1000 * Ni[0] * bg * crs - S[1] * vfp) / vf; // dSg / dP
        dSec_dPri[1 * 4 + 1] = (-1000 * rs * bg - S[1] * vfi[0]) / vf; // dSg / dNo
        dSec_dPri[1 * 4 + 2] = (1000 * bg - S[1] * vfi[1]) / vf;  // dSg / dNg
        dSec_dPri[1 * 4 + 3] = -S[1] * vfi[2] / vf; // dSg / dNw
        dSec_dPri[2 * 4 + 0] = (Ni[2] * bwp * CONV1 - S[2] * vfp) / vf; // dSw / dP
        dSec_dPri[2 * 4 + 1] = -S[2] * vfi[0] / vf; // dSw / dNo
        dSec_dPri[2 * 4 + 2] = -S[2] * vfi[1] / vf; // dSw / dNg
        dSec_dPri[2 * 4 + 3] = (CONV1 * bw - S[2] * vfi[2]) / vf; // dSw / dNw
        break;
    }
    }
}
BOFlash_Ni_OW()
void BOMixture::BOFlash_Ni_OW (const OCP_DBL & Pin, const OCP_DBL * Niin)
flash calculation with moles of components while PVTmode is PHASE_OW, where only water phase and oil phase could exist.
Definition at line 149 of file MixtureBO.cpp.
{}
BOFlash_Ni_OW_Deriv()
void BOMixture::BOFlash_Ni_OW_Deriv (const OCP_DBL & Pin, const OCP_DBL * Niin)
Definition at line 47 of file MixtureBO2_OW.cpp.
{
    phaseExist.assign(numPhase, true);
    dSec_dPri.assign(dSec_dPri.size(), 0);
    P = Pin;
    Ni[0] = Niin[0];
    Ni[1] = Niin[1];
    Nt = Ni[0] + Ni[1];
    // Water Properties
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[1] = data[3];
    xi[1] = 1 / (bw * CONV1);
    rho[1] = std_RhoW / bw;
    muP[1] = cdata[3];
    xiP[1] = -bwp / (bw * bw * CONV1);
    rhoP[1] = CONV1 * xiP[1] * std_RhoW;
    // Oil Properties
    PVDO.Eval_All(0, P, data, cdata);
    OCP_DBL bo = data[1];
    OCP_DBL bop = cdata[1];
    mu[0] = data[2];
    xi[0] = 1 / (CONV1 * bo);
    rho[0] = std_RhoO / bo;
    muP[0] = cdata[2];
    xiP[0] = -xi[0] * bop / bo;
    rhoP[0] = -rho[0] * bop / bo;
    cij[0 * 2 + 0] = 1;  cij[0 * 2 + 1] = 0;
    cij[1 * 2 + 0] = 0;  cij[1 * 2 + 1] = 1;
    v[0] = CONV1 * Ni[0] * bo;
    v[1] = CONV1 * Ni[1] * bw;
    vf = v[0] + v[1];
    S[0] = v[0] / vf;
    S[1] = v[1] / vf;
    vfi[0] = CONV1 * bo;
    vfi[1] = CONV1 * bw;
    vfp = CONV1 * Ni[0] * bop + CONV1 * Ni[1] * bwp;
    dSec_dPri[0] = (CONV1 * Ni[0] * bop - S[0] * vfp) / vf; // dSo / dP
    dSec_dPri[1] = (CONV1 * bo - S[0] * vfi[0]) / vf; // dSo / dNo
    dSec_dPri[2] = -S[0] * vfi[1] / vf; // dSo / dNw
    dSec_dPri[3] = (CONV1 * Ni[1] * bwp - S[1] * vfp) / vf; // dSw / dP
    dSec_dPri[4] = -S[1] * vfi[0] / vf;  // dSw / dNo
    dSec_dPri[5] = (CONV1 * bw - S[1] * vfi[1]) / vf; // dSw / dNw
}
BOFlash_Ni_W()
void BOMixture::BOFlash_Ni_W (const OCP_DBL & Pin, const OCP_DBL * Niin)
flash calculation with moles of components while PVTmode is PHASE_W, where only water phase exists.
Definition at line 147 of file MixtureBO.cpp.
{}
BOFlash_Ni_W_Deriv()
void BOMixture::BOFlash_Ni_W_Deriv (const OCP_DBL & Pin, const OCP_DBL * Niin)
Definition at line 143 of file MixtureBO.cpp.
{}
BOFlash_Sj_ODGW()
void BOMixture::BOFlash_Sj_ODGW (const OCP_DBL & Pin, const OCP_DBL & Pbbin, const OCP_DBL * Sjin, const OCP_DBL & Vpore)
flash calculation with saturations while PVTmode is PHASE_OGW, where water phase, oil phase and gas phase could exist. (to do)in fact, the phasecase where if dissolved gas exists should be distinguished.
Definition at line 14 of file MixtureBO3_ODGW.cpp.
{
    phaseExist.assign(numPhase, false);
    cij.assign(numPhase * numCom, 0); //
    Ni.assign(numCom, 0);
    P = Pin;
    for (USI j = 0; j < numPhase; j++) S[j] = Sjin[j];
    // Water Property
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw  = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[2]  = data[3];
    rho[2] = std_RhoW / bw;
    xi[2]  = 1 / (CONV1 * bw);
    Ni[2]  = Vpore * S[2] * xi[2];
    USI phasecae;
    if (1 - S[1] - S[2] < TINY) {
        if (S[1] < TINY)
            phasecae = PHASE_W; // case 1 : water, no oil, no gas
        else
            phasecae = PHASE_GW; // case 2 : water, gas, no oil
    } else if (S[1] < TINY)
        phasecae = PHASE_OW; // case 3 : water, oil, no gas
    else
        phasecae = PHASE_ODGW; // case 4 : water, oil, gas
    switch (phasecae) {
        case PHASE_W: {
            // water
            phaseExist[2] = true;
            S[0]          = 0;
            S[1]          = 0;
            S[2]          = 1;
            cij[2 * 3 + 2] = 1;
            // hypothetical Oil property
            PVCO.Eval_All(0, P, data, cdata);
            OCP_DBL rs = data[1];
            OCP_DBL bo = data[2];
            // hypothetical Gas property
            PVDG.Eval_All(0, P, data, cdata);
            OCP_DBL bg = data[1] * (CONV1 / 1000);
            // total
            v[0]   = 0;
            v[1]   = 0;
            v[2]   = CONV1 * Ni[2] * bw;
            vf     = v[2];
            vfp    = CONV1 * Ni[2] * bwp;
            vfi[0] = CONV1 * bo - 1000 * rs * bg;
            vfi[1] = 1000 * bg;
            vfi[2] = CONV1 * bw;
            break;
        }
        case PHASE_GW: {
            // water, gas
            phaseExist[1] = true;
            phaseExist[2] = true;
            cij[1 * 3 + 1] = 1;
            cij[2 * 3 + 2] = 1;
            // hypothetical Oil property
            PVCO.Eval_All(0, P, data, cdata);
            OCP_DBL rs = data[1];
            OCP_DBL bo = data[2];
            // gas property
            PVDG.Eval_All(0, P, data, cdata);
            OCP_DBL bg  = data[1] * (CONV1 / 1000);
            OCP_DBL cbg = cdata[1] * (CONV1 / 1000);
            mu[1]  = data[2];
            xi[1]  = 1 / bg / 1000;
            rho[1] = std_RhoG / bg;
            Ni[1]  = Vpore * S[1] * xi[1];
            v[0] = 0;
            v[1] = 1000 * Ni[1] * bg; // Ni[0] = 0;
            v[2] = CONV1 * Ni[2] * bw;
            // total
            vf     = v[1] + v[2];
            S[0]   = 0;
            S[1]   = v[1] / vf;
            S[2]   = v[2] / vf;
            vfp    = 1000 * Ni[1] * cbg + CONV1 * Ni[2] * bwp;
            vfi[0] = CONV1 * bo - 1000 * rs * bg;
            vfi[1] = 1000 * bg;
            vfi[2] = CONV1 * bw;
            break;
        }
        case PHASE_OW: {
            // water, oil, unsaturated
            phaseExist[0] = true;
            phaseExist[2] = true;
            // oil property
            OCP_DBL Pbb = Pbbin;
            PVCO.Eval_All(0, Pbb, data, cdata);
            OCP_DBL rs      = data[1];
            OCP_DBL bosat   = data[2];
            OCP_DBL muosat  = data[3];
            OCP_DBL cbosat  = data[4];
            OCP_DBL cmuosat = data[5];
            OCP_DBL bo      = bosat * (1 - cbosat * (P - Pbb));
            OCP_DBL bop     = -bosat * cbosat;
            OCP_DBL dBo_drs = bo / bosat * cdata[2] +
                              bosat * (cdata[4] * (Pbb - P) + cbosat * cdata[0]);
            dBo_drs /= cdata[1];
            Ni[0]  = Vpore * (1 - S[1] - S[2]) / (CONV1 * bo);
            Ni[1]  = Ni[0] * rs;
            xi[0]  = (1 + rs) / (CONV1 * bo);
            rho[0] = (std_RhoO + (1000 / CONV1) * rs * std_RhoG) / bo;
            mu[0]  = muosat * (1 + cmuosat * (P - Pbb));
            cij[0 * 3 + 0] = Ni[0] / (Ni[0] + Ni[1]);
            cij[0 * 3 + 1] = 1 - cij[0 * 3 + 0];
            cij[1 * 3 + 1] = 1;
            cij[2 * 3 + 2] = 1;
            // total
            v[0]   = CONV1 * Ni[0] * bo;
            v[2]   = CONV1 * Ni[2] * bw;
            vf     = v[0] + v[2];
            S[0]   = v[0] / vf;
            S[1]   = 0;
            S[2]   = v[2] / vf;
            vfp    = CONV1 * (Ni[0] * bop + Ni[2] * bwp);
            vfi[0] = CONV1 * (bo - dBo_drs * (Ni[1] / Ni[0]));
            vfi[1] = CONV1 * dBo_drs;
            vfi[2] = CONV1 * bw;
            break;
        }
        case PHASE_ODGW: {
            phaseExist.assign(3, true);
            // oil property
            PVCO.Eval_All(0, P, data, cdata);
            OCP_DBL rs     = data[1];
            OCP_DBL bo     = data[2];
            OCP_DBL crs    = cdata[1];
            OCP_DBL cbosat = cdata[2];
            mu[0]  = data[3];
            Ni[0]  = Vpore * (1 - S[1] - S[2]) / (CONV1 * bo);
            xi[0]  = (1 + rs) / bo / CONV1;
            rho[0] = (std_RhoO + (1000 / CONV1) * rs * std_RhoG) / bo;
            // gas property
            PVDG.Eval_All(0, P, data, cdata);
            OCP_DBL bg  = data[1] * (CONV1 / 1000);
            OCP_DBL cbg = cdata[1] * (CONV1 / 1000);
            Ni[1]       = Vpore * S[1] / bg / 1000 + Ni[0] * rs;
            xi[1]       = 1 / data[1] / CONV1;
            rho[1]      = std_RhoG / bg;
            mu[1]       = data[2];
            cij[0 * 3 + 0] = 1 / (1 + rs);
            cij[0 * 3 + 1] = 1 - cij[0 * 3 + 0];
            cij[1 * 3 + 1] = 1;
            cij[2 * 3 + 2] = 1;
            // total
            v[0] = CONV1 * Ni[0] * bo;
            v[1] = 1000 * (Ni[1] - rs * Ni[0]) * bg;
            v[2] = CONV1 * Ni[2] * bw;
            vf   = v[0] + v[1] + v[2];
            S[0] = v[0] / vf;
            S[1] = v[1] / vf;
            S[2] = v[2] / vf;
            vfp  = CONV1 * Ni[0] * cbosat +
                  1000 * (-crs * Ni[0] * bg + (Ni[1] - rs * Ni[0]) * cbg) +
                  CONV1 * Ni[2] * bwp;
            vfi[0] = CONV1 * bo - 1000 * rs * bg;
            vfi[1] = 1000 * bg;
            vfi[2] = CONV1 * bw;
            break;
        }
    }
}
References Mixture::cij, CONV1, OCPTable::Eval_All(), Mixture::mu, Mixture::Ni, Mixture::numCom, Mixture::numPhase, Mixture::P, Mixture::phaseExist, Mixture::rho, Mixture::S, TINY, and Mixture::xi.
BOFlash_Sj_OW()
void BOMixture::BOFlash_Sj_OW (const OCP_DBL & Pin, const OCP_DBL * Sjin, const OCP_DBL & Vpore)
flash calculation with saturations while PVTmode is PHASE_OW, where only water phase and oil phase could exist.
Definition at line 4 of file MixtureBO2_OW.cpp.
{
    P = Pin;
    S[1] = Sjin[1];
    // Water Properties
    PVTW.Eval_All(0, P, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw = bw0 * (1 - cbw * (P - Pw0));
    OCP_DBL bwp = -cbw * bw0;
    mu[1] = data[3];
    xi[1] = 1 / (bw * CONV1);
    rho[1] = std_RhoW / bw;
    Ni[1] = Vpore * S[1] * xi[1];
    // Oil Properties
    PVDO.Eval_All(0, P, data, cdata);
    OCP_DBL bo = data[1];
    OCP_DBL bop = cdata[1];
    mu[0] = data[2];
    xi[0] = 1 / (CONV1 * bo);
    rho[0] = std_RhoO / bo;
    Ni[0] = Vpore * (1 - S[1]) * xi[0];
    cij[0 * 2 + 0] = 1;  cij[0 * 2 + 1] = 0;
    cij[1 * 2 + 0] = 0;  cij[1 * 2 + 1] = 1;
    v[0] = CONV1 * Ni[0] * bo;
    v[1] = CONV1 * Ni[1] * bw;
    vf = v[0] + v[1];
    S[0] = v[0] / vf;
    S[1] = v[1] / vf;
    vfi[0] = CONV1 * bo;
    vfi[1] = CONV1 * bw;
    vfp = CONV1 * Ni[0] * bop + CONV1 * Ni[1] * bwp;
}
References Mixture::cij, CONV1, OCPTable::Eval_All(), Mixture::mu, Mixture::Ni, Mixture::P, Mixture::rho, Mixture::S, Mixture::v, Mixture::vf, Mixture::vfi, Mixture::vfp, and Mixture::xi.
BOFlash_Sj_W()
void BOMixture::BOFlash_Sj_W (const OCP_DBL & Pin, const OCP_DBL * Sjin, const OCP_DBL & Vpore)
flash calculation with saturations while PVTmode is PHASE_W, where only water phase exists.
Definition at line 151 of file MixtureBO.cpp.
{
}
Flash_Ni()
void BOMixture::Flash_Ni (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Niin) override virtual
flash calculation with saturations of phase, pressure in bulks. temperature is unnecessary now.
Implements Mixture.
Definition at line 95 of file MixtureBO.cpp.
{
#ifdef _DEBUG
    // CheckNi(Niin);
#endif // _DEBUG
    switch (mode) {
        case PHASE_W:
            BOFlash_Ni_W(Pin, Niin);
            break;
        case PHASE_OW:
            BOFlash_Ni_OW(Pin, Niin);
            break;
        case PHASE_ODGW:
            BOFlash_Ni_ODGW(Pin, Niin);
            break;
        default:
            OCP_ABORT("Wrong mode specified!");
    }
}
Flash_Ni_Deriv()
void BOMixture::Flash_Ni_Deriv (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Niin) override virtual
Flash calculation with moles of components and Calculate the derivative.
Implements Mixture.
Definition at line 119 of file MixtureBO.cpp.
{
#ifdef _DEBUG
    // CheckNi(Niin);
#endif // _DEBUG
    switch (mode) {
    case PHASE_W:
        BOFlash_Ni_W_Deriv(Pin, Niin);
        break;
    case PHASE_OW:
        BOFlash_Ni_OW_Deriv(Pin, Niin);
        break;
    case PHASE_ODGW:
        BOFlash_Ni_ODGW_Deriv(Pin, Niin);
        break;
    default:
        OCP_ABORT("Wrong mode specified!");
    }
}
Flash_Sj()
void BOMixture::Flash_Sj (const OCP_DBL & Pin, const OCP_DBL & Pbbin, const OCP_DBL & Tin, const OCP_DBL * Sjin, const OCP_DBL & Vpore, const OCP_DBL * Ziin) override virtual
flash calculation with saturations of phase, pressure and buble point pressure in bulks. temperature is unnecessary now, Ziin, which represents the proportion of components is useless.
Implements Mixture.
Definition at line 74 of file MixtureBO.cpp.
{
    switch (mode) {
        case PHASE_W:
            BOFlash_Sj_W(Pin, Sjin, Vpore);
            break;
        case PHASE_OW:
            BOFlash_Sj_OW(Pin, Sjin, Vpore);
            break;
        case PHASE_ODGW:
            BOFlash_Sj_ODGW(Pin, Pbbin, Sjin, Vpore);
            break;
        default:
            OCP_ABORT("Wrong mode specified!");
    }
}
GammaPhaseG()
OCP_DBL BOMixture::GammaPhaseG (const OCP_DBL & Pin) override virtual
return gamma of gas phase, gamma equals to mass density times gravity factor.
Implements Mixture.
Definition at line 222 of file MixtureBO.cpp.
{
    if (PVDG.IsEmpty()) {
        OCP_ABORT("PVDG is missing!");
    }
    OCP_DBL bg = (CONV1 / 1000) * PVDG.Eval(0, Pin, 1);
    return std_GammaG / bg;
}
References CONV1, OCPTable::Eval(), OCPTable::IsEmpty(), and OCP_ABORT.
GammaPhaseO()
OCP_DBL BOMixture::GammaPhaseO (const OCP_DBL & Pin, const OCP_DBL & Pbbin) override virtual
return gamma of oil phase, gamma equals to mass density times gravity factor.
Implements Mixture.
Definition at line 194 of file MixtureBO.cpp.
{
    switch (mode) {
        case PHASE_OW:
            return GammaPhaseO_OW(Pin);
            break;
        case PHASE_ODGW:
            return GammaPhaseO_ODGW(Pin, Pbbin);
            break;
        default:
            OCP_ABORT("Wrong Mode");
    }
}
GammaPhaseO_ODGW()
OCP_DBL BOMixture::GammaPhaseO_ODGW (const OCP_DBL & Pin, const OCP_DBL & Pbbin)
Definition at line 763 of file MixtureBO3_ODGW.cpp.
{
    PVCO.Eval_All(0, Pbbin, data, cdata);
    OCP_DBL rs     = data[1];
    OCP_DBL bosat  = data[2];
    OCP_DBL cbosat = data[4];
    OCP_DBL bo     = bosat * (1 - cbosat * (Pin - Pbbin));
    OCP_DBL gammaO = (std_GammaO + (1000 / CONV1) * rs * std_GammaG) / bo;
    return gammaO;
}
GammaPhaseO_OW()
OCP_DBL BOMixture::GammaPhaseO_OW (const OCP_DBL & Pin)
Definition at line 145 of file MixtureBO2_OW.cpp.
{
    OCP_DBL bo = PVDO.Eval(0, Pin, 1);
    OCP_DBL gammaO = std_GammaO / bo;
    return gammaO;
}
GammaPhaseOG()
OCP_DBL BOMixture::GammaPhaseOG (const OCP_DBL & Pin, const OCP_DBL & Tin, const OCP_DBL * Ziin) inline override virtual
return gamma of hydrocarbon mixture, gamma equals to mass density times gravity factor.
Implements Mixture.
Definition at line 87 of file MixtureBO.hpp.
    {
        OCP_ABORT("Should not be used in BLKOIL mode!");
    };
References OCP_ABORT.
GammaPhaseW()
OCP_DBL BOMixture::GammaPhaseW (const OCP_DBL & Pin) override virtual
return gamma of water phase, gamma equals to mass density times gravity factor.
Implements Mixture.
Definition at line 210 of file MixtureBO.cpp.
{
    PVTW.Eval_All(0, Pin, data, cdata);
    OCP_DBL Pw0 = data[0];
    OCP_DBL bw0 = data[1];
    OCP_DBL cbw = data[2];
    OCP_DBL bw  = (bw0 * (1 - cbw * (Pin - Pw0)));
    return std_GammaW / bw;
}
References OCPTable::Eval_All().
IsEmpty_PVDG()
bool BOMixture::IsEmpty_PVDG () const inline override virtual
judge if table PVDG is empty.
Implements Mixture.
Definition at line 30 of file MixtureBO.hpp.
{ return PVDG.IsEmpty(); }
References OCPTable::IsEmpty().
RhoPhase()
OCP_DBL BOMixture::RhoPhase (const OCP_DBL & Pin, const OCP_DBL & T, const OCP_DBL * Ziin) override virtual
return mass density of phase.
Implements Mixture.
Definition at line 176 of file MixtureBO.cpp.
{
    switch (mode) {
        case PHASE_W:
            OCP_ABORT("Will be added!");
        case PHASE_OW:
            return RhoPhase_OW(Pin, Ziin);
            break;
        case PHASE_ODGW:
            return RhoPhase_ODGW(Pin, Ziin);
            break;
        default:
            OCP_ABORT("Not implemented yet!");
    }
    return 0.0; // Should not reach here!
}
RhoPhase_ODGW()
OCP_DBL BOMixture::RhoPhase_ODGW (const OCP_DBL & Pin, const OCP_DBL * Ziin)
Definition at line 740 of file MixtureBO3_ODGW.cpp.
{
    if (Ziin[1] > 1 - TINY) {
        // inj fluid is gas
        OCP_DBL bg   = PVDG.Eval(0, Pin, 1);
        OCP_DBL rhog = (1000 / CONV1) * std_RhoG / bg;
        return rhog;
    } else if (Ziin[2] > 1 - TINY) {
        // inj fluid is water
        PVTW.Eval_All(0, Pin, data, cdata);
        OCP_DBL Pw0  = data[0];
        OCP_DBL bw0  = data[1];
        OCP_DBL cbw  = data[2];
        OCP_DBL bw   = bw0 * (1 - cbw * (P - Pw0));
        OCP_DBL rhow = std_RhoW / bw;
        return rhow;
    } else {
        OCP_ABORT("Wrong Zi!");
    }
}
RhoPhase_OW()
OCP_DBL BOMixture::RhoPhase_OW (const OCP_DBL & Pin, const OCP_DBL * Ziin)
Definition at line 127 of file MixtureBO2_OW.cpp.
{
    if (Ziin[1] > 1 - TINY) {
        // inj fluid is water
        PVTW.Eval_All(0, Pin, data, cdata);
        OCP_DBL Pw0 = data[0];
        OCP_DBL bw0 = data[1];
        OCP_DBL cbw = data[2];
        OCP_DBL bw = bw0 * (1 - cbw * (P - Pw0));
        OCP_DBL rhow = std_RhoW / bw;
        return rhow;
    }
    else {
        OCP_ABORT("Wrong Zi!");
    }
}
XiPhase()
OCP_DBL BOMixture::XiPhase (const OCP_DBL & Pin, const OCP_DBL & T, const OCP_DBL * Ziin) override virtual
Return molar density of phase, it's used to calculate the molar density of injection fluids in injection wells.
Implements Mixture.
Definition at line 158 of file MixtureBO.cpp.
{
    switch (mode) {
        case PHASE_W:
            OCP_ABORT("Will be added!");
        case PHASE_OW:
            return XiPhase_OW(Pin, Ziin);
            break;
        case PHASE_ODGW:
            return XiPhase_ODGW(Pin, Ziin);
            break;
        default:
            OCP_ABORT("Not implemented yet!");
    }
    return 0.0; // Should not reach here!
}
XiPhase_ODGW()
OCP_DBL BOMixture::XiPhase_ODGW (const OCP_DBL & Pin, const OCP_DBL * Ziin)
Definition at line 715 of file MixtureBO3_ODGW.cpp.
{
    if (Ziin[1] > 1 - TINY) {
        // inj fluid is gas
        OCP_DBL bg  = PVDG.Eval(0, Pin, 1);
        // OCP_DBL xig = 1 / (CONV1 * bg);
        OCP_DBL xig = 1 / CONV1 / bg;
        return xig;
    } else if (Ziin[2] > 1 - TINY) {
        // inj fluid is water
        PVTW.Eval_All(0, Pin, data, cdata);
        OCP_DBL Pw0 = data[0];
        OCP_DBL bw0 = data[1];
        OCP_DBL cbw = data[2];
        OCP_DBL bw  = bw0 * (1 - cbw * (P - Pw0));
        // OCP_DBL xiw = 1 / (CONV1 * bw);
        OCP_DBL xiw = 1 / CONV1 / bw;
        return xiw;
    } else {
        OCP_ABORT("Wrong Zi!");
    }
}
XiPhase_OW()
OCP_DBL BOMixture::XiPhase_OW (const OCP_DBL & Pin, const OCP_DBL * Ziin)
Definition at line 109 of file MixtureBO2_OW.cpp.
{
    if (Ziin[1] > 1 - TINY) {
        // inj fluid is water
        PVTW.Eval_All(0, Pin, data, cdata);
        OCP_DBL Pw0 = data[0];
        OCP_DBL bw0 = data[1];
        OCP_DBL cbw = data[2];
        OCP_DBL bw = bw0 * (1 - cbw * (P - Pw0));
        OCP_DBL xiw = 1 / (CONV1 * bw);
        return xiw;
    }
    else {
        OCP_ABORT("Wrong Zi!");
    }
}
The documentation for this class was generated from the following files:
MixtureBO.hpp
MixtureBO.cpp
MixtureBO2_OW.cpp
MixtureBO3_ODGW.cpp