OpenCAEPoro: OCPControl Class Reference
OCPControl Class Reference
All control parameters except for well controlers.
#include <OCPControl.hpp>
Public Member Functions
void InputParam (const ParamControl &CtrlParam)
Input parameters for control.
void ApplyControl (const USI &i)
Apply control for time step i.
void InitTime (const USI &i)
Initialize time step i.
void SetupFastControl (const USI &argc, const char *optset[])
Setup fast Control.
USI GetMethod () const
Return type of the solution method.
USI GetNumTSteps () const
Return number of TSTEPs.
OCP_DBL GetCurTime () const
Return the current time.
OCP_DBL & GetCurDt ()
Return current dt.
OCP_DBL GetLastDt () const
Return last dt.
USI GetLSiter () const
Return the number of linear iterations in one time step.
USI GetLSiterT () const
Return the total number of linear iterations.
USI GetNRiter () const
Return the number of Newton iterations in one time step.
USI GetNRiterT () const
Return the total nubmer of Newton iterations.
void UpdateIters ()
Update the number of iterations.
void UpdateIterLS (const USI &num)
Update the number of linear iterations.
void UpdateIterNR ()
Update the number of Newton iterations.
void ResetIterNRLS ()
Reset the number of iterations.
void UpdateTimeLS (const OCP_DBL &t)
Update time used for linear solver.
void RecordTotalTime (const OCP_DBL &t)
Record the total time of simulation.
void CalNextTstepIMPEC (const Reservoir &reservoir)
Calculate the next time step according to max change of some variables.
void CalNextTstepFIM (const Reservoir &reservoir)
bool IsCriticalTime (const USI &d)
Determine whether the critical time point has been reached.
string GetWorkDir () const
Return work dir name.
string GetLsFile () const
Return linear solver file name.
Friends
class OpenCAEPoro
class OCPOutput
class DetailInfo
class Reservoir
class OCP_FIM
class OCP_FIMn
class OCP_IMPEC
class OCP_AIMc
class OCP_AIMs
class OCP_AIMt
class OCP_FIM_IMPEC
class Solver
Detailed Description
All control parameters except for well controlers.
Definition at line 93 of file OCPControl.hpp.
Member Function Documentation
ApplyControl()
void OCPControl::ApplyControl (const USI & i)
Apply control for time step i.
Definition at line 113 of file OCPControl.cpp.
{
    ctrlTime    = ctrlTimeSet[i];
    ctrlPreTime = ctrlPreTimeSet[i];
    ctrlNR      = ctrlNRSet[i];
    end_time    = criticalTime[i + 1];
    InitTime(i);
}
References InitTime().
CalNextTstepFIM()
void OCPControl::CalNextTstepFIM (const Reservoir & reservoir)
Definition at line 204 of file OCPControl.cpp.
{
    last_dt = current_dt;
    current_time += current_dt;
    OCP_DBL c1, c2, c;
    c1 = c2 = 10;
    const OCP_DBL dPmaxB = reservoir.bulk.GetdPmax();
    const OCP_DBL dPmaxW = reservoir.allWells.GetdBHPmax();
    const OCP_DBL dPmax  = max(dPmaxB, dPmaxW);
    const OCP_DBL dSmax = reservoir.bulk.GetdSmax();
    if (dPmax > TINY) c1 = ctrlPreTime.dPlim / dPmax;
    if (dSmax > TINY) c2 = ctrlPreTime.dSlim / dSmax;
    OCP_DBL c3 = 1.5;
    if (iterNR < 30) { // temp
        c3 = 2;
    } else if (iterNR > 8) {
        c3 = 0.5;
    }
    c = min(min(c1, c2), c3);
    c = max(ctrlTime.minChopFac, c);
    c = min(ctrlTime.maxIncreFac, c);
    current_dt *= c;
    if (current_dt > ctrlTime.timeMax) current_dt = ctrlTime.timeMax;
    if (current_dt < ctrlTime.timeMin) current_dt = ctrlTime.timeMin;
    init_dt = current_dt;
    const OCP_DBL dt = end_time - current_time;
    if (current_dt > dt) current_dt = dt;
}
CalNextTstepIMPEC()
void OCPControl::CalNextTstepIMPEC (const Reservoir & reservoir)
Calculate the next time step according to max change of some variables.
Definition at line 168 of file OCPControl.cpp.
{
    last_dt = current_dt;
    current_time += current_dt;
    OCP_DBL c1, c2, c3, c4, c;
    c1 = c2 = c3 = c4 = 10;
    const OCP_DBL dPmax = reservoir.bulk.GetdPmax();
    const OCP_DBL dNmax = reservoir.bulk.GetdNmax();
    const OCP_DBL dSmax = reservoir.bulk.GetdSmax();
    const OCP_DBL dVmax = reservoir.bulk.GetdVmax();
    //cout << dPmax << "   " << dSmax << endl;
    if (dPmax > TINY) c1 = ctrlPreTime.dPlim / dPmax;
    if (dSmax > TINY) c2 = ctrlPreTime.dSlim / dSmax;
    if (dNmax > TINY) c3 = ctrlPreTime.dNlim / dNmax;
    if (dVmax > TINY) c4 = ctrlPreTime.dVlim / dVmax;
    c = min(min(c1, c2), min(c3, c4));
    c = max(ctrlTime.minChopFac, c);
    c = min(ctrlTime.maxIncreFac, c);
    current_dt *= c;
    if (current_dt > ctrlTime.timeMax) current_dt = ctrlTime.timeMax;
    if (current_dt < ctrlTime.timeMin) current_dt = ctrlTime.timeMin;
    OCP_DBL dt = end_time - current_time;
    if (current_dt > dt) current_dt = dt;
    // cout << "FactorT: " << c << "   Next dt: " << dt << endl;
}
References ControlPreTime::dNlim, ControlPreTime::dPlim, ControlPreTime::dSlim, ControlPreTime::dVlim, Bulk::GetdNmax(), Bulk::GetdPmax(), Bulk::GetdSmax(), Bulk::GetdVmax(), ControlTime::maxIncreFac, ControlTime::minChopFac, ControlTime::timeMax, ControlTime::timeMin, and TINY.
GetCurDt()
OCP_DBL & OCPControl::GetCurDt () inline
Return current dt.
Definition at line 133 of file OCPControl.hpp.
{ return current_dt; }
GetCurTime()
OCP_DBL OCPControl::GetCurTime () const inline
Return the current time.
Definition at line 130 of file OCPControl.hpp.
{ return current_time; }
GetLastDt()
OCP_DBL OCPControl::GetLastDt () const inline
Return last dt.
Definition at line 136 of file OCPControl.hpp.
{ return last_dt; }
GetLsFile()
string OCPControl::GetLsFile () const inline
Return linear solver file name.
Definition at line 182 of file OCPControl.hpp.
{ return linearsolveFile; }
GetLSiter()
USI OCPControl::GetLSiter () const inline
Return the number of linear iterations in one time step.
Definition at line 139 of file OCPControl.hpp.
{ return iterLS; }
GetLSiterT()
USI OCPControl::GetLSiterT () const inline
Return the total number of linear iterations.
Definition at line 142 of file OCPControl.hpp.
{ return iterLS_total; }
GetMethod()
USI OCPControl::GetMethod () const inline
Return type of the solution method.
Definition at line 124 of file OCPControl.hpp.
{ return method; }
GetNRiter()
USI OCPControl::GetNRiter () const inline
Return the number of Newton iterations in one time step.
Definition at line 145 of file OCPControl.hpp.
{ return iterNR; }
GetNRiterT()
USI OCPControl::GetNRiterT () const inline
Return the total nubmer of Newton iterations.
Definition at line 148 of file OCPControl.hpp.
{ return iterNR_total; }
GetNumTSteps()
USI OCPControl::GetNumTSteps () const inline
Return number of TSTEPs.
Definition at line 127 of file OCPControl.hpp.
{ return criticalTime.size(); }
GetWorkDir()
string OCPControl::GetWorkDir () const inline
Return work dir name.
Definition at line 179 of file OCPControl.hpp.
{ return workDir; }
InitTime()
void OCPControl::InitTime (const USI & i)
Initialize time step i.
Definition at line 122 of file OCPControl.cpp.
{
    OCP_DBL dt = criticalTime[i + 1] - current_time;
    if (dt <= 0) OCP_ABORT("Non-positive time stepsize!");
    static bool firstflag = true;
    if (firstflag || true) {
        current_dt = min(dt, ctrlTime.timeInit);
        firstflag = false;
    }
    else {
        current_dt = min(dt, init_dt);
    }
}
References OCP_ABORT, and ControlTime::timeInit.
InputParam()
void OCPControl::InputParam (const ParamControl & CtrlParam)
Input parameters for control.
Definition at line 71 of file OCPControl.cpp.
{
    workDir = CtrlParam.dir;
    if (CtrlParam.method == "IMPEC") {
        method = IMPEC;
    } else if (CtrlParam.method == "FIM") {
        method = FIM;
    } else if (CtrlParam.method == "FIMn") {
        method = FIMn;
    } else if (CtrlParam.method == "AIMc") {
        method = AIMc;
    } else if (CtrlParam.method == "AIMs") {
        method = AIMs;
    } else if (CtrlParam.method == "AIMt") {
        method = AIMt;
    }else {
        OCP_ABORT("Wrong method specified!");
    }
    linearsolveFile = CtrlParam.linearSolve;
    criticalTime = CtrlParam.criticalTime;
    USI t = CtrlParam.criticalTime.size();
    ctrlTimeSet.resize(t);
    ctrlPreTimeSet.resize(t);
    ctrlNRSet.resize(t);
    USI         n = CtrlParam.tuning_T.size();
    vector<USI> ctrlCriticalTime(n + 1);
    for (USI i = 0; i < n; i++) {
        ctrlCriticalTime[i] = CtrlParam.tuning_T[i].d;
    }
    ctrlCriticalTime.back() = t;
    for (USI i = 0; i < n; i++) {
        for (USI d = ctrlCriticalTime[i]; d < ctrlCriticalTime[i + 1]; d++) {
            ctrlTimeSet[d]    = ControlTime(CtrlParam.tuning_T[i].Tuning[0]);
            ctrlPreTimeSet[d] = ControlPreTime(CtrlParam.tuning_T[i].Tuning[1]);
            ctrlNRSet[d]      = ControlNR(CtrlParam.tuning_T[i].Tuning[2]);
        }
    }
}
References AIMc, AIMs, AIMt, ParamControl::criticalTime, ParamControl::dir, FIM, FIMn, IMPEC, ParamControl::linearSolve, ParamControl::method, OCP_ABORT, and ParamControl::tuning_T.
IsCriticalTime()
bool OCPControl::IsCriticalTime (const USI & d) inline
Determine whether the critical time point has been reached.
Definition at line 173 of file OCPControl.hpp.
    {
        return ((criticalTime[d] - current_time) < TINY);
    }
References TINY.
RecordTotalTime()
void OCPControl::RecordTotalTime (const OCP_DBL & t) inline
Record the total time of simulation.
Definition at line 166 of file OCPControl.hpp.
{ totalSimTime += t; }
ResetIterNRLS()
void OCPControl::ResetIterNRLS ()
Reset the number of iterations.
Definition at line 252 of file OCPControl.cpp.
{
    wastedIterNR += iterNR;
    iterNR = 0;
    wastedIterLS += iterLS;
    iterLS = 0;
}
SetupFastControl()
void OCPControl::SetupFastControl (const USI & argc, const char * optset[])
Setup fast Control.
Definition at line 138 of file OCPControl.cpp.
{
    ctrlFast.ReadParam(argc, optset);
    if (ctrlFast.activity) {
        method = ctrlFast.method;
        switch (method) {
            case IMPEC:
            case AIMt:
                linearsolveFile = "./csr.fasp";
                break;
            case AIMs:
            case AIMc:
            case FIM:
            case FIMn:
                linearsolveFile = "./bsr.fasp";
                break;
            default:
                OCP_ABORT("Wrong method in command line!");
                break;
        }
        USI n = ctrlTimeSet.size();
        for (USI i = 0; i < n; i++) {
            ctrlTimeSet[i].timeInit = ctrlFast.timeInit;
            ctrlTimeSet[i].timeMax  = ctrlFast.timeMax;
            ctrlTimeSet[i].timeMin  = ctrlFast.timeMin;
        }
        printLevel = ctrlFast.printLevel;
    }
}
References AIMc, AIMs, AIMt, FIM, FIMn, IMPEC, FastControl::method, OCP_ABORT, FastControl::printLevel, FastControl::timeInit, FastControl::timeMax, and FastControl::timeMin.
UpdateIterLS()
void OCPControl::UpdateIterLS (const USI & num) inline
Update the number of linear iterations.
Definition at line 154 of file OCPControl.hpp.
{ iterLS += num; }
UpdateIterNR()
void OCPControl::UpdateIterNR () inline
Update the number of Newton iterations.
Definition at line 157 of file OCPControl.hpp.
{ iterNR++; }
UpdateIters()
void OCPControl::UpdateIters ()
Update the number of iterations.
Definition at line 243 of file OCPControl.cpp.
{
    numTstep += 1;
    iterNR_total += iterNR;
    iterLS_total += iterLS;
    iterNR = 0;
    iterLS = 0;
}
UpdateTimeLS()
void OCPControl::UpdateTimeLS (const OCP_DBL & t) inline
Update time used for linear solver.
Definition at line 163 of file OCPControl.hpp.
{ totalLStime += t; }
Friends And Related Function Documentation
DetailInfo
friend class DetailInfo friend
Definition at line 97 of file OCPControl.hpp.
OCP_AIMc
friend class OCP_AIMc friend
Definition at line 103 of file OCPControl.hpp.
OCP_AIMs
friend class OCP_AIMs friend
Definition at line 104 of file OCPControl.hpp.
OCP_AIMt
friend class OCP_AIMt friend
Definition at line 105 of file OCPControl.hpp.
OCP_FIM
friend class OCP_FIM friend
Definition at line 100 of file OCPControl.hpp.
OCP_FIM_IMPEC
friend class OCP_FIM_IMPEC friend
Definition at line 106 of file OCPControl.hpp.
OCP_FIMn
friend class OCP_FIMn friend
Definition at line 101 of file OCPControl.hpp.
OCP_IMPEC
friend class OCP_IMPEC friend
Definition at line 102 of file OCPControl.hpp.
OCPOutput
friend class OCPOutput friend
Definition at line 96 of file OCPControl.hpp.
OpenCAEPoro
friend class OpenCAEPoro friend
Definition at line 95 of file OCPControl.hpp.
Reservoir
friend class Reservoir friend
Definition at line 98 of file OCPControl.hpp.
Solver
friend class Solver friend
Definition at line 108 of file OCPControl.hpp.
The documentation for this class was generated from the following files:
OCPControl.hpp
OCPControl.cpp