OpenCAEPoro: Connection_BB Class Reference
Connection_BB Class Reference
#include <BulkConn.hpp>
Public Member Functions
void GetConnectionInfo () const
Print information about connection on screen.
OCP_USI GetBulkNum () const
Return num of bulk.
void Setup (const Grid &myGrid, const Bulk &myBulk)
void InitSize (const Bulk &myBulk)
initialize the size of variable related to neighbor.
void CalConn (const Grid &myGrid, const USI &np)
Setup variable related to neighbor.
void CalIteratorConn ()
generate iteratorConn of active connections from neighbor.
void CalArea (const Grid &myGrid, const Bulk &myBulk)
calculate all effective area of connections.
OCP_DBL CalAkd (const Grid &myGrid, const Bulk &myBulk, const OCP_USI &bIdb, const OCP_USI &eIdb) const
calculate effective area of connections.
OCP_DBL CalCFL (const Bulk &myBulk, const OCP_DBL &dt) const
calculate the CFL number of flow between bulks.
void CalFlux (const Bulk &myBulk)
calculate main information about flow between bulks.
void MassConserve (Bulk &myBulk, const OCP_DBL &dt) const
template<typename T >
void AllocateMat (Solver< T > &mySolver) const
Allocate memory for Matrix, it should be called only once at the beginning.
template<typename T >
void InitAssembleMat (Solver< T > &mySolver) const
void AssembleMat_IMPES (Solver< OCP_DBL > &mySolver, const Bulk &myBulk, const OCP_DBL &dt) const
assmeble Matrix, parts only related to bulks are considered.
Friends
class Solver< OCP_DBL >
Detailed Description
Connection_BB is a core component of reservoir, it contains all properties and operations about connections between bulks(active grids). due to the activity of bulks, almost all connections are meaningful. you can traverse all the connections through the iterator in it, which is effective. flow calculation between active bulks, matrix assembling contributed only by bulks are included in it.
Definition at line 47 of file BulkConn.hpp.
Member Function Documentation
AllocateMat()
template<typename T > void Connection_BB::AllocateMat (Solver< T > & mySolver) const
Allocate memory for Matrix, it should be called only once at the beginning.
Definition at line 121 of file BulkConn.hpp.
{
    for (OCP_USI n = 0; n < numBulk; n++) {
        MySolver.rowCapacity[n] += neighborNum[n];
    }
}
AssembleMat_IMPES()
void Connection_BB::AssembleMat_IMPES (Solver< OCP_DBL > & mySolver, const Bulk & myBulk, const OCP_DBL & dt) const
assmeble Matrix, parts only related to bulks are considered.
Definition at line 309 of file BulkConn.cpp.
{
    // accumulate term
    OCP_DBL Vp0, Vp, vf, vfp, P;
    OCP_DBL cr = myBulk.rockC1;
    for (OCP_USI n = 0; n < numBulk; n++) {
        Vp0 = myBulk.rockVpInit[n];
        Vp  = myBulk.rockVp[n];
        vfp = myBulk.vfp[n];
        P   = myBulk.P[n];
        vf  = myBulk.vf[n];
        OCP_DBL temp        = cr * Vp0 - vfp;
        mySolver.diagVal[n] = temp;
        mySolver.b[n]       = temp * P + dt * (vf - Vp);
    }
    // check
    // ofstream outb("testb.dat");
    // if (!outb.is_open())
    //  cout << "Can not open " << "testb.dat" << endl;
    // outb << mySolver.dim << endl;
    // for (int i = 0; i < mySolver.dim; i++)
    //  outb << mySolver.b[i] << endl;
    // outb.close();
    // flux term
    OCP_USI bId, eId, uId;
    USI     np = myBulk.numPhase;
    USI     nc = myBulk.numCom;
    OCP_DBL valupi, valdowni;
    OCP_DBL valup, rhsup, valdown, rhsdown;
    // OCP_USI    lastbId = -1;
    OCP_USI lastbId = iteratorConn[0].EId;
    for (OCP_USI c = 0; c < numConn; c++) {
        bId     = iteratorConn[c].BId;
        eId     = iteratorConn[c].EId;
        valup   = 0;
        rhsup   = 0;
        valdown = 0;
        rhsdown = 0;
        for (USI j = 0; j < np; j++) {
            uId = upblock[c * np + j];
            if (!myBulk.phaseExist[uId * np + j]) continue;
            valupi   = 0;
            valdowni = 0;
            for (USI i = 0; i < nc; i++) {
                valupi +=
                    myBulk.vfi[bId * nc + i] * myBulk.cij[uId * np * nc + j * nc + i];
                valdowni +=
                    myBulk.vfi[eId * nc + i] * myBulk.cij[uId * np * nc + j * nc + i];
            }
            OCP_DBL dD   = myBulk.depth[bId] - myBulk.depth[eId];
            OCP_DBL dPc  = myBulk.Pc[bId * np + j] - myBulk.Pc[eId * np + j];
            OCP_DBL temp = myBulk.xi[uId * np + j] * upblock_Trans[c * np + j] * dt;
            valup += temp * valupi;
            valdown += temp * valdowni;
            temp *= upblock_Rho[c * np + j] * GRAVITY_FACTOR * dD - dPc;
            rhsup += temp * valupi;
            rhsdown -= temp * valdowni;
        }
        USI diagptr = selfPtr[bId];
        if (bId != lastbId) {
            // new bulk
            assert(mySolver.val[bId].size() == diagptr);
            mySolver.val[bId].push_back(mySolver.diagVal[bId]);
            lastbId = bId;
        }
        mySolver.val[bId][diagptr] += valup;
        mySolver.val[bId].push_back(-valup);
        mySolver.val[eId].push_back(-valdown);
        mySolver.diagVal[eId] += valdown;
        mySolver.b[bId] += rhsup;
        mySolver.b[eId] += rhsdown;
    }
    // Add the rest of diag value
    // important!
    for (OCP_USI n = 0; n < numBulk; n++) {
        if (mySolver.val[n].size() == selfPtr[n])
            mySolver.val[n].push_back(mySolver.diagVal[n]);
    }
}
CalAkd()
OCP_DBL Connection_BB::CalAkd (const Grid & myGrid, const Bulk & myBulk, const OCP_USI & bIdb, const OCP_USI & eIdb) const
calculate effective area of connections.
Definition at line 165 of file BulkConn.cpp.
{
    OCP_USI bIdg = myGrid.activeMap_B2G[bIdb];
    OCP_USI eIdg = myGrid.activeMap_B2G[eIdb];
    OCP_INT diff = eIdg - bIdg;
    if (diff < 0) diff *= -1;
    if (diff == 1) {
        // x - direction
        OCP_DBL T1 = myBulk.rockKx[bIdb] * myBulk.ntg[bIdb] * myBulk.dy[bIdb] *
                     myBulk.dz[bIdb] / myBulk.dx[bIdb];
        OCP_DBL T2 = myBulk.rockKx[eIdb] * myBulk.ntg[eIdb] * myBulk.dy[eIdb] *
                     myBulk.dz[eIdb] / myBulk.dx[eIdb];
        return (2 / (1 / T1 + 1 / T2));
    } else if (diff == myGrid.nx) {
        // y - direction
        OCP_DBL T1 = myBulk.rockKy[bIdb] * myBulk.ntg[bIdb] * myBulk.dz[bIdb] *
                     myBulk.dx[bIdb] / myBulk.dy[bIdb];
        OCP_DBL T2 = myBulk.rockKy[eIdb] * myBulk.ntg[eIdb] * myBulk.dz[eIdb] *
                     myBulk.dx[eIdb] / myBulk.dy[eIdb];
        return (2 / (1 / T1 + 1 / T2));
    } else if (diff == myGrid.nx * myGrid.ny) {
        // z - direction  ----  no ntg
        OCP_DBL T1 =
            myBulk.rockKz[bIdb] * myBulk.dx[bIdb] * myBulk.dy[bIdb] / myBulk.dz[bIdb];
        OCP_DBL T2 =
            myBulk.rockKz[eIdb] * myBulk.dx[eIdb] * myBulk.dy[eIdb] / myBulk.dz[eIdb];
        return (2 / (1 / T1 + 1 / T2));
    } else {
        // Wrong
        ERRORcheck("Wrong bId and eId in function");
        exit(0);
    }
}
CalArea()
void Connection_BB::CalArea (const Grid & myGrid, const Bulk & myBulk)
calculate all effective area of connections.
Definition at line 149 of file BulkConn.cpp.
{
    // calculate efficient area of interface of bulk to bulk
    // using iteratorConn
    area.reserve(numConn);
    for (OCP_USI n = 0; n < numConn; n++) {
        OCP_USI bIdb = iteratorConn[n].BId;
        OCP_USI eIdb = iteratorConn[n].EId;
        // area.push_back(1);
        area.push_back(CalAkd(myGrid, myBulk, bIdb, eIdb));
    }
    assert(area.size() == numConn);
}
References CalAkd().
CalCFL()
OCP_DBL Connection_BB::CalCFL (const Bulk & myBulk, const OCP_DBL & dt) const
calculate the CFL number of flow between bulks.
Definition at line 203 of file BulkConn.cpp.
{
    USI     np   = myBulk.numPhase;
    OCP_DBL cfl  = 0;
    OCP_DBL temp = 0;
    for (OCP_USI c = 0; c < numConn; c++) {
        for (USI j = 0; j < np; j++) {
            OCP_USI uId = upblock[c * np + j];
            if (myBulk.phaseExist[uId]) {
                temp = fabs(upblock_Velocity[c * np + j]) * dt;
                temp /= myBulk.vj[uId * np + j];
                if (cfl < temp) cfl = temp;
            }
        }
    }
    return cfl;
}
CalConn()
void Connection_BB::CalConn (const Grid & myGrid, const USI & np)
Setup variable related to neighbor.
Definition at line 38 of file BulkConn.cpp.
{
    USI     nx   = myGrid.nx;
    USI     ny   = myGrid.ny;
    USI     nz   = myGrid.nz;
    OCP_USI nxny = nx * ny;
    // bIdb : begin id in bulk
    // bIdg : begin id in grid
    // eIdb : end id in bulk
    bool    activity;
    OCP_USI eIdb;
    for (OCP_USI bIdb = 0; bIdb < numBulk; bIdb++) {
        OCP_USI bIdg = myGrid.activeMap_B2G[bIdb];
        USI     k    = bIdg / nxny;
        USI     j    = (bIdg - k * nxny) / nx;
        USI     i    = bIdg - k * nxny - j * nx;
        USI count = 0;
        // up
        if (k > 0) {
            activity = myGrid.activeMap_G2B[bIdg - nxny].GetAct();
            if (activity) {
                eIdb = myGrid.activeMap_G2B[bIdg - nxny].GetId();
                neighbor[bIdb].push_back(eIdb);
                count++;
            }
        }
        // back
        if (j > 0) {
            activity = myGrid.activeMap_G2B[bIdg - nx].GetAct();
            if (activity) {
                eIdb = myGrid.activeMap_G2B[bIdg - nx].GetId();
                neighbor[bIdb].push_back(eIdb);
                count++;
            }
        }
        // left
        if (i > 0) {
            activity = myGrid.activeMap_G2B[bIdg - 1].GetAct();
            if (activity) {
                eIdb = myGrid.activeMap_G2B[bIdg - 1].GetId();
                neighbor[bIdb].push_back(eIdb);
                count++;
            }
        }
        numConn += count;
        // self
        neighbor[bIdb].push_back(bIdb);
        selfPtr[bIdb] = count;
        count++;
        // right
        if (i < nx - 1) {
            activity = myGrid.activeMap_G2B[bIdg + 1].GetAct();
            if (activity) {
                eIdb = myGrid.activeMap_G2B[bIdg + 1].GetId();
                neighbor[bIdb].push_back(eIdb);
                count++;
            }
        }
        // front
        if (j < ny - 1) {
            activity = myGrid.activeMap_G2B[bIdg + nx].GetAct();
            if (activity) {
                eIdb = myGrid.activeMap_G2B[bIdg + nx].GetId();
                neighbor[bIdb].push_back(eIdb);
                count++;
            }
        }
        // down
        if (k < nz - 1) {
            activity = myGrid.activeMap_G2B[bIdg + nxny].GetAct();
            if (activity) {
                eIdb = myGrid.activeMap_G2B[bIdg + nxny].GetId();
                neighbor[bIdb].push_back(eIdb);
                count++;
            }
        }
        neighborNum[bIdb] = count;
    }
    upblock.resize(numConn * np);
    upblock_Rho.resize(numConn * np);
    upblock_Trans.resize(numConn * np);
    upblock_Velocity.resize(numConn * np);
}
CalFlux()
void Connection_BB::CalFlux (const Bulk & myBulk)
calculate main information about flow between bulks.
Definition at line 223 of file BulkConn.cpp.
{
    // calculate a step flux using iteratorConn
    OCP_USI bId, eId, uId;
    OCP_USI bId_np_j, eId_np_j;
    OCP_DBL Pbegin, Pend, rho;
    USI     np = myBulk.numPhase;
    for (OCP_USI c = 0; c < numConn; c++) {
        bId         = iteratorConn[c].BId;
        eId         = iteratorConn[c].EId;
        OCP_DBL Akd = area[c];
        for (USI j = 0; j < np; j++) {
            bId_np_j = bId * np + j;
            eId_np_j = eId * np + j;
            bool exbegin = myBulk.phaseExist[bId_np_j];
            bool exend   = myBulk.phaseExist[eId_np_j];
            if ((exbegin) && (exend)) {
                Pbegin = myBulk.Pj[bId_np_j];
                Pend   = myBulk.Pj[eId_np_j];
                rho    = (myBulk.rho[bId_np_j] + myBulk.rho[eId_np_j]) / 2;
            } else if (exbegin && (!exend)) {
                Pbegin = myBulk.Pj[bId_np_j];
                Pend   = myBulk.P[eId];
                rho    = myBulk.rho[bId_np_j];
            } else if ((!exbegin) && (exend)) {
                Pbegin = myBulk.P[bId];
                Pend   = myBulk.Pj[eId_np_j];
                rho    = myBulk.rho[eId_np_j];
            } else {
                upblock[c * np + j] = bId;
                continue;
            }
            uId          = bId;
            bool    exup = exbegin;
            OCP_DBL dP   = (Pbegin - GRAVITY_FACTOR * rho * myBulk.depth[bId]) -
                         (Pend - GRAVITY_FACTOR * rho * myBulk.depth[eId]);
            if (dP < 0) {
                uId  = eId;
                exup = exend;
            }
            upblock_Rho[c * np + j] = rho;
            upblock[c * np + j]     = uId;
            OCP_USI uId_np_j        = uId * np + j;
            OCP_DBL trans =
                CONV1 * CONV2 * Akd * myBulk.kr[uId_np_j] / myBulk.mu[uId_np_j];
            upblock_Trans[c * np + j] = trans;
            if (exup) {
                upblock_Velocity[c * np + j] = trans * dP;
            } else {
                upblock_Velocity[c * np + j] = 0;
            }
        }
    }
}
CalIteratorConn()
void Connection_BB::CalIteratorConn ()
generate iteratorConn of active connections from neighbor.
Definition at line 132 of file BulkConn.cpp.
{
    iteratorConn.reserve(numConn);
    // generate iterator for BB from iteratorConn
    for (OCP_USI bId = 0; bId < numBulk; bId++) {
        USI beginIt = selfPtr[bId] + 1;
        USI nbc     = neighborNum[bId];
        for (USI c = beginIt; c < nbc; c++) {
            OCP_USI eId = neighbor[bId][c];
            iteratorConn.push_back(BB_Pair(bId, eId));
        }
    }
    assert(iteratorConn.size() == numConn);
}
GetBulkNum()
OCP_USI Connection_BB::GetBulkNum () const inline
Return num of bulk.
Definition at line 57 of file BulkConn.hpp.
{ return numBulk; }
GetConnectionInfo()
void Connection_BB::GetConnectionInfo () const
Print information about connection on screen.
Definition at line 399 of file BulkConn.cpp.
{
    for (OCP_USI i = 0; i < numBulk; i++) {
        cout << "(" << i << ")"
             << "\t";
        for (auto v : neighbor[i]) {
            cout << v << "\t";
        }
        cout << "[" << selfPtr[i] << "]";
        cout << "\t" << neighborNum[i];
        cout << "\n";
    }
    for (OCP_USI i = 0; i < numConn; i++) {
        cout << iteratorConn[i].BId << "\t" << iteratorConn[i].EId << "\n";
    }
}
InitAssembleMat()
template<typename T > void Connection_BB::InitAssembleMat (Solver< T > & mySolver) const
Setup sparsity pattern of Matrix, it should be called before every time the linear system setups. actually, part from wells is neglect, which is much less than bulks.
Definition at line 128 of file BulkConn.hpp.
{
    mySolver.dim = numBulk;
    for (OCP_USI n = 0; n < numBulk; n++) {
        mySolver.colId[n].assign(neighbor[n].begin(), neighbor[n].end());
        mySolver.diagPtr[n] = selfPtr[n];
    }
}
InitSize()
void Connection_BB::InitSize (const Bulk & myBulk)
initialize the size of variable related to neighbor.
Definition at line 28 of file BulkConn.cpp.
{
    numConn = 0;
    numBulk = myBulk.numBulk;
    neighbor.resize(numBulk);
    selfPtr.resize(numBulk);
    neighborNum.resize(numBulk);
}
MassConserve()
void Connection_BB::MassConserve (Bulk & myBulk, const OCP_DBL & dt) const
update moles of component in each bulk according to mass conserve equations at current timestep.
Definition at line 284 of file BulkConn.cpp.
{
    USI np = myBulk.numPhase;
    USI nc = myBulk.numCom;
    for (OCP_USI c = 0; c < numConn; c++) {
        OCP_USI bId = iteratorConn[c].BId;
        OCP_USI eId = iteratorConn[c].EId;
        for (USI j = 0; j < np; j++) {
            OCP_USI uId = upblock[c * np + j];
            if (!myBulk.phaseExist[uId * np + j]) continue;
            OCP_USI uId_np_j      = uId * np + j;
            OCP_DBL phaseVelocity = upblock_Velocity[c * np + j];
            for (USI i = 0; i < nc; i++) {
                OCP_DBL dNi = dt * phaseVelocity * myBulk.xi[uId_np_j] *
                              myBulk.cij[uId_np_j * nc + i];
                myBulk.Ni[eId * nc + i] += dNi;
                myBulk.Ni[bId * nc + i] -= dNi;
            }
        }
    }
}
Setup()
void Connection_BB::Setup (const Grid & myGrid, const Bulk & myBulk)
Setup active connections and calculate necessary property from Grid and Bulk. It should be called after Grid and Bulk Setup.
Definition at line 20 of file BulkConn.cpp.
{
    InitSize(myBulk);
    CalConn(myGrid, myBulk.numPhase);
    CalIteratorConn();
    CalArea(myGrid, myBulk);
}
References CalArea(), CalConn(), CalIteratorConn(), and InitSize().
Friends And Related Function Documentation
Solver< OCP_DBL >
friend class Solver< OCP_DBL > friend
Definition at line 39 of file BulkConn.hpp.
The documentation for this class was generated from the following files:
BulkConn.hpp
BulkConn.cpp