OpenCAEPoro: LinearSystem Class Reference
LinearSystem Class Reference
Linear solvers for discrete systems.
#include <LinearSystem.hpp>
Public Member Functions
void AllocateRowMem (const OCP_USI &dimMax, const USI &nb)
Allocate memory for linear system with max possible number of rows.
void AllocateColMem ()
Allocate memory for each matrix row with max possible number of columns.
void AllocateColMem (const OCP_USI &colnum)
Allocate memory for each matrix row with a constant columns.
void EnlargeRowCap (const OCP_USI &row, const USI &n)
Enlarge row capacity.
void AssembleRhs (const vector< OCP_DBL > &rhs)
Assign Rhs — used for FIM now.
void ClearData ()
Clear the internal matrix data for scalar-value problems.
vector< OCP_DBL > & GetSolution ()
Return the solution.
void CheckEquation () const
Check whether NAN or INF occurs in equations, used in debug mode.
void CheckSolution () const
Check whether NAN or INF occurs in solutions, used in debug mode.
void OutputLinearSystem (const string &fileA, const string &fileb) const
Output the mat and rhs to fileA and fileb. // TODO: output to some obj?
void OutputSolution (const string &filename) const
Output the solution to a disk file name.
void SetupLinearSolver (const USI &i, const string &dir, const string &file)
Setup LinearSolver.
void AssembleMatLinearSolver ()
Assemble Mat for Linear Solver.
OCP_INT Solve ()
Solve the Linear System.
USI GetNumIters ()
Return the Max Iters.
Friends
class OpenCAEPoro
class BulkConn
class Well
Detailed Description
Linear solvers for discrete systems.
Definition at line 30 of file LinearSystem.hpp.
Member Function Documentation
AllocateColMem() [1/2]
void LinearSystem::AllocateColMem ()
Allocate memory for each matrix row with max possible number of columns.
Definition at line 27 of file LinearSystem.cpp.
{
    for (OCP_USI n = 0; n < maxDim; n++) {
        colId[n].reserve(rowCapacity[n]);
        val[n].reserve(rowCapacity[n] * blockSize);
    }
}
AllocateColMem() [2/2]
void LinearSystem::AllocateColMem (const OCP_USI & colnum)
Allocate memory for each matrix row with a constant columns.
Definition at line 35 of file LinearSystem.cpp.
{
    for (OCP_USI n = 0; n < maxDim; n++) {
        rowCapacity[n] = colnum;
        colId[n].reserve(colnum);
        val[n].reserve(colnum * blockSize);
    }
}
AllocateRowMem()
void LinearSystem::AllocateRowMem (const OCP_USI & dimMax, const USI & nb)
Allocate memory for linear system with max possible number of rows.
Definition at line 13 of file LinearSystem.cpp.
{
    blockSize = nb * nb;
    blockDim  = nb;
    maxDim    = dimMax;
    rowCapacity.resize(maxDim);
    colId.resize(maxDim);
    val.resize(maxDim);
    diagPtr.resize(maxDim);
    diagVal.resize(maxDim * blockSize);
    b.resize(maxDim * blockDim);
    u.resize(maxDim * blockDim);
}
AssembleMatLinearSolver()
void LinearSystem::AssembleMatLinearSolver () inline
Assemble Mat for Linear Solver.
Definition at line 66 of file LinearSystem.hpp.
{ LS->AssembleMat(colId, val, dim, blockDim, b, u); }
References LinearSolver::AssembleMat().
AssembleRhs()
void LinearSystem::AssembleRhs (const vector< OCP_DBL > & rhs)
Assign Rhs — used for FIM now.
Definition at line 57 of file LinearSystem.cpp.
{
    OCP_USI nrow = dim * blockDim;
    for (OCP_USI i = 0; i < nrow; i++) {
        b[i] += rhs[i];
    }
}
CheckEquation()
void LinearSystem::CheckEquation () const
Check whether NAN or INF occurs in equations, used in debug mode.
Definition at line 123 of file LinearSystem.cpp.
{
    // check A
    for (OCP_USI n = 0; n < dim; n++) {
        for (auto v : val[n]) {
            if (!isfinite(v)) {
                OCP_ABORT("NAN or INF in MAT");
            }
        }
    }
    // check b
    OCP_USI len = dim * blockDim;
    for (OCP_USI n = 0; n < len; n++) {
        if (!isfinite(b[n])) {
            OCP_ABORT("NAN or INF in rhs");
        }
    }
}
References OCP_ABORT.
CheckSolution()
void LinearSystem::CheckSolution () const
Check whether NAN or INF occurs in solutions, used in debug mode.
Definition at line 142 of file LinearSystem.cpp.
{
    OCP_USI len = dim * blockDim;
    for (OCP_USI n = 0; n < len; n++) {
        if (!isfinite(u[n])) {
            OCP_ABORT("NAN or INF in u");
        }
    }
}
References OCP_ABORT.
ClearData()
void LinearSystem::ClearData ()
Clear the internal matrix data for scalar-value problems.
Definition at line 44 of file LinearSystem.cpp.
{
    for (OCP_USI i = 0; i < maxDim; i++) {
        colId[i].clear(); // actually, only parts of bulks needs to be clear
        val[i].clear();
    }
    // diagPtr.assign(maxDim, 0);
    fill(diagVal.begin(), diagVal.end(), 0.0);
    fill(b.begin(), b.end(), 0.0);
    // In fact, for linear system the current solution is a good initial solution for
    // next step, so u will not be set to zero. u.assign(maxDim, 0);
}
EnlargeRowCap()
void LinearSystem::EnlargeRowCap (const OCP_USI & row, const USI & n) inline
Enlarge row capacity.
Definition at line 44 of file LinearSystem.hpp.
{ rowCapacity[row] += n; }
GetNumIters()
USI LinearSystem::GetNumIters () inline
Return the Max Iters.
Definition at line 71 of file LinearSystem.hpp.
{ return LS->GetNumIters(); }
References LinearSolver::GetNumIters().
GetSolution()
vector< OCP_DBL > & LinearSystem::GetSolution () inline
Return the solution.
Definition at line 52 of file LinearSystem.hpp.
{ return u; }
OutputLinearSystem()
void LinearSystem::OutputLinearSystem (const string & fileA, const string & fileb) const
Output the mat and rhs to fileA and fileb. // TODO: output to some obj?
Definition at line 65 of file LinearSystem.cpp.
{
    string FileA = solveDir + fileA;
    string Fileb = solveDir + fileb;
    // out A
    // csr or bsr
    ofstream outA(FileA);
    if (!outA.is_open()) cout << "Can not open " << FileA << endl;
    outA << dim << endl;
    if (blockDim != 1) {
        outA << blockDim << endl;
    }
    // IA
    OCP_USI rowId = 1;
    for (OCP_USI i = 0; i < dim; i++) {
        outA << rowId << endl;
        rowId += colId[i].size();
    }
    outA << rowId << endl;
    // JA
    USI rowSize = 0;
    for (OCP_USI i = 0; i < dim; i++) {
        rowSize = colId[i].size();
        for (USI j = 0; j < rowSize; j++) {
            outA << colId[i][j] + 1 << endl;
        }
    }
    // val
    for (OCP_USI i = 0; i < dim; i++) {
        rowSize = val[i].size();
        for (USI j = 0; j < rowSize; j++) {
            outA << val[i][j] << endl;
        }
    }
    outA.close();
    // out b
    OCP_USI  nRow = dim * blockDim;
    ofstream outb(Fileb);
    if (!outb.is_open()) cout << "Can not open " << Fileb << endl;
    outb << dim << endl;
    for (OCP_USI i = 0; i < nRow; i++) {
        outb << b[i] << endl;
    }
}
OutputSolution()
void LinearSystem::OutputSolution (const string & filename) const
Output the solution to a disk file name.
Definition at line 112 of file LinearSystem.cpp.
{
    string   FileU = solveDir + fileU;
    ofstream outu(FileU);
    if (!outu.is_open()) cout << "Can not open " << FileU << endl;
    outu << dim << endl;
    OCP_USI nrow = dim * blockDim;
    for (OCP_USI i = 0; i < nrow; i++) outu << u[i] << endl;
    outu.close();
}
SetupLinearSolver()
void LinearSystem::SetupLinearSolver (const USI & i, const string & dir, const string & file)
Setup LinearSolver.
Definition at line 153 of file LinearSystem.cpp.
{
    solveDir = dir;
    switch (i) {
        case SCALARFASP:
            // Fasp
            LS = new ScalarFaspSolver;
            break;
        case VECTORFASP:
            // Blcok Fasp
            LS = new VectorFaspSolver;
            break;
        default:
            OCP_ABORT("Wrong Linear Solver type!");
            break;
    }
    LS->SetupParam(dir, file);
    LS->Allocate(rowCapacity, maxDim, blockDim);
}
References LinearSolver::Allocate(), OCP_ABORT, SCALARFASP, LinearSolver::SetupParam(), and VECTORFASP.
Solve()
OCP_INT LinearSystem::Solve () inline
Solve the Linear System.
Definition at line 68 of file LinearSystem.hpp.
{ return LS->Solve(); }
References LinearSolver::Solve().
Friends And Related Function Documentation
BulkConn
friend class BulkConn friend
Definition at line 33 of file LinearSystem.hpp.
OpenCAEPoro
friend class OpenCAEPoro friend
Definition at line 32 of file LinearSystem.hpp.
Well
friend class Well friend
Definition at line 34 of file LinearSystem.hpp.
The documentation for this class was generated from the following files:
LinearSystem.hpp
LinearSystem.cpp