OpenCAEPoro: Reservoir Class Reference
Reservoir Class Reference
#include <Reservoir.hpp>
Public Member Functions
void InputParam (ParamRead &param)
void Setup ()
Setup static information for reservoir with input params.
void ApplyControl (const USI &i)
Apply the control of ith critical time point.
void PrepareWell ()
Calculate Well Properties at the beginning of each time step.
void CalWellFlux ()
Calculate Flux between Bulk and Wells.
void CalWellTrans ()
Calculate Trans of Wells.
void CalVpore ()
Calculate pore of Bulks.
void CalKrPc ()
Calculate Relative Permeability and Capillary for each Bulk.
void CalMaxChange ()
Calculate Maximum Change of some reference variables for IMPEC.
void CalIPRT (const OCP_DBL &dt)
Calculate num of Injection, Production.
OCP_INT CheckP (const bool &bulkCheck=true, const bool &wellCheck=true)
Check if abnormal Pressure occurs.
bool CheckNi ()
Check if abnormal Pressure occurs.
bool CheckVe (const OCP_DBL &Vlim) const
Check error between Fluids and Pores.
OCP_USI GetBulkNum () const
Return the num of Bulk.
OCP_USI GetMaxFIMBulk () const
Return MaxNUMFIMBulk.
USI GetWellNum () const
Return the num of Well.
USI GetComNum () const
Return the num of Components.
void SetupWellBulk ()
void GetNTQT (const OCP_DBL &dt)
void AllocateAuxIMPEC ()
Allocate memory for auxiliary variables used for IMPEC.
void InitIMPEC ()
Initialize the properties of Reservoir for IMPEC.
OCP_DBL CalCFL (const OCP_DBL &dt)
Calcluate the CFL number, including bulks and wells for IMPEC.
void CalFLuxIMPEC ()
Calculate flux between bulks, bulks and wells.
void CalConnFluxIMPEC ()
Calculate flux between bulks.
void MassConseveIMPEC (const OCP_DBL &dt)
Calculate Ni according to Flux.
void CalFlashIMPEC ()
Calculate Flash For IMPEC.
void UpdateLastStepIMPEC ()
Update value of last step for IMPEC.
void AllocateMatIMPEC (LinearSystem &myLS) const
Allocate Maxmimum memory for internal Matirx for IMPEC.
void AssembleMatIMPEC (LinearSystem &myLS, const OCP_DBL &dt) const
Assemble Matrix for IMPEC.
void GetSolutionIMPEC (const vector< OCP_DBL > &u)
Return the Solution to Reservoir Pressure for IMPEC.
void ResetWellIMPEC ()
Reset Well for IMPEC.
void ResetVal01IMPEC ()
Reset Capillary Pressure, Flux for IMPEC.
void ResetVal02IMPEC ()
Reset Capillary Pressure, Moles of Componnets, Flux for IMPEC.
void ResetVal03IMPEC ()
void AllocateAuxFIM ()
Allocate memory for auxiliary variables used for FIM.
void InitFIM ()
Initialize the properties of Reservoir for FIM.
void CalFlashDerivFIM ()
Calculate Flash for FIM, some derivatives are needed.
void CalFlashDerivFIM_n ()
void CalKrPcDerivFIM ()
Calculate Relative Permeability and Capillary and some derivatives for each Bulk.
void UpdateLastStepFIM ()
Update value of last step for FIM.
void AllocateMatFIM (LinearSystem &myLS) const
Allocate Maxmimum memory for internal Matirx for FIM.
void AssembleMatFIM (LinearSystem &myLS, const OCP_DBL &dt) const
Assemble Matrix for FIM.
void AssembleMatFIM_n (LinearSystem &myLS, const OCP_DBL &dt) const
void GetSolutionFIM (const vector< OCP_DBL > &u, const OCP_DBL &dPmax, const OCP_DBL &dSmax)
void GetSolutionFIM_n (const vector< OCP_DBL > &u, const OCP_DBL &dPmax, const OCP_DBL &dSmax)
void GetSolution01FIM (const vector< OCP_DBL > &u)
void CalResFIM (ResFIM &resFIM, const OCP_DBL &dt)
Calculate the Resiual for FIM, it's also RHS of Linear System.
void ResetFIM (const bool &flag)
Reset FIM.
OCP_DBL GetNRdPmax ()
Return NRdPmax.
OCP_DBL GetNRdSmax (OCP_USI &index)
Return NRdSmax.
OCP_DBL GetNRdNmax ()
Return NRdNmax.
OCP_DBL GetNRdSmaxP ()
Return NRdSmaxP.
void PrintSolFIM (const string &outfile) const
void ShowRes (const vector< OCP_DBL > &res) const
void AllocateAuxAIMt ()
Allocate memory for auxiliary variables used for AIMt.
void AllocateMatAIMt (LinearSystem &myLS) const
Allocate Maxmimum memory for internal Matirx for local FIM.
void SetupFIMBulk (const bool &NRflag=false)
Setup FIMBulk.
void AddFIMBulk ()
void SetupFIMBulkBoundAIMs ()
void CalFlashDerivAIM (const bool &IfAIMs)
Calculate Flash for local FIM, some derivatives are needed.
void CalKrPcDerivAIM (const bool &IfAIMs)
Calculate Relative Permeability and Capillary and some derivatives for each Bulk.
void CalResAIMt (ResFIM &resFIM, const OCP_DBL &dt)
Calculate the Resiual for local FIM, it's also RHS of Linear System.
void AssembleMatAIMt (LinearSystem &myLS, const OCP_DBL &dt) const
Assemble Matrix for AIMt -— local FIM here.
void GetSolutionAIMt (const vector< OCP_DBL > &u, const OCP_DBL &dPmax, const OCP_DBL &dSmax)
void AllocateAuxAIMs ()
Allocate memory for auxiliary variables used for AIMs.
void CalResAIMs (ResFIM &resFIM, const OCP_DBL &dt)
Calculate the Resiual for AIMs, it's also RHS of Linear System.
void AssembleMatAIMs (LinearSystem &myLS, vector< OCP_DBL > &res, const OCP_DBL &dt) const
Assemble Matrix for AIMs.
void GetSolutionAIMs (const vector< OCP_DBL > &u, const OCP_DBL &dPmax, const OCP_DBL &dSmax)
void ResetValAIM ()
OCP_DBL CalCFLAIM (const OCP_DBL &dt)
void UpdateLastStepAIM ()
Update value of last step for IMPEC.
void AllocateAuxAIMc ()
Allocate memory for auxiliary variables used for FIM.
void AssembleMatAIMc (LinearSystem &myLS, const OCP_DBL &dt) const
Assemble Matrix for AIMc.
void CalResAIMc (ResFIM &resFIM, const OCP_DBL &dt)
Calculate the Resiual for FIM, it's also RHS of Linear System.
void CalFlashAIMc ()
void CalFlashAIMc01 ()
void CalKrPcAIMc ()
void CalFlashDerivAIMc ()
Calculate Flash for local FIM, some derivatives are needed.
void CalKrPcDerivAIMc ()
Calculate Relative Permeability and Capillary and some derivatives for each Bulk.
void GetSolutionAIMc (const vector< OCP_DBL > &u, const OCP_DBL &dPmax, const OCP_DBL &dSmax)
void InitAIMc ()
void UpdatePj ()
Friends
class OCPControl
class Summary
class CriticalInfo
class DetailInfo
class OCP_IMPEC
class OCP_FIM
class OCP_AIMs
class OCP_AIMt
class OCP_AIMc
class Solver
Detailed Description
Reservoir is the core component in our simulator, it contains the all reservoir information, and all operations on it.
Reservoir has four Core components. Grids contains the basic informations of all grids as a database of reservoir. Bulk only stores active grids, which defines the area used for calculation. AllWells contains the well information, it's used to manage operations related to wells. BulkConn contains connections between bulks(active grids).
Definition at line 30 of file Reservoir.hpp.
Member Function Documentation
AddFIMBulk()
void Reservoir::AddFIMBulk () inline
Definition at line 189 of file Reservoir.hpp.
{ conn.AddFIMBulk(bulk); }
AllocateAuxAIMc()
void Reservoir::AllocateAuxAIMc ()
Allocate memory for auxiliary variables used for FIM.
Definition at line 632 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.AllocateAuxFIM();
    bulk.AllocateAuxAIMc();
    conn.AllocateAuxAIMc(bulk.GetPhaseNum());
}
References BulkConn::AllocateAuxAIMc(), Bulk::AllocateAuxFIM(), Bulk::GetPhaseNum(), and OCP_FUNCNAME.
AllocateAuxAIMs()
void Reservoir::AllocateAuxAIMs ()
Allocate memory for auxiliary variables used for AIMs.
Definition at line 560 of file Reservoir.cpp.
{
    bulk.AllocateAuxIMPEC();
    bulk.AllocateWellBulkId(allWells.GetWellPerfNum() * 10);
    bulk.AllocateAuxAIM(1);
    conn.AllocateAuxIMPEC(bulk.GetPhaseNum());
    conn.AllocateAuxAIMt();
}
References Bulk::AllocateAuxAIM(), BulkConn::AllocateAuxAIMt(), Bulk::AllocateAuxIMPEC(), BulkConn::AllocateAuxIMPEC(), Bulk::AllocateWellBulkId(), Bulk::GetPhaseNum(), and AllWells::GetWellPerfNum().
AllocateAuxAIMt()
void Reservoir::AllocateAuxAIMt ()
Allocate memory for auxiliary variables used for AIMt.
Definition at line 499 of file Reservoir.cpp.
{
    bulk.AllocateAuxIMPEC();
    conn.AllocateAuxIMPEC(bulk.GetPhaseNum());
    conn.AllocateAuxAIMt();
    bulk.AllocateWellBulkId(allWells.GetWellPerfNum() * 10);
    bulk.AllocateAuxAIM(0.05);
}
References Bulk::AllocateAuxAIM(), BulkConn::AllocateAuxAIMt(), Bulk::AllocateAuxIMPEC(), BulkConn::AllocateAuxIMPEC(), Bulk::AllocateWellBulkId(), Bulk::GetPhaseNum(), and AllWells::GetWellPerfNum().
AllocateAuxFIM()
void Reservoir::AllocateAuxFIM ()
Allocate memory for auxiliary variables used for FIM.
Definition at line 300 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.AllocateAuxFIM();
    conn.AllocateAuxFIM(bulk.GetPhaseNum());
}
References Bulk::AllocateAuxFIM(), BulkConn::AllocateAuxFIM(), Bulk::GetPhaseNum(), and OCP_FUNCNAME.
AllocateAuxIMPEC()
void Reservoir::AllocateAuxIMPEC ()
Allocate memory for auxiliary variables used for IMPEC.
Definition at line 142 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.AllocateAuxIMPEC();
    conn.AllocateAuxIMPEC(bulk.GetPhaseNum());
}
References Bulk::AllocateAuxIMPEC(), BulkConn::AllocateAuxIMPEC(), Bulk::GetPhaseNum(), and OCP_FUNCNAME.
AllocateMatAIMt()
void Reservoir::AllocateMatAIMt (LinearSystem & myLS) const
Allocate Maxmimum memory for internal Matirx for local FIM.
Definition at line 509 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    myLS.AllocateRowMem(bulk.GetMaxFIMBulk() + allWells.GetWellNum(),
        bulk.GetComNum() + 1);
    myLS.AllocateColMem(10);
}
References LinearSystem::AllocateColMem(), LinearSystem::AllocateRowMem(), Bulk::GetComNum(), AllWells::GetWellNum(), and OCP_FUNCNAME.
AllocateMatFIM()
void Reservoir::AllocateMatFIM (LinearSystem & myLS) const
Allocate Maxmimum memory for internal Matirx for FIM.
Definition at line 355 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    myLS.AllocateRowMem(bulk.GetBulkNum() + allWells.GetWellNum(),
                        bulk.GetComNum() + 1);
    conn.AllocateMat(myLS);
    allWells.AllocateMat(myLS, bulk.GetBulkNum());
    myLS.AllocateColMem();
}
References LinearSystem::AllocateColMem(), BulkConn::AllocateMat(), AllWells::AllocateMat(), LinearSystem::AllocateRowMem(), Bulk::GetBulkNum(), Bulk::GetComNum(), AllWells::GetWellNum(), and OCP_FUNCNAME.
AllocateMatIMPEC()
void Reservoir::AllocateMatIMPEC (LinearSystem & myLS) const
Allocate Maxmimum memory for internal Matirx for IMPEC.
Definition at line 222 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    myLS.AllocateRowMem(bulk.GetBulkNum() + allWells.GetWellNum(), 1);
    conn.AllocateMat(myLS);
    allWells.AllocateMat(myLS, bulk.GetBulkNum());
    myLS.AllocateColMem();
}
References LinearSystem::AllocateColMem(), BulkConn::AllocateMat(), AllWells::AllocateMat(), LinearSystem::AllocateRowMem(), Bulk::GetBulkNum(), AllWells::GetWellNum(), and OCP_FUNCNAME.
ApplyControl()
void Reservoir::ApplyControl (const USI & i)
Apply the control of ith critical time point.
Definition at line 38 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    allWells.ApplyControl(i);
    allWells.SetupWellGroup(bulk);
}
References AllWells::ApplyControl(), OCP_FUNCNAME, and AllWells::SetupWellGroup().
AssembleMatAIMc()
void Reservoir::AssembleMatAIMc (LinearSystem & myLS, const OCP_DBL & dt) const
Assemble Matrix for AIMc.
Definition at line 641 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    conn.SetupMatSparsity(myLS);
    conn.AssembleMat_AIMc01(myLS, bulk, dt);
    allWells.AssemblaMatFIM(myLS, bulk, dt);
}
References AllWells::AssemblaMatFIM(), OCP_FUNCNAME, and BulkConn::SetupMatSparsity().
AssembleMatAIMs()
void Reservoir::AssembleMatAIMs (LinearSystem & myLS, vector< OCP_DBL > & res, const OCP_DBL & dt) const
Assemble Matrix for AIMs.
Definition at line 583 of file Reservoir.cpp.
{
    conn.SetupMatSparsity(myLS);
    conn.AssembleMat_AIMs(myLS, res, bulk, dt);
    allWells.AssemblaMatAIMs(myLS, bulk, dt);
}
References AllWells::AssemblaMatAIMs(), BulkConn::AssembleMat_AIMs(), and BulkConn::SetupMatSparsity().
AssembleMatAIMt()
void Reservoir::AssembleMatAIMt (LinearSystem & myLS, const OCP_DBL & dt) const
Assemble Matrix for AIMt -— local FIM here.
Definition at line 545 of file Reservoir.cpp.
{
    conn.SetupMatSparsityAIMt(myLS, bulk);
    conn.AssembleMat_AIMt(myLS, bulk, dt);
    allWells.AssemblaMatAIMt(myLS, bulk, dt);
}
References AllWells::AssemblaMatAIMt(), BulkConn::AssembleMat_AIMt(), and BulkConn::SetupMatSparsityAIMt().
AssembleMatFIM()
void Reservoir::AssembleMatFIM (LinearSystem & myLS, const OCP_DBL & dt) const
Assemble Matrix for FIM.
Definition at line 366 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    conn.SetupMatSparsity(myLS);
#ifdef OCP_NEW_FIM
    conn.AssembleMat_FIM_new(myLS, bulk, dt);
    allWells.AssemblaMatFIM_new(myLS, bulk, dt);
#else
    conn.AssembleMat_FIM(myLS, bulk, dt);
    allWells.AssemblaMatFIM(myLS, bulk, dt);
#endif // OCP_NEW_FIM
}
References AllWells::AssemblaMatFIM(), AllWells::AssemblaMatFIM_new(), BulkConn::AssembleMat_FIM(), BulkConn::AssembleMat_FIM_new(), OCP_FUNCNAME, and BulkConn::SetupMatSparsity().
AssembleMatFIM_n()
void Reservoir::AssembleMatFIM_n (LinearSystem & myLS, const OCP_DBL & dt) const
Definition at line 382 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    conn.SetupMatSparsity(myLS);
    conn.AssembleMat_FIM_new_n(myLS, bulk, dt);
    allWells.AssemblaMatFIM_new_n(myLS, bulk, dt);
}
AssembleMatIMPEC()
void Reservoir::AssembleMatIMPEC (LinearSystem & myLS, const OCP_DBL & dt) const
Assemble Matrix for IMPEC.
Definition at line 232 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    conn.SetupMatSparsity(myLS);
    conn.AssembleMatIMPEC(myLS, bulk, dt);
    allWells.AssemblaMatIMPEC(myLS, bulk, dt);
}
References AllWells::AssemblaMatIMPEC(), BulkConn::AssembleMatIMPEC(), OCP_FUNCNAME, and BulkConn::SetupMatSparsity().
CalCFL()
OCP_DBL Reservoir::CalCFL (const OCP_DBL & dt)
Calcluate the CFL number, including bulks and wells for IMPEC.
Definition at line 170 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.SetCFL2Zero();
    conn.CalCFL(bulk, dt);
    allWells.CalCFL(bulk, dt);
    cfl = bulk.CalCFL();
    return cfl;
}
References Bulk::CalCFL(), AllWells::CalCFL(), BulkConn::CalCFL(), OCP_FUNCNAME, and Bulk::SetCFL2Zero().
CalCFLAIM()
OCP_DBL Reservoir::CalCFLAIM (const OCP_DBL & dt)
Definition at line 611 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.SetCFL2Zero();
    conn.CalCFL(bulk, dt);
    cfl = bulk.CalCFL();
    return cfl;
}
CalConnFluxIMPEC()
void Reservoir::CalConnFluxIMPEC ()
Calculate flux between bulks.
Definition at line 190 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    conn.CalFluxIMPEC(bulk);
}
References BulkConn::CalFluxIMPEC(), and OCP_FUNCNAME.
CalFlashAIMc()
void Reservoir::CalFlashAIMc ()
Definition at line 664 of file Reservoir.cpp.
{
    bulk.FlashAIMc();
}
CalFlashAIMc01()
void Reservoir::CalFlashAIMc01 ()
Definition at line 669 of file Reservoir.cpp.
{
    bulk.FlashAIMc01();
}
CalFlashDerivAIM()
void Reservoir::CalFlashDerivAIM (const bool & IfAIMs)
Calculate Flash for local FIM, some derivatives are needed.
Definition at line 519 of file Reservoir.cpp.
{
    bulk.FlashDerivAIM(IfAIMs);
}
References Bulk::FlashDerivAIM().
CalFlashDerivAIMc()
void Reservoir::CalFlashDerivAIMc ()
Calculate Flash for local FIM, some derivatives are needed.
Definition at line 681 of file Reservoir.cpp.
{
    bulk.FlashDerivAIMc();
}
References Bulk::FlashDerivAIMc().
CalFlashDerivFIM()
void Reservoir::CalFlashDerivFIM ()
Calculate Flash for FIM, some derivatives are needed.
Definition at line 326 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.FlashDeriv();
}
References Bulk::FlashDeriv(), and OCP_FUNCNAME.
CalFlashDerivFIM_n()
void Reservoir::CalFlashDerivFIM_n ()
Definition at line 333 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.FlashDeriv_n();
}
CalFlashIMPEC()
void Reservoir::CalFlashIMPEC ()
Calculate Flash For IMPEC.
Definition at line 205 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.Flash();
}
References Bulk::Flash(), and OCP_FUNCNAME.
CalFLuxIMPEC()
void Reservoir::CalFLuxIMPEC ()
Calculate flux between bulks, bulks and wells.
Definition at line 182 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    conn.CalFluxIMPEC(bulk);
    allWells.CalFlux(bulk);
}
References AllWells::CalFlux(), BulkConn::CalFluxIMPEC(), and OCP_FUNCNAME.
CalIPRT()
void Reservoir::CalIPRT (const OCP_DBL & dt)
Calculate num of Injection, Production.
Definition at line 89 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    // Calculate injection / production rate for current step
    allWells.CalIPRT(bulk, dt);
    // Calculate Reinjection fluid for next step
    allWells.CalReInjFluid(bulk);
}
References AllWells::CalIPRT(), AllWells::CalReInjFluid(), and OCP_FUNCNAME.
CalKrPc()
void Reservoir::CalKrPc ()
Calculate Relative Permeability and Capillary for each Bulk.
Definition at line 74 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.CalKrPc();
}
References Bulk::CalKrPc(), and OCP_FUNCNAME.
CalKrPcAIMc()
void Reservoir::CalKrPcAIMc ()
Definition at line 674 of file Reservoir.cpp.
{
    bulk.CalKrPcAIMc();
}
CalKrPcDerivAIM()
void Reservoir::CalKrPcDerivAIM (const bool & IfAIMs)
Calculate Relative Permeability and Capillary and some derivatives for each Bulk.
Definition at line 525 of file Reservoir.cpp.
{
    bulk.CalKrPcDerivAIM(IfAIMs);
}
References Bulk::CalKrPcDerivAIM().
CalKrPcDerivAIMc()
void Reservoir::CalKrPcDerivAIMc ()
Calculate Relative Permeability and Capillary and some derivatives for each Bulk.
Definition at line 688 of file Reservoir.cpp.
{
    bulk.CalKrPcDerivAIMc();
}
References Bulk::CalKrPcDerivAIMc().
CalKrPcDerivFIM()
void Reservoir::CalKrPcDerivFIM ()
Calculate Relative Permeability and Capillary and some derivatives for each Bulk.
Definition at line 340 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.CalKrPcDeriv();
}
References Bulk::CalKrPcDeriv(), and OCP_FUNCNAME.
CalMaxChange()
void Reservoir::CalMaxChange ()
Calculate Maximum Change of some reference variables for IMPEC.
Definition at line 81 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.CalMaxChange();
    allWells.CalMaxBHPChange();
}
References Bulk::CalMaxChange(), and OCP_FUNCNAME.
CalResAIMc()
void Reservoir::CalResAIMc (ResFIM & resFIM, const OCP_DBL & dt)
Calculate the Resiual for FIM, it's also RHS of Linear System.
Definition at line 650 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    // Initialize
    resFIM.SetZero();
    // Bulk to Bulk
    conn.CalResAIMc(resFIM.res, bulk, dt);
    // Well to Bulk
    allWells.CalResFIM(resFIM, bulk, dt);
    // Calculate RelRes
    bulk.CalRelResFIM(resFIM);
    Dscalar(resFIM.res.size(), -1, resFIM.res.data());
}
References Bulk::CalRelResFIM(), BulkConn::CalResAIMc(), AllWells::CalResFIM(), Dscalar(), and OCP_FUNCNAME.
CalResAIMs()
void Reservoir::CalResAIMs (ResFIM & resFIM, const OCP_DBL & dt)
Calculate the Resiual for AIMs, it's also RHS of Linear System.
Definition at line 570 of file Reservoir.cpp.
{
    // Initialize
    resFIM.SetZero();
    // Bulk to Bulk
    conn.CalResAIMs(resFIM.res, bulk, dt);
    // Well to Bulk
    allWells.CalResFIM(resFIM, bulk, dt);
    // Calculate RelRes
    bulk.CalRelResAIMs(resFIM);
    Dscalar(resFIM.res.size(), -1, resFIM.res.data());
}
References Bulk::CalRelResAIMs(), BulkConn::CalResAIMs(), AllWells::CalResFIM(), and Dscalar().
CalResAIMt()
void Reservoir::CalResAIMt (ResFIM & resFIM, const OCP_DBL & dt)
Calculate the Resiual for local FIM, it's also RHS of Linear System.
Definition at line 531 of file Reservoir.cpp.
{
    // Initialize
    resFIM.SetZero();
    // Bulk to Bulk
    conn.CalResAIMt(resFIM.res, bulk, dt);
    // Well to Bulk
    allWells.CalResAIMt(resFIM, bulk, dt);
    // Calculate RelRes
    bulk.CalRelResAIMt(resFIM);
    Dscalar(resFIM.res.size(), -1, resFIM.res.data());
}
References Bulk::CalRelResAIMt(), AllWells::CalResAIMt(), BulkConn::CalResAIMt(), and Dscalar().
CalResFIM()
void Reservoir::CalResFIM (ResFIM & resFIM, const OCP_DBL & dt)
Calculate the Resiual for FIM, it's also RHS of Linear System.
Definition at line 416 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    // Initialize
    resFIM.SetZero();
    // Bulk to Bulk
    conn.CalResFIM(resFIM.res, bulk, dt);
    // Well to Bulk
    allWells.CalResFIM(resFIM, bulk, dt);
    // Calculate RelRes
    bulk.CalRelResFIM(resFIM);
    Dscalar(resFIM.res.size(), -1.0, resFIM.res.data());
    // Calculate Res2 and ResMax
    // OCP_DBL resmax = 0;
    // OCP_USI maxId = 0;
    // OCP_DBL res2 = 0;
    // for (OCP_USI i = 0; i < resFIM.res.size(); i++) {
    //    res2 += pow(resFIM.res[i], 2);
    //    if (resmax < fabs(resFIM.res[i])) {
    //        resmax = fabs(resFIM.res[i]);
    //        maxId = i;
    //    }
    //}
    // cout << "Res2  " << pow(res2 / resFIM.res.size(), 0.5) << "     "
    //    << resFIM.res.size() << endl;
    // cout << "ResMax   " << resmax << "   " << maxId << endl;
    // cout << "BHP   \n";
    // for (USI w = 0; w < allWells.numWell; w++) {
    //    cout << allWells.GetWBHP(w) << "   ";
    //    for (USI p = 0; p < allWells.GetWellPerfNum(w); p++) {
    //        cout << allWells.wells[w].GetPerfPre(p) << "   ";
    //    }
    //}
    // cout << endl;
}
References Bulk::CalRelResFIM(), AllWells::CalResFIM(), BulkConn::CalResFIM(), Dscalar(), and OCP_FUNCNAME.
CalVpore()
void Reservoir::CalVpore ()
Calculate pore of Bulks.
Definition at line 67 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.CalVpore();
}
References Bulk::CalVpore(), and OCP_FUNCNAME.
CalWellFlux()
void Reservoir::CalWellFlux ()
Calculate Flux between Bulk and Wells.
Definition at line 53 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    allWells.CalFlux(bulk);
}
References AllWells::CalFlux(), and OCP_FUNCNAME.
CalWellTrans()
void Reservoir::CalWellTrans ()
Calculate Trans of Wells.
Definition at line 60 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    allWells.CalTrans(bulk);
}
References AllWells::CalTrans(), and OCP_FUNCNAME.
CheckNi()
bool Reservoir::CheckNi ()
Check if abnormal Pressure occurs.
Definition at line 117 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    return bulk.CheckNi();
}
References Bulk::CheckNi(), and OCP_FUNCNAME.
CheckP()
OCP_INT Reservoir::CheckP (const bool & bulkCheck = true, const bool & wellCheck = true)
Check if abnormal Pressure occurs.
Definition at line 98 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    if (bulkCheck) {
        if (!bulk.CheckP()) {
            return 1;
        }
    }
    if (wellCheck) {
        OCP_INT flag = 0;
        flag         = allWells.CheckP(bulk);
        return flag;
    }
    return 0;
}
References Bulk::CheckP(), AllWells::CheckP(), and OCP_FUNCNAME.
CheckVe()
bool Reservoir::CheckVe (const OCP_DBL & Vlim) const
Check error between Fluids and Pores.
Definition at line 124 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    return bulk.CheckVe(Vlim);
}
References Bulk::CheckVe(), and OCP_FUNCNAME.
GetBulkNum()
OCP_USI Reservoir::GetBulkNum () const inline
Return the num of Bulk.
Definition at line 78 of file Reservoir.hpp.
{ return bulk.GetBulkNum(); }
References Bulk::GetBulkNum().
GetComNum()
USI Reservoir::GetComNum () const inline
Return the num of Components.
Definition at line 84 of file Reservoir.hpp.
{ return bulk.GetComNum(); }
References Bulk::GetComNum().
GetMaxFIMBulk()
OCP_USI Reservoir::GetMaxFIMBulk () const inline
Return MaxNUMFIMBulk.
Definition at line 80 of file Reservoir.hpp.
{ return bulk.GetMaxFIMBulk(); }
GetNRdNmax()
OCP_DBL Reservoir::GetNRdNmax () inline
Return NRdNmax.
Definition at line 172 of file Reservoir.hpp.
{ return bulk.GetNRdNmax(); }
GetNRdPmax()
OCP_DBL Reservoir::GetNRdPmax () inline
Return NRdPmax.
Definition at line 168 of file Reservoir.hpp.
{ return bulk.GetNRdPmax(); }
References Bulk::GetNRdPmax().
GetNRdSmax()
OCP_DBL Reservoir::GetNRdSmax (OCP_USI & index) inline
Return NRdSmax.
Definition at line 170 of file Reservoir.hpp.
{ return bulk.CalNRdSmax(index); }
References Bulk::CalNRdSmax().
GetNRdSmaxP()
OCP_DBL Reservoir::GetNRdSmaxP () inline
Return NRdSmaxP.
Definition at line 174 of file Reservoir.hpp.
{ return bulk.GetNRdSmaxP(); }
References Bulk::GetNRdSmaxP().
GetNTQT()
void Reservoir::GetNTQT (const OCP_DBL & dt)
Definition at line 131 of file Reservoir.cpp.
{
    OCP_DBL NT = bulk.CalNT();
    OCP_DBL QT = allWells.CalWellQT() * dt;
    cout << setprecision(8) << NT << "   " << QT << endl;
}
GetSolution01FIM()
void Reservoir::GetSolution01FIM (const vector< OCP_DBL > & u)
Definition at line 410 of file Reservoir.cpp.
{
    bulk.GetSol01FIM(u);
    allWells.GetSol01FIM(u, bulk.GetBulkNum(), bulk.GetComNum() + 1, 1);
}
GetSolutionAIMc()
void Reservoir::GetSolutionAIMc (const vector< OCP_DBL > & u, const OCP_DBL & dPmax, const OCP_DBL & dSmax)
Definition at line 693 of file Reservoir.cpp.
{
    bulk.GetSolAIMc01(u, dPmax, dSmax);
    allWells.GetSolFIM(u, bulk.GetBulkNum(), bulk.GetComNum() + 1);
}
GetSolutionAIMs()
void Reservoir::GetSolutionAIMs (const vector< OCP_DBL > & u, const OCP_DBL & dPmax, const OCP_DBL & dSmax)
Definition at line 590 of file Reservoir.cpp.
{
    bulk.GetSolAIMs(u, dPmax, dSmax);
    allWells.GetSolFIM(u, bulk.GetBulkNum(), bulk.GetComNum() + 1);
}
GetSolutionAIMt()
void Reservoir::GetSolutionAIMt (const vector< OCP_DBL > & u, const OCP_DBL & dPmax, const OCP_DBL & dSmax)
Return the Solution to Reservoir Pressure and moles of Components for FIM Exactly, it's a Newton step.
Definition at line 552 of file Reservoir.cpp.
{
    bulk.GetSolAIMt(u, dPmax, dSmax);
    allWells.GetSolAIMt(u, bulk.numFIMBulk, bulk.GetComNum() + 1);
}
References Bulk::GetComNum(), Bulk::GetSolAIMt(), and AllWells::GetSolAIMt().
GetSolutionFIM()
void Reservoir::GetSolutionFIM (const vector< OCP_DBL > & u, const OCP_DBL & dPmax, const OCP_DBL & dSmax)
Return the Solution to Reservoir Pressure and moles of Components for FIM Exactly, it's a Newton step.
Definition at line 391 of file Reservoir.cpp.
{
    bulk.GetSolFIM(u, dPmax, dSmax);
    allWells.GetSolFIM(u, bulk.GetBulkNum(), bulk.GetComNum() + 1);
}
References Bulk::GetBulkNum(), Bulk::GetComNum(), Bulk::GetSolFIM(), and AllWells::GetSolFIM().
GetSolutionFIM_n()
void Reservoir::GetSolutionFIM_n (const vector< OCP_DBL > & u, const OCP_DBL & dPmax, const OCP_DBL & dSmax)
Definition at line 399 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.GetSolFIM_n(u, dPmax, dSmax);
    allWells.GetSolFIM(u, bulk.GetBulkNum(), bulk.GetComNum() + 1);
}
GetSolutionIMPEC()
void Reservoir::GetSolutionIMPEC (const vector< OCP_DBL > & u)
Return the Solution to Reservoir Pressure for IMPEC.
Definition at line 241 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.GetSolIMPEC(u);
    allWells.GetSolIMPEC(u, bulk.GetBulkNum());
}
References Bulk::GetBulkNum(), Bulk::GetSolIMPEC(), AllWells::GetSolIMPEC(), and OCP_FUNCNAME.
GetWellNum()
USI Reservoir::GetWellNum () const inline
Return the num of Well.
Definition at line 82 of file Reservoir.hpp.
{ return allWells.GetWellNum(); }
References AllWells::GetWellNum().
InitAIMc()
void Reservoir::InitAIMc ()
Definition at line 700 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    if (bulk.GetMixMode() == BLKOIL)
        bulk.InitSjPcBo(50);
    else if (bulk.GetMixMode() == EOS_PVTW)
        bulk.InitSjPcComp(50, grid);
    bulk.CalVpore();
    bulk.InitFlash(true);
    bulk.CalKrPc();
    conn.CalFluxFIM(bulk);
    allWells.InitBHP(bulk);
    UpdateLastStepFIM();
}
InitFIM()
void Reservoir::InitFIM ()
Initialize the properties of Reservoir for FIM.
Definition at line 308 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    if (bulk.GetMixMode() == BLKOIL)
        bulk.InitSjPcBo(50);
    else if (bulk.GetMixMode() == EOS_PVTW)
        bulk.InitSjPcComp(50, grid);
    bulk.CalVpore();
    bulk.InitFlash(false);
    bulk.FlashDeriv();
    bulk.CalKrPcDeriv();
    conn.CalFluxFIM(bulk);
    allWells.InitBHP(bulk);
    UpdateLastStepFIM();
}
References BLKOIL, BulkConn::CalFluxFIM(), Bulk::CalKrPcDeriv(), Bulk::CalVpore(), EOS_PVTW, Bulk::FlashDeriv(), Bulk::GetMixMode(), AllWells::InitBHP(), Bulk::InitFlash(), Bulk::InitSjPcBo(), Bulk::InitSjPcComp(), OCP_FUNCNAME, and UpdateLastStepFIM().
InitIMPEC()
void Reservoir::InitIMPEC ()
Initialize the properties of Reservoir for IMPEC.
Definition at line 150 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    if (bulk.GetMixMode() == BLKOIL)
        bulk.InitSjPcBo(50);
    else if (bulk.GetMixMode() == EOS_PVTW)
        bulk.InitSjPcComp(50, grid);
    bulk.CalVpore();
    bulk.InitFlash(true);
    bulk.CalKrPc();
    bulk.UpdateLastStepIMPEC();
    conn.CalFluxIMPEC(bulk);
    conn.UpdateLastStep();
    allWells.InitBHP(bulk);
    allWells.UpdateLastBHP();
}
References BLKOIL, BulkConn::CalFluxIMPEC(), Bulk::CalKrPc(), Bulk::CalVpore(), EOS_PVTW, Bulk::GetMixMode(), AllWells::InitBHP(), Bulk::InitFlash(), Bulk::InitSjPcBo(), Bulk::InitSjPcComp(), OCP_FUNCNAME, BulkConn::UpdateLastStep(), and Bulk::UpdateLastStepIMPEC().
InputParam()
void Reservoir::InputParam (ParamRead & param)
Input param from internal param data structure, which stores the params from input files.
Definition at line 18 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    grid.InputParam(param.paramRs);
    bulk.InputParam(param.paramRs);
    allWells.InputParam(param.paramWell);
}
References Grid::InputParam(), AllWells::InputParam(), Bulk::InputParam(), OCP_FUNCNAME, ParamRead::paramRs, and ParamRead::paramWell.
MassConseveIMPEC()
void Reservoir::MassConseveIMPEC (const OCP_DBL & dt)
Calculate Ni according to Flux.
Definition at line 197 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    conn.MassConserveIMPEC(bulk, dt);
    allWells.MassConserveIMPEC(bulk, dt);
}
References BulkConn::MassConserveIMPEC(), AllWells::MassConserveIMPEC(), and OCP_FUNCNAME.
PrepareWell()
void Reservoir::PrepareWell ()
Calculate Well Properties at the beginning of each time step.
Definition at line 46 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    allWells.PrepareWell(bulk);
}
References OCP_FUNCNAME, and AllWells::PrepareWell().
PrintSolFIM()
void Reservoir::PrintSolFIM (const string & outfile) const
Definition at line 466 of file Reservoir.cpp.
{
    ofstream outu(outfile);
    if (!outu.is_open()) cout << "Can not open " << outfile << endl;
    const OCP_USI nb = bulk.numBulk;
    const OCP_USI nc = bulk.numCom;
    for (OCP_USI n = 0; n < nb; n++) {
        // Pressure
        outu << bulk.P[n] << "\n";
        // Ni
        for (USI i = 0; i < nc; i++) {
            outu << bulk.Ni[n * nc + i] << "\n";
        }
    }
    // Well Pressure
    for (USI w = 0; w < allWells.numWell; w++) {
        outu << allWells.GetWBHP(w) << "\n";
    }
    outu.close();
}
ResetFIM()
void Reservoir::ResetFIM (const bool & flag)
Reset FIM.
Definition at line 453 of file Reservoir.cpp.
{
    bulk.ResetFIM();
    allWells.ResetBHP();
    allWells.CalTrans(bulk);
    allWells.CalFlux(bulk);
    if (flag) {
        allWells.CaldG(bulk);
        allWells.CalFlux(bulk);
    }
}
References AllWells::CaldG(), AllWells::CalFlux(), AllWells::CalTrans(), and Bulk::ResetFIM().
ResetVal01IMPEC()
void Reservoir::ResetVal01IMPEC ()
Reset Capillary Pressure, Flux for IMPEC.
Definition at line 259 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.ResetPj();
    conn.Reset();
}
References OCP_FUNCNAME, BulkConn::Reset(), and Bulk::ResetPj().
ResetVal02IMPEC()
void Reservoir::ResetVal02IMPEC ()
Reset Capillary Pressure, Moles of Componnets, Flux for IMPEC.
Definition at line 266 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.ResetPj();
    bulk.ResetNi();
    conn.Reset();
}
References OCP_FUNCNAME, BulkConn::Reset(), Bulk::ResetNi(), and Bulk::ResetPj().
ResetVal03IMPEC()
void Reservoir::ResetVal03IMPEC ()
Reset Pressure, Capillary Pressure, Moles of components, Flux, Volume of Pores for IMPEC
Definition at line 275 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.ResetphaseNum();
    bulk.ResetminEigenSkip();
    bulk.ResetflagSkip();
    bulk.ResetziSkip();
    bulk.ResetPSkip();
    bulk.ResetKs();
    bulk.ResetPj();
    bulk.ResetNi();
    bulk.ResetNt();
    bulk.ResetFlash();
    bulk.ResetVp();
    conn.Reset();
    // Becareful! if recalculate the flash, result may be different because the initial
    // flash was calculated by InitFlash not Flash.
}
References OCP_FUNCNAME, BulkConn::Reset(), Bulk::ResetFlash(), Bulk::ResetNi(), Bulk::ResetNt(), Bulk::ResetPj(), and Bulk::ResetVp().
ResetValAIM()
void Reservoir::ResetValAIM ()
Definition at line 597 of file Reservoir.cpp.
{
    ResetVal03IMPEC();
    bulk.ResetFIMBulk();
    allWells.ResetBHP();
    allWells.CalTrans(bulk);
    allWells.CalFlux(bulk);
    if (false) {
        allWells.CaldG(bulk);
        allWells.CalFlux(bulk);
    }
}
ResetWellIMPEC()
void Reservoir::ResetWellIMPEC ()
Reset Well for IMPEC.
Definition at line 249 of file Reservoir.cpp.
{
    // allWells.ResetDg();
    allWells.ResetBHP();
    allWells.CalTrans(bulk);
    allWells.CalFlux(bulk);
    allWells.CaldG(bulk);
}
References AllWells::CaldG(), AllWells::CalFlux(), and AllWells::CalTrans().
Setup()
void Reservoir::Setup ()
Setup static information for reservoir with input params.
Definition at line 28 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    grid.Setup();
    bulk.Setup(grid);
    conn.Setup(grid, bulk);
    allWells.Setup(grid, bulk);
}
References OCP_FUNCNAME, Grid::Setup(), Bulk::Setup(), AllWells::Setup(), and BulkConn::Setup().
SetupFIMBulk()
void Reservoir::SetupFIMBulk (const bool & NRflag = false) inline
Setup FIMBulk.
Definition at line 188 of file Reservoir.hpp.
{ conn.SetupFIMBulk(bulk, NRflag); }
SetupFIMBulkBoundAIMs()
void Reservoir::SetupFIMBulkBoundAIMs () inline
Definition at line 190 of file Reservoir.hpp.
{ conn.SetupFIMBulkBoundAIMs(bulk); }
SetupWellBulk()
void Reservoir::SetupWellBulk () inline
Definition at line 85 of file Reservoir.hpp.
{ allWells.SetupWellBulk(bulk); }
ShowRes()
void Reservoir::ShowRes (const vector< OCP_DBL > & res) const
Definition at line 488 of file Reservoir.cpp.
{
    bulk.ShowRes(res);
    allWells.ShowRes(res, bulk);
}
UpdateLastStepAIM()
void Reservoir::UpdateLastStepAIM ()
Update value of last step for IMPEC.
Definition at line 622 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.UpdateLastStepIMPEC();
    bulk.UpdateLastStepAIM();
    conn.UpdateLastStep();
    allWells.UpdateLastBHP();
    allWells.UpdateLastDg();
}
References OCP_FUNCNAME, AllWells::UpdateLastDg(), BulkConn::UpdateLastStep(), and Bulk::UpdateLastStepIMPEC().
UpdateLastStepFIM()
void Reservoir::UpdateLastStepFIM ()
Update value of last step for FIM.
Definition at line 347 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.UpdateLastStepFIM();
    allWells.UpdateLastBHP();
}
References OCP_FUNCNAME, and Bulk::UpdateLastStepFIM().
UpdateLastStepIMPEC()
void Reservoir::UpdateLastStepIMPEC ()
Update value of last step for IMPEC.
Definition at line 212 of file Reservoir.cpp.
{
    OCP_FUNCNAME;
    bulk.UpdateLastStepIMPEC();
    conn.UpdateLastStep();
    // useless in IMPEC now
    // allWells.UpdateLastBHP();
    // allWells.UpdateLastDg();
}
References OCP_FUNCNAME, BulkConn::UpdateLastStep(), and Bulk::UpdateLastStepIMPEC().
UpdatePj()
void Reservoir::UpdatePj () inline
Definition at line 234 of file Reservoir.hpp.
{ bulk.UpdatePj(); }
Friends And Related Function Documentation
CriticalInfo
friend class CriticalInfo friend
Definition at line 34 of file Reservoir.hpp.
DetailInfo
friend class DetailInfo friend
Definition at line 35 of file Reservoir.hpp.
OCP_AIMc
friend class OCP_AIMc friend
Definition at line 42 of file Reservoir.hpp.
OCP_AIMs
friend class OCP_AIMs friend
Definition at line 40 of file Reservoir.hpp.
OCP_AIMt
friend class OCP_AIMt friend
Definition at line 41 of file Reservoir.hpp.
OCP_FIM
friend class OCP_FIM friend
Definition at line 39 of file Reservoir.hpp.
OCP_IMPEC
friend class OCP_IMPEC friend
Definition at line 38 of file Reservoir.hpp.
OCPControl
friend class OCPControl friend
Definition at line 32 of file Reservoir.hpp.
Solver
friend class Solver friend
Definition at line 43 of file Reservoir.hpp.
Summary
friend class Summary friend
Definition at line 33 of file Reservoir.hpp.
The documentation for this class was generated from the following files:
Reservoir.hpp
Reservoir.cpp