OpenCAEPoro: ParamWell Class Reference
ParamWell Class Reference
#include <ParamWell.hpp>
Public Member Functions
void Init ()
Initialize the inputting the params of wells.
void InitTime ()
Initialize the critical time.
void InputWELSPECS (ifstream &ifs)
void InputCOMPDAT (ifstream &ifs)
void InputWCONINJE (ifstream &ifs)
void InputWCONPROD (ifstream &ifs)
void InputTSTEP (ifstream &ifs)
void InputWELTARG (ifstream &ifs)
void InputWELLSTRE (ifstream &ifs)
void CheckParam (const bool &boModel) const
Check if wrong params are input.
void CheckPerf () const
Check if params of Perforation is wrong.
void CheckINJFluid () const
Public Attributes
vector< WellParam > well
Contains all the information of wells.
vector< OCP_DBL > criticalTime
Records the critical time given by users.
vector< Solvent > solSet
Sets of Solvent.
Detailed Description
ParamWell is an internal structure used to stores the information of wells from input files. It is an intermediate interface and independent of the main simulator. After all file inputting finishs, the params in it will pass to corresponding modules.
Definition at line 100 of file ParamWell.hpp.
Member Function Documentation
CheckINJFluid()
void ParamWell::CheckINJFluid () const
Definition at line 301 of file ParamWell.cpp.
{
    USI wellnum = well.size();
    USI len;
    for (USI w = 0; w < wellnum; w++) {
        len = well[w].optParam.size();
        for (USI i = 0; i < len; i++) {
            const WellOptParam& tmpOpt = well[w].optParam[i].opt;
            if (tmpOpt.type == "INJ") {
                if (tmpOpt.fluidType == "WAT" || tmpOpt.fluidType == "WATER") {
                } else if (tmpOpt.fluidType == "GAS") {
                } else {
                    OCP_ABORT("Wrong FluidType!");
                }
            }
        }
    }
}
CheckParam()
void ParamWell::CheckParam (const bool & boModel) const
Check if wrong params are input.
Definition at line 293 of file ParamWell.cpp.
{
    if (boModel) {
        CheckINJFluid();
    }
    CheckPerf();
}
References CheckPerf().
CheckPerf()
void ParamWell::CheckPerf () const
Check if params of Perforation is wrong.
Definition at line 320 of file ParamWell.cpp.
{
    USI wellnum = well.size();
    USI perfnum;
    for (USI w = 0; w < wellnum; w++) {
        perfnum = well[w].I_perf.size();
        if (well[w].J_perf.size() != perfnum) {
            OCP_ABORT("Wrong perforation size J_perf!");
        }
        if (well[w].K_perf.size() != perfnum) {
            OCP_ABORT("Wrong perforation size K_perf!");
        }
        if (well[w].diameter.size() != perfnum) {
            OCP_ABORT("Wrong perforation diameter size!");
        }
        if (well[w].WI.size() != perfnum) {
            OCP_ABORT("Wrong perforation WI size!");
        }
        if (well[w].kh.size() != perfnum) {
            OCP_ABORT("Wrong perforation kh size!");
        }
        if (well[w].skinFactor.size() != perfnum) {
            OCP_ABORT("Wrong perforation skinFactor size!");
        }
        if (well[w].direction.size() != perfnum) {
            OCP_ABORT("Wrong perforation direction size!");
        }
    }
}
References OCP_ABORT, and well.
Init()
void ParamWell::Init () inline
Initialize the inputting the params of wells.
Definition at line 108 of file ParamWell.hpp.
{ InitTime(); };
References InitTime().
InitTime()
void ParamWell::InitTime () inline
Initialize the critical time.
Definition at line 110 of file ParamWell.hpp.
{ criticalTime.push_back(0); };
References criticalTime.
InputCOMPDAT()
void ParamWell::InputCOMPDAT (ifstream & ifs)
Input the well keyword COMPDAT. COMPDAT contains the information of perforations of wells, for example the location, the trans or directions.
Definition at line 81 of file ParamWell.cpp.
{
    USI            num = well.size();
    vector<string> vbuf;
    while (ReadLine(ifs, vbuf)) {
        if (vbuf[0] == "/") break;
        DealDefault(vbuf);
        string src   = vbuf[0];
        int    pos   = src.find("*");
        bool   match = (pos != string::npos);
        if (match) {
            src.erase(pos);
        }
        bool tmp = false;
        for (USI w = 0; w < num; w++) {
            if (match)
                tmp = (well[w].name.substr(0, pos) == src);
            else
                tmp = (well[w].name == src);
            if (tmp) {
                USI k1 = stoi(vbuf[3]);
                USI k2 = stoi(vbuf[4]);
                for (USI k = k1; k <= k2; k++) {
                    if (vbuf[1] == "DEFAULT" || vbuf[2] == "DEFAULT") {
                        well[w].I_perf.push_back(well[w].I);
                        well[w].J_perf.push_back(well[w].J);
                    } else {
                        well[w].I_perf.push_back(stoi(vbuf[1]));
                        well[w].J_perf.push_back(stoi(vbuf[2]));
                    }
                    well[w].K_perf.push_back(k);
                    if (vbuf[5] != "DEFAULT")
                        well[w].WI.push_back(stod(vbuf[5]));
                    else
                        well[w].WI.push_back(-1.0);
                    if (vbuf[6] != "DEFAULT")
                        well[w].diameter.push_back(stod(vbuf[6]));
                    else
                        well[w].diameter.push_back(1.0);
                    if (vbuf[7] != "DEFAULT")
                        well[w].kh.push_back(stod(vbuf[7]));
                    else
                        well[w].kh.push_back(-1.0);
                    if (vbuf[8] != "DEFAULT")
                        well[w].skinFactor.push_back(stod(vbuf[8]));
                    else
                        well[w].skinFactor.push_back(0.0);
                    if (vbuf[9] != "DEFAULT")
                        well[w].direction.push_back(vbuf[9]);
                    else
                        well[w].direction.push_back("z");
                }
            }
        }
    }
    cout << "COMPDAT" << endl;
}
References DealDefault(), ReadLine(), and well.
InputTSTEP()
void ParamWell::InputTSTEP (ifstream & ifs)
Input the keyword: TSTEP. TSTEP is used to divide the simulation time and ususally the time point is critical, at which for example, the operation mode of well will change. So the params of solving equations could be adjusted correspondingly.
Definition at line 215 of file ParamWell.cpp.
{
    assert(criticalTime.size() > 0);
    vector<string> vbuf;
    while (ReadLine(ifs, vbuf)) {
        if (vbuf[0] == "/") break;
        DealDefault(vbuf);
        OCP_INT len = vbuf.size();
        for (OCP_INT i = 0; i < len - 1; i++) {
            OCP_DBL t = criticalTime.back() + stod(vbuf[i]);
            criticalTime.push_back(t);
        }
        if (vbuf.back() != "/") {
            OCP_DBL t = criticalTime.back() + stod(vbuf.back());
            criticalTime.push_back(t);
        }
    }
}
References criticalTime, DealDefault(), and ReadLine().
InputWCONINJE()
void ParamWell::InputWCONINJE (ifstream & ifs)
Input the well keyword WCONINJE. WCONINJE describes the initial operation mode of injection well.
Definition at line 149 of file ParamWell.cpp.
{
    assert(criticalTime.size() > 0);
    USI            d   = criticalTime.size() - 1;
    USI            num = well.size();
    vector<string> vbuf;
    while (ReadLine(ifs, vbuf)) {
        if (vbuf[0] == "/") break;
        DealDefault(vbuf);
        string src   = vbuf[0];
        int    pos   = src.find("*");
        bool   match = (pos != string::npos);
        if (match) {
            src.erase(pos);
        }
        if (match) {
            for (USI w = 0; w < num; w++) {
                if (well[w].name.substr(0, pos) == src) {
                    well[w].optParam.push_back(WellOptPair(d, "INJ", vbuf));
                }
            }
        } else {
            for (USI w = 0; w < num; w++) {
                if (well[w].name == src) {
                    well[w].optParam.push_back(WellOptPair(d, "INJ", vbuf));
                }
            }
        }
    }
    cout << "WCONINJE" << endl;
}
References criticalTime, DealDefault(), ReadLine(), and well.
InputWCONPROD()
void ParamWell::InputWCONPROD (ifstream & ifs)
Input the well keyword WCONPROD. WCONPROD describes the initial operation mode of production well.
Definition at line 184 of file ParamWell.cpp.
{
    assert(criticalTime.size() > 0);
    USI            d   = criticalTime.size() - 1;
    USI            num = well.size();
    vector<string> vbuf;
    while (ReadLine(ifs, vbuf)) {
        if (vbuf[0] == "/") break;
        DealDefault(vbuf);
        string src   = vbuf[0];
        int    pos   = src.find("*");
        bool   match = (pos != string::npos);
        if (match) {
            src.erase(pos);
        }
        if (match) {
            for (USI w = 0; w < num; w++)
                if (well[w].name.substr(0, pos) == src)
                    well[w].optParam.push_back(WellOptPair(d, "PROD", vbuf));
        } else {
            for (USI w = 0; w < num; w++)
                if (well[w].name == src)
                    well[w].optParam.push_back(WellOptPair(d, "PROD", vbuf));
        }
    }
    cout << "WCONPROD" << endl;
}
References criticalTime, DealDefault(), ReadLine(), and well.
InputWELLSTRE()
void ParamWell::InputWELLSTRE (ifstream & ifs)
Input well keyword: Solvent. It describes the molar fraction of components of fluid injected to reservoir from INJ.
Definition at line 282 of file ParamWell.cpp.
{
    vector<string> vbuf;
    while (ReadLine(ifs, vbuf)) {
        if (vbuf[0] == "/") break;
        solSet.push_back(Solvent(vbuf));
    }
    cout << "WELLSTRE" << endl;
}
References ReadLine(), and solSet.
InputWELSPECS()
void ParamWell::InputWELSPECS (ifstream & ifs)
Input the well keyword WELSPECS. WELSPECS defines wells including well name, well location, well depth and son on.
Definition at line 69 of file ParamWell.cpp.
{
    vector<string> vbuf;
    while (ReadLine(ifs, vbuf)) {
        if (vbuf[0] == "/") break;
        DealDefault(vbuf);
        well.push_back(WellParam(vbuf));
    }
    cout << "WELSPECS" << endl;
}
References DealDefault(), ReadLine(), and well.
InputWELTARG()
void ParamWell::InputWELTARG (ifstream & ifs)
Input the well keyword: WELTARG. WELTARG is used to change the opeartion mode of well anytime. For example, the oil production rate is changed from 1000 stb/day to 1500 stb/day at the 100th day.
Definition at line 236 of file ParamWell.cpp.
{
    assert(criticalTime.size() > 0);
    USI            d   = criticalTime.size() - 1;
    USI            num = well.size();
    vector<string> vbuf;
    while (ReadLine(ifs, vbuf)) {
        if (vbuf[0] == "/") break;
        DealDefault(vbuf);
        string src   = vbuf[0];
        int    pos   = src.find("*");
        bool   match = (pos != string::npos);
        if (match) {
            src.erase(pos);
        }
        bool tmp = false;
        for (USI w = 0; w < num; w++) {
            if (match)
                tmp = (well[w].name.substr(0, pos) == src);
            else
                tmp = (well[w].name == src);
            if (tmp) {
                WellOptPair tar = well[w].optParam.back();
                tar.d           = d;
                tar.opt.optMode = vbuf[1];
                OCP_DBL val     = stod(vbuf[2]);
                if (vbuf[1] == "BHP") {
                    if (tar.opt.type == "INJ")
                        tar.opt.maxBHP = val;
                    else
                        tar.opt.minBHP = val;
                } else {
                    tar.opt.maxRate = val;
                }
                well[w].optParam.push_back(tar);
            }
        }
    }
    cout << "WELTARG" << endl;
}
References criticalTime, DealDefault(), WellOptParam::maxBHP, WellOptParam::maxRate, WellOptParam::minBHP, WellOptParam::optMode, ReadLine(), WellOptParam::type, and well.
Member Data Documentation
criticalTime
vector<OCP_DBL> ParamWell::criticalTime
Records the critical time given by users.
Definition at line 104 of file ParamWell.hpp.
solSet
vector<Solvent> ParamWell::solSet
Sets of Solvent.
Definition at line 105 of file ParamWell.hpp.
well
vector<WellParam> ParamWell::well
Contains all the information of wells.
Definition at line 103 of file ParamWell.hpp.
The documentation for this class was generated from the following files:
ParamWell.hpp
ParamWell.cpp