OpenCAEPoro: DenseMat.hpp File Reference
DenseMat.hpp File Reference
Operations about small dense mat.
#include <algorithm>
#include <iomanip>
#include <iostream>
#include <string>
Functions
void dscal_ (const int *n, const double *alpha, double *x, const int *incx)
Scales a vector by a constant.
double ddot_ (const int *n, double *a, const int *inca, double *b, const int *incb)
Forms the dot product of two vectors.
int dcopy_ (const int *n, const double *src, const int *incx, double *dst, const int *incy)
Copies a vector, src, to a vector, dst.
int daxpy_ (const int *n, const double *alpha, const double *x, const int *incx, double *y, const int *incy)
Constant times a vector plus a vector.
double dnrm2_ (const int *n, double *x, const int *incx)
Computes the Euclidean norm of a vector.
double dasum_ (const int *n, double *x, const int *incx)
Computes the sum of the absolute values of a vector.
int idamax_ (const int *n, double *x, const int *incx)
Finds the index of element having max absolute value.
int dgemm_ (const char *transa, const char *transb, const int *m, const int *n, const int *k, const double *alpha, const double *A, const int *lda, const double *B, const int *ldb, const double *beta, double *C, const int *ldc)
Performs matrix-matrix operations C : = alpha * op(A) * op(B) + beta * C.
int dgesv_ (const int *n, const int *nrhs, double *A, const int *lda, int *ipiv, double *b, const int *ldb, int *info)
Computes the solution to system of linear equations A * X = B for general matrices.
int dsysv_ (const char *uplo, const int *n, const int *nrhs, double *A, const int *lda, int *ipiv, double *b, const int *ldb, double *work, const int *lwork, int *info)
Computes the solution to system of linear equations A * X = B for symm matrices.
int ssyevd_ (char *jobz, char *uplo, const int *n, float *A, const int *lda, float *w, float *work, const int *lwork, int *iwork, const int *liwork, int *info)
Computes the eigenvalues and, optionally, the leftand /or right eigenvectors for SY matrices.
void MinEigenSY (const int &N, float *A, float *w, float *work, const int &lwork)
Calculate the minimal eigenvalue for sysmetric matrix with mkl lapack.
void Dcopy (const int &N, double *dst, const double *src)
Calculate the minimal eigenvalue for sysmetric matrix with mkl lapack.
double Ddot (int n, double *a, double *b)
Dot product of two double vectors stored as pointers.
double Dnorm1 (const int &N, double *x)
Computes the L1-norm of a vector.
double Dnorm2 (const int &N, double *x)
Computes the L2-norm of a vector.
void Dscalar (const int &n, const double &alpha, double *x)
Scales a vector by a constant.
void Daxpy (const int &n, const double &alpha, const double *x, double *y)
Constant times a vector plus a vector.
void DaABpbC (const int &m, const int &n, const int &k, const double &alpha, const double *A, const double *B, const double &beta, double *C)
Computes C' = alpha B'A' + beta C', all matrices are column-major.
void myDABpC (const int &m, const int &n, const int &k, const double *A, const double *B, double *C)
void myDABpCp (const int &m, const int &n, const int &k, const double *A, const double *B, double *C, const int *flag, const int N)
void myDABpCp1 (const int &m, const int &n, const int &k, const double *A, const double *B, double *C, const int *flag, const int N)
void myDABpCp2 (const int &m, const int &n, const int &k, const double *A, const double *B, double *C, const int *flag, const int N)
void DaAxpby (const int &m, const int &n, const double &a, const double *A, const double *x, const double &b, double *y)
Computes y = a A x + b y.
void LUSolve (const int &nrhs, const int &N, double *A, double *b, int *pivot)
Calls dgesv to solve the linear system for general matrices.
void SYSSolve (const int &nrhs, const char *uplo, const int &N, double *A, double *b, int *pivot, double *work, const int &lwork)
Calls dsysy to solve the linear system for symm matrices.
template<typename T >
void PrintDX (const int &N, const T *x)
Prints a vector.
template<typename T >
bool CheckNan (const int &N, const T *x)
check NaN
Detailed Description
Operations about small dense mat.
Author
Shizhe Li
Date
Oct/24/2021
Copyright (C) 2021–present by the OpenCAEPoro team. All rights reserved.
Released under the terms of the GNU Lesser General Public License 3.0 or later.
Definition in file DenseMat.hpp.
Function Documentation
CheckNan()
template<typename T > bool CheckNan (const int & N, const T * x)
check NaN
Definition at line 132 of file DenseMat.hpp.
{
    for (int i = 0; i < N; i++) {
        if (!isfinite(x[i]) || isnan(x[i])) {
            return false;
        }
    }
    return true;
}
DaABpbC()
void DaABpbC (const int & m, const int & n, const int & k, const double & alpha, const double * A, const double * B, const double & beta, double * C)
Computes C' = alpha B'A' + beta C', all matrices are column-major.
Definition at line 76 of file DenseMat.cpp.
{
    /*  C' = alpha B'A' + beta C'
     *  A: m x k
     *  B: k x n
     *  C: m x n
     *  all column majored matrices, no tranpose
     *  A' in col-order in Fortran = A in row-order in C/Cpp
     */
    const char transa = 'N', transb = 'N';
    dgemm_(&transa, &transb, &n, &m, &k, &alpha, B, &n, A, &k, &beta, C, &n);
}
References dgemm_().
DaAxpby()
void DaAxpby (const int & m, const int & n, const double & a, const double * A, const double * x, const double & b, double * y)
Computes y = a A x + b y.
Definition at line 173 of file DenseMat.cpp.
{
    /*  y= aAx+by
     */
    for (int i = 0; i < m; i++) {
        y[i] = b * y[i];
        for (int j = 0; j < n; j++) {
            y[i] += a * A[i * n + j] * x[j];
        }
    }
}
Daxpy()
void Daxpy (const int & n, const double & alpha, const double * x, double * y)
Constant times a vector plus a vector.
Definition at line 69 of file DenseMat.cpp.
{
    // y= ax +y
    const int incx = 1, incy = 1;
    daxpy_(&n, &alpha, x, &incx, y, &incy);
}
References daxpy_().
Dcopy()
void Dcopy (const int & N, double * dst, const double * src)
Calculate the minimal eigenvalue for sysmetric matrix with mkl lapack.
Copy a double vector from src to dst.
Definition at line 37 of file DenseMat.cpp.
{
    const int incx = 1, incy = 1;
    dcopy_(&N, src, &incx, dst, &incy);
}
References dcopy_().
Ddot()
double Ddot (int n, double * a, double * b)
Dot product of two double vectors stored as pointers.
Definition at line 43 of file DenseMat.cpp.
{
    const int inca = 1, incb = 1;
    return ddot_(&n, a, &inca, b, &incb);
}
References ddot_().
Dnorm1()
double Dnorm1 (const int & N, double * x)
Computes the L1-norm of a vector.
Definition at line 50 of file DenseMat.cpp.
{
    const int incx = 1;
    return dasum_(&N, x, &incx);
}
References dasum_().
Dnorm2()
double Dnorm2 (const int & N, double * x)
Computes the L2-norm of a vector.
Definition at line 56 of file DenseMat.cpp.
{
    const int incx = 1;
    return dnrm2_(&N, x, &incx);
}
References dnrm2_().
Dscalar()
void Dscalar (const int & n, const double & alpha, double * x)
Scales a vector by a constant.
Definition at line 62 of file DenseMat.cpp.
{
    // x = a x
    const int incx = 1;
    dscal_(&n, &alpha, x, &incx);
}
References dscal_().
LUSolve()
void LUSolve (const int & nrhs, const int & N, double * A, double * b, int * pivot)
Calls dgesv to solve the linear system for general matrices.
Definition at line 186 of file DenseMat.cpp.
{
    int info;
    dgesv_(&N, &nrhs, A, &N, pivot, b, &N, &info);
    if (info < 0) {
        cout << "Wrong Input !" << endl;
    } else if (info > 0) {
        cout << "Singular Matrix !" << endl;
    }
}
References dgesv_().
MinEigenSY()
void MinEigenSY (const int & N, float * A, float * w, float * work, const int & lwork)
Calculate the minimal eigenvalue for sysmetric matrix with mkl lapack.
Definition at line 14 of file DenseMat.cpp.
{
    int info;
    int iwork[1] = { 0 };
    int liwork = 1;
    char uplo{ 'U' };
    char Nonly{ 'N' };
    ssyevd_(&Nonly, &uplo, &N, A, &N, w, work, &lwork, iwork, &liwork, &info);
    if (info > 0) {
        cout << "failed to compute eigenvalues!" << endl;
    }
}
References ssyevd_().
myDABpC()
void myDABpC (const int & m, const int & n, const int & k, const double * A, const double * B, double * C)
Definition at line 92 of file DenseMat.cpp.
{
    // C = AB + C
    // A: m*n  B:n*k  C:m*k
    // all matrix are row majored matrices
    for (int i = 0; i < m; i++) {
        for (int j = 0; j < k; j++) {
            for (int m = 0; m < n; m++) {
                C[i * k + j] += A[i * n + m] * B[m * k + j];
            }
        }
    }
}
myDABpCp()
void myDABpCp (const int & m, const int & n, const int & k, const double * A, const double * B, double * C, const int * flag, const int N)
Definition at line 107 of file DenseMat.cpp.
{
    for (int i = 0; i < m; i++) {
        for (int j = 0; j < k; j++) {
            for (int p = 0; p < 3; p++) {
                if (flag[p] != 0)
                    C[i * k + j] += A[i * n + p] * B[p * k + j];
            }
            for (int p = 0; p < 2; p++) {
                if (flag[p] != 0) {
                    for (int m = 0; m < N; m++) {
                        C[i * k + j] += A[i * n + 3 + p * (N + 1) + m] * B[(3 + p * (N + 1) + m) * k + j];
                    }
                }
            }
        }
    }
}
myDABpCp1()
void myDABpCp1 (const int & m, const int & n, const int & k, const double * A, const double * B, double * C, const int * flag, const int N)
Definition at line 126 of file DenseMat.cpp.
{
    for (int i = 0; i < m; i++) {
        for (int j = 0; j < k; j++) {
            int s = 0;
            for (int p = 0; p < 3; p++) {
                if (flag[p] != 0) {
                    C[i * k + j] += A[i * n + p] * B[s * k + j];
                    s++;
                }
            }
            for (int p = 0; p < 2; p++) {
                if (flag[p] != 0) {
                    for (int m = 0; m < N; m++) {
                        C[i * k + j] += A[i * n + 3 + p * (N + 1) + m] * B[s * k + j];
                        s++;
                    }
                }
            }
        }
    }
}
myDABpCp2()
void myDABpCp2 (const int & m, const int & n, const int & k, const double * A, const double * B, double * C, const int * flag, const int N)
Definition at line 150 of file DenseMat.cpp.
{
    for (int i = 0; i < m; i++) {
        for (int j = 0; j < k; j++) {
            int s = 0;
            for (int p = 0; p < 3; p++) {
                if (flag[p] != 0) {
                    C[i * k + j] += A[i * n + s] * B[p * k + j];
                    s++;
                }
            }
            for (int p = 0; p < 2; p++) {
                if (flag[p] != 0) {
                    for (int m = 0; m < N; m++) {
                        C[i * k + j] += A[i * n + s] * B[(3 + p * (N + 1) + m) * k + j];
                        s++;
                    }
                }
            }
        }
    }
}
PrintDX()
template<typename T > void PrintDX (const int & N, const T * x)
Prints a vector.
Definition at line 122 of file DenseMat.hpp.
{
    for (int i = 0; i < N; i++) {
        cout << i << "   " << setprecision(16) << x[i] << endl;
    }
    cout << endl;
}
SYSSolve()
void SYSSolve (const int & nrhs, const char * uplo, const int & N, double * A, double * b, int * pivot, double * work, const int & lwork)
Calls dsysy to solve the linear system for symm matrices.
Definition at line 199 of file DenseMat.cpp.
{
    int    info;
    dsysv_(uplo, &N, &nrhs, A, &N, pivot, b, &N, work, &lwork, &info);
    if (info < 0) {
        cout << "Wrong Input !" << endl;
    } else if (info > 0) {
        cout << "Singular Matrix !" << endl;
    }
}
References dsysv_().