OpenCAEPoro: DenseMat.cpp File Reference
DenseMat.cpp File Reference
Dense matrix-vector operations.
#include "DenseMat.hpp"
Functions
void MinEigenSY (const int &N, float *A, float *w, float *work, const int &lwork)
Calculate the minimal eigenvalue for sysmetric matrix with mkl lapack.
void Dcopy (const int &N, double *dst, const double *src)
Calculate the minimal eigenvalue for sysmetric matrix with mkl lapack.
double Ddot (int n, double *a, double *b)
Dot product of two double vectors stored as pointers.
double Dnorm1 (const int &N, double *x)
Computes the L1-norm of a vector.
double Dnorm2 (const int &N, double *x)
Computes the L2-norm of a vector.
void Dscalar (const int &n, const double &alpha, double *x)
Scales a vector by a constant.
void Daxpy (const int &n, const double &alpha, const double *x, double *y)
Constant times a vector plus a vector.
void DaABpbC (const int &m, const int &n, const int &k, const double &alpha, const double *A, const double *B, const double &beta, double *C)
Computes C' = alpha B'A' + beta C', all matrices are column-major.
void DaAxpby (const int &m, const int &n, const double &a, const double *A, const double *x, const double &b, double *y)
Computes y = a A x + b y.
void LUSolve (const int &nrhs, const int &N, double *A, double *b, int *pivot)
Calls dgesv to solve the linear system for general matrices.
void SYSSolve (const int &nrhs, const char *uplo, const int &N, double *A, double *b, int *pivot, double *work, const int &lwork)
Calls dsysy to solve the linear system for symm matrices.
Detailed Description
Dense matrix-vector operations.
Author
Shizhe Li
Date
Oct/21/2021
Copyright (C) 2021–present by the OpenCAEPoro team. All rights reserved.
Released under the terms of the GNU Lesser General Public License 3.0 or later.
Definition in file DenseMat.cpp.
Function Documentation
DaABpbC()
void DaABpbC (const int & m, const int & n, const int & k, const double & alpha, const double * A, const double * B, const double & beta, double * C)
Computes C' = alpha B'A' + beta C', all matrices are column-major.
Definition at line 76 of file DenseMat.cpp.
{
    /*  C' = alpha B'A' + beta C'
     *  A: m x k
     *  B: k x n
     *  C: m x n
     *  all column majored matrices, no tranpose
     */
    const char transa = 'N', transb = 'N';
    dgemm_(&transa, &transb, &n, &m, &k, &alpha, B, &n, A, &k, &beta, C, &n);
}
References dgemm_().
DaAxpby()
void DaAxpby (const int & m, const int & n, const double & a, const double * A, const double * x, const double & b, double * y)
Computes y = a A x + b y.
Definition at line 90 of file DenseMat.cpp.
{
    /*  y= aAx+by
     */
    for (int i = 0; i < m; i++) {
        y[i] = b * y[i];
        for (int j = 0; j < n; j++) {
            y[i] += a * A[i * n + j] * x[j];
        }
    }
}
Daxpy()
void Daxpy (const int & n, const double & alpha, const double * x, double * y)
Constant times a vector plus a vector.
Definition at line 69 of file DenseMat.cpp.
{
    // y= ax +y
    const int incx = 1, incy = 1;
    daxpy_(&n, &alpha, x, &incx, y, &incy);
}
References daxpy_().
Dcopy()
void Dcopy (const int & N, double * dst, const double * src)
Calculate the minimal eigenvalue for sysmetric matrix with mkl lapack.
Copy a double vector from src to dst.
Definition at line 37 of file DenseMat.cpp.
{
    const int incx = 1, incy = 1;
    dcopy_(&N, src, &incx, dst, &incy);
}
References dcopy_().
Ddot()
double Ddot (int n, double * a, double * b)
Dot product of two double vectors stored as pointers.
Definition at line 43 of file DenseMat.cpp.
{
    const int inca = 1, incb = 1;
    return ddot_(&n, a, &inca, b, &incb);
}
References ddot_().
Dnorm1()
double Dnorm1 (const int & N, double * x)
Computes the L1-norm of a vector.
Definition at line 50 of file DenseMat.cpp.
{
    const int incx = 1;
    return dasum_(&N, x, &incx);
}
References dasum_().
Dnorm2()
double Dnorm2 (const int & N, double * x)
Computes the L2-norm of a vector.
Definition at line 56 of file DenseMat.cpp.
{
    const int incx = 1;
    return dnrm2_(&N, x, &incx);
}
References dnrm2_().
Dscalar()
void Dscalar (const int & n, const double & alpha, double * x)
Scales a vector by a constant.
Definition at line 62 of file DenseMat.cpp.
{
    // x = a x
    const int incx = 1;
    dscal_(&n, &alpha, x, &incx);
}
References dscal_().
LUSolve()
void LUSolve (const int & nrhs, const int & N, double * A, double * b, int * pivot)
Calls dgesv to solve the linear system for general matrices.
Definition at line 103 of file DenseMat.cpp.
{
    int info;
    dgesv_(&N, &nrhs, A, &N, pivot, b, &N, &info);
    if (info < 0) {
        cout << "Wrong Input !" << endl;
    } else if (info > 0) {
        cout << "Singular Matrix !" << endl;
    }
}
References dgesv_().
MinEigenSY()
void MinEigenSY (const int & N, float * A, float * w, float * work, const int & lwork)
Calculate the minimal eigenvalue for sysmetric matrix with mkl lapack.
Definition at line 14 of file DenseMat.cpp.
{
    int info;
    int iwork[1] = { 0 };
    int liwork = 1;
    char uplo{ 'U' };
    char Nonly{ 'N' };
    ssyevd_(&Nonly, &uplo, &N, A, &N, w, work, &lwork, iwork, &liwork, &info);
    if (info > 0) {
        cout << "failed to compute eigenvalues!" << endl;
    }
}
References ssyevd_().
SYSSolve()
void SYSSolve (const int & nrhs, const char * uplo, const int & N, double * A, double * b, int * pivot, double * work, const int & lwork)
Calls dsysy to solve the linear system for symm matrices.
Definition at line 116 of file DenseMat.cpp.
{
    int    info;
    dsysv_(uplo, &N, &nrhs, A, &N, pivot, b, &N, work, &lwork, &info);
    if (info < 0) {
        cout << "Wrong Input !" << endl;
    } else if (info > 0) {
        cout << "Singular Matrix !" << endl;
    }
}
References dsysv_().